import { claim, concept, createDevelopmentFamily, linkSourcesToClaims, source, type CaseSpec, type DevelopmentServiceContract } from "./batch-helpers";

const TESTS = "source.niddk.celiac-tests.2021";
const DIAGNOSIS = "source.niddk.celiac-diagnosis.2020";
const TREATMENT = "source.niddk.celiac-treatment.2020";
const ACG = "source.acg.celiac-patient-education.2026";
export const CELIAC_SERVICE_CONTRACTS: DevelopmentServiceContract[] = [{ serviceId: "service.upper_endoscopy_duodenal_biopsy", allowedRouteIds: ["route.upper_endoscopy_duodenal_biopsy.outsourced"], delivery: "new_external_contract_required" }];
export const CELIAC_CLAIMS = [
  claim({ id: "claim.celiac.initial-serology", statement: "While a patient is eating gluten, tTG-IgA together with total-IgA context is a usual initial serologic assessment for suspected celiac disease.", sourceIds: [TESTS, DIAGNOSIS], evidenceCategory: "evaluation", certainty: "high", limitation: "IgA deficiency changes test selection; serology is not presented as universally definitive.", applicablePopulation: "Adults with compatible symptoms who remain on gluten during diagnostic evaluation.", lastCheckedOn: "2026-09-09" }),
  claim({ id: "claim.celiac.adult-biopsy", statement: "In a usual adult pathway, positive compatible serology leads to upper endoscopy with duodenal biopsies for diagnostic confirmation.", sourceIds: [TESTS, DIAGNOSIS], evidenceCategory: "evaluation", certainty: "high", limitation: "This does not assert that every adult in every setting must undergo biopsy.", applicablePopulation: "Adults with positive celiac serology and adequate total IgA in a routine diagnostic pathway.", lastCheckedOn: "2026-09-09" }),
  claim({ id: "claim.celiac.gluten-free-treatment", statement: "Confirmed celiac disease is treated with a gluten-free diet, supported by a dietitian with relevant expertise.", sourceIds: [TREATMENT, ACG], evidenceCategory: "management", certainty: "high", limitation: "No exact response interval, supplement regimen, or gluten-challenge protocol is taught.", applicablePopulation: "Adults with celiac disease confirmed in the scoped pathway.", lastCheckedOn: "2026-09-09" }),
  claim({ id: "claim.celiac.gluten-testing-boundary", statement: "Starting gluten avoidance before diagnostic testing can alter serologic and biopsy results.", sourceIds: [TESTS, DIAGNOSIS, ACG], evidenceCategory: "safety_boundary", certainty: "high", limitation: "The content does not prescribe a gluten challenge.", applicablePopulation: "People undergoing evaluation for possible celiac disease.", lastCheckedOn: "2026-09-09" }),
  claim({ id: "claim.celiac.igg-tests-in-iga-deficiency", statement: "IgG-based celiac serology has a limited diagnostic role when IgA deficiency makes IgA-based tests unreliable.", sourceIds: [TESTS], evidenceCategory: "evaluation", certainty: "high", limitation: "This does not make an IgG panel the preferred routine first test before total IgA context is known.", applicablePopulation: "People evaluated for celiac disease when IgA deficiency is present or suspected.", lastCheckedOn: "2026-09-09" }),
  claim({ id: "claim.celiac.hla-susceptibility-not-active-disease", statement: "HLA-DQ2 and HLA-DQ8 typing addresses genetic susceptibility and does not by itself establish active celiac disease.", sourceIds: [TESTS], evidenceCategory: "evaluation", certainty: "high", limitation: "This claim does not specify test performance or every clinical use of HLA typing.", applicablePopulation: "People undergoing evaluation for possible celiac disease.", lastCheckedOn: "2026-09-09" }),
];
const gov = (id: string, title: string, year: number, reviewed: string, url: string, assessment: string) => source({ id, title, completeCitation: `National Institute of Diabetes and Digestive and Kidney Diseases. ${title}. Reviewed ${reviewed}.`, organizationOrJournal: "NIDDK", authors: ["National Institute of Diabetes and Digestive and Kidney Diseases"], publicationYear: year, doi: null, pmid: null, officialUrl: url, accessedOn: "2026-09-09", sourceClass: "government_guidance", licenseLabel: "United States government work; NIDDK reuse conditions apply", reuseStatus: "public_domain_conditions_apply", reuseNotes: "Original factual synthesis only; third-party materials and agency marks excluded.", authorityAssessment: assessment, usageRole: "evidence" as const });
export const CELIAC_SOURCES = linkSourcesToClaims([
  gov(TESTS, "Celiac Disease Tests", 2021, "February 2021", "https://www.niddk.nih.gov/health-information/professionals/clinical-tools-patient-management/digestive-diseases/celiac-disease-health-care-professionals?dkrd=www2.niddk.nih.gov", "Federal professional guidance directly checked for initial serology, total IgA context, gluten exposure, and usual biopsy follow-up."),
  gov(DIAGNOSIS, "Diagnosis of Celiac Disease", 2020, "October 2020", "https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/diagnosis", "Federal patient guidance directly checked for blood testing, small-intestinal biopsy, and the effect of gluten avoidance on results."),
  gov(TREATMENT, "Treatment for Celiac Disease", 2020, "October 2020", "https://www.niddk.nih.gov/health-information/digestive-diseases/celiac-disease/treatment", "Federal patient guidance directly checked for gluten-free treatment and dietitian support."),
  source({ id: ACG, title: "Celiac Disease", completeCitation: "American College of Gastroenterology. Celiac Disease. Original authors Connor G. Loftus and Joseph A. Murray; updated by Patrick McCabe (2021) and Claire Jansson-Knodell (April 2026).", organizationOrJournal: "American College of Gastroenterology patient education", authors: ["Connor G. Loftus", "Joseph A. Murray", "Patrick McCabe", "Claire Jansson-Knodell"], publicationYear: 2026, doi: null, pmid: null, officialUrl: "https://gi.org/topics/celiac-disease/", accessedOn: "2026-09-09", sourceClass: "open_educational_resource", licenseLabel: "Copyrighted American College of Gastroenterology patient education", reuseStatus: "copyrighted_targeted_verification_only", reuseNotes: "Citation and bounded factual verification only; no protected wording, lists, tables, or images reproduced.", authorityAssessment: "Current society patient education used only to cross-check gluten-before-testing and dietitian-supported treatment; not a substitute for the full guideline.", usageRole: "cross_check" }),
], CELIAC_CLAIMS);

const scenarios = [
  ["chronic-diarrhea", 29, "I have persistent diarrhea and bloating.", "has months of loose stools, bloating, and fatigue. They are eating gluten and have not started a restrictive diet."],
  ["iron-deficiency-symptoms", 42, "I have bloating and recently documented low iron stores.", "has persistent bloating and documented low iron stores on a recent blood test, prompting consideration of celiac disease. They continue to eat gluten."],
  ["weight-loss-discomfort", 51, "I have chronic abdominal discomfort and loose stools.", "has chronic abdominal discomfort, loose stools, and unintentional weight loss without acute illness. They remain on a gluten-containing diet."],
  ["family-history", 36, "I have persistent bloating and diarrhea.", "has prolonged bloating and diarrhea plus a first-degree relative with celiac disease. They have continued gluten during the evaluation."],
] as const;
const cases: CaseSpec[] = scenarios.map(([slug, age, complaint, story], index) => {
  const n = index + 1;
  const serology = "Serology returns positive for tTG-IgA, and total IgA is adequate.";
  const pathology = "Upper endoscopy with properly obtained duodenal biopsies returns pathology compatible with celiac disease in this clinical and serologic context.";
  return { id: `case.celiac.${slug}`, displayName: "Persistent digestive symptoms", chiefComplaint: complaint, presentation: `{patientName} ${story}`, ageYears: [age, age + 4], sexLabels: ["Female", "Male"], stage: 2, nodes: [
    { conceptId: "concept.celiac.initial-serology", stem: "Which initial laboratory approach best evaluates the suspected diagnosis while this patient is eating gluten?", choices: [
      { id: `ttg_total_iga_${n}`, label: "Order tTG-IgA with a total IgA measurement", isCorrect: true, serviceId: "service.basic_labs", rationale: "This pairs usual initial serology with the IgA context needed to interpret it." },
      { id: `igg_celiac_${n}`, label: "Order tTG-IgG with deamidated gliadin peptide IgG", serviceId: "service.basic_labs", rationale: "An IgG-based celiac panel is more useful when IgA deficiency is present; this patient has not yet had total IgA assessed." },
      { id: `hla_${n}`, label: "Order HLA-DQ2 and HLA-DQ8 typing", serviceId: "service.basic_labs", rationale: "HLA testing addresses genetic compatibility but does not establish active celiac disease as the usual initial serology does." },
      { id: `wheat_ige_${n}`, label: "Order wheat-specific IgE with total IgE", serviceId: "service.basic_labs", rationale: "This does not provide the targeted celiac serologic assessment needed for the current diagnostic question." },
    ], explanation: "tTG-IgA with total-IgA context is a usual initial serologic approach while the patient is eating gluten. Total IgA matters because deficiency can undermine IgA-based testing, and starting gluten avoidance before testing can change results.", claimIds: ["claim.celiac.initial-serology", "claim.celiac.gluten-testing-boundary", "claim.celiac.igg-tests-in-iga-deficiency", "claim.celiac.hla-susceptibility-not-active-disease"], gate: { id: `gate.celiac.serology.${n}`, serviceId: "service.basic_labs", pendingLabel: "Celiac serology pending", resultNarrative: serology, routeIds: ["route.basic_labs.outsourced", "route.basic_labs.phlebotomy_sendout"] } },
    { conceptId: "concept.celiac.duodenal-biopsy-confirmation", currentUpdate: serology, stem: "What is the usual next diagnostic step for this adult in the current pathway?", choices: [
      { id: `endoscopy_biopsy_${n}`, label: "Arrange upper endoscopy with duodenal biopsies", isCorrect: true, serviceId: "service.upper_endoscopy_duodenal_biopsy", rationale: "This is the usual tissue-confirmation step after compatible positive serology in an adult." },
      { id: `repeat_panel_${n}`, label: "Repeat the same celiac serology", serviceId: "service.basic_labs", rationale: "Repeating the same positive test does not provide the usual histologic confirmation." },
      { id: `colonoscopy_${n}`, label: "Arrange colonoscopy with random colonic biopsies", serviceId: "service.colonoscopy", rationale: "The target tissue for this celiac confirmation question is duodenal mucosa." },
      { id: `diagnose_serology_${n}`, label: "Record celiac disease from the serology result", rationale: "The scoped routine adult pathway proceeds to biopsy rather than treating serology as automatically definitive." },
    ], explanation: "In this routine adult pathway, compatible positive serology with adequate IgA is followed by upper endoscopy with duodenal biopsies. This provides histologic evidence interpreted with the clinical and serologic findings; selected alternative pathways may apply in other settings.", claimIds: ["claim.celiac.adult-biopsy"], gate: { id: `gate.celiac.biopsy.${n}`, serviceId: "service.upper_endoscopy_duodenal_biopsy", pendingLabel: "Upper endoscopy and duodenal biopsy pending", resultNarrative: pathology, routeIds: ["route.upper_endoscopy_duodenal_biopsy.outsourced"] } },
    { conceptId: "concept.celiac.gluten-free-treatment", currentUpdate: pathology, stem: "Which long-term treatment plan best follows from the completed workup?", choices: [
      { id: `gfd_dietitian_${n}`, label: "Gluten-free diet with dietitian guidance", isCorrect: true, rationale: "Dietary gluten exclusion with expert nutrition support is the central treatment." },
      { id: `lactose_only_${n}`, label: "Lactose-free diet with dietitian guidance", rationale: "Lactose restriction does not replace gluten exclusion for confirmed celiac disease." },
      { id: `low_fodmap_${n}`, label: "Low-FODMAP diet with dietitian guidance", rationale: "A low-FODMAP plan does not necessarily exclude gluten and does not ensure the disease-directed restriction required for confirmed celiac disease." },
      { id: `low_fat_${n}`, label: "Low-fat diet with dietitian guidance", rationale: "A low-fat plan does not necessarily exclude gluten and does not ensure the disease-directed restriction required for confirmed celiac disease." },
    ], explanation: "Confirmed celiac disease is treated with a gluten-free diet. A dietitian with relevant expertise helps the patient implement a nutritionally appropriate plan.", claimIds: ["claim.celiac.gluten-free-treatment"] },
  ] };
});
export const CELIAC_CONCEPTS = [
  concept({ id: "concept.celiac.initial-serology", educationalTier: 0, displayName: "Initial serology for suspected celiac disease", learningObjective: "Select tTG-IgA with total-IgA context as a usual initial serologic assessment while a patient with compatible symptoms continues eating gluten.", earliestFacilityStage: 2, conceptType: "workup", evidenceClaimIds: ["claim.celiac.initial-serology", "claim.celiac.gluten-testing-boundary", "claim.celiac.igg-tests-in-iga-deficiency", "claim.celiac.hla-susceptibility-not-active-disease"] }),
  concept({ id: "concept.celiac.duodenal-biopsy-confirmation", educationalTier: 1, displayName: "Usual adult duodenal-biopsy confirmation", learningObjective: "Select upper endoscopy with duodenal biopsies as the usual confirmation step for an adult with compatible positive celiac serology and adequate IgA.", earliestFacilityStage: 2, conceptType: "workup", evidenceClaimIds: ["claim.celiac.adult-biopsy"] }),
  concept({ id: "concept.celiac.gluten-free-treatment", educationalTier: 0, displayName: "Dietitian-supported gluten-free treatment", learningObjective: "Recommend a gluten-free diet with dietitian support after celiac disease is confirmed in the completed diagnostic pathway.", earliestFacilityStage: 2, conceptType: "management", evidenceClaimIds: ["claim.celiac.gluten-free-treatment"] }),
];
const family = createDevelopmentFamily({ concepts: CELIAC_CONCEPTS, cases, sourceLabels: ["NIDDK celiac testing, diagnosis, and treatment guidance (2020-2021)", "ACG Celiac Disease patient education (updated 2026; targeted verification only)"] });
export const CELIAC_TESTED_CONCEPTS = family.testedConcepts;
export const CELIAC_QUESTIONS = family.questions;
export const CELIAC_CASES = family.cases;
export const CELIAC_CASE_REVIEWS = family.caseReviews;




