import { CELIAC_CASE_REVIEWS, CELIAC_CASES, CELIAC_CLAIMS, CELIAC_CONCEPTS, CELIAC_QUESTIONS, CELIAC_SERVICE_CONTRACTS, CELIAC_SOURCES, CELIAC_TESTED_CONCEPTS } from "./celiac";
import { COLORECTAL_CASE_REVIEWS, COLORECTAL_CASES, COLORECTAL_CLAIMS, COLORECTAL_CONCEPTS, COLORECTAL_QUESTIONS, COLORECTAL_SERVICE_CONTRACTS, COLORECTAL_SOURCES, COLORECTAL_TESTED_CONCEPTS } from "./colorectal";
import { GALLSTONE_CASE_REVIEWS, GALLSTONE_CASES, GALLSTONE_CLAIMS, GALLSTONE_CONCEPTS, GALLSTONE_QUESTIONS, GALLSTONE_SOURCES, GALLSTONE_TESTED_CONCEPTS } from "./gallstones";
import { IRON_DEFICIENCY_CASE_REVIEWS, IRON_DEFICIENCY_CASES, IRON_DEFICIENCY_CLAIMS, IRON_DEFICIENCY_CONCEPTS, IRON_DEFICIENCY_QUESTIONS, IRON_DEFICIENCY_SOURCES, IRON_DEFICIENCY_TESTED_CONCEPTS } from "./iron-deficiency";
import { NEPHROLITHIASIS_CASE_REVIEWS, NEPHROLITHIASIS_CASES, NEPHROLITHIASIS_CLAIMS, NEPHROLITHIASIS_CONCEPTS, NEPHROLITHIASIS_QUESTIONS, NEPHROLITHIASIS_SOURCES, NEPHROLITHIASIS_TESTED_CONCEPTS } from "./nephrolithiasis";
import { SOFT_TISSUE_MASS_CASE_REVIEWS, SOFT_TISSUE_MASS_CASES, SOFT_TISSUE_MASS_CLAIMS, SOFT_TISSUE_MASS_CONCEPTS, SOFT_TISSUE_MASS_QUESTIONS, SOFT_TISSUE_MASS_SERVICE_CONTRACTS, SOFT_TISSUE_MASS_SOURCES, SOFT_TISSUE_MASS_TESTED_CONCEPTS } from "./soft-tissue-mass";
import type { DevelopmentServiceContract } from "./batch-helpers";

export const NEW_BATCH_AUTHORING_CONCEPTS = [...GALLSTONE_CONCEPTS, ...NEPHROLITHIASIS_CONCEPTS, ...CELIAC_CONCEPTS, ...COLORECTAL_CONCEPTS, ...IRON_DEFICIENCY_CONCEPTS, ...SOFT_TISSUE_MASS_CONCEPTS];
export const NEW_BATCH_CONCEPTS = [...GALLSTONE_TESTED_CONCEPTS, ...NEPHROLITHIASIS_TESTED_CONCEPTS, ...CELIAC_TESTED_CONCEPTS, ...COLORECTAL_TESTED_CONCEPTS, ...IRON_DEFICIENCY_TESTED_CONCEPTS, ...SOFT_TISSUE_MASS_TESTED_CONCEPTS];
export const NEW_BATCH_QUESTIONS = [...GALLSTONE_QUESTIONS, ...NEPHROLITHIASIS_QUESTIONS, ...CELIAC_QUESTIONS, ...COLORECTAL_QUESTIONS, ...IRON_DEFICIENCY_QUESTIONS, ...SOFT_TISSUE_MASS_QUESTIONS];
export const NEW_BATCH_CASES = [...GALLSTONE_CASES, ...NEPHROLITHIASIS_CASES, ...CELIAC_CASES, ...COLORECTAL_CASES, ...IRON_DEFICIENCY_CASES, ...SOFT_TISSUE_MASS_CASES];
export const NEW_BATCH_CASE_REVIEWS = [...GALLSTONE_CASE_REVIEWS, ...NEPHROLITHIASIS_CASE_REVIEWS, ...CELIAC_CASE_REVIEWS, ...COLORECTAL_CASE_REVIEWS, ...IRON_DEFICIENCY_CASE_REVIEWS, ...SOFT_TISSUE_MASS_CASE_REVIEWS];
export const NEW_BATCH_CLAIMS = [...GALLSTONE_CLAIMS, ...NEPHROLITHIASIS_CLAIMS, ...CELIAC_CLAIMS, ...COLORECTAL_CLAIMS, ...IRON_DEFICIENCY_CLAIMS, ...SOFT_TISSUE_MASS_CLAIMS];
export const NEW_BATCH_SOURCES = [...GALLSTONE_SOURCES, ...NEPHROLITHIASIS_SOURCES, ...CELIAC_SOURCES, ...COLORECTAL_SOURCES, ...IRON_DEFICIENCY_SOURCES, ...SOFT_TISSUE_MASS_SOURCES];
export const NEW_BATCH_SERVICE_CONTRACTS: DevelopmentServiceContract[] = [
  { serviceId: "service.ultrasound", allowedRouteIds: ["route.ultrasound.outsourced", "route.ultrasound.in_house"], delivery: "existing_balance_contract" },
  { serviceId: "service.ct", allowedRouteIds: ["route.ct.outsourced", "route.ct.in_house"], delivery: "existing_balance_contract" },
  { serviceId: "service.basic_labs", allowedRouteIds: ["route.basic_labs.outsourced", "route.basic_labs.phlebotomy_sendout"], delivery: "existing_balance_contract" },
  ...CELIAC_SERVICE_CONTRACTS,
  ...COLORECTAL_SERVICE_CONTRACTS,
  ...SOFT_TISSUE_MASS_SERVICE_CONTRACTS,
];

