import { buildFamily } from "./family-builder"; import { variants } from "./spec-utils"; import { REMAINING_SOURCES as S } from "./source-catalog-remaining14";
const OSA="claim.gs028d.osa.validated-screen", MH="claim.gs028d.mh.trigger-free-plan";
export const ANESTHESIA_FAMILY=buildFamily({slug:"anesthesia",label:"Preanesthetic planning",sources:[S.osa,S.mh,S.mhCross],claims:[
 {id:OSA,statement:"Validated preoperative screening can identify adults at increased probability of obstructive sleep apnoea for perioperative communication, but screening does not establish the diagnosis.",sourceIds:[S.osa.id],category:"evaluation",certainty:"moderate",limitation:"No proprietary questionnaire, item wording, score cutoff, or guaranteed outcome benefit is reproduced.",population:"Adults undergoing preoperative assessment."},
 {id:MH,statement:"A patient with known or credibly documented malignant-hyperthermia susceptibility requires advance planning for trigger-free anaesthesia in a facility prepared to manage malignant hyperthermia.",sourceIds:[S.mh.id,S.mhCross.id],category:"management",certainty:"low",limitation:"Evidence relies substantially on expert opinion and case reports; no clinic anaesthetic, crisis algorithm, or dantrolene dose is taught.",population:"Patients with known or credibly documented malignant-hyperthermia susceptibility."}],concepts:[
 {id:"concept.preoperative-osa.validated-risk-screening",displayName:"Screen preoperatively for OSA risk",learningObjective:"Use a validated risk screen and communicate increased OSA probability without treating the screen as a diagnosis.",stage:0,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[OSA],variants:variants([
  {slug:"snoring-surgery",complaint:"Surgery sleep screening",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, is preparing for elective abdominal surgery and reports loud snoring and witnessed breathing pauses without a prior sleep-study diagnosis.",stem:"What is the appropriate next preoperative step?",correct:["Use validated OSA screening","A validated screen can identify increased probability for perioperative planning without making a diagnosis."],wrong:[["Diagnose OSA from snoring alone","Symptoms alone do not establish the diagnosis."],["Cancel surgery automatically","A risk screen informs planning rather than mandating cancellation."],["Ignore sleep symptoms","Potential OSA should be communicated during preanesthetic assessment."]],explanation:"Use a validated screen, communicate the risk category, and keep screening distinct from diagnosis.",claims:[OSA],ageYears:[44,63],sexLabels:["Female","Male"]},
  {slug:"daytime-sleepiness",complaint:"Anesthesia risk visit",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, reports daytime sleepiness and observed nocturnal breathing interruptions before planned hernia repair but has never undergone diagnostic testing.",stem:"Which statement best describes the role of preoperative OSA screening here?",correct:["It estimates risk for perioperative planning","A validated screen identifies suspected OSA and supports communication with anesthesia."],wrong:[["It confirms OSA definitively","Screening does not replace diagnostic evaluation."],["It selects an anesthetic drug by itself","The result informs a broader individualized plan."],["It proves postoperative complications will occur","A risk screen does not predict an event with certainty."]],explanation:"The screening result is a risk signal for planning, not a diagnosis or deterministic outcome forecast.",claims:[OSA],ageYears:[37,58],sexLabels:["Female","Male"]},
  {slug:"prior-high-risk-screen",complaint:"Screen result review",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, brings a completed validated preoperative OSA screen reported as increased risk before colon surgery. No formal sleep diagnosis is documented.",stem:"How should this result be used?",correct:["Share OSA risk with anesthesia","The result supports perioperative risk planning while remaining a screening result."],wrong:[["Record confirmed OSA","The screen does not establish the diagnosis."],["Disregard the result without a sleep study","The result remains relevant to preanesthetic planning."],["Promise a complication-free course","Screening cannot guarantee an outcome."]],explanation:"Document and communicate increased risk while keeping screening and diagnosis separate.",claims:[OSA],ageYears:[51,70],sexLabels:["Female","Male"]},
  {slug:"validated-not-impression",complaint:"Preop sleep concern",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, has several possible OSA features before major surgery, and the clinic note currently records only an informal impression.",stem:"Which approach provides the most defensible preoperative risk classification?",correct:["Use validated OSA screening","A validated instrument is preferred to an undocumented informal impression."],wrong:[["Use age alone","One demographic feature is not a validated multivariable screen."],["Use body weight alone","Body size alone does not replace validated assessment."],["Assign a diagnosis from appearance","Visual impression cannot diagnose OSA."]],explanation:"A validated screen provides a consistent risk classification while remaining distinct from a diagnostic study.",claims:[OSA],ageYears:[46,68],sexLabels:["Female","Male"]},
 ])},
 {id:"concept.malignant-hyperthermia-susceptibility.trigger-free-anesthesia-plan",displayName:"Plan trigger-free anaesthesia for MH susceptibility",learningObjective:"Arrange specialist trigger-free anaesthetic and facility planning for known or credibly documented MH susceptibility.",stage:0,educationalTier:1,conceptType:"management",evidenceClaimIds:[MH],variants:variants([
  {slug:"documented-susceptibility",complaint:"Malignant hyperthermia record",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, has specialist documentation of malignant-hyperthermia susceptibility and is considering elective gallbladder surgery.",stem:"What is the appropriate preoperative plan?",correct:["Plan trigger-free anesthesia","Known susceptibility requires advance anesthesiology and facility planning that avoids triggering agents."],wrong:[["Use routine anesthetic without disclosure","The documented susceptibility must be communicated and planned for."],["Administer a test anesthetic in clinic","The clinic must not simulate anesthetic exposure."],["Cancel all future surgery permanently","Susceptibility calls for a safe plan, not an absolute ban on indicated surgery."]],explanation:"Coordinate a trigger-free anaesthetic in an appropriately prepared hospital setting.",claims:[MH],ageYears:[29,52],sexLabels:["Female","Male"]},
  {slug:"family-testing-record",complaint:"Family MH history",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, has a credible family malignant-hyperthermia history and a genetics service record identifying susceptibility before planned colectomy.",stem:"Which action best incorporates this information into surgical planning?",correct:["Request trigger-free planning","Credibly documented susceptibility should shape anesthetic and facility preparation."],wrong:[["Ignore family-linked documentation","The specialist record is clinically relevant."],["Select a trigger-containing anesthetic","That contradicts the susceptibility plan."],["Give crisis medication in clinic now","Prophylactic clinic treatment is outside the objective and setting."]],explanation:"The clinic's role is to communicate and arrange an appropriate anesthetic setting, not administer anesthesia.",claims:[MH],ageYears:[35,60],sexLabels:["Female","Male"]},
  {slug:"prior-mh-event",complaint:"Prior anesthesia reaction",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, has a prior specialist-reviewed anesthetic record confirming malignant-hyperthermia susceptibility and now needs another operation.",stem:"What should be established before scheduling the new procedure?",correct:["A trigger-free plan","The team should plan an anesthetic that avoids MH triggers in a prepared setting."],wrong:[["A routine outpatient anesthetic plan","The known susceptibility requires specific preparation."],["A clinic challenge with anesthetic gas","Provocation in this clinic is unsafe and unsupported."],["No anesthesiology review","Specialist planning is central to safe future anesthesia."]],explanation:"Known susceptibility should be visible to the anesthesiology and facility teams before the procedure.",claims:[MH],ageYears:[41,66],sexLabels:["Female","Male"]},
  {slug:"mh-alert-bracelet",complaint:"Anesthesia alert review",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, wears an MH alert bracelet and provides the confirming specialist record while discussing elective surgery.",stem:"Which referral message is most important?",correct:["MH requires trigger-free planning","The documented risk must accompany the referral so anesthesia and the facility can prepare."],wrong:[["Bracelet alone determines drug dose","Specific drug and dose choices require the anesthesiology team."],["Routine anesthesia needs no change","That disregards the documented susceptibility."],["Clinic can manage an MH crisis","The clinic has no anesthetic crisis capability."]],explanation:"Transmit the verified susceptibility and request trigger-free, prepared-facility planning.",claims:[MH],ageYears:[32,57],sexLabels:["Female","Male"]},
 ])}
]});


