import { describe,expect,it } from "vitest";
import { answerChoiceTimingRegistryEntrySchema,syntheticClinicalCaseSchema,testedConceptSchema } from "../../schema";
import { GS028_20261003_AUTHORING_CONCEPTS as concepts,GS028_20261003_TESTED_CONCEPTS as tested,GS028_20261003_QUESTIONS as questions,GS028_20261003_CASES as cases,GS028_20261003_CLAIMS as claims,GS028_20261003_SOURCES as sources,GS028_20261003_TIMING_ENTRIES as timing,GS028_20261003_BATCH_MANIFEST as manifest } from "./coverage-gaps-batch";

describe("GS-028 October 3 unadmitted coverage-gap package",()=>{
 it("contains exactly twenty objectives and eighty questions",()=>{expect(concepts).toHaveLength(20);expect(tested).toHaveLength(20);expect(questions).toHaveLength(80);expect(cases).toHaveLength(78);expect(manifest).toMatchObject({contentVersion:"development-batch.2026-10-03.coverage-gaps.1",authoringConceptCount:20,testedConceptCount:20,questionVariantCount:80,caseCount:78,decisionNodeCount:80,timingEntryCount:80,resultGateCount:2,publicReleaseAuthorized:false});for(const concept of concepts)expect(questions.filter((item)=>item.conceptId===concept.id)).toHaveLength(4);});
 it("retains complete provenance and draft metadata",()=>{const claimIds=new Set(claims.map((item)=>item.id)),sourceIds=new Set(sources.map((item)=>item.id));expect(claimIds.size).toBe(claims.length);expect(sourceIds.size).toBe(sources.length);for(const concept of concepts){expect(concept.reviewStatus).toBe("needs_clinician_review");for(const id of concept.evidenceClaimIds)expect(claimIds.has(id)).toBe(true);}for(const question of questions){expect(question.reviewStatus).toBe("needs_clinician_review");for(const id of question.supportingEvidenceClaimIds)expect(claimIds.has(id)).toBe(true);}for(const claim of claims)for(const id of claim.sourceIds)expect(sourceIds.has(id)).toBe(true);});
 it("parses every runtime record without admitting it",()=>{for(const concept of tested)testedConceptSchema.parse(concept);for(const item of cases)syntheticClinicalCaseSchema.parse(item);for(const entry of timing)answerChoiceTimingRegistryEntrySchema.parse(entry);expect(new Set(tested.map((item)=>item.id)).size).toBe(20);expect(new Set(cases.map((item)=>item.id)).size).toBe(78);expect(new Set(questions.map((item)=>item.id)).size).toBe(80);});
});

