import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { REMAINING_SOURCES as S } from "./source-catalog-remaining14";

const BG="claim.gs028d.acidosis.blood-gas"; const AG="claim.gs028d.acidosis.corrected-gap";
const noTest=(label:string,rationale:string):[string,string]=>[label,rationale];
export const FLUIDS_ACID_BASE_FAMILY=buildFamily({slug:"acid-base",label:"Acid-base interpretation",sources:[S.acidosis],claims:[
 {id:BG,statement:"When reduced plasma bicarbonate suggests metabolic acidosis, blood-gas assessment confirms the acidemia and identifies respiratory or mixed acid-base contributions.",sourceIds:[S.acidosis.id],category:"evaluation",certainty:"low",limitation:"R1.1 is expert opinion; arterial sampling is not claimed universally superior.",population:"Adults with reduced plasma bicarbonate and suspected metabolic acidosis."},
 {id:AG,statement:"In metabolic acidosis with low albumin, an albumin-corrected anion gap better assesses unmeasured anion accumulation than the uncorrected gap.",sourceIds:[S.acidosis.id],category:"evaluation",certainty:"moderate",limitation:"No correction formula or arithmetic threshold is taught; units and equations would require separate exact verification.",population:"Adults with metabolic acidosis and hypoalbuminaemia."}],concepts:[
 {id:"concept.metabolic-acidosis.confirm-with-blood-gas",displayName:"Confirm metabolic acidosis with blood gas",learningObjective:"Use an external blood-gas result to confirm metabolic acidosis and identify mixed or respiratory contributions.",stage:0,educationalTier:1,conceptType:"diagnosis",evidenceClaimIds:[BG],variants:variants([
  {slug:"diarrhea-low-bicarb",complaint:"Low bicarbonate result",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, brings an outside chemistry panel obtained for several days of diarrhea. Bicarbonate is reduced, but no blood gas was collected and the patient is now stable.",stem:"Which next assessment best confirms the acid-base disorder and checks for a respiratory contribution?",correct:noTest("External blood gas","A blood gas confirms acidemia and shows whether respiratory compensation or another respiratory process is present."),wrong:[["Repeat bicarbonate test","A repeat chemistry value does not define pH or the respiratory component.",{timingProfileId:"timing.test.basic_labs"}],["Serum lipase test","Lipase does not characterize this acid-base disorder.",{timingProfileId:"timing.test.basic_labs"}],["Thyroid function test","Thyroid testing does not confirm metabolic acidosis or identify a mixed disturbance.",{timingProfileId:"timing.test.basic_labs"}]],explanation:"A low chemistry bicarbonate suggests but does not fully characterize metabolic acidosis; a blood gas supplies pH and respiratory information.",claims:[BG],ageYears:[34,58],sexLabels:["Female","Male"],test:{timingProfileId:"timing.test.basic_labs"}},
  {slug:"renal-low-bicarb",complaint:"Kidney panel review",presentation:"{patientName}, a {patientAge}-year-old {patientSex} with chronic kidney disease brings a complete outside electrolyte panel showing reduced bicarbonate and feels well today.",stem:"Which additional result is most useful to verify metabolic acidosis rather than assume the chemistry result defines the whole disorder?",correct:noTest("External blood-gas result","The pH and carbon dioxide values confirm the primary process and reveal mixed physiology."),wrong:[["Urine culture result","A culture addresses infection rather than the primary acid-base question.",{timingProfileId:"timing.test.basic_labs"}],["Hemoglobin A1c result","Long-term glycaemia does not establish the current acid-base pattern.",{timingProfileId:"timing.test.basic_labs"}],["Abdominal ultrasound result","Imaging does not determine pH or respiratory compensation.",{timingProfileId:"timing.test.ultrasound"}]],explanation:"Interpret the reduced bicarbonate with blood-gas pH and carbon dioxide rather than labeling the disorder from chemistry alone.",claims:[BG],ageYears:[52,71],sexLabels:["Female","Male"],test:{timingProfileId:"timing.test.basic_labs"}},
  {slug:"tachypnea-low-bicarb",complaint:"Fast breathing follow-up",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, is clinically stable after an outside urgent-care visit for tachypnea. The chemistry panel had reduced bicarbonate, but the record contains no pH or carbon dioxide value.",stem:"Which missing study best distinguishes metabolic acidosis with compensation from respiratory alkalosis or a mixed disorder?",correct:noTest("External blood gas","Blood-gas pH and carbon dioxide distinguish these competing acid-base patterns."),wrong:[["Chest radiograph alone","Imaging may address a pulmonary cause but cannot classify the acid-base process.",{timingProfileId:"timing.test.radiography"}],["Serum albumin alone","Albumin helps interpret anion gap but does not supply pH or carbon dioxide.",{timingProfileId:"timing.test.basic_labs"}],["Urine ketones alone","Ketones may identify one cause but do not classify the complete acid-base disturbance.",{timingProfileId:"timing.test.basic_labs"}]],explanation:"Blood-gas assessment is needed because reduced bicarbonate can accompany primary metabolic acidosis or a respiratory/mixed process.",claims:[BG],ageYears:[28,46],sexLabels:["Female","Male"],test:{timingProfileId:"timing.test.basic_labs"}},
  {slug:"postoperative-low-bicarb",complaint:"Discharge lab question",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, returns after an uncomplicated hospital operation. A discharge chemistry panel showed reduced bicarbonate, and the patient asks whether that value alone proves acidemia.",stem:"Which contemporaneous report would establish whether this patient had metabolic acidemia?",correct:noTest("Blood-gas report","Blood-gas pH and carbon dioxide confirm acidemia and characterize the respiratory component."),wrong:[["Operative pathology report","Pathology does not classify the acid-base state."],["Wound culture report","Microbiology cannot establish pH or compensation."],["Preoperative ECG report","An ECG does not define the recorded acid-base disorder."]],explanation:"The chemistry value alone does not provide pH; a contemporaneous blood gas completes the interpretation.",claims:[BG],ageYears:[41,66],sexLabels:["Female","Male"]},
 ])},
 {id:"concept.metabolic-acidosis.albumin-corrected-anion-gap",displayName:"Use albumin-corrected anion gap",learningObjective:"Select albumin correction when interpreting the anion gap in metabolic acidosis with hypoalbuminaemia.",stage:0,educationalTier:1,conceptType:"diagnosis",evidenceClaimIds:[AG],variants:variants([
  {slug:"cirrhosis-gap",complaint:"Acidosis panel review",presentation:"{patientName}, a {patientAge}-year-old {patientSex} with cirrhosis brings a complete outside panel confirming metabolic acidosis and marked hypoalbuminaemia.",stem:"Which calculation best assesses whether unmeasured anions are accumulating in this patient?",correct:noTest("Albumin-corrected anion gap","Correction accounts for the lower baseline contribution of albumin to the measured gap."),wrong:[["Uncorrected anion gap alone","Low albumin can make the uncorrected gap underestimate anion accumulation."],["Bicarbonate concentration alone","Bicarbonate confirms part of the disturbance but does not classify unmeasured anions."],["Uncorrected osmolar gap alone","That calculation answers a different solute question and does not replace corrected anion-gap interpretation."]],explanation:"Hypoalbuminaemia lowers the expected anion gap, so the corrected gap is the appropriate classification tool.",claims:[AG],ageYears:[49,67],sexLabels:["Female","Male"]},
  {slug:"malnutrition-gap",complaint:"Nutrition lab review",presentation:"{patientName}, a {patientAge}-year-old {patientSex} recovering from prolonged poor intake has a complete outside blood-gas and chemistry panel showing metabolic acidosis with low albumin.",stem:"Which reported value should guide classification of anion accumulation?",correct:noTest("Albumin-corrected anion gap","The corrected value adjusts interpretation for hypoalbuminaemia."),wrong:[["Raw anion gap only","The raw value can appear deceptively low when albumin is reduced."],["Albumin concentration alone","Albumin provides the correction context but does not classify the acid-base gap by itself."],["Uncorrected osmolar gap alone","That metric answers a different solute question and does not replace albumin-corrected anion-gap interpretation."]],explanation:"Use the albumin-corrected rather than raw anion gap when albumin is low.",claims:[AG],ageYears:[38,63],sexLabels:["Female","Male"]},
  {slug:"sepsis-recovery-gap",complaint:"Hospital panel question",presentation:"{patientName}, a {patientAge}-year-old {patientSex} is stable after a hospital admission for sepsis. Outside records show metabolic acidosis during admission and a substantially reduced albumin level.",stem:"Which interpretation avoids underestimating unmeasured anion accumulation in the admission record?",correct:noTest("Albumin-corrected anion gap","Albumin correction addresses the depressed baseline gap associated with low albumin."),wrong:[["Uncorrected anion gap alone","That metric can miss anion accumulation in hypoalbuminaemia."],["Uncorrected osmolar gap alone","That metric answers a different solute question."],["Serum lactate level alone","One measured anion does not replace the broader corrected-gap assessment."]],explanation:"The corrected gap is needed to interpret unmeasured anions in a hypoalbuminaemic patient.",claims:[AG],ageYears:[45,72],sexLabels:["Female","Male"]},
  {slug:"cancer-gap",complaint:"Outside labs review",presentation:"{patientName}, a {patientAge}-year-old {patientSex} receiving cancer treatment brings complete outside blood-gas, electrolyte, and albumin results showing metabolic acidosis and hypoalbuminaemia.",stem:"Which acid-base metric should be used to decide whether the gap is elevated for this patient?",correct:noTest("Albumin-corrected anion gap","The correction makes the gap interpretable against the patient's low albumin."),wrong:[["Uncorrected anion gap","The uncorrected result may understate the gap in this setting."],["Chloride value alone","Chloride contributes to the calculation but cannot classify the entire disorder alone."],["Uncorrected osmolar gap alone","That metric answers a different solute question and does not determine the albumin-corrected gap."]],explanation:"Albumin correction accounts for the lower expected gap when the albumin concentration is reduced.",claims:[AG],ageYears:[50,69],sexLabels:["Female","Male"]},
 ])}
]});






