import { buildFamily } from "./family-builder"; import { variants } from "./spec-utils"; import { REMAINING_SOURCES as S } from "./source-catalog-remaining14";
const FRAIL="claim.gs028d.frailty.validated-assessment", DEL="claim.gs028d.delirium.multicomponent-plan";
export const GERIATRICS_FAMILY=buildFamily({slug:"geriatrics",label:"Older-adult perioperative planning",sources:[S.frailty,S.frailtyCross,S.delirium],claims:[
 {id:FRAIL,statement:"For an older adult preparing for elective major abdominal surgery, frailty should be assessed with a structured multidimensional instrument rather than inferred from chronological age or comorbidity count alone.",sourceIds:[S.frailty.id,S.frailtyCross.id],category:"evaluation",certainty:"low",limitation:"Consensus good-practice evidence with an independent low-quality consensus cross-check; no universal tool, cutoff, cancellation rule, or automatic intensive-care disposition is supported.",population:"Older adults preparing for elective major abdominal surgery."},
 {id:DEL,statement:"Surgical patients at risk for postoperative delirium should receive a tailored multidisciplinary multicomponent nonpharmacologic prevention plan from the perioperative hospital team.",sourceIds:[S.delirium.id],category:"management",certainty:"moderate",limitation:"Components are individualized; no identical bundle, clinic monitoring capability, or guaranteed prevention is claimed.",population:"Adults at increased risk for postoperative delirium."}],concepts:[
 {id:"concept.preoperative-frailty.validated-assessment",displayName:"Assess preoperative frailty",learningObjective:"Use a structured multidimensional frailty assessment rather than inferring frailty from age or comorbidity before elective major abdominal surgery.",stage:0,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[FRAIL],variants:variants([
  {slug:"colectomy-independent",complaint:"Surgery fitness review",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, is preparing for elective major colon surgery, lives independently, and has several controlled chronic conditions.",stem:"Which additional assessment best characterizes vulnerability that age and diagnosis lists do not capture?",correct:["Structured frailty assessment","Frailty is a distinct perioperative domain that should be assessed directly."],wrong:[["Age-based risk estimate","Age does not substitute for frailty measurement."],["Comorbidity-based risk estimate","Comorbidity and frailty overlap but are not interchangeable."],["Procedure-based risk estimate","The operation does not measure the patient's physiologic vulnerability."]],explanation:"Assess frailty directly rather than inferring it from age, independence, or comorbidity.",claims:[FRAIL],ageYears:[68,76],sexLabels:["Female","Male"]},
  {slug:"gastrectomy-assistance",complaint:"Preop vulnerability check",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, needs elective major gastric surgery and reports new dependence with shopping and meal preparation despite few listed medical diagnoses.",stem:"What is the best next step for perioperative risk characterization?",correct:["Structured frailty assessment","Functional vulnerability may reveal frailty that a short comorbidity list misses."],wrong:[["Age-only risk assessment","Age cannot establish frailty."],["Comorbidity-only risk assessment","Low comorbidity burden does not exclude frailty."],["Procedure-only risk assessment","The procedure alone does not characterize functional vulnerability."]],explanation:"Frailty assessment characterizes vulnerability without equating it with age or comorbidity.",claims:[FRAIL],ageYears:[70,82],sexLabels:["Female","Male"]},
  {slug:"liver-surgery-active",complaint:"Frailty question",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, remains physically active while preparing for elective major liver surgery but has multiple stable comorbidities.",stem:"Which approach avoids labeling this patient as frail solely from the medical history?",correct:["Structured frailty assessment","Direct assessment distinguishes frailty from comorbidity burden."],wrong:[["Comorbidity-only risk assessment","A diagnosis count is not the same construct."],["Age-only risk assessment","Chronological age alone is insufficient."],["Activity-only risk assessment","One favorable feature does not replace structured assessment."]],explanation:"Assess frailty as its own domain rather than assigning it from age, activity, or diagnoses.",claims:[FRAIL],ageYears:[67,74],sexLabels:["Female","Male"]},
  {slug:"pancreatic-surgery",complaint:"Major surgery planning",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, is being evaluated for elective major pancreatic surgery. The referral lists age and comorbidities but no frailty measure.",stem:"What information should be added to the preoperative assessment?",correct:["Structured frailty assessment","The consensus supports direct frailty assessment during planning for elective major abdominal surgery."],wrong:[["Age-based risk estimate","The record already contains age, which does not measure frailty."],["Comorbidity-based risk estimate","The list is already present and does not replace frailty assessment."],["Procedure-based risk estimate","A procedure label does not characterize patient vulnerability."]],explanation:"Add structured frailty assessment while preserving age and comorbidity as separate information.",claims:[FRAIL],ageYears:[69,79],sexLabels:["Female","Male"]},
 ])},
 {id:"concept.postoperative-delirium.multicomponent-prevention-plan",displayName:"Plan multicomponent delirium prevention",learningObjective:"Communicate a tailored nonpharmacologic multicomponent prevention plan to the hospital perioperative team for an at-risk adult.",stage:0,educationalTier:1,conceptType:"management",evidenceClaimIds:[DEL],variants:variants([
  {slug:"prior-delirium",complaint:"Delirium prevention plan",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, had delirium after a previous operation and is preparing for another major abdominal procedure at the hospital.",stem:"Which prevention approach should be communicated to the perioperative hospital team?",correct:["Tailored non-drug bundle","Risk reduction should combine individualized measures across the multidisciplinary hospital team."],wrong:[["One sedative for every patient","Routine sedative prophylaxis is not the supported multicomponent approach."],["Clinic observation after surgery","Postoperative prevention belongs to the actual hospital team and setting."],["No plan until delirium occurs","Known risk should prompt prevention planning before surgery."]],explanation:"Plan tailored team-based measures before surgery; do not promise that delirium will be prevented.",claims:[DEL],ageYears:[71,83],sexLabels:["Female","Male"]},
  {slug:"sensory-impairment",complaint:"Hospital care planning",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, uses hearing aids and glasses and is preparing for major bowel surgery with a planned hospital admission.",stem:"What is the best delirium-prevention strategy for the receiving team?",correct:["Tailor a multicomponent nonpharmacologic plan","The team should address the patient's specific modifiable risks within a broader prevention plan."],wrong:[["Remove sensory aids routinely","That can worsen disorientation rather than support prevention."],["Use one identical protocol without review","The guideline emphasizes tailoring to the patient."],["Leave prevention to the clinic after discharge","The relevant care occurs during the hospital perioperative course."]],explanation:"Communicate individualized nonpharmacologic measures across the hospital team.",claims:[DEL],ageYears:[70,81],sexLabels:["Female","Male"]},
  {slug:"cognitive-risk",complaint:"Surgery cognition planning",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, has baseline cognitive impairment and is preparing for major abdominal surgery at a regional hospital.",stem:"Which plan best addresses postoperative delirium risk?",correct:["Hospital-team multicomponent prevention","A multidisciplinary tailored plan addresses several modifiable delirium risks together."],wrong:[["A single medication-only plan","The supported prevention approach is multicomponent and nonpharmacologic."],["Routine clinic monitoring overnight","The clinic does not provide postoperative hospital monitoring."],["Delay all planning until confusion appears","Prevention should be planned for an at-risk patient."]],explanation:"The clinic communicates risk and a prevention need; the real perioperative team delivers the plan.",claims:[DEL],ageYears:[73,85],sexLabels:["Female","Male"]},
  {slug:"mobility-nutrition",complaint:"Preoperative team review",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, has mobility and nutrition vulnerabilities before major gastric surgery and will recover in the hospital.",stem:"How should delirium prevention be structured?",correct:["Tailored non-drug bundle","A tailored multicomponent plan can address the patient's specific risks through coordinated hospital care."],wrong:[["Choose one universal intervention","One measure does not constitute the recommended tailored multicomponent plan."],["Rely on age alone to choose care","Risk planning should reflect the patient's actual vulnerabilities."],["Provide only a discharge handout","Prevention requires active perioperative team implementation."]],explanation:"Use the identified vulnerabilities to shape a multidisciplinary prevention plan in the hospital.",claims:[DEL],ageYears:[68,80],sexLabels:["Female","Male"]},
 ])}
]});



