import { buildFamily } from "./family-builder"; import { variants, type VariantRow } from "./spec-utils"; import { REMAINING_SOURCES as S } from "./source-catalog-remaining14";
const SEV="claim.gs028d.hyperkalaemia.severe-transfer", MECH="claim.gs028d.hyperkalaemia.mechanisms";
const scenarios=[
 ["renal-result","Critical potassium result","advanced kidney disease","a potassium of 6.7 mmol/L",52,70],
 ["raas-result","Medication lab alert","a recent renin-angiotensin-system medication change","a confirmed potassium of 6.6 mmol/L",46,68],
 ["dialysis-result","Dialysis lab alert","maintenance haemodialysis","a confirmed community potassium of 6.8 mmol/L",39,73],
 ["dehydration-result","Urgent lab callback","recent gastrointestinal fluid loss","a repeat non-haemolysed potassium of 6.5 mmol/L",31,64],
] as const;
const severeStems=[
 "What is the safest next disposition under the current UKKA adult pathway?",
 "How should this confirmed severe community result be managed now?",
 "Which immediate disposition matches the current UKKA adult pathway?",
 "What action should follow this confirmed repeat community result?",
] as const;
const severeScenario=(index:0|1|2|3):VariantRow=>{const [slug,complaint,context,result,a,b]=scenarios[index];return {slug,complaint,presentation:`{patientName}, a {patientAge}-year-old {patientSex} with ${context}, returns to clinic when an outside laboratory calls with ${result}. The sample is confirmed and the patient is available for immediate transfer.`,stem:severeStems[index],correct:["Immediate hospital assessment","A confirmed community potassium at or above 6.5 mmol/L meets the UKKA severe threshold for immediate hospital care."],wrong:[["Routine follow-up next week","Delayed review is unsafe for a severe confirmed result."],["Repeat testing before any action","The result is already confirmed; another outpatient test must not delay hospital assessment.",{timingProfileId:"timing.test.basic_labs"}],["Dietary advice alone","Counseling does not replace urgent assessment and treatment for severe hyperkalaemia."]],explanation:"Arrange immediate hospital assessment without creating an outpatient delay.",claims:[SEV],acuity:"urgent",ageYears:[a,b],sexLabels:["Female","Male"]};};
export const HYPERKALAEMIA_FAMILY=buildFamily({slug:"hyperkalaemia",label:"Acute hyperkalaemia",sources:[S.ukkaHyperK],claims:[
 {id:SEV,statement:"Under the current UKKA adult pathway, a confirmed community potassium concentration of at least 6.5 mmol/L warrants immediate hospital assessment and treatment.",sourceIds:[S.ukkaHyperK.id],category:"disposition",certainty:"moderate",limitation:"This is a UK guideline threshold, not a universal jurisdictional rule or an exact arrhythmia probability.",population:"Adults with confirmed severe hyperkalaemia detected in the community."},
 {id:MECH,statement:"In acute hyperkalaemia, intravenous calcium protects cardiac membrane physiology but does not lower serum potassium, whereas insulin with glucose shifts potassium into cells.",sourceIds:[S.ukkaHyperK.id],category:"management",certainty:"low",limitation:"The July 2026 calcium recommendation is 2C after no evidence for or against outcome benefit; no dose, timing, or survival claim is taught.",population:"Adults receiving hospital treatment for acute hyperkalaemia."}],concepts:[
 {id:"concept.hyperkalaemia.severe-community-result-transfer",displayName:"Transfer severe community hyperkalaemia",learningObjective:"Recognize a confirmed severe community potassium result in the UKKA framework as requiring immediate hospital assessment.",stage:0,educationalTier:1,conceptType:"disposition",evidenceClaimIds:[SEV],variants:variants([severeScenario(0),severeScenario(1),severeScenario(2),severeScenario(3)])},
 {id:"concept.hyperkalaemia.distinguish-protection-from-potassium-lowering",displayName:"Distinguish hyperkalaemia treatment mechanisms",learningObjective:"Separate cardiac membrane protection by calcium from intracellular potassium shift by insulin and glucose.",stage:0,educationalTier:1,conceptType:"applied_science",evidenceClaimIds:[MECH],variants:variants([
  {slug:"calcium-record",complaint:"Hospital treatment review",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, returns after hospital treatment for severe hyperkalaemia. The record lists intravenous calcium followed by insulin with glucose.",stem:"Which statement correctly distinguishes the two treatment mechanisms in this record?",correct:["Calcium protects; insulin shifts potassium","The therapies answer different immediate problems and calcium does not lower serum potassium."],wrong:[["Calcium lowers potassium; insulin protects the myocardium","The mechanisms are reversed."],["Both therapies remove potassium from the body","Neither listed action is potassium elimination."],["Both therapies only correct acidosis","Their principal roles in this record are membrane protection and intracellular shift."]],explanation:"Calcium is membrane protective; insulin with glucose redistributes potassium intracellularly.",claims:[MECH],ageYears:[44,69],sexLabels:["Female","Male"]},
  {slug:"unchanged-k",complaint:"Potassium record question",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, asks why the hospital repeated potassium-lowering treatment after intravenous calcium during a hyperkalaemia admission.",stem:"What is the best explanation for why calcium did not replace potassium-lowering treatment?",correct:["Calcium does not lower serum potassium","Its role is cardiac membrane protection, so a potassium-shifting or removing strategy is still needed."],wrong:[["Calcium acts only as a diuretic","Calcium is not given here to produce urinary potassium loss."],["Calcium removes potassium in stool","It is not a gastrointestinal potassium binder."],["Calcium permanently corrects renal failure","It does not reverse the underlying renal disorder."]],explanation:"Calcium can address membrane instability without changing the serum potassium concentration.",claims:[MECH],ageYears:[37,72],sexLabels:["Female","Male"]},
  {slug:"insulin-shift",complaint:"Discharge medication question",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, reviews a hospital note stating that insulin and glucose were used for acute hyperkalaemia despite no diagnosis of diabetes.",stem:"Which mechanism explains the insulin-and-glucose treatment in this record?",correct:["Shift potassium from extracellular fluid into cells","Insulin promotes cellular potassium uptake while glucose accompanies treatment."],wrong:[["Stabilize the cardiac membrane without changing potassium","That describes calcium's distinct immediate role."],["Bind potassium inside the intestine","That describes a gastrointestinal removal strategy, not insulin."],["Increase potassium filtration independent of kidney function","Insulin redistributes potassium rather than directly increasing renal filtration."]],explanation:"Insulin with glucose is a redistribution treatment; it is not evidence that the patient has diabetes.",claims:[MECH],ageYears:[33,61],sexLabels:["Female","Male"]},
  {slug:"different-roles",complaint:"Emergency record review",presentation:"{patientName}, a {patientAge}-year-old {patientSex}, is stable after emergency treatment for hyperkalaemia with electrocardiographic concern. The hospital summary records calcium and insulin with glucose.",stem:"Which therapy in the record directly provided the intracellular potassium shift?",correct:["Insulin with glucose","Insulin moves potassium into cells; glucose supports its safe use."],wrong:[["Intravenous calcium","Calcium protects membrane physiology but does not provide the potassium shift."],["Continuous cardiac monitoring","Monitoring detects change but does not move potassium."],["Repeat electrocardiography","An ECG reassesses cardiac effects but is not a potassium-shifting therapy.",{timingProfileId:"timing.test.physiology"}]],explanation:"Insulin moves potassium into cells, while calcium serves a separate membrane-protective role.",claims:[MECH],ageYears:[48,75],sexLabels:["Female","Male"]},
 ])}
]});

