import { describe,expect,it } from "vitest";
import { answerChoiceTimingRegistryEntrySchema,syntheticClinicalCaseSchema,testedConceptSchema } from "../../schema";
import { GS028_20261003_REMAINING14_AUTHORING_CONCEPTS as concepts,GS028_20261003_REMAINING14_TESTED_CONCEPTS as tested,GS028_20261003_REMAINING14_QUESTIONS as questions,GS028_20261003_REMAINING14_CASES as cases,GS028_20261003_REMAINING14_TIMING_ENTRIES as timing,GS028_20261003_REMAINING14_CLAIMS as claims,GS028_20261003_REMAINING14_SOURCES as sources } from "./coverage-gaps-batch";
import { DIALYSIS_ACCESS_FAMILY } from "./dialysis-access";

describe("GS-028 October 3 remaining fourteen authoring",()=>{
 it("contains fourteen objectives and fifty-six substantive questions",()=>{expect(concepts).toHaveLength(14);expect(questions).toHaveLength(56);expect(cases).toHaveLength(54);for(const concept of concepts){const variants=questions.filter((item)=>item.conceptId===concept.id);expect(variants,concept.id).toHaveLength(4);expect(new Set(variants.map((item)=>item.patientPresentation))).toHaveLength(4);expect(new Set(variants.map((item)=>item.stem))).toHaveLength(4);}});
 it("keeps every objective independently eligible at stage zero",()=>{for(const concept of concepts){expect(concept.earliestFacilityStage).toBe(0);expect(cases.some((item)=>item.decisionNodes.length===1&&item.decisionNodes[0]?.primaryConceptId===concept.id),concept.id).toBe(true);}for(const item of cases){expect(item.releasePointId).toBe("release.l0.clinic_evaluation");expect(item.earliestFacilityStage).toBe(0);expect(item.requiredCapabilityIds).toEqual([]);}});
 it("keeps questions complete, randomized, and under draft review",()=>{for(const question of questions){expect(question.answerChoices).toHaveLength(4);expect(question.answerChoices.filter((item)=>item.isCorrect)).toHaveLength(1);expect(question.stem).toMatch(/\?$/);expect(question.patientPresentation).toContain("{patientName}");expect(question.reviewStatus).toBe("needs_clinician_review");expect(question.approvedInstantiationProfiles.length).toBeGreaterThan(0);for(const profile of question.approvedInstantiationProfiles){expect(profile.prototypeDemographics).toBeDefined();if(profile.prototypeDemographics){expect(profile.prototypeDemographics.ageYears).toBeGreaterThanOrEqual(18);expect(["Female","Male","Not specified"]).toContain(profile.prototypeDemographics.sexLabel);}}}for(const item of cases)for(const node of item.decisionNodes)expect(node.shuffleAnswers).toBe(true);});
 it("does not signal the key through a uniquely longest label",()=>{const cues:string[]=[];for(const question of questions){const correct=question.answerChoices.find((choice)=>choice.isCorrect);const longestDistractor=Math.max(...question.answerChoices.filter((choice)=>!choice.isCorrect).map((choice)=>choice.label.length));if(correct&&correct.label.length>longestDistractor)cues.push(`${question.id}: ${correct.label.length}>${longestDistractor} ${correct.label}`);}expect.soft(cues).toEqual([]);});
 it("maps every claim bidirectionally to complete rights-checked sources",()=>{const claimIds=new Set(claims.map((item)=>item.id)),sourceIds=new Set(sources.map((item)=>item.id));expect(claimIds.size).toBe(claims.length);expect(sourceIds.size).toBe(sources.length);for(const question of questions)for(const id of question.supportingEvidenceClaimIds)expect(claimIds.has(id)).toBe(true);for(const item of claims)for(const id of item.sourceIds){expect(sourceIds.has(id)).toBe(true);expect(sources.find((source)=>source.id===id)?.evidenceClaimIds).toContain(item.id);}for(const item of sources){expect(item.authors.length,item.id).toBeGreaterThan(0);expect(item.authors).not.toContain("et al.");expect(item.completeCitation.length).toBeGreaterThan(30);expect(item.officialUrl).toMatch(/^https:/);expect(item.reuseStatus).not.toBe("unknown");}});
 it("assigns timing to every authored test choice",()=>{expect(timing).toHaveLength(56);const testAction=/\b(?:arrange|order|repeat|refer|continue|switch|replace|perform|obtain|start|use)\b.*\b(?:blood-gas|bicarbonate|lipase|thyroid|culture|A1c|ultrasound|imaging|radiograph|ketones|pathology|ECG|LDCT|low-dose CT|CT|sputum|thoracentesis|sampling)\b/i;const negation=/\b(?:no|without|avoid|defer|skip|do not|discontinue|ignore|wait|reassurance)\b/i;let count=0;for(const question of questions){const entry=timing.find((item)=>item.questionVariantId===question.id);expect(entry).toBeDefined();for(const choice of question.answerChoices){if(!testAction.test(choice.label)||negation.test(choice.label))continue;count+=1;expect(entry!.classification.kind,`${question.id}/${choice.id}`).toBe("test_choices");if(entry!.classification.kind==="test_choices")expect(entry!.classification.choices.find((item)=>item.choiceId===choice.id)?.timing.kind,`${question.id}/${choice.id}/${choice.label}`).toBe("test");}}expect(count).toBeGreaterThan(0);});
 it("uses exactly two purposeful outsourced specialist-access ultrasound gates",()=>{const gates=cases.flatMap((item)=>item.decisionNodes).filter((node)=>node.resultGateAfter);expect(gates).toHaveLength(2);for(const node of gates)expect(node.resultGateAfter).toMatchObject({resultTypeId:"service.ultrasound",allowedServiceRouteIds:["route.ultrasound.outsourced"]});expect(DIALYSIS_ACCESS_FAMILY.serviceContracts).toEqual([{serviceId:"service.ultrasound",allowedRouteIds:["route.ultrasound.outsourced"],delivery:"existing_balance_contract"}]);});
 it("passes runtime schemas with unique stable ids",()=>{for(const concept of tested)testedConceptSchema.parse(concept);for(const item of cases)syntheticClinicalCaseSchema.parse(item);for(const entry of timing)answerChoiceTimingRegistryEntrySchema.parse(entry);expect(new Set(cases.map((item)=>item.id)).size).toBe(cases.length);expect(new Set(cases.flatMap((item)=>item.decisionNodes).map((node)=>node.id)).size).toBe(56);expect(new Set(questions.map((item)=>item.id)).size).toBe(56);});
});

