import type { SourceSpec } from "./family-builder";

export const FIRST_SIX_SOURCES = {
  esicmArds: {
    id: "source.esicm.ards-guideline.2023",
    title: "ESICM guidelines on acute respiratory distress syndrome: definition, phenotyping and respiratory support strategies",
    citation:
      "Grasselli G, Calfee CS, Camporota L, et al. ESICM guidelines on acute respiratory distress syndrome: definition, phenotyping and respiratory support strategies. Intensive Care Med. 2023;49:727-759. doi:10.1007/s00134-023-07050-7.",
    organization: "Intensive Care Medicine / European Society of Intensive Care Medicine",
    authors: [
      "Giacomo Grasselli",
      "Carolyn S Calfee",
      "Luigi Camporota",
      "Daniele Poole",
      "Marcelo B P Amato",
      "Massimo Antonelli",
      "Yaseen M Arabi",
      "Francesca Baroncelli",
      "Jeremy R Beitler",
      "Giacomo Bellani",
      "Geoff Bellingan",
      "Bronagh Blackwood",
      "Lieuwe D J Bos",
      "Laurent Brochard",
      "Daniel Brodie",
      "Karen E A Burns",
      "Alain Combes",
      "Sonia D'Arrigo",
      "Daniel De Backer",
      "Alexandre Demoule",
      "Sharon Einav",
      "Eddy Fan",
      "Niall D Ferguson",
      "Jean-Pierre Frat",
      "Luciano Gattinoni",
      "Claude Guérin",
      "Margaret S Herridge",
      "Carol Hodgson",
      "Catherine L Hough",
      "Samir Jaber",
      "Nicole P Juffermans",
      "Christian Karagiannidis",
      "Jozef Kesecioglu",
      "Arthur Kwizera",
      "John G Laffey",
      "Jordi Mancebo",
      "Michael A Matthay",
      "Daniel F McAuley",
      "Alain Mercat",
      "Nuala J Meyer",
      "Marc Moss",
      "Laveena Munshi",
      "Sheila N Myatra",
      "Michelle Ng Gong",
      "Laurent Papazian",
      "Bhakti K Patel",
      "Mariangela Pellegrini",
      "Anders Perner",
      "Antonio Pesenti",
      "Lise Piquilloud",
      "Haibo Qiu",
      "Marco V Ranieri",
      "Elisabeth Riviello",
      "Arthur S Slutsky",
      "Renee D Stapleton",
      "Charlotte Summers",
      "Taylor B Thompson",
      "Carmen S Valente Barbas",
      "Jesús Villar",
      "Lorraine B Ware",
      "Björn Weiss",
      "Fernando G Zampieri",
      "Elie Azoulay",
      "Maurizio Cecconi",
    ],
    year: 2023,
    doi: "10.1007/s00134-023-07050-7",
    url: "https://link.springer.com/article/10.1007/s00134-023-07050-7",
    sourceClass: "peer_reviewed_guideline",
    licenseLabel:
      "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0), https://creativecommons.org/licenses/by-nc/4.0/; authors and journal credited in the citation; facts independently synthesized without adapting source expression",
    reuseStatus: "cc_by_nc_4_0_restricted",
    authority:
      "2023 international critical-care society guideline; the batch uses independently written factual synthesis and retains the noncommercial license restriction.",
    usageRole: "evidence",
  },
  eastBci: {
    id: "source.east.blunt-cardiac-injury-screening.2012",
    title: "Blunt Cardiac Injury, Screening for",
    citation:
      "Clancy K, Velopulos C, Bilaniuk JW, Collier B, Crowley W, Kurek S, Lui F, Nayduch D, Sangosanya A, Tucker B, Haut ER. Screening for blunt cardiac injury: an Eastern Association for the Surgery of Trauma practice management guideline. J Trauma Acute Care Surg. 2012;73(5 Suppl 4):S301-S306. doi:10.1097/TA.0b013e318270193a.",
    organization: "Eastern Association for the Surgery of Trauma / Journal of Trauma and Acute Care Surgery",
    authors: [
      "Keith Clancy",
      "Catherine Velopulos",
      "Jaroslaw W Bilaniuk",
      "Bryan Collier",
      "William Crowley",
      "Stanley Kurek",
      "Felix Lui",
      "Donna Nayduch",
      "Ayodele Sangosanya",
      "Brian Tucker",
      "Elliott R Haut",
    ],
    year: 2012,
    doi: "10.1097/TA.0b013e318270193a",
    url: "https://www.east.org/education-resources/practice-management-guidelines/details/blunt-cardiac-injury,-screening-for",
    sourceClass: "professional_society_guideline",
    licenseLabel: "Copyrighted professional-society guidance; targeted factual verification only",
    reuseStatus: "copyrighted_targeted_verification_only",
    authority:
      "EAST practice-management guideline currently listed by the society; evidence age and the guideline's statement that optimal troponin timing is unknown are retained as limitations.",
    usageRole: "evidence",
  },
  bciReview: {
    id: "source.wjes.blunt-cardiac-injury-diagnostics.2023",
    title: "Accuracy of diagnostic tests in cardiac injury after blunt chest trauma: a systematic review and meta-analysis",
    citation:
      "Kyriazidis IP, Jakob DA, Vargas JAH, et al. Accuracy of diagnostic tests in cardiac injury after blunt chest trauma: a systematic review and meta-analysis. World J Emerg Surg. 2023;18:36. doi:10.1186/s13017-023-00504-9.",
    organization: "World Journal of Emergency Surgery",
    authors: [
      "Ioannis Panagiotis Kyriazidis",
      "Dominik A Jakob",
      "Juliana Alexandra Hernández Vargas",
      "Oscar H Franco",
      "Elias Degiannis",
      "Patrick Dorn",
      "Sjaak Pouwels",
      "Bijendra Patel",
      "Ian Johnson",
      "Christopher John Houdlen",
      "Graham S Whiteley",
      "Marion Head",
      "Anil Lala",
      "Haroon Mumtaz",
      "J Agustin Soler",
      "Katie Mellor",
      "David Rawaf",
      "Ahmed R Ahmed",
      "Suhaib J S Ahmad",
      "Aristomenis Exadaktylos",
    ],
    year: 2023,
    doi: "10.1186/s13017-023-00504-9",
    url: "https://link.springer.com/article/10.1186/s13017-023-00504-9",
    sourceClass: "systematic_review",
    licenseLabel:
      "Creative Commons Attribution 4.0 International (CC BY 4.0), https://creativecommons.org/licenses/by/4.0/; authors and journal credited in the citation; facts independently synthesized without adapting source expression",
    reuseStatus: "cc_by_4_0",
    authority:
      "Recent peer-reviewed systematic review used as an independent cross-check for combined ECG and troponin evaluation; no exact diagnostic-performance estimate is authored.",
    usageRole: "cross_check",
  },
  cdcMtbi: {
    id: "source.cdc.adult-mtbi-key-recommendations",
    title: "Key Recommendations for the Care of Adult Patients with Mild Traumatic Brain Injury",
    citation:
      "Centers for Disease Control and Prevention. Key Recommendations for the Care of Adult Patients with Mild Traumatic Brain Injury. Undated clinical recommendation sheet linked from the CDC adult mild TBI management page; accessed October 3, 2026.",
    organization: "Centers for Disease Control and Prevention",
    authors: ["Centers for Disease Control and Prevention"],
    year: null,
    url: "https://www.cdc.gov/traumatic-brain-injury/media/pdfs/key_recommendations_adult_mTBI-508.pdf",
    sourceClass: "government_guidance",
    licenseLabel: "United States federal government work; third-party material, logos, and marks remain subject to their own terms",
    reuseStatus: "public_domain_conditions_apply",
    authority:
      "CDC adult mild-traumatic-brain-injury clinical recommendation sheet; publication year is not asserted because the document itself is undated.",
    usageRole: "evidence",
  },
  wsesPelvic: {
    id: "source.wses.pelvic-trauma-guideline.2017",
    title: "Pelvic trauma: WSES classification and guidelines",
    citation:
      "Coccolini F, Stahel PF, Montori G, et al. Pelvic trauma: WSES classification and guidelines. World J Emerg Surg. 2017;12:5. doi:10.1186/s13017-017-0117-6.",
    organization: "World Journal of Emergency Surgery / World Society of Emergency Surgery",
    authors: [
      "Federico Coccolini",
      "Philip F Stahel",
      "Giulia Montori",
      "Walter Biffl",
      "Tal M Horer",
      "Fausto Catena",
      "Yoram Kluger",
      "Ernest E Moore",
      "Andrew B Peitzman",
      "Rao Ivatury",
      "Raul Coimbra",
      "Gustavo Pereira Fraga",
      "Bruno Pereira",
      "Sandro Rizoli",
      "Andrew Kirkpatrick",
      "Ari Leppaniemi",
      "Roberto Manfredi",
      "Stefano Magnone",
      "Osvaldo Chiara",
      "Leonardo Solaini",
      "Marco Ceresoli",
      "Niccolo Allievi",
      "Catherine Arvieux",
      "George Velmahos",
      "Zsolt Balogh",
      "Noel Naidoo",
      "Dieter Weber",
      "Fikri Abu-Zidan",
      "Massimo Sartelli",
      "Luca Ansaloni",
    ],
    year: 2017,
    doi: "10.1186/s13017-017-0117-6",
    url: "https://link.springer.com/article/10.1186/s13017-017-0117-6",
    sourceClass: "peer_reviewed_guideline",
    licenseLabel:
      "Creative Commons Attribution 4.0 International (CC BY 4.0), https://creativecommons.org/licenses/by/4.0/; authors and journal credited in the citation; facts independently synthesized without adapting source expression",
    reuseStatus: "cc_by_4_0",
    authority:
      "International trauma guideline used for the anatomical binder-placement principle; this older single-source teaching point remains limited pending clinician review.",
    usageRole: "evidence",
  },
} as const satisfies Record<string, SourceSpec>;
