const fs=require('fs'),path=require('path'),crypto=require('crypto'),{chromium}=require('playwright');
const dir=__dirname,fragment=fs.readFileSync(path.join(dir,'recovery-layout.html'),'utf8'),assert=(v,m)=>{if(!v)throw new Error(m)};
const close=(a,b,e=.02)=>Math.abs(a-b)<=e;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1000,height:1200}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent(fragment);await page.locator('#recovery-art').waitFor();await page.waitForFunction(()=>document.querySelector('#recovery-art')?.dataset.model);const get=()=>page.locator('#recovery-art').evaluate(n=>JSON.parse(n.dataset.model));let m=await get();
assert(m.dimensions.cols===6&&m.dimensions.rows===6&&m.segments.length===24&&m.baySegments.length===8,'6x6/24/8 contract');assert(m.visibleBayCapacity===8&&m.activePartitions.length===4,'default furniture');assert(m.scaleContract.bedPhysical.lengthPx===186&&m.scaleContract.bedPhysical.widthPx===84&&m.scaleContract.stoolWidthPx===60&&m.scaleContract.stationBaseWidthPx===240,'reference scale contract');
for(const id of m.baySegments){const b=m.bays[id],d=m.draws[`${id}.bed`],mon=m.draws[`${id}.monitor`];assert(d&&mon,`${id} draws`);const expected=b.side==='N'||b.side==='S'?84:186;assert(close(d.physicalSpanPx,expected,.01),`${id} physical span`);const rise=d.groundContact.y-d.seatContact.y,reference=b.side==='N'||b.side==='S'?42.48:42.95;assert(Math.abs(rise-reference)<=1.5,`${id} cushion rise ${rise}`)}
for(const id of ['stool1','stool2']){const d=m.draws[id];assert(close(d.physicalSpanPx,60,.01)&&close(d.groundContact.y-d.seatContact.y,50.6818,.02),`${id} Examination scale`)}assert(close(m.draws.station.baseWidth,240,.01),'station base width');const stationScale=m.draws.station.scale;assert(close((1005-660)*stationScale,93.243,.1),'station facade height');
const expectedMon={N3:'monitorS',N4:'monitorS',S3:'monitorN',S4:'monitorN',WC:'monitorE',WD:'monitorE',EC:'monitorW',ED:'monitorW'};for(const[id,sprite]of Object.entries(expectedMon))assert(m.bays[id].monitor===sprite,`${id} inward monitor`);assert(new Set(Object.values(m.artAssignments).map(a=>a.sprite)).size===8,'eight distinct art assignments');
assert(['N1','N3','N4','N6'].every(id=>m.draws[`${id}.art`]&&m.wallArtPlacements[id].visible),'four north-wall artworks');assert(!Object.values(m.draws).some(draw=>draw?.mountedArt),'no partition-mounted art');assert(m.artAssignments.WD.wallPlacementSegment==='N1'&&m.artAssignments.ED.wallPlacementSegment==='N6','moved art ownership');
const sampleValid=async model=>page.evaluate(model=>{const proof=window.__recoveryProof,bad=[],round=v=>Math.round(v*1e10)/1e10;for(const [kind,groups] of [['door',model.routes],['bay',model.bayApproachRoutes],['stool',model.stoolRoutes]])for(const[id,route]of Object.entries(groups))for(let i=1;i<route.length;i++){const a=route[i-1],b=route[i],n=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/.02);for(let j=0;j<=n;j++){const t=j/n,p=j===0?a:j===n?b:{x:round(a.x+(b.x-a.x)*t),y:round(a.y+(b.y-a.y)*t)};if(!proof.valid(p)){bad.push({kind,id,p,a,b});break}}}return bad},model);
for(const id of m.segments){await page.evaluate(id=>{const p=window.__recoveryProof;p.state.doors.clear();p.toggle(id)},id);m=await get();assert(m.routes[id].length,`${id} route`);assert(m.visibleBayCapacity===(m.baySegments.includes(id)?7:8),`${id} capacity`);if(m.baySegments.includes(id)){assert(!m.draws[`${id}.bed`]&&!m.draws[`${id}.monitor`],`${id} furniture hidden`);const partition=m.partitions.find(p=>p.bays.includes(id));assert(!m.activePartitions.includes(partition.id),`${id} partition hidden`)}if(id==='N1'||id==='N3'||id==='N4'||id==='N6'){assert(!m.draws[`${id}.art`],`${id} owns moved wall art`)}if(id==='WC'||id==='WD'||id==='EC'||id==='ED')assert(m.draws['N1.art']&&m.draws['N6.art'],`${id} no longer owns moved art`);assert(Object.values(m.bayApproachRoutes).every(r=>r.length)&&Object.values(m.stoolRoutes).every(r=>r.length),`${id} uses reachable`);const bad=await sampleValid(m);assert(bad.length===0,`${id} sampled clearance ${JSON.stringify(bad[0])}`)}
await page.evaluate(()=>{const p=window.__recoveryProof;p.state.doors=new Set(['N3','S4','WC','ED','N1']);p.render()});m=await get();assert(m.visibleBayCapacity===4&&m.activePartitions.length===0&&m.draws['N4.bed']&&m.draws['S3.bed']&&m.draws['WD.bed']&&m.draws['EC.bed'],'mixed doors and unrelated restoration');assert((await sampleValid(m)).length===0,'mixed sampled clearance');
for(let i=1;i<=6;i++){await page.evaluate(i=>{const p=window.__recoveryProof;p.state.doors.clear();p.state.adjacent=new Set([`N${i}`]);p.render()},i);m=await get();assert(m.activeBays.length===8,`backing N${i} preserves beds`);for(const id of ['N1','N3','N4','N6'])assert(Boolean(m.draws[`${id}.art`])===(id!==`N${i}`),`backing N${i} art ownership ${id}`)}
await page.evaluate(()=>{const p=window.__recoveryProof;p.state.doors=new Set(p.segments);p.render()});m=await get();assert(m.visibleBayCapacity===0&&m.activePartitions.length===0&&m.segments.every(id=>m.routes[id].length),'all doors');
await page.evaluate(()=>{const p=window.__recoveryProof;p.state.doors.clear();p.render()});await page.locator('.recovery-hit[data-segment="N1"]').click({position:{x:30,y:35}});m=await get();assert(m.doors.includes('N1'),'canvas target click');await page.locator('[data-segment="N2"]:not(.recovery-hit)').focus();await page.keyboard.press('Enter');m=await get();assert(m.doors.includes('N2'),'keyboard activation');
assert(errors.length===0,errors.join('; '));await browser.close();const hash=crypto.createHash('sha256').update(fragment).digest('hex').toUpperCase();console.log(`PASS Recovery 6x6: 24 doors, 8 bays, partitions, routes, reference scales, click/keyboard; ${fragment.length} chars; SHA256 ${hash}`)})().catch(e=>{console.error(e.stack||e);process.exit(1)});
