import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { buildStandingGeometry, buildWalkGeometry } from '../../canonical-master/canonical-geometry.mjs';
import { V8_CALIBRATION } from '../green-rig-v8.mjs';
import { DIRECTIONAL_CALIBRATION } from '../directional/directional-rig-v1.mjs';
import { createStandardCharacterRenderer, standardWalkArmProjection } from '../../standard-atlas/standard-character-renderer.mjs';
import { triangulatedQuad } from '../../standard-atlas/normalized-lower-renderer.mjs';
import { loadNormalizedLowerParts } from '../../standard-atlas/normalized-lower-loader.mjs';
import { slotRect } from '../../standard-atlas/schema-v1.mjs';
import { leftEdge, perpendicular, rightEdge, section } from '../gray-overshirt-v2/lower-render-v2.mjs';

export const VIEWS=Object.freeze(['south','east','west','north']);
export const RIG=Object.freeze({
  canvas:{width:160,height:320,axisX:80,floorY:287},neckY:{south:121,east:118,west:118,north:109},torsoHemY:{south:197,east:197,west:197,north:197},
  lowerTextureScale:{south:.45,east:.43,west:.43,north:.45},lowerClothWidth:{south:28,east:25,west:25,north:33},shoeWidthScale:{south:1,east:1,west:1,north:1.3},profileLane:{hip:5,knee:5,ankle:5},
  headNeckOffsetX:{south:0,east:0,west:0,north:0},armLengths:{upper:40,forearm:32},armLengthsByView:{south:{upper:40,forearm:32},north:{upper:40,forearm:32}},
  bendSign:{south:{left:-1,right:1},east:{left:1,right:1},west:{left:-1,right:-1},north:{left:1,right:-1}},
  armMotion:{profileBackwardScale:.30,profileForwardScale:1.30,restWristReach:68,restWristReachByView:{south:68,east:70,west:70,north:68},handTargetOffset:{east:{left:4,right:4},west:{left:-4,right:-4}},frontReachRatio:.995,frontSwingYScale:.86,frontProjectionMinScale:.83,southSwingXScale:V8_CALIBRATION.projectionScale.x*.42,southSwingYScale:V8_CALIBRATION.projectionScale.y,northSwingXScale:.86,directionalSwingYScale:.84,outward:{south:{left:13,right:-13},east:{left:-1,right:-1},west:{left:1,right:1},north:{left:-12,right:12}}},
});
const standing=Object.fromEntries(VIEWS.map(view=>[view,buildStandingGeometry(view)])),walking=buildWalkGeometry();
function anatomicalGeometry(view,g){return view==='south'?{...g,joints:{left:g.joints.right,right:g.joints.left}}:g;}
function mapped(view,g){const map=p=>view==='south'?{x:80+(p.x-112)*V8_CALIBRATION.projectionScale.x,y:287-(296-p.y)*V8_CALIBRATION.projectionScale.y}:{x:80+(p.x-112)*(view==='north'?32/26:1),y:287-(296-p.y)*((287-DIRECTIONAL_CALIBRATION.target.hipY)/96)};return{hipCenter:map(g.hipCenter),joints:Object.fromEntries(['left','right'].map(side=>[side,Object.fromEntries(['hip','knee','ankle','soleContact','shoulder','wrist'].map(k=>[k,map(g.joints[side][k])]))]))};}
export async function loadRig(repo){const root=resolve(repo,'tools/character-mapping/layered-pilot/navy-vest-v1'),manifest=JSON.parse(readFileSync(resolve(root,'manifest-v1.json'),'utf8')),parts=manifest.parts,[upper,identity,lower]=await Promise.all(['upper','identity','lower'].map(page=>loadImage(resolve(root,manifest.pages[page].file)))),renderer=createStandardCharacterRenderer({profile:RIG,partRecord:id=>{const part=parts[id];if(!part)throw Error(`missing ${id}`);return part;},hasPart:id=>Boolean(parts[id]),pageImage:id=>id.startsWith('identity.')?identity:upper});return{manifest,parts,images:{upper,identity,lower},renderer,standardLower:loadNormalizedLowerParts(lower,parts)};}
export function standingPose(view){return{view,index:null,phaseId:'stand',geometry:standing[view]};}
export function walkingPose(view,index){const n=((index%8)+8)%8;return{view,index:n,phaseId:String(n+1).padStart(2,'0'),geometry:walking[view][String(n+1).padStart(2,'0')]};}
const get=(object,path)=>path.split('.').reduce((value,key)=>value?.[key],object);
const imagePixels=new WeakMap();
function pixelsFor(image){let cached=imagePixels.get(image);if(!cached){const canvas=createCanvas(image.width,image.height),context=canvas.getContext('2d');context.drawImage(image,0,0);cached={width:image.width,height:image.height,data:context.getImageData(0,0,image.width,image.height).data};imagePixels.set(image,cached);}return cached;}
const normalizedTextures=new WeakMap();
function normalizedTexture(part){let normalized=normalizedTextures.get(part);if(normalized)return normalized;const slot=slotRect(part.id),bounds=part.record.contentBounds,joint=part.landmarks.joint,isThigh=Boolean(joint.hip),start=isThigh?joint.hip:joint.knee,end=isThigh?joint.knee:joint.ankle,sourceUnderlap=isThigh?{top:4,bottom:6}:{top:6,bottom:4},rect={x:slot.x+bounds.x,y:slot.y+start.y-sourceUnderlap.top,width:bounds.width,height:end.y-start.y+sourceUnderlap.top+sourceUnderlap.bottom},pixels=pixelsFor(part.image),height=Math.max(2,Math.round(rect.height)),canvas=createCanvas(64,height),context=canvas.getContext('2d');context.imageSmoothingEnabled=false;for(let y=0;y<height;y++){const sourceY=Math.min(pixels.height-1,Math.max(0,Math.floor(rect.y+(y+.5)*rect.height/height))),x0=Math.max(0,Math.floor(rect.x)),x1=Math.min(pixels.width-1,Math.ceil(rect.x+rect.width)-1);let left=x1+1,right=x0-1;for(let x=x0;x<=x1;x++)if(pixels.data[(sourceY*pixels.width+x)*4+3]>=24){left=Math.min(left,x);right=Math.max(right,x);}if(right>=left)context.drawImage(part.image,left,sourceY,right-left+1,1,0,y,64,1);}normalized={image:canvas,rect:{x:0,y:0,width:64,height},sourceLongitudinal:{start,end,underlap:sourceUnderlap}};normalizedTextures.set(part,normalized);return normalized;}
export function drawNavyLowerLeg(context,loaded,view,side,joints){
  const leg=loaded.lower?.[view]?.[side];if(!leg?.thigh||!leg?.shin||!leg?.shoe)throw Error(`missing packed lower slots for ${view}/${side}`);
  const profile=view==='east'||view==='west',{thigh,shin,shoe}=leg,scale=RIG.lowerTextureScale[view],shoeHeight=shoe.rect.height*scale,clothWidth=RIG.lowerClothWidth[view],half=clothWidth/2,visualAnkle={x:joints.ankle.x,y:joints.soleContact.y-shoeHeight},trouserAnkle={x:visualAnkle.x,y:visualAnkle.y+2},upperLength=Math.hypot(joints.knee.x-joints.hip.x,joints.knee.y-joints.hip.y)||1,ux=(joints.knee.x-joints.hip.x)/upperLength,uy=(joints.knee.y-joints.hip.y)/upperLength,hipUnderlap=profile?10:8,hipTop={x:joints.hip.x-ux*hipUnderlap,y:joints.hip.y-uy*hipUnderlap},tn=perpendicular(joints.hip,joints.knee),sn=perpendicular(joints.knee,trouserAnkle),sum={x:tn.x+sn.x,y:tn.y+sn.y},sumLength=Math.hypot(sum.x,sum.y)||1,kn={x:sum.x/sumLength,y:sum.y/sumLength},an=profile?{x:Math.sign(sn.x)||1,y:0}:sn,hip=section(hipTop,tn,half),ankle=section(trouserAnkle,an,half),lowerLength=Math.hypot(trouserAnkle.x-joints.knee.x,trouserAnkle.y-joints.knee.y)||1,kneeThigh=section({x:joints.knee.x+(trouserAnkle.x-joints.knee.x)/lowerLength*1.5,y:joints.knee.y+(trouserAnkle.y-joints.knee.y)/lowerLength*1.5},kn,half),kneeShin=section({x:joints.knee.x-(joints.knee.x-joints.hip.x)/upperLength*1.5,y:joints.knee.y-(joints.knee.y-joints.hip.y)/upperLength*1.5},kn,half),cloth=createCanvas(160,320),clothContext=cloth.getContext('2d'),thighTexture=normalizedTexture(thigh),shinTexture=normalizedTexture(shin);
  triangulatedQuad(clothContext,thighTexture.image,thighTexture.rect,[hip[0],hip[1],kneeThigh[1],kneeThigh[0]]);triangulatedQuad(clothContext,shinTexture.image,shinTexture.rect,[kneeShin[0],kneeShin[1],ankle[1],ankle[0]]);clothContext.globalCompositeOperation='destination-in';clothContext.strokeStyle='#fff';clothContext.lineWidth=clothWidth;clothContext.lineCap='round';clothContext.lineJoin='round';clothContext.beginPath();clothContext.moveTo(hipTop.x,hipTop.y);clothContext.lineTo(joints.knee.x,joints.knee.y);clothContext.lineTo(trouserAnkle.x,trouserAnkle.y);clothContext.stroke();context.drawImage(cloth,0,0);
  const width=shoe.rect.width*scale*RIG.shoeWidthScale[view],height=shoeHeight;let x,y,cuffLeft=null,cuffRight=null,shoeAnkle=null;if(profile){const sourceAnkle=get(shoe.landmarks,'joint.ankle'),localAnkleX=sourceAnkle.x-(shoe.rect.x-slotRect(shoe.id).x);x=visualAnkle.x-localAnkleX*scale*RIG.shoeWidthScale[view];y=visualAnkle.y;cuffLeft=leftEdge(cloth,Math.floor(trouserAnkle.y-10),Math.ceil(trouserAnkle.y));cuffRight=rightEdge(cloth,Math.floor(trouserAnkle.y-10),Math.ceil(trouserAnkle.y));shoeAnkle={x:x+localAnkleX*scale*RIG.shoeWidthScale[view],y};}else{x=joints.soleContact.x-width/2;y=visualAnkle.y;}context.drawImage(shoe.image,shoe.rect.x,shoe.rect.y,shoe.rect.width,shoe.rect.height,x,y,width,height);
  return{joints,hipTop,visualAnkle,trouserAnkle,scale,clothWidth,kneeOverlap:3,shoeDestination:{x,y,width,height},shoeAnkle,soleY:y+height,cuffLeft,cuffRight,heelEdge:profile?(view==='east'?x:x+width):null};
}
function drawLeg(context,loaded,view,side,joints,bob){
  // The directional master places the anatomical North hip below this vest's
  // measured hem. Render frontal trouser cloth up to the garment seam while
  // retaining the authored knee, ankle, and floor contacts.
  let renderedJoints=view==='south'||view==='north'?{...joints,hip:{...joints.hip,y:RIG.torsoHemY[view]+bob-2}}:joints;
  if(view==='east'||view==='west'){const direction=view==='east'?1:-1,nearSide=view==='east'?'right':'left',lane=side===nearSide?direction:-direction;renderedJoints={...renderedJoints,hip:{...renderedJoints.hip,x:renderedJoints.hip.x+lane*RIG.profileLane.hip},knee:{...renderedJoints.knee,x:renderedJoints.knee.x+lane*RIG.profileLane.knee},ankle:{...renderedJoints.ankle,x:renderedJoints.ankle.x+lane*RIG.profileLane.ankle},soleContact:{...renderedJoints.soleContact,x:renderedJoints.soleContact.x+lane*RIG.profileLane.ankle}};}
  return drawNavyLowerLeg(context,{lower:loaded.standardLower},view,side,renderedJoints);
}
const PROFILE_LAYERS=Object.freeze(['backHair','farArm','lower','torso','nearArm','head','frontHair','prop']);
export function renderPose(loaded,pose){const {view}=pose,geometry=anatomicalGeometry(view,pose.geometry),rest=anatomicalGeometry(view,standing[view]),m=mapped(view,geometry),sm=mapped(view,rest),bob=Math.round(m.hipCenter.y-sm.hipCenter.y),near=view==='east'?'right':view==='west'?'left':null,far=near?(near==='left'?'right':'left'):null,torso=loaded.renderer.torsoPose(view,bob),projection=Object.fromEntries(['left','right'].map(side=>[side,standardWalkArmProjection({view,side,geometry,standingGeometry:rest,shoulder:torso.shoulders[side],profile:RIG})])),armTargets=Object.fromEntries(['left','right'].map(side=>[side,projection[side].target])),armOverrides=Object.fromEntries(['left','right'].map(side=>[side,projection[side].projectedLengths?{armLengths:projection[side].projectedLengths}:{}])),profile=view==='east'||view==='west',rendered=loaded.renderer.render({view,bob,armTargets,armOverrides,...(profile?{layerOrder:PROFILE_LAYERS,deferLowerToLayer:true}:{}),drawLower:context=>{const legs={};for(const side of near?[far,near]:['left','right'])legs[side]=drawLeg(context,loaded,view,side,m.joints[side],bob);return legs;}});return{canvas:rendered.canvas,metadata:{view,index:pose.index,phaseId:pose.phaseId,bob,mappedGeometry:m,legs:rendered.metadata.lower,lowerCanvas:rendered.metadata.lowerCanvas,arms:rendered.metadata.arms,armProjection:projection,torso:rendered.metadata.torso,head:rendered.metadata.head,near,far,layerOrder:rendered.metadata.layerOrder,bounds:rendered.metadata.bounds}};}
