import { describe,expect,it } from "vitest";
import { MALIGNANT_POLYP } from "./malignant-polyp"; import { DIALYSIS_NUTRITION } from "./dialysis-nutrition"; import { RECURRENT_GASTRIC_ULCER } from "./recurrent-gastric-ulcer";
const families=[MALIGNANT_POLYP,DIALYSIS_NUTRITION,RECURRENT_GASTRIC_ULCER],concepts=families.flatMap(x=>x.authoringConcepts),questions=families.flatMap(x=>x.questions),cases=families.flatMap(x=>x.cases),claims=families.flatMap(x=>x.claims),sources=families.flatMap(x=>x.sources);
describe("GS-028 October 2 M2b nonurgent content",()=>{
 it("has six objectives and twenty-four explicit variants",()=>{expect(concepts).toHaveLength(6);expect(questions).toHaveLength(24);for(const c of concepts){const q=questions.filter(x=>x.conceptId===c.id);expect(q).toHaveLength(4);expect(new Set(q.map(x=>x.patientPresentation))).toHaveLength(4);expect(new Set(q.map(x=>x.stem))).toHaveLength(4);}});
 it("uses one key and specific correction feedback",()=>{for(const q of questions){expect(q.answerChoices.filter(x=>x.isCorrect)).toHaveLength(1);for(const a of q.answerChoices.filter(x=>!x.isCorrect))expect(a.distractorRationale?.length).toBeGreaterThan(35);expect(q.reviewStatus).toBe("needs_clinician_review");}});
 it("keeps all six objectives independently eligible",()=>{for(const c of concepts)expect(cases.some(x=>x.decisionNodes.length===1&&x.decisionNodes[0]?.primaryConceptId===c.id)).toBe(true);for(const c of cases){expect(c.earliestFacilityStage).toBe(0);expect(c.requiredCapabilityIds).toEqual([]);}});
 it("keeps dialysis facts inside documented inpatient contexts",()=>{for(const q of questions.filter(x=>x.conceptId.startsWith("concept.dialysis-nutrition")))expect(q.patientPresentation).toMatch(/hospital|admission|inpatient/i);});
 it("has complete reverse source mappings and no invented services",()=>{for(const c of claims)for(const id of c.sourceIds)expect(sources.find(s=>s.id===id)?.evidenceClaimIds).toContain(c.id);expect(families.flatMap(x=>x.serviceContracts)).toEqual([]);for(const c of cases)for(const n of c.decisionNodes){expect(n.resultGateAfter).toBeNull();expect(n.answerChoices.every(a=>a.serviceRequest===null)).toBe(true);}});
 it("does not reveal the key as the uniquely longest option",()=>{for(const q of questions){const key=q.answerChoices.find(x=>x.isCorrect)!;expect(key.label.length,q.id).toBeLessThanOrEqual(Math.max(...q.answerChoices.filter(x=>!x.isCorrect).map(x=>x.label.length)));}});
});
