import { describe,expect,it } from "vitest";
import { answerChoiceTimingRegistryEntrySchema,syntheticClinicalCaseSchema,testedConceptSchema } from "../../schema";
import { GS028_20261002_AUTHORING_CONCEPTS as concepts,GS028_20261002_TESTED_CONCEPTS as tested,GS028_20261002_QUESTIONS as questions,GS028_20261002_CASES as cases,GS028_20261002_CLAIMS as claims,GS028_20261002_SOURCES as sources,GS028_20261002_TIMING_ENTRIES as timing,GS028_20261002_SERVICE_CONTRACTS as serviceContracts,GS028_20261002_BATCH_MANIFEST as manifest } from "./pre-endoscopy-batch";

describe("GS-028 October 2 pre-Endoscopy authoring package",()=>{
 it("contains twenty objectives and eighty clinically varied questions",()=>{expect(concepts).toHaveLength(20);expect(questions).toHaveLength(80);expect(manifest.contentVersion).toBe("development-batch.2026-10-02.pre-endoscopy.1");for(const c of concepts){const q=questions.filter(x=>x.conceptId===c.id);expect(q).toHaveLength(4);expect(new Set(q.map(x=>x.patientPresentation))).toHaveLength(4);expect(new Set(q.map(x=>x.stem))).toHaveLength(4);}});
 it("reports the complete additive package inventory",()=>{expect(manifest).toMatchObject({authoringConceptCount:20,testedConceptCount:20,questionVariantCount:80,caseCount:78,decisionNodeCount:80,sourceCount:17,evidenceClaimCount:37,timingEntryCount:80,publicReleaseAuthorized:false});});
 it("keeps every objective independently eligible at stage zero",()=>{for(const c of concepts){expect(c.earliestFacilityStage).toBe(0);expect(cases.some(x=>x.decisionNodes.length===1&&x.decisionNodes[0]?.primaryConceptId===c.id)).toBe(true);}for(const c of cases){expect(c.releasePointId).toBe("release.l0.clinic_evaluation");expect(c.earliestFacilityStage).toBe(0);expect(c.requiredCapabilityIds).toEqual([]);}});
 it("uses one randomized key, complete named questions, and draft review status",()=>{for(const q of questions){expect(q.answerChoices).toHaveLength(4);expect(q.answerChoices.filter(x=>x.isCorrect)).toHaveLength(1);expect(q.stem).toMatch(/\?$/);expect(q.patientPresentation).toContain("{patientName}");expect(q.reviewStatus).toBe("needs_clinician_review");expect(q.approvedInstantiationProfiles.length).toBeGreaterThan(0);}for(const c of cases)for(const n of c.decisionNodes)expect(n.shuffleAnswers).toBe(true);});
 it("maps every claim bidirectionally to complete permitted source records",()=>{const ci=new Set(claims.map(x=>x.id)),si=new Set(sources.map(x=>x.id));expect(ci.size).toBe(claims.length);expect(si.size).toBe(sources.length);for(const q of questions)for(const id of q.supportingEvidenceClaimIds)expect(ci.has(id)).toBe(true);for(const c of claims)for(const id of c.sourceIds){expect(si.has(id)).toBe(true);expect(sources.find(s=>s.id===id)?.evidenceClaimIds).toContain(c.id);}for(const s of sources){expect(s.completeCitation.length).toBeGreaterThan(30);expect(s.officialUrl).toMatch(/^https:/);expect(s.reuseStatus).not.toBe("unknown");for(const id of s.evidenceClaimIds)expect(ci.has(id)).toBe(true);}});
 it("provides timing for every service request and declares each service",()=>{expect(timing).toHaveLength(80);const declared=new Set(serviceContracts.map(x=>x.serviceId));for(const c of cases)for(const n of c.decisionNodes){const e=timing.find(x=>x.questionVariantId===n.questionVariantId)!;for(const a of n.answerChoices)if(a.serviceRequest){expect(declared.has(a.serviceRequest.serviceId)).toBe(true);expect(e.classification.kind).toBe("test_choices");if(e.classification.kind==="test_choices")expect(e.classification.choices.find(x=>x.choiceId===a.id)?.timing.kind).toBe("test");}}});
 it("passes runtime schemas with unique ids",()=>{for(const c of tested)testedConceptSchema.parse(c);for(const c of cases)syntheticClinicalCaseSchema.parse(c);for(const t of timing)answerChoiceTimingRegistryEntrySchema.parse(t);expect(new Set(cases.map(x=>x.id)).size).toBe(cases.length);expect(new Set(cases.flatMap(x=>x.decisionNodes).map(x=>x.id)).size).toBe(cases.flatMap(x=>x.decisionNodes).length);expect(new Set(questions.map(x=>x.id)).size).toBe(questions.length);});
 it("uses only declared existing services and two purposeful ultrasound gates",()=>{const ids=new Set(serviceContracts.map(x=>x.serviceId));expect(ids).toEqual(new Set(["service.ultrasound","service.diagnostic_breast_imaging","service.breast_mri","service.ct"]));const gates=cases.flatMap(x=>x.decisionNodes).filter(x=>x.resultGateAfter);expect(gates).toHaveLength(2);for(const n of gates)expect(n.resultGateAfter?.resultTypeId).toBe("service.ultrasound");for(const c of cases)expect(c.decisionNodes.at(-1)?.resultGateAfter).toBeNull();});
 it("does not reveal a key as the uniquely longest option",()=>{for(const q of questions){const key=q.answerChoices.find(x=>x.isCorrect)!;expect(key.label.length,q.id).toBeLessThanOrEqual(Math.max(...q.answerChoices.filter(x=>!x.isCorrect).map(x=>x.label.length)));}});
 it("assigns neutral timing to every answer choice that names a test",()=>{const testLabel=/\b(?:MRI|CT|CTA|ultrasound|radiograph|scintigraphy|colonoscopy|colonoscopic|biopsy|SLNB|node sampling|local endoscopic excision)\b/i;const noTestLabel=/\b(?:no|without|avoid|defer|skip|do not|withhold)\b/i;let namedChoices=0;for(const q of questions){const entry=timing.find(x=>x.questionVariantId===q.id)!;for(const choice of q.answerChoices){if(!testLabel.test(choice.label)||noTestLabel.test(choice.label))continue;namedChoices+=1;expect(entry.classification.kind,`${q.id}/${choice.id}`).toBe("test_choices");if(entry.classification.kind==="test_choices")expect(entry.classification.choices.find(x=>x.choiceId===choice.id)?.timing.kind,`${q.id}/${choice.id}`).toBe("test");}}expect(namedChoices).toBeGreaterThan(0);});
});
