import { describe, expect, it } from "vitest";
import { EARLY_LEVELS_20260913_CASES } from "@gamify-surgery/clinical-content";
import { createInitialGameState, deserializeGameState, gameReducer, getCurrentQuestion, serializeGameState, type GameState } from "../src";

function prepared(seed:string,level:0|1|2=2):GameState{const state=createInitialGameState(undefined,{campaignId:`campaign.early.${seed}`,campaignSeed:seed,createdAtRealMs:0});state.facilityLevel=level;state.encounters={};state.openChartEncounterId=null;state.attendedEncounterId=null;state.nextRoutineArrivalTick=Number.MAX_SAFE_INTEGER;return state;}
function ready(state:GameState,encounterId:string,prefix:string):GameState{let next=state;for(let attempt=0;attempt<1500;attempt+=1){if(getCurrentQuestion(next,encounterId))return next;const encounter=next.encounters[encounterId]!;next=encounter.lifecycle==="waiting_unopened"&&encounter.patientMovement===null?gameReducer(next,{type:"OPEN_CHART",operationId:`${prefix}.open.${attempt}`,encounterId}):gameReducer(next,{type:"ADVANCE_TICK",operationId:`${prefix}.tick.${attempt}`});}throw new Error(`${encounterId} did not become ready`);}
function submit(state:GameState,encounterId:string,correct:boolean,operationId:string,reviewedAtMs:number){const question=getCurrentQuestion(state,encounterId)!;const choice=question.node.answerChoices.find((item)=>item.isCorrect===correct)!;return gameReducer(state,{type:"SUBMIT_ANSWER",operationId,encounterId,decisionNodeId:question.node.id,answerChoiceId:choice.id,reviewedAtMs});}
function acknowledge(state:GameState,encounterId:string,operationId:string){const encounter=state.encounters[encounterId]!;return gameReducer(state,{type:"ACKNOWLEDGE_DECISION_FEEDBACK",operationId,encounterId,decisionNodeId:encounter.steps[encounter.currentNodeIndex]!.decisionNodeId});}

describe("September 13 early-level production flows",()=>{
 it.each(EARLY_LEVELS_20260913_CASES.map((clinicalCase,index)=>[index,clinicalCase] as const))("runs case %s through each authored node with one FSRS review",(index,clinicalCase)=>{const encounterId=`encounter.early.${index}`;let state=prepared(`all-${index}`,clinicalCase.earliestFacilityStage);state=gameReducer(state,{type:"ADMIT_PATIENT",operationId:`early.${index}.admit`,encounterId,caseId:clinicalCase.id,patientDisplayName:`Early Patient ${index}`,arrivalClass:"routine"});expect(state.operationReceipts[`early.${index}.admit`]?.status).toBe("applied");state=ready(state,encounterId,`early.${index}.first`);const first=getCurrentQuestion(state,encounterId)!;state=submit(state,encounterId,true,`early.${index}.first.answer`,index+1);expect(state.learningHistories[first.node.primaryConceptId]?.reviews).toHaveLength(1);if(clinicalCase.decisionNodes.length===1){expect(state.encounters[encounterId]).toMatchObject({lifecycle:"resolved_summary_available",resolutionReason:"completed",pendingResult:null});return;}state=acknowledge(state,encounterId,`early.${index}.first.ack`);const gate=clinicalCase.decisionNodes[0]!.resultGateAfter!;const pending=state.encounters[encounterId]!.pendingResult!;expect(pending).toMatchObject({resultTypeId:gate.resultTypeId});expect(pending.dueTick).toBeGreaterThan(state.facilityTick);while(state.facilityTick<pending.dueTick){expect(getCurrentQuestion(state,encounterId)).toBeNull();expect(state.encounters[encounterId]!.deliveredResultNarratives).toEqual([]);state=gameReducer(state,{type:"ADVANCE_TICK",operationId:`early.${index}.wait.${state.facilityTick}`});}state=ready(state,encounterId,`early.${index}.second`);expect(state.encounters[encounterId]!.deliveredResultNarratives).toContain(gate.resultNarrative);const second=getCurrentQuestion(state,encounterId)!;expect(second.node.primaryConceptId).toBe(clinicalCase.decisionNodes[1]!.primaryConceptId);state=submit(state,encounterId,true,`early.${index}.second.answer`,index+10000);expect(state.encounters[encounterId]).toMatchObject({lifecycle:"resolved_summary_available",resolutionReason:"completed"});expect(state.learningHistories[second.node.primaryConceptId]?.reviews).toHaveLength(1);});

 it("rejects a case before its authored facility stage",()=>{const state=gameReducer(prepared("stage",0),{type:"ADMIT_PATIENT",operationId:"early.stage.reject",encounterId:"encounter.stage",caseId:"case.pancreatic-pseudocyst.early-satiety",patientDisplayName:"Stage Patient",arrivalClass:"routine"});expect(state.operationReceipts["early.stage.reject"]).toMatchObject({status:"rejected",message:"This patient becomes eligible at Level 2."});expect(state.encounters["encounter.stage"]).toBeUndefined();});

 it("resolves urgent asplenia fever without scheduling a test",()=>{const encounterId="encounter.urgent";let state=gameReducer(prepared("urgent",0),{type:"ADMIT_PATIENT",operationId:"early.urgent.admit",encounterId,caseId:"case.asplenia-fever.evening-fever",patientDisplayName:"Urgent Patient",arrivalClass:"routine"});state=ready(state,encounterId,"early.urgent");state=submit(state,encounterId,true,"early.urgent.answer",1);expect(state.encounters[encounterId]).toMatchObject({lifecycle:"resolved_summary_available",resolutionReason:"completed",pendingResult:null});});

 it("preserves a corrected-forward pending result, identity, due tick, and choice order through reload",()=>{const clinicalCase=EARLY_LEVELS_20260913_CASES.find((item)=>item.id==="case.lynch-tumor.new-diagnosis")!;const encounterId="encounter.persist";let state=gameReducer(prepared("persist",1),{type:"ADMIT_PATIENT",operationId:"early.persist.admit",encounterId,caseId:clinicalCase.id,patientDisplayName:"Persistent Patient",arrivalClass:"routine"});state=ready(state,encounterId,"early.persist");const first=getCurrentQuestion(state,encounterId)!;const order=first.node.answerChoices.map((choice)=>choice.id);state=submit(state,encounterId,false,"early.persist.answer",99);expect(state.encounters[encounterId]!.steps[0]!.answer).toMatchObject({correct:false,correctedForward:true,ratingIntent:"Again"});state=acknowledge(state,encounterId,"early.persist.ack");const pending=state.encounters[encounterId]!.pendingResult!;const restored=deserializeGameState(serializeGameState(state));expect(restored.encounters[encounterId]!.pendingResult).toEqual(pending);expect(restored.encounters[encounterId]!.pendingResult?.dueTick).toBe(pending.dueTick);expect(restored.encounters[encounterId]!.patientDisplayName).toBe("Persistent Patient");expect(restored.encounters[encounterId]!.frozenCase).toEqual(state.encounters[encounterId]!.frozenCase);expect(restored.encounters[encounterId]!.frozenCase.decisionNodes[0]!.answerChoices.map((choice)=>choice.id)).toEqual(order);expect(restored.learningHistories[first.node.primaryConceptId]?.reviews).toHaveLength(1);});
});
