// Private derivative of the approved waiting-room/shared-lab proof pattern.
// Writes only this assigned lane; frozen sources guarded before every build.
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import * as Geometry from './geometry.mjs';import {decode,sha,bounds} from '../assets/image-utils.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../../../../..'),lab=path.resolve(here,'../../../touchup-2026-10');
const read=f=>JSON.parse(fs.readFileSync(path.join(here,f),'utf8')),write=(f,x)=>fs.writeFileSync(path.join(here,f),JSON.stringify(x,null,2)+'\n');
const baseline=read('../assets/reference-baseline.json'),layout=read('layout-baseline.json'),actorBaseline=read('actor-baseline.json'),presentation=read('presentation-contract.json'),metadata=read('../assets/processed/metadata.json'),contract=read('asset-contract.json');
const stoolDerivation=read('../assets/derived/stool-backless-manifest.json'),backlessFile=path.resolve(here,'../assets/derived',stoolDerivation.output.file);
if(sha(path.join(repo,stoolDerivation.source.path))!==stoolDerivation.source.sha256||sha(backlessFile)!==stoolDerivation.output.sha256)throw Error('Backless stool provenance/hash mismatch');
for(const file of ['lab/design-rooms.js','lab/lab.js','build/lab-data.json','build/room-touchups.mjs']){const full=path.join(lab,file),rel=path.relative(repo,full).replaceAll('\\','/');if(sha(full)!==baseline.files[rel])throw Error('Concurrent shared lab change: '+rel);}
const room=structuredClone(layout.room),nav=structuredClone(layout.navigation),assets={};nav.privateProofRouteModel=presentation;
for(const r of room.records){const spec=layout.assets[r.assetId],id=Object.keys(contract.assets).find(id=>contract.assets[id].assetId===r.assetId);
 if(id){const m=metadata.assets[id],file=path.resolve(here,'../assets/processed',m.file);if(sha(file)!==m.outputSha256)throw Error('Native sprite changed '+id);r.sourceRect=[0,0,...m.canvas];assets[r.assetId]={...spec,src:'../assets/processed/'+m.file,size:m.canvas,prepared:true,preparedId:id};r.doorOwners=Geometry.ownersFor(room,r);if(r.depthPolicy==='wall')r.backedOwners=r.doorOwners.filter(s=>s[0]==='N');}
 else{const file=path.resolve(lab,'lab',spec.src);assets[r.assetId]={...spec,src:path.relative(here,file).replaceAll('\\','/'),reusedApproved:true,sha256:sha(file)};}
 if(r.id==='stool'){r.sourceRect=[...stoolDerivation.output.sourceRect];assets[r.assetId]={...assets[r.assetId],src:'../assets/derived/'+stoolDerivation.output.file,sourceRect:r.sourceRect,size:stoolDerivation.output.canvas,sha256:stoolDerivation.output.sha256,derivedForOwnerRevision:true,approvedSource:stoolDerivation.source,derivationManifest:'../assets/derived/stool-backless-manifest.json'};}
}
for(const fit of presentation.actors){const s=room.supports.find(s=>s.id===fit.supportId);s.authoredSeat={...s.seat};s.seat={x:fit.seat[0],y:fit.seat[1]};s.recordId=fit.recordId;s.character=fit.characterId;}
const frontManifest=JSON.parse(fs.readFileSync(path.join(here,'../../pediatric-waiting/assets/derived/occluder-manifest.json'),'utf8')).entries.west;
const frontFile=path.join(here,'../../pediatric-waiting/assets/derived',frontManifest.file);if(sha(frontFile)!==frontManifest.sha256)throw Error('Approved armrest changed');
assets['design:reuse:chair-west-front']={src:'../../pediatric-waiting/assets/derived/'+frontManifest.file,size:frontManifest.canvas,sourceRect:[0,0,...frontManifest.canvas],reusedApproved:true,derivedApproved:true,sha256:frontManifest.sha256};
room.records.push({...structuredClone(room.records.find(r=>r.id==='parentChair')),id:'parentChair:front',assetId:'design:reuse:chair-west-front',sourceRect:[0,0,...frontManifest.canvas],depthPolicy:'authored-layer',depthKey:2.8802,overlayFor:'parentChair'});
room.notes=['Owner-approved pediatric exam with requested stool revision: child east on the north-south table; clinician west entirely above the derived backless stool; parent west in the same room behind the front armrest.','Manager-directed game door model: 3x3 room with twelve one-tile wall sections; all bulk and independent controls work.',...presentation.notes];
const shared=JSON.parse(fs.readFileSync(path.join(lab,'build/lab-data.json'),'utf8'));
const data={rooms:shared.rooms.filter(r=>r.proofId==='hallway'),navigation:{[room.definitionId]:nav},atlases:{},characterMetrics:actorBaseline.characterMetrics,characters:actorBaseline.characters,pediatricPresentation:presentation,previewBaseClearances:[]};
for(const [key,entry]of Object.entries(actorBaseline.actorHashes)){if(sha(path.join(repo,entry.path))!==entry.sha256)throw Error('Selected actor pose changed '+key);}
const registry=JSON.parse(fs.readFileSync(path.join(repo,actorBaseline.registryPath),'utf8'));const child=actorBaseline.characters.find(c=>c.id==='level3-roster-v2.021');if(JSON.stringify(child)!==JSON.stringify(registry.characters.find(c=>c.id===child.id)))throw Error('Selected pediatric metadata changed');
for(const r of room.records){const entry=metadata.assets[assets[r.assetId].preparedId];if(!entry||entry.anchorKind!=='floor')continue;const im=await decode(path.resolve(here,'../assets/processed',entry.file)),[w,h]=entry.canvas,bottom=entry.outputOpaqueBounds.bottom,band=im.context.getImageData(0,bottom-7,w,8),b=bounds(band.data,w,8,160),d=Geometry.fixturePlacement(r,entry);
 data.previewBaseClearances.push({id:r.id+':measured-base',recordId:r.id,footprint:{left:d.x/120+b.left*d.w/w/120,top:d.y/120+(bottom-7+b.top)*d.h/h/120,width:b.width*d.w/w/120,height:b.height*d.h/h/120},basis:'Actual alpha >=160 envelope in last eight native base rows'});
}
// Existing rolling stool has no authored footprint; inspect only its actual
// opaque wheel contact band, not its lifted cushion or character legs.
const stool=room.records.find(r=>r.id==='stool'),stoolImage=await decode(path.resolve(here,assets[stool.assetId].src)),sr=stool.sourceRect,stoolBand=stoolImage.context.getImageData(sr[0],sr[1]+sr[3]-32,sr[2],32),sb=bounds(stoolBand.data,sr[2],32,160),sd=Geometry.fixturePlacement(stool);
data.previewBaseClearances.push({id:'stool:measured-wheels',recordId:'stool',footprint:{left:sd.x/120+sb.left*sd.w/sr[2]/120,top:sd.y/120+(sr[3]-32+sb.top)*sd.h/sr[3]/120,width:sb.width*sd.w/sr[2]/120,height:sb.height*sd.h/sr[3]/120},basis:'Reused rolling stool actual final 32 source rows of opaque wheels'});
write('data.json',data);
fs.writeFileSync(path.join(here,'design-rooms.js'),'// Private painted snapshot; frozen source layout in layout-baseline.json.\n'+Object.entries({DESIGN_ASSETS:assets,DESIGN_ROOMS:[room],DESIGN_NAVIGATION:data.navigation,PREPARED_METADATA:metadata,ASSET_CONTRACT:contract}).map(([k,v])=>'export const '+k+' = '+JSON.stringify(v)+';').join('\n')+'\n');
fs.copyFileSync(path.join(lab,'build/room-touchups.mjs'),path.join(here,'room-touchups.mjs'));
let renderer=fs.readFileSync(path.join(lab,'lab/lab.js'),'utf8').replaceAll('\r\n','\n');
function replace(a,b){if(!renderer.includes(a))throw Error('Renderer marker missing: '+a);renderer=renderer.replace(a,b);}
function block(start,next,body){const a=renderer.indexOf(start),b=renderer.indexOf(next,a+start.length);if(a<0||b<0)throw Error('Renderer block missing: '+start);renderer=renderer.slice(0,a)+body+'\n\n'+renderer.slice(b);}
replace('"../build/room-touchups.mjs"','"./room-touchups.mjs"');
replace('import { DESIGN_ASSETS, DESIGN_NAVIGATION, DESIGN_ROOMS }','import * as Geometry from "./geometry.mjs";\nimport { DESIGN_ASSETS, DESIGN_NAVIGATION, DESIGN_ROOMS, PREPARED_METADATA, ASSET_CONTRACT }');
replace('const ART_ROOT = "../../../../apps/player/public/";','const ART_ROOT = "../../../../../apps/player/public/";');
replace('scene: "room", view: "split", roomId: "laboratory",','scene: "room", view: "proposed", roomId: "pediatric-exam",\n  parents: true, children: true, clinicians: true, contacts: false, bases: false,');
replace('fetch("../build/lab-data.json")','fetch("./data.json")');
block('function roomSegments(room) {','const parseSeg','function roomSegments(room) { return Geometry.roomSegments(room); }');
block('function paintCaps(g, P, proposed) {','function paintProposedWall',fs.readFileSync(path.join(here,'shell-painter.js'),'utf8').split('function paintSouth')[0]);
block('function paintSouth(g, P, proposed) {','// Soft contact shadow',fs.readFileSync(path.join(here,'shell-painter.js'),'utf8').slice(fs.readFileSync(path.join(here,'shell-painter.js'),'utf8').indexOf('function paintSouth')));
replace('function recordVisible(rec, P) { return TU.isTouchupRecordVisible(rec, P.doors, P.backed); }','function recordVisible(rec, P) { return Geometry.visible(rec, P.doors, P.backed); }');
replace('const d = { kind: "fixture", id: rec.id, img, src: rec.sourceRect, x: P.ox + lx * T, y: P.oy + ly * T, w: w * T, h: h * T, py: painterY(rec), rec };','const prepared=PREPARED_METADATA.assets[DESIGN_ASSETS[rec.assetId].preparedId];\n    const d={kind:"fixture",id:rec.id,img,src:rec.sourceRect,...Geometry.fixturePlacement(rec,prepared,T,P.ox,P.oy),py:painterY(rec),rec,prepared};');
block('function actorPlacements(P) {','async function drawImageRec(g, d)','function actorPlacements(P) { return Geometry.actorPlacements(P,data,state).map(a=>({...a,url:ART_ROOT+a.url})); }');
block('function passableThroughDoors(P) {','// ---------- routes ----------','function passableThroughDoors(P) { return Geometry.passableThroughDoors(P,navFor(P.room)); }');
block('function blockedTiles(P) {','function bfs(P,','function blockedTiles(P) { const pass=new Set(passableThroughDoors(P).map(x=>x.fixture)); return new Set(navFor(P.room).solidFixtures.filter(f=>!pass.has(f.id)).flatMap(f=>f.blockedTiles.map(t=>t.x+","+t.y))); }');
block('function computeRoutes(P) {','function designBlockers(P) {','function computeRoutes(P) { return Geometry.computeRoutes(P,navFor(P.room),data.previewBaseClearances); }');
block('function designBlockers(P) {','// Every wall segment','function designBlockers(P) { return Geometry.designBlockers(P,navFor(P.room)); }\nfunction decorConflicts(P,routes) { return Geometry.decorConflicts(P,navFor(P.room),routes,data.previewBaseClearances); }');
block('function doorZoneViolations(P) {','// Owner revision: items never overlap a wall.','function doorZoneViolations(P) { return Geometry.doorZoneViolations(P); }');
replace('if (params.get("scene") === "building") state.scene = "building";','// Isolated single-room proof.');replace('if (params.get("view")) state.view = params.get("view");','// Always painted view.');
replace('async function draw() {\n  const token = ++drawToken;','async function draw() {\n  document.body.dataset.ready="0";\n  const token = ++drawToken;');
replace('return { statusLines, bad };','if(state.contacts||state.bases||state.routes)for(const P of placements)paintCandidateDiagnostics(g,P,collected.get(P));\n  return { statusLines, bad };');
replace('Door ${p.door} opens onto the ${p.fixture}; the game already allows it.','Door ${p.door} uses the frozen layout pass-through rule for ${p.fixture}.');
replace('img.onerror = () => { console.warn("missing", src); resolve(null); };','img.onerror = () => { console.error("Missing proof image",src); resolve(null); };');
const checkAt=renderer.indexOf('function check(roomId, doors, backed) {');if(checkAt<0)throw Error('Missing check export');
renderer=renderer.slice(0,checkAt)+'function check(roomId,doors,backed) { const room=rooms.get(roomId);return Geometry.check(room,navFor(room),doors,backed,data.previewBaseClearances); }\nwindow.__lab={check,state,draw,rooms,data,assets:DESIGN_ASSETS,metadata:PREPARED_METADATA,contract:ASSET_CONTRACT,computeRoutes,actorPlacements,collectDrawables,recordVisible,painterY,buildScene,roomSegments,buildRoomControls,paintCaps,paintFloor,render};\n'+fs.readFileSync(path.join(here,'extension.js'),'utf8');
fs.writeFileSync(path.join(here,'lab.js'),renderer);
write('proof-manifest.json',{schemaVersion:1,status:'owner_approved_stool_revision_pending_manager_validation',designApproval:true,ownerApproval:{date:'2026-10-08',quote:stoolDerivation.ownerQuote,...stoolDerivation.approval},runtimeIntegration:false,completeArtwork:true,reviewURL:'http://127.0.0.1:4191/tools/room-design/level-4/pediatric-exam/proof/index.html',reviewOrigin:'http://127.0.0.1:4191',ownerPlaytestOrigin:'http://127.0.0.1:4173',layoutBaselineSha256:sha(path.join(here,'layout-baseline.json')),actorBaselineSha256:sha(path.join(here,'actor-baseline.json')),presentationContractSha256:sha(path.join(here,'presentation-contract.json')),preparedMetadataSha256:sha(path.join(here,'../assets/processed/metadata.json')),stoolDerivationManifestSha256:sha(path.join(here,'../assets/derived/stool-backless-manifest.json')),stoolDerivation,dataSha256:sha(path.join(here,'data.json')),rendererSha256:sha(path.join(here,'lab.js')),geometrySha256:sha(path.join(here,'geometry.mjs')),preparedHashes:Object.fromEntries(Object.entries(metadata.assets).map(([id,m])=>[id,m.outputSha256])),reusedApproved:Object.fromEntries(Object.entries(assets).filter(([,a])=>a.reusedApproved)),actorHashes:actorBaseline.actorHashes,doorModel:presentation.doorModel,privateRouteModel:{basis:presentation.notes.at(-1),step:Geometry.STEP,actorRadius:Geometry.ACTOR_RADIUS,preservesSharedNavigation:true,staticSeatingSeparate:true},seatRegistrations:presentation.actors,sourceGeometryUnchanged:true,sharedFilesChanged:false,browserValidation:'pending_manager'});
console.log('BUILD PASS pediatric-exam-only proof; 5 native sprites, derived backless stool below clinician, approved front armrest, 3 seated identities, 12 one-tile door sections');
