// MANAGER ONLY: real browser captures are distinct from Node-native inspection.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('@playwright/test'),{listen}=require('./browser-errors.cjs');
const here=__dirname,out=path.join(here,'evidence'),url=process.env.PEDIATRIC_EXAM_PROOF_URL||'http://127.0.0.1:4191/tools/room-design/level-4/pediatric-exam/proof/index.html';
const doors=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'],backed=['N1','N2','N3'];
const cases=[['exam-painted',{}],['exam-empty',{actors:false}],['exam-parent',{children:false,clinicians:false}],['exam-child',{parents:false,clinicians:false}],['exam-clinician',{parents:false,children:false}],['exam-all-doors',{doors}],['exam-backed',{backed}],['exam-all-backed',{doors,backed}],['exam-contacts',{doors:['N2','S2','WA','EC'],routes:true,grid:true,contacts:true,bases:true}],['exam-counter-door',{doors:['N3'],routes:true}],['exam-toy-door',{doors:['WC'],routes:true}]];
(async()=>{const manifestBytes=fs.readFileSync(path.join(here,'proof-manifest.json')),manifest=JSON.parse(manifestBytes),proofManifestSha256=crypto.createHash('sha256').update(manifestBytes).digest('hex').toUpperCase();assert.deepEqual([manifest.doorModel.count,manifest.doorModel.perWall,manifest.doorModel.spanTiles,manifest.doorModel.kind],[12,3,1,'game-one-tile']);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),events=listen(page);await page.goto(url);await page.waitForFunction(()=>document.body.dataset.ready==='1');
 assert.deepEqual(await page.evaluate(()=>window.__lab.roomSegments(window.__lab.rooms.get('pediatric-exam'))),doors);assert.deepEqual(await page.evaluate(()=>window.__lab.data.pediatricPresentation.doorModel),manifest.doorModel);
 assert.equal(await page.evaluate(()=>window.__lab.assets['design:reuse:stool'].sha256),manifest.stoolDerivation.output.sha256);assert.equal(await page.evaluate(()=>window.__lab.assets['design:reuse:stool'].derivedForOwnerRevision),true);
 for(const[name,settings]of cases){const result=await page.evaluate(async input=>{const lab=window.__lab;Object.assign(lab.state,{doors:new Set(),backed:new Set(),actors:true,parents:true,children:true,clinicians:true,routes:false,grid:false,contacts:false,bases:false});for(const[k,v]of Object.entries(input))lab.state[k]=['doors','backed'].includes(k)?new Set(v):v;lab.refreshControls();await lab.draw();return{kind:'Manager browser capture',origin:location.origin,doorModel:lab.data.pediatricPresentation.doorModel,png:document.getElementById('canvasB').toDataURL('image/png').split(',')[1],state:{...lab.state,doors:[...lab.state.doors],backed:[...lab.state.backed]},status:document.getElementById('status').textContent,contacts:lab.contactText(),check:lab.check('pediatric-exam',[...lab.state.doors],[...lab.state.backed])};},settings);assert.equal(result.check.unreachable.length+result.check.conflicts.length+result.check.doorZone.length,0,'Clear capture routes '+name);result.proofManifestSha256=proofManifestSha256;fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(result.png,'base64'));delete result.png;fs.writeFileSync(path.join(out,name+'.json'),JSON.stringify(result,null,2)+'\n');console.log('CAPTURE '+name);}
 await page.evaluate(async()=>{const lab=window.__lab;Object.assign(lab.state,{doors:new Set(),backed:new Set(),actors:true,parents:true,children:true,clinicians:true,routes:false,grid:false,contacts:false,bases:false});lab.refreshControls();await lab.draw();});await page.screenshot({path:path.join(out,'exam-desktop.png'),fullPage:true});await page.setViewportSize({width:320,height:900});await page.screenshot({path:path.join(out,'exam-320.png'),fullPage:true});
 if(events.errors.length)throw Error(JSON.stringify(events.errors));fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify({status:'PASS',url,origin:new URL(url).origin,doorLabels:doors,doorModel:manifest.doorModel,proofManifestSha256,stoolDerivationSha256:manifest.stoolDerivationManifestSha256,cases:cases.map(c=>c[0]),screenshots:['exam-desktop.png','exam-320.png'],...events,designApproval:manifest.designApproval,ownerApproval:manifest.ownerApproval},null,2)+'\n');console.log('CAPTURE PASS 12 one-tile door model and backless stool; 11 room states plus desktop/320px pages; page errors 0');
}finally{await browser.close();}})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify({status:'FAIL',url,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
