// MANAGER ONLY. Worker compiles this script; worker does not launch browsers.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const{chromium}=require('@playwright/test'),{listen}=require('./browser-errors.cjs');
const here=__dirname,out=path.join(here,'evidence'),url=process.env.PEDIATRIC_EXAM_PROOF_URL||'http://127.0.0.1:4191/tools/room-design/level-4/pediatric-exam/proof/index.html';
const doorLabels=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'],north=['N1','N2','N3'];
(async()=>{
 const manifestBytes=fs.readFileSync(path.join(here,'proof-manifest.json')),manifest=JSON.parse(manifestBytes),proofManifestSha256=crypto.createHash('sha256').update(manifestBytes).digest('hex').toUpperCase();
 assert.deepEqual([manifest.doorModel.count,manifest.doorModel.perWall,manifest.doorModel.spanTiles,manifest.doorModel.kind],[12,3,1,'game-one-tile']);
 assert.equal(manifest.designApproval,true);assert.equal(manifest.stoolDerivation.renderer.clinicianAboveEntireStool,true);
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1100}}),events=listen(page),checks=[];const response=await page.goto(url);assert.equal(response.status(),200);
  const ready=()=>page.waitForFunction(()=>document.body.dataset.ready==='1');await ready();
  const inspect=()=>page.evaluate(()=>{const lab=window.__lab,room=lab.rooms.get('pediatric-exam'),P={room,doors:lab.state.doors,backed:lab.state.backed,ox:0,oy:0};return{origin:location.origin,state:{...lab.state,doors:[...lab.state.doors],backed:[...lab.state.backed]},visible:room.records.filter(r=>lab.recordVisible(r,P)).map(r=>r.id),actors:lab.state.actors?lab.actorPlacements(P).map(a=>({id:a.id,characterId:a.characterId,category:a.category,direction:a.direction,group:a.group})):[],check:lab.check('pediatric-exam',[...lab.state.doors],[...lab.state.backed]),overflow:document.documentElement.scrollWidth>innerWidth};});
  const initial=await inspect();assert.equal(initial.origin,new URL(url).origin);assert.equal(initial.actors.length,3);assert.equal(await page.locator('#doorGrid button').count(),12);assert.equal(await page.locator('#backedChips button').count(),3);
  assert.deepEqual((await page.locator('#doorGrid button').allTextContents()).sort(),doorLabels.slice().sort());assert.deepEqual(await page.locator('#backedChips button').allTextContents(),north);assert.deepEqual(await page.evaluate(()=>window.__lab.data.pediatricPresentation.doorModel),manifest.doorModel);
  assert.equal(await page.evaluate(()=>window.__lab.assets['design:reuse:stool'].sha256),manifest.stoolDerivation.output.sha256);assert.equal(await page.evaluate(()=>window.__lab.assets['design:reuse:stool'].derivedForOwnerRevision),true);
  assert.deepEqual(initial.actors.map(a=>[a.characterId,a.category,a.direction]),[['level3-roster-v2.021','future-pediatric-presentation','east'],['gs026-employee-001','employee','west'],['patient.adult.007','patient','west']]);checks.push('real .021 pediatric child east, clinician west and same-room parent west');
  const technical=await page.evaluate(async()=>{
   const lab=window.__lab,room=lab.rooms.get('pediatric-exam'),segments=lab.roomSegments(room),north=['N1','N2','N3'],failures=[];let states=0,routes=0;
   for(let mask=0;mask<8;mask++)for(const doors of[[],...segments.map(s=>[s]),segments]){const backed=north.filter((_,i)=>mask&(1<<i)),c=lab.check('pediatric-exam',doors,backed);states++;routes+=c.routes;if(c.unreachable.length||c.conflicts.length||c.doorZone.length)failures.push({mask,doors,c});}
   let assets=0;for(const[id,spec]of Object.entries(lab.assets).filter(([,a])=>a.prepared)){
    const m=lab.metadata.assets[spec.preparedId],im=new Image();im.src=spec.src;await im.decode();if(im.naturalWidth!==m.canvas[0]||im.naturalHeight!==m.canvas[1])failures.push('Native dimensions '+id);
    const canvas=document.createElement('canvas');canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;const g=canvas.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const pixels=g.getImageData(0,0,canvas.width,canvas.height).data;let bottom=-1,top=canvas.height,edge=0,transparent=0;
    for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const a=pixels[(y*canvas.width+x)*4+3];if(a>=160)bottom=y;if(a)top=Math.min(top,y);else transparent++;if(!x||!y||x===canvas.width-1||y===canvas.height-1)edge=Math.max(edge,a);}
    if(edge||!transparent||m.canvasAnchor[1] !==(m.anchorKind==='floor'?bottom+1:top))failures.push('Alpha/contact '+id);assets++;
   }
   const P={room,doors:new Set(),backed:new Set(),ox:0,oy:0},a=await lab.collectDrawables(P,true),b=await lab.collectDrawables({...P,backed:new Set(north)},true),ordered=[...a.sorted].sort((a,b)=>a.py-b.py),index=(id,kind)=>ordered.findIndex(d=>d.id===id&&d.kind===kind);
   if(!(index('pedsTable','fixture')<index('table:patient','actor')&&index('stool','fixture')<index('stool:clinician','actor')&&index('parentChair','fixture')<index('parentChair','actor')&&index('parentChair','actor')<index('parentChair:front','fixture')))failures.push('Seated painter order');
   const stool=ordered.find(d=>d.id==='stool'&&d.kind==='fixture'),clinician=ordered.find(d=>d.id==='stool:clinician'&&d.kind==='actor');
   if(room.records.filter(r=>r.id==='stool'||r.overlayFor==='stool').length!==1||stool.src.join(',')!=='0,0,266,427'||stool.img.naturalWidth!==266||stool.img.naturalHeight!==427)failures.push('Stool must be a single native derived layer');
   const native=document.createElement('canvas');native.width=266;native.height=427;const ng=native.getContext('2d',{willReadFrequently:true});ng.drawImage(stool.img,0,0);const np=ng.getImageData(0,0,266,427).data;for(let y=0;y<104;y++)for(let x=0;x<266;x++)if(np[(y*266+x)*4+3])failures.push('Stool backrest remains');const hip=(135*266+133)*4;if(np[hip+1]-np[hip]<15)failures.push('Back post remains at cushion contact');
   const layers=document.createElement('canvas');layers.width=480;layers.height=480;const lg=layers.getContext('2d',{willReadFrequently:true});lg.drawImage(stool.img,...stool.src,stool.x,stool.y,stool.w,stool.h);const sp=lg.getImageData(0,0,480,480).data;lg.clearRect(0,0,480,480);const ci=new Image();ci.src=clinician.url;await ci.decode();lg.imageSmoothingEnabled=false;lg.drawImage(ci,clinician.x,clinician.y,clinician.w,clinician.h);const cp=lg.getImageData(0,0,480,480).data,readableStool={seat:0,column:0,base:0};let clinicianOverStoolPixels=0;
   for(let y=0;y<480;y++)for(let x=0;x<480;x++){const i=(y*480+x)*4+3;if(sp[i]>=250&&cp[i]>=250)clinicianOverStoolPixels++;if(sp[i]>=160&&cp[i]<160){const sy=(y+.5-stool.y)*427/stool.h;if(sy>=104)readableStool[sy<207?'seat':sy<319?'column':'base']++;}}
   if(clinicianOverStoolPixels<20||Object.values(readableStool).some(n=>n<6))failures.push('Clinician/stool seat, column or base framing');
   const counterA=[...a.wall,...a.sorted].find(d=>d.id==='scaleCounter'),counterB=[...b.wall,...b.sorted].find(d=>d.id==='scaleCounter');if(!counterA||!counterB||['x','y','w','h'].some(k=>counterA[k]!==counterB[k])||counterB.clipTop!==undefined)failures.push('Counter backing/full-height');
   const front=ordered.find(d=>d.id==='parentChair:front'),chair=ordered.find(d=>d.id==='parentChair'&&d.kind==='fixture'),actor=ordered.find(d=>d.id==='parentChair'&&d.kind==='actor');if(['x','y','w','h'].some(k=>front[k]!==chair[k]))failures.push('Armrest registration');
   const canvas=document.createElement('canvas');canvas.width=480;canvas.height=480;const g=canvas.getContext('2d',{willReadFrequently:true}),im=new Image();im.src=actor.url;await im.decode();g.imageSmoothingEnabled=false;g.drawImage(im,actor.x,actor.y,actor.w,actor.h);const ap=g.getImageData(0,0,480,480).data;g.clearRect(0,0,480,480);g.imageSmoothingEnabled=true;g.drawImage(front.img,...front.src,front.x,front.y,front.w,front.h);const fp=g.getImageData(0,0,480,480).data;let armrestOverlap=0;for(let i=3;i<ap.length;i+=4)if(ap[i]>=250&&fp[i]>=250)armrestOverlap++;if(armrestOverlap<20)failures.push('Missing actual parent/front wood overlap');
   return{states,routes,assets,armrestOverlap,backlessStool:true,stoolForegroundLayers:0,readableStool,clinicianOverStoolPixels,failures};
  });assert.deepEqual(technical.failures,[]);assert.equal(technical.states,112);assert.equal(technical.routes,768);assert.equal(technical.assets,5);checks.push('112 states, 768 routes, 5 decoded alpha/anchor assets, clinician above single backless stool with readable seat/column/base, parent layers and full-height counter');
  const hiddenByDoor={scaleCounter:['N3','EA'],toyBin:['WC','S1'],growthChart:['N2'],animalPrint:['N1']};
  for(const s of doorLabels){
   const button=()=>page.locator('#doorGrid button').filter({hasText:new RegExp('^'+s+'$')});await button().click();await ready();let current=await inspect();assert.deepEqual(current.state.doors,[s]);assert.equal(current.check.unreachable.length+current.check.conflicts.length+current.check.doorZone.length,0);
   assert.equal(await button().getAttribute('aria-pressed'),'true');for(const[id,owners]of Object.entries(hiddenByDoor))assert.equal(current.visible.includes(id),!owners.includes(s),'Own-section visibility '+id+'/'+s);
   await button().click();await ready();assert.deepEqual((await inspect()).visible,initial.visible);
  }checks.push('all 12 one-tile door controls, own-section art hiding and exact restoration');
  await page.click('#allDoors');await ready();assert.equal((await inspect()).state.doors.length,12);assert.equal(await page.locator('#doorGrid button[aria-pressed="true"]').count(),12);await page.click('#allDoors');await ready();assert.equal((await inspect()).state.doors.length,12);await page.click('#closeDoors');await ready();assert.equal((await inspect()).state.doors.length,0);assert.deepEqual((await inspect()).visible,initial.visible);
  await page.click('#allBacked');await ready();assert.equal((await inspect()).state.backed.length,3);await page.click('#clearBacked');await ready();assert.equal((await inspect()).state.backed.length,0);assert.deepEqual((await inspect()).visible,initial.visible);checks.push('all four bulk controls, idempotent open-all and exact restoration');
  for(const s of north){await page.locator('#backedChips button').filter({hasText:new RegExp('^'+s+'$')}).click();await ready();assert.ok((await inspect()).visible.includes('scaleCounter'));assert.equal((await inspect()).state.doors.length,0);}assert.ok(!(await inspect()).visible.includes('animalPrint'));assert.ok(!(await inspect()).visible.includes('growthChart'));await page.click('#clearBacked');await ready();assert.deepEqual((await inspect()).visible,initial.visible);checks.push('three independent backing controls, full-height counter and wall hides');
  for(const[id,count]of[['tgParents',2],['tgChildren',2],['tgClinician',2],['tgActors',0]]){await page.uncheck('#'+id);await ready();assert.equal((await inspect()).actors.length,count);await page.check('#'+id);await ready();assert.equal((await inspect()).actors.length,3);}checks.push('parent, child, clinician and all-occupancy toggles');
  await page.locator('h1').click();for(const[key,state]of[['g','grid'],['r','routes'],['a','actors'],['p','parents'],['k','children'],['v','clinicians'],['c','contacts'],['f','bases']]){const before=(await inspect()).state[state];await page.keyboard.press(key);await ready();assert.equal((await inspect()).state[state],!before);await page.keyboard.press(key);await ready();assert.equal((await inspect()).state[state],before);}
  await page.keyboard.press('d');await ready();assert.equal((await inspect()).state.doors.length,12);await page.keyboard.press('b');await ready();assert.equal((await inspect()).state.backed.length,3);await page.keyboard.press('Escape');await ready();assert.equal((await inspect()).state.doors.length,0);assert.equal((await inspect()).state.backed.length,0);
  await page.locator('#allDoors').focus();await page.keyboard.press('Space');await ready();assert.equal((await inspect()).state.doors.length,12);await page.locator('#closeDoors').focus();await page.keyboard.press('Enter');await ready();assert.equal((await inspect()).state.doors.length,0);checks.push('keyboard toggles, Escape and Space/Enter button activation');
  await page.setViewportSize({width:320,height:900});await ready();assert.equal((await inspect()).overflow,false);assert.ok(await page.locator('#canvasB').isVisible());const pixels=await page.evaluate(()=>{const c=document.getElementById('canvasB'),p=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let n=0;for(let i=3;i<p.length;i+=4)if(p[i])n++;return n;});assert.ok(pixels>10000);checks.push('320px layout without horizontal overflow; rendered pixels');
  assert.deepEqual(events.errors,[]);fs.writeFileSync(path.join(out,'browser-validation-report.json'),JSON.stringify({status:'PASS',url,origin:initial.origin,doorLabels,doorModel:manifest.doorModel,proofManifestSha256,stoolDerivationSha256:manifest.stoolDerivationManifestSha256,checks,technical,...events,viewport:[320,900],designApproval:manifest.designApproval,ownerApproval:manifest.ownerApproval},null,2)+'\n');console.log('BROWSER VALIDATION PASS '+checks.length+' groups; 12 one-tile door controls; backless stool below clinician; keyboard; 320px; page errors 0');
 }finally{await browser.close();}
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'browser-validation-report.json'),JSON.stringify({status:'FAIL',url,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
