// Node-only asset, integrity, geometry and actual renderer validation.
// No browser/process launch. Browser acceptance is a separate manager action.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const{pathToFileURL}=require('node:url');const here=__dirname,repo=path.resolve(here,'../../../../..'),lane=path.resolve(here,'..'),out=path.join(here,'evidence');
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex').toUpperCase(),read=f=>JSON.parse(fs.readFileSync(path.join(here,f),'utf8'));
let checks=0;const lines=[],counts={};const ok=(value,message)=>{assert.ok(value,message);checks++;};const equal=(a,b,message)=>{assert.deepEqual(a,b,message);checks++;};const log=s=>{lines.push(s);console.log(s);};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const G=await import(pathToFileURL(path.join(here,'geometry.mjs'))),D=await import(pathToFileURL(path.join(here,'design-rooms.js'))),U=await import(pathToFileURL(path.join(here,'../assets/image-utils.mjs'))),{createCanvas,loadImage}=await import('@napi-rs/canvas');
 const data=read('data.json'),manifest=read('proof-manifest.json'),contract=read('asset-contract.json'),generations=read('../assets/generation-manifest.json'),receipts=read('../assets/generation-receipts.json'),original=read('layout-baseline.json'),actorBaseline=read('actor-baseline.json'),p=read('presentation-contract.json'),stoolDerivation=read('../assets/derived/stool-backless-manifest.json'),room=D.DESIGN_ROOMS[0],nav=D.DESIGN_NAVIGATION[room.definitionId],metadata=D.PREPARED_METADATA;
 equal(room.footprint,[3,3],'Room footprint preserved');equal(room.floor,original.room.floor,'Floor unchanged');equal(room.solids,original.room.solids,'Source solids unchanged');equal(room.shell,original.room.shell,'Source shell palette/dimensions unchanged');
 const cleanNav=structuredClone(nav);delete cleanNav.privateProofRouteModel;equal(cleanNav,original.navigation,'Shared navigation unchanged');
 for(const old of original.room.records){const current=room.records.find(r=>r.id===old.id);ok(current,'Source fixture preserved '+old.id);for(const k of ['renderSizeTiles','worldLocalGround','destinationTopLeftTiles','footprint','depthPolicy','depthKey','canvasTransform'])equal(current[k],old[k],'Frozen placement '+old.id+'/'+k);}
 for(const old of original.room.supports){const s=room.supports.find(s=>s.id===old.id);equal(s.authoredSeat,old.seat,'Authored seat retained '+s.id);for(const k of ['ground','fixtureGround','facing','role','pose'])equal(s[k],old[k],'Support provenance '+s.id+'/'+k);}
 equal(generations.assets.length,5,'Five original pieces');equal(Object.keys(metadata.assets).sort(),['animal-print','growth-chart','peds-table','scale-counter','toy-bin'],'Five processed pieces');
 for(const r of generations.assets){
  const receipt=receipts.records.find(x=>x.generationId===r.generationId),file=path.join(lane,'assets',r.file),prompt=path.join(lane,'assets',r.prompt);equal(sha(file),r.sha256,'Original hash '+r.id);equal(sha(prompt),r.promptSha256,'Prompt hash '+r.id);equal(fs.readFileSync(prompt,'utf8'),receipt.sentPrompt,'Exact tool string '+r.id);
  ok(r.inspection.inspected&&!r.inspection.text&&!r.inspection.logos&&!r.inspection.mediaCharacters&&!r.inspection.cropping,'Inspection complete '+r.id);ok(r.transparent_background&&r.tool==='built-in image_gen','Builtin genuine-alpha request '+r.id);
  for(const ref of r.references)equal(sha(path.join(repo,ref.path)),ref.sha256,'Input reference '+ref.path);
  const m=metadata.assets[r.id],spec=contract.assets[r.id],nativeFile=path.join(lane,'assets/processed',m.file),im=await U.decode(nativeFile),b=U.bounds(im.pixels.data,...m.canvas,160),all=U.bounds(im.pixels.data,...m.canvas),stats=U.alphaStats(im.pixels.data,...m.canvas);
  equal(sha(nativeFile),m.outputSha256,'Native hash '+r.id);equal([im.canvas.width,im.canvas.height],spec.canvas,'Native frame '+r.id);ok(m.canvas[0]/m.widthTiles>=240&&m.canvas[1]/m.heightTiles>=240,'Minimum density '+r.id);ok(stats.transparent>0&&stats.opaque>0&&stats.min===0&&stats.max>=250&&stats.edgeAlphaMax===0,'True native alpha '+r.id);
  equal(m.outputOpaqueBounds,b,'Decoded opaque bounds '+r.id);equal(m.outputAllAlphaBounds,all,'Decoded visible bounds '+r.id);ok(Object.values(m.alphaClearancePixels).every(v=>v>=4),'Clear native margins '+r.id);
  equal(m.canvasAnchor,[m.canvas[0]/2,m.anchorKind==='floor'?b.bottom+1:all.top],'Actual alpha anchor '+r.id);ok(m.aspectPreserved&&!m.sourceUpscaled&&m.alphaCleanup.meaningfulPixelsRemoved===0&&m.alphaCleanup.maxRemovedAlpha<8,'Uniform technical prep '+r.id);
  const record=room.records.find(x=>x.assetId===spec.assetId),d=G.fixturePlacement(record,m),world=record.worldLocalGround??[record.destinationTopLeftTiles[0]+record.renderSizeTiles[0]/2,record.destinationTopLeftTiles[1]];ok(Math.abs(d.x+m.canvasAnchor[0]*d.w/m.canvas[0]-world[0]*120)<1e-8&&Math.abs(d.y+m.canvasAnchor[1]*d.h/m.canvas[1]-world[1]*120)<1e-8,'Registered source-world contact '+r.id);
 }
 log('PASS assets: 5 transparent native PNGs; uniform fit, minimum 240 px/tile, real alpha margins and floor/wall anchors');
 const protectedFiles=read('../assets/reference-baseline.json').files;for(const[rel,hash]of Object.entries(protectedFiles))equal(sha(path.join(repo,rel)),hash,'Protected source changed '+rel);counts.protectedFiles=Object.keys(protectedFiles).length;
 for(const[key,entry]of Object.entries(actorBaseline.actorHashes))equal(sha(path.join(repo,entry.path)),entry.sha256,'Actor pose hash '+key);counts.actorPoses=Object.keys(actorBaseline.actorHashes).length;
 for(const[field,file]of Object.entries({layoutBaselineSha256:'layout-baseline.json',actorBaselineSha256:'actor-baseline.json',presentationContractSha256:'presentation-contract.json',dataSha256:'data.json',rendererSha256:'lab.js',geometrySha256:'geometry.mjs',preparedMetadataSha256:'../assets/processed/metadata.json',stoolDerivationManifestSha256:'../assets/derived/stool-backless-manifest.json'}))equal(sha(path.join(here,file)),manifest[field],'Proof manifest hash '+field);
 for(const a of Object.values(manifest.reusedApproved))equal(sha(path.resolve(here,a.src)),a.sha256,'Reused approved reference');
 log('PASS integrity: 5 exact original/prompt pairs; '+counts.actorPoses+' actor poses; '+counts.protectedFiles+' protected reference files unchanged');
 const intake=read('revisions/door-model-16-reviewed/intake.json'),reviewedData=read('revisions/door-model-16-reviewed/data.json');
 for(const[file,hash]of Object.entries(intake.unchangedHashes))equal(sha(path.join(lane,file)),hash,'Reviewed art/source contract unchanged '+file);
 const restoreAuthorizedPainterChange=actor=>{if(actor.supportId!=='stool:clinician')return actor;const prior=intake.unchangedPresentation.actors.find(a=>a.supportId===actor.supportId);return{...actor,painterGround:prior.painterGround,basis:prior.basis};};
 for(const[field,value]of Object.entries(intake.unchangedPresentation))equal(field==='actors'?p.actors.map(restoreAuthorizedPainterChange):p[field],value,'Reviewed seat presentation unchanged except authorized clinician layering '+field);
 for(const field of ['characters','characterMetrics','previewBaseClearances'])equal(data[field],reviewedData[field],'Reviewed character/base data unchanged '+field);
 const withoutStoolAsset=assets=>Object.fromEntries(Object.entries(assets).filter(([id])=>id!=='design:reuse:stool'));
 equal(withoutStoolAsset(D.DESIGN_ASSETS),withoutStoolAsset(intake.reviewedDesign.assets),'Reviewed asset references unchanged except derived stool');
 equal(room.supports,intake.reviewedDesign.room.supports,'Reviewed seated supports unchanged');
 const withoutDoorOwners=r=>Object.fromEntries(Object.entries(r).filter(([key])=>!['doorOwners','backedOwners'].includes(key)));
 const restoreStoolSourceRect=r=>r.id==='stool'?{...r,sourceRect:intake.reviewedDesign.room.records.find(old=>old.id==='stool').sourceRect}:r;
 equal(room.records.map(r=>withoutDoorOwners(restoreStoolSourceRect(r))),intake.reviewedDesign.room.records.map(withoutDoorOwners),'Reviewed fixture/art/placement unchanged except door ownership and derived stool source rectangle');
 for(const[file,hash]of Object.entries(intake.archivedHashes))equal(sha(path.join(here,'revisions/door-model-16-reviewed',file)),hash,'Prior manager evidence preserved '+file);
 equal([intake.priorBrowserStatus,intake.priorPageErrors],['PASS',0],'Prior manager review recorded');
 const stoolIntake=read('revisions/stool-with-back-reviewed/intake.json');for(const[file,hash]of Object.entries(stoolIntake.archivedHashes))equal(sha(path.join(here,'revisions/stool-with-back-reviewed',file)),hash,'Prior twelve-door evidence preserved '+file);
 equal(p.doorModel,stoolIntake.reviewedPresentation.doorModel,'Twelve-door revision unchanged');
 counts.reviewedImmutableFiles=Object.keys(intake.unchangedHashes).length;
 log('PASS revision preservation: '+counts.reviewedImmutableFiles+' reviewed art/source contracts, seat contacts, fixture placements, twelve-door model and prior evidence unchanged; authorized stool/layer revision only');
 const stoolSource=await U.decode(path.join(repo,stoolDerivation.source.path)),stoolNative=await U.decode(path.join(lane,'assets/derived',stoolDerivation.output.file)),[sx,sy,sw,sh]=stoolDerivation.source.sourceRect,sourcePixels=stoolSource.context.getImageData(sx,sy,sw,sh).data,derivedPixels=stoolNative.pixels.data,repair=stoolDerivation.derivation.repair;
 equal(sha(path.join(repo,stoolDerivation.source.path)),stoolDerivation.source.sha256,'Approved stool sheet unchanged');equal(sha(path.join(lane,'assets/derived',stoolDerivation.output.file)),stoolDerivation.output.sha256,'Backless stool hash');equal([stoolNative.canvas.width,stoolNative.canvas.height],[266,427],'Stool registration canvas unchanged');equal(stoolDerivation.source.sourceRect,[8,2448,266,427],'Approved stool crop');equal(stoolDerivation.output.sourceRect,[0,0,266,427],'Derived stool crop');equal(manifest.stoolDerivation,stoolDerivation,'Stool derivation manifest');equal(stoolDerivation.derivation.clearRows,[0,104],'Backrest mask');equal(repair,{left:110,rightExclusive:150,top:104,bottomExclusive:207,leftSourceX:109,rightSourceX:150},'Back post/cushion repair bounds');
 let removedBackPixels=0,repairedPixels=0,retainedPixels=0,maxRepairChannelDelta=0,repairChangedChannels=0;
 for(let y=0;y<sh;y++)for(let x=0;x<sw;x++){
  const i=(y*sw+x)*4;
  if(y<104){if(derivedPixels[i+3])throw Error('Backrest/post remains above cushion');if(sourcePixels[i+3])removedBackPixels++;continue;}
  if(y>=repair.top&&y<repair.bottomExclusive&&x>=repair.left&&x<repair.rightExclusive){const t=(x-repair.leftSourceX)/(repair.rightSourceX-repair.leftSourceX);for(let c=0;c<4;c++){const expected=Math.round(sourcePixels[(y*sw+repair.leftSourceX)*4+c]*(1-t)+sourcePixels[(y*sw+repair.rightSourceX)*4+c]*t),delta=Math.abs(derivedPixels[i+c]-expected);if(delta>(c===3?0:1))throw Error('Cushion repair differs from source interpolation/native alpha rounding');if(delta)repairChangedChannels++;maxRepairChannelDelta=Math.max(maxRepairChannelDelta,delta);}repairedPixels++;continue;}
  for(let c=0;c<4;c++)if(derivedPixels[i+c]!==sourcePixels[i+c])throw Error('Approved stool pixel changed outside authorized mask/repair');retainedPixels++;
 }
 equal([removedBackPixels,repairedPixels,retainedPixels],[stoolDerivation.derivation.removedBackPixels,stoolDerivation.derivation.repairedPixels,stoolDerivation.derivation.retainedPixels],'Recorded stool pixel derivation');equal([maxRepairChannelDelta,repairChangedChannels],[stoolDerivation.derivation.nativeAlphaEncoding.maxRepairChannelDelta,stoolDerivation.derivation.nativeAlphaEncoding.repairChangedChannels],'Recorded native alpha encoding');equal(U.bounds(derivedPixels,sw,sh,160),stoolDerivation.output.opaqueBounds,'Backless decoded alpha bounds');
 const stoolAsset=D.DESIGN_ASSETS['design:reuse:stool'];equal([stoolAsset.src,stoolAsset.sourceRect,stoolAsset.sha256],['../assets/derived/stool-backless.png',[0,0,266,427],stoolDerivation.output.sha256],'Rendered backless stool asset');equal(stoolAsset.approvedSource,stoolDerivation.source,'Approved stool source provenance');equal(room.records.filter(r=>r.assetId==='design:reuse:stool').map(r=>r.id),['stool'],'Only one complete stool layer');equal([stoolDerivation.renderer.singleStoolLayer,stoolDerivation.renderer.clinicianAboveEntireStool,stoolDerivation.renderer.stoolForegroundLayers],[true,true,0],'Owner stool layering rule');
 counts.removedBackPixels=removedBackPixels;counts.repairedCushionPixels=repairedPixels;counts.retainedStoolPixels=retainedPixels;
 log('PASS backless stool: '+removedBackPixels+' back pixels removed; '+repairedPixels+' source-derived cushion pixels; '+retainedPixels+' approved seat/column/base pixels unchanged; source hash unchanged');
 const segments=G.roomSegments(room),north=['N1','N2','N3'],expected=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'];
 equal(segments,expected,'Game one-tile door labels');equal(new Set(segments).size,12,'Twelve unique sections');equal([p.doorModel.count,p.doorModel.perWall,p.doorModel.spanTiles,p.doorModel.kind],[12,3,1,'game-one-tile'],'Manager-directed door model');equal(manifest.doorModel,p.doorModel,'Door model manifest');
 for(const side of ['N','S','W','E']){const spans=segments.filter(s=>s[0]===side).map(s=>G.segmentSpan(room,s));equal(spans.map(s=>s.length),[1,1,1],'One-tile wall widths '+side);equal(spans.map(s=>[s.start,s.end]),[[0,1],[1,2],[2,3]],'Every wall covered '+side);}
 for(const segment of segments)equal(G.doorInsideWorld(room,segment),G.doorInside(room,segment).map(v=>v+.5),'Entry at game inside-tile center '+segment);
 for(const invalid of ['N4','S4','WD','ED']){assert.throws(()=>G.segmentSpan(room,invalid),/Invalid room door section/);checks++;}
 const owners={pedsTable:[],scaleCounter:['N3','EA'],growthChart:['N2'],animalPrint:['N1'],toyBin:['S1','WC']};
 for(const[id,expectedOwners]of Object.entries(owners)){const r=room.records.find(r=>r.id===id);equal(r.doorOwners,expectedOwners,'Own game door sections '+id);for(const segment of segments)equal(G.visible(r,new Set([segment]),new Set()),!expectedOwners.includes(segment),'Single-door hide/restore '+id+'/'+segment);equal(G.visible(r,new Set(),new Set()),true,'Closed-door restoration '+id);}
 equal(G.passableThroughDoors({room,doors:new Set(segments)},nav).map(p=>[p.door,p.fixture]),[['N1','pedsTable'],['S3','parentChair'],['WA','pedsTable'],['WB','pedsTable'],['EC','parentChair']],'Original game threshold exceptions');
 let states=0,routes=0,samples=0,transitions=0;const failures=[];
 for(let mask=0;mask<8;mask++)for(const doors of[[],...segments.map(s=>[s]),segments]){
  const backed=north.filter((_,i)=>mask&(1<<i)),P={room,doors:new Set(doors),backed:new Set(backed)},r=G.computeRoutes(P,nav,data.previewBaseClearances),c=G.check(room,nav,doors,backed,data.previewBaseClearances),blockers=G.fineBlockers(P,nav,data.previewBaseClearances);states++;routes+=r.length;
  if(c.unreachable.length||c.conflicts.length||c.doorZone.length)failures.push({mask,doors,c});
  samples+=G.sampleWalkingRoutes(r,(x,y)=>{if(!G.clearPoint(P,blockers,x,y))throw Error('Radius clearance '+doors+' at '+x+','+y);});
  for(const route of r){equal(route.walkingPath[0],G.doorInsideWorld(room,route.door),'Entry center');equal(route.walkingPath.at(-1),route.standingApproach,'Separate standing approach');if(route.seatingTransition){transitions++;equal(route.seatingTransition.kind,'static-seating-contact-not-walking','Seat distinct from walking');}}
  const counter=room.records.find(r=>r.id==='scaleCounter');if(!counter.doorOwners.some(s=>doors.includes(s)))ok(G.visible(counter,P.doors,P.backed),'Counter remains full-height when backed');
 }
 equal(failures,[],'Every entry/backing route clear');equal(states,112,'Matrix states');equal(routes,768,'Matrix routes');
 // Backing only changes wall art; every extra doorway monotonically removes
 // blockers through explicit hide/pass-through rules. Confirm that invariant
 // for each pair rather than pretending the 112-state matrix is exhaustive.
 let pairs=0;for(let i=0;i<segments.length;i++)for(let j=i+1;j<segments.length;j++){
  const P={room,doors:new Set([segments[i],segments[j]]),backed:new Set()},combined=G.fineBlockers(P,nav,data.previewBaseClearances).map(b=>b.id);
  for(const s of P.doors){const singleton=G.fineBlockers({...P,doors:new Set([s])},nav,data.previewBaseClearances).map(b=>b.id);ok(combined.every(id=>singleton.includes(id)),'Door combination may only remove blockers');}pairs++;
 }
 counts.states=states;counts.routes=routes;counts.walkingSamples=samples;counts.staticSeatTransitions=transitions;counts.doorPairs=pairs;
 equal(pairs,66,'Every one of 66 door pairs');
 log('PASS doors/routes: 12 one-tile sections; 112 door/backing states; '+routes+' routes; '+samples+' radius-clear walking samples; 66 monotonic door pairs');
 const P={room,doors:new Set(),backed:new Set(),ox:0,oy:0},actors=G.actorPlacements(P,data,{parents:true,children:true,clinicians:true});equal(actors.length,3,'Three same-room occupants');const child=actors.find(a=>a.group==='children'),clinician=actors.find(a=>a.group==='clinicians'),parent=actors.find(a=>a.group==='parents');
 equal([child.characterId,child.category,child.direction,clinician.direction,parent.direction],['level3-roster-v2.021','future-pediatric-presentation','east','west','west'],'Real pediatric still and opposed adults');equal(child.py,2.06,'Authored child painter ground');ok(parent&&room.supports.some(s=>s.id==='parentChair'),'Designated parent spot');
 for(const a of actors){const fit=p.actors.find(f=>f.supportId===a.id),source=data.characters.find(c=>c.id===a.characterId).poses.sit[a.direction],im=await U.decode(path.join(repo,'apps/player/public',source.url)),[x,y]=fit.seatContactSource;ok(im.pixels.data[((y-1)*source.width+x)*4+3]>=160,'Measured posterior opaque '+a.id);ok(im.pixels.data[(y*source.width+x)*4+3]<160,'Measured posterior edge '+a.id);ok(Math.abs(a.x+x*a.sourceScale-fit.seat[0]*120)<1e-8&&Math.abs(a.y+y*a.sourceScale-fit.seat[1]*120)<1e-8,'Rendered exact hip '+a.id);}
 const tableRec=room.records.find(r=>r.id==='pedsTable'),tm=metadata.assets['peds-table'],td=G.fixturePlacement(tableRec,tm),ti=await U.decode(path.join(lane,'assets/processed/peds-table.png')),tableX=Math.round((child.seat.x*120-td.x)*tm.canvas[0]/td.w),tableY=Math.round((child.seat.y*120-td.y)*tm.canvas[1]/td.h);ok(ti.pixels.data[(tableY*tm.canvas[0]+tableX)*4+3]>=160,'Child hip contacts real table pad');
 const {engine,warnings}=await(await import(pathToFileURL(path.join(here,'native-engine.mjs')))).loadNativeEngine(),draw=await engine.collectDrawables(P,true),ordered=[...draw.sorted].sort((a,b)=>a.py-b.py),index=(id,kind)=>ordered.findIndex(d=>d.id===id&&(!kind||d.kind===kind));
 ok(index('pedsTable','fixture')<index('table:patient','actor'),'Child draws over table');ok(index('stool','fixture')<index('stool:clinician','actor'),'Clinician entirely above the stool');equal(clinician.py,1.7501,'Owner requested clinician painter ground');ok(index('parentChair','fixture')<index('parentChair','actor')&&index('parentChair','actor')<index('parentChair:front','fixture'),'Chair-occupant-front armrest order');
 const front=ordered.find(d=>d.id==='parentChair:front'),chair=ordered.find(d=>d.id==='parentChair'&&d.kind==='fixture');for(const k of ['x','y','w','h'])equal(front[k],chair[k],'Front armrest exact registration '+k);
 const layer=createCanvas(480,480),ctx=layer.getContext('2d');const paint=async d=>{ctx.clearRect(0,0,480,480);await engine.drawImageRec(ctx,d);return ctx.getImageData(0,0,480,480).data;};const parentDraw=ordered.find(d=>d.id==='parentChair'&&d.kind==='actor'),parentPixels=await paint(parentDraw),frontPixels=await paint(front);let armrestOverlap=0;for(let i=3;i<frontPixels.length;i+=4)if(frontPixels[i]>=250&&parentPixels[i]>=250)armrestOverlap++;ok(armrestOverlap>=20,'Real parent pixels hidden behind front armrest');
 const stoolDraw=ordered.find(d=>d.id==='stool'&&d.kind==='fixture'),clinDraw=ordered.find(d=>d.id==='stool:clinician'),clinPixels=await paint(clinDraw),stoolPixels=await paint(stoolDraw),readableStool={seat:0,column:0,base:0};let clinicianOverStoolPixels=0;
 for(let y=0;y<480;y++)for(let x=0;x<480;x++){const i=(y*480+x)*4+3;if(stoolPixels[i]>=250&&clinPixels[i]>=250)clinicianOverStoolPixels++;if(stoolPixels[i]>=160&&clinPixels[i]<160){const sourceY=(y+.5-stoolDraw.y)*sh/stoolDraw.h;if(sourceY>=104)readableStool[sourceY<207?'seat':sourceY<319?'column':'base']++;}}
 ok(clinicianOverStoolPixels>20,'Real clinician covers stool pixels');for(const[part,pixels]of Object.entries(readableStool))ok(pixels>5,'Stool '+part+' remains readable under clinician');
 ctx.clearRect(0,0,480,480);for(const d of ordered.filter(d=>d===stoolDraw||d===clinDraw))await engine.drawImageRec(ctx,d);const stoolClinComposite=ctx.getImageData(0,0,480,480).data;let clinicianLayerSamples=0,maxClinicianCompositeChannelDelta=0;
 // The approved character alpha is mostly 252-254. Check source-over color
 // rather than pretending these pixels are fully opaque.
 for(let i=0;i<clinPixels.length;i+=4)if(clinPixels[i+3]>=250){const ca=clinPixels[i+3]/255,sa=stoolPixels[i+3]/255,alpha=ca+sa*(1-ca);for(let c=0;c<4;c++){const expected=c===3?Math.round(alpha*255):Math.round((clinPixels[i+c]*ca+stoolPixels[i+c]*sa*(1-ca))/alpha),delta=Math.abs(stoolClinComposite[i+c]-expected);maxClinicianCompositeChannelDelta=Math.max(maxClinicianCompositeChannelDelta,delta);if(delta>2)throw Error('Stool foreground covers the clinician');}clinicianLayerSamples++;}ok(clinicianLayerSamples>100,'Whole clinician paints above the stool');
 const sourceSheet=await U.decode(path.join(repo,'apps/player/public/art/rooms/gs015-v1/waiting/south.webp')),frontImage=await U.decode(path.resolve(here,D.DESIGN_ASSETS[front.rec.assetId].src));let copied=0;for(let y=0;y<369;y++)for(let x=0;x<315;x++){const i=(y*315+x)*4;if(!frontImage.pixels.data[i+3])continue;const j=((y+748)*sourceSheet.canvas.width+x+8)*4;for(let k=0;k<4;k++)if(frontImage.pixels.data[i+k]!==sourceSheet.pixels.data[j+k])throw Error('Front armrest changed approved pixel');copied++;}ok(copied>10000,'Approved front armrest is source pixels');
 const backedDraw=await engine.collectDrawables({...P,backed:new Set(north)},true),ca=[...draw.wall,...draw.sorted].find(d=>d.id==='scaleCounter'),cb=[...backedDraw.wall,...backedDraw.sorted].find(d=>d.id==='scaleCounter');for(const k of ['x','y','w','h'])equal(ca[k],cb[k],'Counter keeps full height '+k);ok(cb.clipTop===undefined,'Counter never clipped on low wall');equal(warnings,[],'Actual renderer warnings');
 counts.armrestOverlap=armrestOverlap;counts.clinicianOverStoolPixels=clinicianOverStoolPixels;counts.readableStool=readableStool;counts.clinicianLayerSamples=clinicianLayerSamples;counts.maxClinicianCompositeChannelDelta=maxClinicianCompositeChannelDelta;counts.approvedFrontPixels=copied;
 fs.writeFileSync(path.join(out,'seat-layer-report.json'),JSON.stringify({actors,armrestOverlap,clinicianOverStoolPixels,readableStool,clinicianLayerSamples,maxClinicianCompositeChannelDelta,stoolForegroundLayers:0,approvedFrontPixels:copied,order:ordered.map(d=>({id:d.id,kind:d.kind,py:d.py})),tablePadContact:[tableX,tableY],counterFullHeight:true},null,2)+'\n');
 log('PASS seats/layers: real .021 child east; clinician west entirely above backless stool; same-room parent west; '+armrestOverlap+' front-armrest pixels; readable stool seat/column/base '+readableStool.seat+'/'+readableStool.column+'/'+readableStool.base+' pixels');
 const textFiles=[];function collectText(dir){for(const name of fs.readdirSync(dir)){const file=path.join(dir,name);if(fs.statSync(file).isDirectory())collectText(file);else if(/\.(?:json|mjs|cjs|js|html|md|txt|log)$/.test(name))textFiles.push(file);}}collectText(lane);textFiles.push(path.join(repo,'docs/execplans/level4-pediatric-exam-mockup-20261008.md'));
 for(const f of textFiles){const bytes=fs.readFileSync(f);ok(!(bytes[0]===239&&bytes[1]===187&&bytes[2]===191),'No UTF-8 BOM '+f);const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);ok(!text.includes('\uFFFD'),'No replacement characters '+f);}
 equal(manifest.designApproval,true,'Owner approval with requested stool revision recorded');equal(manifest.ownerApproval.quote,stoolIntake.ownerQuote,'Exact owner authorization');equal([manifest.ownerApproval.ownerDesign,manifest.ownerApproval.revisionImplemented,manifest.ownerApproval.managerBrowserValidation],['approved_with_requested_revision',true,'pending'],'Owner decision distinguished from manager browser validation');equal(manifest.runtimeIntegration,false,'No runtime integration');ok(!fs.readFileSync(path.join(here,'lab.js'),'utf8').match(/\b(?:localStorage|sessionStorage|indexedDB)\b/),'No campaign storage');counts.textFiles=textFiles.length;
 log('PASS presentation/provenance: unchanged 3x3 geometry; manager-directed game door model; full-height backed counter; UTF-8 without BOM');
 log('PENDING manager: revised browser validation/captures, actual keyboard and 320px presentation; owner approved with requested stool revision');
 log('VALIDATION PASS '+checks+' Node checks; browser validation pending');
 fs.writeFileSync(path.join(out,'validation.log'),lines.join('\n')+'\n');fs.writeFileSync(path.join(out,'validation-report.json'),JSON.stringify({status:'PASS',checks,counts,browserValidation:'pending_manager',ownerApproval:manifest.ownerApproval,doorModel:p.doorModel,stoolDerivationSha256:manifest.stoolDerivationManifestSha256},null,2)+'\n');
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'validation-report.json'),JSON.stringify({status:'FAIL',checks,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
