// MANAGER ONLY. Browser evidence remains distinct from Node-native inspection.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('@playwright/test'),{listen}=require('./browser-errors.cjs');
const here=__dirname,out=path.join(here,'evidence'),url=process.env.WOUND_OSTOMY_PROOF_URL||'http://127.0.0.1:4191/tools/room-design/level-4/wound-ostomy/proof/index.html';
const doors=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'],backed=['N1','N2','N3'];
const cases=[['wound-painted',{}],['wound-empty',{actors:false}],['wound-patient',{clinicians:false}],['wound-clinician',{patients:false}],['wound-all-doors',{doors}],['wound-backed',{backed}],['wound-all-backed',{doors,backed}],['wound-contacts',{doors:['N2','S2','WA','EC'],routes:true,grid:true,contacts:true,bases:true}],['wound-shelf-door',{doors:['N3'],routes:true}],['wound-corner-door',{doors:['WC'],routes:true}],['wound-recliner-door',{doors:['WB'],routes:true}]];
(async()=>{
 const bytes=fs.readFileSync(path.join(here,'proof-manifest.json')),manifest=JSON.parse(bytes),proofManifestSha256=crypto.createHash('sha256').update(bytes).digest('hex').toUpperCase();assert.deepEqual([manifest.doorModel.count,manifest.doorModel.perWall,manifest.doorModel.spanTiles,manifest.doorModel.kind],[12,3,1,'game-one-tile']);
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1100}}),events=listen(page);const response=await page.goto(url);assert.equal(response.status(),200);await page.waitForFunction(()=>document.body.dataset.ready==='1');assert.deepEqual(await page.evaluate(()=>window.__lab.roomSegments(window.__lab.rooms.get('wound-ostomy'))),doors);
  for(const [name,settings]of cases){
   const result=await page.evaluate(async input=>{const lab=window.__lab;Object.assign(lab.state,{doors:new Set(),backed:new Set(),actors:true,patients:true,clinicians:true,routes:false,grid:false,contacts:false,bases:false});for(const [key,value]of Object.entries(input))lab.state[key]=['doors','backed'].includes(key)?new Set(value):value;lab.refreshControls();await lab.draw();return{kind:'Manager browser capture',origin:location.origin,doorModel:lab.data.woundPresentation.doorModel,png:document.getElementById('canvasB').toDataURL('image/png').split(',')[1],state:{...lab.state,doors:[...lab.state.doors],backed:[...lab.state.backed]},status:document.getElementById('status').textContent,contacts:lab.contactText(),check:lab.check('wound-ostomy',[...lab.state.doors],[...lab.state.backed])};},settings);
   assert.equal(result.check.unreachable.length+result.check.conflicts.length+result.check.doorZone.length,0,'Clear routes '+name);result.proofManifestSha256=proofManifestSha256;fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(result.png,'base64'));delete result.png;fs.writeFileSync(path.join(out,name+'.json'),JSON.stringify(result,null,2)+'\n');console.log('CAPTURE '+name);
  }
  await page.evaluate(async()=>{const lab=window.__lab;Object.assign(lab.state,{doors:new Set(),backed:new Set(),actors:true,patients:true,clinicians:true,routes:false,grid:false,contacts:false,bases:false});lab.refreshControls();await lab.draw();});await page.screenshot({path:path.join(out,'wound-desktop.png'),fullPage:true});await page.setViewportSize({width:320,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px overflow');await page.screenshot({path:path.join(out,'wound-320.png'),fullPage:true});
  assert.deepEqual(events.errors,[]);fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify({status:'PASS',url,origin:new URL(url).origin,proofManifestSha256,doorModel:manifest.doorModel,cases:cases.map(c=>c[0]),screenshots:['wound-desktop.png','wound-320.png'],...events,designApproval:manifest.designApproval,ownerRevision:manifest.ownerRevision.revision},null,2)+'\n');console.log('CAPTURE PASS 11 room states plus desktop/320px pages; 12 one-tile doors; page errors 0');
 }finally{await browser.close();}
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify({status:'FAIL',url,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
