// MANAGER ONLY: worker compiles this script, but does not launch a browser.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('@playwright/test'),{listen}=require('./browser-errors.cjs');
const here=__dirname,out=path.join(here,'evidence'),url=process.env.WOUND_OSTOMY_PROOF_URL||'http://127.0.0.1:4191/tools/room-design/level-4/wound-ostomy/proof/index.html';
const doors=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'],north=['N1','N2','N3'];
(async()=>{
 const bytes=fs.readFileSync(path.join(here,'proof-manifest.json')),manifest=JSON.parse(bytes),proofManifestSha256=crypto.createHash('sha256').update(bytes).digest('hex').toUpperCase();
 assert.deepEqual([manifest.doorModel.count,manifest.doorModel.perWall,manifest.doorModel.spanTiles,manifest.doorModel.kind],[12,3,1,'game-one-tile']);
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1100}}),events=listen(page),checks=[];const response=await page.goto(url);assert.equal(response.status(),200);
  const ready=()=>page.waitForFunction(()=>document.body.dataset.ready==='1');await ready();
  const inspect=()=>page.evaluate(()=>{const lab=window.__lab,room=lab.rooms.get('wound-ostomy'),P={room,doors:lab.state.doors,backed:lab.state.backed,ox:0,oy:0};return{origin:location.origin,state:{...lab.state,doors:[...lab.state.doors],backed:[...lab.state.backed]},visible:room.records.filter(r=>lab.recordVisible(r,P)).map(r=>r.id),actors:lab.state.actors?lab.actorPlacements(P).map(a=>({id:a.id,characterId:a.characterId,category:a.category,direction:a.direction})):[],check:lab.check('wound-ostomy',[...lab.state.doors],[...lab.state.backed]),overflow:document.documentElement.scrollWidth>innerWidth};});
  const initial=await inspect();assert.equal(initial.origin,new URL(url).origin);assert.equal(await page.locator('#doorGrid button').count(),12);assert.equal(await page.locator('#backedChips button').count(),3);
  assert.deepEqual((await page.locator('#doorGrid button').allTextContents()).sort(),doors.slice().sort());assert.deepEqual(await page.locator('#backedChips button').allTextContents(),north);
  assert.deepEqual(initial.actors.map(a=>[a.characterId,a.category,a.direction]),[['patient.adult.007','patient','east'],['gs026-employee-001','employee','west']]);checks.push('real existing opposing patient and clinician, twelve game door sections');
  const technical=await page.evaluate(async expectedActors=>{
   const lab=window.__lab,room=lab.rooms.get('wound-ostomy'),segments=lab.roomSegments(room),north=['N1','N2','N3'],failures=[];let states=0,routes=0;
   for(let mask=0;mask<8;mask++)for(const doors of[[],...segments.map(s=>[s]),segments]){const backed=north.filter((_,i)=>mask&(1<<i)),c=lab.check('wound-ostomy',doors,backed);states++;routes+=c.routes;if(c.unreachable.length||c.conflicts.length||c.doorZone.length)failures.push({mask,doors,c});}
   let assets=0;for(const [id,spec]of Object.entries(lab.assets).filter(([,a])=>a.prepared)){
    const m=lab.metadata.assets[spec.preparedId],im=new Image();im.src=spec.src;await im.decode();if(im.naturalWidth!==m.canvas[0]||im.naturalHeight!==m.canvas[1])failures.push('Native dimensions '+id);
    const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const p=g.getImageData(0,0,c.width,c.height).data;let bottom=-1,top=c.height,edge=0,transparent=0;
    for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const a=p[(y*c.width+x)*4+3];if(a>=160)bottom=y;if(a)top=Math.min(top,y);else transparent++;if(!x||!y||x===c.width-1||y===c.height-1)edge=Math.max(edge,a);}
    if(edge||!transparent||m.canvasAnchor[1] !==(m.anchorKind==='floor'?bottom+1:top))failures.push('Alpha or anchor '+id);assets++;
    if(spec.preparedId==='wound-recliner'){
     if(m.source!=='originals/wound-recliner-02.png')failures.push('Stale chair generation');
     let extensionAlpha=0;for(let y=180;y<400;y++)for(let x=380;x<624;x++)if(p[(y*c.width+x)*4+3])extensionAlpha++;
     if(extensionAlpha)failures.push('Chair leg rest remains visible');
    }
   }
   if(JSON.stringify(lab.data.woundPresentation.actors)!==JSON.stringify(expectedActors))failures.push('Stale patient or clinician registration');
   const P={room,doors:new Set(),backed:new Set(),ox:0,oy:0},normal=await lab.collectDrawables(P,true),low=await lab.collectDrawables({...P,backed:new Set(north)},true),ordered=[...normal.sorted].sort((a,b)=>a.py-b.py),index=(id,kind)=>ordered.findIndex(d=>d.id===id&&d.kind===kind);
   if(!(index('recliner','fixture')<index('recliner:patient','actor')&&index('stool','fixture')<index('stool:clinician','actor')))failures.push('Seated painter order');
   for(const id of ['ostomyShelf','sink']){const a=[...normal.wall,...normal.sorted].find(d=>d.id===id),b=[...low.wall,...low.sorted].find(d=>d.id===id);if(!a||!b||['x','y','w','h'].some(k=>a[k]!==b[k])||b.clipTop!==undefined)failures.push('Full-height low wall '+id);}
   if(!lab.assets['design:reuse:stool'].backless||room.records.some(r=>r.overlayFor==='stool'))failures.push('Stool backless/foreground contract');
   const c=document.createElement('canvas');c.width=480;c.height=480;const g=c.getContext('2d',{willReadFrequently:true}),stool=ordered.find(d=>d.id==='stool'&&d.kind==='fixture'),clinician=ordered.find(d=>d.id==='stool:clinician');
   await lab.drawImageRec(g,stool);const sp=g.getImageData(0,0,480,480).data;g.clearRect(0,0,480,480);await lab.drawImageRec(g,clinician);const ap=g.getImageData(0,0,480,480).data;g.clearRect(0,0,480,480);await lab.drawImageRec(g,stool);await lab.drawImageRec(g,clinician);const composite=g.getImageData(0,0,480,480).data;let clinicianAboveStoolOverlap=0,badBlend=0;
   for(let i=0;i<ap.length;i+=4)if(ap[i+3]>=250&&sp[i+3]>=250){const a=ap[i+3]/255,b=sp[i+3]/255,oa=a+b*(1-a);for(let channel=0;channel<3;channel++)if(Math.abs(composite[i+channel]-Math.round((ap[i+channel]*a+sp[i+channel]*b*(1-a))/oa))>2)badBlend++;clinicianAboveStoolOverlap++;}
   if(clinicianAboveStoolOverlap<20||badBlend)failures.push('Clinician not entirely above actual stool');
   return{states,routes,assets,clinicianAboveStoolOverlap,failures,doorModel:lab.data.woundPresentation.doorModel};
  },manifest.seatRegistrations);assert.deepEqual(technical.failures,[]);assert.deepEqual([technical.states,technical.routes,technical.assets],[112,576,5]);assert.deepEqual(technical.doorModel,manifest.doorModel);checks.push('112 states, 576 routes, five native alpha/anchor assets, leg-rest-free chair, current seat fit, actual clinician-over-stool blend and full-height shelf');
  const owners={sink:['N1','WA'],ostomyShelf:['N2','N3'],dressingCart:['S3','EC'],curtain:['WC'],bio:['S1','WC'],hygieneSign:['N3']};
  for(const s of doors){const button=()=>page.locator('#doorGrid button').filter({hasText:new RegExp('^'+s+'$')});await button().click();await ready();const current=await inspect();assert.deepEqual(current.state.doors,[s]);assert.equal(current.check.unreachable.length+current.check.conflicts.length+current.check.doorZone.length,0);assert.equal(await button().getAttribute('aria-pressed'),'true');for(const [id,list]of Object.entries(owners))assert.equal(current.visible.includes(id),!list.includes(s),'Door visibility '+id+'/'+s);await button().click();await ready();assert.deepEqual((await inspect()).visible,initial.visible);}checks.push('all twelve individual doors, correct art hiding and restoration');
  await page.click('#allDoors');await ready();assert.equal((await inspect()).state.doors.length,12);assert.equal(await page.locator('#doorGrid button[aria-pressed="true"]').count(),12);await page.click('#allDoors');await ready();assert.equal((await inspect()).state.doors.length,12);await page.click('#closeDoors');await ready();assert.equal((await inspect()).state.doors.length,0);
  await page.click('#allBacked');await ready();assert.equal((await inspect()).state.backed.length,3);await page.click('#allBacked');await ready();assert.equal((await inspect()).state.backed.length,3);await page.click('#clearBacked');await ready();assert.equal((await inspect()).state.backed.length,0);assert.deepEqual((await inspect()).visible,initial.visible);checks.push('four bulk controls, idempotence and exact restoration');
  for(const s of north){await page.locator('#backedChips button').filter({hasText:new RegExp('^'+s+'$')}).click();await ready();assert.ok((await inspect()).visible.includes('ostomyShelf'));assert.ok((await inspect()).visible.includes('sink'));assert.equal((await inspect()).state.doors.length,0);}assert.ok(!(await inspect()).visible.includes('hygieneSign'));await page.click('#clearBacked');await ready();assert.deepEqual((await inspect()).visible,initial.visible);checks.push('independent backing retains floor shelf/sink and hides wall poster');
  for(const [id,count]of [['tgPatient',1],['tgClinician',1],['tgActors',0]]){await page.uncheck('#'+id);await ready();assert.equal((await inspect()).actors.length,count);await page.check('#'+id);await ready();assert.equal((await inspect()).actors.length,2);}checks.push('patient, clinician and total occupancy toggles');
  for(const [id,key]of [['tgRoutes','routes'],['tgGrid','grid'],['tgContacts','contacts'],['tgBases','bases']]){await page.check('#'+id);await ready();assert.equal((await inspect()).state[key],true);await page.uncheck('#'+id);await ready();assert.equal((await inspect()).state[key],false);}checks.push('routes, grid, contacts and base toggles');
  await page.locator('h1').click();for(const [key,state]of [['g','grid'],['r','routes'],['a','actors'],['p','patients'],['v','clinicians'],['c','contacts'],['f','bases']]){const before=(await inspect()).state[state];await page.keyboard.press(key);await ready();assert.equal((await inspect()).state[state],!before);await page.keyboard.press(key);await ready();assert.equal((await inspect()).state[state],before);}
  await page.keyboard.press('d');await ready();assert.equal((await inspect()).state.doors.length,12);await page.keyboard.press('b');await ready();assert.equal((await inspect()).state.backed.length,3);await page.keyboard.press('Escape');await ready();assert.equal((await inspect()).state.doors.length,0);assert.equal((await inspect()).state.backed.length,0);
  await page.locator('#allDoors').focus();await page.keyboard.press('Space');await ready();assert.equal((await inspect()).state.doors.length,12);await page.locator('#closeDoors').focus();await page.keyboard.press('Enter');await ready();assert.equal((await inspect()).state.doors.length,0);checks.push('keyboard toggles, reset and native Space/Enter button activation');
  await page.setViewportSize({width:320,height:900});await ready();assert.equal((await inspect()).overflow,false);assert.ok(await page.locator('#canvasB').isVisible());const bounds=await page.locator('#canvasB').boundingBox();assert.ok(bounds.width<=320);checks.push('320px visible canvas, no horizontal overflow');
  assert.deepEqual(events.errors,[]);fs.writeFileSync(path.join(out,'browser-validation-report.json'),JSON.stringify({status:'PASS',url,origin:initial.origin,proofManifestSha256,doorModel:manifest.doorModel,checks,technical,...events,viewport:[320,900],designApproval:manifest.designApproval,ownerRevision:manifest.ownerRevision.revision},null,2)+'\n');console.log('BROWSER VALIDATION PASS '+checks.length+' groups; 12 one-tile doors; keyboard; 320px; page errors 0');
 }finally{await browser.close();}
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'browser-validation-report.json'),JSON.stringify({status:'FAIL',url,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
