import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, rmdirSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import test from 'node:test';
import {
  ALLOWED_CLASSES, CLIENT_ID, ENDPOINT, GRAPH_PATH, RUN_DIR, assertFreshSubmission,
  buildRunManifest, executeSynthetic, prepareLocal, resumeSynthetic, sha256,
  guardPath, validateHistoryEnvelope, validateOffline, validatePinnedArtifacts, validatePng, verifyPinnedBytes,
} from './north-south-runner-lib.mjs';
import { parseObservedTap } from './north-south-runner-validate.mjs';

const repo=resolve(import.meta.dirname,'../..');
const tempRoot=join(repo,'tools','character-pose-process','.north-south-runner-tests');
if(!existsSync(tempRoot))mkdirSync(tempRoot);
let serial=0;
function tempDir(){const p=join(tempRoot,`case-${process.pid}-${Date.now()}-${serial++}`);mkdirSync(p);writeFileSync(join(p,'run-manifest.json'),readFileSync(join(RUN_DIR,'run-manifest.json')));writeFileSync(join(p,'ledger.json'),readFileSync(join(RUN_DIR,'ledger.json')));return p;}
function cleanup(p){assert.ok(resolve(p).startsWith(`${resolve(tempRoot)}\\`));rmSync(p,{recursive:true,force:false});}
function response(body,{status=200,type='application/json',url=''}={}){const bytes=Buffer.isBuffer(body)?body:Buffer.from(typeof body==='string'?body:JSON.stringify(body));return {ok:status>=200&&status<300,status,url,headers:{get:n=>n.toLowerCase()==='content-type'?type:null},text:async()=>bytes.toString(),arrayBuffer:async()=>bytes};}
function png(width=448,height=1024){const b=Buffer.alloc(33);Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]).copy(b);b.writeUInt32BE(13,8);b.write('IHDR',12,'ascii');b.writeUInt32BE(width,16);b.writeUInt32BE(height,20);return b;}
function fakeFetch({promptId='job-001',postThrows=false,historyMutator=null,viewBytes=png()}={}){
  const pinned=validatePinnedArtifacts();let posts=0;
  const outputs={};for(const [id,o] of Object.entries(pinned.outputs)){const i=o.prefix.lastIndexOf('/');outputs[id]={images:[{filename:`${o.prefix.slice(i+1)}_00001_.png`,subfolder:o.prefix.slice(0,i).replaceAll('/','\\'),type:'output'}]};}
  const outputNodes=[...Object.keys(pinned.outputs),...Object.entries(pinned.prepared.graph).filter(([,n])=>n.class_type==='ImageCompositor').map(([id])=>id)];
  const history={status:{status_str:'success',completed:true,messages:[['execution_start',{timestamp:1000}],['execution_success',{timestamp:1123}]]},prompt:[1,promptId,pinned.prepared.graph,{client_id:CLIENT_ID},outputNodes],outputs};
  historyMutator?.(history,pinned);
  const fn=async(url,options={})=>{const path=new URL(url).pathname; if(path.startsWith('/object_info/')){const c=decodeURIComponent(path.split('/').at(-1));return response({[c]:pinned.schema.schemas[c]},{url:String(url)});}if(path==='/queue')return response({queue_running:[],queue_pending:[]},{url:String(url)});if(path==='/prompt'){posts++;if(postThrows)throw new Error('simulated uncertain transport');const parsed=JSON.parse(Buffer.from(options.body).toString());assert.deepEqual(Object.keys(parsed).sort(),['client_id','prompt']);return response({prompt_id:promptId,number:1,node_errors:{}},{url:String(url)});}if(path===`/history/${promptId}`)return response({[promptId]:history},{url:String(url)});if(path==='/view')return response(viewBytes,{type:'image/png',url:String(url)});throw new Error(`unexpected ${url}`);};
  fn.posts=()=>posts;return fn;
}

test('offline validation is deterministic and performs no fetch',()=>{const before=sha256(readFileSync(join(RUN_DIR,'run-manifest.json')));assert.equal(validateOffline().ok,true);assert.equal(sha256(readFileSync(join(RUN_DIR,'run-manifest.json'))),before);const out=execFileSync(process.execPath,[join(import.meta.dirname,'north-south-runner.mjs'),'--validate-only'],{encoding:'utf8'});assert.equal(JSON.parse(out).outputCount,36);});
test('pins and exact inventories validate',()=>{const p=validatePinnedArtifacts();assert.equal(Object.keys(p.prepared.graph).length,674);assert.equal(Object.keys(p.outputs).length,36);assert.equal(p.sourceDefinitionHashes.length,16);assert.equal(p.sourceUseCount,143);assert.equal(buildRunManifest().inventory.allowedClasses.length,8);});
test('CLI rejects unknown, duplicate, and positional arguments',()=>{for(const args of [[],['--wat'],['--validate-only','--validate-only'],['--validate-only','extra']])assert.throws(()=>execFileSync(process.execPath,[join(import.meta.dirname,'north-south-runner.mjs'),...args],{stdio:'pipe'}));});
test('strict PNG validation checks magic, bound, and 448x1024 IHDR',()=>{assert.equal(validatePng(png()),true);assert.throws(()=>validatePng(Buffer.from('no')));assert.throws(()=>validatePng(png(447,1024)));assert.throws(()=>validatePng(png(448,1023)));});
test('successful fake execution posts once, downloads exactly 36, and records measured/null metrics',async()=>{const dir=tempDir(),fetch=fakeFetch();try{const audit=await executeSynthetic(fetch,{runDir:dir,timing:{deadlineMs:1000,now:(()=>{let n=0;return()=>n+=5;})(),sleep:async()=>{}}});assert.equal(fetch.posts(),1);assert.equal(Object.keys(audit.download.outputs).length,36);assert.equal(audit.execution.durationMs,123);assert.equal(audit.metrics.queueDurationMs,null);assert.equal(audit.metrics.operatorDurationMs,null);assert.equal(audit.syntheticEvidence.sourceUseCount,143);assert.equal(existsSync(join(dir,'receipt.json')),true);assert.equal(existsSync(join(dir,'outputs','mechanics-controls','composite.png')),true);assert.throws(()=>assertFreshSubmission(dir),/never resubmit/);}finally{cleanup(dir);}});
test('uncertain POST preserves attempt and refuses second POST/resume',async()=>{const dir=tempDir(),fetch=fakeFetch({postThrows:true});try{await assert.rejects(executeSynthetic(fetch,{runDir:dir}),/uncertain/);assert.equal(fetch.posts(),1);assert.equal(existsSync(join(dir,'attempt.json')),true);await assert.rejects(executeSynthetic(fetch,{runDir:dir}),/never resubmit/);await assert.rejects(resumeSynthetic(fetch,{runDir:dir}),/missing guarded path|resume/i);assert.equal(fetch.posts(),1);}finally{cleanup(dir);}});
test('resume binds own receipt and never posts again',async()=>{const dir=tempDir(),fetch=fakeFetch();try{await executeSynthetic(fetch,{runDir:dir,timing:{deadlineMs:1000,now:(()=>{let n=0;return()=>n+=2;})(),sleep:async()=>{}}});const fetch2=fakeFetch();const audit=await resumeSynthetic(fetch2,{runDir:dir});assert.equal(fetch2.posts(),0);assert.equal(audit.promptId,'job-001');}finally{cleanup(dir);}});
test('history rejects wrong client, graph, membership, output path, and undeclared output',()=>{const p=validatePinnedArtifacts(),baseId='x';const outputs={};for(const[id,o]of Object.entries(p.outputs)){const i=o.prefix.lastIndexOf('/');outputs[id]={images:[{filename:`${o.prefix.slice(i+1)}_00001_.png`,subfolder:o.prefix.slice(0,i),type:'output'}]};}const all=[...Object.keys(p.outputs),...Object.entries(p.prepared.graph).filter(([,n])=>n.class_type==='ImageCompositor').map(([id])=>id)];const base=()=>({[baseId]:{status:{status_str:'success',completed:true,messages:[['execution_start',{timestamp:1}],['execution_success',{timestamp:2}]]},prompt:[1,baseId,p.prepared.graph,{client_id:CLIENT_ID},all],outputs:structuredClone(outputs)}});let x=base();x[baseId].prompt[3].client_id='other';assert.throws(()=>validateHistoryEnvelope(x,baseId,p.prepared,p.outputs));x=base();x[baseId].prompt[2]={};assert.throws(()=>validateHistoryEnvelope(x,baseId,p.prepared,p.outputs));x=base();x[baseId].prompt[4].pop();assert.throws(()=>validateHistoryEnvelope(x,baseId,p.prepared,p.outputs));x=base();x[baseId].outputs[Object.keys(p.outputs)[0]].images[0].subfolder='elsewhere';assert.throws(()=>validateHistoryEnvelope(x,baseId,p.prepared,p.outputs));x=base();x[baseId].outputs.bad={images:[]};assert.throws(()=>validateHistoryEnvelope(x,baseId,p.prepared,p.outputs));});
test('wrong-size or wrong-content-type output fails without audit',async()=>{for(const [bytes,type] of [[png(1,1),'image/png'],[png(),'text/plain']]){const dir=tempDir(),fetch=fakeFetch({viewBytes:bytes});if(type!=='image/png'){const original=fetch;const wrapped=async(u,o)=>{const r=await original(u,o);if(new URL(u).pathname==='/view')r.headers.get=()=>type;return r;};wrapped.posts=fetch.posts;try{await assert.rejects(executeSynthetic(wrapped,{runDir:dir}),/content-type/);}finally{cleanup(dir);}}else{try{await assert.rejects(executeSynthetic(fetch,{runDir:dir}),/IHDR/);}finally{cleanup(dir);}}}});
test('changed local graph pin is detected without modifying frozen bytes',()=>{const original=readFileSync(GRAPH_PATH);assert.equal(sha256(original),'a1c65208d2f6264786d6ad0fa53ad963ad19a91309efe0936b1eaa0d5e602e4a');assert.notEqual(sha256(Buffer.concat([original,Buffer.from(' ')])),sha256(original));});
test('resume after ledger finalization reuses immutable completion and tampered output fails',async()=>{const dir=tempDir(),fetch=fakeFetch();try{await executeSynthetic(fetch,{runDir:dir,timing:{deadlineMs:1000,now:(()=>{let n=0;return()=>n+=3;})(),sleep:async()=>{}}});rmSync(join(dir,'audit.json'));const resumed=await resumeSynthetic(fakeFetch(),{runDir:dir,timing:{deadlineMs:1000,now:(()=>{let n=0;return()=>n+=3;})(),sleep:async()=>{}}});assert.equal(resumed.promptId,'job-001');const target=join(dir,'outputs','mechanics-controls','composite.png');const bytes=readFileSync(target);bytes[24]^=1;writeFileSync(target,bytes);await assert.rejects(resumeSynthetic(fakeFetch(),{runDir:dir}),/PNG|hash mismatch/);}finally{cleanup(dir);}});
test('altered pinned bytes and empty/failing TAP totals reject',()=>{const bytes=readFileSync(GRAPH_PATH);assert.equal(verifyPinnedBytes(bytes,'a1c65208d2f6264786d6ad0fa53ad963ad19a91309efe0936b1eaa0d5e602e4a'),true);assert.throws(()=>verifyPinnedBytes(Buffer.concat([bytes,Buffer.from('x')]),'a1c65208d2f6264786d6ad0fa53ad963ad19a91309efe0936b1eaa0d5e602e4a'));assert.throws(()=>parseObservedTap('# tests 0\n# pass 0\n# fail 0\n',0));assert.throws(()=>parseObservedTap('# tests 1\n# pass 1\n# fail 0\n',1));assert.deepEqual(parseObservedTap('# tests 2\n# pass 2\n# fail 0\n',0),{tests:2,passed:2,failed:0});});
test('repository path guard rejects a junction before redirected reads',()=>{const dir=tempDir(),link=join(dir,'linked-run');try{symlinkSync(RUN_DIR,link,'junction');assert.throws(()=>guardPath(join(link,'ledger.json')),/linked|redirected/);unlinkSync(link);}finally{cleanup(dir);}});

process.on('exit',()=>{if(existsSync(tempRoot)&&readdirSync(tempRoot).length===0)rmdirSync(tempRoot);});
