import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import { guardLocalPath, guardedReadJson, parseObservedTap, parseValidationArgs, readPinnedSchema, validateBindingPackage, writeValidationReportExclusive } from './target-binding-validation-v2.mjs';

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..'); let temp;
test.before(() => { temp = mkdtempSync(join(repo, 'tools', 'character-pose-process', '.binding-validation-v2-test-')); assert.ok(resolve(temp).startsWith(resolve(repo, 'tools', 'character-pose-process'))); });
test.after(() => { assert.ok(resolve(temp).startsWith(resolve(repo, 'tools', 'character-pose-process'))); rmSync(temp, { recursive: true }); assert.equal(existsSync(temp), false); });

test('validation consumes observed focused-test process totals', () => { const report = validateBindingPackage({ testRunner: () => ({ status: 0, stdout: 'tests 11\npass 11\nfail 0\n', stderr: '' }) }); assert.equal(report.state, 'read-only-validated'); assert.deepEqual({ tests: report.observedTests.tests, passed: report.observedTests.passed, failed: report.observedTests.failed, status: report.observedTests.status }, { tests: 11, passed: 11, failed: 0, status: 0 }); assert.equal(report.constraints.reportWritten, false); });
test('test process failure and empty totals propagate without fabricated success', () => { assert.throws(() => validateBindingPackage({ testRunner: () => ({ status: 1, stdout: 'tests 2\npass 1\nfail 1\n', stderr: '' }) }), /failed/); assert.throws(() => parseObservedTap({ status: 0, stdout: 'ok', stderr: '' }), /lacks one observed/); assert.throws(() => parseObservedTap({ status: 0, stdout: 'tests 7\npass 6\nfail 0\n', stderr: '' }), /totals conflict/); assert.throws(() => parseObservedTap({ status: 0, stdout: 'tests 0\npass 0\nfail 0\n', stderr: '' }), /empty/); });
test('linked evidence and schema-like reads fail before redirected content is read', t => { const target = join(temp, 'real'); const link = join(temp, 'linked-schema'); mkdirSync(target); try { symlinkSync(target, link, 'junction'); } catch (error) { if (['EPERM', 'EACCES'].includes(error.code)) return t.skip('junction unavailable'); throw error; } assert.throws(() => guardLocalPath(join(link, 'node-schemas.json'), temp, { mustExist: false }), /linked path/); assert.throws(() => guardedReadJson(join(link, 'evidence.json'), temp), /linked path/); });
test('pinned schema reader rejects changed bytes before JSON use', () => { const path = join(temp, 'changed-schema.json'); writeFileSync(path, '{}\n'); assert.throws(() => readPinnedSchema(path, temp), /schema byte hash mismatch/); });
test('exclusive report output preserves first bytes and rejects overwrite', () => { const root = join(temp, 'exclusive-root'); const evidence = join(root, 'Photos for Codex 2', 'Codex Patients or Staff or Other Characters 2', 'mixed-batch-2026-09-10', 'pose-process-proof-v1', 'binding-v1'); mkdirSync(evidence, { recursive: true }); const path = join(evidence, 'report.json'); const report = { constraints: { reportWritten: false }, ok: true }; writeValidationReportExclusive(report, path, root); const before = readFileSync(path); assert.throws(() => writeValidationReportExclusive(report, path, root), /EEXIST|exist/i); assert.deepEqual(readFileSync(path), before); });
test('linked report destination and output traversal are refused', t => { const root = join(temp, 'linked-output-root'); const proof = join(root, 'Photos for Codex 2', 'Codex Patients or Staff or Other Characters 2', 'mixed-batch-2026-09-10', 'pose-process-proof-v1'); const real = join(proof, 'real-binding'); const link = join(proof, 'binding-v1'); mkdirSync(real, { recursive: true }); try { symlinkSync(real, link, 'junction'); } catch (error) { if (['EPERM', 'EACCES'].includes(error.code)) return t.skip('junction unavailable'); throw error; } assert.throws(() => writeValidationReportExclusive({ constraints: {} }, join(link, 'report.json'), root), /linked path/); const escapeRoot = join(temp, 'escape-root'); mkdirSync(join(escapeRoot, 'Photos for Codex 2', 'Codex Patients or Staff or Other Characters 2', 'mixed-batch-2026-09-10', 'pose-process-proof-v1', 'binding-v1'), { recursive: true }); assert.throws(() => writeValidationReportExclusive({ constraints: {} }, join(escapeRoot, 'escape.json'), escapeRoot), /directly inside/); });
test('CLI argument parser rejects malformed or ambiguous modes', () => { assert.deepEqual(parseValidationArgs([]), { reportName: null }); assert.deepEqual(parseValidationArgs(['--write-report', 'review.json']), { reportName: 'review.json' }); for (const argv of [['--unknown'], ['--write-report'], ['--write-report', '../x.json'], ['--write-report', 'a.json', 'extra'], ['x']]) assert.throws(() => parseValidationArgs(argv), /usage/); });
