import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import { canonicalJson, numericDefinitionHash, validateGraph } from './index.mjs';
import { SCHEMA_SHA256, emitBindingGraph, hashBytes, loadBindingV2Artifact, resolveBinding } from './target-binding.mjs';
import { parseV2ValidationArgs } from './target-binding-v2-validate.mjs';

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..'); const root = join(repo, 'Photos for Codex 2', 'Codex Patients or Staff or Other Characters 2', 'mixed-batch-2026-09-10', 'pose-process-proof-v1', 'binding-v2');
const schemaBytes = readFileSync(join(root, '..', 'parent-evidence', 'node-schemas.json')); assert.equal(hashBytes(schemaBytes), SCHEMA_SHA256); const schema = JSON.parse(schemaBytes);
const load = path => JSON.parse(readFileSync(path)); const fixtures = Object.fromEntries(['baseline', 'ratio', 'registration'].map(id => [id, loadBindingV2Artifact(repo, id)]));
const generated = (fixture, view, phase, name) => join(root, 'generated', fixture, view, `phase-${String(phase).padStart(2, '0')}`, `${name}.json`);

test('compiler produced three authenticated 32-target synthetic artifacts with truthful numeric lineage', () => { for (const [id, loaded] of Object.entries(fixtures)) { assert.equal(loaded.artifact.targets.length, 32); assert.equal(loaded.artifact.dependencies.codeFingerprint, 'e2061adf31ca3e02a345cf8fa8c827591ad1881be23f8b3550df771c93824aa3'); const definition = readFileSync(join(repo, loaded.record.definitionPath)); assert.equal(hashBytes(definition), loaded.record.definitionSha256); for (const view of ['east', 'west', 'south', 'north']) { const lineage = loaded.artifact.sourceLineageVerification.lineage[view]; assert.equal(lineage.kind, 'independent'); assert.equal(lineage.sourcePath, loaded.record.definitionPath); assert.equal(lineage.sourceSha256, loaded.record.definitionSha256); assert.equal(lineage.acceptanceState, 'synthetic_numeric_fixture_unmeasured'); } assert.equal(loaded.artifact.identity.namePolicy, 'synthetic_test_only'); } });

test('48 saved graphs and resolutions reproduce with one unchanged eight-piece kit per fixture', () => { let graphs = 0; for (const [id, loaded] of Object.entries(fixtures)) { const kit = load(join(root, 'kits', `${id}.json`)); assert.equal(kit.pieces.length, 8); assert.deepEqual(new Set(kit.pieces.map(piece => `${piece.anatomy.side}:${piece.anatomy.part}`)), new Set(['left:upper-arm','right:upper-arm','left:forearm','right:forearm','left:thigh','right:thigh','left:shin','right:shin'])); for (const piece of kit.pieces) assert.equal(piece.sourceHash, numericDefinitionHash(piece.source)); for (const view of ['east', 'west']) for (let phase = 1; phase <= 8; phase++) { const request = load(generated(id, view, phase, 'request')), savedResolved = load(generated(id, view, phase, 'resolved')), savedGraph = load(generated(id, view, phase, 'graph')); assert.equal(canonicalJson(request.pieces), canonicalJson(kit.pieces)); const resolved = resolveBinding(loaded.artifact, request); assert.equal(canonicalJson(resolved), canonicalJson(savedResolved)); const graph = emitBindingGraph(resolved, schema); assert.equal(canonicalJson(graph), canonicalJson(savedGraph)); assert.equal(validateGraph(graph.graph, schema), true); assert.equal(graph.outputs[0].filenamePrefix.includes(`${id}-${view}-phase${String(phase).padStart(2,'0')}`), true); graphs++; } } assert.equal(graphs, 48); });

test('resolved anatomy, depth order, phase identity, lineage and quantization match every target', () => { for (const [id, loaded] of Object.entries(fixtures)) for (const view of ['east', 'west']) for (let phase = 1; phase <= 8; phase++) { const request = load(generated(id, view, phase, 'request')), resolved = resolveBinding(loaded.artifact, request), target = loaded.artifact.targets.find(value => value.outputKey === request.selection.outputKey); assert.equal(resolved.selection.phaseId, String(phase).padStart(2, '0')); assert.equal(resolved.selection.normalizedCycle, (phase - 1) / 8); assert.deepEqual(resolved.lineage, target.lineage); assert.deepEqual(resolved.visibility.renderingOrder, target.geometry.renderingOrder); for (const piece of resolved.pieces) { const expectedGroup = target.geometry.farSide === piece.anatomy.side ? `${piece.anatomy.side}-far-limbs` : `${piece.anatomy.side}-near-limbs`; assert.equal(piece.layerGroup, expectedGroup); assert.equal(piece.layerOrder, target.geometry.renderingOrder.indexOf(expectedGroup) * 100 + piece.layerWithinGroup); assert.equal(piece.transform.scale, 1); assert.deepEqual(piece.transform.quantizedPlacement, { x: Math.floor(piece.transform.placement.x + 0.5), y: Math.floor(piece.transform.placement.y + 0.5) }); assert.ok(piece.lengthEvidence.endpointResidual <= piece.lengthEvidence.endpointBound); assert.ok(piece.lengthEvidence.roundedScalarResidual <= 0.00005); } } });

test('ratio and registration fixtures change the intended native geometry independently', () => { const b = fixtures.baseline.artifact.targets.find(target => target.view === 'east' && target.phaseId === '01'), r = fixtures.ratio.artifact.targets.find(target => target.view === 'east' && target.phaseId === '01'), g = fixtures.registration.artifact.targets.find(target => target.view === 'east' && target.phaseId === '01'); assert.notDeepEqual(r.anatomy.segmentLengths, b.anatomy.segmentLengths); assert.equal(r.geometry.registration.scale, b.geometry.registration.scale); assert.deepEqual(g.anatomy.segmentLengths, b.anatomy.segmentLengths); assert.notEqual(g.geometry.registration.scale, b.geometry.registration.scale); assert.notEqual(g.geometry.registration.sourceAxisX, b.geometry.registration.sourceAxisX); assert.notEqual(g.geometry.registration.sourceFloorY, b.geometry.registration.sourceFloorY); assert.notDeepEqual(g.geometry.nativeMaster.joints.left.shoulder, b.geometry.nativeMaster.joints.left.shoulder); });

test('authenticated invalid requests reach part, ref, scalar, side, layer, canvas and output checks', () => { const loaded = fixtures.baseline, original = load(generated('baseline', 'east', 1, 'request')); const cases = [
  [value => value.pieces[0].anatomy.part = 'head', /part unsupported/], [value => value.pieces[0].distalRef = 'geometry.nativeMaster.joints.left.wrist', /anatomy\/endpoints/], [value => value.pieces[0].segmentLength.frameScalarRef = 'anatomy.segmentLengths.forearm', /anatomy\/endpoints/], [value => value.pieces[0].anatomy.side = 'right', /anatomy\/endpoints/], [value => value.pieces[0].layerGroup = 'right-near-limbs', /anatomical side\/layer/], [value => value.canvas.width = 576, /448x1024/], [value => value.output.prefixStem = 'binding-v2-baseline-east-phase02', /selected phase/],
  [value => value.pieces[0].proximalRef = 'geometry.nativeMaster.joints.left.hand', /endpoint refs invalid/], [value => value.pieces[0].proximalRef = 'geometry.nativeMaster.torso.shoulderBack', /endpoint refs invalid/], [value => value.pieces[0].segmentLength.frameScalarRef = 'anatomy.segmentLengths.hand', /frameScalarRef invalid/],
  ]; for (const [change, pattern] of cases) { const value = structuredClone(original); change(value); assert.throws(() => resolveBinding(loaded.artifact, value), pattern); } });

test('v2 validator is read-only by default and rejects malformed or extra arguments', () => { assert.deepEqual(parseV2ValidationArgs([]), { seal: false }); assert.deepEqual(parseV2ValidationArgs(['--seal']), { seal: true }); for (const args of [['--write'], ['--seal', 'extra'], ['extra']]) assert.throws(() => parseV2ValidationArgs(args), /usage/); });

test('north/south requests retain diagnostics but graph emission remains refused', () => { const loaded = fixtures.baseline, target = loaded.artifact.targets.find(value => value.view === 'north' && value.phaseId === '01'), request = { ...load(generated('baseline', 'east', 1, 'request')), selection: { outputKey: target.outputKey, view: target.view, assetView: target.assetView, phaseId: target.phaseId, phaseIndex: target.phaseIndex, normalizedCycle: target.normalizedCycle, reviewFrameMilliseconds: target.reviewFrameMilliseconds, lineageKind: target.lineage.kind }, projectionStrategy: 'unsupported-north-south', pieces: [] }; request.output.prefixStem = 'binding-v2-baseline-north-phase01'; const resolved = resolveBinding(loaded.artifact, request); assert.deepEqual(resolved.coordinateSpaces, { frame: 'frame128x192', latent: 'latent3D-frame-authoring-units', nativeMaster: 'source448x1024-via-projection', compositor: 'source448x1024/top-left/x-right/y-down/continuous-pixels' }); assert.deepEqual(resolved.visibility, target.geometry.visibility); assert.throws(() => emitBindingGraph(resolved, schema), /only resolved synthetic lateral/); });
