import { describe, expect, it } from "vitest";
import { ANSWER_CHOICE_TIMING_REGISTRY, EARLY_LEVELS_20260913_CASES } from "@gamify-surgery/clinical-content";
import { createInitialGameState, gameReducer, patientRosterEntryById } from "@gamify-surgery/game-domain";
import { createPrototypePlayerView } from "./viewModels";

function admitted(caseId:string,index:number){let state=createInitialGameState();state.facilityLevel=2;state.encounters={};state.nextRoutineArrivalTick=Number.MAX_SAFE_INTEGER;state.rooms.push({id:"room.early-presentation.examination",roomDefinitionId:"room.examination",x:29,y:23,orientation:0,doorSide:null,upgradeLevel:1,cleanliness:100},{id:"room.early-presentation.minor",roomDefinitionId:"room.minor_procedure",x:33,y:23,orientation:0,doorSide:null,upgradeLevel:1,cleanliness:100},...([24,25,26,27,28] as const).map((y)=>({id:`room.early-presentation.hall.${y}`,roomDefinitionId:"room.hallway",x:32,y,orientation:0 as const,doorSide:null,upgradeLevel:1 as const,cleanliness:100})));state.doors.push({id:"door.early-presentation.examination",roomId:"room.early-presentation.examination",side:"east",offset:1,exterior:false},{id:"door.early-presentation.minor",roomId:"room.early-presentation.minor",side:"west",offset:1,exterior:false},{id:"door.early-presentation.front",roomId:"room.instance.founder_desk",side:"west",offset:0,exterior:false});const encounterId=`encounter.early.presentation.${index}`;state=gameReducer(state,{type:"ADMIT_PATIENT",operationId:`early.presentation.${index}.admit`,encounterId,caseId,patientDisplayName:`Early Patient ${index}`,arrivalClass:"routine"});const encounter=state.encounters[encounterId]!;encounter.lifecycle="active_action_required";encounter.patientMovement=null;encounter.patientLocation={...state.environment.founderLocation};return{state,encounter,encounterId};}

describe("September 13 early-level chart presentation",()=>{
 it("resolves one named age-and-sex presentation and complete timing display for every new node",()=>{for(const [caseIndex,clinicalCase] of EARLY_LEVELS_20260913_CASES.entries()){const{state,encounter,encounterId}=admitted(clinicalCase.id,caseIndex);const demographics=encounter.frozenCase.prototypeDemographics!;const sexWord=demographics.sexLabel==="Female"?"woman":"man";expect(encounter.frozenCase.presentation).toContain(`${demographics.ageYears}-year-old ${sexWord}`);expect(patientRosterEntryById(encounter.patientAppearance.patientIdentityId)?.compatibleSexLabel).toBe(demographics.sexLabel);for(const [nodeIndex,node] of encounter.frozenCase.decisionNodes.entries()){encounter.currentNodeIndex=nodeIndex;encounter.steps.forEach((step,index)=>{step.status=index<nodeIndex?"completed":index===nodeIndex?"action_required":"locked";});const chart=createPrototypePlayerView(state,encounterId,false,null).chart!;expect(chart.presentation).toContain(`Early Patient ${caseIndex}`);expect(chart.presentation).not.toContain("{patientName}");expect(chart.presentation).toMatch(/\d+-year-old (woman|man|adult)/);const choices=chart.decisionSteps?.find((step)=>step.current)?.answerChoices??chart.answerChoices;expect(choices).toHaveLength(4);expect(choices.map((choice)=>choice.id).sort()).toEqual(node.answerChoices.map((choice)=>choice.id).sort());const timing=ANSWER_CHOICE_TIMING_REGISTRY.find((entry)=>entry.questionVariantId===node.questionVariantId)!;expect(timing).toBeDefined();if(timing.classification.kind==="test_choices"){for(const choice of choices){expect(choice.etaLabel,`${clinicalCase.id}/${node.id}/${choice.id}`).toBeTruthy();expect(choice.detailLabel,`${clinicalCase.id}/${node.id}/${choice.id}`).toBe(choice.etaLabel==="No test wait"?undefined:"Estimated test wait (game time)");}}else{expect(choices.every((choice)=>!choice.etaLabel&&!choice.detailLabel)).toBe(true);}}}});
});
