import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { MASTER, buildSeatedGeometry, buildStandingGeometry, buildWalkGeometry } from './canonical-geometry.mjs';
import { renderGuide, renderMaster } from './render-master.mjs';

const repositoryRoot=resolve(import.meta.dirname,'../../..'),outputRoot=resolve(repositoryRoot,'artifacts/character-movement/canonical-master/preview'),framesRoot=resolve(outputRoot,'frames');mkdirSync(framesRoot,{recursive:true});
const sha256=value=>createHash('sha256').update(value).digest('hex'),writeAsset=(name,bytes)=>{const relative=`frames/${name}`;writeFileSync(resolve(outputRoot,relative),bytes);return{relative,sha256:sha256(bytes)};};
const directions=['east','west','south','north'],phaseIds=MASTER.phases,walk=buildWalkGeometry(),registration={frameAxisX:MASTER.frame.axisX,frameFloorY:MASTER.frame.floorY};
const character={id:'canonical-short-stylized-master-v1',runtimeId:'canonical.master.short-stylized.v1',directions:{},static:{}};
for(const direction of directions){character.directions[direction]={};for(const phaseId of phaseIds){const geometry=walk[direction][phaseId],clean=renderMaster(geometry).toBuffer('image/png'),guide=renderGuide(geometry).toBuffer('image/png'),cleanAsset=writeAsset(`canonical-${direction}-${phaseId}.png`,clean),guideAsset=writeAsset(`canonical-${direction}-${phaseId}-guide.png`,guide);character.directions[direction][phaseId]={clean:cleanAsset.relative,guide:guideAsset.relative,sha256:{clean:cleanAsset.sha256,guide:guideAsset.sha256},geometry:{registration,joints:geometry.joints,hipCenter:geometry.hipCenter,layerPolicy:geometry.layerPolicy}};}}
for(const [key,geometry,chair] of [['standSouth',buildStandingGeometry('south'),false],['sitSouth',buildSeatedGeometry(),true]]){const slug=key==='standSouth'?'stand-south':'sit-south',clean=renderMaster(geometry,{chair}).toBuffer('image/png'),guide=renderGuide(geometry).toBuffer('image/png'),cleanAsset=writeAsset(`canonical-${slug}.png`,clean),guideAsset=writeAsset(`canonical-${slug}-guide.png`,guide);character.static[key]={clean:cleanAsset.relative,guide:guideAsset.relative,sha256:{clean:cleanAsset.sha256,guide:guideAsset.sha256},registration:{axisX:MASTER.frame.axisX,floorY:MASTER.frame.floorY},geometry:{joints:geometry.joints,hipCenter:geometry.hipCenter,layerPolicy:geometry.layerPolicy}};}
const geometryBytes=readFileSync(resolve(import.meta.dirname,'canonical-geometry.mjs')),rendererBytes=readFileSync(resolve(import.meta.dirname,'render-master.mjs')),masterData=Buffer.from(JSON.stringify(MASTER)),walkData=Buffer.from(JSON.stringify(walk));
const manifest={schemaVersion:1,status:'plain-canonical-master-owner-review',directions,phaseIds,characters:[character],canonical:{masterId:MASTER.id,frame:MASTER.frame,lengths:MASTER.lengths,anatomy:MASTER.anatomy,shapes:MASTER.shapes,materialRegions:MASTER.surfaceRegions,attachmentAnchors:MASTER.attachmentAnchors,surfaceContract:{poseIndependentRegionCoordinates:true,identityIndependentGeometry:true,rigidSegmentPrimitives:true,topologyVersion:MASTER.id},hashes:{masterDataSha256:sha256(masterData),walkGeometrySha256:sha256(walkData),geometryDefinitionSha256:sha256(geometryBytes),rendererDefinitionSha256:sha256(rendererBytes)}},semanticInvariants:{phaseCountPerDirection:8,anatomicalBoneLengthsFixedAcrossViews:true,contralateralArmLegSwing:true,elbowsUseConsistentPosteriorBendBranch:true,forwardArmFlexExceedsRearArmFlex:true,standingSleevesExtendBeyondFrontalTorso:true,rigidStraightThighAndShinPrimitives:true,feetUseHeelToeLandmarks:true,thumbLatentOffset:'medial and anatomically anterior before shared projection',thumbVisibilityByView:{east:'visible subtle anterior',west:'visible subtle anterior',south:'visible small medial',north:'guide-only; occluded in clean back-of-hand art'},headUsesCompleteParametricCrown:true,neckIsContinuousParametricRegion:true,frontalArmsBehindTorso:true,lateralLayerPolicy:['farArm','farLeg','nearLeg','torso','head','nearArm'],seatedThighHorizontalAndShinVertical:true},validation:{renderedWalkFrames:32,renderedGuides:32,staticPoses:2,ownerVisualAcceptance:'pending'}};
const bytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');writeFileSync(resolve(outputRoot,'manifest.json'),bytes);console.log(JSON.stringify({manifest:resolve(outputRoot,'manifest.json'),sha256:sha256(bytes),walkFrames:32,guides:32,statics:2},null,2));
