import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { MASTER, geometryInternals } from './canonical-geometry.mjs';

const repositoryRoot=resolve(import.meta.dirname,'../../..'),outputRoot=resolve(repositoryRoot,'artifacts/character-movement/canonical-master/preview');
const manifestBytes=readFileSync(resolve(outputRoot,'manifest.json')),manifest=JSON.parse(manifestBytes),sha256=value=>createHash('sha256').update(value).digest('hex'),near=(a,b,t=.02)=>Math.abs(a-b)<=t;
const asset=relative=>{if(!relative||relative.includes('..'))throw new Error(`unsafe asset ${relative}`);return readFileSync(resolve(outputRoot,relative));};
const pixelsFor=image=>{const canvas=createCanvas(image.width,image.height),context=canvas.getContext('2d');context.drawImage(image,0,0);return context.getImageData(0,0,image.width,image.height).data;};
const alphaAt=(pixels,width,x,y)=>pixels[(Math.round(y)*width+Math.round(x))*4+3];
const skinAt=(pixels,width,x,y)=>{const offset=(Math.round(y)*width+Math.round(x))*4,red=pixels[offset],green=pixels[offset+1],blue=pixels[offset+2];return pixels[offset+3]>0&&red>green+20&&green>blue+10;};
function componentCount(image,pixels){const seen=new Uint8Array(image.width*image.height);let count=0;for(let start=0;start<seen.length;start++){if(seen[start]||!pixels[start*4+3])continue;count++;const stack=[start];seen[start]=1;while(stack.length){const pixel=stack.pop(),x=pixel%image.width,y=Math.floor(pixel/image.width);for(const next of [x?pixel-1:-1,x+1<image.width?pixel+1:-1,y?pixel-image.width:-1,y+1<image.height?pixel+image.width:-1])if(next>=0&&!seen[next]&&pixels[next*4+3]){seen[next]=1;stack.push(next);}}}return count;}
function bones(geometry,label){for(const side of ['left','right']){const latent=geometry.joints[side].latent;for(const [a,b,length] of [['hip','knee',MASTER.lengths.thigh],['knee','ankle',MASTER.lengths.shin],['shoulder','elbow',MASTER.lengths.upperArm],['elbow','wrist',MASTER.lengths.forearm],['wrist','hand',MASTER.lengths.hand]])if(!near(geometryInternals.distance3(latent[a],latent[b]),length))throw new Error(`${label}/${side}/${a}-${b}`);}}
function elbows(geometry,label){for(const side of ['left','right']){const j=geometry.joints[side].latent,t=(j.elbow.height-j.shoulder.height)/(j.wrist.height-j.shoulder.height),lineForward=j.shoulder.forward+(j.wrist.forward-j.shoulder.forward)*t,bend=j.elbow.forward-lineForward,armForward=j.wrist.forward-j.shoulder.forward,span=geometryInternals.distance3(j.shoulder,j.wrist);if(bend>=-4||armForward>0&&span>=73||armForward<0&&span<=73)throw new Error(`${label}/${side}/signed elbow flex`);}}
function semantics(geometry,label){for(const side of ['left','right']){const j=geometry.joints[side],view=geometry.view,hand=j.latent.hand,thumb=j.thumbLatent,sign=side==='right'?1:-1;if((thumb.lateral-hand.lateral)*sign>=0||thumb.forward<=hand.forward||j.thumbSurface!=='medial-anterior'||view==='east'&&j.thumbTip.x<=j.palm.x||view==='west'&&j.thumbTip.x>=j.palm.x||(view==='south'||view==='north')&&Math.abs(j.thumbTip.x-MASTER.frame.axisX)>=Math.abs(j.palm.x-MASTER.frame.axisX)||view==='north'&&j.thumbVisibility!=='guide-only-occluded'||view!=='north'&&j.thumbVisibility!=='visible')throw new Error(`${label}/${side}/thumb`);if(view==='east'&&j.toe.x<=j.heel.x||view==='west'&&j.toe.x>=j.heel.x||(view==='south'||view==='north')&&Math.abs(j.toe.x-MASTER.frame.axisX)<=Math.abs(j.heel.x-MASTER.frame.axisX))throw new Error(`${label}/${side}/foot`);if(j.footLift===0&&(!near(j.heel.y,MASTER.frame.floorY)||!near(j.toe.y,MASTER.frame.floorY)))throw new Error(`${label}/${side}/floor`);}}
let visibleThumbRasterChecks=0,hiddenNorthThumbRasterChecks=0,lateralFarThumbDepthAllowances=0;
async function raster(record,geometry,label){const cleanBytes=asset(record.clean),guideBytes=asset(record.guide);if(sha256(cleanBytes)!==record.sha256.clean||sha256(guideBytes)!==record.sha256.guide||record.sha256.clean===record.sha256.guide)throw new Error(`${label}/asset hash or independent guide`);const image=await loadImage(cleanBytes),pixels=pixelsFor(image);if(componentCount(image,pixels)!==1)throw new Error(`${label}/components`);for(const side of ['left','right']){const j=geometry.joints[side];let thumbSkin=false;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(skinAt(pixels,image.width,j.thumbTip.x+dx,j.thumbTip.y+dy))thumbSkin=true;if(geometry.view==='north'){if(skinAt(pixels,image.width,j.thumbTip.x,j.thumbTip.y))throw new Error(`${label}/${side}/north thumb should be hidden`);hiddenNorthThumbRasterChecks++;}else{const exposed=geometry.view==='south'||geometry.view==='east'&&side==='right'||geometry.view==='west'&&side==='left';if(exposed){if(!thumbSkin)throw new Error(`${label}/${side}/visible thumb`);visibleThumbRasterChecks++;}else lateralFarThumbDepthAllowances++;}if(geometry.view==='east'||geometry.view==='west'){const x=(j.heel.x+j.toe.x)/2,y=Math.min(j.heel.y,j.toe.y)-5;if(!alphaAt(pixels,image.width,x,y))throw new Error(`${label}/${side}/shoe upper`);}}const shoulderY=(geometry.joints.left.shoulder.y+geometry.joints.right.shoulder.y)/2,facing=geometry.view==='east'?1:geometry.view==='west'?-1:0,headX=geometry.hipCenter.x-facing*3;for(let y=Math.round(shoulderY-14);y<=Math.round(shoulderY-7);y++)if(!alphaAt(pixels,image.width,headX,y))throw new Error(`${label}/neck gap`);if(!alphaAt(pixels,image.width,headX,shoulderY-97))throw new Error(`${label}/crown`);}

if(manifest.directions.join(',')!=='east,west,south,north'||manifest.phaseIds.join(',')!=='01,02,03,04,05,06,07,08'||manifest.characters.length!==1)throw new Error('manifest contract');
if(!manifest.canonical.surfaceContract.poseIndependentRegionCoordinates||!manifest.canonical.surfaceContract.identityIndependentGeometry||Object.keys(manifest.canonical.materialRegions).length!==8||MASTER.shapes.torso.front.chestHalfWidth>MASTER.anatomy.shoulderHalfWidth+MASTER.shapes.limbs.upperArmWidth/2-4||sha256(Buffer.from(JSON.stringify(MASTER)))!==manifest.canonical.hashes.masterDataSha256||sha256(readFileSync(resolve(import.meta.dirname,'canonical-geometry.mjs')))!==manifest.canonical.hashes.geometryDefinitionSha256||sha256(readFileSync(resolve(import.meta.dirname,'render-master.mjs')))!==manifest.canonical.hashes.rendererDefinitionSha256)throw new Error('canonical geometry/material contract');
const character=manifest.characters[0];let walkFrames=0,guides=0,bonePoseSets=0,contralateral=0,visibleThumbSides=0,hiddenNorthThumbSides=0,footSides=0,neckFrames=0,crownFrames=0,shoeUpperSides=0;
for(const direction of manifest.directions)for(const phaseId of manifest.phaseIds){const record=character.directions[direction][phaseId],geometry={view:direction,phaseId,joints:record.geometry.joints,hipCenter:record.geometry.hipCenter,layerPolicy:record.geometry.layerPolicy};bones(geometry,`${direction}/${phaseId}`);elbows(geometry,`${direction}/${phaseId}`);bonePoseSets++;semantics(geometry,`${direction}/${phaseId}`);direction==='north'?hiddenNorthThumbSides+=2:visibleThumbSides+=2;footSides+=2;if((direction==='south'||direction==='north')&&record.geometry.layerPolicy.join(',')!=='leftArm,rightArm,leftLeg,rightLeg,torso,head'||(direction==='east'||direction==='west')&&record.geometry.layerPolicy.join(',')!=='farArm,farLeg,nearLeg,torso,head,nearArm')throw new Error(`${direction}/${phaseId}/layer policy`);if(phaseId==='01'||phaseId==='05')for(const side of ['left','right']){const j=geometry.joints[side].latent;if((j.wrist.forward-j.shoulder.forward)*(j.ankle.forward-j.hip.forward)>=0)throw new Error(`${direction}/${phaseId}/${side}/contralateral`);contralateral++;}await raster(record,geometry,`${direction}/${phaseId}`);walkFrames++;guides++;neckFrames++;crownFrames++;if(direction==='east'||direction==='west')shoeUpperSides+=2;}
for(const [key,view] of [['standSouth','south'],['sitSouth','south']]){const record=character.static[key],geometry={view,phaseId:key,joints:record.geometry.joints,hipCenter:record.geometry.hipCenter,layerPolicy:record.geometry.layerPolicy};bones(geometry,key);bonePoseSets++;semantics(geometry,key);await raster(record,geometry,key);visibleThumbSides+=2;neckFrames++;crownFrames++;}
const seated=character.static.sitSouth.geometry;for(const side of ['left','right']){const j=seated.joints[side].latent;if(Math.abs(j.hip.height-j.knee.height)>.01||Math.hypot(j.knee.lateral-j.hip.lateral,j.knee.forward-j.hip.forward)<40||Math.abs(j.knee.forward-j.ankle.forward)>.01||!near(j.knee.height-j.ankle.height,MASTER.lengths.shin))throw new Error(`sit/${side}/anatomy`);}
console.log(JSON.stringify({walkFrames,guides,staticPoses:2,boneLengthPoseSets:bonePoseSets,contralateralStrideSides:contralateral,visibleThumbSemanticSides:visibleThumbSides,hiddenNorthThumbSemanticSides:hiddenNorthThumbSides,visibleThumbRasterChecks,hiddenNorthThumbRasterChecks,lateralFarThumbDepthAllowances,explicitFootSides:footSides+4,lateralShoeUpperSides:shoeUpperSides,visibleNeckFrames:neckFrames,completeCrownFrames:crownFrames,seatedAnatomySides:2,identityIndependentGeometry:true,manifestSha256:sha256(manifestBytes)},null,2));
