(()=>{
 const root=document.getElementById('ct-layout-proof'), art=root.querySelector('#ct-art'), ctx=art.getContext('2d'), status=root.querySelector('#ct-status'), overlay=root.querySelector('#ct-overlay'), targets=root.querySelector('#ct-targets');
 const S=120,X=54,Y=136,W=588,H=680,COLS=4,ROWS=4,BOTTOM=Y+ROWS*S,EAST=X+COLS*S,radius=.16,step=.04;
 const segments=[...Array(4)].flatMap((_,i)=>[`N${i+1}`,`S${i+1}`]).concat(['WA','WB','WC','WD','EA','EB','EC','ED']);
 const state={doors:new Set(['S2']),adjacent:new Set(),selected:'S2'};
 const wallDecor=Object.fromEntries([1,2,3,4].map(i=>[`cat${i}`,{id:`cat${i}`,label:`framed cat scan ${i}`,segment:`N${i}`,centerX:X+(i-.5)*S,top:48,width:83,height:80,mount:'north wall',collision:'nonblocking'}]));
 const fixtures={
  scanner:{id:'scanner',label:'CT scanner',physicalFootprints:[{id:'gantry-left-foot',left:.42,top:1.7,width:.46,height:.3},{id:'gantry-right-foot',left:1.98,top:1.7,width:.4,height:.3},{id:'couch-pedestal',left:1.0,top:2.45,width:.8,height:.2}],navigationBlocker:{left:.5,top:1,width:1.8,height:1.65},anchor:{x:1.4,y:2.65},floorContact:{x:387,y:942},seatContact:{x:387,y:762},seat:{x:1.4,y:2.65-(942-762)*(2*120/774)/120,facing:'S'},approach:{x:1.4,y:3.1},collision:'solid',persistence:'permanent'},
  partition:{id:'partition',label:'technician partition',footprint:{left:2.69,top:.75,width:.12,height:2.4},collision:'solid',persistence:'permanent',style:'north-south top-down wall with observation window'},
  console:{id:'console',label:'CT console',footprint:{left:2.9,top:1.72,width:.9,height:.38},anchor:{x:3.35,y:2.1},floorContact:{x:284,y:514},approach:{x:3.35,y:2.7},facing:'S',operatorFacing:'N',collision:'nonblocking',persistence:'permanent'}
 };
 const crops=__CT_CROP_CONFIG__,wallCrops=__CT_WALL_CROP_CONFIG__, atlas=new Image(),wallAtlas=new Image(); atlas.src='data:image/webp;base64,__CT_ATLAS__';wallAtlas.src='data:image/webp;base64,__CT_WALL_ATLAS__'; atlas.onload=render;wallAtlas.onload=render;
 const key=p=>`${p.x.toFixed(2)},${p.y.toFixed(2)}`, inflate=r=>({left:r.left-radius,top:r.top-radius,right:r.left+r.width+radius,bottom:r.top+r.height+radius});
 const blockers=()=>[fixtures.scanner.navigationBlocker,fixtures.partition.footprint].map(inflate);
 const validPoint=p=>p.x>=radius&&p.x<=COLS-radius&&p.y>=radius&&p.y<=ROWS-radius&&!blockers().some(r=>p.x>=r.left&&p.x<=r.right&&p.y>=r.top&&p.y<=r.bottom);
 const snap=p=>({x:Math.round(p.x/step)*step,y:Math.round(p.y/step)*step});
 function bfs(from,to){const a=snap(from),b=snap(to);if(!validPoint(a)||!validPoint(b))return[];const q=[a],prev=new Map([[key(a),null]]),points=new Map([[key(a),a]]),moves=[[step,0],[-step,0],[0,step],[0,-step]];while(q.length){const p=q.shift(),pk=key(p);if(pk===key(b)){const out=[];for(let k=pk;k;k=prev.get(k))out.unshift(points.get(k));return out}for(const[dX,dY]of moves){const n=snap({x:p.x+dX,y:p.y+dY}),nk=key(n);if(validPoint(n)&&!prev.has(nk)){prev.set(nk,pk);points.set(nk,n);q.push(n)}}}return[]}
 const start={x:1.5,y:3.84};
 function doorCandidates(id){const v=[.28,.38,.5,.62,.72],i=id[0]==='N'||id[0]==='S'?Number(id.slice(1))-1:id.charCodeAt(1)-65;return v.map(t=>id[0]==='N'?{x:i+t,y:radius}:id[0]==='S'?{x:i+t,y:ROWS-radius}:id[0]==='W'?{x:radius,y:i+t}:{x:COLS-radius,y:i+t}).filter(validPoint)}
 function routeToDoor(id){return doorCandidates(id).map(p=>bfs(start,p)).filter(p=>p.length).sort((a,b)=>a.length-b.length)[0]||[]}
 let routeCache,serviceCache; const routes=()=>routeCache||(routeCache=Object.fromEntries(segments.map(id=>[id,routeToDoor(id)]))); const serviceRoutes=()=>serviceCache||(serviceCache={patient:bfs(start,fixtures.scanner.approach),technician:bfs(start,fixtures.console.approach)});
 function floor(x,y,w,h){ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.fillStyle='#d7d1cc';ctx.fillRect(x,y,w,h);for(let py=y;py<y+h;py+=12)for(let px=x;px<x+w;px+=12){const n=(px*13+py*7)%19;ctx.fillStyle=n<5?'rgba(245,238,231,.15)':'rgba(73,82,82,.045)';ctx.fillRect(px+(n%5),py+((n*3)%5),2,2)}ctx.strokeStyle='rgba(82,91,88,.10)';for(let py=y;py<=y+h;py+=24){ctx.beginPath();ctx.moveTo(x,py);ctx.lineTo(x+w,py);ctx.stroke()}for(let px=x;px<=x+w;px+=24){ctx.beginPath();ctx.moveTo(px,y);ctx.lineTo(px,y+h);ctx.stroke()}ctx.restore()}
 function drawShell(){const cream='#efe1bd',north='#dacbd5',green='#58735a',light='#789173',dark='#294632',wood='#744a29',low=29,wall=90,cap=14,bg='#f3ead3';ctx.clearRect(0,0,W,H);ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);floor(X,Y,COLS*S,ROWS*S);const tall=i=>{const x=X+i*S;ctx.fillStyle=north;ctx.fillRect(x,Y-wall,S,wall);ctx.fillStyle='rgba(110,75,95,.06)';ctx.fillRect(x+16,Y-wall+31,S-32,2);ctx.fillStyle=green;ctx.fillRect(x,Y-24,S,24);ctx.fillStyle=light;ctx.fillRect(x,Y-24,S,4);ctx.fillStyle=dark;ctx.fillRect(x-1,Y-wall-9,S+2,9);ctx.fillRect(x,Y-7,S,7);ctx.fillStyle=light;ctx.fillRect(x-1,Y-wall-9,S+2,3)};const backed=i=>{const x=X+i*S;ctx.fillStyle=green;ctx.fillRect(x,Y-low,S,low);ctx.fillStyle=light;ctx.fillRect(x,Y-low,S,4);ctx.fillStyle=dark;ctx.fillRect(x,Y-8,S,8)};for(let i=0;i<COLS;i++)state.adjacent.has(`N${i+1}`)?backed(i):tall(i);for(let i=0;i<COLS;i++)if(state.adjacent.has(`N${i+1}`))ctx.clearRect(X+i*S,0,S,Y-low);const side=right=>{const x=right?EAST-2:X-cap+2,neighbor=right?'N4':'N1',top=state.adjacent.has(neighbor)?Y-low:Y-wall-9;ctx.fillStyle=dark;ctx.fillRect(x,top,cap,BOTTOM+29-top);ctx.fillStyle=light;ctx.fillRect(x+(right?0:cap-3),top,3,BOTTOM+29-top)};side(false);side(true);for(let i=0;i<COLS;i++){const x=X+i*S;ctx.fillStyle=cream;ctx.fillRect(x,BOTTOM,S,29);ctx.fillStyle=green;ctx.fillRect(x,BOTTOM+21,S,8);ctx.fillStyle=dark;ctx.fillRect(x,BOTTOM-6,S,8);ctx.fillStyle=light;ctx.fillRect(x,BOTTOM-6,S,3)}const northDoor=i=>{const isBack=state.adjacent.has(`N${i+1}`),l=X+i*S+12,r=X+(i+1)*S-12,t=isBack?Y-low:Y-wall+8;ctx.clearRect(l,t,r-l,Y-t);ctx.fillStyle=wood;ctx.fillRect(l-5,t,5,Y-t);ctx.fillRect(r,t,5,Y-t);if(!isBack)ctx.fillRect(l-5,t-5,r-l+10,6)};const sideDoor=(right,i)=>{const x=right?EAST-2:X-cap+2,t=Y+i*S+12,h=S-24;ctx.clearRect(x,t,cap,h);if(right)floor(x,t,cap/2,h);else floor(x+cap/2,t,cap/2,h);ctx.fillStyle=wood;ctx.fillRect(x-2,t-3,cap+4,5);ctx.fillRect(x-2,t+h-2,cap+4,5)};for(const id of state.doors){if(id[0]==='N')northDoor(+id.slice(1)-1);else if(id[0]==='S'){const i=+id.slice(1)-1,l=X+i*S+12,r=X+(i+1)*S-12;ctx.clearRect(l,BOTTOM-6,r-l,35);floor(l,BOTTOM-6,r-l,35);ctx.fillStyle=wood;ctx.fillRect(l-5,BOTTOM-8,5,37);ctx.fillRect(r,BOTTOM-8,5,37)}else sideDoor(id[0]==='E',id.charCodeAt(1)-65)}}
 function sprite(id,anchor,width,contact){const c=crops[id],scale=width/c.w,h=c.h*scale,x=X+anchor.x*S-contact.x*scale,y=Y+anchor.y*S-contact.y*scale;ctx.drawImage(atlas,c.x,c.y,c.w,c.h,x,y,width,h);return{x,y,w:width,h,baseX:x+contact.x*scale,baseY:y+contact.y*scale,aspect:c.w/c.h}}
 function hiddenWallDecor(){return Object.values(wallDecor).filter(d=>state.doors.has(d.segment)||state.adjacent.has(d.segment)).map(d=>d.id)}
 function drawWallDecor(){const hidden=hiddenWallDecor(),draws={};for(const d of Object.values(wallDecor)){if(hidden.includes(d.id))continue;const c=wallCrops[d.id],x=d.centerX-d.width/2;ctx.drawImage(wallAtlas,c.x,c.y,c.w,c.h,x,d.top,d.width,d.height);draws[d.id]={x,y:d.top,w:d.width,h:d.height,segment:d.segment,mount:'north wall',collision:'nonblocking'}}return{hidden,draws}}
 function drawPartition(){const r=fixtures.partition.footprint,x=X+r.left*S,y=Y+r.top*S,w=r.width*S,h=r.height*S;ctx.fillStyle='#38524a';ctx.fillRect(x,y,w,h);ctx.fillStyle='#7c9680';ctx.fillRect(x,y,w,4);ctx.fillStyle='#294632';ctx.fillRect(x,y,w,3);const wy=y+h*.39,wh=h*.25;ctx.fillStyle='#8ca8ae';ctx.fillRect(x-2,wy,w+4,wh);ctx.fillStyle='#45616a';ctx.fillRect(x-1,wy+3,w+2,wh-6);return{x,y,w,h,window:{x:x-2,y:wy,w:w+4,h:wh}}}
 function drawFurniture(){const decor=drawWallDecor(),scanner=sprite('scanner',fixtures.scanner.anchor,2*S,fixtures.scanner.floorContact),partition=drawPartition(),console=sprite('console',fixtures.console.anchor,1*S,fixtures.console.floorContact);return{scanner,partition,console,decor}}
 function drawOverlay(rs){if(!overlay.checked)return;ctx.save();const r=rs[state.selected]||[];ctx.strokeStyle='#2f7090';ctx.lineWidth=3;ctx.beginPath();r.forEach((p,i)=>i?ctx.lineTo(X+p.x*S,Y+p.y*S):ctx.moveTo(X+p.x*S,Y+p.y*S));ctx.stroke();for(const q of fixtures.scanner.physicalFootprints){ctx.setLineDash([3,3]);ctx.strokeStyle='#8d5a47';ctx.strokeRect(X+q.left*S,Y+q.top*S,q.width*S,q.height*S)}for(const f of [{footprint:fixtures.scanner.navigationBlocker},{footprint:fixtures.partition.footprint}]){const q=f.footprint;ctx.setLineDash([6,4]);ctx.strokeStyle='#6d466e';ctx.strokeRect(X+q.left*S,Y+q.top*S,q.width*S,q.height*S)}ctx.setLineDash([]);for(const[p,label,color]of[[fixtures.scanner.seat,'patient S','#8d5a47'],[fixtures.scanner.approach,'approach','#8d5a47'],[fixtures.console.approach,'tech N','#355f52']]){ctx.fillStyle=color;ctx.beginPath();ctx.arc(X+p.x*S,Y+p.y*S,5,0,7);ctx.fill();ctx.fillText(label,X+p.x*S+7,Y+p.y*S+3)}ctx.restore()}
 function slot(id){if(id[0]==='N'||id[0]==='S'){const i=+id.slice(1)-1;return{x:X+i*S,y:id[0]==='N'?(state.adjacent.has(id)?Y-29:Y-99):BOTTOM,w:S,h:id[0]==='N'?(state.adjacent.has(id)?29:99):29}}const i=id.charCodeAt(1)-65;return{x:id[0]==='W'?X-14:EAST,y:Y+i*S,w:14,h:S}}
 function render(){ctx.setTransform(1,0,0,1,0,0);drawShell();const draws=drawFurniture(),rs=routes();drawOverlay(rs);for(const b of targets.querySelectorAll('button')){const q=slot(b.dataset.segment);Object.assign(b.style,{left:`${q.x/W*100}%`,top:`${q.y/H*100}%`,width:`${q.w/W*100}%`,height:`${q.h/H*100}%`})}for(const btn of root.querySelectorAll('[data-segment]')){const on=state.doors.has(btn.dataset.segment);btn.setAttribute('aria-pressed',String(on));btn.classList.toggle('btn-primary',on)}const service=serviceRoutes();status.textContent=`${state.selected} ${state.doors.has(state.selected)?'open':'closed'} · ${Object.values(rs).filter(p=>p.length).length}/16 doorway approaches · patient ${service.patient.length?'reachable':'blocked'} · technician ${service.technician.length?'reachable':'blocked'}`;art.dataset.model=JSON.stringify({logicalCols:4,logicalRows:4,tileSize:S,doors:segments,adjacent:[...state.adjacent],selected:state.selected,open:[...state.doors],radius,fixtures,wallDecor,hiddenWallDecor:draws.decor.hidden,draws,routes:rs,service,shell:{northFace:'#dacbd5',backedNorth:'green only',rearWallHeight:90,lowNorthHeight:29,sideCapWidth:14,southHeight:29}})}
 for(const prefix of ['N','S','W','E'])for(const id of segments.filter(v=>v[0]===prefix)){const b=document.createElement('button');b.type='button';b.className='btn';b.dataset.segment=id;b.textContent=id;b.setAttribute('aria-label',`Toggle ${id} doorway`);b.onclick=()=>{state.doors.has(id)?state.doors.delete(id):state.doors.add(id);state.selected=id;render()};root.querySelector(`#ct-${prefix}`).append(b)}
 for(const id of segments){const b=document.createElement('button');b.type='button';b.className='ct-hit';b.dataset.segment=id;b.setAttribute('aria-label',`Toggle ${id} doorway`);b.onclick=()=>{state.doors.has(id)?state.doors.delete(id):state.doors.add(id);state.selected=id;render()};targets.append(b)}
 for(let i=1;i<=4;i++){const label=document.createElement('label');label.className='form-check';label.innerHTML=`<input class="form-check-input" type="checkbox" data-adjacent="N${i}"><span class="form-check-label">N${i} backed</span>`;label.querySelector('input').onchange=e=>{e.target.checked?state.adjacent.add(`N${i}`):state.adjacent.delete(`N${i}`);render()};root.querySelector('#ct-adjacent').append(label)}
 overlay.onchange=render; window.__ctLayout={segments,state,fixtures,wallDecor,crops,radius,step,start,validPoint,bfs,doorCandidates,routes,render,hiddenWallDecor,ready:()=>atlas.complete&&atlas.naturalWidth>0&&wallAtlas.complete&&wallAtlas.naturalWidth>0};render();
})();
