import { NEEDS_REVIEW, claim, concept, createDevelopmentFamily, linkSourcesToClaims, source, type CaseSpec } from "./batch-helpers";
const ASGE="source.asge.choledocholithiasis.2019", ESGE="source.esge.cbds.2019";
export const CHOLEDOCHOLITHIASIS_CLAIMS=[
 claim({id:"claim.early.choledocholithiasis.intermediate-mrcp",statement:"A stable patient with intermediate likelihood of a common-bile-duct stone can undergo MRCP to confirm or exclude a duct stone while avoiding diagnostic ERCP.",sourceIds:[ASGE,ESGE],evidenceCategory:"evaluation",certainty:"high",limitation:"EUS is an equally guideline-supported alternative; this family selects MRCP as the locally available noninvasive route.",applicablePopulation:"Stable adults with intermediate-risk features and no cholangitis.",lastCheckedOn:"2026-09-13"}),
 claim({id:"claim.early.choledocholithiasis.confirmed-stone-therapy",statement:"A common-bile-duct stone confirmed on MRCP requires a therapeutic duct-clearance pathway; preoperative therapeutic ERCP is one accepted pathway when that sequence is selected locally.",sourceIds:[ASGE,ESGE],evidenceCategory:"management",certainty:"high",limitation:"Postoperative ERCP and laparoscopic duct treatment are also valid according to local expertise; the cases explicitly select the preoperative endoscopic pathway.",applicablePopulation:"Stable treatment candidates with a confirmed duct stone before planned cholecystectomy.",lastCheckedOn:"2026-09-13"}),
];
export const CHOLEDOCHOLITHIASIS_SOURCES=linkSourcesToClaims([
 source({id:ASGE,title:"ASGE guideline on the role of endoscopy in the evaluation and management of choledocholithiasis",completeCitation:"Buxbaum JL, Abbas Fehmi SM, Sultan S, Fishman DS, Qumseya BJ, Cortessis VK, et al.; ASGE Standards of Practice Committee. Gastrointestinal Endoscopy. 2019;89(6):1075-1105.e15. doi:10.1016/j.gie.2018.10.001.",organizationOrJournal:"American Society for Gastrointestinal Endoscopy",authors:["Buxbaum JL","Abbas Fehmi SM","Sultan S","Fishman DS","Qumseya BJ","Cortessis VK","et al."],publicationYear:2019,doi:"10.1016/j.gie.2018.10.001",pmid:"30979521",officialUrl:"https://pmc.ncbi.nlm.nih.gov/articles/PMC8594622/",accessedOn:"2026-09-13",sourceClass:"professional_society_guideline",licenseLabel:"Copyrighted society and journal guidance available in PubMed Central",reuseStatus:"copyrighted_targeted_verification_only",reuseNotes:"Underlying facts independently synthesized from the successfully reviewed full text; no guideline prose, tables, or algorithms reproduced.",authorityAssessment:"Primary U.S. society guidance for risk-stratified evaluation and duct-stone management.",usageRole:"evidence"}),
 source({id:ESGE,title:"Endoscopic management of common bile duct stones: ESGE guideline",completeCitation:"Manes G, Paspatis G, Aabakken L, Anderloni A, Arvanitakis M, Ah-Soune P, et al. Endoscopy. 2019;51(5):472-491. doi:10.1055/a-0862-0346.",organizationOrJournal:"European Society of Gastrointestinal Endoscopy",authors:["Manes G","Paspatis G","Aabakken L","Anderloni A","Arvanitakis M","Ah-Soune P","et al."],publicationYear:2019,doi:"10.1055/a-0862-0346",pmid:null,officialUrl:"https://www.esge.com/endoscopic-management-of-common-bile-duct-stones-esge-guideline",accessedOn:"2026-09-13",sourceClass:"professional_society_guideline",licenseLabel:"Copyrighted society and journal guidance",reuseStatus:"copyrighted_targeted_verification_only",reuseNotes:"Independent factual corroboration only.",authorityAssessment:"Independent European society corroboration for MRCP/EUS evaluation and treatment of confirmed stones.",usageRole:"cross_check"}),
],CHOLEDOCHOLITHIASIS_CLAIMS);
const test=(id:string,label:string,tp:string,rationale:string,correct=false,serviceId?:string)=>({id,label,rationale,timing:{kind:"test" as const,timingProfileId:tp==="timing.test.hida"?"timing.test.nuclear_imaging":tp},...(correct?{isCorrect:true,...(serviceId?{serviceId}:{})}:{})});
const action=(id:string,label:string,rationale:string,correct=false)=>({id,label,rationale,timing:correct?{kind:"test" as const,timingProfileId:"timing.test.therapeutic_ercp"}:{kind:"no_test" as const},...(correct?{isCorrect:true}:{})});
const stories=[
 ["episodic-pain",[42,44],"Upper abdominal pain","has episodic right-upper-quadrant pain, gallstones, mildly abnormal liver tests, and a mildly widened bile duct on ultrasound; there is no fever, hypotension, jaundice, or cholangitis"],
 ["abnormal-labs",[57,55],"Abnormal liver tests","has gallstones and improving liver-test abnormalities after a brief pain episode; ultrasound shows no definite duct stone, and there is no pancreatitis or cholangitis"],
 ["dilated-duct",[68,66],"Dilated bile duct","has biliary pain, gallstones, and bile-duct dilation without a stone visualized on ultrasound; vital signs are normal and there are no infectious features"],
 ["resolved-colic",[35,37],"Pain after meals","is here after resolved biliary colic; ultrasound shows gallstones without a definite obstructing duct stone, liver enzymes remain mildly elevated, and there is no cholangitis"],
] as const;
const cases:CaseSpec[]=stories.map(([slug,ages,complaint,detail],i)=>{const result="External MRCP shows a common-bile-duct stone. The patient remains clinically stable, and the local pathway calls for endoscopic duct clearance before planned cholecystectomy.";return{id:`case.choledocholithiasis.${slug}`,displayName:"Biliary evaluation",chiefComplaint:complaint,presentation:`{patientName} is a {patientAge}-year-old {patientSex} here for biliary evaluation. {patientName} ${detail}.`,ageYears:ages,sexLabels:["Female","Male"],stage:1,nodes:[{conceptId:"concept.choledocholithiasis.intermediate-mrcp",stem:"Which next test should be ordered for {patientName} to evaluate the possible common-bile-duct stone?",choices:[test(`mrcp_${i}`,"MRCP", "timing.test.mrcp","MRCP evaluates the duct noninvasively in this intermediate-likelihood setting.",true,"service.mrcp"),test(`ercp_${i}`,"Diagnostic ERCP","timing.test.ercp","ERCP carries procedural risk and should not be used only to diagnose this intermediate-likelihood case."),test(`ct_${i}`,"Abdominal CT","timing.test.ct","CT is not the preferred confirmatory duct test in this constrained scenario."),test(`hida_${i}`,"Hepatobiliary scintigraphy","timing.test.hida","This study does not provide the intended duct-stone evaluation.")],explanation:"Use MRCP as the locally selected noninvasive test for an intermediate-likelihood duct stone; EUS would also be guideline-supported.",claimIds:["claim.early.choledocholithiasis.intermediate-mrcp"],gate:{id:`gate.choledocholithiasis.mrcp.${i}`,serviceId:"service.mrcp",pendingLabel:"External MRCP pending",resultNarrative:result,routeIds:["route.mrcp.outsourced"]}},{conceptId:"concept.choledocholithiasis.confirmed-stone-therapy",currentUpdate:result,stem:"Which next step follows the selected preoperative endoscopic pathway for {patientName}'s confirmed duct stone?",choices:[action(`therapeutic_ercp_${i}`,"Refer for therapeutic ERCP","Arrange duct clearance before the planned cholecystectomy.",true),test(`repeat_mrcp_${i}`,"Repeat MRCP","timing.test.mrcp","The stone is already objectively confirmed."),action(`observe_${i}`,"Observe without treatment","A confirmed duct stone requires a clearance plan in this treatment candidate."),action(`chole_only_${i}`,"Schedule cholecystectomy alone","The selected pathway addresses the confirmed duct stone before cholecystectomy.")],explanation:"Refer for therapeutic ERCP to clear the confirmed duct stone in this explicitly selected preoperative pathway.",claimIds:["claim.early.choledocholithiasis.confirmed-stone-therapy"]}]};});
export const CHOLEDOCHOLITHIASIS_CONCEPTS=[concept({id:"concept.choledocholithiasis.intermediate-mrcp",educationalTier:0,displayName:"MRCP for an intermediate-risk duct stone",learningObjective:"Select MRCP for stable intermediate-likelihood choledocholithiasis when the local route favors noninvasive imaging.",earliestFacilityStage:1,conceptType:"workup",evidenceClaimIds:["claim.early.choledocholithiasis.intermediate-mrcp"]}),concept({id:"concept.choledocholithiasis.confirmed-stone-therapy",educationalTier:1,displayName:"Therapeutic ERCP referral for a confirmed duct stone",learningObjective:"Refer a confirmed duct stone for therapeutic ERCP when the selected local pathway clears the duct before cholecystectomy.",earliestFacilityStage:1,conceptType:"management",evidenceClaimIds:["claim.early.choledocholithiasis.confirmed-stone-therapy"]})];
const family=createDevelopmentFamily({concepts:CHOLEDOCHOLITHIASIS_CONCEPTS,cases,sourceLabels:["ASGE choledocholithiasis guideline (2019)","ESGE common-bile-duct-stone guideline (2019)"]});
export const CHOLEDOCHOLITHIASIS_TESTED_CONCEPTS=family.testedConcepts, CHOLEDOCHOLITHIASIS_QUESTIONS=family.questions, CHOLEDOCHOLITHIASIS_CASES=family.cases, CHOLEDOCHOLITHIASIS_CASE_REVIEWS=family.caseReviews, CHOLEDOCHOLITHIASIS_TIMING_ENTRIES=family.timingEntries;
export const CHOLEDOCHOLITHIASIS_AUTHORING_REVIEW=NEEDS_REVIEW;
export const CHOLEDOCHOLITHIASIS_SERVICE_CONTRACTS=[{serviceId:"service.mrcp",allowedRouteIds:["route.mrcp.outsourced"],delivery:"existing_balance_contract" as const}];
