import * as choledo from "./choledocholithiasis";
import * as bileLeak from "./post-cholecystectomy-bile-leak";
import * as pseudocyst from "./pancreatic-pseudocyst";
import * as gerd from "./preoperative-gerd";
import * as pbh from "./post-bariatric-hypoglycemia";
import * as lynch from "./lynch-tumor";
import * as fissure from "./chronic-anal-fissure";
import * as skin from "./cutaneous-scc";
import * as venous from "./venous-leg-ulcer";
import * as spleen from "./splenectomy-infection-prevention";

export const EARLY_LEVELS_20260913_AUTHORING_CONCEPTS = [
  ...choledo.CHOLEDOCHOLITHIASIS_CONCEPTS,
  ...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_CONCEPTS,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_CONCEPTS,
  ...gerd.PREOPERATIVE_GERD_CONCEPTS,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_CONCEPTS,
  ...lynch.LYNCH_TUMOR_CONCEPTS,
  ...fissure.CHRONIC_ANAL_FISSURE_CONCEPTS,
  ...skin.CUTANEOUS_SCC_CONCEPTS,
  ...venous.VENOUS_LEG_ULCER_CONCEPTS,
  ...spleen.SPLENECTOMY_INFECTION_PREVENTION_CONCEPTS,
];
export const EARLY_LEVELS_20260913_TESTED_CONCEPTS = [
  ...choledo.CHOLEDOCHOLITHIASIS_TESTED_CONCEPTS,
  ...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_TESTED_CONCEPTS,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_TESTED_CONCEPTS,
  ...gerd.PREOPERATIVE_GERD_TESTED_CONCEPTS,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_TESTED_CONCEPTS,
  ...lynch.LYNCH_TUMOR_TESTED_CONCEPTS,
  ...fissure.CHRONIC_ANAL_FISSURE_TESTED_CONCEPTS,
  ...skin.CUTANEOUS_SCC_TESTED_CONCEPTS,
  ...venous.VENOUS_LEG_ULCER_TESTED_CONCEPTS,
  ...spleen.SPLENECTOMY_INFECTION_PREVENTION_TESTED_CONCEPTS,
];
export const EARLY_LEVELS_20260913_QUESTIONS = [
  ...choledo.CHOLEDOCHOLITHIASIS_QUESTIONS,...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_QUESTIONS,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_QUESTIONS,...gerd.PREOPERATIVE_GERD_QUESTIONS,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_QUESTIONS,...lynch.LYNCH_TUMOR_QUESTIONS,
  ...fissure.CHRONIC_ANAL_FISSURE_QUESTIONS,...skin.CUTANEOUS_SCC_QUESTIONS,
  ...venous.VENOUS_LEG_ULCER_QUESTIONS,...spleen.SPLENECTOMY_INFECTION_PREVENTION_QUESTIONS,
];
export const EARLY_LEVELS_20260913_CASES = [
  ...choledo.CHOLEDOCHOLITHIASIS_CASES,...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_CASES,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_CASES,...gerd.PREOPERATIVE_GERD_CASES,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_CASES,...lynch.LYNCH_TUMOR_CASES,
  ...fissure.CHRONIC_ANAL_FISSURE_CASES,...skin.CUTANEOUS_SCC_CASES,
  ...venous.VENOUS_LEG_ULCER_CASES,...spleen.SPLENECTOMY_INFECTION_PREVENTION_CASES,
];
export const EARLY_LEVELS_20260913_CLAIMS = [
  ...choledo.CHOLEDOCHOLITHIASIS_CLAIMS,...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_CLAIMS,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_CLAIMS,...gerd.PREOPERATIVE_GERD_CLAIMS,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_CLAIMS,...lynch.LYNCH_TUMOR_CLAIMS,
  ...fissure.CHRONIC_ANAL_FISSURE_CLAIMS,...skin.CUTANEOUS_SCC_CLAIMS,
  ...venous.VENOUS_LEG_ULCER_CLAIMS,...spleen.SPLENECTOMY_INFECTION_PREVENTION_CLAIMS,
];
export const EARLY_LEVELS_20260913_SOURCES = [
  ...choledo.CHOLEDOCHOLITHIASIS_SOURCES,...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_SOURCES,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_SOURCES,...gerd.PREOPERATIVE_GERD_SOURCES,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_SOURCES,...lynch.LYNCH_TUMOR_SOURCES,
  ...fissure.CHRONIC_ANAL_FISSURE_SOURCES,...skin.CUTANEOUS_SCC_SOURCES,
  ...venous.VENOUS_LEG_ULCER_SOURCES,...spleen.SPLENECTOMY_INFECTION_PREVENTION_SOURCES,
];
export const EARLY_LEVELS_20260913_CASE_REVIEWS = [
  ...choledo.CHOLEDOCHOLITHIASIS_CASE_REVIEWS,...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_CASE_REVIEWS,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_CASE_REVIEWS,...gerd.PREOPERATIVE_GERD_CASE_REVIEWS,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_CASE_REVIEWS,...lynch.LYNCH_TUMOR_CASE_REVIEWS,
  ...fissure.CHRONIC_ANAL_FISSURE_CASE_REVIEWS,...skin.CUTANEOUS_SCC_CASE_REVIEWS,
  ...venous.VENOUS_LEG_ULCER_CASE_REVIEWS,...spleen.SPLENECTOMY_INFECTION_PREVENTION_CASE_REVIEWS,
];
export const EARLY_LEVELS_20260913_SERVICE_CONTRACTS = [
  ...choledo.CHOLEDOCHOLITHIASIS_SERVICE_CONTRACTS,...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_SERVICE_CONTRACTS,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_SERVICE_CONTRACTS,...gerd.PREOPERATIVE_GERD_SERVICE_CONTRACTS,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_SERVICE_CONTRACTS,...lynch.LYNCH_TUMOR_SERVICE_CONTRACTS,
  ...fissure.CHRONIC_ANAL_FISSURE_SERVICE_CONTRACTS,...skin.CUTANEOUS_SCC_SERVICE_CONTRACTS,
  ...venous.VENOUS_LEG_ULCER_SERVICE_CONTRACTS,...spleen.SPLENECTOMY_INFECTION_PREVENTION_SERVICE_CONTRACTS,
];
export const EARLY_LEVELS_20260913_TIMING_ENTRIES = [
  ...choledo.CHOLEDOCHOLITHIASIS_TIMING_ENTRIES,...bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_TIMING_ENTRIES,
  ...pseudocyst.PANCREATIC_PSEUDOCYST_TIMING_ENTRIES,...gerd.PREOPERATIVE_GERD_TIMING_ENTRIES,
  ...pbh.POST_BARIATRIC_HYPOGLYCEMIA_TIMING_ENTRIES,...lynch.LYNCH_TUMOR_TIMING_ENTRIES,
  ...fissure.CHRONIC_ANAL_FISSURE_TIMING_ENTRIES,...skin.CUTANEOUS_SCC_TIMING_ENTRIES,
  ...venous.VENOUS_LEG_ULCER_TIMING_ENTRIES,...spleen.SPLENECTOMY_INFECTION_PREVENTION_TIMING_ENTRIES,
];

export const EARLY_LEVELS_20260913_BATCH_MANIFEST = {
  contentVersion: "development-batch.2026-09-13.1",
  authoringConceptCount: EARLY_LEVELS_20260913_AUTHORING_CONCEPTS.length,
  testedConceptCount: EARLY_LEVELS_20260913_TESTED_CONCEPTS.length,
  questionVariantCount: EARLY_LEVELS_20260913_QUESTIONS.length,
  caseCount: EARLY_LEVELS_20260913_CASES.length,
  decisionNodeCount: EARLY_LEVELS_20260913_CASES.flatMap((item) => item.decisionNodes).length,
  multistepCaseCount: EARLY_LEVELS_20260913_CASES.filter((item) => item.decisionNodes.length > 1).length,
  resultGateCount: EARLY_LEVELS_20260913_CASES.flatMap((item) => item.decisionNodes).filter((node) => node.resultGateAfter !== null).length,
  caseReviewCount: EARLY_LEVELS_20260913_CASE_REVIEWS.length,
  sourceCount: EARLY_LEVELS_20260913_SOURCES.length,
  evidenceClaimCount: EARLY_LEVELS_20260913_CLAIMS.length,
  serviceContractCount: EARLY_LEVELS_20260913_SERVICE_CONTRACTS.length,
  timingEntryCount: EARLY_LEVELS_20260913_TIMING_ENTRIES.length,
  admissionScope: "active_synthetic_unapproved_prototype",
  publicReleaseAuthorized: false,
} as const;
