import { describe, expect, it } from "vitest";
import { syntheticClinicalCaseSchema, testedConceptSchema } from "../../schema";
import * as choledo from "./choledocholithiasis";
import * as bileLeak from "./post-cholecystectomy-bile-leak";
import * as pseudocyst from "./pancreatic-pseudocyst";
import * as gerd from "./preoperative-gerd";
import * as pbh from "./post-bariatric-hypoglycemia";

const families = [
  [choledo.CHOLEDOCHOLITHIASIS_CONCEPTS,choledo.CHOLEDOCHOLITHIASIS_TESTED_CONCEPTS,choledo.CHOLEDOCHOLITHIASIS_QUESTIONS,choledo.CHOLEDOCHOLITHIASIS_CASES,choledo.CHOLEDOCHOLITHIASIS_CLAIMS,choledo.CHOLEDOCHOLITHIASIS_SOURCES,choledo.CHOLEDOCHOLITHIASIS_CASE_REVIEWS,choledo.CHOLEDOCHOLITHIASIS_TIMING_ENTRIES],
  [bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_CONCEPTS,bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_TESTED_CONCEPTS,bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_QUESTIONS,bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_CASES,bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_CLAIMS,bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_SOURCES,bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_CASE_REVIEWS,bileLeak.POST_CHOLECYSTECTOMY_BILE_LEAK_TIMING_ENTRIES],
  [pseudocyst.PANCREATIC_PSEUDOCYST_CONCEPTS,pseudocyst.PANCREATIC_PSEUDOCYST_TESTED_CONCEPTS,pseudocyst.PANCREATIC_PSEUDOCYST_QUESTIONS,pseudocyst.PANCREATIC_PSEUDOCYST_CASES,pseudocyst.PANCREATIC_PSEUDOCYST_CLAIMS,pseudocyst.PANCREATIC_PSEUDOCYST_SOURCES,pseudocyst.PANCREATIC_PSEUDOCYST_CASE_REVIEWS,pseudocyst.PANCREATIC_PSEUDOCYST_TIMING_ENTRIES],
  [gerd.PREOPERATIVE_GERD_CONCEPTS,gerd.PREOPERATIVE_GERD_TESTED_CONCEPTS,gerd.PREOPERATIVE_GERD_QUESTIONS,gerd.PREOPERATIVE_GERD_CASES,gerd.PREOPERATIVE_GERD_CLAIMS,gerd.PREOPERATIVE_GERD_SOURCES,gerd.PREOPERATIVE_GERD_CASE_REVIEWS,gerd.PREOPERATIVE_GERD_TIMING_ENTRIES],
  [pbh.POST_BARIATRIC_HYPOGLYCEMIA_CONCEPTS,pbh.POST_BARIATRIC_HYPOGLYCEMIA_TESTED_CONCEPTS,pbh.POST_BARIATRIC_HYPOGLYCEMIA_QUESTIONS,pbh.POST_BARIATRIC_HYPOGLYCEMIA_CASES,pbh.POST_BARIATRIC_HYPOGLYCEMIA_CLAIMS,pbh.POST_BARIATRIC_HYPOGLYCEMIA_SOURCES,pbh.POST_BARIATRIC_HYPOGLYCEMIA_CASE_REVIEWS,pbh.POST_BARIATRIC_HYPOGLYCEMIA_TIMING_ENTRIES],
] as const;
const concepts=families.flatMap(f=>[...f[0]]),tested=families.flatMap(f=>[...f[1]]),questions=families.flatMap(f=>[...f[2]]),cases=families.flatMap(f=>[...f[3]]),claims=families.flatMap(f=>[...f[4]]),sources=families.flatMap(f=>[...f[5]]),reviews=families.flatMap(f=>[...f[6]]),timing=families.flatMap(f=>[...f[7]]);

describe("2026-09-13 foregut and biliary authoring",()=>{
 it("contains ten concepts and four variants per concept",()=>{expect(concepts).toHaveLength(10);expect(questions).toHaveLength(40);expect(cases).toHaveLength(24);expect(timing).toHaveLength(40);expect(new Set(concepts.map(c=>c.id)).size).toBe(10);for(const c of concepts)expect(questions.filter(q=>q.conceptId===c.id)).toHaveLength(4);});
 it("keeps schema, identity, review, and source links intact",()=>{const bySource=new Map(sources.map(s=>[s.id,s]));for(const item of [...concepts,...questions,...claims,...sources,...reviews]){expect(item.reviewStatus).toBe("needs_clinician_review");expect(item.lastClinicianReview).toBeNull();expect(item.aiAssistedDrafting).toBe(true);}for(const c of tested)expect(testedConceptSchema.parse(c)).toEqual(c);for(const c of cases){expect(syntheticClinicalCaseSchema.parse(c)).toEqual(c);expect(c.chiefComplaint.trim().split(/\s+/).length).toBeGreaterThan(0);expect(c.chiefComplaint.trim().split(/\s+/).length).toBeLessThanOrEqual(5);expect(c.presentation).toContain("{patientName}");expect(c.presentation).toMatch(/\d+-year-old (woman|man|adult)/);expect(c.approvedInstantiationProfiles).toHaveLength(4);for(const p of c.approvedInstantiationProfiles){expect(p.presentation).toContain("{patientName}");expect(p.presentation).toMatch(/\d+-year-old (woman|man|adult)/);}for(const n of c.decisionNodes)expect(n.answerChoices.filter(a=>a.isCorrect)).toHaveLength(1);}for(const c of claims)for(const id of c.sourceIds)expect(bySource.get(id)?.evidenceClaimIds).toContain(c.id);});
 it("withholds every diagnostic result until the gate returns",()=>{const gated=cases.filter(c=>c.decisionNodes.length===2);expect(gated).toHaveLength(16);for(const c of gated){const [first,second]=c.decisionNodes;expect(first?.resultGateAfter).not.toBeNull();expect(second?.currentUpdate).toBe(first?.resultGateAfter?.resultNarrative);expect(first?.answerChoices.find(a=>a.isCorrect)?.serviceRequest?.serviceId).toBe(first?.resultGateAfter?.resultTypeId);expect(c.presentation).not.toContain(first?.resultGateAfter?.resultNarrative ?? "__missing__");}expect(pbh.POST_BARIATRIC_HYPOGLYCEMIA_CASES.every(c=>c.decisionNodes.length===1&&c.decisionNodes[0]?.resultGateAfter===null)).toBe(true);});
 it("records timing for every testing choice without inferring correctness",()=>{for(const entry of timing){const node=cases.find(c=>c.id===entry.caseId)?.decisionNodes.find(n=>n.id===entry.nodeId);expect(node?.questionVariantId).toBe(entry.questionVariantId);if(entry.classification.kind==="test_choices"){expect(entry.classification.choices).toHaveLength(4);for(const choice of entry.classification.choices)expect(node?.answerChoices.some(a=>a.id===choice.choiceId&&a.label===choice.choiceLabel)).toBe(true);}}});
 it("assigns procedure timing only to the matching final referral",()=>{const byQuestion=new Map(timing.map(entry=>[entry.questionVariantId,entry]));for(const question of questions.filter(q=>q.conceptId.includes("confirmed-stone-therapy")||q.conceptId.includes("minor-leak-ercp-stent")||q.conceptId.includes("symptomatic-endoscopic-drainage"))){const entry=byQuestion.get(question.id);expect(entry?.classification.kind).toBe("test_choices");if(entry?.classification.kind!=="test_choices")continue;const correct=question.answerChoices.find(choice=>choice.isCorrect)!;expect(entry.classification.choices.find(choice=>choice.choiceId===correct.id)?.timing.kind).toBe("test");for(const choice of question.answerChoices.filter(choice=>!choice.isCorrect&&choice.label!=="Repeat MRCP"))expect(entry.classification.choices.find(item=>item.choiceId===choice.id)?.timing.kind).toBe("no_test");const repeat=question.answerChoices.find(choice=>choice.label==="Repeat MRCP");if(repeat)expect(entry.classification.choices.find(item=>item.choiceId===repeat.id)?.timing).toEqual({kind:"test",timingProfileId:"timing.test.mrcp"});}});
 it("does not make a keyed answer uniquely longest",()=>{const violations=questions.flatMap(question=>{const correct=question.answerChoices.find(choice=>choice.isCorrect);const longestDistractor=Math.max(...question.answerChoices.filter(choice=>!choice.isCorrect).map(choice=>choice.label.length));return correct&&correct.label.length>longestDistractor?[{questionVariantId:question.id,correctLength:correct.label.length,longestDistractor}]:[];});expect(violations).toEqual([]);});
 it("preserves key clinical sequencing and exclusions",()=>{const all=JSON.stringify(cases);expect(all).toContain("Contrast CT has excluded an uncontrolled collection");expect(all).toContain("without solid debris");expect(all).toContain("GERD is not yet objectively proven");expect(all).toContain("venous plasma glucose measured 48 mg/dL");for(const c of pseudocyst.PANCREATIC_PSEUDOCYST_CASES){expect(c.decisionNodes[0]?.answerChoices.find(a=>a.isCorrect)?.label).toBe("Contrast-enhanced CT");expect(c.decisionNodes[1]?.currentUpdate).toContain("compatible with a pancreatic pseudocyst");}});
});
