import { NEEDS_REVIEW, claim, concept, createDevelopmentFamily, linkSourcesToClaims, source, type CaseSpec } from "./batch-helpers";
const NCI="source.lynch.nci-colorectal-genetics-pdq.2026", COUNSEL="source.lynch.nci-genetic-counseling-pdq.2026";
export const LYNCH_TUMOR_CLAIMS=[
claim({id:"claim.lynch-tumor.universal-mmr-screening-new-crc",statement:"MMR IHC or MSI tumor testing can screen a newly diagnosed colorectal cancer for a possible Lynch-syndrome signal. Tumor screening is not germline testing and does not itself diagnose Lynch syndrome.",sourceIds:[NCI],evidenceCategory:"evaluation",certainty:"high",limitation:"Institutional pathways vary, and a screening result requires interpretation rather than a hereditary diagnosis.",applicablePopulation:"Adults with newly diagnosed colorectal cancer and no prior tumor MMR evaluation.",lastCheckedOn:"2026-09-13"}),
claim({id:"claim.lynch-tumor.genetics-counseling-after-suggestive-ihc",statement:"After a Lynch-suggestive tumor result, genetics counseling and germline-testing discussion are appropriate before assigning an inherited syndrome or family testing plan.",sourceIds:[NCI,COUNSEL],evidenceCategory:"management",certainty:"high",limitation:"MSH2/MSH6 loss can have germline, somatic, or EPCAM-related explanations; the case does not select a specific panel or result.",applicablePopulation:"Adults with colorectal-tumor IHC showing MSH2 and MSH6 loss with retained internal controls.",lastCheckedOn:"2026-09-13"})];
export const LYNCH_TUMOR_SOURCES=linkSourcesToClaims([
source({id:NCI,title:"Genetics of Colorectal Cancer (PDQ), Health Professional Version",completeCitation:"PDQ Cancer Genetics Editorial Board. Genetics of Colorectal Cancer (PDQ®), Health Professional Version. National Cancer Institute. Live summary accessed 2026-09-13.",organizationOrJournal:"National Cancer Institute",authors:["PDQ Cancer Genetics Editorial Board"],publicationYear:null,doi:null,pmid:null,officialUrl:"https://www.cancer.gov/types/colorectal/hp/colorectal-genetics-pdq",accessedOn:"2026-09-13",sourceClass:"government_guidance",licenseLabel:"United States government factual material; NCI conditions apply",reuseStatus:"public_domain_conditions_apply",reuseNotes:"Original factual synthesis only; no PDQ prose, tables, figures, or marks reproduced.",authorityAssessment:"Direct current professional summary for universal tumor testing, MMR IHC interpretation, and hereditary evaluation.",usageRole:"evidence"}),
source({id:COUNSEL,title:"Cancer Genetics Risk Assessment and Counseling (PDQ), Health Professional Version",completeCitation:"PDQ Cancer Genetics Editorial Board. Cancer Genetics Risk Assessment and Counseling (PDQ®), Health Professional Version. National Cancer Institute. Live summary accessed 2026-09-13.",organizationOrJournal:"National Cancer Institute",authors:["PDQ Cancer Genetics Editorial Board"],publicationYear:null,doi:null,pmid:null,officialUrl:"https://www.cancer.gov/publications/pdq/information-summaries/genetics/risk-assessment-hp-pdq",accessedOn:"2026-09-13",sourceClass:"government_guidance",licenseLabel:"United States government factual material; NCI conditions apply",reuseStatus:"public_domain_conditions_apply",reuseNotes:"Original factual synthesis only.",authorityAssessment:"Independent current support for counseling and consent before germline testing.",usageRole:"cross_check"})],LYNCH_TUMOR_CLAIMS);
const t=(id:string,label:string,tp:string,rationale:string,correct=false,serviceId?:string)=>({id,label,rationale,timing:{kind:"test" as const,timingProfileId:tp},...(correct?{isCorrect:true,...(serviceId?{serviceId}:{})}:{})});
const a=(id:string,label:string,rationale:string,correct=false)=>({id,label,rationale,timing:{kind:"no_test" as const},...(correct?{isCorrect:true}:{})});
const stories=[["new-diagnosis",[46,48],"Colon cancer testing","has newly diagnosed colorectal cancer with no prior mismatch-repair tumor evaluation"],["resection-review",[59,57],"Pathology review","is reviewing newly diagnosed colorectal cancer before definitive treatment planning"],["oncology-visit",[38,40],"Cancer workup","has a new colorectal cancer diagnosis and asks how inherited-risk screening begins"],["family-history",[67,65],"Genetics question","has colorectal cancer and an incomplete family history without prior tumor screening"]] as const;
const cases:CaseSpec[]=stories.map(([slug,ages,complaint,detail],i)=>{const result="Tumor IHC retains internal controls and shows loss of MSH2 and MSH6 expression.";return{id:`case.lynch-tumor.${slug}`,displayName:"Colorectal tumor review",chiefComplaint:complaint,presentation:`{patientName} is a {patientAge}-year-old {patientSex} attending colorectal clinic. {patientName} ${detail}.`,ageYears:ages,sexLabels:["Female","Male"],stage:1,nodes:[{conceptId:"concept.lynch-tumor.universal-mmr-screening",stem:"Which tumor study should be arranged for {patientName}'s newly diagnosed colorectal cancer to screen for a Lynch-syndrome signal?",choices:[t(`mmr_ihc_${i}`,"MMR immunohistochemistry","timing.test.tumor_mmr_ihc","This tumor study can identify loss of mismatch-repair proteins.",true,"service.tumor_mmr_ihc"),t(`kras_${i}`,"Tumor KRAS analysis","timing.test.pathology_review","KRAS analysis does not test mismatch-repair status."),t(`germline_${i}`,"Germline multigene testing","timing.test.genetic","Germline testing follows counseling and is not the tumor-screening study."),t(`cea_${i}`,"Serum CEA measurement","timing.test.basic_labs","CEA does not assess mismatch-repair status.")],explanation:"Use tumor MMR IHC for this universal screening step; the other tests do not supply the intended MMR protein result.",claimIds:["claim.lynch-tumor.universal-mmr-screening-new-crc"],gate:{id:`gate.lynch-tumor.ihc.${i}`,serviceId:"service.tumor_mmr_ihc",pendingLabel:"Tumor MMR immunohistochemistry pending",resultNarrative:result,routeIds:["route.tumor_mmr_ihc.outsourced"]}},{conceptId:"concept.lynch-tumor.germline-counseling-after-suggestive-ihc",currentUpdate:result,stem:"After {patientName}'s returned MSH2/MSH6-loss pattern, which next step best addresses possible inherited cancer risk?",choices:[a(`counsel_${i}`,"Refer for genetics counseling","Counseling and germline-testing discussion follow a suggestive tumor screen.",true),a(`label_${i}`,"Diagnose Lynch syndrome","Tumor IHC alone does not establish a germline syndrome."),t(`methylation_${i}`,"Order MLH1 methylation testing","timing.test.pathology_review","MLH1 reflex testing is not the selected next step for this MSH2/MSH6 pattern."),t(`family_${i}`,"Arrange relative genetic testing","timing.test.genetic","Family testing follows an appropriately interpreted inherited finding.")],explanation:"Refer for genetics counseling and germline-testing discussion after this suggestive tumor result; do not assign Lynch syndrome from IHC alone.",claimIds:["claim.lynch-tumor.genetics-counseling-after-suggestive-ihc"]}]};});
export const LYNCH_TUMOR_CONCEPTS=[concept({id:"concept.lynch-tumor.universal-mmr-screening",educationalTier:0,displayName:"Tumor MMR screening in colorectal cancer",learningObjective:"Select tumor MMR IHC screening for a newly diagnosed colorectal cancer in the local universal-screening pathway.",earliestFacilityStage:1,conceptType:"workup",evidenceClaimIds:["claim.lynch-tumor.universal-mmr-screening-new-crc"]}),concept({id:"concept.lynch-tumor.germline-counseling-after-suggestive-ihc",educationalTier:1,displayName:"Genetics counseling after suggestive tumor IHC",learningObjective:"Refer a Lynch-suggestive MSH2/MSH6-loss tumor result for genetics counseling and germline-testing discussion.",earliestFacilityStage:1,conceptType:"management",evidenceClaimIds:["claim.lynch-tumor.genetics-counseling-after-suggestive-ihc"]})];
const family=createDevelopmentFamily({concepts:LYNCH_TUMOR_CONCEPTS,cases,sourceLabels:["NCI colorectal genetics PDQ","NCI cancer genetics counseling PDQ"]});
export const LYNCH_TUMOR_TESTED_CONCEPTS=family.testedConcepts,LYNCH_TUMOR_QUESTIONS=family.questions,LYNCH_TUMOR_CASES=family.cases,LYNCH_TUMOR_CASE_REVIEWS=family.caseReviews,LYNCH_TUMOR_TIMING_ENTRIES=family.timingEntries,LYNCH_TUMOR_AUTHORING_REVIEW=NEEDS_REVIEW;
export const LYNCH_TUMOR_SERVICE_CONTRACTS=[{serviceId:"service.tumor_mmr_ihc",allowedRouteIds:["route.tumor_mmr_ihc.outsourced"],delivery:"new_external_contract_required" as const}];
