import { NEEDS_REVIEW, claim, concept, createDevelopmentFamily, linkSourcesToClaims, source, type CaseSpec } from "./batch-helpers";
const WSES="source.wses.bile-duct-injury.2021",ESGE="source.esge.biliary-stenting.2018";
export const POST_CHOLECYSTECTOMY_BILE_LEAK_CLAIMS=[claim({id:"claim.early.bile-leak.ce-mrcp-anatomic-localization",statement:"After CT assesses postoperative collections, contrast-enhanced MRCP with a hepatobiliary agent can anatomically localize a suspected bile leak and evaluate duct continuity; scintigraphy can demonstrate active leakage but has limited spatial detail.",sourceIds:[WSES],evidenceCategory:"evaluation",certainty:"moderate",limitation:"The dedicated hepatobiliary-contrast study is a distinct external service; this claim does not make MRCP the first test in an unstable patient.",applicablePopulation:"Stable post-cholecystectomy adults after CT excludes an uncontrolled collection.",lastCheckedOn:"2026-09-13"}),claim({id:"claim.early.bile-leak.minor-leak-ercp-stent",statement:"A persistent minor postoperative bile leak with preserved common-duct continuity can be referred for ERCP with transpapillary plastic-stent treatment.",sourceIds:[WSES,ESGE],evidenceCategory:"management",certainty:"high",limitation:"Excludes sepsis, peritonitis, uncontrolled collections, and complete common-bile-duct or common-hepatic-duct transection.",applicablePopulation:"Stable patients with a persistent minor post-cholecystectomy leak and preserved duct continuity.",lastCheckedOn:"2026-09-13"})];
export const POST_CHOLECYSTECTOMY_BILE_LEAK_SOURCES=linkSourcesToClaims([source({id:WSES,title:"2020 WSES guidelines for the detection and management of bile duct injury during cholecystectomy",completeCitation:"de'Angelis N, Catena F, Memeo R, Coccolini F, Martínez-Pérez A, Romeo OM, et al. World Journal of Emergency Surgery. 2021;16:30. doi:10.1186/s13017-021-00369-w.",organizationOrJournal:"World Society of Emergency Surgery",authors:["de'Angelis N","Catena F","Memeo R","Coccolini F","Martínez-Pérez A","Romeo OM","et al."],publicationYear:2021,doi:"10.1186/s13017-021-00369-w",pmid:null,officialUrl:"https://link.springer.com/article/10.1186/s13017-021-00369-w",accessedOn:"2026-09-13",sourceClass:"professional_society_guideline",licenseLabel:"Creative Commons Attribution 4.0",reuseStatus:"cc_by_4_0",reuseNotes:"Original summaries with attribution; no source prose, tables, figures, or algorithms reproduced.",authorityAssessment:"Primary open society guideline supporting CT-first context, CE-MRCP anatomy, and step-up treatment of minor leaks.",usageRole:"evidence"}),source({id:ESGE,title:"Endoscopic biliary stenting: indications, choice of stents, and results",completeCitation:"Dumonceau JM, Tringali A, Papanikolaou IS, Blero D, Mangiavillano B, Schmidt A, et al. Endoscopy. 2018;50:910-930. doi:10.1055/a-0659-9864.",organizationOrJournal:"European Society of Gastrointestinal Endoscopy",authors:["Dumonceau JM","Tringali A","Papanikolaou IS","Blero D","Mangiavillano B","Schmidt A","et al."],publicationYear:2018,doi:"10.1055/a-0659-9864",pmid:null,officialUrl:"https://www.esge.com/endoscopic-biliary-stenting-indications-choice-of-stents-and-results-2017",accessedOn:"2026-09-13",sourceClass:"professional_society_guideline",licenseLabel:"Copyrighted society and journal guidance",reuseStatus:"copyrighted_targeted_verification_only",reuseNotes:"Targeted factual corroboration only.",authorityAssessment:"Independent society corroboration for plastic-stent treatment of non-transection bile leaks.",usageRole:"cross_check"})],POST_CHOLECYSTECTOMY_BILE_LEAK_CLAIMS);
const t=(id:string,label:string,tp:string,rationale:string,correct=false,serviceId?:string)=>({id,label,rationale,timing:{kind:"test" as const,timingProfileId:tp==="timing.test.hida"?"timing.test.nuclear_imaging":tp},...(correct?{isCorrect:true,...(serviceId?{serviceId}:{})}:{})});
const a=(id:string,label:string,rationale:string,correct=false)=>({id,label,rationale,timing:correct?{kind:"test" as const,timingProfileId:"timing.test.bile_leak_ercp"}:{kind:"no_test" as const},...(correct?{isCorrect:true}:{})});
const stories=[
 ["drain-output",[46,48],"Bilious drain output","has persistent bilious surgical-drain output despite initial observation after laparoscopic cholecystectomy"],
 ["painful-recovery",[61,59],"Persistent abdominal pain","has persistent bilious drain output and right-upper-quadrant discomfort despite initial observation after cholecystectomy"],
 ["delayed-recovery",[38,40],"Slow surgical recovery","has persistent low-volume bilious drain output and nausea despite initial observation after cholecystectomy"],
 ["outside-followup",[70,68],"Drain follow-up","was referred for persistent bilious drain output despite initial observation after an outside cholecystectomy"],
] as const;
const cases:CaseSpec[]=stories.map(([slug,ages,complaint,detail],i)=>{const result="Hepatobiliary-contrast MRCP localizes a cystic-duct-stump leak, shows preserved common-duct continuity, and finds no major transection. The leak persists despite initial observation.";return{id:`case.post-cholecystectomy-bile-leak.${slug}`,displayName:"Drain follow-up",chiefComplaint:complaint,presentation:`{patientName} is a {patientAge}-year-old {patientSex} who ${detail}. Contrast CT has excluded an uncontrolled collection. There is no fever, peritonitis, hypotension, or sepsis.`,ageYears:ages,sexLabels:["Female","Male"],stage:2,nodes:[{conceptId:"concept.bile-leak.hepatobiliary-contrast-mrcp",stem:"Which test should be ordered next to localize {patientName}'s suspected leak and assess duct continuity?",choices:[t(`cemrcp_${i}`,"Hepatobiliary CE-MRCP","timing.test.hepatobiliary_contrast_mrcp","This study can localize the leak and show duct continuity.",true,"service.hepatobiliary_contrast_mrcp"),t(`hida_${i}`,"Hepatobiliary scintigraphy","timing.test.hida","Scintigraphy may show leakage but gives less anatomic detail for this task."),t(`us_${i}`,"Abdominal ultrasound","timing.test.ultrasound","Ultrasound does not supply the requested leak localization and duct-continuity assessment."),t(`ct_${i}`,"Repeat contrast CT","timing.test.ct","CT has already assessed the collection question and is less definitive for this anatomic task.")],explanation:"After CT excludes an uncontrolled collection, order dedicated hepatobiliary-contrast MRCP to localize the leak and evaluate duct continuity.",claimIds:["claim.early.bile-leak.ce-mrcp-anatomic-localization"],gate:{id:`gate.bile-leak.cemrcp.${i}`,serviceId:"service.hepatobiliary_contrast_mrcp",pendingLabel:"External hepatobiliary-contrast MRCP pending",resultNarrative:result,routeIds:["route.hepatobiliary_contrast_mrcp.outsourced"]}},{conceptId:"concept.bile-leak.minor-leak-ercp-stent",currentUpdate:result,stem:"Which treatment referral is appropriate for {patientName}'s persistent minor leak with preserved duct continuity?",choices:[a(`ercp_stent_${i}`,"Refer for ERCP with stent","This treats the persistent minor leak through a transpapillary pathway.",true),a(`observe_${i}`,"Continue observation alone","The leak has persisted despite initial observation."),a(`hepaticojejunostomy_${i}`,"Refer for hepaticojejunostomy","Reconstruction is not the intended treatment for a minor leak with intact continuity."),a(`reexplore_${i}`,"Schedule immediate reexploration","The stable minor-leak scenario lacks the major-injury findings that would drive urgent surgery.")],explanation:"Refer the persistent minor leak with intact major-duct continuity for ERCP with plastic-stent treatment.",claimIds:["claim.early.bile-leak.minor-leak-ercp-stent"]}]};});
export const POST_CHOLECYSTECTOMY_BILE_LEAK_CONCEPTS=[concept({id:"concept.bile-leak.hepatobiliary-contrast-mrcp",educationalTier:0,displayName:"Hepatobiliary-contrast MRCP for bile-leak anatomy",learningObjective:"Select hepatobiliary-contrast MRCP after CT to localize a stable postoperative bile leak and assess duct continuity.",earliestFacilityStage:2,conceptType:"workup",evidenceClaimIds:["claim.early.bile-leak.ce-mrcp-anatomic-localization"]}),concept({id:"concept.bile-leak.minor-leak-ercp-stent",educationalTier:1,displayName:"ERCP stent referral for a persistent minor bile leak",learningObjective:"Refer a persistent minor leak with preserved duct continuity for ERCP and plastic-stent treatment.",earliestFacilityStage:2,conceptType:"management",evidenceClaimIds:["claim.early.bile-leak.minor-leak-ercp-stent"]})];
const family=createDevelopmentFamily({concepts:POST_CHOLECYSTECTOMY_BILE_LEAK_CONCEPTS,cases,sourceLabels:["WSES bile duct injury guideline (2021)","ESGE biliary stenting guideline (2018)"]});
export const POST_CHOLECYSTECTOMY_BILE_LEAK_TESTED_CONCEPTS=family.testedConcepts,POST_CHOLECYSTECTOMY_BILE_LEAK_QUESTIONS=family.questions,POST_CHOLECYSTECTOMY_BILE_LEAK_CASES=family.cases,POST_CHOLECYSTECTOMY_BILE_LEAK_CASE_REVIEWS=family.caseReviews,POST_CHOLECYSTECTOMY_BILE_LEAK_TIMING_ENTRIES=family.timingEntries;
export const POST_CHOLECYSTECTOMY_BILE_LEAK_AUTHORING_REVIEW=NEEDS_REVIEW;
export const POST_CHOLECYSTECTOMY_BILE_LEAK_SERVICE_CONTRACTS=[{serviceId:"service.hepatobiliary_contrast_mrcp",allowedRouteIds:["route.hepatobiliary_contrast_mrcp.outsourced"],delivery:"new_external_contract_required" as const}];
