import {readFile,mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
const base='tools/room-design/waiting-layout',html=await readFile(`${base}/waiting-layout.html`,'utf8');
await mkdir(`${base}/evidence`,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:900,height:900}});
await page.setContent(`<main>${html}</main>`);await page.waitForFunction(()=>window.__waitingLayout?.ready());
await page.screenshot({path:`${base}/evidence/waiting-default.png`,fullPage:true});
await page.getByLabel('Show footprints and provisional clearance').check();
await page.screenshot({path:`${base}/evidence/waiting-behind-bench.png`,fullPage:true});
await page.locator('#waiting-route').selectOption('chairs');await page.locator('#waiting-progress').fill('18');
await page.screenshot({path:`${base}/evidence/waiting-behind-left-chair.png`,fullPage:true});
await page.locator('#waiting-progress').fill('82');
await page.screenshot({path:`${base}/evidence/waiting-behind-right-chair.png`,fullPage:true});
await page.locator('#waiting-progress').fill('28');await page.screenshot({path:`${base}/evidence/waiting-around-chair.png`,fullPage:true});
await page.locator('#waiting-orientation').selectOption('90');await page.locator('#waiting-progress').fill('48');
await page.screenshot({path:`${base}/evidence/waiting-west.png`,fullPage:true});
await page.getByLabel('Show footprints and provisional clearance').uncheck();await page.screenshot({path:`${base}/evidence/waiting-west-clean.png`,fullPage:true});
await page.locator('#waiting-orientation').selectOption('0');await page.getByLabel('Show footprints and provisional clearance').uncheck();
for(const id of ['N2','WA','EA'])await page.locator(`button.btn[data-segment="${id}"]`).click();
await page.getByLabel('N2',{exact:true}).check();
await page.screenshot({path:`${base}/evidence/waiting-doors-neighbor.png`,fullPage:true});
await browser.close();
