import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { buildStandingGeometry, buildWalkGeometry } from '../../canonical-master/canonical-geometry.mjs';
import { V8_CALIBRATION } from '../green-rig-v8.mjs';
import { DIRECTIONAL_CALIBRATION } from '../directional/directional-rig-v1.mjs';
import { GREEN_ACTION_RIG_V1, greenStarJumpPose } from '../actions/green-action-rig-v1.mjs';
import { LAYER_ORDER } from '../../standard-atlas/schema-v1.mjs';
import { rigidBoneTransform, transformPoint } from '../../standard-atlas/rigid-geometry.mjs';
import { createStandardCharacterRenderer, drawStandardSlot, standardStarJumpArmTarget, standardWalkArmProjection } from '../../standard-atlas/standard-character-renderer.mjs';
import { drawStandardLowerLeg, loadStandardLowerParts } from './lower-render-v2.mjs';

export const VIEWS=Object.freeze(['south','east','west','north']);
export const RIG_V2=Object.freeze({canvas:{width:160,height:320,axisX:80,floorY:287},neckY:{south:121,east:118,west:119,north:107},headNeckOffsetX:{south:0,east:8,west:0,north:0},torsoHemY:210,armLengths:{upper:36,forearm:29},armLengthsByView:{south:{upper:42,forearm:29},east:{upper:46,forearm:29},west:{upper:46,forearm:29}},bendSign:{south:{left:-1,right:1},east:{left:1,right:1},west:{left:-1,right:-1},north:{left:1,right:-1}},armMotion:{profileBackwardScale:.70,restWristReach:64,restWristReachByView:{south:70,east:74,west:74},handTargetOffset:{south:{left:5,right:-5},north:{left:-5,right:5}},frontReachRatio:.997,frontSwingYScale:.85,frontProjectionMinScale:.83,southSwingXScale:V8_CALIBRATION.projectionScale.x*.4,southSwingYScale:V8_CALIBRATION.projectionScale.y,northSwingXScale:.85,directionalSwingYScale:.84,outward:{south:{left:3,right:-3},east:{left:0,right:0},west:{left:0,right:0},north:{left:-2,right:2}}}});
export const ACTION_PROFILE=Object.freeze({bodyDrop:16,seatY:236,floorY:287,seatedScale:{south:.43,east:.42,west:.42,north:.43},seatedOffsetX:{south:0,east:7,west:-7,north:0},seatedWrist:{south:{left:{x:96,y:202},right:{x:64,y:202}},east:{left:{x:95,y:202},right:{x:97,y:202}},west:{left:{x:63,y:202},right:{x:65,y:202}},north:{left:{x:62,y:200},right:{x:98,y:200}}},clipboard:{board:{x:56,y:137,width:44,height:34},contacts:{left:{x:100,y:171},right:{x:79,y:171}}}});
const standing=Object.fromEntries(VIEWS.map(v=>[v,buildStandingGeometry(v)])),walking=buildWalkGeometry();
function mapped(view,g){const map=p=>view==='south'?{x:80+(p.x-112)*V8_CALIBRATION.projectionScale.x,y:287-(296-p.y)*V8_CALIBRATION.projectionScale.y}:{x:80+(p.x-112)*(view==='north'?32/26:1),y:287-(296-p.y)*((287-DIRECTIONAL_CALIBRATION.target.hipY)/96)};return{hipCenter:map(g.hipCenter),joints:Object.fromEntries(['left','right'].map(s=>[s,Object.fromEntries(['hip','knee','ankle','soleContact','shoulder','wrist'].map(k=>[k,map(g.joints[s][k])]))]))};}
function bounds(canvas){const d=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let l=160,t=320,r=-1,b=-1;for(let i=0;i<d.length;i+=4)if(d[i+3]>=24){const p=i/4,x=p%160,y=Math.floor(p/160);l=Math.min(l,x);t=Math.min(t,y);r=Math.max(r,x);b=Math.max(b,y);}return{left:l,top:t,right:r,bottom:b,width:r-l+1,height:b-t+1};}
function part(loaded,id){const p=loaded.manifest.parts[id];if(!p)throw new Error(`missing standardized slot ${id}`);return p;}
export async function loadRigV2(repo){const root='tools/character-mapping/layered-pilot/gray-overshirt-v2',manifest=JSON.parse(readFileSync(resolve(repo,root,'manifest-v2.json'),'utf8')),[upper,lower,identity,actions,clipboard]=await Promise.all(['upper','lower','identity','actions','clipboard'].map(k=>loadImage(resolve(repo,root,manifest.pages[k].file)))),loaded={manifest,upper,lower,identity,actions,clipboard,root,files:{manifest:`${root}/manifest-v2.json`,original:manifest.sourceLineage.original.path}};loaded.standardLower=loadStandardLowerParts(lower,manifest.parts);loaded.renderer=createStandardCharacterRenderer({profile:RIG_V2,partRecord:id=>part(loaded,id),hasPart:id=>Boolean(manifest.parts[id]),pageImage:id=>id.startsWith('identity.')?identity:upper});return loaded;}
export function poseV2(view,index=0){const n=((index%8)+8)%8,id=String(n+1).padStart(2,'0');return{view,index:n,phaseId:id,geometry:walking[view][id]};}
export function standingPoseV2(view){return{view,index:null,phaseId:'stand',geometry:standing[view]};}
export function renderV2(loaded,pose){const {view,geometry}=pose,m=mapped(view,geometry),sm=mapped(view,standing[view]),bob=Math.round(m.hipCenter.y-sm.hipCenter.y),near=view==='east'?'right':view==='west'?'left':null,far=near?(near==='left'?'right':'left'):null,torsoInfo=loaded.renderer.torsoPose(view,bob),armProjection=Object.fromEntries(['left','right'].map(side=>[side,standardWalkArmProjection({view,side,geometry,standingGeometry:standing[view],shoulder:torsoInfo.shoulders[side],profile:RIG_V2})])),armTargets=Object.fromEntries(['left','right'].map(side=>[side,armProjection[side].target])),armOverrides=Object.fromEntries(['left','right'].map(side=>[side,armProjection[side].projectedLengths?{armLengths:armProjection[side].projectedLengths}:{}]));const rendered=loaded.renderer.render({view,bob,armTargets,armOverrides,drawLower:context=>{const legs={};for(const side of near?[far,near]:['left','right'])legs[side]=drawStandardLowerLeg(context,{lower:loaded.standardLower},view,side,m.joints[side]);return legs;}});return{canvas:rendered.canvas,metadata:{view,index:pose.index,phaseId:pose.phaseId,bob,mappedGeometry:m,legs:rendered.metadata.lower,arms:rendered.metadata.arms,armProjection,torso:rendered.metadata.torso,head:rendered.metadata.head,near,far,layerOrder:rendered.metadata.layerOrder,bounds:rendered.metadata.bounds}};}

function mapActionPoint(p){return{x:80+(p.x-GREEN_ACTION_RIG_V1.sourceActionFrame.axisX)*V8_CALIBRATION.projectionScale.x,y:287-(GREEN_ACTION_RIG_V1.sourceActionFrame.floorY-p.y)*V8_CALIBRATION.projectionScale.y};}
function actionLegJoints(j){const soleY=(j.heel.y+j.toe.y)/2;return{hip:mapActionPoint(j.hip),knee:mapActionPoint(j.knee),ankle:mapActionPoint(j.ankle),soleContact:mapActionPoint({x:j.ankle.x,y:soleY})};}
export function starJumpPoseV2(index){return greenStarJumpPose(index);}
export function renderStarJumpV2(loaded,pose){if(pose.phaseId==='08'){const ready=renderV2(loaded,standingPoseV2('south'));return{canvas:ready.canvas,metadata:{...ready.metadata,action:'starJump',stage:pose.stage,exactStandingEndpoint:true}};}const bob=pose.bodyBob,torso=loaded.renderer.torsoPose('south',bob),straightArms=Object.fromEntries(['left','right'].map(side=>[side,standardStarJumpArmTarget({shoulder:torso.shoulders[side],side,stage:pose.stage,profile:RIG_V2})])),armTargets=Object.fromEntries(['left','right'].map(side=>[side,straightArms[side].target])),armOverrides=Object.fromEntries(['left','right'].map(side=>[side,{straight:true,armLengths:straightArms[side].armLengths}])),joints=Object.fromEntries(['left','right'].map(side=>[side,actionLegJoints(pose.geometry.joints[side])])),rendered=loaded.renderer.render({view:'south',bob,armTargets,armOverrides,drawLower:context=>Object.fromEntries(['left','right'].map(side=>[side,drawStandardLowerLeg(context,{lower:loaded.standardLower},'south',side,joints[side])]))});return{canvas:rendered.canvas,metadata:{...rendered.metadata,action:'starJump',phaseId:pose.phaseId,index:pose.index,stage:pose.stage,bodyBob:bob,exactStandingEndpoint:false}};}

function seatedLowerMatrix(loaded,view){const id=`actions.${view}.seatedLower`,record=part(loaded,id),source=record.source.crop,pack=record.normalization,scale=ACTION_PROFILE.seatedScale[view],destX=80-source.width*scale/2+ACTION_PROFILE.seatedOffsetX[view],destY=288-source.height*scale,k=scale/pack.scale,desired={x:destX-source.x*scale,y:destY-source.y*scale},matrix={a:k,b:0,c:0,d:k,e:desired.x-k*pack.translation.x,f:desired.y-k*pack.translation.y};return{id,matrix,waist:transformPoint(matrix,record.landmarks.seat.waist),seatContact:transformPoint(matrix,record.landmarks.seat.contact),soles:{left:transformPoint(matrix,record.landmarks.sole.left),right:transformPoint(matrix,record.landmarks.sole.right)}};}
export function renderSeatedV2(loaded,view){const bob=ACTION_PROFILE.bodyDrop,lower=seatedLowerMatrix(loaded,view),rendered=loaded.renderer.render({view,bob,armTargets:ACTION_PROFILE.seatedWrist[view],layerOrder:LAYER_ORDER[`seated${view[0].toUpperCase()}${view.slice(1)}`],drawLower:context=>{drawStandardSlot(context,loaded.actions,lower.id,lower.matrix);return lower;}});return{canvas:rendered.canvas,metadata:{...rendered.metadata,action:'sit',view,bodyDrop:bob,waistY:lower.waist.y,seatY:ACTION_PROFILE.seatY,floorY:ACTION_PROFILE.floorY}};}

function drawClipboardBoard(context,b){context.fillStyle='#4a3524';context.fillRect(b.x-2,b.y-2,b.width+4,b.height+4);context.fillStyle='#9b6b3d';context.fillRect(b.x,b.y,b.width,b.height);context.fillStyle='#eee4cf';context.fillRect(b.x+4,b.y+4,b.width-8,b.height-8);context.fillStyle='#5a5c5d';context.fillRect(b.x+b.width/2-6,b.y+1,12,5);}
export function renderClipboardV2(loaded){const base=renderV2(loaded,standingPoseV2('south')),canvas=createCanvas(160,320),context=canvas.getContext('2d'),torso=loaded.renderer.torsoPose('south',0),head=loaded.renderer.headPose('south',0),arms={};for(const side of ['left','right']){const id=`clipboard.${side}.clipboardArm`,record=part(loaded,id),target=ACTION_PROFILE.clipboard.contacts[side],matrix=rigidBoneTransform({sourceStart:record.landmarks.joint.shoulder,sourceEnd:record.landmarks.hand.contact,targetStart:torso.shoulders[side],targetEnd:target});arms[side]={id,matrix,shoulder:torso.shoulders[side],handContact:transformPoint(matrix,record.landmarks.hand.contact),wrist:transformPoint(matrix,record.landmarks.joint.wrist),watch:(record.accessories??[]).some(a=>a.id==='watch')};}const layers={lower(){for(const side of ['left','right'])drawStandardLowerLeg(context,{lower:loaded.standardLower},'south',side,base.metadata.mappedGeometry.joints[side]);},backHair(){},torso(){drawStandardSlot(context,loaded.upper,torso.id,torso.matrix);},head(){drawStandardSlot(context,loaded.identity,head.id,head.matrix);},prop(){drawClipboardBoard(context,ACTION_PROFILE.clipboard.board);},arms(){for(const side of ['left','right'])drawStandardSlot(context,loaded.clipboard,arms[side].id,arms[side].matrix);},frontHair(){}};for(const layer of LAYER_ORDER.clipboardSouth)layers[layer]?.();return{canvas,metadata:{action:'clipboard',view:'south',torso,head,arms,board:ACTION_PROFILE.clipboard.board,floorY:287,layerOrder:LAYER_ORDER.clipboardSouth,bounds:bounds(canvas)}};}
