import { spriteFromMatrix, type PixelSpriteAsset } from "./pixelArt";

export const PIXEL_ICONS = {
  learning: spriteFromMatrix("icon-learning", [
    "         II",
    "       IIII",
    "     III II",
    "   III  II ",
    " III   II  ",
    "IIIIIII    ",
    " I   I     ",
    " II II     ",
  ]),
  money: spriteFromMatrix("icon-money", [
    "   IIIII   ",
    "    III    ",
    "   I   I   ",
    "  I     I  ",
    " I       I ",
    " I  III  I ",
    " I I I I I ",
    " I  III  I ",
    "  I     I  ",
    "   IIIII   ",
  ]),
  satisfactionHappy: spriteFromMatrix("icon-satisfaction-happy", [
    "   IIIII   ",
    " II     II ",
    "I         I",
    "I  II II  I",
    "I         I",
    "I I     I I",
    "I  I   I  I",
    " I  III  I ",
    "  II   II  ",
    "    III    ",
  ]),
  satisfactionSteady: spriteFromMatrix("icon-satisfaction-steady", [
    "   IIIII   ",
    " II     II ",
    "I         I",
    "I  II II  I",
    "I         I",
    "I         I",
    "I  IIIII  I",
    " I       I ",
    "  II   II  ",
    "    III    ",
  ]),
  satisfactionSad: spriteFromMatrix("icon-satisfaction-sad", [
    "   IIIII   ",
    " II     II ",
    "I         I",
    "I  II II  I",
    "I         I",
    "I   III   I",
    "I  I   I  I",
    " I       I ",
    "  II   II  ",
    "    III    ",
  ]),
  time: spriteFromMatrix("icon-time", [
    "   IIIII   ",
    " II     II ",
    "I    I    I",
    "I    I    I",
    "I    I    I",
    "I    III  I",
    "I         I",
    " I       I ",
    "  II   II  ",
    "    III    ",
  ]),
  frontDesk: spriteFromMatrix("icon-front-desk", [
    "  IIIIIII  ",
    " ICCCCCCCI ",
    "ICSSSSSSSCI",
    " ICCCCCCCI ",
    " IIIIIIIII ",
    "IDDDDDDDDDI",
    "IIIIIIIIIII",
    " II     II ",
  ]),
  waiting: spriteFromMatrix("icon-waiting", [
    " III  III ",
    "IDDDIIDDDI",
    "IDOOIIDOOI",
    "IIIIIIIIII",
    " II    II ",
    " II    II ",
  ]),
  examination: spriteFromMatrix("icon-examination", [
    " IIIIIIIII ",
    "ILLLLLLLLLI",
    "ILSSSSSSSLI",
    " IIIIIIIII ",
    "   II II   ",
    "  III III  ",
  ]),
  bathroom: spriteFromMatrix("icon-bathroom", [
    "  IIIII  ",
    " IRRRRRI ",
    "  IIIII  ",
    "IIIIIIIII",
    "IRRRRRRRI",
    " IRRRRRI ",
    "  IIIII  ",
  ]),
  xray: spriteFromMatrix("icon-xray", [
    " IIIIIII ",
    "IDDDDDDI",
    " IDDDDI ",
    "   II   ",
    " IIIIII ",
    "IDCCCCDI",
    "IDCSSCDI",
    "IDCCCCDI",
    " IIIIII ",
  ]),
  imagingControl: spriteFromMatrix("icon-imaging-control", [
    " III III ",
    "ICCCICCCI",
    "ICSCICSCI",
    " III III ",
    "  IIIII  ",
    "IIIIIIIII",
    " II   II ",
  ]),
  minorProcedure: spriteFromMatrix("icon-minor-procedure", [
    "   III   ",
    "   IRI   ",
    "IIIIIRIII",
    "IRRRRRRRI",
    "IIIIIRIII",
    "   IRI   ",
    "   III   ",
  ]),
  ultrasound: spriteFromMatrix("icon-ultrasound", [
    "  IIIIIII  ",
    " ICSSSSSCI ",
    " ICSHHHSCI ",
    " ICSSSSSCI ",
    "  IIIIIII  ",
    "    III    ",
    " IIIIIIIII ",
    " II     II ",
  ]),
  ct: spriteFromMatrix("icon-ct", [
    "   IIIII   ",
    " II     II ",
    " I  III  I ",
    "I  I   I  I",
    " I  III  I ",
    " II     II ",
    "   IIIII   ",
    "  IIIIIII  ",
  ]),
  phlebotomy: spriteFromMatrix("icon-phlebotomy", [
    "   IIII    ",
    "   ISSI    ",
    "   ISSI    ",
    "   ISSI    ",
    "  IIIIII   ",
    " IIRIRRII  ",
    "  IIIIII   ",
    " II    II  ",
  ]),
  evsCloset: spriteFromMatrix("icon-evs-closet", [
    "    II     ",
    "    II     ",
    "    II     ",
    " IIIIIIIII ",
    " IDDDDDDI ",
    " IDSSSSDI ",
    " IDDDDDDI ",
    "IIIIIIIIII",
  ]),
  endoscopy: spriteFromMatrix("icon-endoscopy", [
    "  IIIIII   ",
    " ICSSSCI   ",
    " ICSHHCI   ",
    " ICSSSCI   ",
    "  IIIIII   ",
    " IIIIIIIII ",
    " IDDDDDDDI ",
    " II     II ",
  ]),
  periopRecovery: spriteFromMatrix("icon-periop-recovery", [
    " IIIIIIIIII ",
    "ILSSSSSSSLI",
    "ILLLLLLLLLI",
    " IIIIIIIIII ",
    "   II II   ",
    "  III III  ",
    "    II     ",
    "   IIII    ",
  ]),
  training: spriteFromMatrix("icon-training", [
    " IIIIIIIII ",
    "IDDDDDDDDI",
    "IDPIPIPDI",
    " IIIIIIIII ",
    "  II   II ",
    "IIIIIIIII",
    "IDDDDDDDI",
    " II     II",
  ]),
  coffeeKiosk: spriteFromMatrix("icon-coffee-kiosk", [
    "   IIII    ",
    "  ICCCCI   ",
    "  ICDDCI   ",
    "   ICCI    ",
    " IIIIIIIII ",
    "IDDDDDDDDI",
    "ICCCCCCCCI",
    " II     II ",
  ]),
  glp1Suite: spriteFromMatrix("icon-glp1-suite", [
    "  IIIIIII  ",
    " ICSSSSSCI ",
    " ICSHHHSCI ",
    " ICSSSSSCI ",
    "  IIIIIII  ",
    " IIIIIIIII ",
    "IDDDDDDDDI",
    " II     II ",
  ]),
  hallway: spriteFromMatrix("icon-hallway", [
    "IIIIIIIII",
    "IPPPPPPPI",
    "IPIPIPIPI",
    "IPPPPPPPI",
    "IPIPIPIPI",
    "IPPPPPPPI",
    "IIIIIIIII",
  ]),
  staff: spriteFromMatrix("icon-staff", [
    "   III   ",
    "  ILLLI  ",
    "  ILLLI  ",
    "   III   ",
    " IIIIIII ",
    "IDDDDDDDI",
    "IDDIRIDDI",
    " IIIIIII ",
    " II   II ",
  ]),
  alert: spriteFromMatrix("icon-alert", [
    "   III   ",
    "  IIRI   ",
    " IIRRRII ",
    "IIRRIRRII",
    "IRRRIRRRI",
    "IRRRRRRRI",
    "IRRRIRRRI",
    "IIIIIIIII",
  ]),
  folder: spriteFromMatrix("icon-folder", [
    " IIIII    ",
    "IRRRRIIII ",
    "IRRRRRRRRI",
    "IRRRRRRRRI",
    "IRRRRRRRRI",
    "IIIIIIIIII",
  ]),
  door: spriteFromMatrix("icon-door", [
    " IIIIIII ",
    "IDDDDDDI",
    "IDOOOOODI",
    "IDOOOOODI",
    "IDOOOIODI",
    "IDOOOOODI",
    "IDOOOOODI",
    "IIIIIIIII",
  ]),
} as const satisfies Record<string, PixelSpriteAsset>;

export type PixelIconName = keyof typeof PIXEL_ICONS;
