// Independently written atomic facts, not source excerpts. Each objective's
// questions link to its individual facts; source/limitation metadata is supplied
// by the corresponding objective in authoring.ts.
export const ATOMIC_FACTS:Record<string,readonly string[]>={
 "hiv-perioperative.art-continuity":["Avoid perioperative ART interruption when the prescribed regimen can be administered.","Coordinate unavoidable ART administration interruptions with an experienced HIV clinician.","Surgical antibiotics do not substitute for an effective antiretroviral regimen.","Do not make uncoordinated partial ART regimen substitutions."],
 "hiv-perioperative.booster-midazolam-interaction":["Ritonavir or cobicistat can inhibit CYP3A-mediated midazolam metabolism and increase its exposure.","Oral midazolam is contraindicated with boosted protease inhibitors.","Parenteral midazolam with boosted ART requires appropriate monitoring and individualized consideration of dose adjustment."],
 "neuromuscular-recovery.quantitative-assessment":["Clinical strength tests can miss residual neuromuscular blockade.","Subjective visible or tactile twitch assessment is less accurate than quantitative recovery measurement.","Quantitative neuromuscular monitoring should inform anesthetic recovery assessment."],
 "neuromuscular-recovery.sugammadex-selectivity":["Sugammadex complexes rocuronium and vecuronium to reduce free neuromuscular blocker.","Sugammadex selectivity for rocuronium and vecuronium must not be extrapolated to all neuromuscular blockers.","Sugammadex blockade reversal does not reverse hypnotic or opioid sedation."],
 "peristomal-skin.effluent-irritation":["Intestinal effluent leaking onto peristomal skin can cause irritant dermatitis.","Moist superficial injury that follows an observed leakage distribution supports an effluent-related irritant process.","Spreading infection, fungal-pattern findings or deep ulceration require separate evaluation rather than attribution to simple leakage irritation."],
 "peristomal-skin.restore-seal":["Inspect and correct an ill-fitting pouch when leakage causes peristomal irritant dermatitis.","Local skin cleaning, drying and appliance-compatible protection can support skin care and a reliable seal.","Ostomy-nurse involvement supports individualized care of peristomal skin injury.","Untargeted antimicrobials do not correct continuing noninfectious effluent exposure."],
 "mucocutaneous-separation.recognition":["Mucocutaneous separation is detachment between stoma mucosa and adjacent peristomal skin.","Mucocutaneous separation can involve only part of the stoma junction.","Stoma-junction separation is distinct from necrosis, whole-stoma retraction and bowel-segment prolapse."],
 "mucocutaneous-separation.superficial-care":["Small superficial mucocutaneous separation with viable bowel and no infection can receive conservative local care.","Local care of superficial separation includes protection of the wound and pouch seal with follow-up.","Deep or severe separation, infection or failed conservative care requires surgical reassessment."],
 "incidental-gallbladder.t1a-depth":["Gallbladder carcinoma invading lamina propria without muscular invasion is T1a.","Gallbladder carcinoma invading the muscular layer is T1b.","In-situ gallbladder carcinoma lacks stromal invasion."],
 "incidental-gallbladder.completely-resected-t1a":["Simple cholecystectomy may suffice after complete removal of margin-negative incidental T1a gallbladder carcinoma.","Uncertain depth, positive margins or residual gallbladder carcinoma require a different specialist assessment.","Adequacy of T1a resection does not convert invasive carcinoma into benign disease or eliminate specialist follow-up."],
 "merkel-cell.integrated-diagnosis":["Merkel cell carcinoma is a cutaneous neuroendocrine carcinoma with epithelial and neuroendocrine features.","Cytokeratin-20 is a supporting feature in integrated Merkel cell pathology assessment.","Merkel cell diagnosis requires distinguishing other small-cell neoplasms and metastatic disease rather than relying on one marker alone."],
 "merkel-cell.clinically-negative-node-staging":["Sentinel lymph node biopsy can assess occult regional disease in an appropriate clinically node-negative Merkel cell carcinoma candidate.","A normal regional-node examination does not establish pathologic node negativity.","Coordinating sentinel staging before wider excision can preserve lymphatic mapping options."],
 "incisional-hernia.retrorectus-plane":["Retrorectus mesh lies between rectus muscle and posterior rectus sheath.","Onlay mesh lies superficial to fascia.","Preperitoneal mesh lies between posterior sheath and peritoneum.","Intraperitoneal mesh lies within the peritoneal cavity."],
 "incisional-hernia.fascial-closure":["The EHS midline incisional guideline recommends fascial closure with mesh reinforcement rather than routine mesh bridging within its closable-defect scope.","The EHS guideline scope is adult midline incisional hernias expected to close without advanced myofascial release.","The fascial closure recommendation has low-certainty evidence and does not require closure irrespective of tissue tension."],
 "subtotal-cholecystectomy.safe-bailout":["Subtotal cholecystectomy is an accepted bailout when safe anatomic identification and the critical view cannot be established.","Avoid hazardous division of unidentified structures during difficult cholecystectomy.","Conversion and other safe bailout strategies remain legitimate alternatives to subtotal surgery."],
 "subtotal-cholecystectomy.remnant-classification":["Fenestrating subtotal cholecystectomy leaves the gallbladder remnant open.","Reconstituting subtotal cholecystectomy closes the gallbladder remnant.","Internal cystic-duct closure alone does not establish a closed gallbladder remnant.","Posterior-wall retention alone does not determine the fenestrating versus reconstituting subtype."],
 "laparoscopy-respiratory.co2-absorption":["CO2 used for pneumoperitoneum can be absorbed systemically.","Absorbed insufflation CO2 adds a load requiring ventilatory clearance.","Unexpected acute perioperative deterioration needs assessment rather than automatic attribution to normal insufflation physiology."],
 "laparoscopy-respiratory.diaphragm-compliance":["Pneumoperitoneum can displace the diaphragm cephalad.","Pneumoperitoneum-related mechanical restriction can reduce respiratory compliance and resting lung volume.","Lower respiratory compliance can increase the pressure needed to deliver a given tidal volume.","Head-down positioning can accentuate insufflation-related respiratory restriction."],
 "postoperative-scapula.spinal-accessory":["The spinal accessory nerve supplies trapezius.","The spinal accessory nerve is vulnerable during posterior cervical triangle surgery.","Shoulder droop with weak shrug supports trapezius-pattern postoperative localization."],
 "postoperative-scapula.long-thoracic":["The long thoracic nerve supplies serratus anterior.","Axillary surgery can injure the long thoracic nerve.","Serratus weakness can produce medial scapular winging accentuated by forward pushing.","Trapezius, latissimus and deltoid deficits represent motor localizations different from serratus weakness."],
};
