import { buildFamily, type ClaimSpec, type ConceptSpec, type SourceSpec } from "./family-builder";
import { variants, type VariantRow } from "./spec-utils";
import { SOURCES as S } from "./source-catalog";
import { ATOMIC_FACTS } from "./atomic-facts";
const factIds=(slug:string)=>ATOMIC_FACTS[slug]!.map((_,i)=>`claim.gs028g.${slug}${i===0?"":`.fact${i+1}`}`);

type Option = [label: string, rationale: string, test?: { timingProfileId: string }];
type Row = [slug: string, complaint: string, story: string, task: string, key: Option, wrong: [Option, Option, Option]];
type Objective = { slug:string; name:string; objective:string; claim:string; category:ClaimSpec["category"]; sources:SourceSpec[]; limitation:string; plannedKeyTest?:{timingProfileId:string}; rows:[Row,Row,Row,Row] };
const test = (timingProfileId:string) => ({ timingProfileId });
const V = (objective:Objective) => variants(objective.rows.map(([slug,complaint,story,stem,correct,wrong]) => ({
  slug, complaint, presentation:`{patientName}, a {patientAge}-year-old {patientSex}, ${story}`,
  stem, correct:[correct[0],correct[1]], wrong, ...(objective.plannedKeyTest?{test:objective.plannedKeyTest}:{}), claims:factIds(objective.slug),
  explanation:`The correct answer is “${correct[0]}.” ${correct[1]} ${wrong.map((item)=>item[1]).join(" ")}`,
})) as [VariantRow,VariantRow,VariantRow,VariantRow]);
function family(slug:string,label:string,objectives:[Objective,Objective],updates?:[string,string]) {
  return buildFamily({slug,label,
    concepts:objectives.map((o):ConceptSpec=>({id:`concept.gs028g.${o.slug}`,displayName:o.name,learningObjective:o.objective,
      stage:3,educationalTier:1,conceptType:o.category === "evaluation" ? "workup" : ["anatomy","definition","presentation"].includes(o.category) ? "diagnosis" : "management",
      evidenceClaimIds:factIds(o.slug),variants:V(o)})),
    claims:objectives.flatMap((o)=>ATOMIC_FACTS[o.slug]!.map((statement,i)=>({id:factIds(o.slug)[i]!,statement,category:o.category,
      sourceIds:o.sources.map((s)=>s.id),limitation:o.limitation,population:"Adult synthetic perioperative or postoperative clinic encounters; no onsite hospital operation is simulated."}))),
    sources:objectives.flatMap((o)=>o.sources),
    ...(updates?{pairing:{indices:[0,1],updates}}:{}),
  });
}

export const HIV_FAMILY = family("hiv-perioperative","Preoperative medication discussion",[
 {slug:"hiv-perioperative.art-continuity",name:"Perioperative ART continuity",objective:"Plan continued antiretroviral treatment when feasible and coordinate unavoidable interruptions with the HIV team.",category:"management",sources:[S.hiv],limitation:"One adequate current state guideline; no independent guideline was successfully retrieved. Regimen-specific restrictions and inability to take medications require individualized coordination.",
 claim:"In adults with HIV, perioperative ART interruption should be avoided when feasible; if interruption is unavoidable, coordinate with an experienced HIV clinician rather than withholding or partially substituting the regimen by default.",rows:[
 ["routine-elective","Medication planning","is planning an elective hernia repair at an outside surgical service. HIV is well controlled, and the anesthesia team confirms the prescribed ART can be taken around the procedure.","Which ART plan is appropriate when the prescribed regimen can be continued perioperatively?",["Continue ART with the perioperative team","Routine surgery alone is not an indication to stop effective ART."],[["Withhold ART during surgical recovery","Surgical recovery alone does not justify interrupting feasible ART."],["Use a single-drug ART formulary substitute","An uncoordinated single-drug substitute does not preserve the prescribed regimen."],["Continue the unboosted ART components","Uncoordinated removal of part of a regimen is not the continuity plan."]]],
 ["postoperative-orders","Medication reconciliation","brings discharge paperwork after an uncomplicated hospital operation. Oral medications are tolerated, but ART was omitted from the draft medication list without a documented reason.","What is the best response to an unexplained ART omission when oral therapy is feasible?",["Reconcile and continue the prescribed ART","An omission calls for coordinated medication reconciliation, not a routine postoperative hold."],[["Continue the postoperative ART hold","The unexplained hold should be reconciled when administration is feasible."],["Restart the first listed ART component","A partial regimen is not coordinated ART continuation."],["Restart the ward single-drug ART substitute","Uncoordinated partial substitution does not restore the prescribed regimen."]]],
 ["temporary-enteral-problem","Medication access","is discussing a planned abdominal operation. The treating hospital expects a temporary period when the usual oral regimen cannot be given, and alternative formulations have not yet been reviewed.","How should a possible unavoidable perioperative ART interruption be handled?",["Coordinate a regimen plan with the HIV team","Specialist coordination is needed when usual administration may be impossible."],[["Hold ART until swallowing returns","An anticipated interruption needs a coordinated regimen plan rather than a default hold."],["Give a readily available single ART tablet","Availability does not establish an adequate substitute for the prescribed regimen."],["Switch to the ward single-drug ART substitute","A partial substitution requires regimen-specific HIV expertise."]]],
 ["routine-fast","Preoperative questions","asks whether every medication must be stopped before an elective procedure. The anesthesia team has already confirmed how the prescribed ART can be administered under the fasting instructions.","Which medication instruction best fits confirmed feasible perioperative ART administration?",["Continue ART using the agreed instructions","Use the agreed administration plan when continuation is feasible."],[["Withhold ART during the surgical admission","A routine hold conflicts with the confirmed administration plan."],["Continue ART after removing its booster","Uncoordinated component removal changes the effective regimen."],["Resume ART after postoperative follow-up","Feasible ART administration need not wait for a follow-up visit."]]],
 ]},
 {slug:"hiv-perioperative.booster-midazolam-interaction",name:"Boosted ART and midazolam",objective:"Recognize increased midazolam exposure with ritonavir or cobicistat and coordinate route-specific sedation planning.",category:"safety_boundary",sources:[S.hiv],limitation:"One current guideline interaction table. Oral and parenteral midazolam have different restrictions; no dose or blanket prohibition of monitored IV use is taught.",
 claim:"Ritonavir- or cobicistat-boosted ART can inhibit CYP3A-mediated midazolam metabolism and increase sedation exposure; oral midazolam is contraindicated with boosted protease inhibitors, while parenteral use requires appropriate monitoring and individualized planning.",rows:[
 ["oral-premedication","Sedation planning","takes ritonavir-boosted ART. An outside preoperative order proposes oral midazolam, and the pharmacist flags the combination before it is administered.","What is the appropriate response to proposed oral midazolam with ritonavir-boosted ART?",["Revise sedation for the ART interaction","Boosted therapy can increase midazolam exposure; this oral combination requires an alternative plan."],[["Retain the planned oral midazolam order","The oral combination has a route-specific contraindication."],["Increase the proposed oral midazolam dose","Increased exposure from metabolic inhibition does not support a dose increase."],["Withhold the ART regimen for oral sedation","A coordinated alternative sedation plan is preferable to sacrificing feasible effective ART."]]],
 ["cobicistat-list","Drug interaction review","takes a cobicistat-containing regimen and is planning sedation for a hospital procedure. The anesthesia team asks why midazolam needs a specific interaction check.","Which mechanism explains the midazolam interaction with cobicistat?",["Inhibition of CYP3A-mediated metabolism","Reduced metabolism can increase midazolam exposure and prolong sedation."],[["Increased renal elimination of midazolam","The booster warning concerns metabolic inhibition rather than increased renal elimination."],["Reduced intestinal absorption of midazolam","Reduced absorption does not explain increased exposure from CYP3A inhibition."],["Induction of CYP3A-mediated metabolism","The relevant booster effect inhibits rather than induces midazolam metabolism."]]],
 ["monitored-iv","Anesthesia review","takes ritonavir-boosted ART. An anesthesiologist is considering IV midazolam in a setting with respiratory monitoring and rescue capability.","Which statement correctly distinguishes monitored IV from oral midazolam with boosted ART?",["IV use needs reviewed dosing and monitoring","Parenteral midazolam may be considered with appropriate monitoring and individualized dose review; oral restrictions should not be copied wholesale."],[["IV use can proceed under the unchanged dose plan","Changing route does not erase the need to assess increased exposure."],["Oral substitution is preferable to monitored IV use","The oral route has the contraindication; monitored parenteral use is assessed differently."],["IV use calls for withholding the ART regimen","ART interruption is not the default solution to an interaction requiring sedation planning."]]],
 ["slow-clearance","Medication explanation","reviews an outside anesthesia note warning of prolonged midazolam sedation with a boosted protease-inhibitor regimen. No sedative is being administered in this clinic visit.","What explains the warning about prolonged midazolam effects with boosted protease-inhibitor therapy?",["Reduced CYP3A clearance of midazolam","Booster-mediated metabolic inhibition can increase and prolong exposure."],[["Reduced intestinal absorption of midazolam","Reduced absorption would not explain prolonged increased midazolam exposure."],["Increased renal elimination of midazolam","Greater elimination does not explain the metabolic interaction."],["Increased hepatic metabolism of midazolam","The interaction reduces rather than increases CYP3A-mediated metabolism."]]],
 ]},
],["The medication review now identifies ritonavir-boosted ART and a proposed oral midazolam order at the outside surgical service.","The reconciled medication list includes cobicistat. The anesthesia team now asks about its interaction with midazolam."]);

export const RECOVERY_FAMILY = family("neuromuscular-recovery","Anesthesia recovery planning",[
 {slug:"neuromuscular-recovery.quantitative-assessment",name:"Quantitative blockade recovery assessment",objective:"Use quantitative neuromuscular monitoring rather than head lift, apparent strength or visual twitch count alone to assess recovery from blockade.",category:"evaluation",sources:[S.monitoring],limitation:"Single peer-reviewed narrative review; no numeric extubation threshold, device calibration protocol or individualized extubation decision is authored.",claim:"Clinical strength tests and subjective twitch assessment can miss residual neuromuscular blockade; quantitative monitoring provides an objective assessment of recovery and should inform anesthetic emergence decisions.",rows:[
 ["head-lift","Recovery questions","is reviewing an outside anesthetic record after a prior operation involving rocuronium. The record describes a head lift but lacks an objective recovery measurement.","Which assessment best addresses residual blockade when the record contains only a head-lift test?",["Quantitative train-of-four assessment","An objective measurement is more reliable than apparent clinical strength alone."],[["A second isolated head-lift observation","Repeating a clinical strength sign does not make it quantitative."],["Visual estimation of four equal twitches","Subjective twitch appearance can miss residual blockade."],["Bedside sustained hand-grip assessment","Clinical strength assessment can miss residual blockade."]]],
 ["four-twitches","Anesthesia paperwork","brings an outside record listing four visible twitches after vecuronium. The clinician wants to know whether that count alone proves full recovery.","Which information is more useful than a visible twitch count for judging blockade recovery?",["Quantitative train-of-four ratio","Four visible responses alone do not quantify residual fade adequately."],[["Sustained bedside head-lift assessment","A clinical strength test does not quantify residual blockade."],["Voluntary bedside hand-grip assessment","Clinical strength can appear adequate despite residual blockade."],["Qualitative assessment of twitch fade","Subjective fade assessment is less accurate than quantitative measurement."]]],
 ["future-plan","Preoperative safety review","is planning another operation after an outside note described unexpectedly weak breathing during emergence from neuromuscular blockade. The patient is stable today.","Which monitoring plan specifically improves assessment of recovery from neuromuscular blockade?",["Plan quantitative neuromuscular monitoring","Objective monitoring directly addresses residual blockade assessment; other emergence checks still remain necessary."],[["Assess sustained voluntary head lift","Clinical strength does not replace objective recovery measurement."],["Assess repeated voluntary hand-grip strength","Clinical strength can miss residual blockade."],["Assess train-of-four twitches by visual inspection","Visible twitch assessment is qualitative rather than quantitative."]]],
 ["subjective-fade","Recovery record review","asks about an anesthesia note saying that no fade was felt by hand after a relaxant. The chart contains no quantitative recovery value.","What would strengthen recovery assessment beyond tactile absence of fade?",["Quantitative neuromuscular measurement","Tactile assessment is less accurate than objective recovery measurement."],[["Repeated manual estimation of train-of-four fade","Repeating a subjective assessment does not make it a quantitative measurement."],["A sustained voluntary head-lift assessment","Clinical strength can miss residual blockade."],["A sustained voluntary hand-grip assessment","Apparent voluntary strength does not establish quantitative recovery."]]],
 ]},
 {slug:"neuromuscular-recovery.sugammadex-selectivity",name:"Sugammadex pharmacologic selectivity",objective:"Identify rocuronium and vecuronium as the blockers selectively complexed by sugammadex rather than assuming universal relaxant reversal.",category:"definition",sources:[S.sugammadex,S.monitoring],limitation:"Drug-label mechanism corroborated by a narrative review. No dose, renal-impairment policy, universal reversal strategy or administration order is taught.",claim:"Sugammadex complexes rocuronium and vecuronium to reduce free blocker at nicotinic neuromuscular receptors; its labeled selectivity does not imply reversal of every neuromuscular blocker or of hypnotic sedation.",rows:[
 ["rocuronium-record","Drug explanation","reviews a completed outside anesthesia record listing rocuronium followed by sugammadex. The patient wants to understand what the reversal drug acted on.","Which drug in this completed anesthetic record is specifically complexed by sugammadex?",["Rocuronium","Sugammadex selectively binds this steroidal neuromuscular blocker."],[["Cisatracurium","Sugammadex binding selectivity for rocuronium and vecuronium should not be extrapolated to this blocker."],["Succinylcholine","This is not one of the blockers selectively complexed by sugammadex."],["Atracurium","The labeled rocuronium and vecuronium selectivity does not establish reversal of this blocker."]]],
 ["vecuronium-plan","Anesthetic planning","is discussing an outside operation for which vecuronium is being considered. The team is reviewing why sugammadex can reverse that drug's blockade.","Which mechanism explains sugammadex reversal of vecuronium-induced blockade?",["Complex formation with circulating blocker","Binding reduces free vecuronium available at the neuromuscular junction."],[["Increased acetylcholine release at the motor nerve","Sugammadex acts through blocker binding rather than increasing transmitter release."],["Competitive displacement at nicotinic receptors","The represented mechanism is complex formation with blocker rather than receptor competition."],["Inhibition of acetylcholine breakdown at the junction","Sugammadex binding is distinct from an anticholinesterase mechanism."]]],
 ["cisatracurium-boundary","Medication reconciliation","brings a record listing cisatracurium. A copied discharge explanation says that sugammadex reverses every muscle relaxant by the same binding mechanism.","Which correction best addresses the claim that sugammadex binds every neuromuscular blocker?",["Its binding is selective for rocuronium and vecuronium","The selectivity should not be extrapolated to cisatracurium."],[["Its binding applies equally to cisatracurium and succinylcholine","The stated universal selectivity is incorrect."],["Its binding applies equally to atracurium and mivacurium","Specific binding should not be generalized to other blocker classes."],["Its binding applies equally to rocuronium and succinylcholine","Including a different blocker makes this claimed selectivity incorrect."]]],
 ["still-sedated","Recovery counselling","reviews an outside note stating that rocuronium blockade was reversed with sugammadex while propofol sedation was still being allowed to wear off.","Why can hypnotic sedation persist after sugammadex reverses rocuronium blockade?",["Blocker binding leaves propofol sedation","Neuromuscular reversal and emergence from hypnosis are different processes."],[["Sugammadex accelerates propofol elimination","Blocker complex formation does not establish accelerated hypnotic clearance."],["Sugammadex directly binds circulating propofol","The represented binding targets are neuromuscular blockers, not propofol."],["Sugammadex antagonizes propofol at its receptor","Blocker binding is not direct reversal of hypnotic receptor effects."]]],
 ]},
],["The completed outside medication record now identifies rocuronium and sugammadex; this is a clinic explanation, not a new administration order.","The anesthesia planning note now names vecuronium. The team asks how sugammadex interacts with this blocker."]);

export const SKIN_FAMILY = family("peristomal-skin","Ostomy skin follow-up",[
 {slug:"peristomal-skin.effluent-irritation",name:"Effluent-associated irritant dermatitis",objective:"Recognize peristomal irritant injury by the leakage distribution and distinguish it from an infectious or ulcerative process.",category:"presentation",sources:[S.skin],limitation:"Single adequate open review; bedside pattern recognition is not proof against superimposed infection, allergy or other skin disease.",claim:"Leaking intestinal effluent can cause moist, painful peristomal irritant dermatitis; injury following leakage under an ill-fitting appliance supports this diagnosis, while spreading infection, fungal findings or deep ulceration require separate evaluation.",rows:[
 ["wide-opening","Burning around stoma","has an ileostomy with moist, burning erosions exactly where effluent reaches exposed skin through an oversized appliance opening. The stoma is viable, and there is no spreading redness or purulence.","Which diagnosis best explains erosions confined to the effluent-exposed peristomal skin?",["Irritant contact dermatitis","The leakage distribution and wet erosions support an effluent-related irritant process."],[["Peristomal bacterial cellulitis","Spreading erythema and other infection findings are absent in this story."],["Peristomal candidal dermatitis","No fungal-pattern findings are described; leakage explains this injury."],["Ulcerative peristomal pyoderma gangrenosum","A deep, progressive undermined ulcer is not described."]]],
 ["skin-fold-leak","Pouch leakage","reports burning beneath an ileostomy seal where a skin fold channels output. The irritated strip matches that channel, while skin elsewhere under the adhesive is intact.","Which process most directly explains the skin injury along this repeated output-leak channel?",["Effluent-related irritant dermatitis","Localized output exposure fits the observed pattern."],[["Diffuse adhesive allergic dermatitis","The injury follows effluent rather than the entire adhesive contact area."],["Progressive bacterial cellulitis","The story lacks spreading inflammation or systemic infection findings."],["Deep ulcerative pyoderma gangrenosum","A channel of superficial irritation is not a deep undermined ulcer."]]],
 ["appliance-mismatch","Sore ostomy skin","has a healthy functioning colostomy but continued leakage after using an opening much larger than the stoma. Shallow wet skin injury surrounds the exposed base without fever or an abscess.","What best explains shallow wet skin injury where stool repeatedly contacts the peristomal skin?",["Irritant injury from stool exposure","The poor seal permits output to injure unprotected skin."],[["Stoma ischemia with tissue necrosis","The stoma is described as healthy and viable."],["Bacterial abscess beneath the appliance","There is no focal collection or infection pattern described."],["Allergic injury across the entire adhesive footprint","The injury is concentrated in the exposed leakage zone."]]],
 ["leak-recurrence","Skin burning","reports recurrent ileostomy leaks and superficial raw skin beneath the leaking edge. There is no black stoma tissue, rapidly spreading redness or undermined ulcer.","Which explanation best fits recurrent leakage with superficial raw peristomal skin?",["Effluent-associated irritant dermatitis","The exposure and superficial distribution fit irritant dermatitis."],[["Full-thickness ischemic necrosis of the stoma","No nonviable stoma tissue is described."],["Rapidly spreading peristomal cellulitis","No spreading inflammatory pattern is described."],["Deep peristomal ulcerative pyoderma gangrenosum","The described superficial injury lacks that ulcer pattern."]]],
 ]},
 {slug:"peristomal-skin.restore-seal",name:"Correct the leaking ostomy seal",objective:"Address noninfectious leakage-related dermatitis with appliance fit, a compatible skin-protection plan and ostomy-nurse follow-up.",category:"management",sources:[S.skin],limitation:"Single adequate open review; exact products, convexity, skin preparations and infection treatment must be individualized by the ostomy team.",claim:"For leakage-related peristomal irritant dermatitis without infection, inspect and correct pouch fit, clean and dry the skin, use appliance-compatible protection and involve an ostomy nurse; untargeted antimicrobials do not correct ongoing effluent exposure.",rows:[
 ["resize-seal","Ostomy care plan","has leakage-related dermatitis with a viable stoma and no infection findings. Examination identifies excessive skin exposure within the pouch opening.","What is the best initial care plan for noninfectious dermatitis caused by this oversized pouch opening?",["Refit the seal with ostomy-nurse guidance","Fit correction and compatible skin protection address the continuing exposure."],[["Start systemic antibiotic treatment","Antibiotics do not correct continuing noninfectious leakage."],["Start topical antifungal treatment","A fungal pattern is not supplied, and the leaking fit remains the cause."],["Enlarge the cutout around the irritated skin","An enlarged opening exposes more skin to effluent."]]],
 ["fold-plan","Pouch fitting visit","has moist irritation along a skin-fold leak channel. The stoma remains viable and no bacterial or fungal pattern is found.","Which plan best addresses persistent irritation from a pouch leak over a skin fold?",["Review pouch fit with the ostomy nurse","An individualized seal and compatible protection target the leak source."],[["Prescribe systemic antibiotic treatment","No bacterial process is established; the leak still needs correction."],["Apply topical antifungal treatment","A fungal infection is not established, and the mechanical leak is unaddressed."],["Enlarge the pouch opening over the skin fold","More exposed skin permits continued effluent injury."]]],
 ["wet-barrier","Skin protection visit","has wet superficial peristomal erosions from an observed leak. The ostomy nurse can help select skin protection that permits reliable appliance adhesion.","Which care approach addresses both wet skin injury and continued effluent exposure?",["Restore pouch fit with compatible protection","A product plan must support, rather than undermine, a dependable seal."],[["Apply an oily barrier beneath the adhesive","An unsuitable oily preparation can interfere with a reliable pouch seal."],["Treat the erosions with systemic antibiotics","No infection is established, and medication does not correct effluent exposure."],["Remove the pouch for open-air skin care","Uncontained output can continue to contact and irritate the skin."]]],
 ["repeated-treatment","Persistent irritation","has recurrent noninfectious ostomy-skin irritation despite repeated empiric creams. The pouch still leaks at the same edge.","Which next step most directly treats the continuing cause of this irritant dermatitis?",["Reassess the appliance seal with an ostomy nurse","Source correction is needed when the leak continues."],[["Change to another systemic antibiotic course","Medication changes do not target the documented noninfectious leak."],["Change to another topical antifungal preparation","The story does not establish fungal infection as the cause."],["Continue the present pouch and skin-care routine","Persistent leakage calls for fit and skin-protection reassessment."]]],
 ]},
],["The stoma remains viable with no infection findings. The nurse identifies excessive exposed skin inside the pouch opening.","A skin fold still channels effluent beneath the seal. The nurse confirms no current bacterial or fungal pattern."]);

export const SEPARATION_FAMILY = family("mucocutaneous-separation","Stoma junction follow-up",[
 {slug:"mucocutaneous-separation.recognition",name:"Stoma mucocutaneous separation",objective:"Identify detachment at the sutured intestinal mucosa-to-skin junction rather than labeling every stoma wound as retraction or necrosis.",category:"definition",sources:[S.separation],limitation:"Mapping-review definition; depth, extent and viability must be assessed separately before management.",claim:"Mucocutaneous separation is a partial or circumferential detachment between stoma mucosa and peristomal skin at their junction; it is distinct from nonviable stoma tissue, prolapse or a stoma positioned below skin level.",rows:[
 ["small-gap","Stoma edge gap","returns after hospital stoma creation with a visible gap where bowel mucosa was sutured to skin. The stoma is pink, above skin level and functioning.","Which complication names detachment at the mucosa-to-skin suture junction?",["Mucocutaneous separation","The defining finding is detachment at the intestinal mucosa-to-skin junction."],[["Ischemic stoma necrosis","The stoma is viable rather than nonviable."],["Retraction below the skin","The stoma is above skin level."],["Prolapse of the bowel segment","No elongated protruding bowel segment is described."]]],
 ["junction-review","Stoma wound review","has a functioning, viable stoma. Part of the previously joined bowel edge has detached from the adjacent skin, leaving a visible junctional wound.","What is the correct name for partial detachment of the stoma edge from adjacent skin?",["Mucocutaneous separation","The wound is at the stoma mucosa-to-skin attachment."],[["Parastomal hernia formation","A fascial hernia is not a mucosa-to-skin gap."],["Ischemic stoma necrosis","No nonviable stoma tissue is described."],["Full bowel-segment prolapse","The finding is detachment, not bowel telescoping outward."]]],
 ["pouch-off","Stoma inspection","notices drainage near a new stoma. With the pouch removed, the clinician sees a gap between viable bowel mucosa and the skin at the former sutures, without a bulge or an elongated segment.","Which observed stoma complication explains the gap at the former mucosa-to-skin sutures?",["Mucocutaneous separation","Direct inspection identifies junctional detachment."],[["Parastomal fascial herniation","A fascial bulge is not the finding described."],["Bowel-segment stoma prolapse","No elongated bowel segment is described."],["Necrosis of the stoma mucosa","The mucosa is viable."]]],
 ["seam-question","Stoma seam concern","describes the stoma as 'coming away from its seam.' Examination confirms a segment of detachment at the mucosa-to-skin interface while the stoma itself remains pink and raised.","Which diagnosis best describes this detachment at the stoma's skin interface?",["Mucocutaneous separation","The junction has separated without the described findings of necrosis or retraction."],[["Retraction of the whole stoma","Whole-stoma sinking below skin level is not described."],["Ischemic destruction of the stoma","Pink viable tissue does not match this finding."],["Prolapse through the abdominal wall","The stoma has not elongated outward."]]],
 ]},
 {slug:"mucocutaneous-separation.superficial-care",name:"Care of limited superficial stoma separation",objective:"Choose local ostomy care and close follow-up for small superficial separation with viable bowel, while reserving surgical escalation for complicated separation.",category:"management",sources:[S.separation],limitation:"Single adequate mapping review with limited comparative evidence. Only small superficial separation without ischemia, deep contamination or infection is tested; no fixed healing interval is promised.",claim:"Small superficial mucocutaneous separation with viable stoma tissue and no infection can be managed with appropriate local wound care, absorbent or barrier support, pouch-seal protection and follow-up; deep or severe separation, infection or failed conservative care requires surgical reassessment.",rows:[
 ["superficial-gap","Stoma care planning","has a small superficial mucocutaneous separation. The surgical team confirms viable bowel, no deeper cavity, no abscess and a working pouch seal.","Which initial plan fits a small superficial stoma separation without ischemia or infection?",["Local ostomy care with close follow-up","Conservative local care is reasonable within these explicitly limited findings."],[["Arrange operative revision of the stoma","The small superficial viable separation supports an initial local-care plan."],["Continue the current routine pouch care","The new separation needs individualized wound protection and reassessment."],["Start systemic antimicrobial treatment","Infection is not established and antimicrobials do not replace local wound care."]]],
 ["viable-junction","Wound care discussion","has a short superficial gap at the stoma junction. The rest of the attachment is intact, output is controlled and the surgeon finds no deep contamination.","What is the appropriate initial response to this limited viable superficial junctional wound?",["Arrange local care and ostomy follow-up","Protecting the wound and seal with reassessment is appropriate in this limited case."],[["Arrange hospital stoma revision","Immediate revision is not the initial plan for the represented limited viable separation."],["Continue the previous routine pouch-care plan","New junctional separation warrants wound-specific care and reassessment."],["Start an empiric systemic antibiotic course","No infection is established, and local wound and pouch care are needed."]]],
 ["seal-protection","Stoma wound check","has a small superficial separation already reviewed by the surgeon. Viability is preserved, there is no abscess, and the patient needs help protecting the wound while maintaining the pouch seal.","Which plan best supports healing of this uncomplicated superficial separation?",["Individualized wound and pouch care","Local wound protection and follow-up target the actual problem."],[["Refer for operative stoma reconstruction","The supplied small viable superficial defect permits initial conservative care."],["Use open-air wound care after pouch removal","Loss of output containment does not protect the wound or surrounding skin."],["Continue the existing routine pouch-care plan","The wound needs individualized care and follow-up rather than unchanged routine care."]]],
 ["limited-stable","Stoma follow-up","has a small shallow separation with viable tissue and no fever, purulence or deeper cavity. The patient is stable and can attend ostomy-nurse and surgical follow-up.","What initial disposition fits this stable, small superficial separation with reliable follow-up?",["Conservative local care with reassessment","The limited findings support monitored local care; new deep or infectious findings would change disposition."],[["Immediate operative stoma revision","The represented limited superficial separation does not demand initial reoperation."],["Routine pouch care without wound reassessment","Viability does not eliminate the need to assess and care for the junctional wound."],["Empiric systemic antimicrobial treatment","No infectious process is established; medication does not replace local care."]]],
 ]},
],["The surgeon has now assessed the junctional gap as small and superficial, with viable bowel, no deeper cavity or abscess and a working seal.","Additional inspection confirms a limited shallow separation, controlled output and no deep contamination; local follow-up is available."]);

export const INCIDENTAL_GB_FAMILY = family("incidental-gallbladder","Gallbladder pathology discussion",[
 {slug:"incidental-gallbladder.t1a-depth",name:"Gallbladder lamina-propria invasion",objective:"Identify gallbladder carcinoma confined to the lamina propria as T1a, distinguishing muscular invasion from in-situ disease.",category:"definition",sources:[S.gbStage,S.gbManagement],limitation:"Only the local pathologic T category is assigned; node status, metastasis and full stage grouping are not inferred from wall depth alone.",claim:"Gallbladder carcinoma invading the lamina propria but not the muscular layer is T1a; muscular-layer invasion is T1b, whereas in-situ disease lacks invasion.",rows:[
 ["lamina-only","Pathology questions","brings completed cholecystectomy pathology showing a small invasive adenocarcinoma limited to the lamina propria. The muscular layer is uninvolved.","Which pathologic T category fits invasive gallbladder carcinoma confined to the lamina propria?",["T1a disease","Lamina-propria invasion without muscular invasion defines T1a."],[["Tis disease","In-situ disease does not invade the lamina propria."],["T1b disease","T1b requires muscular-layer invasion."],["T2 disease","T2 requires a deeper extent than the invasion described."]]],
 ["deeper-sections","Report clarification","has a gallbladder pathology addendum confirming invasion through the epithelial basement membrane into lamina propria, with no muscle involvement on reviewed sections.","What is the correct T category after invasive lamina-propria involvement is confirmed without muscle invasion?",["T1a disease","Invasion is present but remains superficial to the muscular layer."],[["Tis disease","Crossing into lamina propria excludes in-situ classification."],["T1b disease","Muscular-layer involvement is explicitly absent."],["T3 disease","The report does not describe serosal perforation or adjacent-organ invasion."]]],
 ["not-in-situ","Pathology explanation","asks why an incidental gallbladder carcinoma is called invasive despite being shallow. The reviewed specimen shows lamina-propria involvement and an intact uninvolved muscular layer.","Which T category describes this shallow but invasive gallbladder carcinoma?",["T1a disease","Shallow invasion into lamina propria is still invasive T1a disease."],[["Tis disease","Shallow invasion is not the same as no invasion."],["T1b disease","There is no muscular-layer invasion."],["T2 disease","Perimuscular connective-tissue invasion is not described."]]],
 ["wall-layer-review","Cancer report review","brings a completed report that places incidental gallbladder cancer in the lamina propria, with neither muscular nor perimuscular connective-tissue invasion.","Which local T category follows from these specific gallbladder wall-layer findings?",["T1a disease","The stated depth is lamina propria only."],[["T1b disease","Muscular-layer invasion is absent."],["T2 disease","Perimuscular connective-tissue invasion is absent."],["T3 disease","No serosal or adjacent-organ involvement is described."]]],
 ]},
 {slug:"incidental-gallbladder.completely-resected-t1a",name:"Completely resected incidental T1a gallbladder cancer",objective:"Avoid automatic radical re-resection after expert confirmation of completely removed margin-negative T1a gallbladder carcinoma.",category:"management",sources:[S.gbManagement,S.gbCross],limitation:"Older specialist guideline cross-checked against 2025 society guidance. This applies only to confirmed completely resected T1a disease; uncertain depth, positive margins, residual disease and T1b or deeper disease need a different specialist plan.",claim:"After specialist pathology review confirms completely resected margin-negative incidental T1a gallbladder carcinoma without residual disease, simple cholecystectomy may be sufficient and radical re-resection is not automatically indicated.",rows:[
 ["confirmed-resection","Cancer follow-up planning","has specialist-confirmed incidental T1a gallbladder carcinoma completely removed by simple cholecystectomy, with negative margins and no evidence of residual disease.","Which surgical plan fits completely resected margin-negative incidental T1a gallbladder cancer?",["Accept the cholecystectomy with specialist follow-up","These constrained findings do not automatically require radical re-resection."],[["Refer for radical gallbladder re-resection","Confirmed completely resected margin-negative T1a disease does not automatically need radical re-resection."],["Refer for extrahepatic bile-duct resection","Routine bile-duct removal is not required by this completely resected T1a profile."],["Return to routine follow-up without specialist review","Adequacy of the operation does not make invasive carcinoma benign or eliminate specialist follow-up."]]],
 ["margin-addendum","Pathology follow-up","has an incidental T1a gallbladder cancer report. Expert review now confirms uninvolved margins, complete removal and no residual disease.","What should these confirmed complete-resection findings change about the surgical discussion?",["Further radical surgery is not automatic","Simple cholecystectomy may be sufficient for this specifically confirmed T1a case."],[["Completion liver resection is required","The verified completely resected T1a profile does not establish a need for completion radical surgery."],["Completion extrahepatic duct resection is required","Routine duct resection is not supported by this profile."],["Routine follow-up can replace cancer-team review","Sufficient resection still calls for specialist cancer follow-up."]]],
 ["patient-choice-review","Second opinion visit","has a specialist-reviewed, completely excised margin-negative T1a gallbladder carcinoma. A copied note recommends radical surgery solely because any invasion was found.","Which response best corrects a blanket radical-surgery recommendation for this confirmed T1a case?",["Arrange specialist follow-up after resection","Expert review of complete margin-negative T1a removal may support no further radical operation."],[["Arrange completion liver and nodal re-resection","Invasion confined to lamina propria with complete negative-margin removal does not automatically require radical re-resection."],["Arrange completion extrahepatic bile-duct resection","The verified margin-negative T1a profile does not supply a routine duct-resection indication."],["Continue routine follow-up without cancer-team review","The finding remains invasive carcinoma even when cholecystectomy is sufficient."]]],
 ["muscle-not-involved","Surgical planning review","has a complete specialist-reviewed gallbladder specimen with T1a carcinoma, negative margins and no residual disease. The patient asks whether the muscular layer's lack of invasion matters for further surgery.","What is the appropriate surgical implication of these fully confirmed T1a findings?",["Simple cholecystectomy may be sufficient","The recommendation is narrowly tied to completely removed T1a disease."],[["Completion liver and nodal resection is required","The verified T1a depth and complete resection do not automatically require completion radical surgery."],["Completion extrahepatic bile-duct excision is required","This fully resected T1a profile does not establish routine duct removal."],["Negative margins permit routine noncancer follow-up","A sufficient resection does not make invasive cancer benign or eliminate specialist follow-up."]]],
 ]},
],["Specialist pathology review now confirms T1a carcinoma, negative margins and complete removal; there is no evidence of residual disease.","The addendum confirms margin-negative, completely removed T1a disease without residual tumor. The visit now turns to the need for further surgery."]);

export const MERKEL_FAMILY = family("merkel-cell","Skin tumor report review",[
 {slug:"merkel-cell.integrated-diagnosis",name:"Cutaneous neuroendocrine carcinoma recognition",objective:"Recognize Merkel cell carcinoma from an integrated cutaneous neuroendocrine pathology assessment rather than assuming every skin nodule is squamous cancer.",category:"presentation",sources:[S.merkel],limitation:"Single current PDQ evidence summary. The diagnosis requires an integrated pathology panel and exclusion of mimics; cytokeratin-20 alone is not treated as diagnostic.",claim:"Merkel cell carcinoma is a cutaneous neuroendocrine carcinoma with epithelial and neuroendocrine features; cytokeratin-20 supports an integrated diagnosis, but pathology must distinguish other small-cell tumors and metastatic disease.",rows:[
 ["skin-panel","Skin pathology questions","brings completed pathology from a growing forearm skin nodule. It shows a dermal small-cell malignancy with epithelial and neuroendocrine differentiation and cytokeratin-20 expression; the integrated workup excludes melanoma, lymphoma and a metastatic pulmonary primary.","Which diagnosis best fits this integrated primary cutaneous neuroendocrine pathology assessment?",["Merkel cell carcinoma","The integrated cutaneous neuroendocrine assessment supports Merkel cell carcinoma rather than a single-stain diagnosis."],[["Cutaneous squamous cell carcinoma","The report describes neuroendocrine small-cell differentiation, not a squamous pattern."],["Primary cutaneous malignant melanoma","The integrated workup excludes melanocytic differentiation."],["Primary cutaneous lymphoid lymphoma","The integrated workup excludes a lymphoid origin."]]],
 ["outside-biopsy","Nodule report review","has a completed upper-arm biopsy showing malignant small cells with epithelial and neuroendocrine differentiation. A specialist panel supports a primary skin origin and cytokeratin-20 expression, with the principal metastatic and lymphoid mimics excluded.","What is the most likely diagnosis after this integrated cutaneous small-cell tumor workup?",["Merkel cell carcinoma","A primary cutaneous neuroendocrine carcinoma with this integrated assessment fits Merkel cell carcinoma."],[["Metastatic pulmonary small-cell carcinoma","The specialist workup does not support a pulmonary primary."],["Primary cutaneous malignant melanoma","The provided integrated phenotype is not melanocytic."],["Primary cutaneous lymphoid lymphoma","The phenotype is epithelial and neuroendocrine rather than lymphoid."]]],
 ["red-nodule","Biopsy explanation","brings pathology from a red thigh nodule. The report describes an epithelial neuroendocrine small-cell carcinoma centered in skin, with supportive cytokeratin-20 and an integrated panel excluding the main noncutaneous mimics.","Which malignant diagnosis best explains this primary skin epithelial-neuroendocrine tumor?",["Merkel cell carcinoma","The diagnosis rests on the integrated primary cutaneous neuroendocrine phenotype."],[["Conventional basal cell carcinoma","The report does not describe conventional basal cell differentiation."],["Conventional squamous cell carcinoma","The integrated report describes neuroendocrine rather than conventional squamous differentiation."],["Primary cutaneous lymphoid lymphoma","An epithelial neuroendocrine phenotype does not fit lymphoma."]]],
 ["not-single-stain","Pathology second opinion","has a skin-biopsy report with small malignant cells and cytokeratin-20 expression. Specialist review also confirms neuroendocrine and epithelial differentiation and excludes the main metastatic, melanocytic and lymphoid alternatives.","Which diagnosis is supported by the full reviewed phenotype rather than cytokeratin-20 alone?",["Merkel cell carcinoma","Multiple integrated findings support a primary cutaneous neuroendocrine carcinoma."],[["Primary cutaneous malignant melanoma","The reviewed panel excludes the melanocytic alternative."],["Metastatic pulmonary small-cell carcinoma","The integrated assessment excludes this metastatic alternative."],["Primary cutaneous lymphoid lymphoma","The reviewed epithelial-neuroendocrine phenotype excludes this lymphoid alternative."]]],
 ]},
 {slug:"merkel-cell.clinically-negative-node-staging",name:"Merkel sentinel-node staging",objective:"Refer an appropriate clinically node-negative Merkel cell carcinoma candidate for sentinel-node staging rather than equating a normal node examination with pathologic node negativity.",category:"management",sources:[S.merkel],plannedKeyTest:test("timing.test.biopsy"),limitation:"Single current PDQ summary; specialist candidacy, tumor location and mapping limitations require individualized planning. No node-positivity rate, treatment regimen or universal completion-dissection rule is taught.",claim:"For an appropriate Merkel cell carcinoma staging candidate with no clinically detectable nodal disease, sentinel lymph node biopsy can assess occult regional involvement; a normal node examination does not establish pathologic node negativity, and specialist coordination before wider excision helps preserve mapping options.",rows:[
 ["node-negative-exam","Cancer staging discussion","has specialist-confirmed Merkel cell carcinoma of the forearm, no clinically detectable regional nodes and no wider excision yet. The cancer team considers the patient an appropriate surgical staging candidate.","Which regional staging plan is appropriate for this clinically node-negative Merkel cell carcinoma candidate?",["Specialist sentinel lymph node staging","Sentinel-node assessment addresses occult regional disease that examination cannot exclude."],[["Use clinical node examination as final staging","Normal examination does not establish pathologic node negativity."],["Proceed directly to local excision alone","The clinically negative candidate still needs consideration of occult regional disease."],["Refer for complete regional-node dissection","Sentinel staging assesses occult disease without automatically committing to full basin dissection."]]],
 ["before-wide-excision","Treatment planning visit","has confirmed upper-arm Merkel cell carcinoma and a normal regional-node examination. The specialist team is planning local treatment and has not yet performed wider excision.","Which coordination step best preserves regional staging options before wider excision for Merkel cell carcinoma?",["Coordinate specialist sentinel-node staging","Early coordination can preserve mapping while assessing occult regional disease."],[["Use the clinical node examination as final staging","Clinical node negativity is not pathologic node negativity."],["Defer regional staging until after wider excision","Coordinating sentinel mapping before wider excision can preserve staging options."],["Arrange complete regional-node dissection","A clinically negative candidate is considered for sentinel staging rather than automatic complete dissection."]]],
 ["normal-exam-boundary","Nodal staging questions","has confirmed Merkel cell carcinoma and no palpable regional adenopathy. The patient asks whether this means a node procedure is unnecessary; the specialist considers sentinel staging feasible.","How should regional nodes be assessed in this appropriate clinically node-negative Merkel staging candidate?",["Arrange specialist sentinel-node assessment","Occult regional involvement can exist despite a normal examination."],[["Assign final nodal stage from clinical examination","A normal physical examination cannot establish pathologic N0."],["Proceed with local excision and routine observation","Absence of palpable symptomatic nodes does not exclude occult regional disease."],["Arrange complete regional-node dissection","Full basin dissection is not the default staging plan for this clinically negative candidate."]]],
 ["mapping-counselling","Cancer care coordination","has a confirmed cutaneous Merkel tumor, a clinically negative regional basin and no prior wide excision. The specialist team is deciding the regional staging approach.","Which initial regional staging approach addresses microscopic disease without automatic full-basin dissection?",["Specialist sentinel lymph node staging","Sentinel staging can evaluate occult disease in a suitable clinically negative basin."],[["Local excision followed by routine nodal observation","A clinically negative examination does not replace consideration of sentinel staging."],["Complete regional lymph-node dissection","Automatic full dissection is not the represented initial staging plan."],["Final nodal staging from the clinical examination","Naming the primary tumor does not establish pathologic regional-node status."]]],
 ]},
],["The specialist now confirms Merkel cell carcinoma. Regional nodes are clinically negative, wider excision has not been performed and sentinel staging is considered feasible.","The cancer team confirms Merkel cell carcinoma and a clinically negative regional basin. Local treatment is being planned before wider excision."]);

export const HERNIA_FAMILY = family("incisional-hernia","Hernia repair planning",[
 {slug:"incisional-hernia.retrorectus-plane",name:"Retrorectus mesh plane",objective:"Identify the retrorectus mesh plane between rectus muscle and posterior rectus sheath in midline incisional hernia planning.",category:"anatomy",sources:[S.hernia],limitation:"Anatomic nomenclature from one current society guideline; broader retromuscular terminology also includes the preperitoneal plane. No universal superiority of one operative approach is taught.",claim:"Retrorectus mesh lies between rectus muscle and posterior rectus sheath; onlay is superficial to fascia, preperitoneal is between posterior sheath and peritoneum, and intraperitoneal placement is within the peritoneal cavity.",rows:[
 ["behind-rectus","Mesh plan questions","reviews an outside elective midline incisional hernia plan placing mesh behind rectus muscle but in front of the posterior rectus sheath.","Which mesh plane is described by placement between rectus muscle and posterior rectus sheath?",["Retrorectus mesh placement","The named boundaries identify the retrorectus space."],[["Subcutaneous onlay mesh placement","Onlay is superficial to the fascial layer."],["Intraperitoneal onlay mesh placement","Intraperitoneal placement is inside the peritoneal cavity."],["Preperitoneal mesh placement","Preperitoneal placement lies deeper than the posterior sheath."]]],
 ["posterior-sheath","Hernia technique review","brings a planned repair note describing mesh anterior to an intact posterior rectus sheath and posterior to the rectus muscle belly.","What is the correct name for this mesh plane anterior to posterior sheath and posterior to rectus?",["Retrorectus mesh placement","Mesh between these structures is retrorectus."],[["Intraperitoneal mesh placement","This would put mesh within the peritoneal cavity."],["Superficial fascial onlay placement","This is superficial to fascia, rather than behind rectus."],["Preperitoneal mesh placement","That plane is between posterior sheath and peritoneum."]]],
 ["compartment-review","Operative report questions","is reviewing a completed midline hernia operation. The report says mesh occupies the compartment between rectus muscle and posterior sheath, with the peritoneal cavity remaining deeper.","Which anatomic mesh compartment was used in this completed hernia repair?",["The retrorectus compartment","The compartment is directly behind rectus and in front of posterior sheath."],[["The subcutaneous onlay compartment","The report is not describing a superficial fascial onlay."],["The intraperitoneal compartment","The mesh is not described inside the peritoneal cavity."],["The preperitoneal compartment","That compartment lies deeper than the posterior sheath."]]],
 ["not-preperitoneal","Repair explanation","asks whether all mesh behind the rectus muscle is preperitoneal. The plan specifically places the mesh in front of the posterior sheath.","Which term most precisely describes mesh behind rectus but anterior to the posterior sheath?",["Retrorectus placement","The posterior-sheath boundary distinguishes retrorectus from the deeper preperitoneal plane."],[["Preperitoneal placement","This would be between posterior sheath and peritoneum."],["Intraperitoneal placement","This would be inside the peritoneal cavity."],["Superficial fascial onlay placement","Onlay would be superficial to the fascia."]]],
 ]},
 {slug:"incisional-hernia.fascial-closure",name:"Fascial closure rather than mesh bridging",objective:"Plan fascial-defect closure with mesh reinforcement in an elective midline incisional hernia expected to close without advanced release, rather than routine bridging.",category:"management",sources:[S.hernia],limitation:"One adequate current guideline; strong recommendation based on low-certainty evidence. Limited to adult midline defects expected to close without advanced release; no forceful closure or guarantee of lower recurrence is taught.",claim:"For adult elective midline incisional hernia repair within the EHS guideline's closable-defect scope, close the fascial defect and reinforce with mesh rather than routinely bridging an unclosed defect; feasibility and tissue tension still require operative judgment.",rows:[
 ["closable-defect","Repair plan discussion","has an elective midline incisional hernia. The specialist expects the fascial edges to close without advanced release or undue tension and plans mesh reinforcement.","Which fascial plan best fits an elective midline defect expected to close without advanced release?",["Close the defect and reinforce with mesh","This fits the guideline's limited closable-defect scope."],[["Bridge the open fascial defect with mesh","The guideline recommends closure with mesh reinforcement when closure is feasible in its stated scope."],["Use primary sutured fascial closure without mesh","The recommended plan includes mesh reinforcement rather than primary sutures alone."],["Use primary fascial closure under high tension","The closable-defect recommendation does not justify excessive tissue tension."]]],
 ["repair-comparison","Hernia planning visit","reviews two proposed elective midline repair plans. The surgeon confirms that the fascia can close without advanced release; one plan would still leave it open beneath mesh.","Which plan is preferred for the stated midline defect that can be closed without advanced release?",["Fascial closure with mesh reinforcement","Closing the defect follows the guideline's reconstruction principle."],[["Mesh bridging across an open fascial defect","Feasible closure with reinforcement is preferred within the guideline scope."],["Primary sutured fascial repair without mesh","The guideline-supported plan includes reinforcement rather than sutures alone."],["Primary fascial closure under high tension","The recommendation does not call for excessive tension."]]],
 ["function-discussion","Abdominal wall questions","has a closable elective midline incisional defect. The specialist discusses restoration of the abdominal wall and separate mesh reinforcement.","Which structural repair goal fits this closable midline incisional hernia?",["Close the fascia and reinforce with mesh","The proposed closable-defect plan restores the fascia and adds reinforcement."],[["Bridge the open fascial defect with mesh","Routine bridging does not follow the stated closable-defect recommendation."],["Use primary fascial sutures without mesh reinforcement","The recommended approach includes mesh reinforcement."],["Use primary fascial closure under high tension","Feasibility and tissue tension remain operative considerations."]]],
 ["scope-limited","Elective repair counselling","has an adult midline incisional hernia whose fascial edges are expected to close without advanced myofascial release. There is no contaminated field or emergency operation in this plan.","Which defect-management approach fits the current guideline's stated closable elective scope?",["Close fascia and add planned mesh reinforcement","The recommendation applies within these expressly stated limits."],[["Bridge the open fascial defect with mesh","This closable defect supports fascia restoration with reinforcement."],["Use primary fascial sutures without mesh reinforcement","The recommendation includes mesh rather than sutures alone."],["Use primary fascial closure under high tension","The guideline scope does not justify excessive-tension closure."]]],
 ]},
],["The specialist also confirms that this elective midline fascial defect should close without advanced release or undue tension; mesh reinforcement is planned.","The surgeon now compares fascial closure with leaving an open gap beneath mesh. Closure is expected to be feasible without advanced release."]);

export const SUBTOTAL_FAMILY = family("subtotal-cholecystectomy","Difficult gallbladder report review",[
 {slug:"subtotal-cholecystectomy.safe-bailout",name:"Subtotal bailout in unsafe anatomy",objective:"Recognize subtotal cholecystectomy as a safe bailout option when the critical view cannot be obtained rather than dividing unidentified structures.",category:"safety_boundary",sources:[S.bailout,S.subtotal],limitation:"Guideline plus independent review; subtotal is an accepted option, not the only safe strategy. Conversion or stopping may also be appropriate and are not used as wrong options.",claim:"When inflammation prevents safe anatomic identification and the critical view of safety cannot be obtained, subtotal cholecystectomy is an accepted bailout that avoids hazardous division of unidentified structures; other safe bailout strategies remain legitimate.",rows:[
 ["unsafe-triangle","Operation explanation","reviews an outside cholecystectomy report describing dense inflammation and inability to identify the cystic structures safely. The surgeon chose a bailout rather than persist in the unsafe triangle.","Which operative choice is an accepted bailout when the critical view cannot be established safely?",["Use subtotal cholecystectomy as a bailout","Subtotal surgery can avoid dangerous dissection of unidentified structures."],[["Clip and divide the presumed cystic duct","Presumed identity is insufficient when the critical view cannot be obtained."],["Continue total cholecystectomy dissection","Unsafe anatomic identification calls for a bailout rather than hazardous further dissection."],["Divide the two visible biliary structures","Seeing two structures does not establish the critical view."]]],
 ["frozen-anatomy","Surgical report review","brings a hospital gallbladder report describing a scarred, inflamed triangle where safe ductal anatomy could not be established. The patient asks why the surgeon did not force a total removal.","Which rationale supports subtotal bailout in this documented unsafe-anatomy setting?",["Prioritize safe anatomic identification","Avoiding hazardous division is the purpose of this bailout."],[["Use the infundibular appearance to identify the duct","A presumed appearance is not safe identification in the represented difficult anatomy."],["Prioritize removal of all gallbladder tissue","Complete removal should not override safe identification."],["Use two visible structures to establish duct identity","Two visible structures alone do not establish the critical view."]]],
 ["not-completeness","Follow-up discussion","is stable after an outside difficult cholecystectomy. The report describes marked inflammatory distortion and inability to establish the critical view before a subtotal procedure.","What best explains choosing subtotal surgery instead of forcing total removal when anatomy remains unsafe?",["A safety bailout for uncertain ductal anatomy","An accepted bailout prioritizes safe dissection over forced completeness."],[["Identification by a ductlike operative appearance","A ductlike appearance is not adequate identification in uncertain anatomy."],["Completion based on removal of all gallbladder tissue","The bailout prioritizes safety rather than complete removal at anatomic risk."],["Identification based on two visible structures","Structure count alone does not establish the critical view."]]],
 ["bailout-option","Outside operation review","reviews a difficult hospital operation in which inflammation obscured reliable cystic-duct and artery identification. The team documented that subtotal removal was technically feasible.","Which documented option is appropriate when subtotal removal is feasible but safe total-dissection anatomy is not?",["Choose a subtotal safety bailout","This is an accepted way to avoid hazardous dissection in the constrained scenario."],[["Clip and divide the presumed cystic duct","Presumed identity does not establish safe anatomy."],["Clip and divide the two visible structures","Structure count does not substitute for the critical view."],["Continue total cholecystectomy dissection","Hazardous further dissection is not appropriate when safe anatomy cannot be obtained."]]],
 ]},
 {slug:"subtotal-cholecystectomy.remnant-classification",name:"Subtotal remnant classification",objective:"Classify subtotal cholecystectomy as fenestrating or reconstituting according to whether the remaining gallbladder is left open or closed.",category:"definition",sources:[S.subtotal],limitation:"Single adequate review for nomenclature. Posterior-wall retention and internal cystic-duct closure do not alone determine the remnant classification; no universal outcome superiority is taught.",claim:"A fenestrating subtotal cholecystectomy leaves the remaining gallbladder open, whereas a reconstituting subtotal closes the remnant; retaining the posterior wall or closing the cystic duct internally does not by itself establish a closed gallbladder remnant.",rows:[
 ["open-remnant","Operative details","brings a completed subtotal gallbladder report. The surgeon removed the accessible wall and stones but left the remaining gallbladder open rather than closing it into a pouch.","Which subtotal classification applies when the remaining gallbladder is left open?",["Fenestrating subtotal surgery","An open remnant defines fenestrating subtotal surgery."],[["Reconstituting subtotal surgery","Reconstituting surgery closes the remnant."],["Standard total cholecystectomy","A gallbladder remnant is still present."],["Tube-only cholecystostomy drainage","The report describes subtotal resection rather than tube drainage alone."]]],
 ["closed-pouch","Operative classification","reviews a completed subtotal operation in which the remaining gallbladder wall was sutured into a closed pouch after stones were removed.","Which subtotal classification applies to a closed remaining gallbladder pouch?",["Reconstituting subtotal surgery","Closing the remnant defines reconstituting surgery."],[["Fenestrating subtotal surgery","Fenestrating surgery leaves the remnant open."],["Standard total cholecystectomy","Total removal would not leave this pouch."],["Tube-only cholecystostomy drainage","Subtotal resection and closure are not tube drainage alone."]]],
 ["duct-closed-remnant-open","Report clarification","brings a subtotal report in which the cystic-duct opening was closed internally but the remaining gallbladder itself was left open. The patient asks which detail determines the subtype.","Which subtype describes a subtotal operation with an open remnant despite internal cystic-duct closure?",["Fenestrating subtotal surgery","The gallbladder remnant remains open; duct closure alone does not reconstitute it."],[["Reconstituting subtotal surgery","Internal duct closure does not establish a closed remnant pouch."],["Standard total cholecystectomy","The operation left gallbladder tissue behind."],["Tube-only cholecystostomy drainage","The report describes a subtotal resection, not drainage alone."]]],
 ["posterior-wall-retained","Surgical terminology","has a subtotal report noting retention of the posterior wall and sutured closure of the remaining gallbladder. The patient assumed leaving the posterior wall automatically meant the open type.","Which subtype follows from a closed remnant even though the posterior wall was retained?",["Reconstituting subtotal surgery","Remnant closure, rather than posterior-wall retention, determines this classification."],[["Fenestrating subtotal surgery","Posterior-wall retention does not override a closed remnant."],["Standard total cholecystectomy","Gallbladder tissue remains after subtotal surgery."],["Tube-only cholecystostomy drainage","A closed subtotal remnant is not tube drainage alone."]]],
 ]},
],["The completed operative details now specify that the remaining gallbladder was left open after accessible wall and stone removal.","The report now describes the remaining gallbladder wall sutured into a closed pouch after stone removal."]);

export const LAPAROSCOPY_FAMILY = family("laparoscopy-respiratory","Laparoscopic anesthesia discussion",[
 {slug:"laparoscopy-respiratory.co2-absorption",name:"Insufflation CO2 absorption",objective:"Explain a documented gradual CO2 rise during uncomplicated pneumoperitoneum by systemic absorption of insufflated gas rather than assuming an unrelated acute catastrophe.",category:"definition",sources:[S.respiratory],limitation:"One adequate current physiology review; only a completed, evaluated anesthetic course is used. Unexplained acute deterioration still requires immediate assessment rather than attribution to normal physiology.",claim:"CO2 used for pneumoperitoneum can be absorbed systemically and increase the ventilatory CO2 load; adequate assessment and ventilation are required, and this mechanism alone does not explain every perioperative CO2 change.",rows:[
 ["gradual-rise","Anesthesia note questions","reviews a completed outside laparoscopy record showing a gradual CO2 rise during insufflation. The anesthesiologist documented patent equipment, stable circulation and no acute complication, and adjusted ventilation.","Which mechanism plausibly explains the documented gradual CO2 rise during otherwise evaluated uncomplicated insufflation?",["Systemic absorption of insufflated CO2","Insufflated gas adds to the CO2 load that ventilation must clear."],[["Circuit rebreathing of exhaled CO2","The completed course includes a functioning assessed circuit rather than rebreathing."],["Increased metabolic CO2 from hyperthermia","The course is described as evaluated and uncomplicated rather than a hyperthermic metabolic event."],["Reduced alveolar ventilation from tube obstruction","The documented course excludes a new airway obstruction."]]],
 ["ventilation-load","Preoperative physiology questions","asks about an outside anesthetic explanation that ventilation requirements can rise after abdominal CO2 insufflation even when the breathing circuit is functioning normally. The explanation concerns an otherwise evaluated uncomplicated course without hyperthermia or airway obstruction.","What physiologic process adds a CO2 load during laparoscopic insufflation?",["Absorption of CO2 from the insufflated cavity","Systemic absorption increases the gas load requiring ventilatory clearance."],[["Circuit rebreathing of exhaled CO2","The completed course includes a functioning assessed circuit rather than rebreathing."],["Increased metabolic CO2 from hyperthermia","The course is described as evaluated and uncomplicated rather than a hyperthermic metabolic event."],["Reduced alveolar ventilation from tube obstruction","The documented course excludes a new airway obstruction."]]],
 ["not-circuit-proof","Recovery explanation","brings a completed laparoscopy anesthesia record documenting additional ventilation during CO2 insufflation. The team assessed the circuit and found it functioning, with no acute deterioration.","Which explanation can account for an increased ventilation need despite a functioning circuit during CO2 insufflation?",["An added systemic load of absorbed CO2","A working circuit does not remove the source of additional absorbed gas."],[["Circuit rebreathing of exhaled CO2","The completed course includes a functioning assessed circuit rather than rebreathing."],["Increased metabolic CO2 from hyperthermia","The course is described as evaluated and uncomplicated rather than a hyperthermic metabolic event."],["Reduced alveolar ventilation from tube obstruction","The documented course excludes a new airway obstruction."]]],
 ["completed-course","Operation record discussion","is stable at follow-up after laparoscopy. A completed anesthesia summary attributes an evaluated gradual CO2 rise during insufflation to absorbed gas, with no airway or circulatory emergency.","Which source of CO2 load supports the anesthesiologist's explanation of this completed uncomplicated course?",["Absorption of the insufflation gas","The insufflated CO2 can enter the systemic circulation."],[["Circuit rebreathing of exhaled CO2","The completed course includes a functioning assessed circuit rather than rebreathing."],["Increased metabolic CO2 from hyperthermia","The course is described as evaluated and uncomplicated rather than a hyperthermic metabolic event."],["Reduced alveolar ventilation from tube obstruction","The documented course excludes a new airway obstruction."]]],
 ]},
 {slug:"laparoscopy-respiratory.diaphragm-compliance",name:"Pneumoperitoneum and respiratory compliance",objective:"Relate increased airway pressure during evaluated pneumoperitoneum to cephalad diaphragm displacement and reduced respiratory compliance.",category:"definition",sources:[S.respiratory],limitation:"Single current physiology review; no exact pressure threshold, fixed ventilator setting or automatic diagnosis for sudden airway-pressure elevation is authored.",claim:"Pneumoperitoneum can displace the diaphragm cephalad and reduce respiratory compliance and functional lung volume, increasing the pressure required to deliver a given tidal volume; positioning may accentuate these effects.",rows:[
 ["same-volume","Ventilation explanation","reviews a completed laparoscopy record. During insufflation the pressure needed for the same tidal volume rose; the anesthesiologist assessed the airway and documented mechanical restriction from the abdomen rather than a new airway obstruction.","Which mechanical effect explains a greater pressure requirement for the same tidal volume during evaluated pneumoperitoneum?",["Cephalad diaphragm shift with lower compliance","Abdominal insufflation can restrict respiratory expansion."],[["Caudal diaphragm shift with greater compliance","That is the opposite of the described restrictive effect."],["Increased lung volume with unchanged chest mechanics","The pressure-volume change reflects altered mechanics."],["Increased chest compliance with easier lung expansion","Greater compliance would not explain the increased pressure requirement."]]],
 ["position-added","Anesthesia discussion","reviews an evaluated outside laparoscopic course in which head-down positioning added to the respiratory restriction from abdominal insufflation. No acute airway problem was found.","Which combined mechanical effect explains increased respiratory restriction in this evaluated course?",["Cephalad abdominal displacement limiting expansion","Position and insufflation can accentuate diaphragm-related restriction."],[["Caudal abdominal displacement enlarging resting lung volume","That does not match head-down insufflation physiology."],["Greater compliance from unrestricted diaphragm descent","The situation restricts rather than frees expansion."],["Increased resting lung volume from an empty abdomen","The abdomen is insufflated rather than decompressed."]]],
 ["reduced-compliance","Pressure record review","brings a completed anesthesia summary documenting lower respiratory compliance after pneumoperitoneum, with the breathing tube and circuit checked and no new obstructive event found.","Which effect of abdominal insufflation is consistent with the documented reduction in respiratory compliance?",["Upward diaphragm displacement restricting lungs","Mechanical compression changes respiratory expansion."],[["Downward diaphragm displacement freeing lung expansion","This would not match the restrictive physiology."],["Expansion of resting lung volume without pressure effects","The summary specifically describes reduced compliance."],["Removal of chest-wall restriction by increased abdominal pressure","Increasing abdominal pressure can impose restriction instead."]]],
 ["mechanics-not-gas-only","Follow-up questions","asks about a completed laparoscopy summary describing both CO2 absorption and increased pressure to deliver the same breath volume. The team found no acute airway complication.","Which effect explains the pressure-volume change rather than the added CO2 load itself?",["Reduced compliance from cephalad diaphragm movement","Gas absorption and restrictive mechanics are distinct consequences of insufflation."],[["Increased compliance from a caudally displaced diaphragm","The documented pressure requirement points toward restriction."],["Improved compliance from greater diaphragm excursion","The documented mechanical effect reduces rather than improves expansion and compliance."],["Expansion of lung volume without altered respiratory mechanics","The pressure-volume relation changed in this course."]]],
 ]},
],["The completed anesthetic record also describes greater pressure to deliver the same tidal volume during insufflation. Airway and circuit checks found no new obstruction; the team documented abdominal mechanical restriction.","The completed outside record adds head-down positioning with increased respiratory restriction. The team assessed and excluded an acute airway problem."]);

const nerveChoices=(key:"spinal"|"thoracic"):[Option,[Option,Option,Option]]=>key==="spinal"
 ? [["Accessory nerve","This nerve supplies trapezius; the postoperative weak-shrug and drooping-shoulder pattern fits its injury."],[["Long thoracic nerve","Serratus-related medial winging with forward pushing is a different motor pattern."],["Thoracodorsal nerve","Latissimus dysfunction does not explain the specified trapezius pattern."],["Axillary nerve","A deltoid-focused deficit does not explain the specified trapezius pattern."]]]
 : [["Long thoracic nerve","This nerve supplies serratus anterior; the forward-push medial-winging pattern fits its injury."],[["Accessory nerve","Trapezius injury typically emphasizes weak shrug and shoulder droop rather than this serratus pattern."],["Thoracodorsal nerve","Latissimus dysfunction does not explain the specified serratus pattern."],["Axillary nerve","A deltoid-focused deficit does not explain medial winging on forward pushing."]]];
const [spinal,spinalWrong]=nerveChoices("spinal");
const [thoracic,thoracicWrong]=nerveChoices("thoracic");
export const SCAPULAR_FAMILY = family("postoperative-scapula","Postoperative shoulder assessment",[
 {slug:"postoperative-scapula.spinal-accessory",name:"Postoperative spinal accessory localization",objective:"Localize weak shoulder shrug and trapezius-pattern shoulder droop after posterior-triangle neck surgery to spinal accessory injury.",category:"anatomy",sources:[S.scapula],limitation:"One older review used for stable anatomy and localization only; physical signs suggest a lesion but do not replace a complete neurologic assessment or establish nerve transection.",claim:"The spinal accessory nerve supplies trapezius and is vulnerable during posterior cervical triangle surgery; postoperative shoulder droop and weak shrug support trapezius-pattern localization, distinct from serratus-anterior medial winging caused by long thoracic injury.",rows:[
 ["node-biopsy","Weak shoulder shrug","reports shoulder droop and weak shrug after an outside posterior-triangle cervical node biopsy. Examination localizes weakness to trapezius rather than deltoid or forward pushing.","Which nerve injury best localizes this postoperative trapezius-pattern weak shrug and shoulder droop?",spinal,spinalWrong],
 ["neck-dissection","Shoulder droop","returns after outside posterior-triangle neck surgery with a lower resting shoulder and difficulty shrugging against resistance. Forward pushing does not produce the dominant medial-winging pattern.","Which nerve supplies the muscle pattern responsible for this postoperative weak shrug and drooping shoulder?",spinal,spinalWrong],
 ["trapezius-exam","Postoperative shoulder weakness","has new shoulder symptoms after cervical node removal. Focused examination identifies trapezius weakness, while serratus anterior forward-push function is preserved.","Which nerve is most consistent with postoperative trapezius weakness and preserved serratus forward-push function?",spinal,spinalWrong],
 ["scar-location","Shoulder function review","has a posterior-triangle neck surgical scar, ipsilateral shoulder droop and weak resisted shrug. The elbow and hand motor examination is preserved.","Which nerve should be considered for this neck-surgery-related trapezius motor pattern?",spinal,spinalWrong],
 ]},
 {slug:"postoperative-scapula.long-thoracic",name:"Postoperative long thoracic localization",objective:"Localize medial scapular winging on forward pushing after axillary surgery to the long thoracic nerve and serratus anterior.",category:"anatomy",sources:[S.scapula],limitation:"One older review used for stable anatomy and localization only; no operative repair deadline or recovery probability is taught. A full postoperative neurologic assessment is still needed.",claim:"The long thoracic nerve supplies serratus anterior and is vulnerable during axillary surgery; serratus weakness can cause medial scapular winging accentuated by forward pushing. Trapezius, latissimus and deltoid deficits represent different motor localizations.",rows:[
 ["wall-push","Scapular winging","has new medial scapular winging after outside axillary node surgery. The medial border becomes prominent during a wall push, while shoulder shrug is preserved.","Which nerve injury best explains postoperative medial winging accentuated by a wall push with preserved shrug?",thoracic,thoracicWrong],
 ["forward-push","Postoperative back prominence","reports an abnormal shoulder-blade prominence after axillary surgery. Examination shows weakness of serratus anterior during forward pushing without a trapezius shrug deficit.","Which nerve supplies the weak serratus anterior in this postoperative forward-push winging pattern?",thoracic,thoracicWrong],
 ["medial-border","Shoulder blade questions","returns after axillary surgery with medial-border winging that becomes clearer during resisted forward arm elevation. Deltoid strength and shoulder shrug remain intact.","Which nerve best localizes the medial-winging motor pattern after axillary surgery?",thoracic,thoracicWrong],
 ["serratus-localization","Postoperative arm function","has a stable postoperative shoulder deficit after axillary node dissection. The examiner identifies serratus anterior weakness and medial scapular winging during forward pushing.","Which nerve lesion is most consistent with this serratus anterior deficit after axillary surgery?",thoracic,thoracicWrong],
 ]},
]);

export const LEVEL3_FAMILIES=[HIV_FAMILY,RECOVERY_FAMILY,SKIN_FAMILY,SEPARATION_FAMILY,INCIDENTAL_GB_FAMILY,MERKEL_FAMILY,HERNIA_FAMILY,SUBTOTAL_FAMILY,LAPAROSCOPY_FAMILY,SCAPULAR_FAMILY] as const;
