import { claim, concept, createDevelopmentFamily, linkSourcesToClaims, NEEDS_REVIEW, source, type CaseSpec } from "./batch-helpers";

const HERNIASURGE = "source.sc.herniasurge-2018";
const NIDDK = "source.sc.niddk-inguinal-hernia";

export const INGUINAL_HERNIA_CLAIMS = [
  claim({ id: "claim.inguinal-hernia.equivocal-exam-ultrasound", statement: "For a stable patient with intermittent groin symptoms and an equivocal examination, targeted dynamic groin ultrasound is a selected next study to clarify possible inguinal hernia anatomy.", sourceIds: [HERNIASURGE, NIDDK], evidenceCategory: "evaluation", certainty: "moderate", limitation: "Obvious hernias do not require routine imaging; ultrasound is operator-dependent, and a nondiagnostic study can require context-specific further imaging. NIDDK cites HerniaSurge, so it is not independent underlying trial evidence.", applicablePopulation: "Stable outpatients with activity-related groin symptoms, equivocal examination, and no incarceration, obstruction, or strangulation features.", lastCheckedOn: "2026-09-10" }),
  claim({ id: "claim.inguinal-hernia.symptomatic-elective-repair", statement: "For a patient with a confirmed reducible inguinal hernia and meaningful activity-limiting symptoms, elective repair discussion and planning are appropriate.", sourceIds: [HERNIASURGE, NIDDK], evidenceCategory: "management", certainty: "moderate", limitation: "This does not select a repair technique, mesh, or timing protocol, and does not treat watchful waiting as the default for the symptomatic profiles used here. NIDDK cites HerniaSurge as underlying evidence.", applicablePopulation: "Stable adults with confirmed reducible inguinal hernia and authored symptomatic activity limitation.", lastCheckedOn: "2026-09-10" }),
];

export const INGUINAL_HERNIA_SOURCES = linkSourcesToClaims([
  source({ id: HERNIASURGE, title: "International guidelines for groin hernia management", completeCitation: "The HerniaSurge Group. International guidelines for groin hernia management. Hernia. 2018;22(1):1-165. Published 2018-01-12. doi:10.1007/s10029-017-1668-x. PMID:29330835.", organizationOrJournal: "Hernia / HerniaSurge Group", authors: ["The HerniaSurge Group"], publicationYear: 2018, doi: "10.1007/s10029-017-1668-x", pmid: "29330835", officialUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5809582/", accessedOn: "2026-09-10", sourceClass: "peer_reviewed_guideline", licenseLabel: "Creative Commons Attribution-NonCommercial 4.0 International", reuseStatus: "cc_by_nc_4_0_restricted", reuseNotes: "Original factual synthesis only for local noncommercial development. Attribute the source and CC BY-NC 4.0 license at https://creativecommons.org/licenses/by-nc/4.0/; no source prose, figures, tables, or other third-party material is reproduced. Commercial reuse requires separate review.", authorityAssessment: "International society evidence-based guideline directly checked for exam-first selected imaging, uncertainty around occult imaging, and symptomatic groin-hernia management. It does not establish a universal ultrasound algorithm.", usageRole: "evidence" }),
  source({ id: NIDDK, title: "Inguinal Hernia", completeCitation: "National Institute of Diabetes and Digestive and Kidney Diseases. Inguinal Hernia. Last reviewed September 2019. Accessed 2026-09-10.", organizationOrJournal: "National Institute of Diabetes and Digestive and Kidney Diseases", authors: ["National Institute of Diabetes and Digestive and Kidney Diseases", "Neal E. Seymour, MD (acknowledged reviewer)"], publicationYear: 2019, doi: null, pmid: null, officialUrl: "https://www.niddk.nih.gov/health-information/digestive-diseases/inguinal-hernia", accessedOn: "2026-09-10", sourceClass: "government_guidance", licenseLabel: "United States government factual material; NIDDK reuse conditions apply", reuseStatus: "public_domain_conditions_apply", reuseNotes: "Original factual synthesis only. Third-party content, images, and agency marks are excluded; credit NIDDK without implying endorsement.", authorityAssessment: "Directly checked NIDDK patient education cross-checking selected imaging after an unclear examination, elective repair, and watchful waiting limited to men with few or no symptoms. It cites HerniaSurge, so it is not independent underlying evidence.", usageRole: "cross_check" }),
], INGUINAL_HERNIA_CLAIMS);

const labels = ["HerniaSurge international groin-hernia guideline (2018), CC BY-NC 4.0", "NIDDK inguinal hernia guidance (reviewed September 2019)"];
const ultrasoundChoices = (n: number) => [
  { id: `dynamic_ultrasound_${n}`, label: "Dynamic groin ultrasound", isCorrect: true, serviceId: "service.ultrasound", rationale: "The examination is equivocal and experienced dynamic ultrasound is available." },
  { id: `immediate_repair_${n}`, label: "Pelvic magnetic resonance imaging", rationale: "MRI can follow an unresolved examination and ultrasound evaluation." },
  { id: `routine_xray_${n}`, label: "Lower-extremity venous duplex", rationale: "Venous duplex does not clarify suspected groin-hernia anatomy." },
  { id: `observe_only_${n}`, label: "Plain abdominal and pelvic radiographs", rationale: "Plain radiography does not clarify suspected groin-hernia anatomy." },
] as const;
const repairChoices = (n: number) => [
  { id: `elective_discussion_${n}`, label: "Elective hernia repair consultation", isCorrect: true, rationale: "The returned study confirms a reducible inguinal hernia with meaningful symptoms." },
  { id: `routine_observation_${n}`, label: "Observation with activity modification", rationale: "This patient has meaningful activity limitation rather than minimal symptoms." },
  { id: `emergency_operation_${n}`, label: "Emergency exploration of the groin", rationale: "The patient is stable and the returned study identifies a reducible hernia without emergency features." },
  { id: `activity_only_${n}`, label: "Physical therapy for presumed groin strain", rationale: "The confirmed hernia is limiting usual work or exercise and merits an elective discussion." },
] as const;

const stories = [
  ["lifting-bulge", 44, "I get a groin bulge while lifting.", "reports an intermittent groin bulge and discomfort with lifting, but the bulge is absent during today’s examination. The groin and femoral regions are assessed, and experienced dynamic groin ultrasound is available; there is no vomiting, obstipation, persistent severe pain, or nonreducible mass.", "Which initial study best fits {patientName}'s equivocal examination?", "Dynamic groin ultrasound confirms a reducible inguinal hernia. The patient reports that the symptoms limit lifting at work."],
  ["running-discomfort", 35, "I get groin pressure when I run.", "describes recurring groin pressure during running and a fleeting bulge that cannot be reproduced in clinic. Groin and femoral assessment is equivocal, and experienced dynamic groin ultrasound is available; the patient denies obstruction symptoms, escalating pain, or an irreducible lump.", "What is the appropriate initial study for {patientName}'s groin symptoms?", "Targeted dynamic ultrasound demonstrates a reducible inguinal hernia, and the symptoms now prevent usual exercise."],
  ["caregiving-strain", 59, "My caregiving tasks trigger groin pain.", "notes an intermittent groin bulge while assisting a family member, although today’s groin and femoral-region examination is equivocal. Experienced dynamic groin ultrasound is available, and there are no features of incarceration or bowel obstruction.", "Which initial diagnostic study should be selected for {patientName} now?", "Dynamic ultrasound confirms inguinal anatomy with a reducible hernia. The recurring discomfort limits caregiving tasks."],
  ["standing-shift", 51, "My long shifts bring on a groin bulge.", "has activity-related groin discomfort and a bulge late in long work shifts, but no visible mass is present at the visit. Groin and femoral assessment is equivocal, and experienced dynamic groin ultrasound is available; the patient denies vomiting, abdominal distension, severe constant pain, or an irreducible bulge.", "What is the most useful initial study for {patientName}'s symptoms?", "A dynamic groin ultrasound confirms a reducible inguinal hernia; symptoms interfere with completing work shifts."],
] as const;

const cases: CaseSpec[] = stories.map(([slug, age, complaint, story, stem, result], index) => ({
  id: `case.inguinal-hernia.${slug}`, displayName: "Equivocal symptomatic groin presentation", chiefComplaint: complaint,
  presentation: `{patientName} ${story}`, ageYears: [age, age + 3, age + 6, age + 9], sexLabels: ["Male"], stage: 1,
  nodes: [
    { conceptId: "concept.inguinal-hernia.equivocal-exam-ultrasound", stem, choices: [...ultrasoundChoices(index + 1)], explanation: "For intermittent groin symptoms with an equivocal examination, targeted dynamic ultrasound can clarify the anatomy. A clear clinical hernia does not routinely require imaging, and a nondiagnostic study may need further assessment.", claimIds: ["claim.inguinal-hernia.equivocal-exam-ultrasound"], gate: { id: `gate.inguinal-hernia.ultrasound.${index + 1}`, serviceId: "service.ultrasound", pendingLabel: "Dynamic groin ultrasound pending", resultNarrative: result, routeIds: ["route.ultrasound.outsourced", "route.ultrasound.in_house"] } },
    { conceptId: "concept.inguinal-hernia.symptomatic-elective-repair", currentUpdate: result, stem: "After {patientName}'s ultrasound confirms a reducible hernia limiting usual activities, what is the appropriate next plan?", choices: [...repairChoices(index + 1)], explanation: "A reducible inguinal hernia causing meaningful activity limitation supports elective repair discussion and planning. The stable presentation does not require emergency treatment or a specific technique selection.", claimIds: ["claim.inguinal-hernia.symptomatic-elective-repair"] },
  ],
}));

export const INGUINAL_HERNIA_CONCEPTS = [
  concept({ id: "concept.inguinal-hernia.equivocal-exam-ultrasound", educationalTier: 0, displayName: "Dynamic ultrasound after an equivocal inguinal-hernia examination", learningObjective: "Select targeted dynamic groin ultrasound for the scoped stable patient with intermittent symptoms and an equivocal examination.", earliestFacilityStage: 1, conceptType: "workup", evidenceClaimIds: ["claim.inguinal-hernia.equivocal-exam-ultrasound"] }),
  concept({ id: "concept.inguinal-hernia.symptomatic-elective-repair", educationalTier: 1, displayName: "Elective planning for symptomatic inguinal hernia", learningObjective: "Recommend elective repair discussion and planning after a reducible inguinal hernia is confirmed in a patient with meaningful activity-limiting symptoms.", earliestFacilityStage: 1, conceptType: "management", evidenceClaimIds: ["claim.inguinal-hernia.symptomatic-elective-repair"] }),
];
const family = createDevelopmentFamily({ concepts: INGUINAL_HERNIA_CONCEPTS, cases, sourceLabels: labels });
export const INGUINAL_HERNIA_TESTED_CONCEPTS = family.testedConcepts;
export const INGUINAL_HERNIA_QUESTIONS = family.questions;
export const INGUINAL_HERNIA_CASES = family.cases;
export const INGUINAL_HERNIA_CASE_REVIEWS = family.caseReviews;
export const INGUINAL_HERNIA_AUTHORING_REVIEW = NEEDS_REVIEW;
export const INGUINAL_HERNIA_SERVICE_CONTRACTS = [{ serviceId: "service.ultrasound", allowedRouteIds: ["route.ultrasound.outsourced", "route.ultrasound.in_house"], delivery: "existing_balance_contract" as const }];
