import { claim, concept, createDevelopmentFamily, linkSourcesToClaims, NEEDS_REVIEW, source, type CaseSpec } from "./batch-helpers";

const NIDDK = "source.sc.niddk-primary-hyperparathyroidism";
const AAES = "source.sc.aaes-phpt-treatment";

export const PRIMARY_HYPERPARATHYROIDISM_CLAIMS = [
  claim({ id: "claim.primary-hyperparathyroidism.biochemical-pattern", statement: "In the scoped stable outpatient evaluation, repeat serum calcium together with intact PTH establishes the biochemical pattern of primary hyperparathyroidism before localization planning.", sourceIds: [NIDDK], evidenceCategory: "evaluation", certainty: "moderate", limitation: "This single-source claim does not define every cause of hypercalcemia or make localization imaging diagnostic.", applicablePopulation: "Stable adults with prior hypercalcemia whose renal, vitamin-D, medication, and inherited-mimic context has already been reviewed.", lastCheckedOn: "2026-09-10" }),
  claim({ id: "claim.primary-hyperparathyroidism.renal-bone-surgery-assessment", statement: "For a patient with biochemically confirmed primary hyperparathyroidism and documented kidney-stone or fragility-fracture involvement, parathyroid surgical assessment is an appropriate planning step.", sourceIds: [NIDDK, AAES], evidenceCategory: "management", certainty: "moderate", limitation: "The accepted cross-check is undated AAES patient education rather than a newly verified formal guideline. This claim excludes asymptomatic cutoffs, surveillance intervals, drug regimens, and individualized operative-suitability decisions.", applicablePopulation: "Stable adults with confirmed primary hyperparathyroidism and an authored kidney stone or fragility fracture.", lastCheckedOn: "2026-09-10" }),
];

export const PRIMARY_HYPERPARATHYROIDISM_SOURCES = linkSourcesToClaims([
  source({ id: NIDDK, title: "Primary Hyperparathyroidism", completeCitation: "National Institute of Diabetes and Digestive and Kidney Diseases. Primary Hyperparathyroidism. Last reviewed March 2019. Accessed 2026-09-10.", organizationOrJournal: "National Institute of Diabetes and Digestive and Kidney Diseases", authors: ["National Institute of Diabetes and Digestive and Kidney Diseases", "John P. Bilezikian, MD (acknowledged reviewer)"], publicationYear: 2019, doi: null, pmid: null, officialUrl: "https://www.niddk.nih.gov/health-information/endocrine-diseases/primary-hyperparathyroidism", accessedOn: "2026-09-10", sourceClass: "government_guidance", licenseLabel: "United States government factual material; NIDDK reuse conditions apply", reuseStatus: "public_domain_conditions_apply", reuseNotes: "Original factual synthesis only. Third-party content, images, and agency marks are excluded; credit NIDDK without implying endorsement.", authorityAssessment: "Directly checked NIDDK patient education supporting biochemical evaluation, renal/bone complications, surgery context, and the FHH differential boundary.", usageRole: "evidence" }),
  source({ id: AAES, title: "Hyperparathyroidism Treatment", completeCitation: "American Association of Endocrine Surgeons. Hyperparathyroidism Treatment. Undated patient education page. Accessed 2026-09-10.", organizationOrJournal: "American Association of Endocrine Surgeons", authors: ["American Association of Endocrine Surgeons"], publicationYear: null, doi: null, pmid: null, officialUrl: "https://endocrinediseases.org/parathyroid/hyperparathyroidism-treatment/", accessedOn: "2026-09-10", sourceClass: "open_educational_resource", licenseLabel: "Copyrighted society educational guidance; targeted factual verification only", reuseStatus: "copyrighted_targeted_verification_only", reuseNotes: "Original factual synthesis and citation only. No source prose, images, tables, or marks are reproduced; this undated page is not used for outdated asymptomatic criteria, intervals, regimens, costs, or outcome claims.", authorityAssessment: "Directly checked AAES patient education corroborating surgery discussion for symptomatic kidney stones and fragility fractures. It is an undated patient page, not a current verified formal guideline.", usageRole: "cross_check" }),
], PRIMARY_HYPERPARATHYROIDISM_CLAIMS);

const labels = ["NIDDK primary hyperparathyroidism guidance (reviewed March 2019)", "AAES hyperparathyroidism treatment education (undated; symptomatic-management cross-check)"];
const labChoices = (n: number) => [
  { id: `calcium_pth_${n}`, label: "Repeat calcium and intact PTH", isCorrect: true, serviceId: "service.basic_labs", rationale: "The biochemical pattern should be established before localization planning." },
  { id: `sestamibi_${n}`, label: "Sestamibi parathyroid localization imaging", rationale: "Localization assists operative planning after biochemical confirmation." },
  { id: `neck_ct_${n}`, label: "Contrast-enhanced neck computed tomography", rationale: "Cross-sectional localization does not establish the biochemical diagnosis." },
  { id: `parathyroid_fna_${n}`, label: "Ultrasound-guided parathyroid aspiration", rationale: "The initial confirmation is biochemical rather than tissue sampling." },
] as const;
const surgeryChoices = (n: number) => [
  { id: `surgical_assessment_${n}`, label: "Parathyroid surgical consultation", isCorrect: true, rationale: "Confirmed disease with renal or skeletal involvement supports surgical assessment." },
  { id: `localization_as_diagnosis_${n}`, label: "Observation with periodic calcium measurements", rationale: "Renal or skeletal involvement supports elective surgical assessment." },
  { id: `reassure_fhh_${n}`, label: "Reassurance with routine primary care follow-up", rationale: "The current result and reviewed context establish primary hyperparathyroidism rather than confirmed FHH." },
  { id: `emergency_treatment_${n}`, label: "Emergency admission for calcium-lowering treatment", rationale: "The patient is stable and does not present an emergency-treatment scenario." },
] as const;

const stories = [
  ["stone-history", 48, "I have had kidney stones and high calcium.", "is referred after recurrent kidney stones and prior high calcium values. Renal function, vitamin-D status, and medication context were reviewed; prior urine and family evaluation do not support FHH, and the patient is stable today.", "Which test should establish {patientName}'s biochemical pattern before localization planning?", "Persistent hypercalcemia is present with an inappropriately nonsuppressed intact PTH."],
  ["fragility-fracture", 67, "I had a low-trauma fracture and abnormal calcium.", "returns after a documented low-trauma fracture with previously documented hypercalcemia. Renal, vitamin-D, medication, and inherited-mimic assessment has already been reviewed without support for FHH; there is no acute hypercalcemia crisis.", "What is the appropriate next confirmation step for {patientName}?", "Repeat testing confirms persistent hypercalcemia with elevated intact PTH."],
  ["recurrent-stone-review", 39, "My stone clinic referred me for high calcium.", "comes from stone clinic after repeated stones and persistent calcium elevation. Renal function, vitamin-D status, medication context, urinary calcium, and family evaluation were reviewed without support for FHH; there are no acute symptoms.", "Which laboratory assessment should be obtained for {patientName} before localization planning?", "The returned studies show persistent hypercalcemia with nonsuppressed intact PTH."],
  ["bone-density-referral", 58, "My fracture led to an endocrine referral.", "is referred after a documented fragility fracture and prior hypercalcemia. Kidney function, vitamin-D status, medications, and inherited-mimic context have been assessed; FHH is not supported in this patient.", "What should be used to confirm {patientName}'s biochemical diagnosis first?", "Repeat serum testing shows hypercalcemia with an inappropriately elevated intact PTH."],
] as const;

const cases: CaseSpec[] = stories.map(([slug, age, complaint, story, stem, result], index) => ({
  id: `case.primary-hyperparathyroidism.${slug}`, displayName: "Primary-hyperparathyroidism evaluation", chiefComplaint: complaint,
  presentation: `{patientName} ${story}`, ageYears: [age, age + 4], sexLabels: ["Female", "Male"], stage: 1,
  nodes: [
    { conceptId: "concept.primary-hyperparathyroidism.biochemical-confirmation", stem, choices: [...labChoices(index + 1)], explanation: "Repeat serum calcium with intact PTH confirms the biochemical pattern before localization planning. FHH has been considered in the history, but urinary calcium alone is not an absolute exclusion.", claimIds: ["claim.primary-hyperparathyroidism.biochemical-pattern"], gate: { id: `gate.primary-hyperparathyroidism.labs.${index + 1}`, serviceId: "service.basic_labs", pendingLabel: "Calcium and PTH testing pending", resultNarrative: result, routeIds: ["route.basic_labs.outsourced", "route.basic_labs.phlebotomy_sendout"] } },
    { conceptId: "concept.primary-hyperparathyroidism.symptomatic-surgery-assessment", currentUpdate: result, stem: `Given {patientName}'s result and documented ${index === 0 || index === 2 ? "kidney-stone history" : "fragility fracture"}, what is the appropriate next planning step?`, choices: [...surgeryChoices(index + 1)], explanation: "Persistent hypercalcemia with nonsuppressed or elevated PTH and kidney-stone or fragility-fracture involvement supports parathyroid surgical assessment. Localization helps plan surgery after the diagnosis is established.", claimIds: ["claim.primary-hyperparathyroidism.renal-bone-surgery-assessment", "claim.primary-hyperparathyroidism.biochemical-pattern"] },
  ],
}));

export const PRIMARY_HYPERPARATHYROIDISM_CONCEPTS = [
  concept({ id: "concept.primary-hyperparathyroidism.biochemical-confirmation", educationalTier: 0, displayName: "Biochemical confirmation of primary hyperparathyroidism", learningObjective: "Use repeat serum calcium with intact PTH to establish the biochemical pattern before localization planning in the scoped stable outpatient pathway.", earliestFacilityStage: 1, conceptType: "workup", evidenceClaimIds: ["claim.primary-hyperparathyroidism.biochemical-pattern"] }),
  concept({ id: "concept.primary-hyperparathyroidism.symptomatic-surgery-assessment", educationalTier: 1, displayName: "Surgical assessment for complicated primary hyperparathyroidism", learningObjective: "Recommend parathyroid surgical assessment for biochemically confirmed primary hyperparathyroidism with authored renal or skeletal complications.", earliestFacilityStage: 1, conceptType: "management", evidenceClaimIds: ["claim.primary-hyperparathyroidism.renal-bone-surgery-assessment"] }),
];
const family = createDevelopmentFamily({ concepts: PRIMARY_HYPERPARATHYROIDISM_CONCEPTS, cases, sourceLabels: labels });
export const PRIMARY_HYPERPARATHYROIDISM_TESTED_CONCEPTS = family.testedConcepts;
export const PRIMARY_HYPERPARATHYROIDISM_QUESTIONS = family.questions;
export const PRIMARY_HYPERPARATHYROIDISM_CASES = family.cases;
export const PRIMARY_HYPERPARATHYROIDISM_CASE_REVIEWS = family.caseReviews;
export const PRIMARY_HYPERPARATHYROIDISM_AUTHORING_REVIEW = NEEDS_REVIEW;
export const PRIMARY_HYPERPARATHYROIDISM_SERVICE_CONTRACTS = [{ serviceId: "service.basic_labs", allowedRouteIds: ["route.basic_labs.outsourced", "route.basic_labs.phlebotomy_sendout"], delivery: "existing_balance_contract" as const }];
