import { ACHALASIA_CASE_REVIEWS, ACHALASIA_CASES, ACHALASIA_CLAIMS, ACHALASIA_CONCEPTS, ACHALASIA_QUESTIONS, ACHALASIA_SERVICE_CONTRACTS, ACHALASIA_SOURCES, ACHALASIA_TESTED_CONCEPTS } from "./achalasia";
import { ANAL_FISSURE_CASE_REVIEWS, ANAL_FISSURE_CASES, ANAL_FISSURE_CLAIMS, ANAL_FISSURE_CONCEPTS, ANAL_FISSURE_QUESTIONS, ANAL_FISSURE_SOURCES, ANAL_FISSURE_TESTED_CONCEPTS } from "./anal-fissure";
import { ESOPHAGEAL_DYSPHAGIA_CASE_REVIEWS, ESOPHAGEAL_DYSPHAGIA_CASES, ESOPHAGEAL_DYSPHAGIA_CLAIMS, ESOPHAGEAL_DYSPHAGIA_CONCEPTS, ESOPHAGEAL_DYSPHAGIA_QUESTIONS, ESOPHAGEAL_DYSPHAGIA_SERVICE_CONTRACTS, ESOPHAGEAL_DYSPHAGIA_SOURCES, ESOPHAGEAL_DYSPHAGIA_TESTED_CONCEPTS } from "./esophageal-dysphagia";
import { INGUINAL_HERNIA_CASE_REVIEWS, INGUINAL_HERNIA_CASES, INGUINAL_HERNIA_CLAIMS, INGUINAL_HERNIA_CONCEPTS, INGUINAL_HERNIA_QUESTIONS, INGUINAL_HERNIA_SERVICE_CONTRACTS, INGUINAL_HERNIA_SOURCES, INGUINAL_HERNIA_TESTED_CONCEPTS } from "./inguinal-hernia";
import { INTERNAL_HEMORRHOIDS_CASE_REVIEWS, INTERNAL_HEMORRHOIDS_CASES, INTERNAL_HEMORRHOIDS_CLAIMS, INTERNAL_HEMORRHOIDS_CONCEPTS, INTERNAL_HEMORRHOIDS_QUESTIONS, INTERNAL_HEMORRHOIDS_SERVICE_CONTRACTS, INTERNAL_HEMORRHOIDS_SOURCES, INTERNAL_HEMORRHOIDS_TESTED_CONCEPTS } from "./internal-hemorrhoids";
import { PIGMENTED_SKIN_LESION_CASE_REVIEWS, PIGMENTED_SKIN_LESION_CASES, PIGMENTED_SKIN_LESION_CLAIMS, PIGMENTED_SKIN_LESION_CONCEPTS, PIGMENTED_SKIN_LESION_QUESTIONS, PIGMENTED_SKIN_LESION_SERVICE_CONTRACTS, PIGMENTED_SKIN_LESION_SOURCES, PIGMENTED_SKIN_LESION_TESTED_CONCEPTS } from "./pigmented-skin-lesion";
import { PILONIDAL_DISEASE_CASE_REVIEWS, PILONIDAL_DISEASE_CASES, PILONIDAL_DISEASE_CLAIMS, PILONIDAL_DISEASE_CONCEPTS, PILONIDAL_DISEASE_QUESTIONS, PILONIDAL_DISEASE_SOURCES, PILONIDAL_DISEASE_TESTED_CONCEPTS } from "./pilonidal-disease";
import { POSTOPERATIVE_SEROMA_CASE_REVIEWS, POSTOPERATIVE_SEROMA_CASES, POSTOPERATIVE_SEROMA_CLAIMS, POSTOPERATIVE_SEROMA_CONCEPTS, POSTOPERATIVE_SEROMA_QUESTIONS, POSTOPERATIVE_SEROMA_SOURCES, POSTOPERATIVE_SEROMA_TESTED_CONCEPTS } from "./postoperative-seroma";
import { PRIMARY_HYPERPARATHYROIDISM_CASE_REVIEWS, PRIMARY_HYPERPARATHYROIDISM_CASES, PRIMARY_HYPERPARATHYROIDISM_CLAIMS, PRIMARY_HYPERPARATHYROIDISM_CONCEPTS, PRIMARY_HYPERPARATHYROIDISM_QUESTIONS, PRIMARY_HYPERPARATHYROIDISM_SERVICE_CONTRACTS, PRIMARY_HYPERPARATHYROIDISM_SOURCES, PRIMARY_HYPERPARATHYROIDISM_TESTED_CONCEPTS } from "./primary-hyperparathyroidism";
import { THYROID_NODULE_CASE_REVIEWS, THYROID_NODULE_CASES, THYROID_NODULE_CLAIMS, THYROID_NODULE_CONCEPTS, THYROID_NODULE_QUESTIONS, THYROID_NODULE_SERVICE_CONTRACTS, THYROID_NODULE_SOURCES, THYROID_NODULE_TESTED_CONCEPTS } from "./thyroid-nodule";

export const SURGERY_CENTER_AUTHORING_CONCEPTS = [...THYROID_NODULE_CONCEPTS, ...PRIMARY_HYPERPARATHYROIDISM_CONCEPTS, ...INGUINAL_HERNIA_CONCEPTS, ...ANAL_FISSURE_CONCEPTS, ...INTERNAL_HEMORRHOIDS_CONCEPTS, ...ESOPHAGEAL_DYSPHAGIA_CONCEPTS, ...ACHALASIA_CONCEPTS, ...PIGMENTED_SKIN_LESION_CONCEPTS, ...POSTOPERATIVE_SEROMA_CONCEPTS, ...PILONIDAL_DISEASE_CONCEPTS];
export const SURGERY_CENTER_TESTED_CONCEPTS = [...THYROID_NODULE_TESTED_CONCEPTS, ...PRIMARY_HYPERPARATHYROIDISM_TESTED_CONCEPTS, ...INGUINAL_HERNIA_TESTED_CONCEPTS, ...ANAL_FISSURE_TESTED_CONCEPTS, ...INTERNAL_HEMORRHOIDS_TESTED_CONCEPTS, ...ESOPHAGEAL_DYSPHAGIA_TESTED_CONCEPTS, ...ACHALASIA_TESTED_CONCEPTS, ...PIGMENTED_SKIN_LESION_TESTED_CONCEPTS, ...POSTOPERATIVE_SEROMA_TESTED_CONCEPTS, ...PILONIDAL_DISEASE_TESTED_CONCEPTS];
export const SURGERY_CENTER_QUESTIONS = [...THYROID_NODULE_QUESTIONS, ...PRIMARY_HYPERPARATHYROIDISM_QUESTIONS, ...INGUINAL_HERNIA_QUESTIONS, ...ANAL_FISSURE_QUESTIONS, ...INTERNAL_HEMORRHOIDS_QUESTIONS, ...ESOPHAGEAL_DYSPHAGIA_QUESTIONS, ...ACHALASIA_QUESTIONS, ...PIGMENTED_SKIN_LESION_QUESTIONS, ...POSTOPERATIVE_SEROMA_QUESTIONS, ...PILONIDAL_DISEASE_QUESTIONS];
export const SURGERY_CENTER_CASES = [...THYROID_NODULE_CASES, ...PRIMARY_HYPERPARATHYROIDISM_CASES, ...INGUINAL_HERNIA_CASES, ...ANAL_FISSURE_CASES, ...INTERNAL_HEMORRHOIDS_CASES, ...ESOPHAGEAL_DYSPHAGIA_CASES, ...ACHALASIA_CASES, ...PIGMENTED_SKIN_LESION_CASES, ...POSTOPERATIVE_SEROMA_CASES, ...PILONIDAL_DISEASE_CASES];
export const SURGERY_CENTER_CLAIMS = [...THYROID_NODULE_CLAIMS, ...PRIMARY_HYPERPARATHYROIDISM_CLAIMS, ...INGUINAL_HERNIA_CLAIMS, ...ANAL_FISSURE_CLAIMS, ...INTERNAL_HEMORRHOIDS_CLAIMS, ...ESOPHAGEAL_DYSPHAGIA_CLAIMS, ...ACHALASIA_CLAIMS, ...PIGMENTED_SKIN_LESION_CLAIMS, ...POSTOPERATIVE_SEROMA_CLAIMS, ...PILONIDAL_DISEASE_CLAIMS];
export const SURGERY_CENTER_SOURCES = [...THYROID_NODULE_SOURCES, ...PRIMARY_HYPERPARATHYROIDISM_SOURCES, ...INGUINAL_HERNIA_SOURCES, ...ANAL_FISSURE_SOURCES, ...INTERNAL_HEMORRHOIDS_SOURCES, ...ESOPHAGEAL_DYSPHAGIA_SOURCES, ...ACHALASIA_SOURCES, ...PIGMENTED_SKIN_LESION_SOURCES, ...POSTOPERATIVE_SEROMA_SOURCES, ...PILONIDAL_DISEASE_SOURCES];
export const SURGERY_CENTER_CASE_REVIEWS = [...THYROID_NODULE_CASE_REVIEWS, ...PRIMARY_HYPERPARATHYROIDISM_CASE_REVIEWS, ...INGUINAL_HERNIA_CASE_REVIEWS, ...ANAL_FISSURE_CASE_REVIEWS, ...INTERNAL_HEMORRHOIDS_CASE_REVIEWS, ...ESOPHAGEAL_DYSPHAGIA_CASE_REVIEWS, ...ACHALASIA_CASE_REVIEWS, ...PIGMENTED_SKIN_LESION_CASE_REVIEWS, ...POSTOPERATIVE_SEROMA_CASE_REVIEWS, ...PILONIDAL_DISEASE_CASE_REVIEWS];

export const SURGERY_CENTER_SERVICE_CONTRACTS = [
  ...THYROID_NODULE_SERVICE_CONTRACTS,
  ...PRIMARY_HYPERPARATHYROIDISM_SERVICE_CONTRACTS,
  ...INGUINAL_HERNIA_SERVICE_CONTRACTS,
  ...INTERNAL_HEMORRHOIDS_SERVICE_CONTRACTS,
  ...ESOPHAGEAL_DYSPHAGIA_SERVICE_CONTRACTS,
  ...ACHALASIA_SERVICE_CONTRACTS,
  ...PIGMENTED_SKIN_LESION_SERVICE_CONTRACTS,
] as const;

export const SURGERY_CENTER_BATCH_MANIFEST = {
  contentVersion: "development-batch.2026-09-10.1",
  authoringConceptCount: 20,
  testedConceptCount: 20,
  questionVariantCount: 80,
  caseCount: 40,
  multistepCaseCount: 40,
  resultGateCount: 32,
  caseReviewCount: 40,
  sourceCount: 20,
  evidenceClaimCount: 20,
  serviceContractCount: 7,
  admissionScope: "active_synthetic_unapproved_prototype",
  publicReleaseAuthorized: false,
} as const;
