export interface ServiceOperationPhase { id: string; roomDefinitionId: string | null; durationMinutes: number; staffRoleDefinitionIds: readonly string[]; providerRoleDefinitionIds?: readonly string[]; founderEligible?: boolean }
export interface ServiceOperationContract { visitorMode: "scheduled" | "work_queue" | "explicit_only"; arrivalCadenceMinutes: number | null; phases: readonly ServiceOperationPhase[] }
export interface ServiceIncomeLine { id: string; displayName: string; kind: "clinical" | "retail" | "remote"; minimumFacilityLevel: 1 | 2 | 3 | 4 | 5; fee: number; requiredCapabilityIds: readonly string[]; eligibleRouteIds: readonly string[]; paymentStage: "resource_completion" | "episode_completion" | "dispense"; operation?: ServiceOperationContract }

const phase = (id: string, roomDefinitionId: string | null, durationMinutes: number, staffRoleDefinitionIds: readonly string[] = [], providerRoleDefinitionIds?: readonly string[], founderEligible?: boolean): ServiceOperationPhase => ({ id, roomDefinitionId, durationMinutes, staffRoleDefinitionIds, ...(providerRoleDefinitionIds ? { providerRoleDefinitionIds } : {}), ...(founderEligible ? { founderEligible: true } : {}) });

/** Product balance rows; clinical route/provider approval remains authoritative. */
export const SERVICE_INCOME_CATALOG: readonly ServiceIncomeLine[] = [
  { id: "income.ultrasound", displayName: "Ultrasound", kind: "clinical", minimumFacilityLevel: 1, fee: 120, requiredCapabilityIds: ["capability.ultrasound_machine", "capability.staff.imaging_technician"], eligibleRouteIds: ["route.ultrasound.in_house"], paymentStage: "resource_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 120, phases: [phase("acquisition", "room.ultrasound", 45, ["staff.imaging_technician"])] } },
  { id: "income.xray", displayName: "X-ray", kind: "clinical", minimumFacilityLevel: 2, fee: 90, requiredCapabilityIds: ["capability.xray_machine", "capability.staff.imaging_technician"], eligibleRouteIds: ["route.xray.in_house"], paymentStage: "resource_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 180, phases: [phase("acquisition", "room.xray", 60, ["staff.imaging_technician"])] } },
  { id: "income.ct", displayName: "CT", kind: "clinical", minimumFacilityLevel: 2, fee: 180, requiredCapabilityIds: ["capability.ct_scanner", "capability.staff.imaging_technician"], eligibleRouteIds: ["route.ct.in_house"], paymentStage: "resource_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 240, phases: [phase("acquisition", "room.ct", 60, ["staff.imaging_technician"])] } },
  { id: "income.collection", displayName: "Blood/specimen collection", kind: "clinical", minimumFacilityLevel: 2, fee: 50, requiredCapabilityIds: ["capability.phlebotomy_collection", "capability.staff.phlebotomist"], eligibleRouteIds: ["route.basic_labs.phlebotomy_sendout"], paymentStage: "resource_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 60, phases: [phase("collection", "room.phlebotomy", 15, ["staff.phlebotomist"])] } },
  { id: "income.bladder_scan", displayName: "Bladder scan", kind: "clinical", minimumFacilityLevel: 1, fee: 20, requiredCapabilityIds: ["capability.ultrasound_machine", "capability.staff.imaging_technician"], eligibleRouteIds: ["route.bladder_scan.ultrasound_room"], paymentStage: "resource_completion", operation: { visitorMode: "explicit_only", arrivalCadenceMinutes: null, phases: [phase("scan", "room.ultrasound", 5, ["staff.imaging_technician"])] } },
  { id: "income.endoscopy", displayName: "Routine endoscopy", kind: "clinical", minimumFacilityLevel: 2, fee: 400, requiredCapabilityIds: ["capability.endoscopy", "capability.periop_recovery"], eligibleRouteIds: ["route.endoscopy.in_house"], paymentStage: "resource_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 300, phases: [phase("preparation_and_procedure", "room.endoscopy", 75, ["staff.endoscopy_nurse"], ["staff.endoscopist"], true), phase("recovery", "room.periop_recovery", 45, ["staff.periop_nurse"])] } },
  { id: "income.advanced_endoscopy", displayName: "Advanced endoscopy", kind: "clinical", minimumFacilityLevel: 2, fee: 550, requiredCapabilityIds: ["capability.endoscopy", "capability.periop_recovery"], eligibleRouteIds: ["route.endoscopy.eus-ercp-sampling.in_house"], paymentStage: "resource_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 600, phases: [phase("preparation_and_procedure", "room.endoscopy", 75, ["staff.endoscopy_nurse"], ["staff.endoscopist"], true), phase("recovery", "room.periop_recovery", 45, ["staff.periop_nurse"])] } },
  { id: "income.glp1_telehealth", displayName: "GLP-1 telehealth consultation", kind: "remote", minimumFacilityLevel: 2, fee: 50, requiredCapabilityIds: ["capability.glp1_telehealth", "capability.staff.glp1_np"], eligibleRouteIds: [], paymentStage: "episode_completion" },
  { id: "income.laboratory_processing", displayName: "Onsite laboratory processing", kind: "clinical", minimumFacilityLevel: 3, fee: 80, requiredCapabilityIds: ["capability.in_house_laboratory", "capability.staff.laboratory_technician"], eligibleRouteIds: [], paymentStage: "resource_completion", operation: { visitorMode: "explicit_only", arrivalCadenceMinutes: null, phases: [phase("processing", "room.laboratory", 60, ["staff.laboratory_technician"])] } },
  { id: "income.ambulatory_operation", displayName: "Ambulatory operation", kind: "clinical", minimumFacilityLevel: 3, fee: 900, requiredCapabilityIds: ["capability.ambulatory_or", "capability.staff.or_nurse"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 600, phases: [phase("operation", "room.ambulatory_or", 120, ["staff.or_nurse"], ["staff.surgeon"], true), phase("recovery", "room.periop_recovery", 60, ["staff.periop_nurse"])] } },
  { id: "income.ambulatory_operation_extended", displayName: "Extended ambulatory operation", kind: "clinical", minimumFacilityLevel: 3, fee: 1300, requiredCapabilityIds: ["capability.ambulatory_or", "capability.staff.or_nurse"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "explicit_only", arrivalCadenceMinutes: null, phases: [phase("operation", "room.ambulatory_or", 180, ["staff.or_nurse"], ["staff.surgeon"], true), phase("recovery", "room.periop_recovery", 60, ["staff.periop_nurse"])] } },
  { id: "income.pharmacy_pickup", displayName: "Prescription pickup", kind: "retail", minimumFacilityLevel: 3, fee: 25, requiredCapabilityIds: ["capability.pharmacy", "capability.staff.pharmacist"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.mri", displayName: "MRI", kind: "clinical", minimumFacilityLevel: 4, fee: 240, requiredCapabilityIds: ["capability.mri_machine", "capability.staff.imaging_technician"], eligibleRouteIds: [], paymentStage: "resource_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 240, phases: [phase("acquisition", "room.mri", 60, ["staff.imaging_technician"])] } },
  { id: "income.image_read", displayName: "Onsite image interpretation", kind: "remote", minimumFacilityLevel: 4, fee: 40, requiredCapabilityIds: ["capability.radiology_reading", "capability.staff.radiologist"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "work_queue", arrivalCadenceMinutes: null, phases: [phase("interpretation", "room.reading", 30, ["staff.radiologist"])] } },
  { id: "income.app_consult", displayName: "APP appointment", kind: "clinical", minimumFacilityLevel: 4, fee: 80, requiredCapabilityIds: ["capability.staff.app"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 120, phases: [phase("consultation", "room.examination", 30, ["staff.app"])] } },
  { id: "income.pediatric_consult", displayName: "Pediatric appointment", kind: "clinical", minimumFacilityLevel: 4, fee: 80, requiredCapabilityIds: ["capability.pediatric_examination", "capability.staff.app"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "explicit_only", arrivalCadenceMinutes: null, phases: [phase("consultation", "room.pediatric_examination", 30, ["staff.app"])] } },
  { id: "income.wound_care", displayName: "Routine wound care", kind: "clinical", minimumFacilityLevel: 4, fee: 60, requiredCapabilityIds: ["capability.wound_ostomy_clinic", "capability.staff.app"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 180, phases: [phase("wound_care", "room.wound_ostomy", 30, ["staff.app"])] } },
  { id: "income.wound_procedure", displayName: "Wound procedure", kind: "clinical", minimumFacilityLevel: 4, fee: 120, requiredCapabilityIds: ["capability.wound_ostomy_clinic", "capability.staff.app"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "explicit_only", arrivalCadenceMinutes: null, phases: [phase("wound_procedure", "room.wound_ostomy", 45, ["staff.app"])] } },
  { id: "income.ostomy_support", displayName: "Ostomy support", kind: "clinical", minimumFacilityLevel: 4, fee: 75, requiredCapabilityIds: ["capability.wound_ostomy_clinic", "capability.staff.app"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 180, phases: [phase("support", "room.wound_ostomy", 30, ["staff.app"])] } },
  { id: "income.followup_independent", displayName: "Independent follow-up", kind: "clinical", minimumFacilityLevel: 1, fee: 40, requiredCapabilityIds: ["capability.examination"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "explicit_only", arrivalCadenceMinutes: null, phases: [phase("followup", "room.examination", 20, [], [], true)] } },
  { id: "income.minor_procedure_simple", displayName: "Simple minor procedure", kind: "clinical", minimumFacilityLevel: 1, fee: 100, requiredCapabilityIds: ["capability.minor_procedure"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "scheduled", arrivalCadenceMinutes: 240, phases: [phase("procedure", "room.minor_procedure", 45, [], [], true)] } },
  { id: "income.minor_procedure_sampling", displayName: "Minor diagnostic sampling", kind: "clinical", minimumFacilityLevel: 1, fee: 150, requiredCapabilityIds: ["capability.minor_procedure"], eligibleRouteIds: ["route.skin_excisional_biopsy.in_house", "route.cutaneous_lesion_biopsy.in_house"], paymentStage: "resource_completion", operation: { visitorMode: "explicit_only", arrivalCadenceMinutes: null, phases: [phase("sampling", "room.minor_procedure", 60, [], [], true)] } },
  { id: "income.minor_procedure_complex", displayName: "Complex office procedure", kind: "clinical", minimumFacilityLevel: 1, fee: 200, requiredCapabilityIds: ["capability.minor_procedure"], eligibleRouteIds: [], paymentStage: "episode_completion", operation: { visitorMode: "explicit_only", arrivalCadenceMinutes: null, phases: [phase("procedure", "room.minor_procedure", 60, [], [], true)] } },
  { id: "income.coffee", displayName: "Coffee", kind: "retail", minimumFacilityLevel: 2, fee: 5, requiredCapabilityIds: ["capability.coffee_kiosk"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.kiosk_drink", displayName: "Bottled drink", kind: "retail", minimumFacilityLevel: 2, fee: 3, requiredCapabilityIds: ["capability.coffee_kiosk"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.kiosk_snack", displayName: "Packaged snack", kind: "retail", minimumFacilityLevel: 2, fee: 4, requiredCapabilityIds: ["capability.coffee_kiosk"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.vending_drink", displayName: "Vending drink", kind: "retail", minimumFacilityLevel: 3, fee: 3, requiredCapabilityIds: ["capability.vending"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.vending_snack", displayName: "Vending snack", kind: "retail", minimumFacilityLevel: 3, fee: 4, requiredCapabilityIds: ["capability.vending"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.gift_shop", displayName: "Gift", kind: "retail", minimumFacilityLevel: 5, fee: 15, requiredCapabilityIds: ["capability.gift_shop"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.gift_shop_premium", displayName: "Premium gift", kind: "retail", minimumFacilityLevel: 5, fee: 25, requiredCapabilityIds: ["capability.gift_shop"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.otc_supply", displayName: "OTC supply basket", kind: "retail", minimumFacilityLevel: 3, fee: 12, requiredCapabilityIds: ["capability.pharmacy"], eligibleRouteIds: [], paymentStage: "dispense" },
  { id: "income.wound_supply", displayName: "Wound/ostomy supply basket", kind: "retail", minimumFacilityLevel: 4, fee: 20, requiredCapabilityIds: ["capability.wound_ostomy_clinic"], eligibleRouteIds: [], paymentStage: "dispense" },
];

export function getServiceIncomeForRoute(routeId: string): ServiceIncomeLine | null { return SERVICE_INCOME_CATALOG.find((line) => line.eligibleRouteIds.includes(routeId)) ?? null; }
export function getServiceIncomeLine(lineId: string): ServiceIncomeLine | null { return SERVICE_INCOME_CATALOG.find((line) => line.id === lineId) ?? null; }
