import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';

const repo=path.resolve(import.meta.dirname,'../../..'),out=path.join(repo,'artifacts/character-movement/gs019-gray-braid-walk/west-candidate-v1'),probe=process.argv.includes('--probe'),phases=['01','02','03','04','05','06','07','08'];
const sha=value=>createHash('sha256').update(value).digest('hex'),save=(file,canvas)=>{const bytes=canvas.toBuffer('image/png');mkdirSync(path.dirname(path.join(out,file)),{recursive:true});writeFileSync(path.join(out,file),bytes);return{file,sha256:sha(bytes),width:canvas.width,height:canvas.height};};
const sources={
  first:{file:'tools/character-mapping/gs019-gray-braid-walk/west-first-half-v3-source.png',prompt:'tools/character-mapping/gs019-gray-braid-walk/west-first-half-v3-prompt.txt'},
  second:{file:'tools/character-mapping/gs019-gray-braid-walk/west-second-half-v3-source.png',prompt:'tools/character-mapping/gs019-gray-braid-walk/west-second-half-v3-prompt.txt'}
};
const contract={'01':'NEAR contact foreground; FAR leg back','02':'NEAR straight support foreground; FAR heel-off behind','03':'NEAR straight support foreground; FAR bent passing behind','04':'FAR swing left behind; NEAR support foreground','05':'FAR contact; NEAR leg back foreground','06':'NEAR bent foreground with heel lifting right; FAR planted','07':'NEAR low bend foreground; FAR straight planted','08':'NEAR uncurl left foreground; FAR support behind'};
const pixels=canvas=>canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
function cell(image,index){const col=index%2,row=Math.floor(index/2),x=Math.floor(col*image.width/2),y=Math.floor(row*image.height/2),width=Math.floor((col+1)*image.width/2)-x,height=Math.floor((row+1)*image.height/2)-y,canvas=createCanvas(width,height);canvas.getContext('2d').drawImage(image,x,y,width,height,0,0,width,height);return{canvas,cell:{x,y,width,height}};}
function largest(canvas){const data=pixels(canvas),seen=new Uint8Array(canvas.width*canvas.height);let best=[];for(let start=0;start<seen.length;start++){if(seen[start]||data[start*4+3]<24)continue;const queue=[start],group=[];seen[start]=1;while(queue.length){const at=queue.pop(),x=at%canvas.width,y=Math.floor(at/canvas.width);group.push(at);for(const next of[x?at-1:-1,x<canvas.width-1?at+1:-1,y?at-canvas.width:-1,y<canvas.height-1?at+canvas.width:-1])if(next>=0&&!seen[next]&&data[next*4+3]>=24){seen[next]=1;queue.push(next);}}if(group.length>best.length)best=group;}const output=createCanvas(canvas.width,canvas.height),image=output.getContext('2d').createImageData(canvas.width,canvas.height);let left=canvas.width,top=canvas.height,right=-1,bottom=-1;for(const at of best){const x=at%canvas.width,y=Math.floor(at/canvas.width);for(let channel=0;channel<4;channel++)image.data[at*4+channel]=data[at*4+channel];left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}output.getContext('2d').putImageData(image,0,0);return{canvas:output,pixels:best.length,bounds:{left,top,right,bottom,width:right-left+1,height:bottom-top+1}};}
function crop(canvas){const data=pixels(canvas);let left=canvas.width,top=canvas.height,right=-1,bottom=-1;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++)if(data[(y*canvas.width+x)*4+3]>=24){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}const output=createCanvas(right-left+1,bottom-top+1);output.getContext('2d').drawImage(canvas,left,top,output.width,output.height,0,0,output.width,output.height);return{canvas:output,bounds:{left,top,right,bottom,width:output.width,height:output.height}};}
function cleanHeadlessBody(component){const cleaned=crop(component.canvas),topData=pixels(cleaned.canvas),centers=[];for(let y=0;y<Math.min(14,cleaned.canvas.height);y++){let left=cleaned.canvas.width,right=-1,count=0;for(let x=0;x<cleaned.canvas.width;x++)if(topData[(y*cleaned.canvas.width+x)*4+3]>=24){left=Math.min(left,x);right=Math.max(right,x);count++;}if(count>=8)centers.push((left+right)/2);}centers.sort((a,b)=>a-b);return{...cleaned,collarAxis:centers[Math.floor(centers.length/2)],collarRows:centers.length,removedHeadPixels:0,removedBraidPixels:0};}
function resize(canvas,scale){const output=createCanvas(Math.round(canvas.width*scale),Math.round(canvas.height*scale)),context=output.getContext('2d');context.imageSmoothingEnabled=false;context.drawImage(canvas,0,0,output.width,output.height);return output;}
function geometry(canvas){const data=pixels(canvas);let left=canvas.width,top=canvas.height,right=-1,bottom=-1,floorAlpha=0,belowFloorAlpha=0;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const alpha=data[(y*canvas.width+x)*4+3];if(alpha<24)continue;left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);if(y===287)floorAlpha++;if(y>287)belowFloorAlpha++;}return{bounds:{left,top,right,bottom,width:right-left+1,height:bottom-top+1},floorAlpha,belowFloorAlpha};}
async function cleanedNativeFace(face,patch){const canvas=createCanvas(face.width,face.height),context=canvas.getContext('2d');context.drawImage(face,0,0);const faceData=context.getImageData(0,0,canvas.width,canvas.height);let coatPixels=0;for(let y=117;y<=132;y++)for(let x=78;x<=118;x++){const boundary=127-(x-78)*.3,k=(y*canvas.width+x)*4;if(y>=boundary&&faceData.data[k+3]>=24){faceData.data[k+3]=0;coatPixels++;}}context.putImageData(faceData,0,0);let retainedPixels=0;for(let at=3;at<faceData.data.length;at+=4)if(faceData.data[at]>=24)retainedPixels++;return{canvas,coatPixels,outlinePixels:0,retainedPixels,authoredContour:[[78,127],[118,115],[118,132],[78,132]]};}

const standingFile='artifacts/character-movement/whole-body-static-v1/gray-braid/stand-west.png',faceFile='tools/character-mapping/layered-pilot/gray-braid/assets/gray-west-face-crown-v1.png',braidFile='tools/character-mapping/layered-pilot/gray-braid/assets/gray-west-braid-tail-v1.png',patchFile='tools/character-mapping/layered-pilot/gray-braid/assets/gray-west-shoulder-patch-v1.png',standingBytes=readFileSync(path.join(repo,standingFile)),faceBytes=readFileSync(path.join(repo,faceFile)),braidBytes=readFileSync(path.join(repo,braidFile)),patchBytes=readFileSync(path.join(repo,patchFile)),standing=await loadImage(standingBytes),face=await loadImage(faceBytes),braid=await loadImage(braidBytes),patch=await loadImage(patchBytes),nativeFace=await cleanedNativeFace(face,patch);
const library={};for(const[id,source]of Object.entries(sources)){const bytes=readFileSync(path.join(repo,source.file)),image=await loadImage(path.join(repo,source.file));library[id]=[];for(let index=0;index<4;index++){const extracted=cell(image,index),component=largest(extracted.canvas),body=cleanHeadlessBody(component);library[id].push({...body,originalCell:extracted.canvas,cell:extracted.cell,componentPixels:component.pixels,componentBounds:component.bounds});}source.sha256=sha(bytes);source.promptSha256=sha(readFileSync(path.join(repo,source.prompt)));}
const targetSpan=287-108,scale={};for(const id of['first','second']){const spans=library[id].map(item=>item.canvas.height-1).sort((a,b)=>a-b),median=(spans[1]+spans[2])/2,maxWidth=Math.max(...library[id].map(item=>item.canvas.width));scale[id]=Math.min(targetSpan/median,156/maxWidth);}
const prepared={};for(const[index,phase]of phases.entries()){const id=index<4?'first':'second',source=library[id][index%4],body=resize(source.canvas,scale[id]),collarAxis=source.collarAxis*scale[id],rawX=Math.round(80-collarAxis),x=Math.max(1,Math.min(159-body.width,rawX)),y=287-(body.height-1);prepared[phase]={id,source,body,x,y,rawX,collarAxis};}
const frames={},eastFrames={},authored={},measurements={};for(const phase of probe?['01','05']:phases){const item=prepared[phase];authored[phase]=save(`authored/${phase}.png`,item.body);const collar={x:item.x+item.collarAxis,y:item.y},delta={x:Math.round(collar.x-80),y:collar.y-108},identityTranslation={e:-1+delta.x,f:-24+delta.y},frame=createCanvas(160,320),context=frame.getContext('2d');context.imageSmoothingEnabled=false;context.drawImage(braid,identityTranslation.e,identityTranslation.f);context.drawImage(item.body,item.x,item.y);const nativeFaceCanvas=createCanvas(160,320),faceContext=nativeFaceCanvas.getContext('2d');faceContext.drawImage(nativeFace.canvas,identityTranslation.e,identityTranslation.f);const frameImage=context.getImageData(0,0,160,320),faceData=pixels(nativeFaceCanvas);for(let at=0;at<160*320;at++)if(faceData[at*4+3])frameImage.data[at*4+3]=0;context.putImageData(frameImage,0,0);context.drawImage(nativeFaceCanvas,0,0);frames[phase]=save(`frames/west-${phase}.png`,frame);const measured=geometry(frame);measurements[phase]={sourceSheet:item.id,sourceCell:(Number(phase)-1)%4+1,sourceCellRect:item.source.cell,componentPixels:item.source.componentPixels,componentBounds:item.source.componentBounds,sourceIdentityPolicy:{policy:'selected v3 source is authored headless and braidless; largest alpha component cropped without pixel deletion',removedHeadPixels:0,removedBraidPixels:0,collarRowsMeasured:item.source.collarRows},uniformScale:scale[item.id],bodyPlacement:{x:item.x,y:item.y,width:item.body.width,height:item.body.height},collar:{sourceAxis:item.source.collarAxis,scaledAxis:item.collarAxis,screen:collar,target:{x:80,y:108}},alignment:{requestedX:item.rawX,appliedX:item.x,collarResidualX:collar.x-80,collarDelta:delta},identityTranslation,geometry:measured,gaitAudit:contract[phase]};const east=createCanvas(160,320),eastContext=east.getContext('2d');eastContext.translate(160,0);eastContext.scale(-1,1);eastContext.drawImage(frame,0,0);eastFrames[phase]={...save(`frames/east-${phase}.png`,east),exactHorizontalMirrorOf:frames[phase].file};}
const early=createCanvas(480,344),earlyContext=early.getContext('2d');earlyContext.fillStyle='#ded8ce';earlyContext.fillRect(0,0,early.width,early.height);earlyContext.fillStyle='#20242a';earlyContext.font='14px sans-serif';earlyContext.imageSmoothingEnabled=false;for(const[index,[label,image]]of[['Standing West',standing],['Candidate 01',await loadImage(path.join(out,frames['01'].file))],['Candidate 05',await loadImage(path.join(out,frames['05'].file))]].entries()){earlyContext.fillText(label,index*160+4,17);earlyContext.drawImage(image,index*160,24);}
const neck=createCanvas(640,312),neckContext=neck.getContext('2d');neckContext.fillStyle='#ded8ce';neckContext.fillRect(0,0,neck.width,neck.height);neckContext.fillStyle='#20242a';neckContext.font='14px sans-serif';neckContext.imageSmoothingEnabled=false;for(const[index,[label,file]]of[['01 neckline/braid 4x',frames['01'].file],['05 neckline/braid 4x',frames['05'].file]].entries()){neckContext.fillText(label,index*320+4,17);const image=await loadImage(path.join(out,file));neckContext.drawImage(image,30,68,100,72,index*320,24,400,288);}
const cleanedProof=createCanvas(1000,620),cleanedContext=cleanedProof.getContext('2d');cleanedContext.fillStyle='#ded8ce';cleanedContext.fillRect(0,0,cleanedProof.width,cleanedProof.height);cleanedContext.fillStyle='#20242a';cleanedContext.font='16px sans-serif';cleanedContext.imageSmoothingEnabled=false;for(const[index,phase]of['01','05'].entries()){const item=prepared[phase],ox=index*500,fit=Math.min(460/item.source.canvas.width,550/item.source.canvas.height),dw=item.source.canvas.width*fit,dh=item.source.canvas.height*fit;cleanedContext.fillText(`${phase} selected headless source component`,ox+4,20);cleanedContext.drawImage(item.source.canvas,ox+(500-dw)/2,40,dw,dh);}
async function strip(direction,records){const canvas=createCanvas(1280,344),context=canvas.getContext('2d');context.fillStyle='#ded8ce';context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle='#20242a';context.font='14px sans-serif';context.imageSmoothingEnabled=false;for(const[index,phase]of phases.entries()){context.fillText(`${direction} ${phase}`,index*160+4,17);context.drawImage(await loadImage(path.join(out,records[phase].file)),index*160,24);}return canvas;}
const proofs={early01And05Native:save('proofs/standing-01-05-native.png',early),early01And05NeckBraid4x:save('proofs/01-05-neckline-braid-4x.png',neck),early01And05CleanedSource:save('proofs/01-05-cleaned-source-detail.png',cleanedProof),...(probe?{}:{westAll8Native:save('proofs/west-all8-native.png',await strip('West',frames)),eastAll8Native:save('proofs/east-all8-native.png',await strip('East',eastFrames))})};
const pin=(file,bytes)=>({file,sha256:sha(bytes)}),manifest={schemaVersion:'gs019-gray-braid-walk/west-candidate-v1',status:probe?'probe-needs-parent-review':'prototype-needs-parent-review',characterId:'patient.adult.046',direction:'west',canvas:{width:160,height:320,axisX:80,floorY:287,visualSoleY:287},gamePresentation:{width:32,height:64,tileSize:24},phaseContract:{ids:phases,cadenceMs:180,anatomy:contract,auditStatus:'visual near/far and braid-layer review required; pixel validation cannot certify anatomy'},pins:{approvedStanding:pin(standingFile,standingBytes),nativeIdentity:{face:{...pin(faceFile,faceBytes),directStandingTranslation:{e:-1,f:-24},coatWedgeRemoval:{coatPixels:nativeFace.coatPixels,outlinePixels:nativeFace.outlinePixels,retainedPixels:nativeFace.retainedPixels,authoredContour:nativeFace.authoredContour}},braid:{...pin(braidFile,braidBytes),directStandingTranslation:{e:-1,f:-24}},shoulderPatchEvidence:pin(patchFile,patchBytes),policy:'native braid behind complete body; cleaned native face on top; shoulder patch never drawn'},sources},registration:{collarTarget:{x:80,y:108},floorY:287,policy:'one nearest-neighbor uniform scale per half; whole body translated only; split native identity follows integer collar delta'},scaleEvidence:scale,authored,frames,eastFrames,measurements,proofs};const bytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');mkdirSync(out,{recursive:true});writeFileSync(path.join(out,probe?'probe-manifest.json':'manifest.json'),bytes);console.log(JSON.stringify({status:'PASS',mode:probe?'probe':'full',manifestSha256:sha(bytes),scale,identityCleanup:manifest.pins.nativeIdentity.face.coatWedgeRemoval,measurements:Object.fromEntries(Object.entries(measurements).map(([phase,value])=>[phase,{collar:value.collar,identityTranslation:value.identityTranslation,geometry:value.geometry}])),proofs},null,2));
