// Manager browser captures. Pins the reviewed manifest and records real errors.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');const {chromium}=require('@playwright/test'),{listen}=require('./browser-errors.cjs');
const here=__dirname,out=path.join(here,'evidence'),url=process.env.FOUNDER_OFFICE_PROOF_URL||'http://127.0.0.1:4191/tools/room-design/level-5/founders-office/proof/index.html';
(async()=>{fs.mkdirSync(out,{recursive:true});const bytes=fs.readFileSync(path.join(here,'proof-manifest.json')),proofManifestSha256=crypto.createHash('sha256').update(bytes).digest('hex');const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),events=listen(page),captures=[];assert.equal((await page.goto(url)).status(),200);await page.waitForFunction(()=>document.body.dataset.ready==='1');assert.equal(await page.evaluate(async()=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await(await fetch('./proof-manifest.json')).arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('')),proofManifestSha256);
 const states=[['painted',{}],['empty',{actors:false}],['founder',{visitors:false}],['visitor',{founders:false}],['contacts',{contacts:true,bases:true,grid:true}],['all-doors',{routes:true,doors:['N1','N2','N3','N4','S1','S2','S3','S4','WA','WB','WC','WD','EA','EB','EC','ED']}],['backed',{backed:['N1','N2','N3','N4']}],['bookcase-door',{doors:['N1']}],['plant-door',{doors:['EA']}],['print-door',{doors:['N2']}]];
 for(const [id,override]of states){await page.evaluate(async o=>{const L=window.__lab;Object.assign(L.state,{actors:true,founders:true,visitors:true,routes:false,grid:false,contacts:false,bases:false,doors:new Set(),backed:new Set()},o);if(o.doors)L.state.doors=new Set(o.doors);if(o.backed)L.state.backed=new Set(o.backed);L.refreshControls();await L.draw();},override);await page.waitForFunction(()=>document.body.dataset.ready==='1');const file='office-'+id+'.png';await page.locator('#canvasB').screenshot({path:path.join(out,file)});captures.push({id,file,state:override});}
 await page.keyboard.press('Escape');await page.waitForFunction(()=>document.body.dataset.ready==='1');await page.screenshot({path:path.join(out,'office-desktop.png'),fullPage:true});await page.setViewportSize({width:320,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'office-320.png'),fullPage:true});assert.deepEqual(events.errors,[]);fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify({status:'PASS',url,origin:new URL(url).origin,proofManifestSha256,captures,fullPage:['office-desktop.png','office-320.png'],...events,approval:null},null,2)+'\n');console.log('CAPTURE PASS: 10 browser room states plus desktop/320px pages; real page errors 0.');
 }finally{await browser.close();}})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify({status:'FAIL',url,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
