// Focused software/art-contract validation, not owner or clinical approval.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const here=__dirname,root=path.dirname(here),repo=path.resolve(root,'../../../..'),out=path.join(here,'evidence');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),json=p=>JSON.parse(fs.readFileSync(p,'utf8'));
(async()=>{
 const {createCanvas,loadImage}=require('@napi-rs/canvas'),G=await import('./geometry.mjs'),D=await import('./design-rooms.js'),{loadNativeEngine}=await import('./native-engine.mjs');
 const room=D.DESIGN_ROOMS[0],nav=D.DESIGN_NAVIGATION[room.definitionId],data=json(path.join(here,'data.json')),layout=json(path.join(root,'layout.json')),manifest=json(path.join(here,'proof-manifest.json')),gen=json(path.join(root,'assets/generation-manifest.json'));
 assert.equal(manifest.approval,null);assert.equal(manifest.runtimeIntegrationAuthorized,false);assert.equal(manifest.mode,'painted');assert.deepEqual(room,layout.room);assert.deepEqual(nav.privateProofRouteModel,layout.presentation);assert.equal(manifest.layoutSha256,hash(path.join(root,'layout.json')));assert.equal(manifest.designRoomsSha256,hash(path.join(here,'design-rooms.js')));assert.equal(manifest.dataSha256,hash(path.join(here,'data.json')));assert.equal(manifest.generationManifestSha256,hash(path.join(root,'assets/generation-manifest.json')));
 assert.deepEqual(G.roomSegments(room),['N1','N2','N3','N4','S1','S2','S3','S4','WA','WB','WC','WD','EA','EB','EC','ED']);assert.equal(nav.doorThresholdExceptions.length,0);
 const html=fs.readFileSync(path.join(here,'index.html'),'utf8');assert.ok(html.includes('Proposed 4 × 4 base room'));assert.ok(html.includes('Owner review pending'));assert.ok(html.includes('Adult visitor in armchair'));assert.ok(!/Owner-approved|treatment chair|Wound\/Ostomy|leg rest removed/.test(html));
 let sourceHashes=0;const concurrentReferenceChanges=[];
 for(const r of json(path.join(root,'assets/reference-baseline.json')).references){const actual=hash(path.join(repo,r.path));if(actual!==r.sha256){if(/\/proof\/.*\.(?:mjs|js|cjs)$/.test(r.path))concurrentReferenceChanges.push({path:r.path,intakeSha256:r.sha256,currentSha256:actual});else assert.equal(actual,r.sha256,'Preserved shared art/still '+r.path);}sourceHashes++;}
 async function pixels(p){const im=await loadImage(p),c=createCanvas(im.width,im.height),g=c.getContext('2d');g.drawImage(im,0,0);return{im,c,p:g.getImageData(0,0,c.width,c.height).data};}
 let assets=0;const assetChecks=[];
 for(const a of gen.assets){
  assert.equal(a.tool,'image_gen.imagegen');assert.equal(a.transparentBackground,true);assert.equal(hash(path.join(root,a.original)),a.originalSha256);assert.equal(hash(path.join(root,a.prompt)),a.promptSha256);
  for(const v of a.rejectedVersions??[]){assert.equal(hash(path.join(root,v.original)),v.originalSha256);assert.equal(hash(path.join(root,v.prompt)),v.promptSha256);}
  const m=D.PREPARED_METADATA.assets[a.id],p=path.resolve(here,m.file),d=await pixels(p);assert.deepEqual([d.im.width,d.im.height],m.canvas);assert.equal(hash(p),m.outputSha256);assert.equal(m.sourceSha256,a.originalSha256);assert.equal(m.promptSha256,a.promptSha256);assert.equal(m.aspectPreserved,true);assert.equal(m.sourceUpscaled,false);assert.ok(m.transform.scale<=1);
  let edge=0,zero=0,top=d.im.height,bottom=-1;for(let y=0;y<d.im.height;y++)for(let x=0;x<d.im.width;x++){const alpha=d.p[(y*d.im.width+x)*4+3];if(!alpha)zero++;else top=Math.min(top,y);if(alpha>=160)bottom=y;if(!x||!y||x===d.im.width-1||y===d.im.height-1)edge=Math.max(edge,alpha);}
  assert.equal(edge,0,'Clear alpha edge '+a.id);assert.ok(zero>200);assert.equal(m.canvasAnchor[1],m.anchorKind==='floor'?bottom+1:top);assert.ok(Math.min(m.outputAllAlphaBounds.left,m.outputAllAlphaBounds.top,d.im.width-1-m.outputAllAlphaBounds.right,d.im.height-1-m.outputAllAlphaBounds.bottom)>=4);assetChecks.push({id:a.id,canvas:m.canvas,sha256:m.outputSha256,alphaEdge:edge,transparentPixels:zero,anchor:m.canvasAnchor});assets++;
 }
 const worktop=D.PREPARED_METADATA.assets['founder-desk'].measuredWorktopRisePixels;assert.ok(Math.abs(worktop-80)<1,'Actual leading worktop registration');
 const reused=json(path.join(root,'assets/reused/contract.json'));for(const r of Object.values(reused))assert.equal(hash(path.join(root,'assets/reused',r.file)),r.sha256);
 // Cropped guest chair and both front masks contain the exact approved source pixels.
 const originalGuest=await pixels(path.join(repo,'apps/player/public/art/rooms/gs015-v1/waiting/south.webp')),guest=await pixels(path.join(root,'assets/reused/visitor-chair.png'));
 for(let y=0;y<369;y++)for(let x=0;x<315;x++)assert.deepEqual(guest.p.subarray((y*315+x)*4,(y*315+x)*4+4),originalGuest.p.subarray(((y+748)*originalGuest.im.width+x+8)*4,((y+748)*originalGuest.im.width+x+8)*4+4));
 const chair=await pixels(path.join(root,'assets/reused/founder-chair.webp')),front=await pixels(path.join(root,'assets/reused/founder-chair-front.png'));for(let y=0;y<465;y++)for(let x=0;x<412;x++){const i=(y*412+x)*4;if(y<296)assert.equal(front.p[i+3],0);else assert.deepEqual(front.p.subarray(i,i+4),chair.p.subarray(i,i+4));}
 // All independent backing states and every single door, plus all-doors state.
 const doors=G.roomSegments(room),north=doors.filter(s=>s[0]==='N');let states=0,routes=0,samples=0;
 for(let mask=0;mask<16;mask++)for(const open of [[],...doors.map(s=>[s]),doors]){
  const backed=north.filter((_,i)=>mask&(1<<i)),P={room,doors:new Set(open),backed:new Set(backed)},result=G.check(room,nav,open,backed,data.previewBaseClearances);assert.deepEqual(result.unreachable,[]);assert.deepEqual(result.conflicts,[]);assert.deepEqual(result.doorZone,[]);states++;routes+=result.routes;
  const blockers=G.fineBlockers(P,nav,data.previewBaseClearances);for(const r of G.computeRoutes(P,nav,data.previewBaseClearances))for(let i=1;i<r.walkingPath.length;i++){const a=r.walkingPath[i-1],b=r.walkingPath[i],n=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/.005));for(let k=0;k<=n;k++){assert.equal(G.clearPoint(P,blockers,a[0]+(b[0]-a[0])*k/n,a[1]+(b[1]-a[1])*k/n),true);samples++;}}
 }
 // Four obstruction states exhaust optional floor furniture visibility. Every door
 // must have a safe route with all OTHER optional furniture still present. Opening
 // more doors/removing owned furniture cannot invalidate that fixed safe route.
 let monotonicChecks=0;for(const d of doors){const P={room,doors:new Set([d]),backed:new Set()},blockers=G.fineBlockers(P,nav,data.previewBaseClearances);for(const other of doors){const Q={...P,doors:new Set([d,other])};assert.ok(G.fineBlockers(Q,nav,data.previewBaseClearances).every(b=>blockers.some(c=>c.id===b.id)));monotonicChecks++;}}
 const {engine,warnings}=await loadNativeEngine(),P={room,doors:new Set(),backed:new Set(),ox:0,oy:0},collected=await engine.collectDrawables(P,true),sorted=[...collected.sorted].sort((a,b)=>a.py-b.py),index=(id,kind)=>sorted.findIndex(d=>d.id===id&&d.kind===kind);
 const layers=[];for(const id of ['founderChair','visitorChair']){assert.ok(index(id,'fixture')<index(id,'actor'));assert.ok(index(id,'actor')<index(id+':front','fixture'));const original=sorted.find(d=>d.id===id&&d.kind==='fixture'),mask=sorted.find(d=>d.id===id+':front'),actor=sorted.find(d=>d.id===id&&d.kind==='actor');for(const k of ['x','y','w','h'])assert.equal(original[k],mask[k]);const a=createCanvas(480,480),ag=a.getContext('2d');await engine.drawImageRec(ag,actor);const ap=ag.getImageData(0,0,480,480).data;ag.clearRect(0,0,480,480);await engine.drawImageRec(ag,mask);const mp=ag.getImageData(0,0,480,480).data;let overlap=0;for(let i=3;i<ap.length;i+=4)if(ap[i]>=250&&mp[i]>=250)overlap++;assert.ok(overlap>=20,'Real foreground overlap '+id);layers.push({id,opaqueForegroundOverlap:overlap,order:'chair → real adult → front mask'});}
 assert.ok(index('founderChair','actor')<index('desk','fixture'));const backed=await engine.collectDrawables({...P,backed:new Set(north)},true);for(const id of ['bookcase','plant']){const a=[...collected.wall,...collected.sorted].find(d=>d.id===id),b=[...backed.wall,...backed.sorted].find(d=>d.id===id);for(const k of ['x','y','w','h'])assert.equal(a[k],b[k]);assert.equal(b.clipTop,undefined);}
 for(const fit of data.founderPresentation.actors){const c=data.characters.find(c=>c.id===fit.characterId),p=c.poses.sit[fit.direction];assert.equal(hash(path.join(repo,'apps/player/public',p.url)),p.sha256);const actor=engine.actorPlacements(P).find(a=>a.id===fit.supportId);assert.ok(Math.abs(actor.x+fit.seatContactSource[0]*fit.sourceScale-fit.seat[0]*120)<1e-8);assert.ok(Math.abs(actor.y+fit.seatContactSource[1]*fit.sourceScale-fit.seat[1]*120)<1e-8);}
 let textFiles=0;for(const file of walk(root)){if(/\.(?:md|json|js|mjs|cjs|html|txt)$/.test(file)){const b=fs.readFileSync(file);assert.ok(!(b[0]===239&&b[1]===187&&b[2]===191),'No UTF-8 BOM '+file);new TextDecoder('utf-8',{fatal:true}).decode(b);textFiles++;}}assert.deepEqual(warnings,[]);
 const report={status:'PASS',approval:null,runtimeIntegrationAuthorized:false,footprint:[4,4],states,routes,radiusClearSamples:samples,sampleSpacingTiles:.005,actorRadiusTiles:.18,doorSections:16,backingSections:4,arbitraryDoorCombinationProof:'Each single-door route is safe with every other optional object present; additional doors only remove obstacles. Backing changes no floor obstacle.',monotonicChecks,assets,assetChecks,worktopRisePixels:worktop,reusedLayers:4,layers,realIdentities:data.characters.map(c=>c.id),sourceHashes,concurrentReferenceChanges,textFiles,warnings,browserQA:'pending manager',sourceManifestSha256:hash(path.join(here,'proof-manifest.json'))};fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'validation-report.json'),JSON.stringify(report,null,2)+'\n');console.log('VALIDATION PASS: '+assets+' painted assets; 4 approved chair layers; 2 real stills; '+states+' door/backing states; '+routes+' routes; '+samples+' radius-clear samples at 0.005T; 16 one-tile doors; no pass-through exceptions; contacts/layers/alpha/hashes/UTF-8 checked.');
 function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)]);}
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'validation-report.json'),JSON.stringify({status:'FAIL',error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
