// Manager browser QA. No gameplay, campaign storage or live game page is opened.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('@playwright/test'),{listen}=require('./browser-errors.cjs');
const here=__dirname,out=path.join(here,'evidence'),url=process.env.FOUNDER_OFFICE_PROOF_URL||'http://127.0.0.1:4191/tools/room-design/level-5/founders-office/proof/index.html';
const doorLabels=['N1','N2','N3','N4','S1','S2','S3','S4','WA','WB','WC','WD','EA','EB','EC','ED'],north=['N1','N2','N3','N4'];
(async()=>{
 const bytes=fs.readFileSync(path.join(here,'proof-manifest.json')),manifest=JSON.parse(bytes),proofManifestSha256=crypto.createHash('sha256').update(bytes).digest('hex');assert.equal(manifest.approval,null);assert.equal(manifest.mode,'painted');assert.deepEqual(manifest.doorModel,{count:16,perWall:4,spanTiles:1,kind:'game-one-tile'});fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1100}}),events=listen(page),checks=[];const response=await page.goto(url);assert.equal(response.status(),200);const ready=()=>page.waitForFunction(()=>document.body.dataset.ready==='1');await ready();
  const servedHash=await page.evaluate(async()=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await(await fetch('./proof-manifest.json')).arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join(''));assert.equal(servedHash,proofManifestSha256);
  const inspect=()=>page.evaluate(()=>{const L=window.__lab,room=L.rooms.get('founders-office'),P={room,doors:L.state.doors,backed:L.state.backed,ox:0,oy:0};return{origin:location.origin,state:{...L.state,doors:[...L.state.doors],backed:[...L.state.backed]},visible:room.records.filter(r=>L.recordVisible(r,P)).map(r=>r.id),actors:L.state.actors?L.actorPlacements(P).map(a=>({id:a.id,characterId:a.characterId,direction:a.direction})):[],check:L.check('founders-office',[...L.state.doors],[...L.state.backed]),overflow:document.documentElement.scrollWidth>innerWidth};});
  const initial=await inspect();assert.equal(initial.origin,new URL(url).origin);assert.deepEqual(initial.actors,[{id:'founderChair',characterId:'founder.01',direction:'south'},{id:'visitorChair',characterId:'patient.adult.007',direction:'west'}]);assert.equal(await page.locator('#doorGrid button').count(),16);assert.equal(await page.locator('#backedChips button').count(),4);assert.deepEqual((await page.locator('#doorGrid button').allTextContents()).sort(),doorLabels.slice().sort());checks.push('actual two existing stills and 16 one-tile door controls');
  const technical=await page.evaluate(async()=>{
   const L=window.__lab,room=L.rooms.get('founders-office'),segments=L.roomSegments(room),north=['N1','N2','N3','N4'],failures=[];let states=0,routes=0;
   for(let mask=0;mask<16;mask++)for(const doors of[[],...segments.map(s=>[s]),segments]){const c=L.check('founders-office',doors,north.filter((_,i)=>mask&(1<<i)));states++;routes+=c.routes;if(c.unreachable.length||c.conflicts.length||c.doorZone.length)failures.push({doors,mask,c});}
   const assets=[];for(const [id,s]of Object.entries(L.assets).filter(([,s])=>s.prepared)){const m=L.metadata.assets[s.preparedId],im=new Image();im.src=s.src;await im.decode();if(im.naturalWidth!==m.canvas[0]||im.naturalHeight!==m.canvas[1])failures.push('Native size '+id);const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const p=g.getImageData(0,0,c.width,c.height).data;let edge=0,zero=0,top=c.height,bottom=-1;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const a=p[(y*c.width+x)*4+3];if(a)top=Math.min(top,y);else zero++;if(a>=160)bottom=y;if(!x||!y||x===c.width-1||y===c.height-1)edge=Math.max(edge,a);}if(edge||!zero||m.canvasAnchor[1]!==(m.anchorKind==='floor'?bottom+1:top))failures.push('Alpha/anchor '+id);assets.push(id);}
   const P={room,doors:new Set(),backed:new Set(),ox:0,oy:0},a=await L.collectDrawables(P,true),b=await L.collectDrawables({...P,backed:new Set(north)},true),sorted=[...a.sorted].sort((a,b)=>a.py-b.py),index=(id,kind)=>sorted.findIndex(d=>d.id===id&&d.kind===kind),overlaps=[];
   for(const id of['founderChair','visitorChair']){const actor=sorted.find(d=>d.id===id&&d.kind==='actor'),front=sorted.find(d=>d.id===id+':front'),chair=sorted.find(d=>d.id===id&&d.kind==='fixture');if(!(index(id,'fixture')<index(id,'actor')&&index(id,'actor')<index(id+':front','fixture')))failures.push('Adult/chair front order '+id);if(['x','y','w','h'].some(k=>chair[k]!==front[k]))failures.push('Chair front registration '+id);const c=document.createElement('canvas');c.width=c.height=480;const g=c.getContext('2d',{willReadFrequently:true});await L.drawImageRec(g,actor);const ap=g.getImageData(0,0,480,480).data;g.clearRect(0,0,480,480);await L.drawImageRec(g,front);const fp=g.getImageData(0,0,480,480).data;let n=0;for(let i=3;i<ap.length;i+=4)if(ap[i]>=250&&fp[i]>=250)n++;if(n<20)failures.push('Missing real opaque armrest overlap '+id);overlaps.push({id,pixels:n});}
   if(!(index('founderChair','actor')<index('desk','fixture')))failures.push('Founder behind desk');for(const id of['bookcase','plant']){const x=[...a.wall,...a.sorted].find(d=>d.id===id),y=[...b.wall,...b.sorted].find(d=>d.id===id);if(!x||!y||['x','y','w','h'].some(k=>x[k]!==y[k])||y.clipTop!==undefined)failures.push('Full-height backing '+id);}
   return{states,routes,assets,overlaps,failures};
  });assert.deepEqual(technical.failures,[]);assert.equal(technical.states,288);assert.equal(technical.routes,1536);assert.equal(technical.assets.length,4);checks.push('288 geometry states, decoded native alpha/anchors, actual armrest overlaps, Founder behind desk and full-height north furniture');
  const hide={bookcase:['N1','WA'],plant:['N4','EA'],print:['N2']};for(const s of doorLabels){const button=()=>page.locator('#doorGrid button').filter({hasText:new RegExp('^'+s+'$')});await button().click();await ready();const c=await inspect();assert.deepEqual(c.state.doors,[s]);assert.equal(await button().getAttribute('aria-pressed'),'true');assert.equal(c.check.unreachable.length+c.check.conflicts.length+c.check.doorZone.length,0);for(const [id,owners]of Object.entries(hide))assert.equal(c.visible.includes(id),!owners.includes(s));await button().click();await ready();assert.deepEqual((await inspect()).visible,initial.visible);}checks.push('every independent door, own-section hiding and exact restoration');
  for(const [id,key,count]of[['allDoors','doors',16],['allDoors','doors',16],['closeDoors','doors',0],['allBacked','backed',4],['allBacked','backed',4],['clearBacked','backed',0]]){await page.click('#'+id);await ready();assert.equal((await inspect()).state[key].length,count);}checks.push('bulk controls, idempotence and backing restoration');
  for(const s of north){await page.locator('#backedChips button').filter({hasText:new RegExp('^'+s+'$')}).click();await ready();const c=await inspect();assert.ok(c.visible.includes('bookcase')&&c.visible.includes('plant'));}assert.ok(!(await inspect()).visible.includes('print'));await page.click('#clearBacked');await ready();checks.push('independent backing sections, wall art hides and floor art remains');
  for(const[id,count]of[['tgVisitor',1],['tgFounder',1],['tgActors',0]]){await page.uncheck('#'+id);await ready();assert.equal((await inspect()).actors.length,count);await page.check('#'+id);await ready();assert.equal((await inspect()).actors.length,2);}checks.push('individual/all occupancy');
  await page.locator('h1').click();for(const[key,state]of[['g','grid'],['r','routes'],['a','actors'],['p','visitors'],['v','founders'],['c','contacts'],['f','bases']]){const before=(await inspect()).state[state];await page.keyboard.press(key);await ready();assert.equal((await inspect()).state[state],!before);await page.keyboard.press(key);await ready();assert.equal((await inspect()).state[state],before);}await page.keyboard.press('d');await ready();assert.equal((await inspect()).state.doors.length,16);await page.keyboard.press('b');await ready();assert.equal((await inspect()).state.backed.length,4);await page.keyboard.press('Escape');await ready();assert.equal((await inspect()).state.doors.length,0);assert.equal((await inspect()).state.backed.length,0);
  await page.locator('#allDoors').focus();await page.keyboard.press('Space');await ready();assert.equal((await inspect()).state.doors.length,16);await page.locator('#closeDoors').focus();await page.keyboard.press('Enter');await ready();assert.equal((await inspect()).state.doors.length,0);checks.push('keyboard toggles, reset, Space/Enter activation');
  await page.setViewportSize({width:320,height:900});await ready();assert.equal((await inspect()).overflow,false);assert.ok(await page.locator('#canvasB').isVisible());checks.push('320px layout with no horizontal overflow');assert.deepEqual(events.errors,[]);
  fs.writeFileSync(path.join(out,'browser-validation-report.json'),JSON.stringify({status:'PASS',url,origin:initial.origin,proofManifestSha256,checks,technical,...events,approval:null,runtimeIntegrationAuthorized:false},null,2)+'\n');console.log('BROWSER VALIDATION PASS: '+checks.length+' groups; 16 doors; 288 states / 1536 routes; two real seated adults behind chair fronts; keyboard; 320px; real page errors 0.');
 }finally{await browser.close();}
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'browser-validation-report.json'),JSON.stringify({status:'FAIL',url,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
