(()=>{
  const root=document.getElementById('waiting-layout-proof'),art=root.querySelector('#waiting-art'),ctx=art.getContext('2d'),wrap=root.querySelector('.waiting-art-wrap'),targets=root.querySelector('#waiting-targets'),status=root.querySelector('#waiting-status'),orientation=root.querySelector('#waiting-orientation'),optional=root.querySelector('#waiting-optional'),footprints=root.querySelector('#waiting-footprints'),routeSelect=root.querySelector('#waiting-route'),progress=root.querySelector('#waiting-progress'),play=root.querySelector('#waiting-play');
  const S=120,scale=2,radius=.16,step=.04,C={bg:'#f3ead3',cream:'#efe1bd',sage:'#58735a',light:'#789173',dark:'#294632',wood:'#744a29',woodLight:'#b07a43',carpet:'#baa88e',neighbor:'#cbd5ce'};
  const originalAtlas=new Image(),westAtlas=new Image(),actorAtlas=new Image();originalAtlas.src='data:image/webp;base64,__ORIGINAL_ATLAS__';westAtlas.src='data:image/webp;base64,__WEST_ATLAS__';actorAtlas.src='data:image/webp;base64,__ACTOR_ASSET__';
  const originalCrops={bench:{x:8,y:8,w:545,h:356,foot:349},chairEast:{x:8,y:372,w:311,h:368,foot:360},chairWest:{x:8,y:748,w:315,h:369,foot:362},table:{x:8,y:1125,w:551,h:260,foot:252},rack:{x:8,y:1393,w:495,h:247},plant:{x:8,y:1648,w:286,h:328}},westCrops={benchE:{x:8,y:8,w:417,h:1088,foot:1079},chairN:{x:8,y:1104,w:364,h:336,foot:327},chairS:{x:8,y:1448,w:385,h:451,foot:440},tableV:{x:8,y:1907,w:305,h:523,foot:513}},actorCrops={frontA:{x:0,y:0,w:128,h:192},frontB:{x:128,y:0,w:128,h:192},backA:{x:0,y:192,w:128,h:192},backB:{x:128,y:192,w:128,h:192},leftA:{x:0,y:384,w:128,h:192},leftB:{x:128,y:384,w:128,h:192},rightA:{x:0,y:576,w:128,h:192},rightB:{x:128,y:576,w:128,h:192}};
  const localSegments=['N1','N2','N3','N4','S1','S2','S3','S4','WA','WB','WC','EA','EB','EC'],state={orientation:0,open:new Set(['S2']),adjacency:{0:new Set(),90:new Set()},optional:true,route:'behind',progress:35,playing:false,animation:0},routeCache=new Map(),reachCache=new Map(),reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const contracts={bench:{anchor:{x:2,y:.95},footprint:{left:1.05,top:.55,width:1.90,height:.40},seats:[{x:1.55,y:.88},{x:2.45,y:.88}],facing:'south',approach:{x:2,y:1.20},collision:'solid',persistence:'permanent'},leftChair:{anchor:{x:.70,y:1.95},footprint:{left:.42,top:1.45,width:.56,height:.50},seats:[{x:.70,y:1.72}],facing:'east',approach:{x:1.12,y:1.72},collision:'solid',persistence:'permanent'},rightChair:{anchor:{x:3.30,y:1.95},footprint:{left:3.02,top:1.45,width:.56,height:.50},seats:[{x:3.30,y:1.72}],facing:'west',approach:{x:2.88,y:1.72},collision:'solid',persistence:'permanent'},table:{anchor:{x:2,y:2.08},footprint:{left:1.35,top:1.48,width:1.30,height:.60},collision:'solid',persistence:'optional'},magazineRack:{anchor:{x:.36,y:0},mount:'N1',collision:'none',persistence:'optional'},plant:{anchor:{x:3.63,y:.72},footprint:{left:3.41,top:.26,width:.44,height:.44},collision:'none',persistence:'optional'}};
  const routes={behind:{label:'Behind bench',start:{x:.55,y:.22},end:{x:3.45,y:.22}},chairs:{label:'Around side chairs',start:{x:.22,y:1.50},end:{x:3.78,y:1.50}},south:{label:'South aisle',start:{x:.45,y:2.72},end:{x:3.55,y:2.72}}};
  const rotPoint=p=>({x:p.y,y:4-p.x}),rotRect=q=>({left:q.top,top:4-q.left-q.width,width:q.height,height:q.width}),rotDirection=d=>({north:'west',west:'south',south:'east',east:'north'}[d]),rotMotion=d=>({back:'left',left:'front',front:'right',right:'back'}[d]);
  function localToWorld(id){if(!state.orientation)return id;if(id[0]==='N')return `W${'DCBA'[+id[1]-1]}`;if(id[0]==='S')return `E${'DCBA'[+id[1]-1]}`;if(id[0]==='W')return `S${'ABC'.indexOf(id[1])+1}`;return `N${'ABC'.indexOf(id[1])+1}`}
  function worldToLocal(id){for(const local of localSegments)if(localToWorld(local)===id)return local;return null}
  function dims(){return state.orientation?{cols:3,rows:4,x:180,y:230,w:720,h:778}:{cols:4,rows:3,x:120,y:230,w:720,h:658}}
  function worldRect(rect){return state.orientation?rotRect(rect):{...rect}}
  function worldPoint(point){return state.orientation?rotPoint(point):{...point}}
  function worldFacing(facing){return state.orientation?rotDirection(facing):facing}
  function solidRects(){return ['bench','leftChair','rightChair',...(state.optional?['table']:[])].map(id=>({id,...contracts[id].footprint}))}
  function inflated(rect){return{left:rect.left-radius,top:rect.top-radius,right:rect.left+rect.width+radius,bottom:rect.top+rect.height+radius}}
  function validPoint(p){if(p.x<radius-1e-6||p.x>4-radius+1e-6||p.y<radius-1e-6||p.y>3-radius+1e-6)return false;return !solidRects().some(rect=>{const q=inflated(rect);return p.x>=q.left&&p.x<=q.right&&p.y>=q.top&&p.y<=q.bottom})}
  function bfs(start,end){const cols=Math.round((4-2*radius)/step),rows=Math.round((3-2*radius)/step),key=(x,y)=>`${x},${y}`,point=(x,y)=>({x:radius+x*step,y:radius+y*step}),grid=p=>({x:Math.round((p.x-radius)/step),y:Math.round((p.y-radius)/step)}),a=grid(start),b=grid(end),queue=[a],previous=new Map([[key(a.x,a.y),null]]);for(let qi=0;qi<queue.length;qi++){const u=queue[qi];if(u.x===b.x&&u.y===b.y)break;for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const v={x:u.x+dx,y:u.y+dy},k=key(v.x,v.y);if(v.x<0||v.x>cols||v.y<0||v.y>rows||previous.has(k)||!validPoint(point(v.x,v.y)))continue;previous.set(k,u);queue.push(v)}}const last=key(b.x,b.y);if(!previous.has(last))return[];const raw=[];for(let u=b;u;u=previous.get(key(u.x,u.y)))raw.push(point(u.x,u.y));raw.reverse();return raw.filter((p,i)=>{if(i===0||i===raw.length-1)return true;const before=raw[i-1],after=raw[i+1];return Math.sign(p.x-before.x)!==Math.sign(after.x-p.x)||Math.sign(p.y-before.y)!==Math.sign(after.y-p.y)})}
  function doorPoint(id){if(id[0]==='N')return{x:+id.slice(1)-.5,y:radius};if(id[0]==='S')return{x:+id.slice(1)-.5,y:3-radius};const row='ABC'.indexOf(id[1]);return{x:id[0]==='W'?radius:4-radius,y:row+.5}}
  function reachability(){const key=state.optional?'with-table':'without-table';if(!reachCache.has(key)){const origin=doorPoint('S2'),blocked=[];for(const id of localSegments)if(!bfs(origin,doorPoint(id)).length)blocked.push(id);reachCache.set(key,{reachable:14-blocked.length,blocked})}const result=reachCache.get(key);return{reachable:result.reachable,blocked:result.blocked.map(localToWorld)}}
  function currentPath(){const key=`${state.optional?'with':'without'}:${state.route}`;if(!routeCache.has(key)){const def=routes[state.route];routeCache.set(key,bfs(def.start,def.end))}return routeCache.get(key)}
  function samplePath(path,t){if(!path.length)return null;if(path.length===1)return{point:path[0],direction:'front'};const lengths=[],total=path.slice(1).reduce((sum,p,i)=>{const a=path[i],len=Math.hypot(p.x-a.x,p.y-a.y);lengths.push(len);return sum+len},0);let target=Math.max(0,Math.min(1,t))*total,index=0;while(index<lengths.length-1&&target>lengths[index])target-=lengths[index++];const a=path[index],b=path[index+1],q=lengths[index]?target/lengths[index]:0,point={x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q},dx=b.x-a.x,dy=b.y-a.y,direction=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'front':'back');return{point,direction}}
  function carpetRect(rx,ry,w,h){ctx.fillStyle=C.carpet;ctx.fillRect(rx,ry,w,h);for(let py=Math.floor(ry);py<ry+h;py+=3)for(let px=Math.floor(rx);px<rx+w;px+=3){const seed=((px*37+py*19)%29+29)%29;if(seed===0||seed===7){ctx.fillStyle=seed?'rgba(91,70,49,.07)':'rgba(255,245,224,.08)';ctx.fillRect(px,py,1,1)}}}
  function neighborRect(rx,ry,w,h){ctx.fillStyle=C.neighbor;ctx.fillRect(rx,ry,w,h);ctx.fillStyle='rgba(54,83,74,.055)';for(let py=Math.floor(ry)+2;py<ry+h;py+=7)for(let px=Math.floor(rx)+3;px<rx+w;px+=11)if((px+py)%5===0)ctx.fillRect(px,py,1,1)}
  function shellGeometry(){const d=dims();return{...d,east:d.x+d.cols*S,bottom:d.y+d.rows*S,westCapX:d.x-12,eastCapX:d.x+d.cols*S-2}}
  function worldSegments(){const d=dims(),ids=[];for(let i=1;i<=d.cols;i++)ids.push(`N${i}`);for(let i=1;i<=d.cols;i++)ids.push(`S${i}`);for(let i=0;i<d.rows;i++)ids.push(`W${'ABCD'[i]}`);for(let i=0;i<d.rows;i++)ids.push(`E${'ABCD'[i]}`);return ids}
  function slot(worldId){const g=shellGeometry(),adj=state.adjacency[state.orientation].has(worldId);if(worldId[0]==='N'||worldId[0]==='S'){const i=+worldId.slice(1)-1;return{x:g.x+i*S,y:worldId[0]==='N'?(adj?g.y-29:g.y-90):g.bottom-6,w:S,h:worldId[0]==='N'?(adj?29:90):35}}const row='ABCD'.indexOf(worldId[1]);return{x:worldId[0]==='W'?g.westCapX:g.eastCapX,y:g.y+row*S,w:14,h:S}}
  function drawShell(){const g=shellGeometry(),adj=state.adjacency[state.orientation];carpetRect(g.x,g.y,g.cols*S,g.rows*S);ctx.fillStyle='rgba(92,70,50,.035)';for(let py=g.y+8;py<g.bottom;py+=18)for(let px=g.x+11;px<g.east;px+=21)if(((px*13+py*7)>>2)%4===0)ctx.fillRect(px,py,2,1);for(let i=0;i<g.cols;i++){const sx=g.x+i*S,id=`N${i+1}`,low=adj.has(id);if(low){neighborRect(sx,g.y-71,S,42);ctx.fillStyle=C.sage;ctx.fillRect(sx,g.y-29,S,29);ctx.fillStyle=C.dark;ctx.fillRect(sx,g.y-29,S,8);ctx.fillStyle=C.light;ctx.fillRect(sx,g.y-29,S,3)}else{ctx.fillStyle=C.cream;ctx.fillRect(sx,g.y-90,S,90);ctx.fillStyle='rgba(146,110,67,.05)';ctx.fillRect(sx+13,g.y-61,S-26,2);ctx.fillRect(sx+21,g.y-33,S-42,2);ctx.fillStyle=C.sage;ctx.fillRect(sx,g.y-24,S,24);ctx.fillStyle=C.light;ctx.fillRect(sx,g.y-24,S,4);ctx.fillStyle=C.dark;ctx.fillRect(sx,g.y-7,S,7);ctx.fillRect(sx-1,g.y-99,S+2,9);ctx.fillStyle=C.light;ctx.fillRect(sx-1,g.y-99,S+2,3)}}const side=(right)=>{const capX=right?g.eastCapX:g.westCapX,neighbor=right?`N${g.cols}`:'N1',top=adj.has(neighbor)?g.y-29:g.y-99;ctx.fillStyle=C.dark;ctx.fillRect(capX,top,14,g.bottom+29-top);ctx.fillStyle=C.light;ctx.fillRect(capX+(right?0:11),top,3,g.bottom+29-top)};side(false);side(true);for(let i=0;i<g.cols;i++){const sx=g.x+i*S;ctx.fillStyle=C.cream;ctx.fillRect(sx,g.bottom,S,29);ctx.fillStyle=C.sage;ctx.fillRect(sx,g.bottom+21,S,8);ctx.fillStyle=C.dark;ctx.fillRect(sx,g.bottom-6,S,8);ctx.fillStyle=C.light;ctx.fillRect(sx,g.bottom-6,S,3)}for(const localId of state.open){const id=localToWorld(localId),q=slot(id);if(id[0]==='N'){const i=+id.slice(1)-1,low=adj.has(id),left=g.x+i*S+12,right=g.x+(i+1)*S-12,top=low?g.y-29:g.y-82;ctx.clearRect(left,top,right-left,g.y-top);neighborRect(left,top,right-left,g.y-top);ctx.fillStyle=C.wood;ctx.fillRect(left-5,top,5,g.y-top);ctx.fillRect(right,top,5,g.y-top);if(!low){ctx.fillRect(left-5,top-5,right-left+10,6);ctx.fillStyle=C.woodLight;ctx.fillRect(left+2,g.y-4,right-left-4,4)}}else if(id[0]==='S'){const i=+id.slice(1)-1,left=g.x+i*S+12,right=g.x+(i+1)*S-12;ctx.clearRect(left,g.bottom-6,right-left,35);carpetRect(left,g.bottom-6,right-left,35);ctx.fillStyle=C.wood;ctx.fillRect(left-5,g.bottom-6,5,35);ctx.fillRect(right,g.bottom-6,5,35)}else{const right=id[0]==='E',capX=right?g.eastCapX:g.westCapX,row='ABCD'.indexOf(id[1]),top=g.y+row*S+12,height=S-24;ctx.clearRect(capX,top,14,height);right?(carpetRect(capX,top,7,height),neighborRect(capX+7,top,7,height)):(neighborRect(capX,top,7,height),carpetRect(capX+7,top,7,height));ctx.fillStyle=C.wood;ctx.fillRect(capX-2,top-3,18,5);ctx.fillRect(capX-2,top+height-2,18,5)}}return g}
  function sprite(atlas,crop,left,base,width,footRow=crop.foot){const height=width*crop.h/crop.w,draw={x:left,y:base-height,width,height,base,aspect:crop.w/crop.h,contactY:footRow==null?base:base-height+footRow*(width/crop.w)};ctx.drawImage(atlas,crop.x,crop.y,crop.w,crop.h,draw.x,draw.y,draw.width,draw.height);return draw}
  function fixtureItems(g){const items=[],add=(id,depth,draw)=>items.push({id,depth,draw});if(!state.orientation){if(state.optional&&!state.open.has('N1')&&!state.adjacency[0].has('N1'))add('magazineRack',.05,()=>sprite(originalAtlas,originalCrops.rack,g.x+.03*S,g.y-.11*S,.81*S));if(state.optional&&!state.open.has('N4')&&!state.open.has('EA'))add('plant',.70,()=>sprite(originalAtlas,originalCrops.plant,g.x+3.34*S,g.y+.72*S,.58*S));add('bench',.95,()=>sprite(originalAtlas,originalCrops.bench,g.x+1.05*S,g.y+.974*S,1.90*S));add('leftChair',1.95,()=>sprite(originalAtlas,originalCrops.chairEast,g.x+.30*S,g.y+1.971*S,.80*S));add('rightChair',1.95,()=>sprite(originalAtlas,originalCrops.chairWest,g.x+2.90*S,g.y+1.968*S,.80*S));if(state.optional)add('table',2.08,()=>sprite(originalAtlas,originalCrops.table,g.x+1.275*S,g.y+2.101*S,1.45*S))}else{const b=worldRect(contracts.bench.footprint),l=worldRect(contracts.leftChair.footprint),r=worldRect(contracts.rightChair.footprint),t=worldRect(contracts.table.footprint),plant=worldRect(contracts.plant.footprint);if(state.optional&&!state.open.has('N4')&&!state.open.has('EA'))add('plant',plant.top+plant.height,()=>sprite(originalAtlas,originalCrops.plant,g.x+(plant.left-.07)*S,g.y+(plant.top+plant.height+.02)*S,.58*S));add('rightChair',r.top+r.height,()=>sprite(westAtlas,westCrops.chairS,g.x+(r.left+r.width/2-.40)*S,g.y+(r.top+r.height+.023)*S,.80*S));if(state.optional)add('table',t.top+t.height,()=>sprite(westAtlas,westCrops.tableV,g.x+(t.left+t.width/2-.41)*S,g.y+(t.top+t.height+.027)*S,.82*S));add('bench',b.top+b.height,()=>sprite(westAtlas,westCrops.benchE,g.x+(b.left+b.width/2-.42)*S,g.y+(b.top+b.height+.018)*S,.84*S));add('leftChair',l.top+l.height,()=>sprite(westAtlas,westCrops.chairN,g.x+(l.left+l.width/2-.40)*S,g.y+(l.top+l.height+.020)*S,.80*S))}return items}
  function actorItem(g,path){const sampled=samplePath(path,state.progress/100);if(!sampled)return null;const world=worldPoint(sampled.point),next=state.orientation?rotMotion(sampled.direction):sampled.direction,phase=state.playing&&Math.floor(state.progress/7)%2?'B':'A',crop=actorCrops[`${next}${phase}`],width=1.35*S,height=2.025*S,left=g.x+world.x*S-64*(width/128),top=g.y+world.y*S-181*(width/128);return{id:'actor',depth:world.y,point:world,direction:next,phase,draw:()=>{ctx.drawImage(actorAtlas,crop.x,crop.y,crop.w,crop.h,left,top,width,height);return{x:left,y:top,width,height,feet:{x:g.x+world.x*S,y:g.y+world.y*S}}}}}
  function drawOverlay(g,path){if(!footprints.checked)return;ctx.save();ctx.lineWidth=2;for(const rect of solidRects()){const q=worldRect(rect),inf=worldRect({left:rect.left-radius,top:rect.top-radius,width:rect.width+2*radius,height:rect.height+2*radius});ctx.fillStyle='rgba(159,69,62,.10)';ctx.fillRect(g.x+inf.left*S,g.y+inf.top*S,inf.width*S,inf.height*S);ctx.strokeStyle='rgba(133,51,45,.8)';ctx.strokeRect(g.x+q.left*S,g.y+q.top*S,q.width*S,q.height*S)}ctx.strokeStyle='#355e77';ctx.setLineDash([6,4]);ctx.beginPath();path.map(worldPoint).forEach((p,i)=>i?ctx.lineTo(g.x+p.x*S,g.y+p.y*S):ctx.moveTo(g.x+p.x*S,g.y+p.y*S));ctx.stroke();ctx.restore()}
  function render(){const d=dims();if(art.width!==d.w*scale||art.height!==d.h*scale){art.width=d.w*scale;art.height=d.h*scale}ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle=C.bg;ctx.fillRect(0,0,art.width,art.height);ctx.setTransform(scale,0,0,scale,0,0);const g=drawShell(),path=currentPath(),actor=actorItem(g,path),items=fixtureItems(g);if(actor)items.push(actor);items.sort((a,b)=>a.depth-b.depth);const draws={};for(const item of items)draws[item.id]=item.draw();drawOverlay(g,path);ctx.setTransform(1,0,0,1,0,0);const reach=reachability(),hidden=[];if(!state.optional)hidden.push('table','magazine rack','plant');else{if(state.orientation)hidden.push('magazine rack (west cutaway)');else if(state.open.has('N1')||state.adjacency[0].has('N1'))hidden.push('magazine rack');if(state.open.has('N4')||state.open.has('EA'))hidden.push('plant')}art.dataset.openings=[...state.open].map(localToWorld).join(',');art.dataset.adjacency=[...state.adjacency[state.orientation]].join(',');art.dataset.fixtures=JSON.stringify({contracts:Object.fromEntries(Object.entries(contracts).map(([id,c])=>[id,{...c,worldFootprint:c.footprint?worldRect(c.footprint):null,worldAnchor:c.anchor?worldPoint(c.anchor):null,worldGroundAnchor:c.anchor?worldPoint(c.anchor):null,worldSeats:c.seats?c.seats.map(worldPoint):[],worldApproach:c.approach?worldPoint(c.approach):null,worldFacing:c.facing?worldFacing(c.facing):null}])),draws,hidden,drawOrder:items.map(i=>i.id)});art.dataset.route=JSON.stringify({id:state.route,localPath:path,worldPath:path.map(worldPoint),actor:actor?{point:actor.point,direction:actor.direction,phase:actor.phase}:null,radius,step,reachable:reach.reachable,blocked:reach.blocked});art.dataset.surface=JSON.stringify({orientation:state.orientation,logicalCols:d.cols,logicalRows:d.rows,doorCount:14,northAdjacencySlots:d.cols,sideCapWidth:14,lowWallHeight:29,renderScale:scale,originalAtlas:[originalAtlas.naturalWidth,originalAtlas.naturalHeight],westAtlas:[westAtlas.naturalWidth,westAtlas.naturalHeight],actorAtlas:[actorAtlas.naturalWidth,actorAtlas.naturalHeight]});updateControls();status.innerHTML=`<strong>${routes[state.route].label}</strong> · ${reach.reachable}/14 door approaches reachable${reach.blocked.length?` · blocked: ${reach.blocked.join(', ')}`:''} · actor radius ${radius.toFixed(2)} tile · ${hidden.length?`hidden: ${hidden.join(', ')}`:'all selected furnishings visible'}`}
  function controlButton(localId,hit=false){const world=localToWorld(localId),button=document.createElement('button');button.type='button';button.className=hit?'waiting-hit':'btn';button.dataset.local=localId;button.dataset.segment=world;button.textContent=world;button.setAttribute('aria-label',hit?`Wall doorway ${world}`:`Toggle doorway ${world}`);button.onclick=()=>{state.open.has(localId)?state.open.delete(localId):state.open.add(localId);render();root.querySelector(`${hit?'.waiting-hit':'.btn'}[data-local="${localId}"]`)?.focus()};return button}
  function rebuildControls(){targets.replaceChildren();for(const id of ['#waiting-north','#waiting-south','#waiting-west','#waiting-east'])root.querySelector(id).replaceChildren();const groups={N:'#waiting-north',S:'#waiting-south',W:'#waiting-west',E:'#waiting-east'};for(const world of worldSegments()){const local=worldToLocal(world);root.querySelector(groups[world[0]]).append(controlButton(local));targets.append(controlButton(local,true))}const adjacency=root.querySelector('#waiting-adjacency');adjacency.replaceChildren();for(let i=1;i<=dims().cols;i++){const id=`N${i}`,label=document.createElement('label');label.className='form-check';label.innerHTML=`<input class="form-check-input" type="checkbox" data-adjacent="${id}"><span class="form-check-label">${id}</span>`;const input=label.querySelector('input');input.checked=state.adjacency[state.orientation].has(id);input.onchange=()=>{input.checked?state.adjacency[state.orientation].add(id):state.adjacency[state.orientation].delete(id);render()};adjacency.append(label)}}
  function updateControls(){for(const el of root.querySelectorAll('[data-local]')){const open=state.open.has(el.dataset.local);el.setAttribute('aria-pressed',String(open));el.classList.toggle('btn-primary',open);if(el.classList.contains('waiting-hit')){const q=slot(el.dataset.segment),d=dims();Object.assign(el.style,{left:`${(q.x-8)/d.w*100}%`,top:`${(q.y-8)/d.h*100}%`,width:`${(q.w+16)/d.w*100}%`,height:`${(q.h+16)/d.h*100}%`})}}}
  function playOnce(){cancelAnimationFrame(state.animation);if(reducedMotion){state.progress=100;progress.value='100';state.playing=false;render();return}state.playing=true;const start=performance.now();const frame=now=>{state.progress=Math.min(100,(now-start)/28);progress.value=String(state.progress);render();if(state.progress<100)state.animation=requestAnimationFrame(frame);else{state.playing=false;render()}};state.animation=requestAnimationFrame(frame)}
  orientation.onchange=()=>{state.orientation=+orientation.value;rebuildControls();render()};optional.onchange=()=>{state.optional=optional.checked;render()};footprints.onchange=render;routeSelect.onchange=()=>{state.route=routeSelect.value;state.progress=0;progress.value='0';render()};progress.oninput=()=>{state.progress=+progress.value;state.playing=false;cancelAnimationFrame(state.animation);render()};play.onclick=playOnce;
  rebuildControls();for(const image of [originalAtlas,westAtlas,actorAtlas])image.addEventListener('load',render);window.__waitingLayout={ready:()=>originalAtlas.complete&&originalAtlas.naturalWidth===567&&westAtlas.complete&&westAtlas.naturalWidth===433&&actorAtlas.complete&&actorAtlas.naturalWidth===256,state,contracts,localSegments,localToWorld,worldToLocal,rotPoint,rotRect,worldFacing,solidRects,validPoint,bfs,doorPoint,reachability,currentPath,reducedMotion,render};render();
})();
