import { expect, test } from "@playwright/test";
import { getRoomDefinition } from "@gamify-surgery/game-domain";
import { setFastFacilitySpeed, startClinic } from "./helpers";
import { clickFacilityTile, earnExamCash, finishProtectedVisits, protectedVisitIds, reloadTutorialCampaign, tutorialState } from "./tutorial-helpers";

test("a fresh player retains its paid, inaccessible exam and repairs it after a mid-build reload", async ({page}, testInfo) => {
  test.skip(testInfo.project.name !== "desktop-chrome", "Natural canvas and saved-room proof runs once at desktop width.");
  testInfo.setTimeout(300_000);
  const clinicName = "Fresh Examination Recovery Clinic";
  await startClinic(page, "Fresh Founder", clinicName);
  let state = await tutorialState(page);
  expect(state.rooms.map((room) => room.roomDefinitionId)).toEqual(["room.front_desk"]);
  expect(state.doors).toHaveLength(1);
  await setFastFacilitySpeed(page);
  const filed = await finishProtectedVisits(page, [true, true, true]);
  await earnExamCash(page);
  await page.getByRole("button", {name: "Enter Build Mode"}).click();
  await page.locator('[data-room-definition-id="room.examination"]').click();
  const before = await tutorialState(page);
  await clickFacilityTile(page, 34.5, 26.5);
  await expect.poll(async () => (await tutorialState(page)).rooms.filter((room) => room.roomDefinitionId === "room.examination").length).toBe(1);
  state = await tutorialState(page);
  expect(state.cash).toBe(before.cash - getRoomDefinition("room.examination")!.constructionCost);
  const exam = state.rooms.find((room) => room.roomDefinitionId === "room.examination")!;
  expect(state.doors.some((door) => door.roomId === exam.id)).toBe(false);
  await reloadTutorialCampaign(page, clinicName);
  const saved = await tutorialState(page);
  expect(saved.rooms.find((room) => room.id === exam.id)).toEqual(exam);
  expect(saved.cash).toBe(state.cash);
  expect(saved.paused).toBe(true);
  expect(protectedVisitIds.map((id) => saved.encounters[id]!.answers)).toEqual(protectedVisitIds.map((id) => filed.encounters[id]!.answers));
  await expect(page.locator(".tutorial-coach")).toHaveAttribute("data-tutorial-step", "place-exam-room-door");
  await page.getByRole("button", {name: "Enter Build Mode"}).click();
  await page.getByRole("button", {name: "Doors", exact: true}).click();
  await clickFacilityTile(page, 35.5, 28);
  await expect.poll(async () => (await tutorialState(page)).doors.some((door) => door.roomId === exam.id && !door.exterior)).toBe(true);
  await page.getByRole("button", {name: "Done / Save"}).click();
  await expect(page.locator(".tutorial-coach")).toHaveAttribute("data-tutorial-step", "advance-level");
  await reloadTutorialCampaign(page, clinicName);
  state = await tutorialState(page);
  expect(state.rooms.filter((room) => room.roomDefinitionId === "room.examination")).toHaveLength(1);
  expect(state.rooms.find((room) => room.id === exam.id)).toEqual(exam);
  expect(state.learningHistories).toEqual(filed.learningHistories);
  expect(state.doors.some((door) => door.roomId === exam.id && !door.exterior)).toBe(true);
});
