import type { ResearchWorkspace } from "../src/index.js";

export const sha = (character: string) => character.repeat(64);

export function makeResearchWorkspace(): ResearchWorkspace {
  return {
    schemaVersion: 1,
    id: "research.workspace.test",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-10T00:00:00.000Z",
    externalReferences: {
      sources: [{ id: "source.one" }, { id: "source.two" }],
      citations: [
        {
          id: "citation.one",
          sourceId: "source.one",
          sourceSnapshotId: "snapshot.one",
          verificationState: "human_verified",
          verifiedBy: "reviewer.clinical.one",
          verifiedAt: "2026-01-02T10:00:00.000Z",
        },
      ],
      clinicalTargets: [
        { kind: "structured_fact", id: "fact.one" },
        { kind: "clinical_topic_revision", id: "topic.rev.one" },
      ],
      clinicalApprovals: [
        {
          id: "approval.one",
          targetRevisionId: "topic.rev.one",
          reviewedAt: "2026-01-09T00:00:00.000Z",
        },
      ],
    },
    citationVerificationSignals: [
      {
        id: "citation-verification.citation.one.human.v1",
        citationId: "citation.one",
        supersedesSignalId: null,
        verificationState: "human_verified",
        verifiedBy: "reviewer.clinical.one",
        verifiedAt: "2026-01-02T10:00:00.000Z",
        recordedAt: "2026-01-02T10:00:00.000Z",
      },
    ],
    evidenceGaps: [
      {
        id: "gap.one",
        createdAt: "2026-01-01T01:00:00.000Z",
        createdBy: "author.one",
      },
    ],
    evidenceGapRevisions: [
      {
        revisionId: "gap.rev.one",
        gapId: "gap.one",
        supersedesRevisionId: null,
        title: "When is imaging indicated?",
        clinicalQuestion:
          "Which findings make imaging appropriate in this surgical presentation?",
        whyNeeded:
          "The clinical fact needs a current, claim-specific evidence basis.",
        targetContent: [{ kind: "structured_fact", id: "fact.one" }],
        acceptanceCriteria: [
          "Defines findings that alter the imaging recommendation.",
          "Separates routine from urgent evaluation.",
        ],
        scoutPolicy: {
          mode: "metadata_search",
          preferredSourceTypes: [
            "clinical_guideline",
            "systematic_review",
          ],
          preferredJurisdictions: ["United States"],
          preferredPopulations: ["Adults"],
          preferredSettings: ["Outpatient surgery"],
          providerStrategies: [
            {
              provider: "pubmed",
              query:
                "(surgical presentation[Title/Abstract]) AND imaging[Title/Abstract]",
              filters: ["English", "Humans"],
            },
          ],
          publicationYearFloor: 2020,
          includePreprints: false,
          maximumCandidates: 25,
          refreshIntervalDays: 30,
          requireHumanScreening: true,
          requireRightsDecisionBeforeFullText: true,
        },
        status: "awaiting_review",
        resolutionNote: null,
        recordedAt: "2026-01-02T00:00:00.000Z",
        recordedBy: "author.one",
        changeSummary: "Opened the initial evidence gap.",
      },
    ],
    sourceRelations: [
      {
        id: "relation.one",
        fromSourceId: "source.two",
        toSourceId: "source.one",
        relationType: "companion_to",
        relationStatus: "active",
        supersedesRelationId: null,
        note: "Source two accompanies source one without replacing it.",
        recordedAt: "2026-01-02T01:00:00.000Z",
        recordedBy: "reviewer.rights",
      },
    ],
    sourceRightsDecisions: [
      {
        id: "rights.source.one.default",
        sourceId: "source.one",
        supersedesDecisionId: null,
        decisionStatus: "default_deny",
        legalBasis: "unreviewed",
        permissions: {
          bibliographicMetadata: false,
          privateStorage: false,
          localTextExtraction: false,
          localStructuredIndexing: false,
          externalAiProcessing: false,
          derivedClinicalContent: false,
          projectParaphrasePublication: false,
          publicSourceTextReuse: false,
          runtimeRedistribution: false,
          commercialDistribution: false,
        },
        territories: ["Global"],
        licenseLabel: null,
        licenseUrl: null,
        termsUrl: null,
        attributionStatement: null,
        requiredNotices: [],
        nonCommercialOnly: false,
        shareAlikeRequired: false,
        thirdPartyMaterialPolicy: "not_applicable",
        fairUseAssessment: null,
        permissionEvidenceReferenceIds: [],
        reviewBasis: "engineering_risk_assessment",
        reviewedBy: "reviewer.rights",
        reviewedAt: "2026-01-01T01:00:00.000Z",
        effectiveAt: "2026-01-01T01:00:00.000Z",
        expiresAt: null,
        recordedAt: "2026-01-01T02:00:00.000Z",
        notes: "Unreviewed sources begin with no permissions.",
      },
      {
        id: "rights.source.one.open",
        sourceId: "source.one",
        supersedesDecisionId: "rights.source.one.default",
        decisionStatus: "permitted_with_conditions",
        legalBasis: "open_license",
        permissions: {
          bibliographicMetadata: true,
          privateStorage: true,
          localTextExtraction: true,
          localStructuredIndexing: true,
          externalAiProcessing: true,
          derivedClinicalContent: true,
          projectParaphrasePublication: true,
          publicSourceTextReuse: false,
          runtimeRedistribution: true,
          commercialDistribution: false,
        },
        territories: ["Global"],
        licenseLabel: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        termsUrl: "https://example.test/source-terms",
        attributionStatement: "Example Source, CC BY 4.0.",
        requiredNotices: ["Identify project-authored adaptations."],
        nonCommercialOnly: false,
        shareAlikeRequired: false,
        thirdPartyMaterialPolicy: "item_level_review_required",
        fairUseAssessment: null,
        permissionEvidenceReferenceIds: [],
        reviewBasis: "engineering_risk_assessment",
        reviewedBy: "reviewer.rights",
        reviewedAt: "2026-01-02T01:00:00.000Z",
        effectiveAt: "2026-01-02T01:00:00.000Z",
        expiresAt: null,
        recordedAt: "2026-01-02T02:00:00.000Z",
        notes:
          "The open license permits the recorded local and derived uses with attribution.",
      },
    ],
    searchRuns: [
      {
        id: "search.one",
        gapRevisionIds: ["gap.rev.one"],
        strategyVersion: "search.strategy.one",
        scoutPolicyFingerprint: sha("a"),
        queries: [
          {
            databaseOrRegistry: "PubMed",
            query:
              "(surgical presentation[Title/Abstract]) AND imaging[Title/Abstract]",
            filters: ["English", "Humans"],
          },
        ],
        startedAt: "2026-01-03T10:00:00.000Z",
        completedAt: "2026-01-03T10:05:00.000Z",
        searchThroughDate: "2026-01-03",
        status: "completed",
        providerResultCountTotal: 10,
        providerRecordsInspected: 2,
        candidateCountCaptured: 2,
        toolId: "tool.pubmed",
        toolVersion: "1.0.0",
        inputFingerprint: sha("b"),
        statusNote: null,
        recordedAt: "2026-01-03T10:06:00.000Z",
        recordedBy: "scout.one",
      },
    ],
    candidates: [
      {
        id: "candidate.one",
        searchRunId: "search.one",
        sourceType: "clinical_guideline",
        title: "Example imaging guideline",
        authors: [],
        organization: "Example Surgical Society",
        publicationDate: "2025",
        doi: null,
        pmid: "12345678",
        url: "https://example.test/guideline",
        citation: "Example Surgical Society. Example imaging guideline. 2025.",
        publicationTypes: ["Practice Guideline"],
        language: "English",
        authoritySignals: [
          "professional_society",
          "clinical_guideline",
        ],
        surfacingRationale:
          "Matched the literal imaging query and preferred guideline source type.",
        accessHint: "public",
        matchedExistingSourceId: "source.one",
        metadataFingerprint: sha("c"),
        discoveredAt: "2026-01-03T10:02:00.000Z",
        recordedAt: "2026-01-03T10:06:00.000Z",
        recordedBy: "scout.one",
      },
      {
        id: "candidate.two",
        searchRunId: "search.one",
        sourceType: "systematic_review",
        title: "Example imaging review",
        authors: ["A. Reviewer"],
        organization: null,
        publicationDate: "2024",
        doi: "10.1234/example.review",
        pmid: null,
        url: "https://example.test/review",
        citation: "Reviewer A. Example imaging review. 2024.",
        publicationTypes: ["Systematic Review"],
        language: "English",
        authoritySignals: ["peer_reviewed", "systematic_review"],
        surfacingRationale:
          "Matched the literal imaging query and preferred synthesis source type.",
        accessHint: "restricted",
        matchedExistingSourceId: null,
        metadataFingerprint: sha("d"),
        discoveredAt: "2026-01-03T10:03:00.000Z",
        recordedAt: "2026-01-03T10:06:00.000Z",
        recordedBy: "scout.one",
      },
    ],
    candidateObservations: [
      {
        id: "candidate-observation.one",
        candidateId: "candidate.one",
        searchRunId: "search.one",
        provider: "pubmed",
        providerRecordId: "12345678",
        observedDoi: null,
        observedPmid: "12345678",
        metadataFingerprint: sha("c"),
        observedAt: "2026-01-03T10:02:00.000Z",
        recordedAt: "2026-01-03T10:06:00.000Z",
        recordedBy: "scout.one",
      },
      {
        id: "candidate-observation.two",
        candidateId: "candidate.two",
        searchRunId: "search.one",
        provider: "pubmed",
        providerRecordId: "example-review-record",
        observedDoi: "10.1234/example.review",
        observedPmid: null,
        metadataFingerprint: sha("d"),
        observedAt: "2026-01-03T10:03:00.000Z",
        recordedAt: "2026-01-03T10:06:00.000Z",
        recordedBy: "scout.one",
      },
    ],
    screeningDecisions: [
      {
        id: "screen.one",
        candidateId: "candidate.one",
        gapId: "gap.one",
        supersedesDecisionId: null,
        disposition: "include",
        resolvedSourceId: "source.one",
        reason: "Meets the gap acceptance criteria for full review.",
        reviewedAt: "2026-01-03T11:00:00.000Z",
        reviewedBy: "reviewer.evidence",
        recordedAt: "2026-01-03T11:01:00.000Z",
      },
      {
        id: "screen.two",
        candidateId: "candidate.two",
        gapId: "gap.one",
        supersedesDecisionId: null,
        disposition: "awaiting_full_text",
        resolvedSourceId: null,
        reason: "Full text and rights still require review.",
        reviewedAt: "2026-01-03T11:00:00.000Z",
        reviewedBy: "reviewer.evidence",
        recordedAt: "2026-01-03T11:01:00.000Z",
      },
    ],
    contributions: [
      {
        id: "contribution.formal.one",
        seriesId: "contribution.series.formal.one",
        supersedesContributionId: null,
        evidenceGapIds: ["gap.one"],
        targetContent: [{ kind: "structured_fact", id: "fact.one" }],
        authority: "formal_source",
        sourceId: "source.one",
        citationIds: ["citation.one"],
        expertOpinionRevisionId: null,
        role: "supports",
        contributionTypes: ["workup"],
        statement:
          "Selected clinical findings can make imaging appropriate.",
        applicabilityNote: "Adults in an outpatient surgical setting.",
        sourceRole: "guideline",
        generatedBy: "human",
        reviewStatus: "accepted",
        reviewedAt: "2026-01-04T12:00:00.000Z",
        reviewedBy: "reviewer.clinical",
        recordedAt: "2026-01-04T11:00:00.000Z",
        recordedBy: "author.one",
      },
      {
        id: "contribution.formal.proposed",
        seriesId: "contribution.series.formal.proposed",
        supersedesContributionId: null,
        evidenceGapIds: ["gap.one"],
        targetContent: [{ kind: "structured_fact", id: "fact.one" }],
        authority: "formal_source",
        sourceId: "source.one",
        citationIds: ["citation.one"],
        expertOpinionRevisionId: null,
        role: "qualifies",
        contributionTypes: ["workup"],
        statement: "A proposed qualification remains under review.",
        applicabilityNote: "Scope not yet reviewed.",
        sourceRole: "guideline",
        generatedBy: "human",
        reviewStatus: "proposed",
        reviewedAt: null,
        reviewedBy: null,
        recordedAt: "2026-01-04T13:00:00.000Z",
        recordedBy: "author.one",
      },
      {
        id: "contribution.expert.one",
        seriesId: "contribution.series.expert.one",
        supersedesContributionId: null,
        evidenceGapIds: ["gap.one"],
        targetContent: [{ kind: "structured_fact", id: "fact.one" }],
        authority: "expert_opinion",
        sourceId: null,
        citationIds: [],
        expertOpinionRevisionId: "opinion.rev.one",
        role: "qualifies",
        contributionTypes: ["workup"],
        statement:
          "Clinical context may narrow how the general evidence is taught.",
        applicabilityNote: "Prototype outpatient teaching only.",
        sourceRole: "expert_opinion",
        generatedBy: "human",
        reviewStatus: "accepted",
        reviewedAt: "2026-01-05T13:00:00.000Z",
        reviewedBy: "reviewer.clinical",
        recordedAt: "2026-01-05T12:00:00.000Z",
        recordedBy: "author.one",
      },
    ],
    expertOpinions: [
      {
        id: "opinion.one",
        createdAt: "2026-01-04T10:00:00.000Z",
        createdBy: "expert.one",
      },
    ],
    expertOpinionRevisions: [
      {
        revisionId: "opinion.rev.one",
        opinionId: "opinion.one",
        supersedesRevisionId: null,
        evidenceGapIds: ["gap.one"],
        relatedFormalContributionIds: ["contribution.formal.one"],
        statement:
          "Use a deliberately narrow prototype rule until broader evidence is reviewed.",
        rationale:
          "The available guideline supports the direction but not every possible presentation.",
        clinicalScope: "Level 0 and Level 1 outpatient prototype encounters.",
        limitations: ["This does not define a universal imaging rule."],
        reviewStatus: "accepted",
        reviewedAt: "2026-01-05T11:00:00.000Z",
        reviewedBy: "reviewer.clinical",
        recordedAt: "2026-01-05T10:00:00.000Z",
        recordedBy: "expert.one",
        changeSummary: "Recorded the initial narrow expert interpretation.",
      },
    ],
    synthesisProposals: [
      {
        id: "synthesis.one",
        evidenceGapRevisionIds: ["gap.rev.one"],
        searchRunIds: ["search.one"],
        contributionIds: [
          "contribution.formal.one",
          "contribution.expert.one",
        ],
        expertOpinionRevisionIds: ["opinion.rev.one"],
        focusedQuestion:
          "Which findings should affect the prototype imaging decision?",
        supportingSummary:
          "The reviewed formal Contribution supports a conditional imaging decision.",
        opposingOrQualifyingSummary:
          "The reviewed Expert Opinion limits application to the prototype scope.",
        proposedDirection:
          "Author a narrow conditional rule for separately reviewed content.",
        limitations: ["Only the prototype setting has been evaluated."],
        unresolvedQuestions: ["Broader inpatient applicability remains open."],
        generatedBy: "human",
        generationProvenance: null,
        pointMagnitudeExcluded: true,
        clinicalApprovalId: null,
        recordedAt: "2026-01-06T00:00:00.000Z",
        recordedBy: "author.one",
      },
    ],
    synthesisDecisions: [
      {
        id: "synthesis.decision.one",
        proposalId: "synthesis.one",
        supersedesDecisionId: null,
        disposition: "accept",
        acceptedStatement:
          "Proceed with a narrow conditional prototype rule.",
        rationale:
          "The evidence and expert limitation are explicit and traceable.",
        resultingEvidenceGapIds: [],
        reviewedAt: "2026-01-07T00:00:00.000Z",
        reviewedBy: "reviewer.clinical",
        recordedAt: "2026-01-07T01:00:00.000Z",
        clinicalApprovalId: null,
      },
    ],
    contentChangeProposals: [
      {
        id: "change.one",
        synthesisDecisionId: "synthesis.decision.one",
        targetContent: [{ kind: "structured_fact", id: "fact.one" }],
        changeKind: "modify",
        beforeSummary: "No reviewed conditional imaging rule.",
        proposedSummary:
          "Draft a conditional imaging rule for clinical review.",
        status: "ready_for_authoring",
        crossTargetReview: null,
        clinicalApprovalId: null,
        recordedAt: "2026-01-08T00:00:00.000Z",
        recordedBy: "author.one",
      },
    ],
  };
}
