import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { ACTION, buildClipboardGeometry, buildJumpGeometry, buildSeatedGeometry } from './action-geometry.mjs';
import { renderAction, renderGuide } from './render-actions.mjs';

const root=resolve(import.meta.dirname,'../../..'),out=resolve(root,'artifacts/character-movement/canonical-actions/preview'),frames=resolve(out,'frames'),statics=resolve(out,'static');
mkdirSync(frames,{recursive:true});mkdirSync(statics,{recursive:true});
const sha256=bytes=>createHash('sha256').update(bytes).digest('hex'),registration={frameAxisX:ACTION.frame.axisX,frameFloorY:ACTION.frame.floorY};
function writeAsset(path,bytes){mkdirSync(dirname(path),{recursive:true});writeFileSync(path,bytes);return {path:relative(out,path).replaceAll('\\','/'),sha256:sha256(bytes)};}
function record(pathBase,geometry,isStatic=false){const clean=renderAction(geometry).toBuffer('image/png'),guide=renderGuide(geometry).toBuffer('image/png'),cleanAsset=writeAsset(`${pathBase}.png`,clean),guideAsset=writeAsset(`${pathBase}-guide.png`,guide);return {clean:cleanAsset.path,guide:guideAsset.path,sha256:{clean:cleanAsset.sha256,guide:guideAsset.sha256},...(isStatic?{registration:{axisX:ACTION.frame.axisX,floorY:ACTION.frame.floorY}}:{}),geometry:{...geometry,registration}};}
const jump=buildJumpGeometry(),character={id:'canonical-short-stylized-master-v1',runtimeId:'canonical.master.short-stylized.v1',directions:{},static:{}};
for(const direction of ACTION.directions){character.directions[direction]={};for(const phaseId of ACTION.phaseIds)character.directions[direction][phaseId]=record(resolve(frames,`canonical-jump-${direction}-${phaseId}`),jump[direction][phaseId]);}
for(const direction of ACTION.directions){const suffix=direction[0].toUpperCase()+direction.slice(1);character.static[`sit${suffix}`]=record(resolve(statics,`canonical-sit-${direction}`),buildSeatedGeometry(direction),true);character.static[`clipboard${suffix}`]=record(resolve(statics,`canonical-clipboard-${direction}`),buildClipboardGeometry(direction),true);}
const oldMasterBytes=readFileSync(resolve(root,'artifacts/character-movement/canonical-master/preview/manifest.json'));
const manifest={schemaVersion:1,status:'plain-canonical-actions-owner-review',directions:ACTION.directions,phaseIds:ACTION.phaseIds,characters:[character],actions:{primary:{id:'starJump',label:'Star jump',phaseStages:Object.fromEntries(ACTION.phaseIds.map((id,index)=>[id,ACTION.jumpStages[index]]))},staticViews:{sitEast:'Sitting · East',sitWest:'Sitting · West',sitSouth:'Sitting · South',sitNorth:'Sitting · North',clipboardEast:'Clipboard hold · East',clipboardWest:'Clipboard hold · West',clipboardSouth:'Clipboard hold · South',clipboardNorth:'Clipboard hold · North'}},canonical:{masterId:'canonical-short-stylized-v1',frame:ACTION.frame,lengths:{upperArm:38,forearm:37,hand:10,thigh:42,shin:42},oldApprovedMasterManifestSha256:sha256(oldMasterBytes),sharedMaterials:['skin.head','skin.hand','cloth.torso','cloth.upperArm','cloth.forearm','cloth.thigh','cloth.shin','shoe.foot']},semanticInvariants:{fixedAnatomicalLengths:true,airborneFeetUseProjectedHeight:true,starJumpStages:ACTION.jumpStages,seatedThighsForwardAndShinsVertical:true,clipboardPlane:'shared 3D plane, top edge anatomically farther forward than bottom edge',clipboardRoles:{left:'entire arm foreground, hand supports lower underside',right:'arm and resting hand behind board'},northClipboardOccludedByTorso:true,independentGuide:true},validation:{jumpFrames:32,staticPoses:8,ownerVisualAcceptance:'pending'}};
const bytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');writeFileSync(resolve(out,'manifest.json'),bytes);console.log(JSON.stringify({manifest:resolve(out,'manifest.json'),sha256:sha256(bytes),frame:ACTION.frame,jumpFrames:32,staticPoses:8},null,2));
