import { createCanvas } from '@napi-rs/canvas';
import { MASTER } from '../canonical-master/canonical-geometry.mjs';
import { ACTION } from './action-geometry.mjs';

const C = { outline:'#26313a',skin:'#d9a779',skinLight:'#edc49b',shirt:'#6d8792',shirtLight:'#819aa3',pants:'#43505d',pantsLight:'#53616d',shoe:'#5b4534',sole:'#2b2928',guide:'#2acadd',chair:'#78868d',board:'#c89b58',paper:'#efe7d5' };
const midpoint = (a,b) => ({x:(a.x+b.x)/2,y:(a.y+b.y)/2});

function joined(ctx,a,b,c,widths,fills){ctx.lineCap='round';for(const [s,e,w] of [[a,b,widths[0]],[b,c,widths[1]]]){ctx.strokeStyle=C.outline;ctx.lineWidth=w+3;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(e.x,e.y);ctx.stroke();}for(const [s,e,w,f] of [[a,b,widths[0],fills[0]],[b,c,widths[1],fills[1]]]){ctx.strokeStyle=f;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(e.x,e.y);ctx.stroke();ctx.globalAlpha=.22;ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,w*.13);ctx.beginPath();ctx.moveTo(s.x-1,s.y);ctx.lineTo(e.x-1,e.y);ctx.stroke();ctx.globalAlpha=1;}}
function hand(ctx,j){ctx.fillStyle=C.outline;ctx.beginPath();ctx.ellipse(j.palm.x,j.palm.y,6,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.skin;ctx.beginPath();ctx.ellipse(j.palm.x,j.palm.y,4.6,6.5,0,0,Math.PI*2);ctx.fill();if(j.thumbVisibility==='visible'){ctx.strokeStyle=C.outline;ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(j.palm.x,j.palm.y-1);ctx.lineTo(j.thumbTip.x,j.thumbTip.y);ctx.stroke();ctx.strokeStyle=C.skinLight;ctx.lineWidth=2.5;ctx.stroke();}}
function foot(ctx,j,view){const {heel,toe,ankle}=j,dx=toe.x-heel.x,dy=toe.y-heel.y,len=Math.hypot(dx,dy);if(view==='south'||view==='north'){const angle=Math.atan2(dy,dx),center=midpoint(heel,toe);ctx.fillStyle=C.outline;ctx.beginPath();ctx.ellipse(center.x,center.y-4,Math.max(10,len*.63),7,angle,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.shoe;ctx.beginPath();ctx.ellipse(center.x,center.y-5,Math.max(9,len*.58),5.5,angle,0,Math.PI*2);ctx.fill();ctx.strokeStyle=C.sole;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(heel.x,heel.y);ctx.lineTo(toe.x,toe.y);ctx.stroke();return;}ctx.fillStyle=C.outline;ctx.beginPath();ctx.moveTo(heel.x,heel.y+2);ctx.lineTo(toe.x+Math.sign(dx)*2,toe.y+1);ctx.lineTo(toe.x,toe.y-7);ctx.lineTo(ankle.x,ankle.y);ctx.lineTo(heel.x,heel.y-8);ctx.closePath();ctx.fill();ctx.fillStyle=C.shoe;ctx.beginPath();ctx.moveTo(heel.x,heel.y);ctx.lineTo(toe.x,toe.y-1);ctx.lineTo(toe.x,toe.y-6);ctx.lineTo(ankle.x,ankle.y+1);ctx.lineTo(heel.x+Math.sign(dx),heel.y-7);ctx.closePath();ctx.fill();ctx.strokeStyle=C.sole;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(heel.x,heel.y+1);ctx.lineTo(toe.x,toe.y);ctx.stroke();}
function limb(ctx,j,kind,view,{handOnly=false}={}){if(kind==='arm'){if(!handOnly){const start={x:j.shoulder.x+(j.elbow.x-j.shoulder.x)*.14,y:j.shoulder.y+(j.elbow.y-j.shoulder.y)*.14};joined(ctx,start,j.elbow,j.wrist,[17,16],[C.shirtLight,C.shirt]);}hand(ctx,j);}else{joined(ctx,j.hip,j.knee,j.ankle,[24,21],[C.pantsLight,C.pants]);foot(ctx,j,view);}}
function torsoPath(ctx,g){const shoulderY=(g.joints.left.shoulder.y+g.joints.right.shoulder.y)/2,lateral=g.view==='east'||g.view==='west',s=lateral?MASTER.shapes.torso.side:MASTER.shapes.torso.front,cx=g.hipCenter.x;ctx.beginPath();ctx.moveTo(cx-10,shoulderY-2);ctx.quadraticCurveTo(cx-18,shoulderY-11,cx-s.shoulderHalfWidth+8,shoulderY-11);ctx.quadraticCurveTo(cx-s.shoulderHalfWidth,shoulderY-10,cx-s.chestHalfWidth,shoulderY+20);ctx.lineTo(cx-s.chestHalfWidth,shoulderY+42);ctx.quadraticCurveTo(cx-s.hipHalfWidth,g.hipCenter.y-4,cx-s.hipHalfWidth,g.hipCenter.y+2);ctx.quadraticCurveTo(cx,g.hipCenter.y+8,cx+s.hipHalfWidth,g.hipCenter.y+2);ctx.quadraticCurveTo(cx+s.hipHalfWidth,g.hipCenter.y-4,cx+s.chestHalfWidth,shoulderY+42);ctx.lineTo(cx+s.chestHalfWidth,shoulderY+20);ctx.quadraticCurveTo(cx+s.shoulderHalfWidth,shoulderY-10,cx+s.shoulderHalfWidth-8,shoulderY-11);ctx.quadraticCurveTo(cx+18,shoulderY-11,cx+10,shoulderY-2);ctx.closePath();}
function body(ctx,g){const shoulderY=(g.joints.left.shoulder.y+g.joints.right.shoulder.y)/2,cx=g.hipCenter.x,facing=g.view==='east'?1:g.view==='west'?-1:0,headX=cx-facing*3,headY=shoulderY-52;ctx.fillStyle=C.outline;torsoPath(ctx,g);ctx.fill();ctx.save();torsoPath(ctx,g);ctx.clip();const grad=ctx.createLinearGradient(cx-44,0,cx+44,0);grad.addColorStop(0,'#58737d');grad.addColorStop(.5,C.shirtLight);grad.addColorStop(1,'#55707a');ctx.fillStyle=grad;ctx.fillRect(cx-50,shoulderY-8,100,g.hipCenter.y-shoulderY+18);ctx.restore();ctx.fillStyle=C.outline;ctx.fillRect(headX-11,shoulderY-16,22,23);ctx.fillStyle=C.skin;ctx.fillRect(headX-9,shoulderY-17,18,24);ctx.fillStyle=C.outline;ctx.beginPath();ctx.ellipse(headX,headY,40,45,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.skin;ctx.beginPath();ctx.ellipse(headX,headY,38,43,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=C.outline;ctx.lineWidth=2;if(g.view==='south'){for(const dx of [-13,13]){ctx.beginPath();ctx.arc(headX+dx,headY+2,4,0,Math.PI*2);ctx.stroke();}ctx.beginPath();ctx.moveTo(headX-9,headY+19);ctx.quadraticCurveTo(headX,headY+24,headX+9,headY+19);ctx.stroke();}else if(facing){ctx.beginPath();ctx.arc(headX+facing*15,headY+3,4,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(headX+facing*34,headY+6);ctx.lineTo(headX+facing*42,headY+10);ctx.lineTo(headX+facing*34,headY+13);ctx.stroke();}}
function chair(ctx,g){const y=g.hipCenter.y+2;if(g.view==='east'||g.view==='west'){const facing=g.view==='east'?1:-1;ctx.fillStyle=C.chair;ctx.fillRect(g.hipCenter.x-facing*32,y-70,7,72);ctx.fillRect(g.hipCenter.x-facing*34,y,72*facing,8);ctx.fillRect(g.hipCenter.x+facing*30,y+7,7,ACTION.frame.floorY-y-7);ctx.fillRect(g.hipCenter.x-facing*27,y+7,7,ACTION.frame.floorY-y-7);}else{ctx.fillStyle=C.chair;ctx.fillRect(g.hipCenter.x-42,y,84,8);ctx.fillRect(g.hipCenter.x-36,y+7,7,ACTION.frame.floorY-y-7);ctx.fillRect(g.hipCenter.x+29,y+7,7,ACTION.frame.floorY-y-7);}}
function polygon(ctx,points){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const point of points.slice(1))ctx.lineTo(point.x,point.y);ctx.closePath();}
function clipboard(ctx,g){const b=g.clipboard,points=[b.corners.topLeft,b.corners.topRight,b.corners.bottomRight,b.corners.bottomLeft],center={x:points.reduce((sum,p)=>sum+p.x,0)/4,y:points.reduce((sum,p)=>sum+p.y,0)/4},paper=points.map(p=>({x:p.x+(center.x-p.x)*.10,y:p.y+(center.y-p.y)*.12}));ctx.fillStyle=C.board;ctx.strokeStyle=C.outline;ctx.lineWidth=4;ctx.lineJoin='round';polygon(ctx,points);ctx.fill();ctx.stroke();ctx.fillStyle=C.paper;polygon(ctx,paper);ctx.fill();const top={x:(points[0].x+points[1].x)/2,y:(points[0].y+points[1].y)/2};ctx.strokeStyle=C.outline;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(top.x-6,top.y+2);ctx.lineTo(top.x+6,top.y+2);ctx.stroke();}

export function renderAction(g){
  const canvas=createCanvas(ACTION.frame.width,ACTION.frame.height),ctx=canvas.getContext('2d'),near=g.view==='east'?'right':g.view==='west'?'left':'right',far=near==='right'?'left':'right',frontal=g.view==='south'||g.view==='north';
  if(g.action==='sit')chair(ctx,g);
  if(g.action==='clipboard'){
    if(g.view==='north'){
      limb(ctx,g.joints.right,'arm',g.view);clipboard(ctx,g);limb(ctx,g.joints.left,'arm',g.view);
      for(const side of ['left','right'])limb(ctx,g.joints[side],'leg',g.view);body(ctx,g);
    }else{
      if(frontal)for(const side of ['left','right'])limb(ctx,g.joints[side],'leg',g.view);
      else {limb(ctx,g.joints[far],'leg',g.view);limb(ctx,g.joints[near],'leg',g.view);}
      body(ctx,g);limb(ctx,g.joints.right,'arm',g.view);clipboard(ctx,g);limb(ctx,g.joints.left,'arm',g.view);
    }
    return canvas;
  }
  if(frontal){
    if(g.action!=='sit'&&g.action!=='clipboard')for(const side of ['left','right'])limb(ctx,g.joints[side],'arm',g.view);
    if(g.action==='sit'&&g.view==='north')for(const side of ['left','right'])limb(ctx,g.joints[side],'arm',g.view);
    if(g.action==='clipboard'&&g.view==='north')for(const side of ['left','right'])limb(ctx,g.joints[side],'arm',g.view);
    for(const side of ['left','right'])limb(ctx,g.joints[side],'leg',g.view);
  }else{
    limb(ctx,g.joints[far],'arm',g.view);limb(ctx,g.joints[far],'leg',g.view);limb(ctx,g.joints[near],'leg',g.view);
  }
  body(ctx,g);
  if(g.action==='sit'){
    if(g.view==='south')for(const side of ['left','right'])limb(ctx,g.joints[side],'arm',g.view);
    else if(!frontal)limb(ctx,g.joints[near],'arm',g.view);
  }else if(!frontal)limb(ctx,g.joints[near],'arm',g.view);
  return canvas;
}

export function renderGuide(g){const canvas=createCanvas(ACTION.frame.width,ACTION.frame.height),ctx=canvas.getContext('2d');ctx.strokeStyle=C.guide;ctx.fillStyle='rgba(42,202,221,.12)';ctx.lineWidth=1.5;ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(ACTION.frame.axisX,0);ctx.lineTo(ACTION.frame.axisX,ACTION.frame.height);ctx.moveTo(0,ACTION.frame.floorY);ctx.lineTo(ACTION.frame.width,ACTION.frame.floorY);ctx.stroke();ctx.setLineDash([]);torsoPath(ctx,g);ctx.fill();ctx.stroke();const shoulderY=(g.joints.left.shoulder.y+g.joints.right.shoulder.y)/2,facing=g.view==='east'?1:g.view==='west'?-1:0,headX=g.hipCenter.x-facing*3;ctx.strokeRect(headX-9,shoulderY-17,18,24);ctx.beginPath();ctx.ellipse(headX,shoulderY-52,40,45,0,0,Math.PI*2);ctx.stroke();for(const side of ['left','right']){const j=g.joints[side];ctx.strokeStyle=side==='left'?'#f5b942':C.guide;ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(j.shoulder.x,j.shoulder.y);ctx.lineTo(j.elbow.x,j.elbow.y);ctx.lineTo(j.wrist.x,j.wrist.y);ctx.lineTo(j.palm.x,j.palm.y);ctx.moveTo(j.hip.x,j.hip.y);ctx.lineTo(j.knee.x,j.knee.y);ctx.lineTo(j.ankle.x,j.ankle.y);ctx.moveTo(j.heel.x,j.heel.y);ctx.lineTo(j.toe.x,j.toe.y);ctx.stroke();for(const p of [j.shoulder,j.elbow,j.wrist,j.palm,j.thumbTip,j.hip,j.knee,j.ankle,j.heel,j.toe]){ctx.beginPath();ctx.arc(p.x,p.y,2.2,0,Math.PI*2);ctx.fill();}}if(g.clipboard){const points=[g.clipboard.corners.topLeft,g.clipboard.corners.topRight,g.clipboard.corners.bottomRight,g.clipboard.corners.bottomLeft];ctx.strokeStyle='#d98b2b';polygon(ctx,points);ctx.stroke();ctx.font='bold 10px sans-serif';ctx.fillStyle='#f5b942';ctx.fillText('L support',g.joints.left.palm.x+4,g.joints.left.palm.y+4);ctx.fillStyle=C.guide;ctx.fillText('R rest',g.joints.right.palm.x+4,g.joints.right.palm.y-4);}return canvas;}
