import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { MASTER } from '../canonical-master/canonical-geometry.mjs';
import { ACTION, actionInternals } from './action-geometry.mjs';

const root=resolve(import.meta.dirname,'../../..'),out=resolve(root,'artifacts/character-movement/canonical-actions/preview'),manifestBytes=readFileSync(resolve(out,'manifest.json')),manifest=JSON.parse(manifestBytes),sha256=bytes=>createHash('sha256').update(bytes).digest('hex'),near=(a,b,t=.02)=>Math.abs(a-b)<=t;
const bytesFor=relative=>readFileSync(resolve(out,relative));
function pixelsFor(image){const canvas=createCanvas(image.width,image.height),ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);return ctx.getImageData(0,0,image.width,image.height).data;}
function validateBones(g,label){for(const side of ['left','right']){const j=g.joints[side].latent;for(const [a,b,length] of [['hip','knee',MASTER.lengths.thigh],['knee','ankle',MASTER.lengths.shin],['shoulder','elbow',MASTER.lengths.upperArm],['elbow','wrist',MASTER.lengths.forearm],['wrist','hand',MASTER.lengths.hand]])if(!near(actionInternals.distance3(j[a],j[b]),length))throw new Error(`${label}/${side}/${a}-${b}`);const t=(j.elbow.height-j.shoulder.height)/(j.wrist.height-j.shoulder.height),lineForward=j.shoulder.forward+(j.wrist.forward-j.shoulder.forward)*t;if(j.elbow.forward-lineForward>=-1)throw new Error(`${label}/${side}/posterior elbow branch`);}}
async function validateRaster(record,label){const clean=bytesFor(record.clean),guide=bytesFor(record.guide);if(sha256(clean)!==record.sha256.clean||sha256(guide)!==record.sha256.guide||record.sha256.clean===record.sha256.guide)throw new Error(`${label}/hash or independent guide`);const image=await loadImage(clean);if(image.width!==ACTION.frame.width||image.height!==ACTION.frame.height)throw new Error(`${label}/native frame`);const pixels=pixelsFor(image);let minX=image.width,minY=image.height,maxX=-1,maxY=-1,boardPixels=0;for(let y=0;y<image.height;y++)for(let x=0;x<image.width;x++){const i=(y*image.width+x)*4;if(!pixels[i+3])continue;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);if((pixels[i]===200&&pixels[i+1]===155&&pixels[i+2]===88)||(pixels[i]===239&&pixels[i+1]===231&&pixels[i+2]===213))boardPixels++;}if(minX<1||minY<1||maxX>=image.width-1||maxY>=image.height-1)throw new Error(`${label}/clipped raster`);return boardPixels;}
function expectedLayer(g){if(g.action==='sit')return g.view==='south'?'chair,legs,torso,head,arms':g.view==='north'?'chair,arms,legs,torso,head':'chair,farArm,farLeg,nearLeg,torso,head,nearArm';if(g.action==='clipboard')return g.view==='north'?'rightArm,clipboard,leftArm,legs,torso,head':'legs,torso,head,rightArm,clipboard,leftArm';return g.view==='south'||g.view==='north'?'arms,legs,torso,head':'farArm,farLeg,nearLeg,torso,head,nearArm';}

if(manifest.directions.join(',')!==ACTION.directions.join(',')||manifest.phaseIds.join(',')!==ACTION.phaseIds.join(',')||manifest.characters.length!==1)throw new Error('manifest contract');
const oldPath=resolve(root,'artifacts/character-movement/canonical-master/preview'),oldBytes=readFileSync(resolve(oldPath,'manifest.json')),old=JSON.parse(oldBytes);if(sha256(oldBytes)!=='c9ccf24da87a4f89e1f464a65819d205bf0b2930950f9c60105a64c6d618c309'||manifest.canonical.oldApprovedMasterManifestSha256!==sha256(oldBytes))throw new Error('approved master manifest changed');
let oldAssets=0;for(const direction of old.directions)for(const phase of old.phaseIds)for(const kind of ['clean','guide']){const r=old.characters[0].directions[direction][phase];if(sha256(readFileSync(resolve(oldPath,r[kind])))!==r.sha256[kind])throw new Error(`old ${direction}/${phase}/${kind}`);oldAssets++;}for(const r of Object.values(old.characters[0].static))for(const kind of ['clean','guide']){if(sha256(readFileSync(resolve(oldPath,r[kind])))!==r.sha256[kind])throw new Error(`old static/${kind}`);oldAssets++;}
const character=manifest.characters[0];let jumpFrames=0,staticPoses=0,bonePoseSets=0,airborneFootSides=0,groundFootSides=0,boardContactHands=0,northBoardPixels=0,southBoardPixels=0;
for(const direction of ACTION.directions)for(const phaseId of ACTION.phaseIds){const record=character.directions[direction][phaseId],g=record.geometry,label=`jump/${direction}/${phaseId}`;validateBones(g,label);bonePoseSets++;if(g.stage!==manifest.actions.primary.phaseStages[phaseId]||g.layerPolicy.join(',')!==expectedLayer(g))throw new Error(`${label}/stage or layer`);for(const side of ['left','right']){const j=g.joints[side];if(['02','03','04','05'].includes(phaseId)){if(j.soleHeight<=0||j.heel.y>=ACTION.frame.floorY||j.toe.y>=ACTION.frame.floorY)throw new Error(`${label}/${side}/airborne`);airborneFootSides++;}else{if(j.soleHeight!==0||!near(j.heel.y,ACTION.frame.floorY)||!near(j.toe.y,ACTION.frame.floorY))throw new Error(`${label}/${side}/ground`);groundFootSides++;}}if(phaseId==='04')for(const side of ['left','right']){const j=g.joints[side];if(j.latent.wrist.height<=j.latent.shoulder.height||Math.abs(j.latent.ankle.lateral)<50)throw new Error(`${label}/${side}/open star`);}await validateRaster(record,label);jumpFrames++;}
for(const direction of ACTION.directions){const suffix=direction[0].toUpperCase()+direction.slice(1);for(const [key,action] of [[`sit${suffix}`,'sit'],[`clipboard${suffix}`,'clipboard']]){const record=character.static[key],g=record.geometry,label=`static/${key}`;if(g.view!==direction||g.action!==action||g.layerPolicy.join(',')!==expectedLayer(g))throw new Error(`${label}/view action or layer`);validateBones(g,label);bonePoseSets++;if(action==='sit')for(const side of ['left','right']){const j=g.joints[side].latent;if(!near(j.hip.height,j.knee.height)||!near(j.knee.height-j.ankle.height,MASTER.lengths.shin)||!near(j.knee.forward,j.ankle.forward)||j.knee.forward-j.hip.forward<39)throw new Error(`${label}/${side}/seated anatomy`);}else{const b=g.clipboard,left=g.joints.left.latent.hand,right=g.joints.right.latent.hand,top=(b.latentCorners.topLeft.forward+b.latentCorners.topRight.forward)/2,bottom=(b.latentCorners.bottomLeft.forward+b.latentCorners.bottomRight.forward)/2,faceAtRight=bottom+(top-bottom)*(right.height-b.latentCorners.bottomLeft.height)/(b.latentCorners.topLeft.height-b.latentCorners.bottomLeft.height),raise=direction==='south'?12:0;if(b.roles.left!=='underside-support'||b.roles.right!=='writing-face-rest'||actionInternals.distance3(left,b.anchors.leftSupport)>.02||actionInternals.distance3(right,b.anchors.rightRest)>.02||left.height>b.latentCorners.bottomLeft.height+3||left.forward>=bottom||right.forward<=faceAtRight||b.latentCorners.topLeft.height!==153+raise||b.latentCorners.bottomLeft.height!==111+raise||top<=bottom)throw new Error(`${label}/clipboard support roles or plane`);boardContactHands+=2;}const boardPixels=await validateRaster(record,label);if(key==='clipboardNorth')northBoardPixels=boardPixels;if(key==='clipboardSouth')southBoardPixels=boardPixels;staticPoses++;}}
if(northBoardPixels>=southBoardPixels*.35)throw new Error('north clipboard is not naturally torso-occluded');
console.log(JSON.stringify({jumpFrames,staticPoses,boneLengthPoseSets:bonePoseSets,airborneFootSides,groundFootSides,boardContactHands,northBoardPixels,southBoardPixels,oldApprovedAssetsVerified:oldAssets,manifestSha256:sha256(manifestBytes)},null,2));
