import type { ClinicalSource, EvidenceClaim } from "../../pilot-schema";
import { CHECKED_ON, NEEDS_REVIEW } from "./batch-helpers";

export const S = {
  cornwallSurgery: "source.pediatric-clinic.cornwall-surgery-2025",
  nhsHernia: "source.pediatric-clinic.nhs-hernia-2026",
  nhsUmbilical: "source.pediatric-clinic.nhs-umbilical-2025",
  goshHernia: "source.pediatric-clinic.gosh-midline-hernia-2016",
  cornwallNodes: "source.pediatric-clinic.cornwall-nodes-2025",
  cuaTestis: "source.pediatric-clinic.cua-puc-testis-2017",
  cuhTestis: "source.pediatric-clinic.cuh-testis-2025",
  pectusReview: "source.pediatric-clinic.scalise-demehri-pectus-2023",
  shtgBrace: "source.pediatric-clinic.shtg-bracing-2022",
  alderBrace: "source.pediatric-clinic.alder-hey-bracing-2026",
  pilonidal: "source.pediatric-clinic.metzger-pilonidal-2021",
  cpsAssent: "source.pediatric-clinic.cps-decision-making-2018",
} as const;

interface SourceInput extends Omit<ClinicalSource, keyof typeof NEEDS_REVIEW | "evidenceClaimIds" | "accessedOn" | "doi" | "pmid"> {
  doi?: string | null;
  pmid?: string | null;
  licenseUrl?: string;
  termsUrl?: string;
  accessMethod: "primary_html_targeted_read" | "primary_guideline_pdf_targeted_read" | "licensed_europe_pmc_xml_targeted_read";
}

const nhsLicense = "Open Government Licence v3.0 where applicable; third-party material, logos and images excluded";
const nhsReuse = "Only underlying facts were checked and independently expressed. No prose, table, illustration or algorithm is reproduced. Contains public sector information licensed under the Open Government Licence v3.0. The existing reuse enum is conservative because it has no OGL category.";
const targeted = "Targeted factual verification only; no copyrighted expression, source excerpts, tables, figures, algorithms or clinical vignettes are stored or reproduced. Copyright is not treated as AI-use permission.";

const rawSources: SourceInput[] = [
  {
    id: S.cornwallSurgery,
    title: "Paediatric Surgery",
    completeCitation: "Faux W, Burns S. Paediatric Surgery. NHS Cornwall and Isles of Scilly Referral Management Service. Version 1.2; partial update 9 May 2025. Review date listed as 9 May 2026. Accessed 8 October 2026.",
    organizationOrJournal: "NHS Cornwall and Isles of Scilly Referral Management Service",
    authors: ["Will Faux", "S. Burns"],
    publicationYear: 2025,
    publicationDateNote: "The page identifies a partial update on 2025-05-09 and a review date on 2026-05-09; the latter is not assumed to be a completed update.",
    officialUrl: "https://rms.cornwall.nhs.uk/rms/primary_care_clinical_referral_criteria/rms/primary_care_clinical_referral_criteria/paediatrics/paediatric_surgery",
    sourceClass: "government_guidance",
    licenseLabel: "Copyright NHS/Kernow CCG; all rights reserved",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: targeted,
    authorityAssessment: "Local NHS referral guidance authored by a consultant pediatric surgeon and GP. Adequate for narrow referral facts; not a national operative guideline. Retractile-testis terminology and umbilical repair ages are retained as disagreements, not teaching rules.",
    usageRole: "both",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.nhsHernia,
    title: "Hernia",
    completeCitation: "NHS website. Hernia. Reviewed 19 May 2026. Accessed 8 October 2026.",
    organizationOrJournal: "NHS website",
    authors: ["NHS website editorial team"],
    publicationYear: 2026,
    publicationDateNote: "Page last reviewed 2026-05-19; next review due 2029-05-19.",
    officialUrl: "https://www.nhs.uk/conditions/hernia/",
    sourceClass: "government_guidance",
    licenseLabel: nhsLicense,
    licenseUrl: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
    termsUrl: "https://www.nhs.uk/our-policies/terms-and-conditions/",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: nhsReuse,
    authorityAssessment: "Current government patient guidance used only for general hernia location and dynamic bulge facts. Adult lifestyle advice and management recommendations are not transferred to children.",
    usageRole: "cross_check",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.nhsUmbilical,
    title: "Umbilical hernia",
    completeCitation: "NHS website. Umbilical hernia. Reviewed 24 November 2025. Accessed 8 October 2026.",
    organizationOrJournal: "NHS website",
    authors: ["NHS website editorial team"],
    publicationYear: 2025,
    publicationDateNote: "Page last reviewed 2025-11-24; next review due 2028-11-24.",
    officialUrl: "https://www.nhs.uk/conditions/umbilical-hernia/",
    sourceClass: "government_guidance",
    licenseLabel: nhsLicense,
    licenseUrl: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
    termsUrl: "https://www.nhs.uk/our-policies/terms-and-conditions/",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: nhsReuse,
    authorityAssessment: "Current government patient guidance. Used for navel location and to preserve disagreement about repair ages; no repair-age question is admitted.",
    usageRole: "cross_check",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.goshHernia,
    title: "Umbilical and epigastric hernia",
    completeCitation: "Great Ormond Street Hospital General Surgery Department and Child and Family Information Group. Umbilical and epigastric hernia. Reference 2016F1150; reviewed 1 July 2016. Accessed 8 October 2026.",
    organizationOrJournal: "Great Ormond Street Hospital for Children NHS Foundation Trust",
    authors: ["General Surgery Department", "Child and Family Information Group"],
    publicationYear: 2016,
    publicationDateNote: "Last review 2016-07-01; displayed next review 2017-07-01 is overdue. Used narrowly for anatomy, not current treatment timing.",
    officialUrl: "https://www.gosh.nhs.uk/conditions-and-treatments/conditions-we-treat/umbilical-and-epigastric-hernia/",
    sourceClass: "open_educational_resource",
    licenseLabel: "Copyright GOSH/UCL; private research and in-house noncommercial study conditions",
    termsUrl: "https://www.gosh.nhs.uk/terms-and-conditions/",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: `${targeted} Terms reviewed 2026-05-20 permit private research/study; no source material is distributed. Terms encourage hyperlinks and do not state an automated/AI access prohibition. Patient images are excluded.`,
    authorityAssessment: "Specialist pediatric hospital information, but dated. Basic epigastric/umbilical anatomy is used with an explicit dated-source limitation; treatment-age guidance is withheld.",
    usageRole: "both",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.cornwallNodes,
    title: "Cervical Lymphadenopathy in Children",
    completeCitation: "Vines L, Schick M; contributors Goyal S, Reddy V, Lambert A, McGraw-Allen K, Keaney C. Cervical Lymphadenopathy in Children. NHS Cornwall and Isles of Scilly Referral Management Service. Reviewed 10 October 2025. Accessed 8 October 2026.",
    organizationOrJournal: "NHS Cornwall and Isles of Scilly Referral Management Service",
    authors: ["Laura Vines", "Melanie Schick", "Shama Goyal", "Venkat Reddy", "Aileen Lambert", "Kate McGraw-Allen", "Claire Keaney"],
    publicationYear: 2025,
    publicationDateNote: "Review 2025-10-10; next review 2027-10-10. Its stated pathway population ends at the sixteenth birthday.",
    officialUrl: "https://rms.cornwall.nhs.uk/primary_care_clinical_referral_criteria/rms/primary_care_clinical_referral_criteria/paediatrics/lymphadenopathy",
    sourceClass: "government_guidance",
    licenseLabel: "Copyright NHS/Kernow CCG; all rights reserved",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: targeted,
    authorityAssessment: "Current local NHS pediatric pathway with pediatric, ENT and GP input. Supports observation/safety-net and red-flag referral; does not establish a diagnosis of malignancy or a universal biopsy rule.",
    usageRole: "evidence",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.cuaTestis,
    title: "Canadian Urological Association-Pediatric Urologists of Canada (CUA-PUC) guideline for the diagnosis, management, and followup of cryptorchidism",
    completeCitation: "Braga LH, Lorenzo AJ, Romao RLP. Canadian Urological Association-Pediatric Urologists of Canada (CUA-PUC) guideline for the diagnosis, management, and followup of cryptorchidism. Can Urol Assoc J. 2017;11(7):E251-E260. doi:10.5489/cuaj.4585.",
    organizationOrJournal: "Canadian Urological Association Journal",
    authors: ["Luis H. Braga", "Armando J. Lorenzo", "Rodrigo L. P. Romao"],
    publicationYear: 2017,
    publicationDateNote: "Published 2017-07-11. Older society guideline, cross-checked against eligible NHS information; no claim of a 2026 update.",
    doi: "10.5489/cuaj.4585",
    pmid: "28761584",
    officialUrl: "https://cuaj.ca/index.php/journal/article/view/4585",
    sourceClass: "professional_society_guideline",
    licenseLabel: "Copyright Canadian Urological Association; reproduction rights reserved",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: `${targeted} The publisher's guideline PDF was read for the specific examination definition and follow-up/referral distinctions; no algorithm or table was copied.`,
    authorityAssessment: "Professional society guideline with evidence grading. Adequate for the narrowly defined true-retractile versus acquired-ascent distinction; broader high/persistent-retractile terminology remains disputed and withheld.",
    usageRole: "both",
    accessMethod: "primary_guideline_pdf_targeted_read",
  },
  {
    id: S.cuhTestis,
    title: "Undescended testes and orchidopexy surgery - in children",
    completeCitation: "Cambridge University Hospitals NHS Foundation Trust, Paediatric Surgery and Urology. Undescended testes and orchidopexy surgery - in children. Document 1716, version 9; approved 7 November 2025. Accessed 8 October 2026.",
    organizationOrJournal: "Cambridge University Hospitals NHS Foundation Trust",
    authors: ["Paediatric Surgery and Urology Department"],
    publicationYear: 2025,
    publicationDateNote: "Approved 2025-11-07; version 9. The leaflet's institutional approval is not approval of this authored batch.",
    officialUrl: "https://www.cuh.nhs.uk/patient-information/undescended-testes-and-surgery-in-children/",
    sourceClass: "open_educational_resource",
    licenseLabel: "Copyright Cambridge University Hospitals NHS Foundation Trust",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: targeted,
    authorityAssessment: "Current pediatric hospital information, used as independent corroboration of observation for a true retractile testis. Source-specific surveillance intervals and procedure/anesthetic details are not authored.",
    usageRole: "cross_check",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.pectusReview,
    title: "The management of pectus excavatum in pediatric patients: a narrative review",
    completeCitation: "Scalise PN, Demehri FR. The management of pectus excavatum in pediatric patients: a narrative review. Transl Pediatr. 2023;12(2):208-220. doi:10.21037/tp-22-361.",
    organizationOrJournal: "Translational Pediatrics",
    authors: ["P. Nina Scalise", "Farokh R. Demehri"],
    publicationYear: 2023,
    publicationDateNote: "Published online 2023-01-31; February 2023 issue.",
    doi: "10.21037/tp-22-361",
    officialUrl: "https://tp.amegroups.org/article/view/108944/html",
    sourceClass: "narrative_review",
    licenseLabel: "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: "Underlying medical facts only, independently expressed and attributed to both authors and DOI. No article adaptation, excerpt, figure or table is distributed. The restricted/ND license is recorded explicitly; the schema has no CC BY-NC-ND category. No inference of unrestricted reuse or commercial permission.",
    authorityAssessment: "Pediatric surgery narrative review, not a formal guideline. Only one eligible substantive source was fully verified for this narrow referral objective; physiologic causation and postoperative benefit remain uncertain.",
    usageRole: "evidence",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.shtgBrace,
    title: "Chest wall bracing for children and young people with pectus carinatum",
    completeCitation: "Scottish Health Technologies Group, Healthcare Improvement Scotland. Chest wall bracing for children and young people with pectus carinatum. Published 11 February 2022. Accessed 8 October 2026.",
    organizationOrJournal: "Scottish Health Technologies Group, Healthcare Improvement Scotland",
    authors: ["Scottish Health Technologies Group"],
    publicationYear: 2022,
    publicationDateNote: "Advice published 2022-02-11; no later update is claimed.",
    officialUrl: "https://shtg.scot/our-advice/chest-wall-bracing-for-children-and-young-people-with-pectus-carinatum/",
    sourceClass: "government_guidance",
    licenseLabel: "Copyright Healthcare Improvement Scotland / SHTG",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: targeted,
    authorityAssessment: "Government health-technology assessment. Bracing evidence is mostly observational and heterogeneous; supports suitability assessment, not universal effectiveness, a pressure threshold or a wear schedule.",
    usageRole: "evidence",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.alderBrace,
    title: "Bracing for Pectus Deformities (PIAG 154)",
    completeCitation: "Alder Hey Children's NHS Foundation Trust, Orthotics Department. Bracing for Pectus Deformities (PIAG 154). Reviewed 28 July 2026. Accessed 8 October 2026.",
    organizationOrJournal: "Alder Hey Children's NHS Foundation Trust",
    authors: ["Orthotics Department"],
    publicationYear: 2026,
    publicationDateNote: "Reviewed 2026-07-28; next review 2029-06-12.",
    officialUrl: "https://www.alderhey.nhs.uk/conditions/patient-information-leaflets/bracing-for-pectus-deformities-piag-154/",
    sourceClass: "open_educational_resource",
    licenseLabel: "Copyright Alder Hey Children's NHS Foundation Trust",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: targeted,
    authorityAssessment: "Current specialist hospital orthotics information corroborating carinatum appearance and supervised brace fitting. Its patient instructions are not copied or prescribed in clinic.",
    usageRole: "cross_check",
    accessMethod: "primary_html_targeted_read",
  },
  {
    id: S.pilonidal,
    title: "Principles in treating pediatric patients with pilonidal disease - An expert perspective",
    completeCitation: "Metzger GA, Apfeld JC, Nishimura L, Lutz C, Deans KJ, Minneci PC. Principles in treating pediatric patients with pilonidal disease - An expert perspective. Ann Med Surg (Lond). 2021;64:102233. doi:10.1016/j.amsu.2021.102233. PMID:33868675; PMCID:PMC8040102.",
    organizationOrJournal: "Annals of Medicine and Surgery",
    authors: ["Gregory A. Metzger", "Jordan C. Apfeld", "Leah Nishimura", "Carley Lutz", "Katherine J. Deans", "Peter C. Minneci"],
    publicationYear: 2021,
    publicationDateNote: "Published 2021-03-27; April 2021 volume.",
    doi: "10.1016/j.amsu.2021.102233",
    pmid: "33868675",
    officialUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8040102/",
    sourceClass: "narrative_review",
    licenseLabel: "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    reuseStatus: "cc_by_4_0",
    reuseNotes: "Attributed to all authors, article title, DOI and CC BY 4.0. Independently authored factual synthesis; no source prose or clinical stem is reused. The actual article license was verified. PMC browser access showed a CAPTCHA; permitted licensed XML was instead read in memory through the official Europe PMC API, without bypassing access controls or saving the article.",
    authorityAssessment: "Pediatric surgery expert perspective rather than formal guideline or comparative trial. One adequate pediatric source; individualized conservative care is taught, with no universal hair-removal method, schedule or operation.",
    usageRole: "evidence",
    accessMethod: "licensed_europe_pmc_xml_targeted_read",
  },
  {
    id: S.cpsAssent,
    title: "Medical decision-making in paediatrics: Infancy to adolescence",
    completeCitation: "Coughlin KW; Canadian Paediatric Society Bioethics Committee. Medical decision-making in paediatrics: Infancy to adolescence. Paediatr Child Health. 2018;23(2):138-146. doi:10.1093/pch/pxx127. Posted 12 April 2018; reaffirmed 11 January 2024.",
    organizationOrJournal: "Canadian Paediatric Society / Paediatrics & Child Health",
    authors: ["Kevin W. Coughlin", "Canadian Paediatric Society Bioethics Committee"],
    publicationYear: 2018,
    publicationDateNote: "Posted 2018-04-12; reaffirmed 2024-01-11. Reaffirmation does not change the publication year.",
    doi: "10.1093/pch/pxx127",
    officialUrl: "https://cps.ca/en/documents/position/medical-decision-making-in-paediatrics-infancy-to-adolescence",
    sourceClass: "professional_society_guideline",
    licenseLabel: "Copyright Canadian Paediatric Society; reproduction requires permission",
    termsUrl: "https://cps.ca/en/policies-politiques/copyright",
    reuseStatus: "copyrighted_targeted_verification_only",
    reuseNotes: `${targeted} Copyright policy governs copying; no source content or logo is reproduced. No automated/AI-use restriction was stated in the checked policy. Only ethical participation facts, not Canadian legal rules, are used.`,
    authorityAssessment: "Reaffirmed professional society bioethics statement. One adequate source for child participation/assent; legal consent, mature-minor rules, emergency refusal and confidentiality depend on context and jurisdiction and are not authored.",
    usageRole: "evidence",
    accessMethod: "primary_html_targeted_read",
  },
];

export function linkSourcesToClaims(claims: EvidenceClaim[]) {
  return rawSources.map(({ doi = null, pmid = null, ...source }) => ({
    ...NEEDS_REVIEW, ...source, doi, pmid, accessedOn: CHECKED_ON,
    evidenceClaimIds: claims.filter((claim) => claim.sourceIds.includes(source.id)).map((claim) => claim.id),
  } satisfies ClinicalSource & Pick<SourceInput, "licenseUrl" | "termsUrl" | "accessMethod">));
}

/** Metadata for future reviewed UI assembly; these links never trigger gameplay retrieval. */
export const CLINICAL_LINK_POLICY = { target: "_blank", rel: "noopener noreferrer", retrieveDuringGameplay: false } as const;
