(()=>{
  const root=document.getElementById('phlebotomy-layout-proof'),canvas=root.querySelector('#phlebotomy-art'),ctx=canvas.getContext('2d'),status=root.querySelector('#phlebotomy-status'),orientationControl=root.querySelector('#phlebotomy-orientation'),overlay=root.querySelector('#phlebotomy-overlay'),optionalToggle=root.querySelector('#phlebotomy-optional'),targets=root.querySelector('#phlebotomy-targets');
  const SCALE=2,W=480,S=120,Y=130,radius=.16,step=.04,viewHeight=()=>state.orientation==='south'?430:550;
  const data=__DATA__,sprites=__SPRITES__,windowData=__WINDOW_DATA__,atlases={south:new Image(),east:new Image()},windowArt=new Image();atlases.south.src='data:image/webp;base64,__SOUTH__';atlases.east.src='data:image/webp;base64,__EAST__';windowArt.src='data:image/webp;base64,__WINDOW__';
  const worldSegments=['N1','N2','N3','S1','S2','S3','WA','WB','EA','EB'];
  const worldToEast={N1:'WC',N2:'WB',N3:'WA',S1:'EC',S2:'EB',S3:'EA',WA:'S1',WB:'S2',EA:'N1',EB:'N2'};
  const eastToWorld=Object.fromEntries(Object.entries(worldToEast).map(([world,local])=>[local,world]));
  const state={orientation:'south',doors:new Set(['S2']),adjacent:new Set(),selectedWorld:'S2',optional:true};
  const dimensions=()=>state.orientation==='south'?{cols:3,rows:2,x:60}:{cols:2,rows:3,x:120};
  const localSegments=()=>{const{cols,rows}=dimensions(),out=[];for(let i=1;i<=cols;i++)out.push(`N${i}`);for(let i=1;i<=cols;i++)out.push(`S${i}`);for(let i=0;i<rows;i++)out.push(`W${String.fromCharCode(65+i)}`);for(let i=0;i<rows;i++)out.push(`E${String.fromCharCode(65+i)}`);return out};
  const toLocal=world=>state.orientation==='south'?world:worldToEast[world],toWorld=local=>state.orientation==='south'?local:eastToWorld[local];
  const rotatePoint=p=>({x:p.y,y:3-p.x}),rotateRect=r=>({left:r.top,top:3-r.left-r.width,width:r.height,height:r.width});
  const base={
    chair:{id:'chair',label:'patient phlebotomy chair',ground:{x:1.5,y:.98},approach:{x:1.5,y:1.32},footprint:{left:1.05,top:.5,width:.9,height:.48},navigationBlocker:{left:1.05,top:.5,width:.9,height:.48},facing:'S',collision:'solid',persistence:'permanent'},
    stool:{id:'stool',label:'staff stool',ground:{x:1.5,y:1.7},approach:{x:1.5,y:1.7},footprint:{left:1.24,top:1.44,width:.52,height:.26},facing:'N',collision:'nonblocking',persistence:'permanent'},
    sink:{id:'sink',label:'sink cabinet and specimen tubes',ground:{x:.43,y:.3},footprint:{left:.03,top:0,width:.8,height:.3},conflicts:['N1','WA'],backedConflicts:['N1'],collision:'nonblocking',persistence:'optional'}
  };
  const poseFixture=fixture=>{if(state.orientation==='south')return structuredClone(fixture);const f=structuredClone(fixture);for(const key of ['ground','approach'])if(f[key])f[key]=rotatePoint(f[key]);for(const key of ['footprint','navigationBlocker'])if(f[key])f[key]=rotateRect(f[key]);if(f.facing)f.facing={S:'E',N:'W'}[f.facing]||f.facing;if(f.id==='sink'){f.rotationGround=structuredClone(f.ground);f.ground={x:.4,y:2.88};f.viewRegistrationOffset={x:.1,y:.31}}return f};
  const fixtures=()=>Object.fromEntries(Object.entries(base).map(([key,value])=>[key,poseFixture(value)]));
  const localDoors=()=>new Set([...state.doors].map(toLocal));
  const selectedLocal=()=>toLocal(state.selectedWorld);
  const hiddenOptional=()=>{if(!state.optional)return['sink'];return base.sink.conflicts.some(id=>state.doors.has(id))||[...state.adjacent].some(local=>base.sink.backedConflicts.includes(toWorld(local)))?['sink']:[]};
  const box=()=>{const d=dimensions();return{...d,bottom:Y+d.rows*S,east:d.x+d.cols*S}};
  const floorSurface=(left,top,width,height)=>{const b=box(),tile=24,startCol=Math.floor((left-b.x)/tile),endCol=Math.ceil((left+width-b.x)/tile),startRow=Math.floor((top-Y)/tile),endRow=Math.ceil((top+height-Y)/tile);ctx.save();ctx.beginPath();ctx.rect(left,top,width,height);ctx.clip();ctx.fillStyle='#eee7da';ctx.fillRect(left,top,width,height);for(let row=startRow;row<endRow;row++)for(let col=startCol;col<endCol;col++){const x=b.x+col*tile,y=Y+row*tile,tone=Math.abs(col*7+row*11)%9;ctx.fillStyle=tone===0?'rgba(196,139,148,.115)':tone===4?'rgba(145,132,119,.075)':'rgba(255,252,244,.055)';ctx.fillRect(x+1,y+1,tile-1,tile-1);const chip=Math.abs(col*17+row*23)%13;ctx.fillStyle=chip%3?'rgba(112,101,90,.10)':'rgba(181,111,126,.13)';ctx.fillRect(x+5+chip%11,y+4+(chip*3)%13,1,1);ctx.fillRect(x+15-(chip%5),y+16-(chip%7),1,1)}ctx.strokeStyle='rgba(122,108,94,.14)';ctx.lineWidth=1;for(let col=startCol;col<=endCol;col++){const x=b.x+col*tile+.5;ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+height);ctx.stroke()}for(let row=startRow;row<=endRow;row++){const y=Y+row*tile+.5;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left+width,y);ctx.stroke()}ctx.restore()};
  const hitSlot=id=>{const b=box(),i=id[0]==='N'||id[0]==='S'?Number(id.slice(1))-1:id.charCodeAt(1)-65;if(id[0]==='N')return{x:b.x+i*S,y:state.adjacent.has(id)?Y-29:Y-99,w:S,h:state.adjacent.has(id)?29:99};if(id[0]==='S')return{x:b.x+i*S,y:b.bottom,w:S,h:29};return{x:id[0]==='W'?b.x-14:b.east,y:Y+i*S,w:14,h:S}};
  function drawShell(){const b=box(),doors=localDoors(),rose='#e2c3ca',green='#58735a',dark='#294632',light='#789173',wood='#744a29',background='#f3ead3',cream='#efe1bd',wall=90,low=29,cap=14;ctx.clearRect(0,0,W,viewHeight());ctx.fillStyle=background;ctx.fillRect(0,0,W,viewHeight());floorSurface(b.x,Y,b.cols*S,b.rows*S);
    for(let i=0;i<b.cols;i++){const left=b.x+i*S,id=`N${i+1}`;if(state.adjacent.has(id)){ctx.clearRect(left,0,S,Y-low);ctx.fillStyle=green;ctx.fillRect(left,Y-low,S,low);ctx.fillStyle=light;ctx.fillRect(left,Y-low,S,4);ctx.fillStyle=dark;ctx.fillRect(left,Y-7,S,7)}else{ctx.fillStyle=rose;ctx.fillRect(left,Y-wall,S,wall);ctx.fillStyle='rgba(131,82,95,.055)';ctx.fillRect(left+12,Y-wall+30,S-24,2);ctx.fillStyle=green;ctx.fillRect(left,Y-23,S,23);ctx.fillStyle=light;ctx.fillRect(left,Y-23,S,4);ctx.fillStyle=dark;ctx.fillRect(left,Y-7,S,7);ctx.fillRect(left-1,Y-wall-9,S+2,9);ctx.fillStyle=light;ctx.fillRect(left-1,Y-wall-9,S+2,3)}}
    const westX=b.x-cap+2,eastX=b.east-2;for(const[right,px]of[[false,westX],[true,eastX]]){const neighbor=right?`N${b.cols}`:'N1',top=state.adjacent.has(neighbor)?Y-low:Y-wall-9;ctx.fillStyle=dark;ctx.fillRect(px,top,cap,b.bottom+29-top);ctx.fillStyle=light;ctx.fillRect(px+(right?0:cap-3),top,3,b.bottom+29-top)}
    for(let i=0;i<b.cols;i++){const left=b.x+i*S;ctx.fillStyle=cream;ctx.fillRect(left,b.bottom,S,29);ctx.fillStyle=green;ctx.fillRect(left,b.bottom+21,S,8);ctx.fillStyle=dark;ctx.fillRect(left,b.bottom-6,S,8);ctx.fillStyle=light;ctx.fillRect(left,b.bottom-6,S,3)}
    for(const id of doors){if(id[0]==='N'){const i=Number(id.slice(1))-1,left=b.x+i*S+12,right=b.x+(i+1)*S-12,backed=state.adjacent.has(id),top=backed?Y-low:Y-wall+8;ctx.clearRect(left,top,right-left,Y-top);ctx.fillStyle=wood;ctx.fillRect(left-5,top,5,Y-top);ctx.fillRect(right,top,5,Y-top);if(!backed)ctx.fillRect(left-5,top-5,right-left+10,6)}else if(id[0]==='S'){const i=Number(id.slice(1))-1,left=b.x+i*S+12,right=b.x+(i+1)*S-12;ctx.clearRect(left,b.bottom-6,right-left,35);floorSurface(left,b.bottom-6,right-left,35);ctx.fillStyle=wood;ctx.fillRect(left-5,b.bottom-8,5,37);ctx.fillRect(right,b.bottom-8,5,37)}else{const right=id[0]==='E',i=id.charCodeAt(1)-65,px=right?eastX:westX,top=Y+i*S+12,height=S-24,half=cap/2;ctx.clearRect(px,top,cap,height);if(right){floorSurface(px,top,half,height);ctx.clearRect(px+half,top,half,height)}else{ctx.clearRect(px,top,half,height);floorSurface(px+half,top,half,height)}ctx.fillStyle=wood;ctx.fillRect(px-2,top-3,cap+4,5);ctx.fillRect(px-2,top+height-2,cap+4,5)}}
  }
  function drawWindows(){const b=box(),doors=localDoors(),windows=[],frame=windowData.packedFrame,height=80,width=height*frame.w/frame.h,segments=state.orientation==='south'?['N2','N3']:['N1','N2'];for(const segment of segments){const i=Number(segment.slice(1))-1,visible=!doors.has(segment)&&!state.adjacent.has(segment),x=b.x+i*S+(S-width)/2,y=Y-86,entry={id:`window-${segment}`,segment,visible,hiddenBy:doors.has(segment)?'door':state.adjacent.has(segment)?'backed north':null,mount:'north wall',collision:'none',x,y,w:width,h:height,aspect:frame.w/frame.h};windows.push(entry);if(visible)ctx.drawImage(windowArt,frame.x,frame.y,frame.w,frame.h,x,y,width,height)}return windows}
  const contactFor=(view,id)=>{const source=sprites[view][id],contact={ground:{x:source.ground[0],y:source.ground[1]},height:source.renderedHeight};if(source.seat)contact.seat={x:source.seat[0],y:source.seat[1]};return contact};
  const drawSprite=(id,fixture)=>{const frame=data[state.orientation].packedFrames[id],contact=contactFor(state.orientation,id),scale=contact.height/frame.h,width=frame.w*scale,ground=fixture.ground,x=box().x+ground.x*S-contact.ground.x*scale,y=Y+ground.y*S-contact.ground.y*scale;ctx.drawImage(atlases[state.orientation],frame.x,frame.y,frame.w,frame.h,x,y,width,contact.height);const result={x,y,w:width,h:contact.height,groundContact:{x:x+contact.ground.x*scale,y:y+contact.ground.y*scale},sourceGround:contact.ground,aspect:frame.w/frame.h};if(contact.seat){result.seatContact={x:x+contact.seat.x*scale,y:y+contact.seat.y*scale};result.sourceSeat=contact.seat;result.seatRisePx=(contact.ground.y-contact.seat.y)*scale;result.seatShiftXPx=(contact.seat.x-contact.ground.x)*scale}return result};
  function drawFurniture(){const f=fixtures(),hidden=hiddenOptional(),draws={};if(!hidden.includes('sink'))draws.sink=drawSprite('sink',f.sink);draws.chair=drawSprite('chair',f.chair);draws.stool=drawSprite('stool',f.stool);f.chair.seat={x:(draws.chair.seatContact.x-box().x)/S,y:(draws.chair.seatContact.y-Y)/S};f.stool.seat={x:(draws.stool.seatContact.x-box().x)/S,y:(draws.stool.seatContact.y-Y)/S};return{fixtures:f,hidden,draws}}
  const inflated=r=>({left:r.left-radius,top:r.top-radius,right:r.left+r.width+radius,bottom:r.top+r.height+radius});
  const validPoint=(p,blocker,d)=>p.x>=radius-1e-6&&p.x<=d.cols-radius+1e-6&&p.y>=radius-1e-6&&p.y<=d.rows-radius+1e-6&&!(()=>{const r=inflated(blocker);return p.x>=r.left-1e-6&&p.x<=r.right+1e-6&&p.y>=r.top-1e-6&&p.y<=r.bottom+1e-6})();
  const doorCandidates=(id,blocker,d)=>{const values=[.28,.36,.5,.64,.72];if(id[0]==='N'||id[0]==='S'){const i=Number(id.slice(1))-1,y=id[0]==='N'?radius:d.rows-radius;return values.map(v=>({x:i+v,y})).filter(p=>validPoint(p,blocker,d))}const i=id.charCodeAt(1)-65,x=id[0]==='W'?radius:d.cols-radius;return values.map(v=>({x,y:i+v})).filter(p=>validPoint(p,blocker,d))};
  const key=p=>`${p.x.toFixed(2)},${p.y.toFixed(2)}`,simplify=path=>path.filter((p,i)=>i===0||i===path.length-1||Math.abs((path[i-1].x-p.x)*(path[i+1].y-p.y)-(path[i-1].y-p.y)*(path[i+1].x-p.x))>.0001);
  function bfs(from,to,blocker,d){const snap=p=>({x:Math.round(p.x/step)*step,y:Math.round(p.y/step)*step}),a=snap(from),z=snap(to);if(!validPoint(a,blocker,d)||!validPoint(z,blocker,d))return[];const queue=[a],prev=new Map([[key(a),null]]),points=new Map([[key(a),a]]),moves=[[step,0],[-step,0],[0,step],[0,-step]];while(queue.length){const p=queue.shift(),pk=key(p);if(pk===key(z)){const path=[];for(let k=pk;k;k=prev.get(k))path.unshift(points.get(k));return simplify(path)}for(const[dx,dy]of moves){const n=snap({x:p.x+dx,y:p.y+dy}),nk=key(n);if(validPoint(n,blocker,d)&&!prev.has(nk)){prev.set(nk,pk);points.set(nk,n);queue.push(n)}}}return[]}
  const routeCache={};const routeModel=f=>{if(routeCache[state.orientation])return routeCache[state.orientation];const d=dimensions(),blocker=f.chair.navigationBlocker,start=state.orientation==='south'?{x:1.5,y:1.84}:rotatePoint({x:1.5,y:1.84});const routes={};for(const id of localSegments()){let best=[];for(const target of doorCandidates(id,blocker,d)){const route=bfs(start,target,blocker,d);if(route.length&&(!best.length||route.length<best.length))best=route}routes[id]=best}return routeCache[state.orientation]={start,routes,uses:{patient:bfs(start,f.chair.approach,blocker,d),staff:bfs(start,f.stool.approach,blocker,d)}}};
  function drawOverlay(model,f){if(!overlay.checked)return;const b=box(),route=model.routes[selectedLocal()]||[];ctx.save();if(route.length){ctx.strokeStyle='#2f7090';ctx.lineWidth=3;ctx.beginPath();route.forEach((p,i)=>i?ctx.lineTo(b.x+p.x*S,Y+p.y*S):ctx.moveTo(b.x+p.x*S,Y+p.y*S));ctx.stroke()}for(const fixture of Object.values(f)){if(!fixture.footprint)continue;const q=fixture.footprint;ctx.setLineDash([5,4]);ctx.strokeStyle=fixture.collision==='solid'?'#8d5a47':'#2f7090';ctx.strokeRect(b.x+q.left*S,Y+q.top*S,q.width*S,q.height*S)}ctx.setLineDash([]);for(const[p,label,color]of[[f.chair.seat,`patient ${f.chair.facing}`,'#8d5a47'],[f.chair.approach,'patient approach','#a66d2b'],[f.stool.seat,`staff ${f.stool.facing}`,'#355f52'],[f.stool.approach,'staff approach','#2f7090']]){ctx.fillStyle=color;ctx.beginPath();ctx.arc(b.x+p.x*S,Y+p.y*S,5,0,Math.PI*2);ctx.fill();ctx.font='10px sans-serif';ctx.fillText(label,b.x+p.x*S+7,Y+p.y*S+3)}ctx.restore()}
  function render(){const height=viewHeight();if(canvas.height!==height*SCALE)canvas.height=height*SCALE;ctx.setTransform(SCALE,0,0,SCALE,0,0);ctx.imageSmoothingEnabled=true;drawShell();const windows=drawWindows(),furniture=drawFurniture(),model=routeModel(furniture.fixtures);drawOverlay(model,furniture.fixtures);for(const button of targets.querySelectorAll('button')){const q=hitSlot(button.dataset.local);Object.assign(button.style,{left:`${q.x/W*100}%`,top:`${q.y/height*100}%`,width:`${q.w/W*100}%`,height:`${q.h/height*100}%`})}const reachable=Object.values(model.routes).filter(path=>path.length).length,local=selectedLocal();status.innerHTML=`<strong>${state.orientation==='south'?'3 × 2 South view':'2 × 3 East view'}</strong> · ${local} (${state.selectedWorld} world) ${state.doors.has(state.selectedWorld)?'open':'closed'} · ${reachable}/10 approaches reachable<br>Patient ${furniture.fixtures.chair.facing} ${model.uses.patient.length?'reachable':'blocked'} · staff ${furniture.fixtures.stool.facing} ${model.uses.staff.length?'reachable':'blocked'} · hidden: ${furniture.hidden.join(', ')||'none'}`;root.querySelectorAll('[data-world]').forEach(button=>{const active=state.doors.has(button.dataset.world);button.setAttribute('aria-pressed',String(active));button.classList.toggle('btn-primary',active)});canvas.dataset.model=JSON.stringify({orientation:state.orientation,viewHeight:height,dimensions:dimensions(),segments:localSegments(),worldSegments,worldToLocal:Object.fromEntries(worldSegments.map(id=>[id,toLocal(id)])),doors:[...state.doors],localDoors:[...localDoors()],selectedWorld:state.selectedWorld,selectedLocal:local,adjacency:[...state.adjacent],hidden:furniture.hidden,windows,routes:model.routes,useRoutes:model.uses,fixtures:furniture.fixtures,draws:furniture.draws,spriteRevision:sprites.revision,shell:{tileSize:S,rearWallHeight:90,lowNorthHeight:29,sideCapWidth:14,southHeight:29,northDoorTransparent:true,sideDoorSeam:'floor-half-thickness',southDoorFloorBase:true,northColor:'#e2c3ca',floor:'24px ivory/rose terrazzo tiles',floorPatternSize:24,floorPatternOrigin:{x:box().x,y:Y},logicalGridDrawn:false},radius})}
  function toggleWorld(world){state.doors.has(world)?state.doors.delete(world):state.doors.add(world);state.selectedWorld=world;render()}
  function rebuildControls(){for(const id of ['phlebotomy-north','phlebotomy-south','phlebotomy-west','phlebotomy-east','phlebotomy-adjacency','phlebotomy-targets'])root.querySelector(`#${id}`).replaceChildren();for(const local of localSegments()){const world=toWorld(local),side={N:'north',S:'south',W:'west',E:'east'}[local[0]],button=document.createElement('button');button.type='button';button.className='btn btn-sm btn-outline-secondary';button.textContent=local;button.dataset.local=local;button.dataset.world=world;button.setAttribute('aria-label',`${local} doorway, world ${world}`);button.addEventListener('click',()=>toggleWorld(world));root.querySelector(`#phlebotomy-${side}`).append(button);const hit=button.cloneNode(true);hit.className='phleb-hit';hit.textContent='';hit.addEventListener('click',()=>toggleWorld(world));targets.append(hit)}const d=dimensions();for(let i=1;i<=d.cols;i++){const id=`N${i}`,label=document.createElement('label');label.className='form-check form-check-inline';label.innerHTML=`<input class="form-check-input" type="checkbox" data-adjacent="${id}"><span class="form-check-label">${id}</span>`;label.querySelector('input').addEventListener('change',event=>{event.target.checked?state.adjacent.add(id):state.adjacent.delete(id);render()});root.querySelector('#phlebotomy-adjacency').append(label)}render()}
  orientationControl.addEventListener('change',event=>{state.orientation=event.target.value;state.adjacent.clear();rebuildControls()});overlay.addEventListener('change',render);optionalToggle.addEventListener('change',event=>{state.optional=event.target.checked;render()});atlases.south.onload=render;atlases.east.onload=render;windowArt.onload=render;rebuildControls();
  window.__phlebotomyProof={state,render,rebuildControls,toLocal,toWorld,localSegments,fixtures,routeModel,ready:()=>atlases.south.complete&&atlases.east.complete&&windowArt.complete&&atlases.south.naturalWidth>0&&atlases.east.naturalWidth>0&&windowArt.naturalWidth>0};
})();
