const fs=require('fs'),path=require('path'),crypto=require('crypto'),{chromium}=require('playwright');
const dir=__dirname,source=path.join(dir,'phlebotomy-layout.html'),evidence=path.join(dir,'evidence'),chrome='C:/Program Files/Google/Chrome/Application/chrome.exe';
const assert=(value,message)=>{if(!value)throw new Error(message)},near=(a,b,e=.02)=>Math.abs(a-b)<=e;
(async()=>{
  const html=fs.readFileSync(source,'utf8');assert(Buffer.byteLength(html)<1_000_000,'fragment must remain below 1 MB');assert(!/<(?:html|head|body|!doctype)/i.test(html),'deliverable must remain an HTML fragment');
  fs.mkdirSync(evidence,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:chrome}),page=await browser.newPage({viewport:{width:1000,height:1050},deviceScaleFactor:1});const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.setContent(`<main>${html}</main>`);await page.waitForFunction(()=>window.__phlebotomyProof?.ready()&&document.querySelector('#phlebotomy-art').dataset.model,{timeout:30000});
  const read=()=>page.evaluate(()=>JSON.parse(document.querySelector('#phlebotomy-art').dataset.model));
  const expectedMap={N1:'WC',N2:'WB',N3:'WA',S1:'EC',S2:'EB',S3:'EA',WA:'S1',WB:'S2',EA:'N1',EB:'N2'};
  for(const orientation of ['south','east']){
    await page.locator('#phlebotomy-orientation').selectOption(orientation);let m=await read();
    assert(m.segments.length===10,`${orientation}: ten local segments`);assert(m.worldSegments.length===10,`${orientation}: ten world segments`);assert(await page.locator('[data-world]:not(.phleb-hit)').count()===10,`${orientation}: ten visible door buttons`);assert(await page.locator('.phleb-hit').count()===10,`${orientation}: ten canvas targets`);assert(await page.locator('[data-adjacent]').count()===(orientation==='south'?3:2),`${orientation}: backed controls match north width`);
    assert(m.dimensions.cols===(orientation==='south'?3:2)&&m.dimensions.rows===(orientation==='south'?2:3),`${orientation}: room dimensions`);assert(Object.values(m.routes).every(route=>route.length>0),`${orientation}: all doorway routes reachable`);assert(m.useRoutes.patient.length&&m.useRoutes.staff.length,`${orientation}: both use approaches reachable`);
    assert(m.shell.rearWallHeight===90&&m.shell.lowNorthHeight===29&&m.shell.sideCapWidth===14&&m.shell.southHeight===29,`${orientation}: common shell dimensions`);assert(m.shell.northDoorTransparent&&m.shell.sideDoorSeam==='floor-half-thickness'&&m.shell.southDoorFloorBase,`${orientation}: door rendering contract`);assert(m.shell.northColor==='#e2c3ca'&&m.shell.floor==='24px ivory/rose terrazzo tiles'&&m.shell.floorPatternSize===24&&!m.shell.logicalGridDrawn,`${orientation}: small floor pattern without gameplay grid`);assert(m.shell.floorPatternOrigin.x===m.dimensions.x&&m.shell.floorPatternOrigin.y===130,`${orientation}: floor pattern anchored to room origin`);
    const expectedWindows=orientation==='south'?['N2','N3']:['N1','N2'];assert(m.windows.length===2&&m.windows.every(window=>window.visible)&&m.windows.map(window=>window.segment).join(',')===expectedWindows.join(','),`${orientation}: approved north window installation`);for(const window of m.windows){const i=Number(window.segment.slice(1))-1;assert(window.collision==='none'&&window.mount==='north wall',`${orientation}: ${window.segment} wall-only contract`);assert(near(window.h,80)&&near(window.y,44)&&near(window.aspect,1213/1060,.0001),`${orientation}: ${window.segment} registered source aspect/height`);assert(near(window.x,m.dimensions.x+i*120+(120-window.w)/2),`${orientation}: ${window.segment} centered`) }
    const chair=m.fixtures.chair,stool=m.fixtures.stool;assert(chair.collision==='solid'&&stool.collision==='nonblocking',`${orientation}: collision ownership`);assert(chair.facing===(orientation==='south'?'S':'E')&&stool.facing===(orientation==='south'?'N':'W'),`${orientation}: seated cardinal directions`);
    const expectedChair=orientation==='south'?{x:1.5,y:.98,left:1.05,top:.5,width:.9,height:.48}:{x:.98,y:1.5,left:.5,top:1.05,width:.48,height:.9};assert(near(chair.ground.x,expectedChair.x)&&near(chair.ground.y,expectedChair.y),`${orientation}: chair ground transform`);for(const key of ['left','top','width','height'])assert(near(chair.navigationBlocker[key],expectedChair[key]),`${orientation}: chair blocker ${key}`);
    assert(near(stool.ground.x,orientation==='south'?1.5:1.7)&&near(stool.ground.y,orientation==='south'?1.7:1.5),`${orientation}: stool transform`);
    for(const [id,route]of Object.entries(m.routes)){const block=chair.navigationBlocker,inflate={left:block.left-m.radius,top:block.top-m.radius,right:block.left+block.width+m.radius,bottom:block.top+block.height+m.radius};for(let i=1;i<route.length;i++){const a=route[i-1],b=route[i],distance=Math.hypot(b.x-a.x,b.y-a.y),samples=Math.max(1,Math.ceil(distance/.02));for(let n=0;n<=samples;n++){const t=n/samples,p={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t};assert(p.x>=m.radius-.001&&p.x<=m.dimensions.cols-m.radius+.001&&p.y>=m.radius-.001&&p.y<=m.dimensions.rows-m.radius+.001,`${orientation}/${id}: route within room`);assert(!(p.x>=inflate.left-.001&&p.x<=inflate.right+.001&&p.y>=inflate.top-.001&&p.y<=inflate.bottom+.001),`${orientation}/${id}: route clears inflated chair`)}}const end=route[route.length-1],offset=id[0]==='N'||id[0]==='S'?end.x-(Number(id.slice(1))-1):end.y-(id.charCodeAt(1)-65);assert(offset>=.16&&offset<=.84,`${orientation}/${id}: endpoint clears jamb`)}
    const chairDraw=m.draws.chair,stoolDraw=m.draws.stool,sinkDraw=m.draws.sink;assert(near(chairDraw.aspect,orientation==='south'?648/748:589/807,.0001),`${orientation}: chair source aspect`);assert(near(stoolDraw.aspect,orientation==='south'?405/430:409/517,.0001),`${orientation}: stool source aspect`);assert(sinkDraw&&near(sinkDraw.aspect,orientation==='south'?555/698:429/813,.0001),`${orientation}: sink source aspect`);assert(near(chairDraw.h,orientation==='south'?143:164.45,.01)&&near(stoolDraw.h,orientation==='south'?66.25:76.19,.01)&&near(sinkDraw.h,orientation==='south'?120.73:138.84,.01),`${orientation}: approved revision heights`);assert(near(chairDraw.groundContact.x,(orientation==='south'?60:120)+chair.ground.x*120,.02)&&near(chairDraw.groundContact.y,130+chair.ground.y*120,.02),`${orientation}: chair ground registration`);
    if(orientation==='east'){assert(near(chairDraw.sourceGround.x,319)&&near(chairDraw.sourceGround.y,793)&&near(chairDraw.sourceSeat.x,539)&&near(chairDraw.sourceSeat.y,512),'east: true cropped chair contacts');assert(near(stoolDraw.sourceGround.x,216)&&near(stoolDraw.sourceGround.y,498)&&near(stoolDraw.sourceSeat.x,217)&&near(stoolDraw.sourceSeat.y,123),'east: true cropped stool contacts');assert(chairDraw.seatShiftXPx>44&&chairDraw.seatShiftXPx<46&&chairDraw.seatRisePx>57&&chairDraw.seatRisePx<58,'east: source-derived chair seat shift/rise');assert(stoolDraw.seatRisePx>55&&stoolDraw.seatRisePx<56&&Math.abs(chairDraw.seatContact.y-stoolDraw.seatContact.y)<3,'east: patient/staff visible seats align from source contacts');assert(near(m.fixtures.sink.rotationGround.x,.3)&&near(m.fixtures.sink.rotationGround.y,2.57)&&near(m.fixtures.sink.ground.x,.4)&&near(m.fixtures.sink.ground.y,2.88),'east: sink rotation anchor plus planted view registration');assert(near(m.fixtures.sink.viewRegistrationOffset.x,.1)&&near(m.fixtures.sink.viewRegistrationOffset.y,.31),'east: explicit sink view-registration offset');assert(near(sinkDraw.groundContact.x,120+.4*120)&&near(sinkDraw.groundContact.y,130+2.88*120),'east: sink source base planted at view registration');for(const [world,local]of Object.entries(expectedMap))assert(m.worldToLocal[world]===local,`east: ${world} remaps to ${local}`)}
  }
  await page.evaluate(()=>{const p=window.__phlebotomyProof;p.state.orientation='south';p.state.adjacent.clear();p.state.doors=new Set(['S2']);p.state.optional=true;p.rebuildControls()});
  await page.evaluate(()=>{const p=window.__phlebotomyProof;p.state.doors=new Set(['N1']);p.render()});let m=await read();assert(m.hidden.includes('sink')&&m.windows.map(window=>window.segment).join(',')==='N2,N3'&&!m.windows.some(window=>window.segment==='N1'),'south: N1 window remains uninstalled when N1 door hides sink');await page.evaluate(()=>{const p=window.__phlebotomyProof;p.state.doors.clear();p.render()});m=await read();assert(!m.hidden.includes('sink')&&!m.windows.some(window=>window.segment==='N1'),'south: N1 window remains uninstalled when sink is visible');
  let failures=await page.evaluate(()=>{const p=window.__phlebotomyProof,ids=['N1','N2','N3','S1','S2','S3','WA','WB','EA','EB'],bad=[];for(let mask=0;mask<1024;mask++){p.state.doors=new Set(ids.filter((_,i)=>mask&(1<<i)));p.render();const model=JSON.parse(document.querySelector('#phlebotomy-art').dataset.model),sink=model.hidden.includes('sink'),windows=model.windows.every(window=>window.visible===!model.localDoors.includes(window.segment));if(sink!==Boolean((mask&1)||(mask&(1<<6)))||!windows)bad.push(mask)}return bad});assert(!failures.length,`south door/window masks fail: ${failures.join(',')}`);
  failures=await page.evaluate(()=>{const p=window.__phlebotomyProof,bad=[];for(let mask=0;mask<8;mask++){p.state.doors=new Set();p.state.adjacent=new Set(['N1','N2','N3'].filter((_,i)=>mask&(1<<i)));p.render();const model=JSON.parse(document.querySelector('#phlebotomy-art').dataset.model),sink=model.hidden.includes('sink'),windows=model.windows.every(window=>window.visible===!model.adjacency.includes(window.segment));if(sink!==Boolean(mask&1)||!windows)bad.push(mask)}return bad});assert(!failures.length,`south backed/window masks fail: ${failures.join(',')}`);
  await page.locator('#phlebotomy-orientation').selectOption('east');
  failures=await page.evaluate(()=>{const p=window.__phlebotomyProof,ids=['N1','N2','N3','S1','S2','S3','WA','WB','EA','EB'],bad=[];for(let mask=0;mask<1024;mask++){p.state.doors=new Set(ids.filter((_,i)=>mask&(1<<i)));p.render();const model=JSON.parse(document.querySelector('#phlebotomy-art').dataset.model),sink=model.hidden.includes('sink'),windows=model.windows.every(window=>window.visible===!model.localDoors.includes(window.segment));if(sink!==Boolean((mask&1)||(mask&(1<<6)))||!windows)bad.push(mask)}return bad});assert(!failures.length,`east door/window masks fail: ${failures.join(',')}`);
  failures=await page.evaluate(()=>{const p=window.__phlebotomyProof,bad=[];for(let mask=0;mask<4;mask++){p.state.doors=new Set();p.state.adjacent=new Set(['N1','N2'].filter((_,i)=>mask&(1<<i)));p.render();const model=JSON.parse(document.querySelector('#phlebotomy-art').dataset.model),windows=model.windows.every(window=>window.visible===!model.adjacency.includes(window.segment));if(model.hidden.includes('sink')||!windows)bad.push(mask)}return bad});assert(!failures.length,`east backed/window masks fail: ${failures.join(',')}`);
  await page.evaluate(()=>{const p=window.__phlebotomyProof;p.state.doors=new Set(['S2']);p.state.adjacent.clear();p.render()});m=await read();assert(!m.hidden.includes('sink')&&m.localDoors.includes('EB'),'east: S2 maps EB and does not hide sink');const canvasBox=await page.locator('#phlebotomy-art').boundingBox();await page.mouse.click(canvasBox.x+113/480*canvasBox.width,canvasBox.y+430/550*canvasBox.height);m=await read();assert(m.doors.includes('N1')&&m.hidden.includes('sink'),'physical east WC canvas coordinate toggles world N1 and hides sink');
  const keyButton=page.locator('[data-world="N1"]:not(.phleb-hit)');await keyButton.focus();await page.keyboard.press('Enter');m=await read();assert(!m.doors.includes('N1')&&!m.hidden.includes('sink'),'keyboard restores N1/sink');
  await page.locator('#phlebotomy-optional').uncheck();m=await read();assert(m.hidden.includes('sink'),'optional toggle hides sink');await page.locator('#phlebotomy-optional').check();
  await page.locator('#phlebotomy-overlay').check();await page.screenshot({path:path.join(evidence,'phlebotomy-east-overlay.png'),fullPage:true});await page.locator('#phlebotomy-orientation').selectOption('south');m=await read();assert(m.viewHeight===430&&await page.locator('#phlebotomy-art').getAttribute('height')==='860','south canvas trims to 430 CSS pixels');await page.screenshot({path:path.join(evidence,'phlebotomy-south-desktop.png'),fullPage:true});
  await page.setViewportSize({width:320,height:1000});await page.screenshot({path:path.join(evidence,'phlebotomy-south-320.png'),fullPage:true});const narrow=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,root:document.querySelector('#phlebotomy-layout-proof').getBoundingClientRect().width}));assert(narrow.scroll<=narrow.client&&narrow.root<=320,'320px layout must not overflow');
  await page.evaluate(()=>{const p=window.__phlebotomyProof;p.state.orientation='south';p.state.doors=new Set(['S2']);p.state.adjacent.clear();p.state.selectedWorld='S2';p.state.optional=true;document.querySelector('#phlebotomy-orientation').value='south';document.querySelector('#phlebotomy-optional').checked=true;document.querySelector('#phlebotomy-overlay').checked=false;p.rebuildControls()});m=await read();assert(m.orientation==='south'&&m.doors.length===1&&m.doors[0]==='S2'&&!m.hidden.length,'final default resets to South/S2 with optional sink visible');
  assert(errors.length===0,`page errors: ${errors.join('; ')}`);await browser.close();const digest=crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex').toUpperCase();console.log(`PASS phlebotomy revision: 2 orientations, 20 door routes, 2048 door/window masks, 12 backed-window masks, contacts/aspects/scales, planted East sink, floor contract, physical canvas click, keyboard, desktop/320; ${Buffer.byteLength(html)} bytes; SHA256 ${digest}`);
})().catch(error=>{console.error(error.stack||error);process.exit(1)});
