import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { GRAY_VIEWS, grayPose, grayStandingPose, grayStarJumpPose, loadGrayRigV1, renderGrayClipboard, renderGraySeated, renderGrayStarJump, renderGrayV1 } from './gray-rig-v1.mjs';

const repo=resolve(import.meta.dirname,'../../../..'),output=resolve(repo,'artifacts/character-movement/gray-braid-v1');mkdirSync(output,{recursive:true});
const sha256=bytes=>createHash('sha256').update(bytes).digest('hex'),loaded=await loadGrayRigV1(repo),loadedBefore=await loadGrayRigV1(repo);loadedBefore.enableWestTrailingCuffRegistration=false;
const priorManifestPath=resolve(output,'manifest.json'),priorManifest=existsSync(priorManifestPath)?JSON.parse(readFileSync(priorManifestPath,'utf8')):null;
function save(relative,canvas){const path=resolve(output,relative);mkdirSync(dirname(path),{recursive:true});const bytes=canvas.toBuffer('image/png');writeFileSync(path,bytes);return{file:relative.replaceAll('\\','/'),sha256:sha256(bytes),width:canvas.width,height:canvas.height};}
function tileSheet(items,columns=4,scale=1,labelHeight=22){const cell={width:160*scale,height:320*scale},rows=Math.ceil(items.length/columns),canvas=createCanvas(cell.width*columns,(cell.height+labelHeight)*rows),context=canvas.getContext('2d');context.fillStyle='#ded8ce';context.fillRect(0,0,canvas.width,canvas.height);context.font='bold 12px sans-serif';context.textBaseline='middle';for(const[index,item]of items.entries()){const x=index%columns*cell.width,y=Math.floor(index/columns)*(cell.height+labelHeight);context.fillStyle='#20242a';context.fillRect(x,y,cell.width,labelHeight);context.fillStyle='#fff';context.fillText(item.label,x+5,y+labelHeight/2);context.imageSmoothingEnabled=false;context.drawImage(item.canvas,x,y+labelHeight,cell.width,cell.height);}return canvas;}

const legProofCases=[['east','01'],['east','05'],['west','01'],['west','05']],legBaselines={};
for(const[view,id]of legProofCases){const key=`${view}-${id}`,baseline=resolve(output,`reviews/leg-baseline/${key}.png`),current=resolve(output,`frames/walk/${view}/${id}.png`);mkdirSync(dirname(baseline),{recursive:true});if(!existsSync(baseline)){if(!existsSync(current))throw new Error(`missing prior leg baseline ${current}`);writeFileSync(baseline,readFileSync(current));}legBaselines[key]=await loadImage(baseline);}

const frames={stand:{},walk:{}};
for(const view of GRAY_VIEWS){const standing=renderGrayV1(loaded,grayStandingPose(view));frames.stand[view]=save(`frames/stand/${view}.png`,standing.canvas);frames.walk[view]={};for(let index=0;index<8;index+=1){const rendered=renderGrayV1(loaded,grayPose(view,index)),id=String(index+1).padStart(2,'0');frames.walk[view][id]=save(`frames/walk/${view}/${id}.png`,rendered.canvas);}}

const representative=[];for(const phase of ['stand','03','07'])for(const view of GRAY_VIEWS){const canvas=phase==='stand'?renderGrayV1(loaded,grayStandingPose(view)).canvas:renderGrayV1(loaded,grayPose(view,Number(phase)-1)).canvas;representative.push({label:`${view} ${phase}`,canvas});}
const representativeRecord=save('gray-all-view-representative.png',tileSheet(representative,4));
const directionContacts={};for(const view of GRAY_VIEWS){const items=[];for(let index=0;index<8;index+=1)items.push({label:`${view} ${String(index+1).padStart(2,'0')}`,canvas:renderGrayV1(loaded,grayPose(view,index)).canvas});directionContacts[view]=save(`gray-walk-${view}-contact.png`,tileSheet(items,4));}
function markedWest(loadedVariant,index){const rendered=renderGrayV1(loadedVariant,grayPose('west',index)),canvas=createCanvas(160,320),context=canvas.getContext('2d');context.drawImage(rendered.canvas,0,0);for(const side of ['left','right']){const leg=rendered.metadata.legs[side];context.strokeStyle=side==='left'?'#00d9ff':'#ff4fd8';context.lineWidth=2;context.beginPath();context.moveTo(leg.joints.ankle.x-4,leg.joints.ankle.y);context.lineTo(leg.joints.ankle.x+4,leg.joints.ankle.y);context.moveTo(leg.joints.ankle.x,leg.joints.ankle.y-4);context.lineTo(leg.joints.ankle.x,leg.joints.ankle.y+4);context.stroke();context.strokeStyle='#ffe359';context.strokeRect(leg.shoeDestination.x,leg.shoeDestination.y,leg.shoeDestination.width,leg.shoeDestination.height);}return canvas;}
const westTrailingItems=[];for(let index=0;index<8;index+=1){const id=String(index+1).padStart(2,'0');westTrailingItems.push({label:`west ${id} · prior uniform heel`,canvas:markedWest(loadedBefore,index)},{label:`west ${id} · cuff registration`,canvas:markedWest(loaded,index)});}const westTrailingProof=save('gray-west-trailing-cuff-before-after.png',tileSheet(westTrailingItems,4));
const westLegOnly=createCanvas(880,520),westLegOnlyContext=westLegOnly.getContext('2d'),westLegCrop={x:24,y:184,width:112,height:120};westLegOnlyContext.fillStyle='#ded8ce';westLegOnlyContext.fillRect(0,0,880,520);westLegOnlyContext.font='bold 13px sans-serif';westLegOnlyContext.textBaseline='middle';for(const [row,index] of [0,4].entries())for(const [column,[label,variant]] of [['prior uniform heel',loadedBefore],['cuff registration',loaded]].entries()){const x=column*440,y=row*260,canvas=renderGrayV1(variant,grayPose('west',index)).canvas;westLegOnlyContext.fillStyle='#20242a';westLegOnlyContext.fillRect(x,y,440,24);westLegOnlyContext.fillStyle='#fff';westLegOnlyContext.fillText(`west ${String(index+1).padStart(2,'0')} · ${label}`,x+8,y+12);westLegOnlyContext.imageSmoothingEnabled=false;westLegOnlyContext.drawImage(canvas,westLegCrop.x,westLegCrop.y,westLegCrop.width,westLegCrop.height,x,y+24,440,236);}const westLegOnlyProof=save('gray-west-trailing-leg-only-4x-before-after.png',westLegOnly);
const legProof=createCanvas(440,960),legProofContext=legProof.getContext('2d'),legCrop={x:25,y:185,width:110,height:120},legCell={width:220,height:240};legProofContext.fillStyle='#ded8ce';legProofContext.fillRect(0,0,legProof.width,legProof.height);legProofContext.font='bold 12px sans-serif';legProofContext.textBaseline='middle';
for(const[row,[view,id]]of legProofCases.entries()){const rendered=renderGrayV1(loaded,grayPose(view,Number(id)-1));for(const[column,kind]of ['before','after'].entries()){const x=column*legCell.width,y=row*legCell.height;legProofContext.fillStyle='#20242a';legProofContext.fillRect(x,y,legCell.width,20);legProofContext.fillStyle='#fff';legProofContext.fillText(`${view} ${id} · ${kind}`,x+5,y+10);legProofContext.imageSmoothingEnabled=false;legProofContext.drawImage(kind==='before'?legBaselines[`${view}-${id}`]:rendered.canvas,legCrop.x,legCrop.y,legCrop.width,legCrop.height,x,y+20,legCell.width,legCell.height-20);for(const[side,color]of [['left','#00d9ff'],['right','#ff4fd8']]){const ankle=rendered.metadata.legs[side].joints.ankle,px=x+(ankle.x-legCrop.x)*2,py=y+20+(ankle.y-legCrop.y)*(220/120);legProofContext.strokeStyle=color;legProofContext.lineWidth=2;legProofContext.beginPath();legProofContext.moveTo(px-6,py);legProofContext.lineTo(px+6,py);legProofContext.moveTo(px,py-6);legProofContext.lineTo(px,py+6);legProofContext.stroke();}}}
const legAlignmentProof=save('gray-profile-leg-alignment-before-after.png',legProof);

const original=await loadImage(resolve(repo,loaded.provenance.original.path)),proof=createCanvas(960,660),proofContext=proof.getContext('2d');proofContext.font='bold 13px sans-serif';proofContext.textBaseline='middle';
for(const[column,view]of GRAY_VIEWS.entries()){
  const record=loaded.provenance.identity[view],x=column*240;
  proofContext.fillStyle='#20242a';proofContext.fillRect(x,0,240,20);proofContext.fillStyle='#fff';proofContext.fillText(`${view} · original crop`,x+6,10);proofContext.drawImage(original,...record.crop,x,20,240,310);
  proofContext.fillStyle='#20242a';proofContext.fillRect(x,330,240,20);proofContext.fillStyle='#fff';proofContext.fillText(`${view} · exact RGB layers`,x+6,340);proofContext.fillStyle='#101216';proofContext.fillRect(x,350,240,310);proofContext.drawImage(loaded.identity[view].tail,x,350);proofContext.drawImage(loaded.identity[view].face,x,350);
}
const identityProof=save('gray-original-vs-extracted-identity.png',proof);
const headProof=createCanvas(800,420),headProofContext=headProof.getContext('2d');headProofContext.font='bold 12px sans-serif';headProofContext.textBaseline='middle';
for(const[column,view]of GRAY_VIEWS.entries()){const x=column*200,record=loaded.provenance.identity[view],headCrop=[28,25,130,115];headProofContext.fillStyle='#20242a';headProofContext.fillRect(x,0,200,20);headProofContext.fillRect(x,210,200,20);headProofContext.fillStyle='#fff';headProofContext.fillText(`${view} · source head`,x+5,10);headProofContext.fillText(`${view} · retained RGB`,x+5,220);headProofContext.imageSmoothingEnabled=false;headProofContext.drawImage(original,record.crop[0]+headCrop[0],record.crop[1]+headCrop[1],headCrop[2],headCrop[3],x,20,200,177);headProofContext.fillStyle='#101216';headProofContext.fillRect(x,230,200,177);headProofContext.drawImage(loaded.identity[view].face,headCrop[0],headCrop[1],headCrop[2],headCrop[3],x,230,200,177);}
const headCoverageProof=save('gray-head-source-coverage.png',headProof);
const proportionProof=createCanvas(960,684),proportionContext=proportionProof.getContext('2d');proportionContext.font='bold 13px sans-serif';proportionContext.textBaseline='middle';
for(const[column,view]of GRAY_VIEWS.entries()){
  const x=column*240,record=loaded.provenance.identity[view];
  proportionContext.fillStyle='#ded8ce';proportionContext.fillRect(x,22,240,320);proportionContext.fillRect(x,364,240,320);proportionContext.save();proportionContext.beginPath();proportionContext.rect(x,22,240,320);proportionContext.clip();proportionContext.drawImage(original,...record.crop,x,9,240,310);proportionContext.restore();proportionContext.drawImage(renderGrayV1(loaded,grayStandingPose(view)).canvas,x+40,364);
  proportionContext.fillStyle='#20242a';proportionContext.fillRect(x,0,240,22);proportionContext.fillRect(x,342,240,22);proportionContext.fillStyle='#fff';proportionContext.fillText(`${view} · approved source`,x+6,11);proportionContext.fillText(`${view} · fitted stand`,x+6,353);
}
const proportionRecord=save('gray-source-vs-fitted-proportions.png',proportionProof);
const sourceReferences={};for(const view of GRAY_VIEWS){const record=loaded.provenance.identity[view],canvas=createCanvas(160,320),context=canvas.getContext('2d');context.drawImage(original,...record.crop,80-record.sourceHipX,-13,240,310);sourceReferences[view]=save(`source-reference/${view}.png`,canvas);}
const actions={starJump:{south:{}},sitting:{},clipboard:{}};const jumpItems=[];for(let index=0;index<8;index++){const pose=grayStarJumpPose(index),rendered=renderGrayStarJump(loaded,pose),id=String(index+1).padStart(2,'0');actions.starJump.south[id]=save(`frames/star-jump/south/${id}.png`,rendered.canvas);jumpItems.push({label:`jump ${id} · ${pose.stage}`,canvas:rendered.canvas});}
const sitItems=[];for(const view of GRAY_VIEWS){const rendered=renderGraySeated(loaded,view);actions.sitting[view]=save(`frames/sit/${view}.png`,rendered.canvas);sitItems.push({label:`sit ${view}`,canvas:rendered.canvas});}
const clipboardRendered=renderGrayClipboard(loaded);actions.clipboard.south=save('frames/clipboard/south.png',clipboardRendered.canvas);
if(priorManifest){for(const view of ['south','east','north']){assert.equal(frames.stand[view].sha256,priorManifest.frames.stand[view].sha256,`${view} standing changed during West heel correction`);for(const id of Object.keys(frames.walk[view]))assert.equal(frames.walk[view][id].sha256,priorManifest.frames.walk[view][id].sha256,`${view} ${id} changed during West heel correction`);}for(const [id,frame]of Object.entries(actions.starJump.south))assert.equal(frame.sha256,priorManifest.actions.starJump.south[id].sha256,`jump ${id} changed during West heel correction`);for(const view of GRAY_VIEWS)assert.equal(actions.sitting[view].sha256,priorManifest.actions.sitting[view].sha256,`sit ${view} changed during West heel correction`);assert.equal(actions.clipboard.south.sha256,priorManifest.actions.clipboard.south.sha256,'clipboard changed during West heel correction');}
const actionReview={jump:save('gray-star-jump-south-contact.png',tileSheet(jumpItems,4)),sitting:save('gray-sitting-four-view-contact.png',tileSheet(sitItems,4)),clipboard:save('gray-clipboard-south-4x.png',tileSheet([{label:'clipboard south',canvas:clipboardRendered.canvas}],1,4))};
const sourcePins=Object.fromEntries(Object.entries(loaded.files).map(([key,path])=>[key,{path,sha256:sha256(readFileSync(resolve(repo,path)))}]));
const manifest={schemaVersion:1,status:'gray-braid-actions-owner-review',frameContract:{width:160,height:320,axisX:80,floorY:287,phaseDurationMs:180},sourcePins,sourceReferences,frames,actions,actionMetadata:{jumpStages:Object.fromEntries([...Array(8)].map((_,index)=>{const pose=grayStarJumpPose(index);return[String(index+1).padStart(2,'0'),pose.stage];})),sitting:{seatY:236,floorY:287,chairPolicy:'separate preview prop'},clipboard:{view:'south'}},review:{identityProof,headCoverage:headCoverageProof,legAlignment:legAlignmentProof,westTrailing:westTrailingProof,westTrailingLegOnly:westLegOnlyProof,proportions:proportionRecord,representative:representativeRecord,directions:directionContacts,actions:actionReview},notes:['Exact original face/crown and braid pixels are translated rigidly at native scale.','Canonical Green gait geometry and 0.70 E/W rearward arm swing scale are reused.','Gray coat retains its authored long hem; profile shoes use a same-view forward-facing donor registered from source ankle to target sole.']};
const bytes=Buffer.from(`${JSON.stringify(manifest,null,2)}\n`);writeFileSync(resolve(output,'manifest.json'),bytes);console.log(JSON.stringify({output,manifestSha256:sha256(bytes),identityProof,representative:representativeRecord},null,2));
