import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { loadRig, renderPose, standingPose } from '../layered-pilot/blue-glasses-v1/blue-glasses-rig-v1.mjs';
import { drawStandardSlot } from '../standard-atlas/standard-character-renderer.mjs';

const repo=path.resolve(import.meta.dirname,'../../..'),out=path.join(repo,'artifacts/character-movement/gs019-blue-west/whole-body-candidate-v6'),probe=process.argv.includes('--probe'),phases=['01','02','03','04','05','06','07','08'];
const sha=x=>createHash('sha256').update(x).digest('hex'),save=(file,canvas)=>{const bytes=canvas.toBuffer('image/png');mkdirSync(path.dirname(path.join(out,file)),{recursive:true});writeFileSync(path.join(out,file),bytes);return{file,sha256:sha(bytes),width:canvas.width,height:canvas.height}};
const sources={first:{file:'tools/character-mapping/gs019-blue-west/west-first-half-v6-source.png',prompt:'tools/character-mapping/gs019-blue-west/west-first-half-v6-prompt.txt'},second:{file:'tools/character-mapping/gs019-blue-west/west-second-half-v6-source.png',prompt:'tools/character-mapping/gs019-blue-west/west-second-half-v6-prompt.txt'}};
const contract={'01':'NEAR contact foreground; FAR leg back','02':'NEAR load foreground; FAR heel-off behind','03':'NEAR straight foreground; FAR bent behind','04':'FAR swing left behind; NEAR support','05':'FAR contact; NEAR leg back foreground','06':'NEAR heel-off foreground; FAR support','07':'NEAR bend foreground over FAR straight','08':'NEAR uncurl left foreground; FAR support behind'};
function cell(image,index){const col=index%2,row=Math.floor(index/2),x=Math.floor(col*image.width/2),y=Math.floor(row*image.height/2),w=Math.floor((col+1)*image.width/2)-x,h=Math.floor((row+1)*image.height/2)-y,c=createCanvas(w,h);c.getContext('2d').drawImage(image,x,y,w,h,0,0,w,h);return c}
function largest(c){const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,seen=new Uint8Array(c.width*c.height);let best=[];for(let s=0;s<seen.length;s++){if(seen[s]||d[s*4+3]<24)continue;let group=[],q=[s];seen[s]=1;while(q.length){const n=q.pop(),x=n%c.width,y=Math.floor(n/c.width);group.push(n);for(const z of[x?n-1:-1,x<c.width-1?n+1:-1,y?n-c.width:-1,y<c.height-1?n+c.width:-1])if(z>=0&&!seen[z]&&d[z*4+3]>=24){seen[z]=1;q.push(z)}}if(group.length>best.length)best=group}let l=c.width,t=c.height,r=-1,b=-1;for(const n of best){const x=n%c.width,y=Math.floor(n/c.width);l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}const o=createCanvas(r-l+1,b-t+1),p=o.getContext('2d').createImageData(o.width,o.height);for(const n of best){const x=n%c.width,y=Math.floor(n/c.width),from=n*4,to=((y-t)*o.width+x-l)*4;for(let k=0;k<4;k++)p.data[to+k]=d[from+k]}o.getContext('2d').putImageData(p,0,0);return{canvas:o,bounds:{x:l,y:t,width:o.width,height:o.height}}}
function crop(c){const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let l=c.width,t=c.height,r=-1,b=-1;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(d[(y*c.width+x)*4+3]>=24){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}const o=createCanvas(r-l+1,b-t+1);o.getContext('2d').drawImage(c,l,t,o.width,o.height,0,0,o.width,o.height);return{canvas:o,bounds:{x:l,y:t,width:o.width,height:o.height}}}
const isBlue=(r,g,b,a)=>a>=80&&b>=r+8&&g>=r+4&&b>=g-10&&r<150&&g<170;
function shirtLandmarks(c){const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,rows=[];for(let y=0;y<c.height;y++){let l=c.width,r=-1,n=0;for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4;if(isBlue(d[i],d[i+1],d[i+2],d[i+3])){l=Math.min(l,x);r=Math.max(r,x);n++}}if(n>=Math.max(4,Math.round(c.width*.06)))rows.push({y,l,r,n,axis:(l+r)/2})}if(!rows.length)throw new Error('blue garment rows absent');const upper=rows.filter(row=>row.y<=rows[0].y+Math.max(8,Math.round(c.height*.16)));return{socketY:rows[0].y,axis:upper.map(row=>row.axis).sort((a,b)=>a-b)[Math.floor(upper.length/2)],rows}}
function removeHead(full){const mark=shirtLandmarks(full.canvas),x=full.canvas.getContext('2d'),p=x.getImageData(0,0,full.canvas.width,full.canvas.height);for(let y=0;y<mark.socketY;y++)for(let q=0;q<full.canvas.width;q++)p.data[(y*full.canvas.width+q)*4+3]=0;x.putImageData(p,0,0);return{...largest(full.canvas),cutY:mark.socketY}}
function resize(c,scale){const o=createCanvas(Math.round(c.width*scale),Math.round(c.height*scale)),x=o.getContext('2d');x.imageSmoothingEnabled=false;x.drawImage(c,0,0,o.width,o.height);return o}
function components(c,diagonal=true){const d=c.getContext('2d').getImageData(0,0,160,320).data,h=new Uint8Array(160*320),s=new Uint8Array(h.length),sizes=[];for(let n=0;n<h.length;n++)h[n]=d[n*4+3]>=24;for(let n=0;n<h.length;n++){if(!h[n]||s[n])continue;let size=0;const q=[n];s[n]=1;while(q.length){const z=q.pop(),x=z%160,y=Math.floor(z/160);size++;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy||!diagonal&&dx&&dy)continue;const nx=x+dx,ny=y+dy;if(nx<0||nx>=160||ny<0||ny>=320)continue;const k=ny*160+nx;if(h[k]&&!s[k]){s[k]=1;q.push(k)}}}sizes.push(size)}return{count:sizes.length,sizes:sizes.sort((a,b)=>b-a)}}
function isolateIdentity(c){const x=c.getContext('2d'),p=x.getImageData(0,0,160,320),d=p.data;let top=320,bottom=-1;for(let y=0;y<320;y++)for(let q=0;q<160;q++)if(d[(y*160+q)*4+3]>=24){top=Math.min(top,y);bottom=Math.max(bottom,y)}const collarStart=top+Math.floor((bottom-top+1)*.86);for(let y=collarStart;y<320;y++){let first=160,right=-1;for(let q=0;q<160;q++){const i=(y*160+q)*4;if(d[i+3]>=24)right=q;if(isBlue(d[i],d[i+1],d[i+2],d[i+3]))first=Math.min(first,q)}if(first<160)for(let q=first;q<=right;q++)d[(y*160+q)*4+3]=0}x.putImageData(p,0,0)}
const standingFile='artifacts/character-movement/blue-glasses-v1/frames/stand/west.png',standingBytes=readFileSync(path.join(repo,standingFile)),standing=await loadImage(standingBytes),standingCanvas=createCanvas(160,320),loaded=await loadRig(repo),meta=renderPose(loaded,standingPose('west')).metadata,base={...meta.head.matrix,e:-51,f:-85};standingCanvas.getContext('2d').drawImage(standing,0,0);const nativeLandmarks=shirtLandmarks(standingCanvas);
const library={};for(const[id,s]of Object.entries(sources)){const bytes=readFileSync(path.join(repo,s.file)),image=await loadImage(path.join(repo,s.file));library[id]=[];for(let i=0;i<4;i++)library[id].push(removeHead(crop(cell(image,i))));s.sha256=sha(bytes);s.promptSha256=sha(readFileSync(path.join(repo,s.prompt)));}
const scale={first:(287-nativeLandmarks.socketY)/library.first.map(x=>x.canvas.height).sort((a,b)=>a-b)[2],second:(287-nativeLandmarks.socketY)/library.second.map(x=>x.canvas.height).sort((a,b)=>a-b)[2]},prepared={};for (const index of phases.keys()) { const phase=phases[index],id=index<4?'first':'second',body=resize(library[id][index%4].canvas,scale[id]),mark=shirtLandmarks(body),rawX=Math.round(nativeLandmarks.axis-mark.axis),x=Math.max(1,Math.min(159-body.width,rawX)),y=287-(body.height-1);prepared[phase]={id,index:index%4,body,x,y,rawX,mark,source:library[id][index%4]}; }
const baseline=prepared['01'],frames={},eastFrames={},authored={},measurements={};for(const phase of probe?['01','05']:phases){const item=prepared[phase],bodyFile=`authored/${phase}.png`;authored[phase]=save(bodyFile,item.body);const delta={x:(item.x+item.mark.axis)-(baseline.x+baseline.mark.axis),y:(item.y+item.mark.socketY)-(baseline.y+baseline.mark.socketY)},matrix={...base,e:base.e+Math.round(delta.x),f:base.f+delta.y},frame=createCanvas(160,320),ctx=frame.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(item.body,item.x,item.y);const head=createCanvas(160,320),hc=head.getContext('2d');hc.imageSmoothingEnabled=false;drawStandardSlot(hc,loaded.images.identity,meta.head.id,matrix);isolateIdentity(head);const fd=ctx.getImageData(0,0,160,320),hd=hc.getImageData(0,0,160,320).data;for(let i=0;i<160*320;i++)if(hd[i*4+3])fd.data[i*4+3]=0;ctx.putImageData(fd,0,0);ctx.drawImage(head,0,0);let floor=0,below=0,d=ctx.getImageData(0,0,160,320).data;for(let x=0;x<160;x++)if(d[(287*160+x)*4+3])floor++;for(let y=288;y<320;y++)for(let x=0;x<160;x++)if(d[(y*160+x)*4+3])below++;frames[phase]=save(`frames/west-${phase}.png`,frame);const connected=components(frame,true),orthogonal=components(frame,false);measurements[phase]={bodyPlacement:{x:item.x,y:item.y,width:item.body.width,height:item.body.height},sourceSheet:item.id,sourceCell:item.index+1,cutY:item.source.cutY,uniformScale:scale[item.id],landmarks:item.mark,alignment:{requestedX:item.rawX,appliedX:item.x,collarAxisResidual:item.x+item.mark.axis-nativeLandmarks.axis},bodyDelta:delta,headMatrix:matrix,floorAlpha:floor,belowFloorAlpha:below,components:connected.count,componentEvidence:{connectivity8:connected,connectivity4:orthogonal,alphaThreshold:24,note:'8-neighbor connectivity matches raster silhouette adjacency; 4-neighbor may isolate diagonal antialias edge pixels'},gaitAudit:contract[phase]};const east=createCanvas(160,320),ec=east.getContext('2d');ec.translate(160,0);ec.scale(-1,1);ec.drawImage(frame,0,0);eastFrames[phase]={...save(`frames/east-${phase}.png`,east),exactHorizontalMirrorOf:frames[phase].file};}
const proof=createCanvas(800,344),pc=proof.getContext('2d');pc.fillStyle='#ded8ce';pc.fillRect(0,0,800,344);pc.fillStyle='#20242a';pc.font='14px sans-serif';pc.imageSmoothingEnabled=false;for(const[i,[label,image]]of[['Standing',standing],['V5 01',await loadImage(path.join(repo,'artifacts/character-movement/gs019-blue-west/whole-body-candidate-v5/frames/01.png'))],['V6 01',await loadImage(path.join(out,frames['01'].file))],['V5 05',await loadImage(path.join(repo,'artifacts/character-movement/gs019-blue-west/whole-body-candidate-v5/frames/05.png'))],['V6 05',await loadImage(path.join(out,frames['05'].file))]].entries()){pc.fillText(label,i*160+5,17);pc.drawImage(image,i*160,24)}
async function allPhaseProof(direction,records){const canvas=createCanvas(1280,344),context=canvas.getContext('2d');context.fillStyle='#ded8ce';context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle='#20242a';context.font='14px sans-serif';context.imageSmoothingEnabled=false;for(const[index,phase]of phases.entries()){context.fillText(`${direction} ${phase}`,index*160+5,17);context.drawImage(await loadImage(path.join(out,records[phase].file)),index*160,24);}return canvas;}
const proofs={early01And05:save('proofs/standing-v5-v6-early-01-05-native.png',proof),westAll8Native:save('proofs/west-all8-native.png',await allPhaseProof('West',frames)),eastAll8Native:save('proofs/east-all8-native.png',await allPhaseProof('East',eastFrames))};
const manifest={schemaVersion:'gs019-blue-west-whole-body/candidate-v6',status:probe?'probe-needs-parent-review':'prototype-needs-parent-review',characterId:'patient.adult.039',direction:'west',canvas:{width:160,height:320,axisX:80,floorY:287},gamePresentation:{width:32,height:64,tileSize:24},phaseContract:{ids:phases,cadenceMs:180,nearFarAudit:contract,disclaimer:'source occlusion was visually reviewed; pixel checks do not certify gait'},pins:{approvedStanding:{file:standingFile,sha256:sha(standingBytes)},sources},approvedStandingHeadReference:{headMatrix:base},scaleEvidence:scale,authored,frames,eastFrames,measurements,proofs};const bytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');writeFileSync(path.join(out,probe?'probe-manifest.json':'manifest.json'),bytes);console.log(JSON.stringify({status:'PASS',mode:probe?'probe':'full',manifestSha256:sha(bytes),measurements:{'01':measurements['01'],'05':measurements['05']},proofs},null,2));
