import { readFileSync } from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';

const requested=process.argv[2],variant=['v1','v2','v3','candidate-v1','candidate-v2','candidate-v3','candidate-v4','candidate-v5'].includes(requested)?requested:'candidate-v5';
const repo=path.resolve(import.meta.dirname,'../../..'),fragmentPath=path.join(repo,`artifacts/character-movement/gs019-blue-west/whole-body-${variant}/blue-west-whole-body-${variant}-review.html`),fragment=readFileSync(fragmentPath,'utf8'),chrome='C:/Program Files/Google/Chrome/Application/chrome.exe';
const assert=(ok,message)=>{if(!ok)throw Error(message)};
async function inspect(width){const browser=await chromium.launch({executablePath:chrome,headless:true});try{const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.setContent(`<style>:root{--foreground:#20242a;--muted:#ded8ce;--muted-foreground:#535861;--border:#888;--ring:#1677a8}</style>${fragment}`,{waitUntil:'load'});await page.waitForSelector('#gs019-play:not([disabled])');assert(await page.locator('.gs019-phase').count()===8,'phase buttons missing');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}px overflow`);const nonblank=await page.locator('#gs019-game-stand,#gs019-game-old,#gs019-game-fresh,#gs019-stand,#gs019-old,#gs019-fresh,#gs019-detail').evaluateAll(items=>items.every(canvas=>{const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let opaque=0;for(let i=3;i<data.length;i+=4)if(data[i])opaque++;return opaque>100}));assert(nonblank,`${width}px blank canvas`);const outputValue=()=>page.locator('#gs019-phase-output').evaluate(node=>node.value||node.textContent);for(let i=0;i<8;i++){await page.locator('.gs019-phase').nth(i).click();assert(await outputValue()===String(i+1).padStart(2,'0'),`phase ${i+1} selection failed`)}await page.locator('.gs019-phase').first().click();await page.locator('#gs019-play').click();await page.waitForTimeout(220);assert(await outputValue()!=='01','playback did not advance');await page.locator('#gs019-play').click();assert(!errors.length,errors.join('; '));return{width,phaseButtons:8,nonblank:true,noOverflow:true,playback:true}}finally{await browser.close()}}
console.log(JSON.stringify({status:'PASS',variant,results:[await inspect(736),await inspect(320)]},null,2));
