import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';

const repo=path.resolve(import.meta.dirname,'../../..'),out=path.join(repo,'artifacts/character-movement/gs019-blue-west'),manifest=JSON.parse(readFileSync(path.join(out,'manifest.json'),'utf8')),sha=value=>createHash('sha256').update(value).digest('hex'),errors=[];
const check=(ok,message)=>{if(!ok)errors.push(message)},read=file=>readFileSync(path.join(repo,file)),resolveOutput=file=>path.join(out,file);
check(manifest.schemaVersion==='gs019-blue-west/v1','schema mismatch');check(manifest.characterId==='patient.adult.039','identity mismatch');check(manifest.direction==='west','direction mismatch');check(JSON.stringify(manifest.phaseContract.ids)===JSON.stringify(['01','02','03','04','05','06','07','08']),'phase order mismatch');check(manifest.canvas.width===160&&manifest.canvas.height===320&&manifest.canvas.floorY===287,'canvas contract mismatch');check(manifest.gamePresentation.width===32&&manifest.gamePresentation.height===64&&manifest.gamePresentation.tileSize===24,'game-size evidence mismatch');
for(const [label,record] of Object.entries(manifest.pins)){check(sha(read(record.file))===record.sha256,`${label} pin mismatch`)}
for(const [phase,record] of Object.entries(manifest.rejectedFrames))check(sha(read(record.file))===record.sha256,`rejected ${phase} pin mismatch`);
const metrics={frames:0,minSocketAlpha:255,maxBelowFloor:0,floorContactFrames:0,bounds:{}};
for(const phase of manifest.phaseContract.ids){const record=manifest.frames[phase],bytes=readFileSync(resolveOutput(record.file));check(sha(bytes)===record.sha256,`new frame ${phase} hash mismatch`);const image=await loadImage(bytes),canvas=createCanvas(160,320),context=canvas.getContext('2d');context.drawImage(image,0,0);check(image.width===160&&image.height===320,`new frame ${phase} wrong dimensions`);const measurement=manifest.measurements[phase];metrics.minSocketAlpha=Math.min(metrics.minSocketAlpha,...Object.values(measurement.socketAlpha));metrics.maxBelowFloor=Math.max(metrics.maxBelowFloor,measurement.belowFloorAlpha);if(measurement.floorAlpha>0)metrics.floorContactFrames++;metrics.bounds[phase]=measurement.bounds;check(measurement.bounds&&measurement.bounds.left>=0&&measurement.bounds.right<160&&measurement.bounds.top>=0,`new frame ${phase} clipped laterally/top`);check(measurement.belowFloorAlpha===0,`new frame ${phase} extends below floor`);check(Object.values(measurement.socketAlpha).every(value=>value>0),`new frame ${phase} has transparent socket`);metrics.frames++;}
for(const role of ['nearArm','farArm','nearLeg','farLeg']){const record=manifest.donorExtraction.roles[role];check(Number.isFinite(record.uniformScale)&&record.uniformScale>0,`${role} invalid scale`);for(const phase of manifest.phaseContract.ids){const frame=record.frames[phase];check(sha(readFileSync(resolveOutput(frame.file)))===frame.sha256,`${role}/${phase} authored bitmap mismatch`)}}
for(const record of Object.values(manifest.proofs))check(sha(readFileSync(resolveOutput(record.file)))===record.sha256,`proof ${record.file} mismatch`);check(sha(readFileSync(resolveOutput(manifest.review.file)))===manifest.review.sha256,'review mismatch');const html=readFileSync(resolveOutput(manifest.review.file),'utf8');for(const token of ['Actual game size: 32×64','Prior rejected','New complete limbs','setInterval','All eight at game size','imageSmoothingEnabled=false'])check(html.includes(token),`review missing ${token}`);check(!/<\/?(?:html|head|body)|<!doctype/i.test(html),'review must be an HTML fragment');check(html.includes('id="gs019-blue-west-review"'),'review root missing');check(Buffer.byteLength(html)<1_000_000,'review exceeds 1MB');check(!/fetch\(|XMLHttpRequest|WebSocket/.test(html),'review contains network API');
check(metrics.frames===8,'expected eight frames');check(metrics.floorContactFrames===8,'every phase must touch floor');
const result={status:errors.length?'FAIL':'PASS',errorCount:errors.length,errors,metrics,visualApproval:'required-separately'};console.log(JSON.stringify(result,null,2));if(errors.length)process.exitCode=1;
