import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { createMRIRevision } from './layout-revision.mjs';
const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '../../../../..');
const lab = path.resolve(here, '../../../touchup-2026-10');
const sha = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex').toUpperCase();
const uri = file => `data:image/${path.extname(file).slice(1)};base64,${fs.readFileSync(file).toString('base64')}`;
const designSource = path.join(lab, 'lab/design-rooms.js');
const design = await import(`data:text/javascript;base64,${fs.readFileSync(designSource).toString('base64')}`);
const originalMRI = structuredClone(design.DESIGN_ROOMS.find(x => x.proofId === 'mri'));
if (!originalMRI) throw new Error('MRI layout absent in shared design source');
const metadataPath = path.resolve(here, '../assets/prepared/metadata.json');
const metadata = fs.existsSync(metadataPath) ? JSON.parse(fs.readFileSync(metadataPath, 'utf8')) : { complete: false, assets: {}, missing: Object.keys(JSON.parse(fs.readFileSync(path.join(here, 'asset-contract.json'))).assets), notes: [] };
const contract = JSON.parse(fs.readFileSync(path.join(here, 'asset-contract.json'), 'utf8'));
const assets = {};
for (const name of Object.keys(contract.assets)) {
  const id='design:mri:'+name,spec=design.DESIGN_ASSETS[id];
  const prepared = metadata.assets[name];
  if(!prepared&&!spec)throw new Error(`Required revised artwork not prepared: ${name}`);
  const imageFile=prepared?path.resolve(here,'../assets/prepared',prepared.file):path.resolve(lab,'lab',spec.src);
  assets[id]={...(spec||{}),src:uri(imageFile),candidateSrc:uri(imageFile),prepared:!!prepared};
}
const labDataPath = path.join(lab, 'build/lab-data.json');
const data = JSON.parse(fs.readFileSync(labDataPath, 'utf8'));
const actorHashes = {};
data.characters = data.characters.filter(x => ['gs026-employee-004', 'patient.adult.001'].includes(x.id));
const actorBaselinePath = path.join(here, 'actor-baseline.json');
const actorBaseline = JSON.parse(fs.readFileSync(actorBaselinePath, 'utf8'));
const actorContracts = structuredClone(data.characters);
for (const character of actorContracts) for (const pose of Object.values(character.poses)) for (const asset of Object.values(pose)) delete asset.url;
const actorContract = { characterMetrics: data.characterMetrics, characters: actorContracts };
const actorContractSha256 = crypto.createHash('sha256').update(JSON.stringify(actorContract)).digest('hex').toUpperCase();
if (actorContractSha256 !== actorBaseline.actorContractSha256) throw new Error('Shared actor export differs from the frozen first MRI proof baseline; return this change to the parent instead of silently replacing actor scale, anchors or sources.');
for (const character of data.characters) for (const [pose, directions] of Object.entries(character.poses)) for (const [direction, asset] of Object.entries(directions)) {
  const file = path.resolve(repo, 'apps/player/public', asset.url);
  const hash = sha(file);
  if (asset.sha256?.toUpperCase() !== hash) throw new Error(`Stale shared actor registry export: ${character.id}/${pose}/${direction}`);
  actorHashes[`${character.id}/${pose}/${direction}`] = { path: path.relative(repo, file).replaceAll('\\', '/'), sha256: hash };
  asset.url = uri(file);
}
if (JSON.stringify(actorHashes) !== JSON.stringify(actorBaseline.actorHashes)) throw new Error('Actor source identities differ from the frozen first MRI proof baseline');
const mri=createMRIRevision(originalMRI,contract,metadata,data);
data.rooms = data.rooms.filter(x => x.proofId === 'hallway');
data.navigation = { 'room.mri': design.DESIGN_NAVIGATION['room.mri'] };
data.atlases = {};
fs.writeFileSync(path.join(here, 'data.json'), JSON.stringify(data));
fs.writeFileSync(path.join(here, 'design-rooms.js'), `// Private MRI snapshot; generated by build.mjs. Shared source is never edited.\nexport const DESIGN_ASSETS = ${JSON.stringify(assets)};\nexport const DESIGN_ROOMS = ${JSON.stringify([mri])};\nexport const DESIGN_NAVIGATION = ${JSON.stringify(data.navigation)};\nexport const PREPARED_METADATA = ${JSON.stringify(metadata)};\nexport const ASSET_CONTRACT = ${JSON.stringify(contract)};\n`);
fs.copyFileSync(path.join(lab, 'build/room-touchups.mjs'), path.join(here, 'room-touchups.mjs'));
let renderer = fs.readFileSync(path.join(lab, 'lab/lab.js'), 'utf8');
const replacements = [
  ['"../build/room-touchups.mjs"', '"./room-touchups.mjs"'],
  ['import { DESIGN_ASSETS, DESIGN_NAVIGATION, DESIGN_ROOMS }', 'import { DESIGN_ASSETS, DESIGN_NAVIGATION, DESIGN_ROOMS, PREPARED_METADATA, ASSET_CONTRACT }'],
  ['const ART_ROOT = "../../../../apps/player/public/";', 'const ART_ROOT = "";'],
  ['scene: "room", view: "split", roomId: "laboratory",', 'scene: "room", view: "proposed", roomId: "mri",\n  operator: true, seatMode: "baseline", contacts: false, bases: false,'],
  ['imaging: true, occupied: false', 'imaging: true, patientSeated: true'],
  ['const occupancyOk = (item) => !item.occupancy || item.occupancy === (state.occupied ? "occupied" : "empty");','const occupancyOk = (item) => !item.occupancy || item.occupancy === (state.patientSeated ? "seated" : "standing");'],
  ['fetch("../build/lab-data.json")', 'fetch("./data.json")'],
  ['const atlasSrc = (assetId) => DESIGN_ASSETS[assetId] ? DESIGN_ASSETS[assetId].src', 'const atlasSrc = (assetId, proposed = true) => DESIGN_ASSETS[assetId] ? (proposed ? DESIGN_ASSETS[assetId].candidateSrc : DESIGN_ASSETS[assetId].src)'],
  ['const img = await loadImage(atlasSrc(rec.assetId));', 'const img = await loadImage(atlasSrc(rec.assetId, proposed));'],
  ['const d = { kind: "fixture", id: rec.id, img, src: rec.sourceRect, x: P.ox + lx * T, y: P.oy + ly * T, w: w * T, h: h * T, py: painterY(rec), rec };', 'const d = { kind: "fixture", id: rec.id, img, src: rec.sourceRect, x: P.ox + lx * T, y: P.oy + ly * T, w: w * T, h: h * T, py: painterY(rec), rec };\n    const prepared = PREPARED_METADATA.assets[rec.assetId.split(":").at(-1)];\n    if (proposed && prepared && rec.worldLocalGround) {\n      d.x = P.ox + rec.worldLocalGround[0] * T - prepared.canvasAnchor[0] * d.w / prepared.canvas[0];\n      d.y = P.oy + rec.worldLocalGround[1] * T - prepared.canvasAnchor[1] * d.h / prepared.canvas[1];\n      d.nativeGroundAnchor = prepared.canvasAnchor;\n    }'],
  ['d.py = TU.getTouchupRecordFloorLine(rec); sorted.push(d);', 'd.py = prepared && rec.worldLocalGround ? rec.worldLocalGround[1] : TU.getTouchupRecordFloorLine(rec); sorted.push(d);'],
  ['for (const s of sups) {', 'for (const s of sups) {\n    if (s.id === "operator" && !state.operator) continue;\n    const seat = s.id === "operator" && state.seatMode === "brief" ? { ...s.seat, y: s.ground.y - .375 } : s.seat;'],
  ['s.seat.x * T - w', 'seat.x * T - w'],
  ['s.seat.y * T - h', 'seat.y * T - h'],
  ['const py = s.pose === "standing" ? s.ground.y : Math.max(s.ground.y, s.fixtureGround?.y ?? s.ground.y);', 'const py = s.painterDepth ?? (s.pose === "standing" ? s.ground.y : Math.max(s.ground.y, s.fixtureGround?.y ?? s.ground.y));'],
  ['if (d.kind === "actor") g.imageSmoothingEnabled = false;', 'if (d.rec?.clipRightWorld !== undefined) {\n    const right=d.x+(d.rec.clipRightWorld-d.rec.destinationTopLeftTiles[0])*T;\n    g.beginPath(); g.rect(d.x-2,d.y-2,Math.max(0,right-d.x+2),d.h+4); g.clip();\n  }\n  if (d.kind === "actor") g.imageSmoothingEnabled = false;'],
  ['function paintLighting(g, P, drawables) {', 'function paintLighting(g, P, drawables) {\n  if (P.room.definitionId === "room.mri") return; // Owner: MRI never dims.'],
  ['if (params.get("scene") === "building") state.scene = "building";', '// MRI candidate stays a single room; north backing is independently controlled.'],
  ['return { statusLines, bad };', 'if (state.contacts || state.bases) for (const P of placements) paintCandidateDiagnostics(g, P, proposed);\n  return { statusLines, bad };'],
  ['window.__lab = { check,', 'window.__lab = { assets: DESIGN_ASSETS, paintCaps, paintFloor, actorPlacements, collectDrawables, recordVisible, painterY, metadata: PREPARED_METADATA, contract: ASSET_CONTRACT, check,']
];
for (const [from, to] of replacements) {
  if (!renderer.includes(from)) throw new Error(`Shared renderer changed: cannot locate ${from}`);
  renderer = renderer.replace(from, to);
}
renderer += '\n' + fs.readFileSync(path.join(here, 'extension.js'), 'utf8');
renderer=renderer.replaceAll('"tgOccupied"','"tgPatientSeated"').replaceAll('"occupiedRow"','"patientRow"').replace('["tgPatientSeated", "occupied"]','["tgPatientSeated", "patientSeated"]');
fs.writeFileSync(path.join(here, 'lab.js'), renderer);
const sourceFiles = ['lab/design-rooms.js', 'lab/lab.js', 'lab/touchup-lab.html', 'build/lab-data.json', 'build/room-touchups.mjs'];
const manifest = {
  status: 'candidate_needs_owner_review', designApproval: false, runtimeIntegration: false, completeArtwork: metadata.complete,
  missingArtwork: metadata.missing, sourceSnapshots: Object.fromEntries(sourceFiles.map(file => [file, sha(path.join(lab, file))])),
  artworkSources: Object.fromEntries(Object.entries(metadata.assets).map(([id, spec]) => [id, spec.sourceSha256])),
  preparedHashes: Object.fromEntries(Object.entries(metadata.assets).map(([id, spec]) => [id, spec.outputSha256])),
  actorHashes, actorBaseline: { file: 'actor-baseline.json', sha256: sha(actorBaselinePath), actorContractSha256, initialProof: actorBaseline.initialProof }, fixtureLayoutSha256: crypto.createHash('sha256').update(JSON.stringify(mri)).digest('hex').toUpperCase(),
  revisedLayout: mri, historicalBaselineLayoutSha256: crypto.createHash('sha256').update(JSON.stringify(originalMRI)).digest('hex').toUpperCase(), privateRevision: contract.revision, ownerDirection: contract.ownerDirection, permittedRotations: [0], ownerPlaytestOrigin: 'http://127.0.0.1:4173', reviewOrigin: 'http://127.0.0.1:4191',
  notes: ['Shell/route/actor math copied from the touch-up lab; owner-authorized geometry changes apply only in the private MRI candidate.', 'No game storage APIs, clinical content, AI or web retrieval during proof use.', 'Nine active art assets: bigger desk, tech seated south facing north, bed forepart reaches bore center, patient sits at outer west end and draws in front of both bed and scanner. Existing actor sources/scales remain frozen; shared lab/runtime unchanged.']
};
fs.writeFileSync(path.join(here, 'proof-manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`BUILD revised MRI-only candidate ${Object.keys(metadata.assets).length}/9 artwork assets; private owner-authorized geometry, shared source unchanged.`);
