import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';

const repo = path.resolve(import.meta.dirname, '../../..'), root = path.join(repo, 'artifacts/character-movement/gs019-navy-walk/west-candidate-v2');
const manifestBytes = readFileSync(path.join(root, 'manifest.json')), manifest = JSON.parse(manifestBytes), phases = ['01', '02', '03', '04', '05', '06', '07', '08'];
const expectedMap = [['firstHalf', 1], ['firstHalf', 2], ['firstHalf', 3], ['firstHalf', 4], ['secondHalf', 1], ['secondHalf', 2], ['secondHalf', 3], ['secondHalf', 4]];
const expectedAnatomy = [
  'near contact ahead; far toe behind', 'near support; far heel-off behind', 'near support; far bent passing behind', 'near late support; far swing forward behind',
  'far contact ahead; near toe behind foreground', 'far support; near heel-off foreground', 'far support; near bent passing foreground', 'far late support; near swing forward foreground',
];
const sha = value => createHash('sha256').update(value).digest('hex'), errors = [], check = (ok, message) => { if (!ok) errors.push(message); };
function pixels(canvas) { return canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data; }
function geometry(data) { const hit = new Uint8Array(160 * 320), seen = new Uint8Array(hit.length); let left = 160, top = 320, right = -1, bottom = -1, floorAlpha = 0, belowFloorAlpha = 0; for (let y = 0; y < 320; y++) for (let x = 0; x < 160; x++) { const n = y * 160 + x; if (data[n * 4 + 3] < 24) continue; hit[n] = 1; left = Math.min(left, x); right = Math.max(right, x); top = Math.min(top, y); bottom = Math.max(bottom, y); if (y === 287) floorAlpha++; if (y > 287) belowFloorAlpha++; } let components = 0; for (let seed = 0; seed < hit.length; seed++) if (hit[seed] && !seen[seed]) { components++; const stack = [seed]; seen[seed] = 1; while (stack.length) { const n = stack.pop(), x = n % 160, y = Math.floor(n / 160); for (const next of [x ? n - 1 : -1, x < 159 ? n + 1 : -1, y ? n - 160 : -1, y < 319 ? n + 160 : -1]) if (next >= 0 && hit[next] && !seen[next]) { seen[next] = 1; stack.push(next); } } } return { bounds: { left, top, right, bottom }, floorAlpha, belowFloorAlpha, components }; }

check(manifest.schemaVersion === 'gs019-navy-walk/west-candidate-v2', 'schema'); check(JSON.stringify(manifest.phaseContract.ids) === JSON.stringify(phases), 'phase order/count'); check(manifest.phaseContract.cadenceMs === 180, 'cadence'); check(manifest.canvas.width === 160 && manifest.canvas.height === 320 && manifest.canvas.floorY === 287, 'canvas'); check(manifest.registration.collarTargetX === 88, 'collar target'); check(manifest.neckPatch.pixelCount === 0, 'no neck patch');
for (const pin of [manifest.pins.standing, manifest.pins.eastStanding, manifest.pins.identityHead]) check(sha(readFileSync(path.join(repo, pin.file))) === pin.sha256, `pin ${pin.file}`);
for (const source of Object.values(manifest.pins.sources)) { check(sha(readFileSync(path.join(repo, source.file))) === source.sha256, `source ${source.file}`); check(sha(readFileSync(path.join(repo, source.prompt))) === source.promptSha256, `prompt ${source.prompt}`); check(sha(readFileSync(path.join(repo, source.normalizedFile))) === source.normalizedSha256, `normalized ${source.normalizedFile}`); }
const identity = await loadImage(path.join(repo, manifest.pins.identityHead.file)), standing = await loadImage(path.join(repo, manifest.pins.standing.file)), standingCanvas = createCanvas(160, 320); standingCanvas.getContext('2d').drawImage(standing, 0, 0); const standingData = pixels(standingCanvas);
let exactMirrorChannels = 0, headPixels = 0, exactHeadPixels = 0, lowerBodyChannels = 0, exactLowerBodyChannels = 0, minFloorAlpha = Infinity, maxBelowFloorAlpha = 0, maxComponents = 0;
const frameMetrics = {};
for (const [index, phase] of phases.entries()) {
  const westRecord = manifest.frames[phase], eastRecord = manifest.eastFrames[phase], authoredRecord = manifest.authored[phase], [sheet, cell] = expectedMap[index];
  check(westRecord.sourceSheet === sheet && westRecord.sourceCell === cell, `phase map ${phase}`); check(westRecord.anatomy === expectedAnatomy[index] && manifest.phaseContract.anatomy[phase] === expectedAnatomy[index], `anatomy contract ${phase}`); check(westRecord.uniformScale === manifest.scaleEvidence[sheet].uniformScale, `uniform scale ${phase}`); check(Number.isInteger(westRecord.headTranslation.e) && Number.isInteger(westRecord.headTranslation.f) && westRecord.headTranslation.e === -4 && westRecord.headTranslation.f === -23 + westRecord.deltaY, `integer head registration ${phase}`); check(Math.abs(westRecord.deltaY) <= 5, `bob ${phase}`); check(Math.abs(westRecord.globalLandmarks.collarX - 88) <= .5, `collar registration ${phase}`); check(Math.abs(westRecord.alignment.hipResidual) <= 12, `hip wander ${phase}`); check(westRecord.bodyPlacement.y + westRecord.bodyPlacement.height - 1 === 287, `body floor ${phase}`);
  const westBytes = readFileSync(path.join(root, westRecord.file)), eastBytes = readFileSync(path.join(root, eastRecord.file)), authoredBytes = readFileSync(path.join(root, authoredRecord.file)); check(sha(westBytes) === westRecord.sha256, `west hash ${phase}`); check(sha(eastBytes) === eastRecord.sha256, `east hash ${phase}`); check(sha(authoredBytes) === authoredRecord.sha256, `authored hash ${phase}`);
  const [westImage, eastImage, authoredImage] = await Promise.all([loadImage(westBytes), loadImage(eastBytes), loadImage(authoredBytes)]); check(westImage.width === 160 && westImage.height === 320 && eastImage.width === 160 && eastImage.height === 320, `dimensions ${phase}`);
  const west = createCanvas(160, 320), east = createCanvas(160, 320), authored = createCanvas(160, 320), head = createCanvas(160, 320); west.getContext('2d').drawImage(westImage, 0, 0); east.getContext('2d').drawImage(eastImage, 0, 0); authored.getContext('2d').drawImage(authoredImage, westRecord.bodyPlacement.x, westRecord.bodyPlacement.y); const headContext = head.getContext('2d'); headContext.imageSmoothingEnabled = false; headContext.drawImage(identity, westRecord.headTranslation.e, westRecord.headTranslation.f);
  const westData = pixels(west), eastData = pixels(east), bodyData = pixels(authored), headData = pixels(head), measured = geometry(westData); frameMetrics[phase] = measured; check(measured.components === 1, `connected West ${phase}`); check(measured.floorAlpha > 0 && measured.belowFloorAlpha === 0 && measured.bounds.bottom === 287, `ground West ${phase}`); check(measured.bounds.left > 0 && measured.bounds.right < 159 && measured.bounds.top > 0, `clipping West ${phase}`); minFloorAlpha = Math.min(minFloorAlpha, measured.floorAlpha); maxBelowFloorAlpha = Math.max(maxBelowFloorAlpha, measured.belowFloorAlpha); maxComponents = Math.max(maxComponents, measured.components);
  for (let y = 0; y < 320; y++) for (let x = 0; x < 160; x++) { const i = (y * 160 + x) * 4, mirrorI = (y * 160 + (159 - x)) * 4; for (let channel = 0; channel < 4; channel++) { check(eastData[i + channel] === westData[mirrorI + channel], `mirror ${phase}@${x},${y},${channel}`); exactMirrorChannels++; } if (headData[i + 3] === 255) { headPixels++; if (westData[i] === headData[i] && westData[i + 1] === headData[i + 1] && westData[i + 2] === headData[i + 2] && westData[i + 3] === headData[i + 3]) exactHeadPixels++; } if (y >= 145) for (let channel = 0; channel < 4; channel++) { lowerBodyChannels++; if (westData[i + channel] === bodyData[i + channel]) exactLowerBodyChannels++; } }
}
check(exactHeadPixels === headPixels, 'exact native head'); check(exactLowerBodyChannels === lowerBodyChannels, 'unchanged lower wholebody');
for (const proof of Object.values(manifest.proofs)) check(sha(readFileSync(path.join(root, proof.file))) === proof.sha256, `proof ${proof.file}`);
const result = { status: errors.length ? 'FAIL' : 'PASS', errors: errors.slice(0, 20), anatomicalAudit: { pixelCertified: false, status: 'visual-source-and-render-review-required', phases: Object.fromEntries(phases.map((phase, index) => [phase, expectedAnatomy[index]])) }, metrics: { manifestSha256: sha(manifestBytes), exactMirrorChannels, headPixels, exactHeadPixels, lowerBodyChannels, exactLowerBodyChannels, minFloorAlpha, maxBelowFloorAlpha, maxComponents, frameMetrics } };
writeFileSync(path.join(root, 'validation.json'), `${JSON.stringify(result, null, 2)}\n`); console.log(JSON.stringify(result, null, 2)); if (errors.length) process.exitCode = 1;
