import * as fap from "./familial-adenomatous-polyposis";
import * as fistula from "./complex-perianal-fistula";
import * as diverticulitis from "./recovered-diverticulitis";
import * as analScc from "./anal-squamous-cell-cancer";
import * as dvt from "./postoperative-dvt";
import * as itp from "./persistent-itp";
import * as gist from "./gastric-gist";
import * as adenoma from "./hepatic-adenoma";
import * as cmi from "./chronic-mesenteric-ischemia";
import * as pa from "./primary-aldosteronism";

export const BOARD_EXPANSION_20260912_AUTHORING_CONCEPTS = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CONCEPTS,
  ...fistula.COMPLEX_PERIANAL_FISTULA_CONCEPTS,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_CONCEPTS,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_CONCEPTS,
  ...dvt.POSTOPERATIVE_DVT_CONCEPTS,
  ...itp.PERSISTENT_ITP_CONCEPTS,
  ...gist.GASTRIC_GIST_CONCEPTS,
  ...adenoma.HEPATIC_ADENOMA_CONCEPTS,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_CONCEPTS,
  ...pa.PRIMARY_ALDOSTERONISM_CONCEPTS,
];
export const BOARD_EXPANSION_20260912_TESTED_CONCEPTS = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_TESTED_CONCEPTS,
  ...fistula.COMPLEX_PERIANAL_FISTULA_TESTED_CONCEPTS,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_TESTED_CONCEPTS,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_TESTED_CONCEPTS,
  ...dvt.POSTOPERATIVE_DVT_TESTED_CONCEPTS,
  ...itp.PERSISTENT_ITP_TESTED_CONCEPTS,
  ...gist.GASTRIC_GIST_TESTED_CONCEPTS,
  ...adenoma.HEPATIC_ADENOMA_TESTED_CONCEPTS,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_TESTED_CONCEPTS,
  ...pa.PRIMARY_ALDOSTERONISM_TESTED_CONCEPTS,
];
export const BOARD_EXPANSION_20260912_QUESTIONS = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_QUESTIONS,
  ...fistula.COMPLEX_PERIANAL_FISTULA_QUESTIONS,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_QUESTIONS,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_QUESTIONS,
  ...dvt.POSTOPERATIVE_DVT_QUESTIONS,
  ...itp.PERSISTENT_ITP_QUESTIONS,
  ...gist.GASTRIC_GIST_QUESTIONS,
  ...adenoma.HEPATIC_ADENOMA_QUESTIONS,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_QUESTIONS,
  ...pa.PRIMARY_ALDOSTERONISM_QUESTIONS,
];
export const BOARD_EXPANSION_20260912_CASES = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CASES,
  ...fistula.COMPLEX_PERIANAL_FISTULA_CASES,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_CASES,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_CASES,
  ...dvt.POSTOPERATIVE_DVT_CASES,
  ...itp.PERSISTENT_ITP_CASES,
  ...gist.GASTRIC_GIST_CASES,
  ...adenoma.HEPATIC_ADENOMA_CASES,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_CASES,
  ...pa.PRIMARY_ALDOSTERONISM_CASES,
];
export const BOARD_EXPANSION_20260912_CLAIMS = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CLAIMS,
  ...fistula.COMPLEX_PERIANAL_FISTULA_CLAIMS,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_CLAIMS,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_CLAIMS,
  ...dvt.POSTOPERATIVE_DVT_CLAIMS,
  ...itp.PERSISTENT_ITP_CLAIMS,
  ...gist.GASTRIC_GIST_CLAIMS,
  ...adenoma.HEPATIC_ADENOMA_CLAIMS,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_CLAIMS,
  ...pa.PRIMARY_ALDOSTERONISM_CLAIMS,
];
export const BOARD_EXPANSION_20260912_SOURCES = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_SOURCES,
  ...fistula.COMPLEX_PERIANAL_FISTULA_SOURCES,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_SOURCES,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_SOURCES,
  ...dvt.POSTOPERATIVE_DVT_SOURCES,
  ...itp.PERSISTENT_ITP_SOURCES,
  ...gist.GASTRIC_GIST_SOURCES,
  ...adenoma.HEPATIC_ADENOMA_SOURCES,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_SOURCES,
  ...pa.PRIMARY_ALDOSTERONISM_SOURCES,
];
export const BOARD_EXPANSION_20260912_CASE_REVIEWS = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CASE_REVIEWS,
  ...fistula.COMPLEX_PERIANAL_FISTULA_CASE_REVIEWS,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_CASE_REVIEWS,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_CASE_REVIEWS,
  ...dvt.POSTOPERATIVE_DVT_CASE_REVIEWS,
  ...itp.PERSISTENT_ITP_CASE_REVIEWS,
  ...gist.GASTRIC_GIST_CASE_REVIEWS,
  ...adenoma.HEPATIC_ADENOMA_CASE_REVIEWS,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_CASE_REVIEWS,
  ...pa.PRIMARY_ALDOSTERONISM_CASE_REVIEWS,
];
export const BOARD_EXPANSION_20260912_SERVICE_CONTRACTS = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_SERVICE_CONTRACTS,
  ...fistula.COMPLEX_PERIANAL_FISTULA_SERVICE_CONTRACTS,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_SERVICE_CONTRACTS,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_SERVICE_CONTRACTS,
  ...dvt.POSTOPERATIVE_DVT_SERVICE_CONTRACTS,
  ...itp.PERSISTENT_ITP_SERVICE_CONTRACTS,
  ...gist.GASTRIC_GIST_SERVICE_CONTRACTS,
  ...adenoma.HEPATIC_ADENOMA_SERVICE_CONTRACTS,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_SERVICE_CONTRACTS,
  ...pa.PRIMARY_ALDOSTERONISM_SERVICE_CONTRACTS,
];
export const BOARD_EXPANSION_20260912_TIMING_ENTRIES = [
  ...fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_TIMING_ENTRIES,
  ...fistula.COMPLEX_PERIANAL_FISTULA_TIMING_ENTRIES,
  ...diverticulitis.RECOVERED_DIVERTICULITIS_TIMING_ENTRIES,
  ...analScc.ANAL_SQUAMOUS_CELL_CANCER_TIMING_ENTRIES,
  ...dvt.POSTOPERATIVE_DVT_TIMING_ENTRIES,
  ...itp.PERSISTENT_ITP_TIMING_ENTRIES,
  ...gist.GASTRIC_GIST_TIMING_ENTRIES,
  ...adenoma.HEPATIC_ADENOMA_TIMING_ENTRIES,
  ...cmi.CHRONIC_MESENTERIC_ISCHEMIA_TIMING_ENTRIES,
  ...pa.PRIMARY_ALDOSTERONISM_TIMING_ENTRIES,
];

export const BOARD_EXPANSION_20260912_BATCH_MANIFEST = {
  contentVersion: "development-batch.2026-09-12.1",
  authoringConceptCount: BOARD_EXPANSION_20260912_AUTHORING_CONCEPTS.length,
  testedConceptCount: BOARD_EXPANSION_20260912_TESTED_CONCEPTS.length,
  questionVariantCount: BOARD_EXPANSION_20260912_QUESTIONS.length,
  caseCount: BOARD_EXPANSION_20260912_CASES.length,
  multistepCaseCount: BOARD_EXPANSION_20260912_CASES.filter(
    (clinicalCase) => clinicalCase.decisionNodes.length > 1,
  ).length,
  resultGateCount: BOARD_EXPANSION_20260912_CASES.flatMap(
    (clinicalCase) => clinicalCase.decisionNodes,
  ).filter((node) => node.resultGateAfter !== null).length,
  caseReviewCount: BOARD_EXPANSION_20260912_CASE_REVIEWS.length,
  sourceCount: BOARD_EXPANSION_20260912_SOURCES.length,
  evidenceClaimCount: BOARD_EXPANSION_20260912_CLAIMS.length,
  serviceContractCount: BOARD_EXPANSION_20260912_SERVICE_CONTRACTS.length,
  timingEntryCount: BOARD_EXPANSION_20260912_TIMING_ENTRIES.length,
  admissionScope: "active_synthetic_unapproved_prototype",
  publicReleaseAuthorized: false,
} as const;
