import { describe, expect, it } from "vitest";
import { syntheticClinicalCaseSchema, testedConceptSchema } from "../../schema";
import * as fap from "./familial-adenomatous-polyposis";
import * as fistula from "./complex-perianal-fistula";
import * as diverticulitis from "./recovered-diverticulitis";
import * as analScc from "./anal-squamous-cell-cancer";
import * as dvt from "./postoperative-dvt";
import * as itp from "./persistent-itp";

const families = [
  [fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CONCEPTS,fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_TESTED_CONCEPTS,fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_QUESTIONS,fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CASES,fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CLAIMS,fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_SOURCES,fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CASE_REVIEWS,fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_TIMING_ENTRIES],
  [fistula.COMPLEX_PERIANAL_FISTULA_CONCEPTS,fistula.COMPLEX_PERIANAL_FISTULA_TESTED_CONCEPTS,fistula.COMPLEX_PERIANAL_FISTULA_QUESTIONS,fistula.COMPLEX_PERIANAL_FISTULA_CASES,fistula.COMPLEX_PERIANAL_FISTULA_CLAIMS,fistula.COMPLEX_PERIANAL_FISTULA_SOURCES,fistula.COMPLEX_PERIANAL_FISTULA_CASE_REVIEWS,fistula.COMPLEX_PERIANAL_FISTULA_TIMING_ENTRIES],
  [diverticulitis.RECOVERED_DIVERTICULITIS_CONCEPTS,diverticulitis.RECOVERED_DIVERTICULITIS_TESTED_CONCEPTS,diverticulitis.RECOVERED_DIVERTICULITIS_QUESTIONS,diverticulitis.RECOVERED_DIVERTICULITIS_CASES,diverticulitis.RECOVERED_DIVERTICULITIS_CLAIMS,diverticulitis.RECOVERED_DIVERTICULITIS_SOURCES,diverticulitis.RECOVERED_DIVERTICULITIS_CASE_REVIEWS,diverticulitis.RECOVERED_DIVERTICULITIS_TIMING_ENTRIES],
  [analScc.ANAL_SQUAMOUS_CELL_CANCER_CONCEPTS,analScc.ANAL_SQUAMOUS_CELL_CANCER_TESTED_CONCEPTS,analScc.ANAL_SQUAMOUS_CELL_CANCER_QUESTIONS,analScc.ANAL_SQUAMOUS_CELL_CANCER_CASES,analScc.ANAL_SQUAMOUS_CELL_CANCER_CLAIMS,analScc.ANAL_SQUAMOUS_CELL_CANCER_SOURCES,analScc.ANAL_SQUAMOUS_CELL_CANCER_CASE_REVIEWS,analScc.ANAL_SQUAMOUS_CELL_CANCER_TIMING_ENTRIES],
  [dvt.POSTOPERATIVE_DVT_CONCEPTS,dvt.POSTOPERATIVE_DVT_TESTED_CONCEPTS,dvt.POSTOPERATIVE_DVT_QUESTIONS,dvt.POSTOPERATIVE_DVT_CASES,dvt.POSTOPERATIVE_DVT_CLAIMS,dvt.POSTOPERATIVE_DVT_SOURCES,dvt.POSTOPERATIVE_DVT_CASE_REVIEWS,dvt.POSTOPERATIVE_DVT_TIMING_ENTRIES],
  [itp.PERSISTENT_ITP_CONCEPTS,itp.PERSISTENT_ITP_TESTED_CONCEPTS,itp.PERSISTENT_ITP_QUESTIONS,itp.PERSISTENT_ITP_CASES,itp.PERSISTENT_ITP_CLAIMS,itp.PERSISTENT_ITP_SOURCES,itp.PERSISTENT_ITP_CASE_REVIEWS,itp.PERSISTENT_ITP_TIMING_ENTRIES],
] as const;
const concepts=families.flatMap(x=>[...x[0]]), tested=families.flatMap(x=>[...x[1]]), questions=families.flatMap(x=>[...x[2]]), cases=families.flatMap(x=>[...x[3]]), claims=families.flatMap(x=>[...x[4]]), sources=families.flatMap(x=>[...x[5]]), reviews=families.flatMap(x=>[...x[6]]), timing=families.flatMap(x=>[...x[7]]);
describe("2026-09-12 colorectal and hematology authoring",()=>{
 it("contains twelve concepts, forty-eight variants, and twenty-four real gates",()=>{expect(concepts).toHaveLength(12);expect(questions).toHaveLength(48);expect(cases).toHaveLength(24);expect(timing).toHaveLength(48);expect(cases.flatMap(c=>c.decisionNodes).filter(n=>n.resultGateAfter)).toHaveLength(24);expect(new Set(concepts.map(c=>c.id)).size).toBe(12);for(const c of concepts)expect(questions.filter(q=>q.conceptId===c.id)).toHaveLength(4);});
 it("keeps schema, patient identity, review status, gate sequencing, and source links intact",()=>{const bySource=new Map(sources.map(s=>[s.id,s]));for(const item of [...concepts,...questions,...claims,...sources,...reviews]){expect(item.reviewStatus).toBe("needs_clinician_review");expect(item.lastClinicianReview).toBeNull();expect(item.aiAssistedDrafting).toBe(true);}for(const c of tested)expect(testedConceptSchema.parse(c)).toEqual(c);for(const c of cases){expect(syntheticClinicalCaseSchema.parse(c)).toEqual(c);expect(c.chiefComplaint).toMatch(/^(I|My)\b/);expect(c.presentation).toContain("{patientName}");expect(c.approvedInstantiationProfiles).toHaveLength(4);const first=c.decisionNodes[0]!;const second=c.decisionNodes[1]!;expect(first.resultGateAfter).not.toBeNull();expect(second.resultGateAfter).toBeNull();expect(second.currentUpdate).toBe(first.resultGateAfter?.resultNarrative);for(const n of c.decisionNodes)expect(n.answerChoices.filter(a=>a.isCorrect)).toHaveLength(1);expect(first.answerChoices.find(a=>a.isCorrect)?.serviceRequest?.serviceId).toBe(first.resultGateAfter?.resultTypeId);}for(const c of claims)for(const id of c.sourceIds)expect(bySource.get(id)?.evidenceClaimIds).toContain(c.id);});
 it("records neutral timing for every choice without correctness inference",()=>{for(const entry of timing){const node=cases.find(c=>c.id===entry.caseId)?.decisionNodes.find(n=>n.id===entry.nodeId);expect(node?.questionVariantId).toBe(entry.questionVariantId);if(entry.classification.kind==="test_choices"){expect(entry.classification.choices).toHaveLength(4);for(const choice of entry.classification.choices)expect(node?.answerChoices.some(a=>a.id===choice.choiceId&&a.label===choice.choiceLabel)).toBe(true);}}});
 it("preserves the constrained clinical boundaries",()=>{expect(JSON.stringify(fap.FAMILIAL_ADENOMATOUS_POLYPOSIS_CASES)).toContain("cannot be controlled endoscopically");expect(JSON.stringify(fistula.COMPLEX_PERIANAL_FISTULA_CASES)).toContain("no undrained abscess");expect(JSON.stringify(diverticulitis.RECOVERED_DIVERTICULITIS_CASES)).toContain("no alternative colorectal lesion");expect(JSON.stringify(analScc.ANAL_SQUAMOUS_CELL_CANCER_CASES)).toContain("CT of the chest, abdomen, and pelvis");expect(JSON.stringify(dvt.POSTOPERATIVE_DVT_CASES)).toContain("no chest symptoms");expect(JSON.stringify(itp.PERSISTENT_ITP_CASES)).toContain("at least one year");});
});
