import { claim, concept, createDevelopmentFamily, linkSourcesToClaims, NEEDS_REVIEW, source, type CaseSpec } from "./batch-helpers";

const ACG = "source.board.hepatic-adenoma-acg-2024";
const EASL = "source.board.hepatic-adenoma-easl-summary-2020";

export const HEPATIC_ADENOMA_CLAIMS = [
  claim({ id: "claim.hepatic-adenoma.multiphasic-mri-characterization", statement: "Multiphasic liver MRI is preferred to characterize a suspected hepatic adenoma and distinguish it from other focal liver lesions, while indeterminate or atypical findings still require expert review.", sourceIds: [ACG, EASL], evidenceCategory: "evaluation", certainty: "moderate", limitation: "MRI compatibility is not presented as infallible histology or reliable identification of every molecular subtype.", applicablePopulation: "Stable adults without cirrhosis, known extrahepatic cancer, active hemorrhage, or imaging that already establishes malignancy.", lastCheckedOn: "2026-09-12" }),
  claim({ id: "claim.hepatic-adenoma.resection-in-men", statement: "Resection is recommended for a hepatic adenoma in a man regardless of lesion size after appropriate characterization and specialist review.", sourceIds: [ACG, EASL], evidenceCategory: "management", certainty: "moderate", limitation: "This sex-specific branch does not imply that every hepatic adenoma in every patient requires surgery.", applicablePopulation: "Stable adult men with an MRI-characterized hepatic adenoma and no active hemorrhage or prohibitive operative condition.", lastCheckedOn: "2026-09-12" }),
];

export const HEPATIC_ADENOMA_SOURCES = linkSourcesToClaims([
  source({ id: ACG, title: "ACG Clinical Guideline: Focal Liver Lesions", completeCitation: "Frenette C, Mendiratta-Lala M, Salgia R, Wong RJ, Sauer BG, Pillai A. ACG Clinical Guideline: Focal Liver Lesions. American Journal of Gastroenterology. 2024;119(7):1235-1271. doi:10.14309/ajg.0000000000002857. Epub January 26, 2024. Accessed 2026-09-12.", organizationOrJournal: "American College of Gastroenterology / American Journal of Gastroenterology", authors: ["C Frenette", "M Mendiratta-Lala", "R Salgia", "RJ Wong", "BG Sauer", "A Pillai"], publicationYear: 2024, doi: "10.14309/ajg.0000000000002857", pmid: "38958301", officialUrl: "https://gi.org/wp-content/uploads/2025/04/GuidelineHighlight_FLL.pdf", accessedOn: "2026-09-12", sourceClass: "professional_society_guideline", licenseLabel: "Copyright © 2024 American College of Gastroenterology", reuseStatus: "copyrighted_targeted_verification_only", reuseNotes: "Targeted factual verification and citation only; no guideline prose, tables, or figures reused.", authorityAssessment: "Current ACG guideline supporting preferred multiphasic MRI and sex/risk-selected hepatic adenoma management.", usageRole: "evidence" }),
  source({ id: EASL, title: "EASL Clinical Practice Guidelines on the Management of Benign Liver Tumors", completeCitation: "Colombo M. EASL Clinical Practice Guidelines on the Management of Benign Liver Tumors. Clinical Liver Disease (Hoboken). 2020;15(4):133-135. doi:10.1002/cld.933. Summary of EASL Clinical Practice Guidelines on benign liver tumours, Journal of Hepatology. 2016;65:386-398. doi:10.1016/j.jhep.2016.04.001. Accessed 2026-09-12.", organizationOrJournal: "American Association for the Study of Liver Diseases / European Association for the Study of the Liver", authors: ["M Colombo", "European Association for the Study of the Liver"], publicationYear: 2020, doi: "10.1002/cld.933", pmid: null, officialUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7206317/", accessedOn: "2026-09-12", sourceClass: "professional_society_guideline", licenseLabel: "Copyrighted AASLD summary with EASL recommendations reproduced by permission", reuseStatus: "copyrighted_targeted_verification_only", reuseNotes: "Independent factual cross-check only; linked Wiley content was not opened or used.", authorityAssessment: "Older society-guideline summary cross-checks MRI characterization and resection in men regardless of size.", usageRole: "cross_check" }),
], HEPATIC_ADENOMA_CLAIMS);

const t=(id:string,label:string,tp:string,rationale:string,isCorrect=false,serviceId?:string)=>({id,label,rationale,timing:{kind:"test" as const,timingProfileId:tp},...(isCorrect?{isCorrect:true,...(serviceId?{serviceId}:{})}:{})});
const n=(id:string,label:string,rationale:string,isCorrect=false)=>({id,label,rationale,timing:{kind:"no_test" as const},...(isCorrect?{isCorrect:true}:{})});
const stories=[
  ["hormone-exposure",[29,33,37,41],"I was told a liver spot needs better characterization.","an incidental solid liver lesion found during evaluation of abdominal discomfort and prior androgen exposure"],
  ["metabolic-risk",[38,42,46,50],"I have a solid liver lesion that was not fully characterized on ultrasound.","an indeterminate solid lesion found on ultrasound and a history of metabolic risk"],
  ["right-upper-pressure",[44,48,52,56],"I have mild right-upper-abdominal pressure and an unclear liver mass.","a solid liver lesion found during evaluation of mild right-upper-quadrant pressure"],
  ["incidental-lesion",[35,39,43,47],"I have an incidental liver lesion and want to know what it is.","an incidentally detected solid liver lesion on a nondedicated CT"],
] as const;
const cases:CaseSpec[]=stories.map(([slug,ages,complaint,detail],i)=>{const num=i+1;const result="Multiphasic MRI features are compatible with hepatocellular adenoma. Multidisciplinary review finds no atypical feature requiring a separate tissue diagnosis.";return{id:`case.hepatic-adenoma.${slug}`,displayName:"Solid liver-lesion evaluation",chiefComplaint:complaint,presentation:`{patientName} comes for review as a stable adult man with ${detail}. There is no cirrhosis, known extrahepatic cancer, active hemorrhage, or established malignant diagnosis.`,ageYears:ages,sexLabels:["Male"],stage:1,nodes:[{conceptId:"concept.hepatic-adenoma.multiphasic-mri-characterization",stem:`Which imaging study should be arranged to characterize ${"{patientName}"}'s liver lesion?`,choices:[t(`mri_${num}`,"Multiphasic liver MRI","timing.test.mri","MRI is preferred for characterizing suspected hepatic adenoma.",true,"service.liver_mri"),t(`single_ct_${num}`,"Single-phase abdominal CT","timing.test.ct","Single-phase CT is less suitable than a dedicated multiphasic MRI for this characterization."),t(`repeat_us_${num}`,"Repeat noncontrast liver ultrasound","timing.test.ultrasound","Repeat noncontrast ultrasound does not provide the preferred cross-sectional characterization."),t(`pet_${num}`,"Whole-body PET-CT","timing.test.pet_ct","PET-CT is not the preferred initial characterization study for this suspected benign focal lesion.")],explanation:"Multiphasic liver MRI is preferred for characterizing suspected hepatic adenoma while recognizing that atypical findings may still require multidisciplinary evaluation.",claimIds:["claim.hepatic-adenoma.multiphasic-mri-characterization"],gate:{id:`gate.hepatic-adenoma.mri.${num}`,serviceId:"service.liver_mri",pendingLabel:"External multiphasic liver MRI pending",resultNarrative:result,routeIds:["route.liver_mri.outsourced"]}},{conceptId:"concept.hepatic-adenoma.resection-in-men",currentUpdate:result,stem:`Which management plan is appropriate for ${"{patientName}"}'s characterized hepatic adenoma?`,choices:[n(`resection_${num}`,"Refer for elective hepatic resection planning","Resection is recommended for hepatic adenoma in men after appropriate characterization.",true),t(`observe_${num}`,"Begin imaging surveillance without surgical referral","timing.test.mri","Surveillance alone does not fit the sex-specific resection recommendation in this stable man."),n(`embolize_${num}`,"Arrange elective arterial embolization as first treatment","There is no active hemorrhage or unresectable lesion requiring embolization as the initial plan."),n(`ablate_${num}`,"Arrange percutaneous ablation as first treatment","Ablation is not the standard first plan for this operable hepatic adenoma in a man.")],explanation:"After compatible MRI and specialist review, hepatic adenoma in a man supports elective resection planning regardless of lesion size.",claimIds:["claim.hepatic-adenoma.resection-in-men"]}]};});
export const HEPATIC_ADENOMA_CONCEPTS=[concept({id:"concept.hepatic-adenoma.multiphasic-mri-characterization",educationalTier:1,displayName:"Multiphasic MRI characterization of hepatic adenoma",learningObjective:"Select multiphasic liver MRI to characterize a suspected hepatic adenoma while respecting imaging limitations.",earliestFacilityStage:1,conceptType:"workup",evidenceClaimIds:["claim.hepatic-adenoma.multiphasic-mri-characterization"]}),concept({id:"concept.hepatic-adenoma.resection-in-men",educationalTier:1,displayName:"Resection planning for hepatic adenoma in men",learningObjective:"Refer a stable man with a characterized hepatic adenoma for elective resection planning regardless of lesion size.",earliestFacilityStage:1,conceptType:"management",evidenceClaimIds:["claim.hepatic-adenoma.resection-in-men"]})];
const family=createDevelopmentFamily({concepts:HEPATIC_ADENOMA_CONCEPTS,cases,sourceLabels:["ACG focal liver lesion guideline (2024)","EASL benign liver tumor summary (2020)"]});
export const HEPATIC_ADENOMA_TESTED_CONCEPTS=family.testedConcepts;export const HEPATIC_ADENOMA_QUESTIONS=family.questions;export const HEPATIC_ADENOMA_CASES=family.cases;export const HEPATIC_ADENOMA_CASE_REVIEWS=family.caseReviews;export const HEPATIC_ADENOMA_TIMING_ENTRIES=family.timingEntries;export const HEPATIC_ADENOMA_AUTHORING_REVIEW=NEEDS_REVIEW;export const HEPATIC_ADENOMA_SERVICE_CONTRACTS=[{serviceId:"service.liver_mri",allowedRouteIds:["route.liver_mri.outsourced"],delivery:"new_external_contract_required" as const}];
