const fs=require('fs'),path=require('path'),crypto=require('crypto'),{chromium}=require('playwright');
const assert=(x,m)=>{if(!x)throw new Error(m)},near=(a,b,t=.02)=>Math.abs(a-b)<=t;
(async()=>{const dir=__dirname,html=fs.readFileSync(path.join(dir,'coffee-kiosk-layout.html'),'utf8'),meta=JSON.parse(fs.readFileSync(path.join(dir,'coffee.json'))),config=JSON.parse(fs.readFileSync(path.join(dir,'sprite-config.json'))),browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:900,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent('<main>'+html+'</main>');await page.waitForFunction(()=>window.__coffeeProof?.ready()&&document.querySelector('#coffee-art')?.dataset.model);const read=()=>page.locator('#coffee-art').evaluate(n=>JSON.parse(n.dataset.model));let m=await read();
assert(m.dimensions.cols===2&&m.dimensions.rows===2&&m.segments.length===8,'2x2/eight segments');assert(m.doors.length===0&&m.selected==='S1','default');assert(m.island.collision==='solid'&&near(m.island.footprint.left,.5)&&near(m.island.footprint.top,.6)&&near(m.island.footprint.width,1)&&near(m.island.footprint.height,.8),'one-tile island');assert(m.draws.island&&m.draws.print1&&m.draws.print2&&m.serviceRoute.length,'initial art/service');
let d=m.draws.island,f=meta.packedFrames.island;assert(near(d.groundContact.x,270)&&near(d.groundContact.y,318),'island base contact');assert(near(d.groundContact.y-d.worktopContact.y,82.5,.2),'measured 82.5px facade rise');assert(near(d.w/d.h,f.w/f.h,1e-7),'uniform aspect');assert(config.sprites.island.baseRight-config.sprites.island.baseLeft===720,'720px physical feet span');assert(m.scaleContract.islandPhysicalBaseWidthPx===120&&m.scaleContract.counterFacadeRisePx===82.5,'scale contract');
for(const id of m.segments){await page.locator(`[data-segment="${id}"]:not(.coffee-hit)`).click();m=await read();assert(m.doors.length===1&&m.routes[id].length&&m.draws.island,`${id} door and permanent island`);assert(m.hidden.includes('print1')===(id==='N1')&&m.hidden.includes('print2')===(id==='N2'),`${id} print ownership`);await page.locator(`[data-segment="${id}"]:not(.coffee-hit)`).click()}
for(const id of ['N1','N2']){await page.locator(`[data-adjacent="${id}"]`).check();m=await read();assert(m.hidden.includes(id==='N1'?'print1':'print2')&&m.draws.island&&m.serviceRoute.length,id+' backing');await page.locator(`[data-adjacent="${id}"]`).uncheck()}
for(const id of m.segments)await page.locator(`[data-segment="${id}"]:not(.coffee-hit)`).click();m=await read();assert(m.doors.length===8&&Object.values(m.routes).every(r=>r.length)&&m.serviceRoute.length&&m.draws.island,'all doors');
let loop=await page.evaluate(()=>{let p=window.__coffeeProof,bad=[];for(let x=.16;x<=1.84;x+=.04)for(let y of [.16,1.84])if(!p.valid({x:+x.toFixed(10),y}))bad.push({x,y});for(let y=.16;y<=1.84;y+=.04)for(let x of [.16,1.84])if(!p.valid({x,y:+y.toFixed(10)}))bad.push({x,y});return bad});assert(!loop.length,'perimeter loop clear');let sampled=await page.evaluate(()=>{let p=window.__coffeeProof,r=p.routes(),all=[...Object.values(r.doors),r.service],bad=[];for(let a of all)for(let i=1;i<a.length;i++){let u=a[i-1],v=a[i],n=Math.max(1,Math.ceil(Math.hypot(v.x-u.x,v.y-u.y)/.02));for(let j=0;j<=n;j++){let z={x:+(u.x+(v.x-u.x)*j/n).toFixed(10),y:+(u.y+(v.y-u.y)*j/n).toFixed(10)};if(!p.valid(z)){bad.push(z);break}}}return{n:all.length,bad}});assert(sampled.n===9&&!sampled.bad.length,'sampled routes');
await page.locator('[data-segment="WA"].coffee-hit').click({position:{x:7,y:60}});m=await read();assert(!m.doors.includes('WA'),'direct hit');await page.locator('[data-segment="WA"]:not(.coffee-hit)').focus();await page.keyboard.press('Enter');m=await read();assert(m.doors.includes('WA'),'keyboard');assert(!errors.length,errors.join('; '));await browser.close();let hash=crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,'coffee-kiosk-layout.html'))).digest('hex').toUpperCase();console.log(`PASS Coffee Kiosk: 8 doors, backing/print ownership, permanent island, perimeter loop, 9 sampled routes, controls\n${fs.statSync(path.join(dir,'coffee-kiosk-layout.html')).size} bytes\nSHA256 ${hash}`)})().catch(e=>{console.error(e.stack||e);process.exit(1)});
