const fs=require('fs'),path=require('path'),crypto=require('crypto'),{chromium}=require('playwright');
const assert=(value,message)=>{if(!value)throw new Error(message)},near=(a,b,t=.02)=>Math.abs(a-b)<=t;
(async()=>{const dir=__dirname,html=fs.readFileSync(path.join(dir,'training-layout.html'),'utf8'),meta=JSON.parse(fs.readFileSync(path.join(dir,'training.json'))),config=JSON.parse(fs.readFileSync(path.join(dir,'sprite-config.json'))),browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:900,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent(`<main>${html}</main>`);await page.waitForFunction(()=>window.__trainingProof?.ready()&&document.querySelector('#training-art')?.dataset.model);const read=()=>page.locator('#training-art').evaluate(n=>JSON.parse(n.dataset.model));let m=await read();
assert(m.dimensions.cols===3&&m.dimensions.rows===3&&m.segments.length===12,'3x3/12 segment contract');assert(m.doors.length===0&&m.selected==='S2','default state');assert(m.bench.collision==='solid'&&near(m.bench.footprint.left,.65)&&near(m.bench.footprint.top,.85)&&near(m.bench.footprint.width,1.7)&&near(m.bench.footprint.height,.6),'bench geometry');assert(m.stools.length===2&&m.stools.every(s=>s.facing==='N'&&near(s.ground.y,1.7)),'two north-facing stools');assert(Object.values(m.routes).every(r=>r.length)&&Object.values(m.stoolRoutes).every(r=>r.length)&&Object.values(m.benchRoutes).every(r=>r.length),'default routes');assert(m.draws.bench&&m.draws.stool1&&m.draws.stool2&&m.draws.cabinetAnatomy&&m.draws.whiteboard&&m.draws.skeleton,'default draws');
const bench=m.draws.bench;assert(near(bench.groundContact.x,90+1.5*120)&&near(bench.groundContact.y,150+1.45*120),'bench ground contact');assert(near(bench.groundContact.y-bench.worktopContact.y,85.94,.2),'bench measured worktop rise');for(const id of ['stool1','stool2']){const d=m.draws[id];assert(near(d.groundContact.y-d.seatContact.y,50.68,.03),'approved stool seat rise');assert(near(d.w/d.h,meta.packedFrames.stool.w/meta.packedFrames.stool.h,1e-7),'stool uniform aspect')}
for(const[id,d]of Object.entries(m.draws)){const frame=meta.packedFrames[d.id]||meta.packedFrames[id.replace(/\d+$/,'')];if(frame)assert(near(d.w/d.h,frame.w/frame.h,1e-7),`${id} uniform aspect`)}assert(m.scaleContract.stoolWidthPx===60&&m.scaleContract.benchBaseWidthPx===204,'scale contract');assert(config.sprites.stool.renderedSize===60&&config.sprites.stool.physicalSpan===264,'exact Exam stool config');assert(config.sprites.bench.baseRight-config.sprites.bench.baseLeft===1080,'bench physical base span');
const expected={N1:['cabinetAnatomy'],WA:['cabinetAnatomy'],N2:['whiteboard'],N3:['skeleton'],EA:['skeleton']};for(const id of m.segments){await page.locator(`[data-segment="${id}"]:not(.training-hit)`).click();m=await read();assert(m.doors.length===1&&m.doors[0]===id,`${id} single state`);assert(m.routes[id].length&&Object.values(m.stoolRoutes).every(r=>r.length)&&Object.values(m.benchRoutes).every(r=>r.length),`${id} routes`);for(const fixture of ['cabinetAnatomy','whiteboard','skeleton'])assert(m.hidden.includes(fixture)===(expected[id]||[]).includes(fixture),`${id} ${fixture} ownership`);assert(m.draws.bench&&m.draws.stool1&&m.draws.stool2,`${id} permanent furniture`);await page.locator(`[data-segment="${id}"]:not(.training-hit)`).click()}
for(const [segment,fixture] of [['N1','cabinetAnatomy'],['N2','whiteboard'],['N3','skeleton']]){const input=page.locator(`[data-adjacent="${segment}"]`);await input.check();m=await read();assert(m.hidden.includes(fixture),`${segment} backing hides ${fixture}`);assert(['cabinetAnatomy','whiteboard','skeleton'].filter(x=>x!==fixture).every(x=>!m.hidden.includes(x)),`${segment} backing unrelated restore`);await input.uncheck()}
await page.locator('[data-segment="N1"]:not(.training-hit)').click();await page.locator('[data-segment="EA"]:not(.training-hit)').click();m=await read();assert(m.hidden.includes('cabinetAnatomy')&&m.hidden.includes('skeleton')&&!m.hidden.includes('whiteboard'),'mixed hiding');await page.locator('[data-segment="N1"]:not(.training-hit)').click();await page.locator('[data-segment="EA"]:not(.training-hit)').click();
await page.locator('[data-segment="WC"].training-hit').click({position:{x:7,y:60}});m=await read();assert(m.doors.includes('WC'),'real canvas-aligned hit click');await page.locator('[data-segment="WC"]:not(.training-hit)').focus();await page.keyboard.press('Enter');m=await read();assert(!m.doors.includes('WC'),'keyboard control');
const routeProof=await page.evaluate(()=>{const q=window.__trainingProof.routes(),routes=[...Object.values(q.doors),...Object.values(q.stoolRoutes),...Object.values(q.benchRoutes)],bad=[];for(const route of routes)for(let i=1;i<route.length;i++){const a=route[i-1],b=route[i],n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/.02));for(let j=0;j<=n;j++){const p={x:+(a.x+(b.x-a.x)*j/n).toFixed(10),y:+(a.y+(b.y-a.y)*j/n).toFixed(10)};if(!window.__trainingProof.valid(p)){bad.push(p);break}}}return{count:routes.length,bad}});assert(routeProof.count===16&&routeProof.bad.length===0,'sampled route clearance');assert(errors.length===0,`page errors: ${errors.join('; ')}`);await browser.close();const hash=crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,'training-layout.html'))).digest('hex').toUpperCase();console.log(`PASS Training 3x3: 12 doors, physical hiding/backing, contacts/aspects, 16 sampled routes, click/keyboard\n${fs.statSync(path.join(dir,'training-layout.html')).size} bytes\nSHA256 ${hash}`)})().catch(e=>{console.error(e.stack||e);process.exit(1)});
