(()=>{
  const root=document.getElementById('evs-layout-proof'),canvas=root.querySelector('#evs-art'),ctx=canvas.getContext('2d'),status=root.querySelector('#evs-status'),overlay=root.querySelector('#evs-overlay'),optionalToggle=root.querySelector('#evs-optional'),targets=root.querySelector('#evs-targets');
  const SCALE=2,W=360,H=430,S=120,Y=130,X=60,radius=.16,data=__DATA__,sprites=__SPRITES__,atlas=new Image();
  atlas.src='data:image/webp;base64,__ATLAS__';
  const segments=['N1','N2','S1','S2','WA','WB','EA','EB'];
  const state={doors:new Set(),adjacent:new Set(),selected:'S2',optional:true};
  const box={x:X,y:Y,cols:2,rows:2,east:X+2*S,bottom:Y+2*S};
  const localDoors=()=>new Set(state.doors);
  const floorSurface=(left,top,width,height)=>{const tile=24,startCol=Math.floor((left-X)/tile),endCol=Math.ceil((left+width-X)/tile),startRow=Math.floor((top-Y)/tile),endRow=Math.ceil((top+height-Y)/tile);ctx.save();ctx.beginPath();ctx.rect(left,top,width,height);ctx.clip();ctx.fillStyle='#85877a';ctx.fillRect(left,top,width,height);for(let row=startRow;row<endRow;row++)for(let col=startCol;col<endCol;col++){const x=X+col*tile,y=Y+row*tile,tone=Math.abs(col*5+row*7)%8;ctx.fillStyle=tone===0?'rgba(58,73,62,.18)':tone===3?'rgba(140,132,111,.13)':'rgba(221,219,197,.07)';ctx.fillRect(x+1,y+1,tile-1,tile-1);const chip=Math.abs(col*13+row*19)%11;ctx.fillStyle=chip%3?'rgba(38,49,41,.16)':'rgba(182,169,135,.14)';ctx.fillRect(x+4+chip%12,y+5+(chip*3)%12,1,1)}ctx.strokeStyle='rgba(39,48,41,.25)';ctx.lineWidth=1;for(let col=startCol;col<=endCol;col++){const x=X+col*tile+.5;ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+height);ctx.stroke()}for(let row=startRow;row<=endRow;row++){const y=Y+row*tile+.5;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left+width,y);ctx.stroke()}ctx.restore()};
  const hitSlot=id=>{const i=id[0]==='N'||id[0]==='S'?Number(id.slice(1))-1:id.charCodeAt(1)-65;if(id[0]==='N')return{x:X+i*S,y:state.adjacent.has(id)?Y-29:Y-99,w:S,h:state.adjacent.has(id)?29:99};if(id[0]==='S')return{x:X+i*S,y:box.bottom,w:S,h:29};return{x:id[0]==='W'?X-12:box.east,y:Y+i*S,w:12,h:S}};
  function drawShell(){const doors=localDoors(),sage='#5f6854',green='#58735a',dark='#294632',light='#789173',wood='#744a29',background='#eee9d8',cream='#efe1bd',wall=90,low=29,cap=14;ctx.clearRect(0,0,W,H);ctx.fillStyle=background;ctx.fillRect(0,0,W,H);floorSurface(X,Y,2*S,2*S);
    for(let i=0;i<2;i++){const left=X+i*S,id=`N${i+1}`;if(state.adjacent.has(id)){ctx.clearRect(left,0,S,Y-low);ctx.fillStyle=green;ctx.fillRect(left,Y-low,S,low);ctx.fillStyle=light;ctx.fillRect(left,Y-low,S,4);ctx.fillStyle=dark;ctx.fillRect(left,Y-7,S,7)}else{ctx.fillStyle=sage;ctx.fillRect(left,Y-wall,S,wall);ctx.fillStyle='rgba(73,98,79,.055)';ctx.fillRect(left+12,Y-wall+30,S-24,2);ctx.fillStyle=green;ctx.fillRect(left,Y-23,S,23);ctx.fillStyle=light;ctx.fillRect(left,Y-23,S,4);ctx.fillStyle=dark;ctx.fillRect(left,Y-7,S,7);ctx.fillRect(left-1,Y-wall-9,S+2,9);ctx.fillStyle=light;ctx.fillRect(left-1,Y-wall-9,S+2,3)}}
    const westX=X-cap+2,eastX=box.east-2;for(const[right,px]of[[false,westX],[true,eastX]]){const neighbor=right?'N2':'N1',top=state.adjacent.has(neighbor)?Y-low:Y-wall-9;ctx.fillStyle=dark;ctx.fillRect(px,top,cap,box.bottom+29-top);ctx.fillStyle=light;ctx.fillRect(px+(right?0:cap-3),top,3,box.bottom+29-top)}
    for(let i=0;i<2;i++){const left=X+i*S;ctx.fillStyle=cream;ctx.fillRect(left,box.bottom,S,29);ctx.fillStyle=green;ctx.fillRect(left,box.bottom+21,S,8);ctx.fillStyle=dark;ctx.fillRect(left,box.bottom-6,S,8);ctx.fillStyle=light;ctx.fillRect(left,box.bottom-6,S,3)}
    for(const id of doors){if(id[0]==='N'){const i=Number(id.slice(1))-1,left=X+i*S+12,right=X+(i+1)*S-12,backed=state.adjacent.has(id),top=backed?Y-low:Y-wall+8;ctx.clearRect(left,top,right-left,Y-top);ctx.fillStyle=wood;ctx.fillRect(left-5,top,5,Y-top);ctx.fillRect(right,top,5,Y-top);if(!backed)ctx.fillRect(left-5,top-5,right-left+10,6)}else if(id[0]==='S'){const i=Number(id.slice(1))-1,left=X+i*S+12,right=X+(i+1)*S-12;ctx.clearRect(left,box.bottom-6,right-left,35);floorSurface(left,box.bottom-6,right-left,35);ctx.fillStyle=wood;ctx.fillRect(left-5,box.bottom-8,5,37);ctx.fillRect(right,box.bottom-8,5,37)}else{const right=id[0]==='E',i=id.charCodeAt(1)-65,px=right?eastX:westX,top=Y+i*S+12,height=S-24,half=cap/2;ctx.clearRect(px,top,cap,height);if(right){floorSurface(px,top,half,height);ctx.clearRect(px+half,top,half,height)}else{ctx.clearRect(px,top,half,height);floorSurface(px+half,top,half,height)}ctx.fillStyle=wood;ctx.fillRect(px-2,top-3,cap+4,5);ctx.fillRect(px-2,top+height-2,cap+4,5)}}
  }
  const fixtures={
    shelf1:{id:'shelf1',label:'north supply shelf N1',ground:{x:.5,y:.35},footprint:{left:0,top:.15,width:1,height:.20},collision:'nonblocking',persistence:'optional',conflicts:['N1'],backedConflicts:['N1']},
    shelf2:{id:'shelf2',label:'north supply shelf N2',ground:{x:1.5,y:.35},footprint:{left:1,top:.15,width:1,height:.20},collision:'nonblocking',persistence:'optional',conflicts:['N2'],backedConflicts:['N2']},
    clutter1:{id:'clutter1',label:'southwest cleaning clutter',ground:{x:.40,y:1.87},footprint:{left:.03,top:1.58,width:.74,height:.29},collision:'nonblocking',persistence:'optional',conflicts:['WB','S1'],backedConflicts:[]},
    clutter2:{id:'clutter2',label:'southeast cleaning clutter',ground:{x:1.60,y:1.87},footprint:{left:1.23,top:1.58,width:.74,height:.29},collision:'nonblocking',persistence:'optional',conflicts:['EB','S2'],backedConflicts:[]},
    bucket:{id:'bucket',label:'mop bucket and caddy',ground:{x:1.25,y:1.15},footprint:{left:1.01,top:.90,width:.48,height:.25},collision:'nonblocking',persistence:'permanent'}
  };
  const hidden=()=>Object.values(fixtures).filter(f=>f.persistence==='optional'&&(!state.optional||f.conflicts.some(id=>state.doors.has(id))||f.backedConflicts.some(id=>state.adjacent.has(id)))).map(f=>f.id);
  function drawSprite(id,fixture){const frame=data.packedFrames[id],source=sprites[id],scale=source.renderedHeight/frame.h,w=frame.w*scale,x=X+fixture.ground.x*S-source.ground[0]*scale,y=Y+fixture.ground.y*S-source.ground[1]*scale;ctx.drawImage(atlas,frame.x,frame.y,frame.w,frame.h,x,y,w,source.renderedHeight);return{x,y,w,h:source.renderedHeight,aspect:frame.w/frame.h,sourceGround:{x:source.ground[0],y:source.ground[1]},groundContact:{x:x+source.ground[0]*scale,y:y+source.ground[1]*scale}}}
  function drawFurniture(){const absent=hidden(),draws={};for(const id of Object.keys(fixtures).sort((a,b)=>fixtures[a].ground.y-fixtures[b].ground.y))if(!absent.includes(id))draws[id]=drawSprite(id,fixtures[id]);return{hidden:absent,draws}}
  const doorPoint=id=>{const i=id[0]==='N'||id[0]==='S'?Number(id.slice(1))-1:id.charCodeAt(1)-65;if(id[0]==='N')return{x:i+.5,y:radius};if(id[0]==='S')return{x:i+.5,y:2-radius};if(id[0]==='W')return{x:radius,y:i+.5};return{x:2-radius,y:i+.5}};
  const routes=()=>Object.fromEntries(segments.map(id=>[id,[{x:1,y:1},doorPoint(id)]]));
  function drawOverlay(routeModel){if(!overlay.checked)return;const route=routeModel[state.selected]||[];ctx.save();if(route.length){ctx.strokeStyle='#2f7090';ctx.lineWidth=3;ctx.beginPath();route.forEach((p,i)=>i?ctx.lineTo(X+p.x*S,Y+p.y*S):ctx.moveTo(X+p.x*S,Y+p.y*S));ctx.stroke()}for(const f of Object.values(fixtures)){const q=f.footprint;ctx.setLineDash([5,4]);ctx.strokeStyle='#2f7090';ctx.strokeRect(X+q.left*S,Y+q.top*S,q.width*S,q.height*S)}ctx.restore()}
  function render(){ctx.setTransform(SCALE,0,0,SCALE,0,0);ctx.imageSmoothingEnabled=true;drawShell();const furniture=drawFurniture(),routeModel=routes();drawOverlay(routeModel);for(const button of targets.querySelectorAll('button')){const q=hitSlot(button.dataset.local);Object.assign(button.style,{left:`${q.x/W*100}%`,top:`${q.y/H*100}%`,width:`${q.w/W*100}%`,height:`${q.h/H*100}%`})}const reachable=Object.values(routeModel).filter(path=>path.length).length;status.innerHTML=`<strong>2 × 2 fixed north-up</strong> · ${state.selected} ${state.doors.has(state.selected)?'open':'closed'} · ${reachable}/8 approaches reachable<br>Hidden: ${furniture.hidden.join(', ')||'none'} · mop bucket permanent`;root.querySelectorAll('[data-world]').forEach(button=>{const active=state.doors.has(button.dataset.world);button.setAttribute('aria-pressed',String(active));button.classList.toggle('btn-primary',active)});canvas.dataset.model=JSON.stringify({orientation:'north-up',viewHeight:H,dimensions:{cols:2,rows:2,x:X,y:Y},segments,doors:[...state.doors],localDoors:[...state.doors],selected:state.selected,adjacency:[...state.adjacent],hidden:furniture.hidden,routes:routeModel,fixtures,draws:furniture.draws,spriteRevision:sprites.revision,shell:{tileSize:S,rearWallHeight:90,lowNorthHeight:29,sideCapWidth:14,southHeight:29,northDoorTransparent:true,sideDoorSeam:'floor-half-thickness',southDoorFloorBase:true,northColor:'#5f6854',floor:'24px dark sage/stone utility tiles',floorPatternSize:24,floorPatternOrigin:{x:X,y:Y},logicalGridDrawn:false},radius})}
  function toggleDoor(id){state.doors.has(id)?state.doors.delete(id):state.doors.add(id);state.selected=id;render()}
  function rebuildControls(){for(const id of ['evs-north','evs-south','evs-west','evs-east','evs-adjacency','evs-targets'])root.querySelector(`#${id}`).replaceChildren();for(const local of segments){const side={N:'north',S:'south',W:'west',E:'east'}[local[0]],button=document.createElement('button');button.type='button';button.className='btn btn-sm btn-outline-secondary';button.textContent=local;button.dataset.local=local;button.dataset.world=local;button.setAttribute('aria-label',`${local} doorway`);button.addEventListener('click',()=>toggleDoor(local));root.querySelector(`#evs-${side}`).append(button);const hit=button.cloneNode(true);hit.className='evs-hit';hit.textContent='';hit.addEventListener('click',()=>toggleDoor(local));targets.append(hit)}for(const id of ['N1','N2']){const label=document.createElement('label');label.className='form-check form-check-inline';label.innerHTML=`<input class="form-check-input" type="checkbox" data-adjacent="${id}"><span class="form-check-label">${id}</span>`;label.querySelector('input').addEventListener('change',event=>{event.target.checked?state.adjacent.add(id):state.adjacent.delete(id);render()});root.querySelector('#evs-adjacency').append(label)}render()}
  overlay.addEventListener('change',render);optionalToggle.addEventListener('change',event=>{state.optional=event.target.checked;render()});atlas.onload=render;rebuildControls();
  window.__evsProof={state,render,rebuildControls,routes,fixtures,ready:()=>atlas.complete&&atlas.naturalWidth>0};
})();
