const fs=require('fs'),path=require('path'),crypto=require('crypto'),{chromium}=require('playwright');
const dir=__dirname,source=path.join(dir,'evs-layout.html'),evidence=path.join(dir,'evidence'),chrome='C:/Program Files/Google/Chrome/Application/chrome.exe';
const assert=(value,message)=>{if(!value)throw new Error(message)},near=(a,b,e=.02)=>Math.abs(a-b)<=e;
(async()=>{
  const html=fs.readFileSync(source,'utf8');assert(Buffer.byteLength(html)<1_000_000,'fragment must remain below 1 MB');assert(!/<(?:html|head|body|!doctype)/i.test(html),'deliverable must remain an HTML fragment');
  const metadata=JSON.parse(fs.readFileSync(path.join(dir,'evs.json'),'utf8'));assert(metadata.sourceSize[0]===1312&&metadata.sourceSize[1]===1199&&metadata.bucketSourceSize[0]===1536&&metadata.bucketSourceSize[1]===1024,'source atlas dimensions');assert(metadata.packedFrames.shelf1.sourceVisibleBounds.join(',')==='0,0,654,648','shelf1 alpha crop');assert(metadata.packedFrames.shelf2.sourceVisibleBounds.join(',')==='655,21,1282,650','shelf2 alpha crop');assert(metadata.packedFrames.clutter1.sourceVisibleBounds.join(',')==='44,658,611,1167','clutter1 alpha crop');assert(metadata.packedFrames.clutter2.sourceVisibleBounds.join(',')==='703,675,1251,1154','clutter2 alpha crop');assert(metadata.packedFrames.bucket.sourceVisibleBounds.join(',')==='1089,55,1518,968','bucket alpha crop');
  fs.mkdirSync(evidence,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:chrome}),page=await browser.newPage({viewport:{width:900,height:950},deviceScaleFactor:1}),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.setContent(`<main>${html}</main>`);await page.waitForFunction(()=>window.__evsProof?.ready()&&document.querySelector('#evs-art').dataset.model,{timeout:30000});
  const read=()=>page.evaluate(()=>JSON.parse(document.querySelector('#evs-art').dataset.model));let m=await read();
  assert(m.orientation==='north-up'&&m.dimensions.cols===2&&m.dimensions.rows===2,'fixed 2x2 north-up layout');assert(m.segments.join(',')==='N1,N2,S1,S2,WA,WB,EA,EB','eight doorway segments');assert(await page.locator('[data-world]:not(.evs-hit)').count()===8&&await page.locator('.evs-hit').count()===8,'eight visible controls and canvas targets');assert(await page.locator('[data-adjacent]').count()===2,'two backed north controls');assert(Object.values(m.routes).every(route=>route.length===2),'all eight door routes reachable');
  assert(m.shell.rearWallHeight===90&&m.shell.lowNorthHeight===29&&m.shell.sideCapWidth===14&&m.shell.southHeight===29,'common shell dimensions');assert(m.shell.northDoorTransparent&&m.shell.sideDoorSeam==='floor-half-thickness'&&m.shell.southDoorFloorBase,'common door rendering contract');assert(m.shell.northColor==='#5f6854'&&m.shell.floor==='24px dark sage/stone utility tiles'&&m.shell.floorPatternSize===24&&!m.shell.logicalGridDrawn,'dark utility surface contract');assert(m.shell.floorPatternOrigin.x===60&&m.shell.floorPatternOrigin.y===130,'floor anchored to room origin');
  const f=m.fixtures,d=m.draws;for(const id of ['shelf1','shelf2','clutter1','clutter2','bucket'])assert(f[id].collision==='nonblocking',`${id} nonblocking`);assert(f.shelf1.conflicts.join(',')==='N1'&&f.shelf2.conflicts.join(',')==='N2','shelves hide only for own north door');assert(f.shelf1.backedConflicts.join(',')==='N1'&&f.shelf2.backedConflicts.join(',')==='N2','shelves hide only for own backed north');assert(f.clutter1.conflicts.join(',')==='WB,S1'&&f.clutter2.conflicts.join(',')==='EB,S2','lateral clutter owns its two corner door segments');assert(!f.clutter1.backedConflicts.length&&!f.clutter2.backedConflicts.length,'lateral clutter unaffected by backed north');assert(f.bucket.persistence==='permanent','bucket permanent');
  assert(near(f.shelf1.ground.x,.5)&&near(f.shelf1.ground.y,.35)&&near(f.shelf2.ground.x,1.5)&&near(f.shelf2.ground.y,.35)&&near(f.clutter1.ground.x,.4)&&near(f.clutter1.ground.y,1.87)&&near(f.clutter2.ground.x,1.6)&&near(f.clutter2.ground.y,1.87)&&near(f.bucket.ground.x,1.25)&&near(f.bucket.ground.y,1.15),'approved fixture grounds');assert(near(d.shelf1.h,130.92)&&near(d.shelf2.h,126.87)&&near(d.clutter1.h,80.79)&&near(d.clutter2.h,78.67)&&near(d.bucket.h,125),'approved rendered heights');assert(near(589*d.shelf1.h/648,119,.05)&&near(590*d.shelf2.h/629,119,.05),'solid shelf widths fill north wall');assert(near(d.shelf1.aspect,654/648,.0001)&&near(d.shelf2.aspect,627/629,.0001)&&near(d.clutter1.aspect,567/509,.0001)&&near(d.clutter2.aspect,548/479,.0001)&&near(d.bucket.aspect,429/913,.0001),'source crop aspects');assert(d.shelf1.sourceGround.x===328&&d.shelf1.sourceGround.y===641&&d.shelf2.sourceGround.x===325&&d.shelf2.sourceGround.y===620&&d.clutter1.sourceGround.x===276&&d.clutter1.sourceGround.y===492&&d.clutter2.sourceGround.x===272&&d.clutter2.sourceGround.y===475&&d.bucket.sourceGround.x===245&&d.bucket.sourceGround.y===899,'measured source contacts');for(const id of ['shelf1','shelf2','clutter1','clutter2','bucket']){assert(near(d[id].groundContact.x,60+f[id].ground.x*120)&&near(d[id].groundContact.y,130+f[id].ground.y*120),`${id} ground registration`)}
  const maskFailures=await page.evaluate(()=>{const p=window.__evsProof,ids=['N1','N2','S1','S2','WA','WB','EA','EB'],bad=[];for(let backed=0;backed<4;backed++)for(let mask=0;mask<256;mask++){p.state.optional=true;p.state.doors=new Set(ids.filter((_,i)=>mask&(1<<i)));p.state.adjacent=new Set(['N1','N2'].filter((_,i)=>backed&(1<<i)));p.render();const m=JSON.parse(document.querySelector('#evs-art').dataset.model),expect1=Boolean((mask&1)||(backed&1)),expect2=Boolean((mask&2)||(backed&2)),expect3=Boolean(mask&(4|32)),expect4=Boolean(mask&(8|128));if(m.hidden.includes('shelf1')!==expect1||m.hidden.includes('shelf2')!==expect2||m.hidden.includes('clutter1')!==expect3||m.hidden.includes('clutter2')!==expect4||m.hidden.includes('bucket'))bad.push(`${backed}:${mask}`)}return bad});assert(!maskFailures.length,`door/backed masks fail: ${maskFailures.slice(0,10).join(',')}`);
  await page.evaluate(()=>{const p=window.__evsProof;p.state.doors=new Set(['WA','EA']);p.state.adjacent.clear();p.state.optional=true;p.render()});m=await read();assert(!m.hidden.length,'non-owning side doors do not hide fixtures');
  await page.locator('#evs-optional').uncheck();m=await read();assert(m.hidden.join(',')==='shelf1,shelf2,clutter1,clutter2'&&!m.hidden.includes('bucket'),'optional toggle hides all four optional groups only');await page.locator('#evs-optional').check();
  await page.evaluate(()=>{const p=window.__evsProof;p.state.doors.clear();p.state.adjacent.clear();p.state.selected='S2';p.render()});const canvasBox=await page.locator('#evs-art').boundingBox();await page.mouse.click(canvasBox.x+120/360*canvasBox.width,canvasBox.y+80/430*canvasBox.height);m=await read();assert(m.doors.includes('N1')&&m.hidden.join(',')==='shelf1','physical N1 canvas click hides only shelf1');
  const keyButton=page.locator('[data-world="N1"]:not(.evs-hit)');await keyButton.focus();await page.keyboard.press('Enter');m=await read();assert(!m.doors.includes('N1')&&!m.hidden.length,'keyboard restores N1 and shelf1');
  await page.locator('#evs-overlay').check();await page.screenshot({path:path.join(evidence,'evs-overlay.png'),fullPage:true});await page.setViewportSize({width:320,height:900});await page.screenshot({path:path.join(evidence,'evs-320.png'),fullPage:true});const narrow=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,root:document.querySelector('#evs-layout-proof').getBoundingClientRect().width}));assert(narrow.scroll<=narrow.client&&narrow.root<=320,'320px layout must not overflow');
  await page.evaluate(()=>{const p=window.__evsProof;p.state.doors.clear();p.state.adjacent.clear();p.state.selected='S2';p.state.optional=true;document.querySelector('#evs-optional').checked=true;document.querySelector('#evs-overlay').checked=false;p.render()});m=await read();assert(!m.doors.length&&!m.hidden.length&&m.selected==='S2','final default resets to all closed with every optional fixture visible');
  assert(errors.length===0,`page errors: ${errors.join('; ')}`);await browser.close();const digest=crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex').toUpperCase();console.log(`PASS EVS proof: fixed 2x2, 8 routes, 1024 door/backed combinations, four own-segment hide rules, source contacts/aspects, canvas click, keyboard, desktop/320; ${Buffer.byteLength(html)} bytes; SHA256 ${digest}`);
})().catch(error=>{console.error(error.stack||error);process.exit(1)});
