(()=>{
  const root=document.getElementById('endoscopy-scale-comparison'),viewsNode=root.querySelector('#esc-views'),status=root.querySelector('#esc-status'),data=__DATA__,W=220,H=300,baseline=260,tile=120;
  const bedAtlases={south:new Image(),east:new Image()},liveAtlas=new Image();bedAtlases.south.src='data:image/webp;base64,__BED_SOUTH__';bedAtlases.east.src='data:image/webp;base64,__BED_EAST__';liveAtlas.src='data:image/webp;base64,__LIVE__';
  const approved={};for(const[view,poses]of Object.entries(data.selected)){approved[view]={};for(const[kind,record]of Object.entries(poses)){const image=new Image();image.src=`data:image/png;base64,${record.data}`;approved[view][kind]=image}}
  const labels={south:{title:'Default room · generic head faces West',stand:'Approved P01 · standing West',sit:'Approved P01 · seated West',live:'Live P01 · side idle'},east:{title:'Rotated room · generic head faces South',stand:'Approved P01 · standing South',sit:'Approved P01 · seated South',live:'Live P01 · idle South'}};
  const canvases={};
  for(const view of ['south','east']){const section=document.createElement('section');section.className='esc-view';const heading=document.createElement('h3');heading.textContent=labels[view].title;section.append(heading);const grid=document.createElement('div');grid.className='esc-grid';grid.setAttribute('aria-label',`${view} comparison row`);canvases[view]={};for(const kind of ['bed','stand','sit','live']){const figure=document.createElement('figure'),canvas=document.createElement('canvas'),caption=document.createElement('figcaption');canvas.width=W*2;canvas.height=H*2;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',kind==='bed'?`${view} occupied procedure bed at accepted proof size`:labels[view][kind]);caption.className='text-small';caption.textContent=kind==='bed'?`Occupied bed · ${view==='south'?'205px high':'110px high'}`:labels[view][kind];figure.append(canvas,caption);grid.append(figure);canvases[view][kind]=canvas}section.append(grid);viewsNode.append(section)}
  function surface(canvas){const context=canvas.getContext('2d');context.setTransform(2,0,0,2,0,0);context.clearRect(0,0,W,H);context.fillStyle='#778087';context.fillRect(0,0,W,baseline);context.fillStyle='rgba(233,227,211,.08)';for(let y=20;y<baseline;y+=24)for(let x=6;x<W;x+=24)context.fillRect(x,y,22,22);context.strokeStyle='rgba(245,231,197,.7)';context.lineWidth=1;context.strokeRect((W-tile)/2+.5,baseline-tile+.5,tile-1,tile-1);context.fillStyle='rgba(245,231,197,.92)';context.fillRect(0,baseline,W,2);context.font='10px sans-serif';context.fillText('120px tile',8,baseline-5);return context}
  function drawBed(view){const context=surface(canvases[view].bed),frame=data.beds[view].packedFrames.tableOccupied,source=data.bedSprites[view].tableOccupied,height=source.renderedHeight,scale=height/frame.h,width=frame.w*scale,groundX=source.ground[0]*scale,groundY=source.ground[1]*scale,anchorX=view==='south'?110:190,x=anchorX-groundX,y=baseline-groundY;context.drawImage(bedAtlases[view],frame.x,frame.y,frame.w,frame.h,x,y,width,height);context.fillStyle='#f0c084';context.beginPath();context.arc(anchorX,baseline,3,0,Math.PI*2);context.fill();canvases[view].bed.dataset.model=JSON.stringify({view,renderedHeight:height,width,x,y,ground:{x:anchorX,y:baseline},sourceGround:source.ground,frame})}
  function drawApproved(view,kind){const context=surface(canvases[view][kind]),image=approved[view][kind],scale=data.approvedScale,width=160*scale,height=320*scale,x=(W-width)/2,y=baseline-287*scale;context.imageSmoothingEnabled=true;context.drawImage(image,x,y,width,height);const record=data.selected[view][kind],seat=record.anchors.seatContact?.y;context.fillStyle='#abd5c1';context.beginPath();context.arc(W/2,baseline,3,0,Math.PI*2);context.fill();if(seat){context.fillStyle='#efbe82';context.beginPath();context.arc(W/2,y+seat*scale,3,0,Math.PI*2);context.fill()}canvases[view][kind].dataset.model=JSON.stringify({view,kind,sourceFile:record.file,sourceSize:[160,320],visibleBounds:record.visibleBounds,floorAnchor:[80,287],seatContact:seat??null,scale,displaySize:{width,height},visibleHeight:record.visibleBounds.height*scale,provisional:true})}
  function drawLive(view){const context=surface(canvases[view].live),frame=data.live.frames[view==='south'?'west':'south'],width=data.liveMetrics.width,height=data.liveMetrics.height,x=(W-width)/2,y=baseline-height*181/192;context.imageSmoothingEnabled=true;context.drawImage(liveAtlas,frame.x,frame.y,frame.w,frame.h,x,y,width,height);context.fillStyle='#abd5c1';context.beginPath();context.arc(W/2,baseline,3,0,Math.PI*2);context.fill();canvases[view].live.dataset.model=JSON.stringify({view,sourceFile:frame.sourceFile,sourceCell:frame.sourceCell,visibleBounds:frame.visibleBounds,displaySize:{width,height},floorAnchor:[64,181],scale:data.liveMetrics.cellScale,displayScale:1,runtime:true})}
  function render(){for(const view of ['south','east']){drawBed(view);drawApproved(view,'stand');drawApproved(view,'sit');drawLive(view)}const model={tileSize:data.tileSize,liveMetrics:data.liveMetrics,approvedScale:data.approvedScale,scaleMethod:'match approved P01 287px standing visible height to live P01 171px source visible height at 243/192 runtime cell scale',bedHeights:{south:data.bedSprites.south.tableOccupied.renderedHeight,east:data.bedSprites.east.tableOccupied.renderedHeight},views:Object.fromEntries(Object.entries(canvases).map(([view,items])=>[view,Object.fromEntries(Object.entries(items).map(([kind,canvas])=>[kind,JSON.parse(canvas.dataset.model)]))]))};root.dataset.model=JSON.stringify(model);status.innerHTML=`Live P01 at tile 120: <strong>162 × 243px</strong>, feet anchored at source y181. Approved still comparison scale: <strong>${data.approvedScale.toFixed(6)}×</strong>, feet anchored at source y287. Bed art remains South 205px / East 110px.`}
  const all=[...Object.values(bedAtlases),liveAtlas,...Object.values(approved).flatMap(item=>Object.values(item))];Promise.all(all.map(image=>image.decode())).then(()=>{render();root.dataset.ready='true'}).catch(error=>{root.dataset.ready='error';status.setAttribute('role','alert');status.textContent='Comparison images could not load.';console.error(error)});window.__endoscopyScaleComparison={data,render,ready:()=>root.dataset.ready==='true'};
})();
