import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createCanvas, loadImage } from "@napi-rs/canvas";
import { DIRECTIONS, SLOTS, extractEight, fileSha, inferSeatContact, loadCanvas, measure, normalizeCells, sha256 } from "./pipeline.mjs";

const tool=dirname(fileURLToPath(import.meta.url)), repo=resolve(tool,"../../.."), artifacts=resolve(repo,"artifacts/character-statics/gs026-employee-expansion-v1"), config=JSON.parse(readFileSync(resolve(tool,"config.json"),"utf8"));
const posix=file=>relative(repo,file).replaceAll("\\","/");
const writePng=(canvas,file)=>{mkdirSync(dirname(file),{recursive:true});const bytes=canvas.toBuffer("image/png");writeFileSync(file,bytes);return{file:posix(file),sha256:sha256(bytes),width:canvas.width,height:canvas.height};};
const sourceFiles=id=>{const base=resolve(tool,"assets",`${id}-cardinals-v1`), exact=`${base}-exact-prompt.txt`, reconstructed=`${base}-reconstructed-prompt.txt`, prompt=existsSync(exact)?exact:reconstructed, provenance=[`${base}-tool-output-provenance.txt`,`${base}-provenance.md`].find(existsSync);return{png:`${base}.png`,prompt,promptProvenance:prompt===exact?"exact-tool-input":"reconstructed-from-batch-template-not-exact-tool-input",provenance};};

async function gridProof(id,frames,scale,theme,name){const w=160*scale,h=320*scale,canvas=createCanvas(w*4,h*2),ctx=canvas.getContext("2d");ctx.fillStyle=theme==="dark"?"#20252b":"#eee9df";ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<8;i++)ctx.drawImage(frames[i].canvas,(i%4)*w,Math.floor(i/4)*h,w,h);return writePng(canvas,resolve(artifacts,"proofs",id,`${name}-${theme}.png`));}
async function contactProof(id,frames,contacts){const canvas=createCanvas(320*4,640),ctx=canvas.getContext("2d");ctx.fillStyle="#20252b";ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<4;i++){ctx.drawImage(frames[i+4].canvas,i*320,0,320,640);ctx.strokeStyle="#ff2d55";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(i*320,contacts[DIRECTIONS[i]]*2);ctx.lineTo(i*320+320,contacts[DIRECTIONS[i]]*2);ctx.stroke();}return writePng(canvas,resolve(artifacts,"proofs",id,`${id}-seat-contact-2x-dark.png`));}
function sourceProof(id,sheet,extraction){const canvas=createCanvas(sheet.width,sheet.height),ctx=canvas.getContext("2d");ctx.drawImage(sheet,0,0);ctx.strokeStyle="#ff2d55";ctx.lineWidth=Math.max(2,Math.round(sheet.width/768));for(const cell of extraction.cells)ctx.strokeRect(cell.sourceRect.x,cell.sourceRect.y,cell.sourceRect.width,cell.sourceRect.height);return writePng(canvas,resolve(artifacts,"proofs",id,`${id}-source-crops.png`));}

mkdirSync(artifacts,{recursive:true}); const records=[], skipped=[];
for(const identity of config.identities){const files=sourceFiles(identity.id);if(!existsSync(files.png)||!existsSync(files.prompt)||!files.provenance){skipped.push({id:identity.id,reason:"complete png + exact prompt + provenance bundle not yet available"});continue;}
  console.error(`packaging ${identity.id}`); const sheet=await loadCanvas(files.png); let extraction;
  try { extraction=extractEight(sheet); } catch (error) { skipped.push({id:identity.id,reason:`source rejected: ${error.message}`}); continue; }
  let frames; try { frames=normalizeCells(extraction.cells,config.target); } catch (error) { skipped.push({id:identity.id,reason:`normalization rejected: ${error.message}`}); continue; }
  const southHeight=frames[0].measure.visibleBounds.height;
  assert(Math.abs(southHeight-config.target.standingSouthVisibleHeight)<=1,`${identity.id} South target height drift`);
  const configured=config.seatContacts[identity.id]??{}, contacts=Object.fromEntries(DIRECTIONS.map((direction,index)=>[direction,configured[direction]??inferSeatContact(frames[index+4])]));
  const poses={stand:{},sit:{}};
  for(let i=0;i<8;i++){const slot=SLOTS[i],out=writePng(frames[i].canvas,resolve(artifacts,"characters",identity.id,`${slot.pose}-${slot.direction}.png`));poses[slot.pose][slot.direction]={...out,anchors:{bodyAxisX:80,floorY:287,...(slot.pose==="sit"?{seatContactY:contacts[slot.direction]}:{})},visibleBounds:frames[i].measure.visibleBounds,transform:frames[i].transform,sourceCell:{index:i,rect:extraction.cells[i].sourceRect,principalArea:extraction.cells[i].principal.area,boundaryAlphaPixels:extraction.cells[i].measure.borderPixels}};}
  const proof={nativeLight:await gridProof(identity.id,frames,1,"light",`${identity.id}-native`),nativeDark:await gridProof(identity.id,frames,1,"dark",`${identity.id}-native`),gameLight:await gridProof(identity.id,frames,0.2,"light",`${identity.id}-game-32x64`),gameDark:await gridProof(identity.id,frames,0.2,"dark",`${identity.id}-game-32x64`),sourceCrops:sourceProof(identity.id,sheet,extraction),seatContact:await contactProof(identity.id,frames,contacts)};
  const accepted=config.productionQaAccepted&&Object.keys(configured).length===4;records.push({id:identity.id,cohort:config.cohort,category:config.category,role:identity.role,eligibleStaffRoleDefinitionIds:[identity.role],artistBatch:identity.artistBatch,status:accepted?"agent-production-qa-accepted-root-authorized-local-integration":"agent-source-reviewed-packaged-seat-contacts-pending-parent-review",ownerApproval:false,runtimePromotionAuthorized:accepted,source:{png:{path:posix(files.png),sha256:fileSha(files.png)},prompt:{path:posix(files.prompt),sha256:fileSha(files.prompt),promptProvenance:files.promptProvenance},provenance:{path:posix(files.provenance),sha256:fileSha(files.provenance)},dimensions:{width:sheet.width,height:sheet.height},order:config.sourceOrder,segmentation:{method:"eight alpha-connected principal figures; rows grouped by centroid; crop cuts placed only between non-overlapping figure bounds",threshold:13,rowCut:extraction.rowCut,componentCount:extraction.componentCount,ignoredComponents:extraction.ignoredComponents,boundaryExceptions:extraction.cells.map((cell,index)=>({index,pixels:cell.measure.borderPixels})).filter(entry=>entry.pixels>0),boundaryPolicy:"principal figure must remain strictly inside; at most 8 recorded nonprincipal alpha-threshold pixels may meet a derived cell boundary; no pixels are removed"}},calibration:{policy:"one whole-body scale across all eight poses",targetStandingSouthVisibleHeight:246,appliedScale:frames[0].transform.scale},seatContacts:{status:accepted?"agent-authored-parent-production-qa-accepted":Object.keys(configured).length===4?"authored-pending-parent-review":"geometric-inference-pending-parent-authorship-and-review",outputY:contacts},poses,proof});
}
const manifest={schemaVersion:"gs026-employee-expansion-package/v1",status:records.length===25&&config.productionQaAccepted?"agent-production-qa-accepted-local-integration-authorized-not-published":"partial-additive-candidate-not-published",runtimeIntegration:{authorized:Boolean(config.productionQaAccepted),ready:records.length===25,published:false},canvas:config.target,baseRuntimeLedger:"tools/character-mapping/gs026-employee-expansion-v1/base-runtime-hash-ledger.json",counts:{plannedIdentities:25,packagedIdentities:records.length,packagedPoses:records.length*8,pendingIdentities:25-records.length},records,skipped};writeFileSync(resolve(artifacts,"manifest.json"),JSON.stringify(manifest,null,2)+"\n");console.log(JSON.stringify({status:"PASS",...manifest.counts,ids:records.map(x=>x.id)}));
