import assert from "node:assert/strict";import{copyFileSync,existsSync,mkdirSync,readFileSync,writeFileSync}from"node:fs";import{dirname,resolve}from"node:path";import{fileURLToPath}from"node:url";import{fileSha}from"./pipeline.mjs";
const tool=dirname(fileURLToPath(import.meta.url)),repo=resolve(tool,"../../.."),artifactRoot=resolve(repo,"artifacts/character-statics/gs026-employee-expansion-v1"),manifestPath=resolve(artifactRoot,"manifest.json"),manifest=JSON.parse(readFileSync(manifestPath,"utf8")),baselineRoot=resolve(tool,"baseline"),baseRegistry=JSON.parse(readFileSync(resolve(baselineRoot,"characterStillRegistry.generated.json"),"utf8")),baseProvenance=JSON.parse(readFileSync(resolve(baselineRoot,"provenance-manifest.json"),"utf8")),ledger=JSON.parse(readFileSync(resolve(tool,"base-runtime-hash-ledger.json"),"utf8"));
const registryPath=resolve(repo,"apps/player/src/art/characterStillRegistry.generated.json"),provenancePath=resolve(repo,"tools/character-mapping/gs026-runtime-stills/provenance-manifest.json"),publicRoot=resolve(repo,"apps/player/public/art/characters/gs026-employee-expansion-v1"),directions=["south","east","west","north"];
assert.equal(manifest.records.length,25,"promotion requires all 25 candidate identities");assert.equal(manifest.records.every(x=>x.seatContacts.status==="agent-authored-parent-production-qa-accepted"&&x.runtimePromotionAuthorized),true);assert.equal(baseRegistry.characters.length,128);assert.equal(fileSha(resolve(baselineRoot,"characterStillRegistry.generated.json")),ledger.registry.sha256,"durable baseline registry drift");assert.equal(fileSha(resolve(baselineRoot,"provenance-manifest.json")),ledger.provenance.sha256,"durable baseline provenance drift");assert.equal(ledger.assetCount,1054);for(const asset of ledger.assets)assert.equal(fileSha(resolve(repo,asset.path)),asset.sha256,`old runtime asset drift ${asset.path}`);
const activeRegistry=JSON.parse(readFileSync(registryPath,"utf8")),ownIds=manifest.records.map(x=>x.id);const activeIsBase=JSON.stringify(activeRegistry.characters)===JSON.stringify(baseRegistry.characters),activeIsOwnExpansion=activeRegistry.characters.length===153&&JSON.stringify(activeRegistry.characters.slice(0,128))===JSON.stringify(baseRegistry.characters)&&JSON.stringify(activeRegistry.characters.slice(128).map(x=>x.id))===JSON.stringify(ownIds);assert(activeIsBase||activeIsOwnExpansion,"active registry contains unrelated additions; refusing to overwrite");
const characters=[],assets=[];
for(const record of manifest.records){const poses={stand:{},sit:{}};for(const posture of ["stand","sit"])for(const direction of directions){const source=record.poses[posture][direction],sourceFile=resolve(repo,source.file),outputFile=resolve(publicRoot,record.id,`${posture}-${direction}.png`);mkdirSync(dirname(outputFile),{recursive:true});copyFileSync(sourceFile,outputFile);assert.equal(fileSha(outputFile),source.sha256);poses[posture][direction]={url:`art/characters/gs026-employee-expansion-v1/${record.id}/${posture}-${direction}.png`,sha256:source.sha256,width:160,height:320,anchors:source.anchors,visibleBounds:source.visibleBounds};assets.push({identityId:record.id,pose:`${posture}-${direction}`,sourceInput:"employeeExpansionV1",sourceFile:source.file,sourceSha256:source.sha256,outputFile:`apps/player/public/art/characters/gs026-employee-expansion-v1/${record.id}/${posture}-${direction}.png`,outputSha256:source.sha256});}characters.push({id:record.id,cohort:"employeeCoverage",category:"employee",role:record.role,poses});}
const registry={...baseRegistry,integrationStatus:"agent-production-qa-accepted-local-integration-authorized-not-published",counts:{identities:153,cardinalPoses:1224,clipboardPoses:30,assets:1254},characters:[...baseRegistry.characters,...characters]};writeFileSync(registryPath,JSON.stringify(registry,null,2)+"\n");
const provenance={...baseProvenance,integrationStatus:"agent-production-qa-accepted-local-integration-authorized-not-published",inputs:{...baseProvenance.inputs,employeeExpansionV1:{file:"artifacts/character-statics/gs026-employee-expansion-v1/manifest.json",sha256:fileSha(manifestPath),reviewStatus:"agent-production-qa-accepted-root-authorized-local-integration",ownerArtApproval:false,promptProvenanceLimitation:"identities 002-013 use reconstructed batch-template prompt records; manifests do not represent those as exact tool inputs"}},registry:{file:"apps/player/src/art/characterStillRegistry.generated.json",sha256:fileSha(registryPath)},counts:registry.counts,assets:[...baseProvenance.assets,...assets]};writeFileSync(provenancePath,JSON.stringify(provenance,null,2)+"\n");
console.log(JSON.stringify({status:"PASS",oldIdentitiesPreserved:128,newIdentities:25,assetsCopied:assets.length,counts:registry.counts,registrySha256:fileSha(registryPath),provenanceSha256:fileSha(provenancePath)}));
