import { readFile } from 'node:fs/promises';
import { chromium } from 'playwright';
const fragment = await readFile('tools/room-design/front-desk-layout/front-desk-layout.html','utf8');
const browser = await chromium.launch({headless:true, executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'});
const page = await browser.newPage({viewport:{width:1280,height:900}});
await page.setContent(`<main>${fragment}</main>`);
await page.waitForFunction(()=>window.__frontDeskLayout?.atlasReady());
async function capture(name){await page.screenshot({path:`tools/room-design/front-desk-layout/evidence/art-${name}.png`,fullPage:true});}
await capture('closed');
await capture('upkeep-full-clean');
await page.selectOption('#fd-water','empty');
await capture('upkeep-empty-clean');
await page.selectOption('#fd-cleanliness','litter');
await capture('upkeep-empty-litter');
await page.getByLabel('Show floor footprints, routes, and service points').check();
await capture('upkeep-service-points');
await page.getByLabel('Show floor footprints, routes, and service points').uncheck();
await page.selectOption('#fd-water','full');
await page.selectOption('#fd-cleanliness','clean');
await page.getByRole('button',{name:'Wall door N5'}).click();
await page.getByRole('button',{name:'Wall door EA'}).click();
await capture('door-n5-ea-cooler-permanent');
await page.getByRole('button',{name:'Wall door N5'}).click();
await page.getByRole('button',{name:'Wall door EA'}).click();
await page.getByRole('button',{name:'Wall door N2'}).click();
await capture('door-n2-tall');
await page.getByRole('button',{name:'Wall door N2'}).click();
await page.getByLabel('N2', { exact: true }).check();
await page.getByLabel('N4', { exact: true }).check();
await capture('adjacent-n2-n4');
await page.getByLabel('N2', { exact: true }).uncheck();
await page.getByLabel('N4', { exact: true }).uncheck();
for (const id of ['N1','N2','N3','N4','N5']) await page.getByLabel(id, { exact: true }).check();
await capture('adjacent-all-north');
for (const id of ['N1','N2','N3','N4','N5']) await page.getByLabel(id, { exact: true }).uncheck();
await page.getByLabel('N2', { exact: true }).check();
await page.getByRole('button',{name:'Wall door N2'}).click();
await capture('door-n2-adjacent');
await page.getByRole('button',{name:'Wall door N2'}).click();
await page.getByLabel('N2', { exact: true }).uncheck();
await page.getByLabel('Show floor footprints, routes, and service points').check();
await capture('footprints');
await page.getByLabel('Show floor footprints, routes, and service points').uncheck();
await page.getByRole('button',{name:'Wall door WB'}).click();
await page.getByRole('button',{name:'Wall door EB'}).click();
await capture('side-wb-eb');
await page.getByRole('button',{name:'Wall door WB'}).click();
await page.getByRole('button',{name:'Wall door EB'}).click();
await page.getByRole('button',{name:'Wall door ED'}).click();
await capture('ed-stay');
await page.evaluate(()=>{const select=document.querySelector('#fd-ed-chair');select.value='hide';select.dispatchEvent(new Event('change',{bubbles:true}))});
await capture('ed-hide');
await page.evaluate(()=>{const select=document.querySelector('#fd-ed-chair');select.value='stay';select.dispatchEvent(new Event('change',{bubbles:true}))});
await page.getByRole('button',{name:'Wall door ED'}).click();
await page.getByRole('button',{name:'Wall door N1'}).click();
await page.getByRole('button',{name:'Wall door WA'}).click();
await capture('corner-n1-wa');
for(const id of ['N1','N2','N3','N4','N5','WA','WB','WC','WD','EA','EB','EC','ED']) {const b=page.getByRole('button',{name:`Wall door ${id}`}); if(await b.getAttribute('aria-pressed') !== 'true') await b.click();}
await capture('all-open');
await browser.close();
