import { validatePrototypeBalanceRelease } from "./schema";

export const PROTOTYPE_BALANCE_RELEASE = validatePrototypeBalanceRelease({
  id: "balance.synthetic.prototype.v1",
  schemaVersion: 1,
  publicationStatus: "prototype_unpublished",
  facility: {
    // Zoom 1 frames roughly the central 16 columns. Zooming out reveals the
    // full 24-column buildable site so expansion adds usable grid space.
    gridWidth: 72,
    gridHeight: 32,
    hallwayRoomDefinitionId: "room.hallway",
    protectedRoomDefinitionIds: ["room.front_desk"],
    roomResalePercent: 25,
    // Two visible grid steps per simulated minute keeps ordinary movement
    // legible without turning short clinic routes into long real-time waits.
    staffMovementIntervalTicks: 1,
    // Four tiles per facility minute keeps the wide sidewalk entrance
    // readable without making a new player wait nearly twenty real seconds
    // before the first chart becomes available.
    patientTravelTilesPerTick: 4,
    // Keeps the required Level 0 examination-room purchase reachable even
    // after the protected tutorial's lowest authored payout.
    startingCash: 120,
    startingSatisfaction: 95,
    maximumPlayableLevel: 1,
    initialRooms: [
      {
        id: "room.instance.founder_desk",
        roomDefinitionId: "room.front_desk",
        x: 33,
        y: 28,
        orientation: 0,
        // Doors are explicit build objects. The reducer creates only the
        // protected south-facing public entrance for a new campaign.
        doorSide: null,
        upgradeLevel: 1,
      },
    ],
    roomDefinitions: [
      {
        id: "room.front_desk",
        displayName: "Front Desk",
        kind: "room",
        unlockFacilityLevel: 0,
        width: 5,
        height: 4,
        defaultDoorSide: "north",
        constructionCost: 0,
        upkeepPerExpenseInterval: 6,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        maximumInstances: 1,
        maximumUpgradeLevel: 1,
        upgradeCosts: [],
        upkeepPerUpgradeLevel: 0,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 0,
        requiredRoomDefinitionIds: [],
        capabilityIds: [],
      },
      {
        id: "room.hallway",
        displayName: "Hallway",
        kind: "hallway",
        unlockFacilityLevel: 0,
        width: 1,
        height: 1,
        defaultDoorSide: null,
        constructionCost: 35,
        upkeepPerExpenseInterval: 0,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        maximumInstances: null,
        maximumUpgradeLevel: 1,
        upgradeCosts: [],
        upkeepPerUpgradeLevel: 0,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 0,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.walkable_hallway"],
      },
      {
        id: "room.examination",
        displayName: "Examination Room",
        kind: "room",
        unlockFacilityLevel: 0,
        width: 3,
        height: 2,
        defaultDoorSide: "south",
        constructionCost: 160,
        upkeepPerExpenseInterval: 6,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 2,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [90, 140, 210, 300],
        upkeepPerUpgradeLevel: 1,
        workloadLimitContributionPerUpgradeLevel: 1,
        serviceDurationReductionPercentPerUpgradeLevel: 5,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: [
          "capability.examination",
          "capability.synthetic.in_house_analysis",
        ],
      },
      {
        id: "room.bathroom",
        displayName: "Bathroom",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 2,
        height: 2,
        defaultDoorSide: "south",
        constructionCost: 225,
        upkeepPerExpenseInterval: 4,
        satisfactionOnBuild: 2,
        workloadLimitContribution: 0,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [70, 110, 170, 250],
        upkeepPerUpgradeLevel: 1,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 0,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.patient_bathroom"],
      },
      {
        id: "room.waiting",
        displayName: "Waiting Room",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 4,
        height: 3,
        defaultDoorSide: "south",
        constructionCost: 350,
        upkeepPerExpenseInterval: 7,
        satisfactionOnBuild: 2,
        workloadLimitContribution: 2,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [110, 170, 250, 360],
        upkeepPerUpgradeLevel: 1,
        workloadLimitContributionPerUpgradeLevel: 1,
        serviceDurationReductionPercentPerUpgradeLevel: 0,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.waiting_seats"],
      },
      {
        id: "room.xray",
        displayName: "X-ray Room",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 3,
        height: 3,
        defaultDoorSide: "south",
        constructionCost: 750,
        upkeepPerExpenseInterval: 14,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [190, 280, 400, 560],
        upkeepPerUpgradeLevel: 2,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 8,
        requiredRoomDefinitionIds: ["room.imaging_control"],
        capabilityIds: ["capability.xray_machine"],
      },
      {
        id: "room.imaging_control",
        displayName: "Imaging Control Room",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 2,
        height: 2,
        defaultDoorSide: "south",
        constructionCost: 440,
        upkeepPerExpenseInterval: 9,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [90, 140, 210, 300],
        upkeepPerUpgradeLevel: 1,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 5,
        requiredRoomDefinitionIds: ["room.examination"],
        capabilityIds: ["capability.imaging_control"],
      },
      {
        id: "room.minor_procedure",
        displayName: "Minor-Procedure Room",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 3,
        height: 3,
        defaultDoorSide: "south",
        constructionCost: 800,
        upkeepPerExpenseInterval: 15,
        satisfactionOnBuild: 1,
        workloadLimitContribution: 1,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [220, 330, 480, 680],
        upkeepPerUpgradeLevel: 2,
        workloadLimitContributionPerUpgradeLevel: 1,
        serviceDurationReductionPercentPerUpgradeLevel: 5,
        requiredRoomDefinitionIds: ["room.examination"],
        capabilityIds: ["capability.minor_procedure"],
      },
    ],
    staffRoleDefinitions: [
      {
        id: "staff.receptionist",
        displayName: "Receptionist",
        unlockFacilityLevel: 1,
        hiringCost: 180,
        salaryPerExpenseInterval: 18,
        minimumSalaryPerExpenseInterval: 14,
        maximumSalaryPerExpenseInterval: 30,
        salaryAdjustmentStep: 2,
        moralePerSalaryStep: 5,
        baseMorale: 75,
        maximumEmployees: 1,
        maximumTrainingLevel: 5,
        workloadLimitContribution: 1,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.staff.reception"],
      },
      {
        id: "staff.imaging_technician",
        displayName: "Imaging Technician",
        unlockFacilityLevel: 1,
        hiringCost: 300,
        salaryPerExpenseInterval: 26,
        minimumSalaryPerExpenseInterval: 20,
        maximumSalaryPerExpenseInterval: 42,
        salaryAdjustmentStep: 2,
        moralePerSalaryStep: 5,
        baseMorale: 75,
        maximumEmployees: 1,
        maximumTrainingLevel: 5,
        workloadLimitContribution: 0,
        requiredRoomDefinitionIds: ["room.xray", "room.imaging_control"],
        capabilityIds: ["capability.staff.imaging_technician"],
      },
    ],
    stageDefinitions: [
      {
        level: 0,
        displayName: "Level 0 - Founder Desk Clinic",
        minimumClinicalXp: 10,
        minimumCompletedEncounters: 0,
        satisfactionMustBeGreaterThan: 90,
        requiredRoomDefinitionIds: ["room.examination"],
        requiredStaffRoleIds: [],
        nextFacilityLevel: 1,
      },
      {
        level: 1,
        displayName: "Level 1 - First Clinic",
        minimumClinicalXp: 150,
        minimumCompletedEncounters: 0,
        satisfactionMustBeGreaterThan: 90,
        requiredRoomDefinitionIds: [
          "room.xray",
          "room.minor_procedure",
        ],
        requiredStaffRoleIds: ["staff.imaging_technician"],
        nextFacilityLevel: null,
      },
    ],
    tutorialRequiredRoomDefinitionId: "room.examination",
    tutorialMinimumOperatingBuffer: 0,
  },
  workload: {
    baseRoutineLimit: 2,
    criticalReservedSlots: 1,
  },
  clock: {
    facilityHoursPerTick: 1,
    realMillisecondsPerFacilityHour: 60_000,
    simulatedMinutesPerTick: 1,
    realMillisecondsPerFacilityMinuteAt1x: 1_000,
    supportedSpeeds: [1, 2, 4],
    dayStartHour: 8,
    dayEndHour: 18,
  },
  patientPatience: {
    routineDurationTicks: 16,
    warningAtRemainingTicks: [8, 4, 0],
    // Early warning is informational; sustained and final delays add mild,
    // one-time facility-satisfaction pressure.
    satisfactionPenaltyAtWarningTicks: [4, 0],
    satisfactionPenaltyPerWarning: 1,
    leftBeforeSeenSatisfactionPenalty: 2,
  },
  patientSatisfaction: {
    startingValue: 100,
    idleGraceMinutes: 20,
    decayIntervalMinutes: 5,
    decayPerInterval: 1,
    sidewalkDecayMultiplierPercent: 150,
    warningThresholds: [75, 60, 40, 20, 0],
    walkoutThresholdMinimum: 0,
    walkoutThresholdMaximum: 59,
    correctCareRecovery: 3,
    incorrectCarePenalty: 8,
    cleanRoomThreshold: 80,
    dirtyRoomThreshold: 45,
    cleanRoomCompletionBonus: 2,
    dirtyRoomCompletionPenalty: 4,
    roomUpgradeBonusPerLevel: 1,
    maximumRoomUpgradeBonus: 3,
    happyStaffMoraleThreshold: 80,
    unhappyStaffMoraleThreshold: 45,
    happyStaffCompletionBonus: 2,
    unhappyStaffCompletionPenalty: 3,
    maximumAmenityCompletionBonus: 3,
    roomCleanlinessLossPerEncounter: 1,
    rollingWindowSize: 10,
  },
  environment: {
    litterSpawnMinimumMinutes: 45,
    litterSpawnMaximumMinutes: 90,
    maximumLitterItems: 3,
    litterCleanupRestore: 12,
    litterCleanupSatisfactionBonus: 1,
    waterCoolerDrainIntervalMinutes: 60,
    waterCoolerDrainPerInterval: 25,
    waterCoolerLowThreshold: 25,
    waterRefillSatisfactionBonus: 1,
    praiseMoraleBonus: 5,
    praiseCooldownMinutes: 600,
    founderInteractionMinutes: 2,
    idleActionMinimumMinutes: 10,
    idleActionMaximumMinutes: 25,
    idleActionChancePercent: 35,
  },
  arrivals: {
    levelZeroRecoveryIntervalTicks: 2,
    levelOneRoutineIntervalTicks: 2,
    firstArrivalMinimumMinutes: 35,
    firstArrivalMaximumMinutes: 75,
    routineBaseIntervalMinutes: 60,
    routineVariationMinutes: 15,
  },
  economy: {
    expenseIntervalTicks: 10,
    postingIntervalMinutes: 15,
  },
  advertising: {
    levels: [
      {
        level: 0,
        displayName: "Off",
        hourlyCost: 0,
        arrivalIntervalMultiplierPercent: 100,
      },
      {
        level: 1,
        displayName: "Local listings",
        hourlyCost: 4,
        arrivalIntervalMultiplierPercent: 92,
      },
      {
        level: 2,
        displayName: "Neighborhood ads",
        hourlyCost: 8,
        arrivalIntervalMultiplierPercent: 84,
      },
      {
        level: 3,
        displayName: "Aggressive outreach",
        hourlyCost: 14,
        arrivalIntervalMultiplierPercent: 75,
      },
    ],
  },
  insolvency: {
    moraleDecayPerPosting: 3,
    employeeQuittingThreshold: 10,
  },
  emergencyGlp1: {
    cashEligibilityThreshold: 200,
    cooldownTicks: 1,
    cooldownMinutes: 60,
    payment: 25,
    sarcasmStartsAtUse: 5,
    sarcasmLines: [
      "Your commitment to comprehensive metabolic care has been noted.",
      "Another individualized 90-second consultation completed.",
      "Prior authorization remains someone elses problem.",
      "At this point, this is less of a safety net and more of a business model.",
      "This was supposed to be an emergency measure.",
      "One more visit and we have to call this a service line.",
      "The safety net has developed a revenue forecast.",
      "Your surgical clinic has developed a suspiciously scalable side hustle.",
      "Continuity of care is limited. Continuity of revenue is excellent.",
      "The cash balance has improved. The clinics identity is less certain.",
      "The emergency button would like to discuss its promotion.",
      "The founder has discovered recurring revenue.",
      "This is becoming less of a contingency plan and more of a lifestyle.",
      "Even the algorithm has standards.",
    ],
  },
  development: {
    fastForwardTickCount: 10,
    addMoneyAmount: 100,
  },
  learning: {
    parameterSetId: "learning.prototype.fsrs6.v1",
    requestedRetention: 0.9,
    maximumIntervalDays: 36_500,
    minimumAgainDelayMinutes: 30,
    enableFuzz: false,
  },
  clinicalSettlement: {
    patientRewardTiers: [
      {
        id: "reward.tutorial",
        completionRevenue: 45,
      },
      {
        id: "reward.clinic_basic",
        completionRevenue: 75,
      },
      {
        id: "reward.referral",
        completionRevenue: 60,
      },
    ],
    maximumQualityRevenueBonus: 15,
    maximumIncorrectFinancialConsequence: 5,
    clinicalXpPerCorrectFirstAnswer: 10,
    clinicalXpPerIncorrectFirstAnswer: 2,
    firstTutorialCorrectDecisionXp: 20,
    levelZeroBasePayment: 15,
    levelZeroPerQuestionPayment: 10,
    levelZeroPerCorrectPayment: 50,
    levelOneBasePayment: 20,
    levelOnePerQuestionPayment: 15,
    levelOnePerCorrectPayment: 65,
    // Individual patient-satisfaction effects now live in patientSatisfaction.
    // These legacy structural bounds remain zero in the unpublished fixture.
    maximumCorrectSatisfactionBonus: 0,
    maximumIncorrectSatisfactionConsequence: 0,
    patientSatisfactionDeltaMinimum: 0,
    patientSatisfactionDeltaMaximum: 0,
  },
  services: [
    {
      id: "service.synthetic.analysis",
      displayName: "Synthetic Analysis",
      routes: [
        {
          id: "route.synthetic.in_house",
          displayName: "In-house synthetic analysis",
          durationTicks: 10,
          requiredCapabilityId: "capability.synthetic.in_house_analysis",
          requiredCapabilityIds: [],
          preference: 0,
        },
        {
          id: "route.synthetic.outsourced",
          displayName: "Outsourced synthetic analysis",
          // The first interface tutorial should demonstrate a pending result
          // without making a new player wait 90 real seconds.
          durationTicks: 10,
          requiredCapabilityId: null,
          requiredCapabilityIds: [],
          preference: 1,
        },
      ],
    },
    {
      id: "service.xray",
      displayName: "X-ray",
      routes: [
        {
          id: "route.xray.in_house",
          displayName: "In-house X-ray",
          durationTicks: 60,
          satisfactionOnResult: 1,
          requiredCapabilityId: "capability.xray_machine",
          requiredCapabilityIds: [
            "capability.imaging_control",
            "capability.staff.imaging_technician",
          ],
          preference: 0,
          patientTravel: {
            originRoomDefinitionId: "room.examination",
            destinationRoomDefinitionId: "room.xray",
            roundTrip: true,
          },
        },
        {
          id: "route.xray.outsourced",
          displayName: "Outsourced X-ray",
          durationTicks: 120,
          requiredCapabilityId: null,
          requiredCapabilityIds: [],
          preference: 1,
        },
      ],
    },
    {
      id: "service.basic_labs",
      displayName: "Basic laboratory testing",
      routes: [
        {
          id: "route.basic_labs.outsourced",
          displayName: "Off-site basic laboratory testing",
          durationTicks: 60,
          requiredCapabilityId: null,
          requiredCapabilityIds: [],
          preference: 1,
        },
      ],
    },
  ],
});

export const EXAMINATION_ROOM_DEFINITION_ID = "room.examination";
export const LEVEL_ONE_ROOM_DEFINITION_IDS = [
  "room.bathroom",
  "room.waiting",
  "room.xray",
  "room.imaging_control",
  "room.minor_procedure",
] as const;
export const RECEPTIONIST_ROLE_ID = "staff.receptionist";
export const IMAGING_TECHNICIAN_ROLE_ID = "staff.imaging_technician";
