import { validatePrototypeBalanceRelease } from "./schema";

export const PROTOTYPE_BALANCE_RELEASE = validatePrototypeBalanceRelease({
  id: "balance.synthetic.prototype.v1",
  schemaVersion: 1,
  publicationStatus: "prototype_unpublished",
  facility: {
    gridWidth: 16,
    gridHeight: 10,
    startingCash: 90,
    startingSatisfaction: 95,
    maximumPlayableLevel: 1,
    initialRooms: [
      {
        id: "room.instance.founder_desk",
        roomDefinitionId: "room.front_desk",
        x: 1,
        y: 2,
      },
    ],
    roomDefinitions: [
      {
        id: "room.front_desk",
        displayName: "Founder Front Desk",
        unlockFacilityLevel: 0,
        width: 5,
        height: 4,
        constructionCost: 0,
        upkeepPerExpenseInterval: 0,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        requiredRoomDefinitionIds: [],
        capabilityIds: [],
      },
      {
        id: "room.examination",
        displayName: "Examination Room",
        unlockFacilityLevel: 0,
        width: 3,
        height: 2,
        constructionCost: 120,
        upkeepPerExpenseInterval: 2,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 2,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: [
          "capability.examination",
          "capability.synthetic.in_house_analysis",
        ],
      },
      {
        id: "room.bathroom",
        displayName: "Bathroom",
        unlockFacilityLevel: 1,
        width: 2,
        height: 2,
        constructionCost: 90,
        upkeepPerExpenseInterval: 1,
        satisfactionOnBuild: 2,
        workloadLimitContribution: 0,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.patient_bathroom"],
      },
      {
        id: "room.waiting",
        displayName: "Waiting Room",
        unlockFacilityLevel: 1,
        width: 4,
        height: 3,
        constructionCost: 150,
        upkeepPerExpenseInterval: 2,
        satisfactionOnBuild: 2,
        workloadLimitContribution: 2,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.waiting_seats"],
      },
      {
        id: "room.xray",
        displayName: "X-ray Room",
        unlockFacilityLevel: 1,
        width: 3,
        height: 3,
        constructionCost: 260,
        upkeepPerExpenseInterval: 4,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        requiredRoomDefinitionIds: ["room.imaging_control"],
        capabilityIds: ["capability.xray_machine"],
      },
      {
        id: "room.imaging_control",
        displayName: "Imaging Control Room",
        unlockFacilityLevel: 1,
        width: 2,
        height: 2,
        constructionCost: 120,
        upkeepPerExpenseInterval: 2,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        requiredRoomDefinitionIds: ["room.examination"],
        capabilityIds: ["capability.imaging_control"],
      },
      {
        id: "room.minor_procedure",
        displayName: "Minor-Procedure Room",
        unlockFacilityLevel: 1,
        width: 3,
        height: 3,
        constructionCost: 300,
        upkeepPerExpenseInterval: 4,
        satisfactionOnBuild: 1,
        workloadLimitContribution: 1,
        requiredRoomDefinitionIds: ["room.examination"],
        capabilityIds: ["capability.minor_procedure"],
      },
    ],
    staffRoleDefinitions: [
      {
        id: "staff.receptionist",
        displayName: "Receptionist",
        unlockFacilityLevel: 1,
        hiringCost: 80,
        salaryPerExpenseInterval: 3,
        workloadLimitContribution: 1,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.staff.reception"],
      },
      {
        id: "staff.imaging_technician",
        displayName: "Imaging Technician",
        unlockFacilityLevel: 1,
        hiringCost: 120,
        salaryPerExpenseInterval: 5,
        workloadLimitContribution: 0,
        requiredRoomDefinitionIds: ["room.xray", "room.imaging_control"],
        capabilityIds: ["capability.staff.imaging_technician"],
      },
    ],
    stageDefinitions: [
      {
        level: 0,
        displayName: "Level 0 - Founder Desk Clinic",
        minimumClinicalXp: 5,
        minimumCompletedEncounters: 2,
        satisfactionMustBeGreaterThan: 90,
        requiredRoomDefinitionIds: ["room.examination"],
        requiredStaffRoleIds: [],
        nextFacilityLevel: 1,
      },
      {
        level: 1,
        displayName: "Level 1 - First Clinic",
        minimumClinicalXp: 45,
        minimumCompletedEncounters: 6,
        satisfactionMustBeGreaterThan: 90,
        requiredRoomDefinitionIds: [
          "room.bathroom",
          "room.waiting",
          "room.xray",
          "room.imaging_control",
          "room.minor_procedure",
        ],
        requiredStaffRoleIds: [
          "staff.receptionist",
          "staff.imaging_technician",
        ],
        nextFacilityLevel: null,
      },
    ],
    tutorialRequiredRoomDefinitionId: "room.examination",
    tutorialMinimumOperatingBuffer: 20,
  },
  workload: {
    baseRoutineLimit: 2,
    criticalReservedSlots: 1,
  },
  patientPatience: {
    routineDurationTicks: 12,
    warningAtRemainingTicks: [5, 2, 0],
    leftBeforeSeenSatisfactionPenalty: 2,
  },
  arrivals: {
    levelZeroRecoveryIntervalTicks: 5,
    levelOneRoutineIntervalTicks: 6,
  },
  economy: {
    expenseIntervalTicks: 10,
  },
  development: {
    fastForwardTickCount: 10,
    addMoneyAmount: 100,
  },
  learning: {
    parameterSetId: "learning.prototype.fsrs6.v1",
    requestedRetention: 0.9,
    maximumIntervalDays: 36_500,
    minimumAgainDelayMinutes: 30,
    enableFuzz: false,
  },
  clinicalSettlement: {
    patientRewardTiers: [
      {
        id: "reward.tutorial",
        completionRevenue: 55,
      },
      {
        id: "reward.clinic_basic",
        completionRevenue: 95,
      },
      {
        id: "reward.referral",
        completionRevenue: 70,
      },
    ],
    maximumQualityRevenueBonus: 15,
    maximumIncorrectFinancialConsequence: 5,
    clinicalXpPerCorrectFirstAnswer: 5,
    maximumCorrectSatisfactionBonus: 2,
    maximumIncorrectSatisfactionConsequence: 2,
    patientSatisfactionDeltaMinimum: -2,
    patientSatisfactionDeltaMaximum: 2,
  },
  services: [
    {
      id: "service.synthetic.analysis",
      displayName: "Synthetic Analysis",
      routes: [
        {
          id: "route.synthetic.in_house",
          displayName: "In-house synthetic analysis",
          durationTicks: 1,
          requiredCapabilityId: "capability.synthetic.in_house_analysis",
          requiredCapabilityIds: [],
          preference: 0,
        },
        {
          id: "route.synthetic.outsourced",
          displayName: "Outsourced synthetic analysis",
          durationTicks: 3,
          requiredCapabilityId: null,
          requiredCapabilityIds: [],
          preference: 1,
        },
      ],
    },
    {
      id: "service.xray",
      displayName: "X-ray",
      routes: [
        {
          id: "route.xray.in_house",
          displayName: "In-house X-ray",
          durationTicks: 2,
          requiredCapabilityId: "capability.xray_machine",
          requiredCapabilityIds: [
            "capability.imaging_control",
            "capability.staff.imaging_technician",
          ],
          preference: 0,
        },
        {
          id: "route.xray.outsourced",
          displayName: "Outsourced X-ray",
          durationTicks: 6,
          requiredCapabilityId: null,
          requiredCapabilityIds: [],
          preference: 1,
        },
      ],
    },
  ],
});

export const EXAMINATION_ROOM_DEFINITION_ID = "room.examination";
export const LEVEL_ONE_ROOM_DEFINITION_IDS = [
  "room.bathroom",
  "room.waiting",
  "room.xray",
  "room.imaging_control",
  "room.minor_procedure",
] as const;
export const RECEPTIONIST_ROLE_ID = "staff.receptionist";
export const IMAGING_TECHNICIAN_ROLE_ID = "staff.imaging_technician";
