import { validatePrototypeBalanceRelease } from "./schema";

export const PROTOTYPE_BALANCE_RELEASE = validatePrototypeBalanceRelease({
  id: "balance.synthetic.prototype.v1",
  schemaVersion: 1,
  publicationStatus: "prototype_unpublished",
  facility: {
    // Zoom 1 frames roughly the central 16 columns. Zooming out reveals the
    // full 24-column buildable site so expansion adds usable grid space.
    gridWidth: 24,
    gridHeight: 10,
    hallwayRoomDefinitionId: "room.hallway",
    protectedRoomDefinitionIds: ["room.front_desk"],
    roomResalePercent: 25,
    // One visible grid step per facility hour keeps hiring travel meaningful
    // without leaving a new employee unusable for several real clinic days.
    staffMovementIntervalTicks: 1,
    patientTravelTilesPerTick: 6,
    startingCash: 90,
    startingSatisfaction: 95,
    maximumPlayableLevel: 1,
    initialRooms: [
      {
        id: "room.instance.founder_desk",
        roomDefinitionId: "room.front_desk",
        x: 9,
        y: 6,
        orientation: 0,
        // This north door connects future rooms. The renderer gives the
        // founder room a separate south-facing exterior entrance.
        doorSide: "north",
        upgradeLevel: 1,
      },
    ],
    roomDefinitions: [
      {
        id: "room.front_desk",
        displayName: "Front Desk",
        kind: "room",
        unlockFacilityLevel: 0,
        width: 5,
        height: 4,
        defaultDoorSide: "north",
        constructionCost: 0,
        upkeepPerExpenseInterval: 10,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        maximumInstances: 1,
        maximumUpgradeLevel: 1,
        upgradeCosts: [],
        upkeepPerUpgradeLevel: 0,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 0,
        requiredRoomDefinitionIds: [],
        capabilityIds: [],
      },
      {
        id: "room.hallway",
        displayName: "Hallway",
        kind: "hallway",
        unlockFacilityLevel: 0,
        width: 1,
        height: 1,
        defaultDoorSide: null,
        constructionCost: 30,
        upkeepPerExpenseInterval: 0,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        maximumInstances: null,
        maximumUpgradeLevel: 1,
        upgradeCosts: [],
        upkeepPerUpgradeLevel: 0,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 0,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.walkable_hallway"],
      },
      {
        id: "room.examination",
        displayName: "Examination Room",
        kind: "room",
        unlockFacilityLevel: 0,
        width: 3,
        height: 2,
        defaultDoorSide: "south",
        constructionCost: 130,
        upkeepPerExpenseInterval: 12,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 2,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [90, 140, 210, 300],
        upkeepPerUpgradeLevel: 1,
        workloadLimitContributionPerUpgradeLevel: 1,
        serviceDurationReductionPercentPerUpgradeLevel: 5,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: [
          "capability.examination",
          "capability.synthetic.in_house_analysis",
        ],
      },
      {
        id: "room.bathroom",
        displayName: "Bathroom",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 2,
        height: 2,
        defaultDoorSide: "south",
        constructionCost: 180,
        upkeepPerExpenseInterval: 8,
        satisfactionOnBuild: 2,
        workloadLimitContribution: 0,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [70, 110, 170, 250],
        upkeepPerUpgradeLevel: 1,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 0,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.patient_bathroom"],
      },
      {
        id: "room.waiting",
        displayName: "Waiting Room",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 4,
        height: 3,
        defaultDoorSide: "south",
        constructionCost: 280,
        upkeepPerExpenseInterval: 14,
        satisfactionOnBuild: 2,
        workloadLimitContribution: 2,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [110, 170, 250, 360],
        upkeepPerUpgradeLevel: 1,
        workloadLimitContributionPerUpgradeLevel: 1,
        serviceDurationReductionPercentPerUpgradeLevel: 0,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.waiting_seats"],
      },
      {
        id: "room.xray",
        displayName: "X-ray Room",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 3,
        height: 3,
        defaultDoorSide: "south",
        constructionCost: 600,
        upkeepPerExpenseInterval: 28,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [190, 280, 400, 560],
        upkeepPerUpgradeLevel: 2,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 8,
        requiredRoomDefinitionIds: ["room.imaging_control"],
        capabilityIds: ["capability.xray_machine"],
      },
      {
        id: "room.imaging_control",
        displayName: "Imaging Control Room",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 2,
        height: 2,
        defaultDoorSide: "south",
        constructionCost: 350,
        upkeepPerExpenseInterval: 18,
        satisfactionOnBuild: 0,
        workloadLimitContribution: 0,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [90, 140, 210, 300],
        upkeepPerUpgradeLevel: 1,
        workloadLimitContributionPerUpgradeLevel: 0,
        serviceDurationReductionPercentPerUpgradeLevel: 5,
        requiredRoomDefinitionIds: ["room.examination"],
        capabilityIds: ["capability.imaging_control"],
      },
      {
        id: "room.minor_procedure",
        displayName: "Minor-Procedure Room",
        kind: "room",
        unlockFacilityLevel: 1,
        width: 3,
        height: 3,
        defaultDoorSide: "south",
        constructionCost: 650,
        upkeepPerExpenseInterval: 30,
        satisfactionOnBuild: 1,
        workloadLimitContribution: 1,
        maximumInstances: null,
        maximumUpgradeLevel: 5,
        upgradeCosts: [220, 330, 480, 680],
        upkeepPerUpgradeLevel: 2,
        workloadLimitContributionPerUpgradeLevel: 1,
        serviceDurationReductionPercentPerUpgradeLevel: 5,
        requiredRoomDefinitionIds: ["room.examination"],
        capabilityIds: ["capability.minor_procedure"],
      },
    ],
    staffRoleDefinitions: [
      {
        id: "staff.receptionist",
        displayName: "Receptionist",
        unlockFacilityLevel: 1,
        hiringCost: 180,
        salaryPerExpenseInterval: 18,
        minimumSalaryPerExpenseInterval: 14,
        maximumSalaryPerExpenseInterval: 30,
        salaryAdjustmentStep: 2,
        moralePerSalaryStep: 5,
        baseMorale: 75,
        maximumEmployees: 1,
        maximumTrainingLevel: 5,
        workloadLimitContribution: 1,
        requiredRoomDefinitionIds: ["room.front_desk"],
        capabilityIds: ["capability.staff.reception"],
      },
      {
        id: "staff.imaging_technician",
        displayName: "Imaging Technician",
        unlockFacilityLevel: 1,
        hiringCost: 300,
        salaryPerExpenseInterval: 26,
        minimumSalaryPerExpenseInterval: 20,
        maximumSalaryPerExpenseInterval: 42,
        salaryAdjustmentStep: 2,
        moralePerSalaryStep: 5,
        baseMorale: 75,
        maximumEmployees: 1,
        maximumTrainingLevel: 5,
        workloadLimitContribution: 0,
        requiredRoomDefinitionIds: ["room.xray", "room.imaging_control"],
        capabilityIds: ["capability.staff.imaging_technician"],
      },
    ],
    stageDefinitions: [
      {
        level: 0,
        displayName: "Level 0 - Founder Desk Clinic",
        minimumClinicalXp: 10,
        minimumCompletedEncounters: 0,
        satisfactionMustBeGreaterThan: 90,
        requiredRoomDefinitionIds: ["room.examination"],
        requiredStaffRoleIds: [],
        nextFacilityLevel: 1,
      },
      {
        level: 1,
        displayName: "Level 1 - First Clinic",
        minimumClinicalXp: 60,
        minimumCompletedEncounters: 0,
        satisfactionMustBeGreaterThan: 90,
        requiredRoomDefinitionIds: [
          "room.xray",
          "room.imaging_control",
          "room.minor_procedure",
        ],
        requiredStaffRoleIds: ["staff.imaging_technician"],
        nextFacilityLevel: null,
      },
    ],
    tutorialRequiredRoomDefinitionId: "room.examination",
    tutorialMinimumOperatingBuffer: 0,
  },
  workload: {
    baseRoutineLimit: 2,
    criticalReservedSlots: 1,
  },
  clock: {
    facilityHoursPerTick: 1,
    realMillisecondsPerFacilityHour: 30_000,
    dayStartHour: 8,
    dayEndHour: 18,
  },
  patientPatience: {
    routineDurationTicks: 16,
    warningAtRemainingTicks: [8, 4, 0],
    // Early warning is informational; sustained and final delays add mild,
    // one-time facility-satisfaction pressure.
    satisfactionPenaltyAtWarningTicks: [4, 0],
    satisfactionPenaltyPerWarning: 1,
    leftBeforeSeenSatisfactionPenalty: 2,
  },
  arrivals: {
    levelZeroRecoveryIntervalTicks: 2,
    levelOneRoutineIntervalTicks: 2,
  },
  economy: {
    expenseIntervalTicks: 10,
  },
  emergencyGlp1: {
    cashEligibilityThreshold: 200,
    cooldownTicks: 1,
    dailyUseCap: 8,
    fullPayment: 20,
    reducedPayment: 10,
    fullPaymentUseLimit: 5,
    sarcasmStartsAtUse: 5,
    sarcasmLines: [
      "Your commitment to comprehensive metabolic care has been noted.",
      "Another individualized 90-second consultation completed.",
      "Prior authorization remains someone elses problem.",
      "At this point, this is less of a safety net and more of a business model.",
      "This was supposed to be an emergency measure.",
      "One more visit and we have to call this a service line.",
      "The safety net has developed a revenue forecast.",
      "Your surgical clinic has developed a suspiciously scalable side hustle.",
      "Continuity of care is limited. Continuity of revenue is excellent.",
      "The cash balance has improved. The clinics identity is less certain.",
      "The emergency button would like to discuss its promotion.",
      "The founder has discovered recurring revenue.",
      "This is becoming less of a contingency plan and more of a lifestyle.",
      "Even the algorithm has standards.",
    ],
  },
  development: {
    fastForwardTickCount: 10,
    addMoneyAmount: 100,
  },
  learning: {
    parameterSetId: "learning.prototype.fsrs6.v1",
    requestedRetention: 0.9,
    maximumIntervalDays: 36_500,
    minimumAgainDelayMinutes: 30,
    enableFuzz: false,
  },
  clinicalSettlement: {
    patientRewardTiers: [
      {
        id: "reward.tutorial",
        completionRevenue: 45,
      },
      {
        id: "reward.clinic_basic",
        completionRevenue: 75,
      },
      {
        id: "reward.referral",
        completionRevenue: 60,
      },
    ],
    maximumQualityRevenueBonus: 15,
    maximumIncorrectFinancialConsequence: 5,
    clinicalXpPerCorrectFirstAnswer: 5,
    // Correctness affects a short-lived daily confidence modifier in the
    // domain. It does not permanently ratchet facility satisfaction.
    maximumCorrectSatisfactionBonus: 0,
    maximumIncorrectSatisfactionConsequence: 0,
    patientSatisfactionDeltaMinimum: 0,
    patientSatisfactionDeltaMaximum: 0,
  },
  services: [
    {
      id: "service.synthetic.analysis",
      displayName: "Synthetic Analysis",
      routes: [
        {
          id: "route.synthetic.in_house",
          displayName: "In-house synthetic analysis",
          durationTicks: 1,
          requiredCapabilityId: "capability.synthetic.in_house_analysis",
          requiredCapabilityIds: [],
          preference: 0,
        },
        {
          id: "route.synthetic.outsourced",
          displayName: "Outsourced synthetic analysis",
          // The first interface tutorial should demonstrate a pending result
          // without making a new player wait 90 real seconds.
          durationTicks: 1,
          requiredCapabilityId: null,
          requiredCapabilityIds: [],
          preference: 1,
        },
      ],
    },
    {
      id: "service.xray",
      displayName: "X-ray",
      routes: [
        {
          id: "route.xray.in_house",
          displayName: "In-house X-ray",
          durationTicks: 2,
          satisfactionOnResult: 1,
          requiredCapabilityId: "capability.xray_machine",
          requiredCapabilityIds: [
            "capability.imaging_control",
            "capability.staff.imaging_technician",
          ],
          preference: 0,
          patientTravel: {
            originRoomDefinitionId: "room.examination",
            destinationRoomDefinitionId: "room.xray",
            roundTrip: true,
          },
        },
        {
          id: "route.xray.outsourced",
          displayName: "Outsourced X-ray",
          durationTicks: 6,
          requiredCapabilityId: null,
          requiredCapabilityIds: [],
          preference: 1,
        },
      ],
    },
    {
      id: "service.basic_labs",
      displayName: "Basic laboratory testing",
      routes: [
        {
          id: "route.basic_labs.outsourced",
          displayName: "Off-site basic laboratory testing",
          durationTicks: 4,
          requiredCapabilityId: null,
          requiredCapabilityIds: [],
          preference: 1,
        },
      ],
    },
  ],
});

export const EXAMINATION_ROOM_DEFINITION_ID = "room.examination";
export const LEVEL_ONE_ROOM_DEFINITION_IDS = [
  "room.bathroom",
  "room.waiting",
  "room.xray",
  "room.imaging_control",
  "room.minor_procedure",
] as const;
export const RECEPTIONIST_ROLE_ID = "staff.receptionist";
export const IMAGING_TECHNICIAN_ROLE_ID = "staff.imaging_technician";
