// Replay the frozen prepaint layout through the actual native renderer.
// This produces stand-in evidence without replacing the painted proof exports.
import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createCanvas,loadImage}from'@napi-rs/canvas';import{loadNativeEngine}from'../../proof/native-engine.mjs';import{roomSegments}from'../../proof/geometry.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),proof=path.join(root,'proof'),layout=JSON.parse(fs.readFileSync(path.join(here,'layout-prepaint.json'))),manifest=JSON.parse(fs.readFileSync(path.join(here,'manifest.json'))),room=structuredClone(layout.room),assets={},metadata={mode:'stand-in',assets:{}};room.tierLevel=1;room.records=room.records.filter(r=>!r.presentIn||r.presentIn.includes(1));
for(const p of layout.pieces){const input=manifest.assets.find(a=>a.id===p.id),im=await loadImage(path.join(root,input.file)),c=createCanvas(im.width,im.height),g=c.getContext('2d');g.drawImage(im,0,0);const pix=g.getImageData(0,0,c.width,c.height).data;let bottom=-1,top=c.height;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(pix[(y*c.width+x)*4+3]>=160){bottom=y;top=Math.min(top,y);}const id='l1-'+p.id,anchor=p.center?[c.width/2,c.height/2]:p.top?[c.width/2,top]:[c.width/2,bottom+1];assets['design:fo:'+id]={src:path.relative(proof,path.join(root,input.file)).replaceAll('\\','/'),preparedId:id,size:p.canvas};metadata.assets[id]={canvas:p.canvas,canvasAnchor:anchor,anchorKind:p.center?'walkable-rug':p.top?'wall':'floor',calibratedPoints:input.sourcePoints??{},outputOpaqueBounds:{left:8,top,right:c.width-9,bottom,width:c.width-16}};
if(input.sourcePoints?.seat){const front=createCanvas(c.width,c.height),fg=front.getContext('2d');for(const r of input.sourcePoints.frontRegions){fg.save();fg.beginPath();fg.rect(...r);fg.clip();fg.drawImage(c,0,0);fg.restore();}const file=path.join(here,p.id+'-front.png');fs.writeFileSync(file,front.toBuffer('image/png'));assets['design:fo:'+id+'-front']={src:path.relative(proof,file).replaceAll('\\','/'),preparedId:id+'-front',size:p.canvas};metadata.assets[id+'-front']={...metadata.assets[id]};}}
const tier={level:1,room,navigation:layout.navigation,presentation:layout.presentation,bases:[]},data=JSON.parse(fs.readFileSync(path.join(proof,'data.json')));data.founderPresentation=layout.presentation;data.previewBaseClearances=[];const{engine,warnings}=await loadNativeEngine({data,definitions:{DESIGN_ASSETS:assets,DESIGN_ROOMS:[room],DESIGN_NAVIGATION:{[room.definitionId]:layout.navigation},PREPARED_METADATA:metadata,ASSET_CONTRACT:{},DESIGN_TIERS:[tier]}});
for(const[id,extra]of[['seated',{}],['empty',{actors:false}],['all-doors',{doors:new Set(roomSegments(room)),routes:true,grid:true}]]){Object.assign(engine.state,{actors:true,visitors:true,founders:true,doors:new Set(),backed:new Set(),routes:false,grid:false},extra);const c=createCanvas(1,1),result=await engine.render(c,true);if(result.bad)throw Error(JSON.stringify(result));fs.writeFileSync(path.join(here,'layout-'+id+'.png'),c.toBuffer('image/png'));}
if(warnings.length)throw Error(warnings.join('; '));console.log('FROZEN STAND-IN REPLAY PASS: 3 original 3x3 layout states; painted proof unchanged.');
