import { buildFamily,type FamilySpec } from "./family-builder"; import { variants } from "./spec-utils"; import { SOURCES } from "./source-catalog";
const S="claim.burn.superficial-partial-depth",D="claim.burn.deeper-depth-contrast",R="claim.burn.referral-boundary",H="claim.burn.deep-hand-consult",A="claim.burn.inhalation-emergency";
const depth=variants([
{slug:"scald-blister",complaint:"Painful scald",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a small kitchen scald that is moist, bright red, blanching, blistered, and very painful. No special area, inhalation injury, circumferential injury, or major comorbidity is involved.",stem:"Which burn depth best matches the wound?",correct:["Superficial partial-thickness burn","Moist red blanching blisters with marked pain fit superficial partial thickness."],wrong:[["Epidermal (superficial) burn","An epidermal burn is red and painful but does not form blisters."],["Deep partial-thickness dermal burn","Deeper injury is generally paler, drier, less blanching, and less sensate."],["Full-thickness (third-degree) burn","Full thickness is leathery or dry and has markedly reduced sensation."]],explanation:"Classify the wound as superficial partial thickness while recognizing that depth can evolve and needs reassessment.",claims:[S,D]},
{slug:"contact-moist",complaint:"Blistered arm burn",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a limited forearm contact burn. The surface is wet, pink-red, briskly blanching, blistered, and exquisitely tender.",stem:"What is the most likely depth?",correct:["Superficial partial-thickness burn","The moist, blanching, highly painful blistered pattern is characteristic."],wrong:[["Epidermal (superficial) injury","Blister formation extends beyond epidermal-only injury."],["Deep partial-thickness dermal injury","The wound is not pale, dry, poorly blanching, or relatively insensate."],["Full-thickness injury","The preserved blanching and sensation argue against full thickness."]],explanation:"Use appearance, blanching, moisture, blistering, and sensation together rather than relying on one feature.",claims:[S,D]},
{slug:"pale-less-sensate",complaint:"Pale hand burn",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a thermal hand injury that appears pale and mottled, is relatively dry, blanches slowly, and is less sensitive than adjacent skin.",stem:"Which burn depth best fits these findings?",correct:["Deep partial-thickness burn","Pallor, dryness, impaired blanching, and reduced sensation suggest deeper dermal injury."],wrong:[["Superficial epidermal burn","Superficial burns are red, dry, painful, and blanching."],["Superficial partial-thickness burn","A superficial partial burn is typically moist, red, briskly blanching, and very painful."],["Full-thickness burn","The wound is less sensate but not described as leathery, nonblanching, or completely insensate."]],explanation:"This pattern is deeper than superficial partial thickness and also involves the hand, supporting burn-center consultation.",claims:[D,R]},
{slug:"leathery-insensate",complaint:"Dry painless burn",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a sharply demarcated thermal wound that is dry, leathery, nonblanching, and insensate centrally.",stem:"Which depth best fits the central wound?",correct:["Full-thickness burn","A dry leathery nonblanching and insensate wound is full thickness."],wrong:[["Superficial epidermal burn","Superficial injury remains painful and blanching."],["Superficial partial-thickness burn","Superficial partial-thickness burns are moist, blistered, blanching, and painful."],["Deep partial-thickness burn","The fully dry, leathery, nonblanching, insensate center indicates full-thickness injury."]],explanation:"Recognize full-thickness injury and move to burn-center consultation or transfer planning based on the whole patient.",claims:[D,R]}]);
const referral=variants([
{slug:"small-simple-scald",complaint:"Small forearm scald",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a small superficial partial-thickness forearm scald, controlled pain, normal circulation, limited to the forearm, with no hand, face, foot, genital, joint, or inhalation concern, and reliable follow-up.",stem:"Which disposition best fits this limited injury?",correct:["Burn consult, then local care","A small uncomplicated superficial partial burn may remain local after consultation; transfer is not automatic."],wrong:[["Immediate burn-center transfer","Not every small superficial partial burn requires transfer."],["Emergency airway intervention","There is no inhalation or airway concern."],["Urgent operative debridement","The described depth and stability do not mandate emergency surgery."]],explanation:"Use depth, extent, location, mechanism, pain, comorbidity, and resources; consultation can support local follow-up without automatic transfer.",claims:[R]},
{slug:"hand-deep-burn",complaint:"Deep hand burn",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a deep partial-thickness burn across the hand and fingers, reduced sensation, and impaired movement. Airway and hemodynamics are stable.",stem:"What is the appropriate next disposition?",correct:["Burn-center consultation for transfer planning","A deep burn involving the hand warrants specialist consultation and likely transfer planning."],wrong:[["Elective hand-clinic referral","The depth and functional involvement require burn expertise sooner than elective review."],["Local outpatient burn follow-up","Deep injury across the hand exceeds uncomplicated local follow-up."],["Hospital observation without burn consultation","Observation alone omits the needed burn-specialist coordination."]],explanation:"Contact the burn center; the receiving team and local resources determine transfer logistics.",claims:[R,H]},
{slug:"inhalation-concern",complaint:"Smoke exposure burn",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who returns after an enclosed-space fire with facial burns, soot around the mouth, hoarseness, and increasing work of breathing.",stem:"Which action has priority?",correct:["Activate EMS and burn team","Possible inhalation injury requires immediate emergency care and specialist coordination."],wrong:[["Routine clinic observation","Airway deterioration can be rapid."],["Delayed outpatient burn review","The inhalation concern is an emergency."],["Topical treatment then discharge","Skin treatment does not address the airway threat."]],explanation:"Do not delay stabilization and external emergency transfer for an inhalation concern.",claims:[R,A],acuity:"urgent"},
{slug:"difficult-pain",complaint:"Burn pain uncontrolled",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a partial-thickness torso burn and severe pain that remains uncontrolled despite appropriate initial analgesia. Airway and hemodynamics are stable.",stem:"Which disposition is appropriate?",correct:["Burn-center consultation","Poorly controlled pain is a reason for specialist consultation and transfer discussion."],wrong:[["Routine primary-care follow-up","Uncontrolled pain exceeds simple routine follow-up."],["Local care with unchanged analgesia","Persisting severe pain needs reassessment and specialist input."],["Delayed dermatology appointment","A delayed skin appointment does not address current burn pain."]],explanation:"Consult a burn center and use the receiving service and local resources to decide transfer.",claims:[R]}]);
const spec:FamilySpec={slug:"burn",label:"Burn depth and referral",claims:[{id:S,statement:"A superficial partial-thickness burn is typically moist, red, blanching, blistered, and very painful; depth can evolve and requires reassessment.",sourceIds:[SOURCES.burnAba.id,SOURCES.burnAha.id],category:"evaluation",limitation:"Individual findings are interpreted together rather than as absolute rules.",population:"Adults with thermal burns."},{id:D,statement:"Deep partial-thickness burns tend to be paler or drier, less blanching, and less sensate; full-thickness burns are dry or leathery, nonblanching, and insensate.",sourceIds:[SOURCES.burnAba.id],category:"evaluation",limitation:"Burn depth can be mixed or evolve.",population:"Adults with thermal burns."},{id:R,statement:"Burn-center consultation or transfer depends on depth, extent, special location, mechanism, inhalation concern, comorbidity, pain, local resources, and associated trauma; consultation does not make every small burn an automatic transfer.",sourceIds:[SOURCES.burnAba.id,SOURCES.burnAha.id],category:"disposition",limitation:"No unsourced numeric threshold or general treatment algorithm is taught.",population:"Adults with burns evaluated in a general clinic or emergency handoff."},{id:H,statement:"A deep partial-thickness burn involving the hand warrants burn-center consultation for transfer planning.",sourceIds:[SOURCES.burnAba.id],category:"disposition",limitation:"Consultation and transfer are distinct decisions shaped by the receiving center and local resources.",population:"Adults with deep partial-thickness hand burns."},{id:A,statement:"Facial burns with soot, hoarseness, or increasing work of breathing require emergency stabilization and burn-center coordination for possible inhalation injury.",sourceIds:[SOURCES.burnAba.id,SOURCES.burnAha.id],category:"safety_boundary",limitation:"Airway stabilization must not wait for routine outpatient care.",population:"Adults with burns and possible inhalation injury."}],sources:[SOURCES.burnAba,SOURCES.burnAha],concepts:[{id:"concept.burn.superficial-partial-thickness-recognition",displayName:"Recognize burn depth",learningObjective:"Distinguish superficial partial-thickness from deeper thermal burns using wound findings.",stage:0,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[S,D],variants:depth},{id:"concept.burn.referral-consultation-selection",displayName:"Choose burn consultation or transfer",learningObjective:"Use burn and patient factors to select outpatient reassessment, consultation, or emergency transfer.",stage:0,educationalTier:0,conceptType:"disposition",evidenceClaimIds:[R,H,A],variants:referral}]};
const f=buildFamily(spec); export const BURN=f; export const BURN_AUTHORING_CONCEPTS=f.authoringConcepts,BURN_TESTED_CONCEPTS=f.testedConcepts,BURN_QUESTIONS=f.questions,BURN_CASES=f.cases,BURN_CLAIMS=f.claims,BURN_SOURCES=f.sources,BURN_CASE_REVIEWS=f.caseReviews,BURN_TIMING_ENTRIES=f.timingEntries,BURN_SERVICE_CONTRACTS=f.serviceContracts;









