import { buildFamily,type FamilySpec } from "./family-builder"; import { variants } from "./spec-utils"; import { SOURCES } from "./source-catalog";
const R="claim.dfi.clinical-recognition",E="claim.dfi.initial-escalation",N="claim.dfu.no-antibiotics-uninfected";
const infected=variants([
{slug:"erythema-purulence",complaint:"Red draining foot",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with diabetes and a plantar ulcer now surrounded by warmth, erythema, tenderness, swelling, and purulent drainage. Vital signs are stable and there is no gangrene or severe ischemia.",stem:"How should the ulcer be classified at this visit?",correct:["Infected diabetic foot ulcer","Multiple local inflammatory findings and purulence establish clinical infection."],wrong:[["Uninfected colonized ulcer","Colonization alone lacks the inflammatory findings present here."],["Uninfected neuropathic ulcer","An uninfected neuropathic ulcer lacks the inflammatory changes and purulence present here."],["Chronic venous ulcer","The plantar diabetic ulcer with local infection findings is not defined by venous disease."]],explanation:"Diagnose diabetic foot soft-tissue infection clinically from compatible inflammatory findings, then arrange appropriate external multidisciplinary care.",claims:[R]},
{slug:"cellulitis-spread",complaint:"Foot redness spreading",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with diabetes, a toe ulcer, expanding erythema and warmth across the forefoot, swelling, and new pain. There is no hypotension, gangrene, fluctuance, or compartment concern.",stem:"Which interpretation best fits the examination?",correct:["Diabetic foot infection","Spreading local inflammation around an ulcer supports clinical infection."],wrong:[["Simple bacterial colonization","Colonization does not explain spreading erythema, warmth, swelling, and pain."],["Stable callus","A callus does not produce the current inflammatory change."],["Dependent edema alone","Edema alone does not account for the focal ulcer-associated inflammation."]],explanation:"The diagnosis is clinical; a culture result is not required before recognizing infection.",claims:[R]},
{slug:"systemic-illness",complaint:"Fever with foot wound",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with diabetes, a foot ulcer, fever, tachycardia, spreading erythema, and malaise. The patient appears systemically ill.",stem:"How should the current foot problem be classified?",correct:["Severe diabetic foot infection","Systemic inflammatory illness with local infection findings indicates severe infection."],wrong:[["Uninfected diabetic foot ulcer","Systemic and local inflammatory findings establish infection."],["Mild localized foot infection","Systemic illness makes a mild classification inappropriate."],["Neuropathic ulcer without infection","Neuropathy does not explain fever, tachycardia, and spreading erythema."]],explanation:"Recognize the infection clinically and escalate externally; urgent hospital assessment follows recognition.",claims:[R,E],acuity:"urgent",prototypeVitalSigns:{heartRateBpm:116,systolicBloodPressureMmHg:106,diastolicBloodPressureMmHg:66,temperatureF:102.1,oxygenSaturationPercent:96}},
{slug:"gangrene-abscess",complaint:"Dark toe and swelling",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with diabetes, an ulcer, black tissue at a toe, rapidly increasing swelling, severe pain, and fluctuance extending into the plantar foot.",stem:"Which classification best captures the current problem?",correct:["Infected ulcer with gangrene","Gangrene and suspected deep abscess are urgent surgical danger features."],wrong:[["Uninfected ischemic ulcer","The fluctuance and rapidly increasing inflammatory findings support infection."],["Mild superficial foot infection","Gangrene and suspected deep abscess exceed a mild superficial process."],["Stable neuropathic ulcer","The acute pain, swelling, gangrene, and fluctuance are not stable neuropathy."]],explanation:"Gangrene or suspected deep abscess crosses the urgent external surgical boundary.",claims:[E],acuity:"urgent",prototypeVitalSigns:{heartRateBpm:110,systolicBloodPressureMmHg:112,diastolicBloodPressureMmHg:70,temperatureF:99.5,oxygenSaturationPercent:97}}]);
const noabx=variants([
{slug:"clean-neuropathic-ulcer",complaint:"Foot ulcer check",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with diabetes and a shallow plantar ulcer. It has a clean base and no erythema, warmth, swelling, tenderness, purulence, fever, or systemic illness.",stem:"Should antibiotics be started solely to prevent infection?",correct:["No antibiotics; external foot care","Antibiotics do not prevent infection or accelerate healing in a clinically uninfected ulcer."],wrong:[["Yes; start systemic antibiotics","There are no clinical infection findings to justify antibiotics."],["Yes; apply topical antibiotics","Topical antibiotics are not indicated solely for prevention in an uninfected ulcer."],["Use antibiotics until specialty review","Antibiotics remain unsupported without clinical infection."]],explanation:"Withhold prophylactic antibiotics while arranging external diabetic-foot care; the wound also needs appropriate multidisciplinary assessment.",claims:[N]},
{slug:"colonized-no-inflammation",complaint:"Positive wound swab",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with diabetes and a chronic foot ulcer. A surface swab reports bacteria, but examination shows no purulence, erythema, warmth, swelling, pain, fever, or systemic change.",stem:"What is the best antibiotic decision?",correct:["Do not treat colonization","A positive surface result without clinical inflammation does not establish infection."],wrong:[["Treat the cultured organism systemically","Culture positivity alone does not define clinical infection."],["Use dual antibiotics prophylactically","Broader prophylaxis remains unsupported in an uninfected ulcer."],["Use topical antibiotics until review","Topical prophylaxis is not supported without clinical infection."]],explanation:"Base infection diagnosis on clinical findings rather than colonization alone.",claims:[R,N]},
{slug:"stable-dry-ulcer",complaint:"Dry toe ulcer",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with diabetes and a small dry toe ulcer found during self-inspection. There is no drainage, surrounding inflammation, pain change, fever, or systemic symptom.",stem:"Which initial clinic plan is appropriate?",correct:["Withhold antibiotics; refer","An uninfected ulcer needs foot-care assessment, not prophylactic antibiotics."],wrong:[["Start oral antibiotics now","No clinical infection is present."],["Apply a topical antibiotic course","Local antibiotics are not indicated to speed healing of an uninfected ulcer."],["Start a short preventive oral course","Preventive systemic antibiotics are unsupported without infection."]],explanation:"Antibiotic stewardship accompanies prompt external multidisciplinary foot assessment.",claims:[N]},
{slug:"healing-ulcer-request",complaint:"Asking for antibiotics",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with diabetes and a slowly healing plantar ulcer under external foot-team care. Today it has no erythema, warmth, swelling, tenderness, purulence, or systemic illness, but the patient asks whether antibiotics would speed closure.",stem:"What is the best response?",correct:["Do not add antibiotics","Antibiotics should not be used solely to promote healing of an uninfected ulcer."],wrong:[["Add antibiotics to speed closure","Antibiotics do not serve as a healing accelerator without infection."],["Add topical antibiotics for prevention","Preventive topical antibiotics are not supported here."],["Use oral antibiotics until closure","Healing time alone is not an indication for antibiotics."]],explanation:"Do not use systemic or local antibiotics solely to promote healing when clinical infection is absent.",claims:[N]}]);
const spec:FamilySpec={slug:"diabetic-foot",label:"Diabetic foot assessment",claims:[{id:R,statement:"Diabetes-related foot soft-tissue infection is diagnosed clinically from local or systemic inflammatory findings; colonization alone does not establish infection.",sourceIds:[SOURCES.dfi.id],category:"evaluation",limitation:"Single-current-guideline limitation.",population:"Adults with diabetes and a foot wound."},{id:E,statement:"Severe infection or moderate infection with important morbidity warrants hospital consideration; gangrene, deep abscess, necrotizing infection, compartment syndrome, or severe ischemia warrants urgent surgical consultation.",sourceIds:[SOURCES.dfi.id],category:"disposition",limitation:"The clinic objective stops at recognition and external escalation.",population:"Adults with diabetes-related foot infection and danger features."},{id:N,statement:"Systemic or local antibiotics should not be used for a clinically uninfected diabetic foot ulcer solely to prevent infection or promote healing.",sourceIds:[SOURCES.dfi.id],category:"management",limitation:"External multidisciplinary foot care remains required; no onsite wound service is implied.",population:"Adults with a clinically uninfected diabetes-related foot ulcer."}],sources:[SOURCES.dfi],concepts:[{id:"concept.diabetic-foot-infection.clinical-recognition",displayName:"Recognize diabetic foot infection",learningObjective:"Distinguish clinical infection from colonization and escalate danger features externally.",stage:1,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[R,E],variants:infected},{id:"concept.diabetic-foot-ulcer.no-antibiotics-without-infection",displayName:"Avoid antibiotics for uninfected diabetic foot ulcer",learningObjective:"Withhold antibiotics used solely for prevention or healing when clinical infection is absent.",stage:1,educationalTier:0,conceptType:"management",evidenceClaimIds:[N],variants:noabx}]};
const f=buildFamily(spec); export const DIABETIC_FOOT=f; export const DIABETIC_FOOT_AUTHORING_CONCEPTS=f.authoringConcepts,DIABETIC_FOOT_TESTED_CONCEPTS=f.testedConcepts,DIABETIC_FOOT_QUESTIONS=f.questions,DIABETIC_FOOT_CASES=f.cases,DIABETIC_FOOT_CLAIMS=f.claims,DIABETIC_FOOT_SOURCES=f.sources,DIABETIC_FOOT_CASE_REVIEWS=f.caseReviews,DIABETIC_FOOT_TIMING_ENTRIES=f.timingEntries,DIABETIC_FOOT_SERVICE_CONTRACTS=f.serviceContracts;









