import { buildFamily,type FamilySpec } from "./family-builder"; import { variants } from "./spec-utils"; import { SOURCES } from "./source-catalog";
const E="claim.gcs.eye-mapping",V="claim.gcs.verbal-mapping",M="claim.gcs.motor-mapping",T="claim.gcs.complete-total",N="claim.gcs.verbal-nt";
const total=variants([
{slug:"e4v5m6",complaint:"Review trauma note",presentation:"{patientName} is a {patientAge}-year-old {patientSex} at stable post-hospital follow-up. The emergency note records eyes opening spontaneously, orientation to person/place/time, and obedience to commands. All components were testable.",stem:"What GCS components and total should be documented from that assessment?",correct:["E4 V5 M6 = 15","Spontaneous eyes, oriented verbal response, and command following score 4, 5, and 6."],wrong:[["E3 V5 M6 = 14","Eye response was spontaneous rather than to sound."],["E4 V4 M6 = 14","The patient was oriented rather than confused."],["E4 V5 M5 = 14","The patient obeyed commands rather than only localizing."]],explanation:"Report the components and sum them because all three were testable: E4 + V5 + M6 = 15.",claims:[E,V,M,T]},
{slug:"e3v4m6",complaint:"Calculate prior GCS",presentation:"{patientName} is a {patientAge}-year-old {patientSex} reviewing a prior emergency assessment. Eyes opened to spoken sound, conversation was confused, and motor response obeyed commands. All components were testable.",stem:"Which documented score is correct?",correct:["E3 V4 M6 = 13","Eyes to sound, confused speech, and command following score 3, 4, and 6."],wrong:[["E4 V4 M6 = 14","Eyes did not open spontaneously."],["E3 V5 M6 = 14","The verbal response was confused, not oriented."],["E3 V4 M5 = 12","The motor response obeyed commands, not localization alone."]],explanation:"The component scores are E3, V4, and M6, producing a valid total of 13.",claims:[E,V,M,T]},
{slug:"e2v3m5",complaint:"Interpret response scores",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who returns for stable follow-up after an emergency visit. The original assessment recorded eye opening only to pressure, recognizable single words without conversation, and localization toward a painful stimulus. All components were testable.",stem:"What is the correct component report and total?",correct:["E2 V3 M5 = 10","Eyes to pressure, words, and localization score 2, 3, and 5."],wrong:[["E2 V2 M5 = 9","Recognizable words score above sounds alone."],["E3 V3 M5 = 11","Eyes opened to pressure, not sound."],["E2 V3 M4 = 9","Localization scores above normal flexion withdrawal."]],explanation:"Preserve the observed responses as E2 V3 M5 and sum them to 10.",claims:[E,V,M,T]},
{slug:"e1v2m4",complaint:"Check GCS arithmetic",presentation:"{patientName} is a {patientAge}-year-old {patientSex} reviewing a completed emergency record. There was no eye opening, only incomprehensible sounds, and normal flexion withdrawal from pressure. All components were testable.",stem:"Which GCS report matches the observations?",correct:["E1 V2 M4 = 7","No eye response, sounds, and normal flexion score 1, 2, and 4."],wrong:[["E1 V3 M4 = 8","The response was sounds rather than recognizable words."],["E2 V2 M4 = 8","There was no eye opening to pressure."],["E1 V2 M3 = 6","Normal flexion differs from abnormal flexion."]],explanation:"The component mapping is E1 V2 M4, giving a total of 7 because every component was testable.",claims:[E,V,M,T]}]);
const nt=variants([
{slug:"intubated",complaint:"Document intubated GCS",presentation:"{patientName} is a {patientAge}-year-old {patientSex} reviewing an ICU note: eyes opened to sound and motor response localized, but an endotracheal tube prevented verbal testing at that time.",stem:"How should that GCS assessment be documented?",correct:["E3 V-NT (intubated) M5; no total","The verbal component was genuinely untestable and should not be replaced with a numeric score."],wrong:[["E3 V1 (intubated) M5 = 9","A tube preventing testing is not the same as a tested absent response."],["E3 V0 (intubated) M5 = 8","Zero is not a GCS verbal score and creates a misleading total."],["E3 V-NT (intubated) M5; total = 8","Adding the two testable components creates a misleading total while verbal response is unavailable."]],explanation:"Record components, the interference, and no misleading total: E3 V-NT (intubated) M5.",claims:[E,M,N]},
{slug:"aphonia-swelling",complaint:"Verbal score question",presentation:"{patientName} is a {patientAge}-year-old {patientSex} reviewing an emergency note after severe oral swelling made phonation impossible. Eyes opened spontaneously and commands were obeyed, but the clinician documented that verbal response could not be tested reliably.",stem:"Which GCS documentation is appropriate?",correct:["E4 V-NT (phonation prevented) M6; no total","The reason for non-testability should accompany the component report."],wrong:[["E4 V1 (phonation prevented) M6 = 11","Inability to test speech is not a tested absent verbal response."],["E4 V0 (phonation prevented) M6 = 10","Zero is not a valid substitute for an untestable component."],["E4 V-NT (phonation prevented) M6; total = 10","Adding the two testable components creates a misleading total while verbal response is unavailable."]],explanation:"Use V-NT with the specific interference and retain the observed eye and motor components.",claims:[E,M,N]},
{slug:"language-barrier-resolved",complaint:"Review translated exam",presentation:"{patientName} is a {patientAge}-year-old {patientSex} reviewing a prior assessment. Before an interpreter arrived, verbal testing was not reliable because no shared language was available; eyes opened spontaneously and commands demonstrated nonverbally were obeyed.",stem:"How should the pre-interpreter assessment be recorded?",correct:["E4 V-NT (language barrier) M6; no total","The record should name the interference rather than invent a verbal score."],wrong:[["E4 V1 (language barrier) M6 = 11","A language barrier does not establish absent verbal response."],["E4 V3 (language barrier) M6 = 13","Recognizable words were not validly assessed."],["E4 V5 (language barrier) M6; total = 15","Orientation cannot be assumed before reliable communication."]],explanation:"Document the pre-interpreter verbal component as not testable and repeat the assessment once communication is possible.",claims:[E,M,N]},
{slug:"speaking-valve",complaint:"Tracheostomy GCS review",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a tracheostomy and a functioning speaking valve during assessment. Eyes opened spontaneously, the patient answered orientation questions reliably, and commands were obeyed; the verbal response was fully testable.",stem:"How should the verbal component be documented?",correct:["E4 V5 (speaking valve) M6 = 15","A tracheostomy does not make verbal response untestable when reliable speech is possible."],wrong:[["E4 V-NT (speaking valve) M6; no total","The verbal component was actually testable with the speaking valve."],["E4 V1 (speaking valve) M6 = 11","A tracheostomy is not an automatic score of one."],["E4 V0 (speaking valve) M6 = 10","Zero is not a valid verbal score."]],explanation:"Use the observed testable response; reserve V-NT for an actual interference.",claims:[E,V,M,T,N]}]);
const spec:FamilySpec={slug:"glasgow-coma-scale",label:"Glasgow Coma Scale",claims:[{id:E,statement:"Eye response scores are E4 spontaneous, E3 to sound, E2 to pressure, and E1 none.",sourceIds:[SOURCES.gcsAid.id],category:"evaluation",limitation:"Official source family; independent corroboration limited.",population:"Patients undergoing GCS assessment."},{id:V,statement:"Verbal response scores are V5 oriented, V4 confused, V3 words, V2 sounds, and V1 none when testable.",sourceIds:[SOURCES.gcsAid.id],category:"evaluation",limitation:"Official source family; independent corroboration limited.",population:"Patients with a testable verbal response."},{id:M,statement:"Motor response scores are M6 obeys commands, M5 localizes, M4 normal flexion, M3 abnormal flexion, M2 extension, and M1 none.",sourceIds:[SOURCES.gcsAid.id],category:"evaluation",limitation:"Official source family; independent corroboration limited.",population:"Patients undergoing GCS assessment."},{id:T,statement:"A GCS total is the sum of eye, verbal, and motor scores only when all three components are testable; components should remain visible.",sourceIds:[SOURCES.gcsFaq.id,SOURCES.gcsAid.id],category:"evaluation",limitation:"No severity band, prognosis, or treatment threshold is taught.",population:"Patients with all three GCS components testable."},{id:N,statement:"When an interference genuinely prevents verbal testing, document V-NT with the reason and do not substitute 1 or 0 or report a misleading total.",sourceIds:[SOURCES.gcsFaq.id,SOURCES.gcsAid.id],category:"safety_boundary",limitation:"A tracheostomy does not automatically make speech untestable.",population:"Patients with an actual interference to verbal-response testing."}],sources:[SOURCES.gcsFaq,SOURCES.gcsAid],concepts:[{id:"concept.gcs.complete-component-total",displayName:"Calculate a complete GCS total",learningObjective:"Map documented eye, verbal, and motor responses and sum only when all are testable.",stage:0,educationalTier:0,conceptType:"applied_science",evidenceClaimIds:[E,V,M,T],variants:total},{id:"concept.gcs.verbal-not-testable-documentation",displayName:"Document a non-testable GCS component",learningObjective:"Record V-NT with its reason and avoid a misleading numeric total.",stage:0,educationalTier:0,conceptType:"applied_science",evidenceClaimIds:[N],variants:nt}]};
const f=buildFamily(spec); export const GCS=f; export const GCS_AUTHORING_CONCEPTS=f.authoringConcepts,GCS_TESTED_CONCEPTS=f.testedConcepts,GCS_QUESTIONS=f.questions,GCS_CASES=f.cases,GCS_CLAIMS=f.claims,GCS_SOURCES=f.sources,GCS_CASE_REVIEWS=f.caseReviews,GCS_TIMING_ENTRIES=f.timingEntries,GCS_SERVICE_CONTRACTS=f.serviceContracts;










