import { buildFamily,type FamilySpec } from "./family-builder"; import { variants } from "./spec-utils"; import { SOURCES } from "./source-catalog";
const R="claim.hs.pattern-recognition",P="claim.hs.multimodal-planning",D="claim.hs.drainage-limitation";
const recognition=variants([
{slug:"axillary-recurrence",complaint:"Recurring armpit lumps",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with repeated painful axillary nodules over three years, intermittent drainage, paired openings, and rope-like scars between prior lesions.",stem:"Which diagnosis best unifies the pattern?",correct:["Hidradenitis suppurativa","Recurrent nodules, drainage tunnels, and scarring in an intertriginous site are typical."],wrong:[["Recurrent isolated furuncles","Independent furuncles do not explain chronic interconnected tunnels and scars."],["Allergic contact dermatitis","Dermatitis does not cause deep recurrent nodules and draining tunnels."],["Reactive lymphadenopathy","Nodes do not create cutaneous openings and tract-like scars."]],explanation:"The lesion type, axillary site, and relapsing course support hidradenitis suppurativa.",claims:[R]},
{slug:"inframammary-scars",complaint:"Painful fold sores",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with recurrent tender inframammary nodules that rupture, drain, and heal with bridging scars. Similar episodes have occurred for years.",stem:"What is the most likely diagnosis?",correct:["Hidradenitis suppurativa","The chronic relapsing intertriginous nodules and scars fit HS."],wrong:[["Simple acute abscess","One acute abscess does not explain years of recurrent lesions and bridging scars."],["Candidal intertrigo","Intertrigo is a superficial fold rash rather than deep nodules and tunnels."],["Inflammatory breast cancer","The episodic fold lesions and tract-like scarring are not that pattern."]],explanation:"Recognize HS from morphology, distribution, and recurrence rather than treating each episode as unrelated.",claims:[R],ageYears:[36,54],sexLabels:["Female"]},
{slug:"groin-tunnels",complaint:"Groin boils return",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with painful groin nodules recurring in the same areas, malodorous drainage, double-ended openings, and fibrotic scars. There is no perianal fluctuance.",stem:"Which condition best explains these findings?",correct:["Hidradenitis suppurativa","Recurrent intertriginous nodules with tunnels and scars are characteristic."],wrong:[["Pilonidal disease","Pilonidal disease centers in the natal cleft, not multiple groin sites."],["Perianal abscess","No focal perianal collection is described."],["Recurrent bacterial folliculitis","Superficial folliculitis does not usually create chronic tunnels and fibrotic scars."]],explanation:"The relapsing groin distribution and tunnel formation point to HS.",claims:[R]},
{slug:"multisite-relapse",complaint:"Lumps in skin folds",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with episodic painful nodules in both axillae and the groin, several prior drainage procedures, and persistent scars and draining tracts between flares.",stem:"Which diagnosis should replace the isolated-abscess framing?",correct:["Hidradenitis suppurativa","Multisite recurrence with tracts and scars is a chronic HS pattern."],wrong:[["Multiple unrelated abscesses","The stereotyped sites and chronic tracts indicate one relapsing disease."],["Acute bacterial cellulitis","Cellulitis does not explain years of nodules and sinus tracts."],["Epidermal inclusion cysts","Separate cysts are less consistent with bilateral intertriginous tunneling disease."]],explanation:"The full longitudinal pattern is necessary for recognition.",claims:[R]}]);
const planning=variants([
{slug:"repeat-drainage",complaint:"Another painful flare",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with established HS, repeated incision and drainage procedures, and persistent axillary tunnels that refill after temporary relief.",stem:"Which long-term plan is most appropriate?",correct:["Multidisciplinary HS referral","Chronic tunnel-forming disease needs longitudinal medical and procedural planning."],wrong:[["Repeat drainage for recurrent lesions","Drainage may relieve an acute collection but does not control chronic tunnels."],["Long-term antibiotic therapy alone","A universal indefinite antibiotic plan is not appropriate without specialist assessment."],["Immediate wide excision","Procedure selection depends on severity, site, goals, and expertise."]],explanation:"Use severity-based dermatology and surgical planning; acute drainage alone is not definitive chronic control.",claims:[P,D]},
{slug:"scarring-function",complaint:"Scars limit arm movement",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with recurrent intertriginous HS, thick bridging scars, and movement-related discomfort from scar contracture. No drainable acute collection is present today.",stem:"What is the best next step?",correct:["Combined dermatology-surgery review","Symptomatic scarring needs individualized multimodal assessment."],wrong:[["Offer another isolated drainage procedure","There is no acute collection, and drainage does not address chronic scarring."],["Treat only with pain medication","Analgesia alone does not address active disease and contracture."],["Observe without follow-up","Functional impairment merits specialist planning."]],explanation:"Refer for coordinated chronic-disease control and procedural assessment tailored to function.",claims:[P]},
{slug:"mild-recurrent-nodules",complaint:"Recurring tender nodules",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with recognized HS and intermittent nodules but no tunnels, extensive scarring, fever, or current abscess. The patient wants a prevention plan.",stem:"Which approach is appropriate?",correct:["Longitudinal dermatology management","Even limited recurrent disease benefits from diagnosis-specific preventive planning."],wrong:[["Schedule drainage for recurrent nodules","Not every HS nodule requires incision and drainage."],["Offer immediate excision","Limited disease does not mandate a single operation."],["Manage as unrelated infections","The relapsing HS diagnosis should guide care."]],explanation:"Severity-based longitudinal care applies even when a procedure is not currently indicated.",claims:[P,D]},
{slug:"acute-collection-plus-chronic",complaint:"Painful draining armpit",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with known tunnel-forming HS and a new fluctuant painful axillary collection, plus chronic scars and several draining openings. Vital signs are stable.",stem:"How should the care plan be framed?",correct:["Treat collection and arrange HS care","Acute relief and chronic disease control are separate needs."],wrong:[["Drain the acute collection without longitudinal referral","Drainage does not control the underlying tunnel-forming disease."],["Defer acute assessment until dermatology","The painful fluctuant collection still requires timely assessment."],["Choose definitive surgery without evaluation","Procedure extent requires specialist assessment and shared planning."]],explanation:"Address the acute collection while ensuring follow-up for chronic multimodal control.",claims:[P,D]}]);
const spec:FamilySpec={slug:"hidradenitis-suppurativa",label:"Hidradenitis suppurativa",pairing:{indices:[0,1],updates:["The longitudinal history confirms repeated lesions and persistent tunnels rather than one isolated abscess.","Examination confirms recurrent inframammary HS with bridging scars that cause movement-related discomfort and no acute collection."]},claims:[{id:R,statement:"HS is recognized clinically by typical recurrent nodules, abscesses, tunnels, or scars in characteristic intertriginous sites with a relapsing course.",sourceIds:[SOURCES.hsAus.id,SOURCES.hsNa.id],category:"presentation",limitation:"No single lesion alone establishes the longitudinal diagnosis.",population:"Adults with recurrent lesions in intertriginous skin."},{id:P,statement:"Recurrent or tunnel-forming HS needs severity-based longitudinal multimodal medical and procedural planning.",sourceIds:[SOURCES.hsAus.id,SOURCES.hsNa.id],category:"management",limitation:"No specific drug regimen or universal operation is prescribed.",population:"Adults with established recurrent HS."},{id:D,statement:"Incision and drainage may relieve an acute collection but is not definitive control of chronic tunnel-forming HS.",sourceIds:[SOURCES.hsNa.id],category:"management",limitation:"Acute abscess assessment remains necessary when present.",population:"Adults with HS and recurrent abscesses or tunnels."}],sources:[SOURCES.hsAus,SOURCES.hsNa],concepts:[{id:"concept.hidradenitis-suppurativa.pattern-recognition",displayName:"Recognize hidradenitis suppurativa",learningObjective:"Recognize HS from lesion morphology, intertriginous distribution, and recurrence.",stage:0,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[R],variants:recognition},{id:"concept.hidradenitis-suppurativa.multimodal-specialist-planning",displayName:"Plan longitudinal HS care",learningObjective:"Refer recurrent or tunnel-forming HS for severity-based medical and procedural planning.",stage:0,educationalTier:1,conceptType:"management",evidenceClaimIds:[P,D],variants:planning}]};
const f=buildFamily(spec); export const HIDRADENITIS=f; export const HIDRADENITIS_AUTHORING_CONCEPTS=f.authoringConcepts,HIDRADENITIS_TESTED_CONCEPTS=f.testedConcepts,HIDRADENITIS_QUESTIONS=f.questions,HIDRADENITIS_CASES=f.cases,HIDRADENITIS_CLAIMS=f.claims,HIDRADENITIS_SOURCES=f.sources,HIDRADENITIS_CASE_REVIEWS=f.caseReviews,HIDRADENITIS_TIMING_ENTRIES=f.timingEntries,HIDRADENITIS_SERVICE_CONTRACTS=f.serviceContracts;







