import { buildFamily,type FamilySpec } from "./family-builder"; import { variants } from "./spec-utils"; import { SOURCES } from "./source-catalog";
const R="claim.parastomal-hernia.recognition",N="claim.parastomal-hernia.individualized-nonurgent-care",U="claim.parastomal-hernia.urgent-boundary";
const recognition=variants([
{slug:"standing-bulge",complaint:"Bulge by stoma",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a colostomy and a new soft bulge around the stoma that enlarges while standing or coughing and reduces while supine. Output and stoma color remain normal.",stem:"Which diagnosis best fits the examination?",correct:["Parastomal hernia","A dynamic peristomal bulge is compatible with a fascial defect beside the stoma."],wrong:[["Stoma prolapse","Prolapse is bowel telescoping outward through the stoma opening."],["Peristomal dermatitis","Dermatitis affects skin rather than creating a reducible bulge."],["Stoma retraction","Retraction draws the stoma below skin level rather than creating a bulge."]],explanation:"Recognize a stable parastomal hernia clinically and assess output, viability, pain, and obstruction.",claims:[R,U]},
{slug:"appliance-leak-bulge",complaint:"Pouch keeps leaking",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with an ileostomy, a gradually enlarging peristomal contour, and new appliance leakage. The bulge is reducible; output is normal and there is no severe pain.",stem:"Which structural complication is most likely?",correct:["Parastomal hernia","The reducible contour change beside the stoma explains appliance fit problems."],wrong:[["Stoma prolapse","The bowel itself is not described as elongated or protruding."],["Mucocutaneous separation","Separation occurs at the skin-stoma junction without a reducible bulge."],["Peristomal candidiasis","A rash does not explain the changing abdominal contour."]],explanation:"The peristomal bulge and appliance problem support parastomal hernia without emergency features.",claims:[R]},
{slug:"uncertain-obesity",complaint:"Uneven stoma area",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a stoma and an intermittent asymmetric peristomal fullness that cannot be clearly characterized on today's examination. Output is normal and symptoms are mild.",stem:"What is the best next assessment step?",correct:["Stoma-hernia specialist assessment","Diagnostic uncertainty warrants focused specialist examination, with imaging if needed."],wrong:[["Diagnose prolapse from the history alone","The bowel is not described as telescoping outward."],["Schedule immediate emergency surgery","There is no obstruction, ischemia, or severe pain."],["Treat empirically for skin infection","No rash or inflammatory skin finding is described."]],explanation:"When the examination is uncertain, obtain focused external assessment rather than asserting a diagnosis.",claims:[R,N]},
{slug:"obstructive-bulge",complaint:"Painful stoma bulge",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a tense nonreducible peristomal bulge, cramping abdominal pain, vomiting, and sharply decreased stoma output.",stem:"Which complication should be suspected?",correct:["Parastomal obstruction","A painful nonreducible bulge with vomiting and reduced output suggests obstruction."],wrong:[["Stable parastomal hernia","The obstructive symptoms make this more than a stable bulge."],["Stoma retraction","Retraction does not explain a tense bulge and bowel obstruction."],["Peristomal dermatitis","Skin inflammation does not explain vomiting and loss of output."]],explanation:"Recognize obstruction and arrange urgent external surgical evaluation.",claims:[R,U],acuity:"urgent"}]);
const care=variants([
{slug:"fit-and-comfort",complaint:"Pouch fit trouble",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a reducible parastomal hernia, normal output and viable stoma, but recurrent leakage and discomfort. There is no obstruction.",stem:"Which nonurgent plan is most appropriate?",correct:["Stoma-hernia specialist referral","Appliance fit, symptoms, goals, and operative candidacy need individualized assessment."],wrong:[["Choose an off-the-shelf support belt","A generic belt does not address the current pouch-fit problem without individualized assessment."],["Monitor symptoms without appliance review","Ongoing leakage and discomfort warrant focused appliance and stoma assessment."],["Emergency hospital transfer","Stable output, viability, and reducibility do not indicate an emergency."]],explanation:"Use individualized external stoma and hernia care; no universal garment or operation is promised.",claims:[N]},
{slug:"minimal-symptoms",complaint:"Stoma bulge options",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a stable reducible parastomal hernia, reliable appliance seal, normal output, and minimal discomfort. The patient prefers nonoperative care.",stem:"Which plan best respects the current situation?",correct:["Conservative follow-up","Stable minimal symptoms and preference can support conservative care with safety-netting."],wrong:[["Elective repair referral now","Repair is not compulsory for every stable parastomal hernia."],["Fixed garment prescription","A universal garment cannot be selected without individual assessment."],["Emergency transfer","No acute complication is present."]],explanation:"Preserve patient preference and evidence uncertainty while arranging appropriate follow-up.",claims:[N,U]},
{slug:"activity-concern",complaint:"Safe activity with bulge",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a reducible parastomal hernia, normal output, and anxiety about activity after noticing the bulge. There is no pain or appliance failure.",stem:"What is the best management approach?",correct:["Specialist-guided activity plan","Advice should reflect symptoms, appliance fit, goals, and available expertise."],wrong:[["Restrict lifting without specialist review","A universal permanent restriction is unsupported."],["Order routine emergency surgery","The stable reducible finding is not an emergency."],["Select a garment without fitting","Support products require individualized assessment."]],explanation:"Use tailored education and external stoma expertise rather than one-size restrictions.",claims:[N]},
{slug:"support-preference",complaint:"Support garment question",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a stable reducible parastomal hernia, normal output, and intermittent discomfort. The patient wants to know whether a support garment could help.",stem:"Which plan is most appropriate?",correct:["Individualized stoma-specialist fitting","A specialist can assess symptoms, appliance contour, goals, and whether a fitted support is useful."],wrong:[["Standard garment selected by size alone","Support selection needs individualized assessment of the stoma and abdominal contour."],["Elective repair based only on garment interest","Interest in support does not itself establish an operative indication."],["Observation without stoma assessment","Symptoms and support questions merit focused nonurgent review."]],explanation:"Use individualized external stoma care rather than a universal support prescription.",claims:[N]}]);
const spec:FamilySpec={slug:"parastomal-hernia",label:"Parastomal hernia",pairing:{indices:[0,1],updates:["The bulge remains reducible, output is normal, and the main issue is comfort and pouch fit.","Focused fitting restores a reliable seal; the patient reports minimal discomfort and prefers nonoperative follow-up."]},claims:[{id:R,statement:"A dynamic peristomal bulge compatible with a fascial defect supports parastomal-hernia recognition; uncertainty or obstructive symptoms require further assessment.",sourceIds:[SOURCES.missto.id,SOURCES.parastomal.id],category:"evaluation",limitation:"The EHS source is a limited cross-check; detailed boundaries rely on the open mapping review.",population:"Adults with an established stoma and new peristomal contour change."},{id:N,statement:"Stable nonobstructed parastomal hernia symptoms may receive individualized appliance, support, activity, education, and external referral measures.",sourceIds:[SOURCES.nursing.id,SOURCES.missto.id],category:"management",certainty:"low",limitation:"Evidence is limited; no universal garment or routine operation is supported.",population:"Adults with a stable reducible parastomal hernia."},{id:U,statement:"A painful nonreducible parastomal bulge with vomiting or reduced output requires urgent surgical evaluation for obstruction or ischemia.",sourceIds:[SOURCES.missto.id,SOURCES.acpgbi.id],category:"disposition",limitation:"No clinic maneuver should delay transfer.",population:"Adults with a stoma and acute obstructive features."}],sources:[SOURCES.missto,SOURCES.parastomal,SOURCES.nursing,SOURCES.acpgbi],concepts:[{id:"concept.parastomal-hernia.clinical-recognition",displayName:"Recognize parastomal hernia",learningObjective:"Recognize a parastomal hernia and identify uncertainty or obstruction.",stage:1,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[R,U],variants:recognition},{id:"concept.parastomal-hernia.nonurgent-stoma-specialist-management",displayName:"Plan stable parastomal hernia care",learningObjective:"Choose individualized external stoma and hernia care for a stable reducible parastomal hernia.",stage:1,educationalTier:1,conceptType:"management",evidenceClaimIds:[N,U],variants:care}]};
const f=buildFamily(spec); export const PARASTOMAL_HERNIA=f; export const PARASTOMAL_HERNIA_AUTHORING_CONCEPTS=f.authoringConcepts,PARASTOMAL_HERNIA_TESTED_CONCEPTS=f.testedConcepts,PARASTOMAL_HERNIA_QUESTIONS=f.questions,PARASTOMAL_HERNIA_CASES=f.cases,PARASTOMAL_HERNIA_CLAIMS=f.claims,PARASTOMAL_HERNIA_SOURCES=f.sources,PARASTOMAL_HERNIA_CASE_REVIEWS=f.caseReviews,PARASTOMAL_HERNIA_TIMING_ENTRIES=f.timingEntries,PARASTOMAL_HERNIA_SERVICE_CONTRACTS=f.serviceContracts;








