import { describe,expect,it } from "vitest";
import { answerChoiceTimingRegistryEntrySchema, syntheticClinicalCaseSchema, testedConceptSchema } from "../../schema";
import { GS028_20260928_AUTHORING_CONCEPTS as concepts,GS028_20260928_TESTED_CONCEPTS as testedConcepts,GS028_20260928_QUESTIONS as questions,GS028_20260928_CASES as cases,GS028_20260928_CLAIMS as claims,GS028_20260928_SOURCES as sources,GS028_20260928_TIMING_ENTRIES as timing } from "./pre-endoscopy-batch";
describe("GS-028 pre-Endoscopy batch",()=>{
 it("contains exactly 20 concepts and four substantive variants each",()=>{expect(concepts).toHaveLength(20);expect(questions).toHaveLength(80);for(const c of concepts){const q=questions.filter(x=>x.conceptId===c.id);expect(q).toHaveLength(4);expect(new Set(q.map(x=>x.patientPresentation))).toHaveLength(4);expect(new Set(q.map(x=>x.stem+"|"+x.answerChoices.map(a=>a.label).join("|")))).toHaveLength(4);}});
 it("keeps every objective independently eligible",()=>{for(const c of concepts)expect(cases.some(x=>x.decisionNodes.length===1&&x.decisionNodes[0]?.primaryConceptId===c.id)).toBe(true);});
 it("has one key, coherent profiles, review metadata, and randomized answers",()=>{for(const q of questions){expect(q.answerChoices).toHaveLength(4);expect(q.answerChoices.filter(x=>x.isCorrect)).toHaveLength(1);expect(q.approvedInstantiationProfiles.length).toBeGreaterThanOrEqual(2);for(const p of q.approvedInstantiationProfiles){expect(p.prototypeDemographics!.ageYears).toBeGreaterThan(17);expect(["Female","Male","Not specified"]).toContain(p.prototypeDemographics!.sexLabel);}expect(q.reviewStatus).toBe("needs_clinician_review");}for(const c of cases)for(const n of c.decisionNodes)expect(n.shuffleAnswers).toBe(true);});
 it("maps questions to existing claims and claims to complete sources",()=>{const claimIds=new Set(claims.map(x=>x.id)),sourceIds=new Set(sources.map(x=>x.id));expect(sourceIds.size).toBe(sources.length);for(const q of questions)for(const id of q.supportingEvidenceClaimIds)expect(claimIds.has(id)).toBe(true);expect(new Set(claims.map(x=>x.id)).size).toBe(claims.length);for(const c of claims)for(const id of c.sourceIds){expect(sourceIds.has(id)).toBe(true);expect(sources.find(s=>s.id===id)?.evidenceClaimIds).toContain(c.id);}for(const s of sources){expect(s.completeCitation.length).toBeGreaterThan(25);expect(s.organizationOrJournal.length).toBeGreaterThan(2);expect(s.officialUrl).toMatch(/^https:/);for(const id of s.evidenceClaimIds)expect(claimIds.has(id)).toBe(true);}});
 it("provides timing classifications for every question",()=>{expect(timing).toHaveLength(questions.length);expect(new Set(timing.map(x=>x.questionVariantId)).size).toBe(questions.length);});
 it("passes runtime schemas and keeps all identifiers unique",()=>{for(const c of testedConcepts)testedConceptSchema.parse(c);for(const c of cases)syntheticClinicalCaseSchema.parse(c);for(const t of timing)answerChoiceTimingRegistryEntrySchema.parse(t);expect(new Set(cases.map(x=>x.id)).size).toBe(cases.length);const nodes=cases.flatMap(x=>x.decisionNodes);expect(new Set(nodes.map(x=>x.id)).size).toBe(nodes.length);expect(new Set(questions.map(x=>x.id)).size).toBe(questions.length);});
 it("classifies every authored reflux-duplex choice as a timed test",()=>{const entries=timing.filter(x=>x.questionVariantId.includes("varicose-veins.reflux-duplex-evaluation"));expect(entries).toHaveLength(4);for(const entry of entries){expect(entry.classification.kind).toBe("test_choices");if(entry.classification.kind==="test_choices")for(const item of entry.classification.choices)expect(item.timing.kind).toBe("test");}});
 it("stays in the clinic release and before Endoscopy capability stage",()=>{for(const c of cases){expect(c.releasePointId).toBe("release.l0.clinic_evaluation");expect(c.earliestFacilityStage).toBeLessThanOrEqual(2);}});
 it("anchors every case to a named patient's story",()=>{const cue=/\b(?:asks?|wants?|requests?|reports?|returns?|arrives?|noticed|notes?|describes?|is seen|comes?|brings?|discuss|reviews?|reviewing|hoping|considering|counseled|diagnosed|shows?|showing|discovered|identifies|referred|confirming|evaluated|found|undergoing|preparing|prepared|presents?|has|have|had|develops?|confirms|completed|scheduled|plans|starts|persists|decides|receives|eats?)\b/i;expect(cases.filter(x=>!cue.test(x.presentation)).map(x=>x.id)).toEqual([]);});
 it("does not reveal the key by making it uniquely longest",()=>{const violations=questions.flatMap(q=>{const key=q.answerChoices.find(x=>x.isCorrect);const wrong=q.answerChoices.filter(x=>!x.isCorrect);return key!==undefined&&key.label.length>Math.max(...wrong.map(x=>x.label.length))?[{id:q.id,key:key.label,wrong:wrong.map(x=>x.label)}]:[];});expect(violations).toEqual([]);});
});




