import { buildFamily, type FamilySpec } from "./family-builder"; import { variants } from "./spec-utils"; import { SOURCES } from "./source-catalog";
const R="claim.primary-midline-hernia.clinical-recognition",M="claim.primary-midline-hernia.symptomatic-referral",U="claim.primary-midline-hernia.urgent-boundary";
const recognition=variants([
{slug:"umbilical-cough-bulge",complaint:"Navel bulge",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a soft focal bulge at the umbilicus that appears with coughing and reduces while supine. There is no vomiting, skin change, or persistent pain.",stem:"Which diagnosis best fits {patientName}'s examination?",correct:["Umbilical hernia","A focal reducible umbilical bulge is a clinical hernia pattern."],wrong:[["Epigastric hernia","The defect is described at the umbilicus, not above it."],["Rectus sheath hematoma","A hematoma is not typically cough-impulsive and reducible."],["Umbilical skin abscess","An abscess would not reduce with position or pressure."]],explanation:"A focal reducible umbilical bulge is usually diagnosed clinically; imaging is reserved for uncertainty.",claims:[R]},
{slug:"epigastric-focal-lump",complaint:"Upper midline lump",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a small focal upper-midline bulge between the xiphoid and umbilicus that becomes prominent while lifting. It is soft, reducible, and without obstructive symptoms.",stem:"Which diagnosis is most likely?",correct:["Epigastric hernia","The focal reducible upper-midline defect fits an epigastric hernia."],wrong:[["Umbilical hernia","The bulge is above rather than at the umbilicus."],["Subcutaneous lipoma","A lipoma does not usually change with strain and reduce through a defect."],["Abdominal-wall abscess","An abscess would be inflammatory rather than reducible."]],explanation:"The site and reducible focal defect support an epigastric hernia on clinical examination.",claims:[R]},
{slug:"uncertain-deep-bulge",complaint:"Intermittent belly lump",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with an intermittent small midline bulge and discomfort, but today's examination cannot define a fascial defect because the finding is not reproducible. There are no emergency features.",stem:"What is the most appropriate next step to clarify the diagnosis?",correct:["Targeted abdominal-wall ultrasound","Ultrasound or CT can clarify an equivocal examination."],wrong:[["Diagnose a hernia with certainty","The examination is explicitly inconclusive."],["Immediate emergency surgical transfer","There are no obstructive, ischemic, or peritoneal findings."],["Begin antibiotics for cellulitis","No inflammatory skin findings support infection."]],explanation:"Most primary midline hernias are clinical diagnoses, but targeted imaging is reasonable when examination is inconclusive.",claims:[R],test:{timingProfileId:"timing.test.ultrasound",serviceId:"service.ultrasound",gate:{serviceId:"service.ultrasound",pendingLabel:"Abdominal-wall ultrasound pending",resultNarrative:"Ultrasound identifies a small primary midline fascial defect containing reducible fat.",routeIds:["route.ultrasound.in_house","route.ultrasound.outsourced"]}}},
{slug:"reducible-after-pregnancy",complaint:"Small navel lump",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a discrete pea-sized bulge at the umbilical ring that enlarges on standing and slips back when supine. The surrounding skin is normal and bowel function is unchanged.",stem:"Which finding most directly supports the diagnosis?",correct:["Reducible umbilical defect","The focal location and reducibility support an umbilical hernia."],wrong:[["Diffuse abdominal-wall laxity","Diffuse laxity is not the discrete defect described."],["Fixed tender skin nodule","A fixed skin lesion would not behave like a reducible defect."],["Generalized abdominal distention","Distention does not localize a fascial defect."]],explanation:"Recognition rests on the discrete umbilical defect and its dynamic reducibility, and imaging is not routinely needed when examination is clear.",claims:[R]}]);
const referral=variants([
{slug:"activity-pain",complaint:"Painful navel hernia",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a reducible umbilical hernia that now causes pain during work and limits activity. There is no vomiting, incarceration, or skin compromise.",stem:"Which plan best addresses the stable symptomatic hernia?",correct:["Elective hernia-surgery referral","Persistent symptoms support individualized elective repair discussion."],wrong:[["Emergency transfer now","The hernia is reducible without obstruction or ischemia."],["Routine antibiotics","There is no evidence of infection."],["Continue observation without referral","Persistent activity-limiting symptoms merit a repair discussion."]],explanation:"Refer the stable symptomatic hernia for an individualized elective discussion; do not prescribe one universal technique.",claims:[M,U]},
{slug:"enlarging-epigastric",complaint:"Growing upper lump",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a reducible epigastric hernia that has enlarged and become uncomfortable with lifting. Examination shows no tenderness, skin change, or obstruction.",stem:"What is the best disposition?",correct:["Elective surgery consultation","Growth and symptoms justify individualized elective assessment."],wrong:[["Immediate emergency operation","No emergency feature is present."],["Antibiotic treatment","The presentation is not infectious."],["Continue self-monitoring","An enlarging symptomatic hernia warrants discussion."]],explanation:"A stable but enlarging symptomatic epigastric hernia belongs in an elective referral pathway.",claims:[M,U]},
{slug:"minimally-symptomatic-preference",complaint:"Hernia options",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a small reducible umbilical hernia causing occasional discomfort. The patient wants to understand observation and repair, and has no acute warning signs.",stem:"Which counseling plan is most appropriate?",correct:["Discuss observation and elective repair","Symptoms, goals, hernia features, and local resources should guide the choice."],wrong:[["Recommend elective repair as the only option","A stable reducible hernia does not make one choice mandatory."],["Select a repair technique in clinic","Technique requires individualized surgical assessment."],["Send for emergency transfer","No incarceration or strangulation feature is present."]],explanation:"Use shared elective decision-making and preserve uncertainty about technique and timing.",claims:[M,U]},
{slug:"incarceration-warning",complaint:"Painful stuck bulge",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a previously reducible umbilical hernia that is now acutely painful, firm, nonreducible, and accompanied by vomiting.",stem:"Which disposition is required?",correct:["Emergency surgery review","A painful nonreducible hernia with vomiting raises concern for incarceration or strangulation."],wrong:[["Routine elective referral","The acute nonreducibility and vomiting cannot wait for routine review."],["Home observation","Observation risks delayed treatment of compromised bowel."],["Compression garment fitting","A garment does not treat an acute incarcerated hernia."]],explanation:"Acute pain, nonreducibility, and obstructive symptoms cross the emergency boundary.",claims:[U],acuity:"urgent"}]);
const spec:FamilySpec={slug:"primary-midline-hernia",label:"Primary midline hernia",pairing:{indices:[0,1],updates:["Examination confirms a reducible umbilical defect without obstruction; the patient adds that pain during work now limits activity.","Examination confirms a reducible epigastric defect without obstruction; the patient reports interval enlargement and discomfort with lifting."]},claims:[
{id:R,statement:"Most umbilical and epigastric hernias are diagnosed clinically; targeted ultrasound or CT can clarify an inconclusive examination.",sourceIds:[SOURCES.hernia.id],category:"evaluation",limitation:"No unsourced distinction from rectus diastasis is taught.",population:"Adults with a suspected primary umbilical or epigastric hernia."},
{id:M,statement:"A stable symptomatic umbilical or epigastric hernia supports individualized elective repair discussion.",sourceIds:[SOURCES.hernia.id],category:"management",limitation:"The guideline reports limited evidence for many technique details; no universal technique is claimed.",population:"Adults with reducible symptomatic primary midline hernias."},
{id:U,statement:"Acute nonreducibility with severe pain, vomiting, obstruction, or skin compromise requires urgent surgical assessment rather than elective counseling.",sourceIds:[SOURCES.hernia.id],category:"safety_boundary",certainty:"moderate",limitation:"The objective teaches disposition, not operative technique.",population:"Adults with primary midline hernias."}],sources:[SOURCES.hernia],serviceContracts:[{serviceId:"service.ultrasound",allowedRouteIds:["route.ultrasound.in_house","route.ultrasound.outsourced"],delivery:"existing_balance_contract"}],concepts:[
{id:"concept.umbilical-epigastric-hernia.clinical-recognition",displayName:"Recognize primary midline hernia",learningObjective:"Recognize umbilical or epigastric hernia clinically and reserve imaging for uncertainty.",stage:0,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[R],variants:recognition},
{id:"concept.umbilical-epigastric-hernia.symptomatic-elective-referral",displayName:"Refer symptomatic primary midline hernia",learningObjective:"Refer a stable symptomatic primary midline hernia for individualized elective repair discussion.",stage:0,educationalTier:0,conceptType:"disposition",evidenceClaimIds:[M,U],variants:referral}]};
const f=buildFamily(spec); export const PRIMARY_MIDLINE_HERNIA=f; export const PRIMARY_MIDLINE_HERNIA_AUTHORING_CONCEPTS=f.authoringConcepts,PRIMARY_MIDLINE_HERNIA_TESTED_CONCEPTS=f.testedConcepts,PRIMARY_MIDLINE_HERNIA_QUESTIONS=f.questions,PRIMARY_MIDLINE_HERNIA_CASES=f.cases,PRIMARY_MIDLINE_HERNIA_CLAIMS=f.claims,PRIMARY_MIDLINE_HERNIA_SOURCES=f.sources,PRIMARY_MIDLINE_HERNIA_CASE_REVIEWS=f.caseReviews,PRIMARY_MIDLINE_HERNIA_TIMING_ENTRIES=f.timingEntries,PRIMARY_MIDLINE_HERNIA_SERVICE_CONTRACTS=f.serviceContracts;









