import { buildFamily,type FamilySpec } from "./family-builder"; import { variants } from "./spec-utils"; import { SOURCES } from "./source-catalog";
const R="claim.lymphedema.secondary-recognition",D="claim.lymphedema.differential-safety",T="claim.lymphedema.decongestive-referral",E="claim.lymphedema.early-pitting",L="claim.lymphedema.late-fibrosis";
const recognition=variants([
{slug:"arm-after-axillary",complaint:"Arm swelling",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with gradually progressive arm heaviness, swelling, and skin thickening months after axillary lymph-node surgery and radiation. There is no erythema, fever, acute pain, chest symptom, or sudden onset.",stem:"Which diagnosis best fits the pattern?",correct:["Secondary arm lymphedema","Prior lymphatic treatment and chronic progressive swelling support secondary lymphedema."],wrong:[["Acute upper-extremity DVT","DVT is an important exclusion but the gradual chronic tissue change favors lymphedema."],["Acute cellulitis","There is no warmth, erythema, tenderness, or fever."],["Generalized heart-failure edema","The swelling is localized to the treated lymphatic territory."]],explanation:"Recognize secondary lymphedema while remaining alert for acute thrombosis, infection, recurrence, and systemic edema when findings suggest them.",claims:[R,D]},
{slug:"leg-after-groin-nodes",complaint:"Heavy swollen leg",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with slowly increasing unilateral leg heaviness, dorsal-foot swelling, and firm skin months after groin-node treatment. There is no abrupt pain, redness, fever, or dyspnea.",stem:"What is the most likely diagnosis?",correct:["Secondary leg lymphedema","The lymphatic treatment history and chronic tissue pattern are compatible."],wrong:[["Acute lower-extremity DVT","Acute DVT remains a differential but is less consistent with the slow chronic evolution."],["Bacterial cellulitis","There are no acute inflammatory or systemic findings."],["Bilateral systemic edema","The problem is unilateral in a treated lymphatic basin."]],explanation:"The history and chronic distribution support secondary lymphedema, with targeted investigation if the pattern changes.",claims:[R,D]},
{slug:"early-pitting-arm",complaint:"Arm feels full",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with gradually increasing arm fullness and pitting swelling several months after sentinel and axillary node treatment. There is no fever, erythema, acute pain, chest symptom, or sudden onset.",stem:"Which diagnosis best fits this chronic pattern?",correct:["Early arm lymphedema","Early lymphedema may remain soft and pitting after lymphatic injury."],wrong:[["Acute upper-extremity DVT","The gradual painless course is less typical, though sudden change would require evaluation."],["Acute cellulitis","No warmth, erythema, tenderness, or fever is present."],["Generalized systemic edema","The swelling is localized to the treated lymphatic territory."]],explanation:"Secondary lymphedema can be pitting early; the chronic tempo and treatment distribution support recognition.",claims:[R,D,E]},
{slug:"late-fibrotic-leg",complaint:"Firm swollen leg",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with long-standing unilateral leg swelling, skin thickening, and firm tissue after pelvic lymph-node treatment. The change has been gradual, without redness, fever, acute pain, dyspnea, or sudden worsening.",stem:"Which diagnosis best explains the findings?",correct:["Chronic leg lymphedema","Later lymphedema can become firm and fibrotic in the treated drainage territory."],wrong:[["Acute lower-extremity DVT","The long gradual fibrotic course is less typical of acute thrombosis."],["Acute bacterial cellulitis","There are no inflammatory or systemic findings."],["Bilateral cardiac edema","The unilateral treated-territory pattern is not generalized systemic edema."]],explanation:"The chronic unilateral fibrotic pattern after lymphatic treatment supports secondary lymphedema.",claims:[R,D,L]}]);
const therapy=variants([
{slug:"new-stable-arm",complaint:"Lymphedema treatment",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with confirmed stable secondary arm lymphedema after node treatment and no infection, DVT, or recurrence concern. The patient asks about treatment.",stem:"Which plan is most appropriate?",correct:["Refer for decongestive therapy","Specialist care can combine fitted compression, exercise, skin care, and manual techniques as appropriate."],wrong:[["Choose a fixed compression pressure now","Garment type and pressure require individual assessment."],["Use compression alone without assessment","Compression is one component and needs individual fitting."],["Recommend rest without movement","Appropriate exercise is commonly part of decongestive care."]],explanation:"Refer for individualized complete decongestive care rather than prescribing one universal modality or dose.",claims:[T]},
{slug:"leg-skin-care",complaint:"Leg swelling plan",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with established stable secondary leg lymphedema, dry fissured skin, and heaviness but no acute infection or thrombosis concern.",stem:"Which management pathway is appropriate?",correct:["Lymphedema-therapy referral","A tailored program can address compression fitting, movement, skin care, and manual techniques."],wrong:[["Compression purchase without fitting","Unsupervised generic compression may not fit the limb or clinical context."],["Antibiotics without infection","Dry skin alone is not an indication for antibiotics."],["Strict activity avoidance","Movement is generally incorporated rather than prohibited."]],explanation:"Use specialist assessment to tailor the components and protect the skin.",claims:[T]},
{slug:"garment-discomfort",complaint:"Compression feels wrong",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with stable secondary lymphedema and a poorly fitting over-the-counter garment causing focal pressure and discomfort. There are no acute vascular or infectious findings.",stem:"What is the best next step?",correct:["Specialist garment reassessment","Compression should be individualized and reassessed for fit and tolerance."],wrong:[["Increase compression independently","More pressure without assessment may worsen focal problems."],["Stop compression and defer reassessment","The problem may be fit rather than the entire treatment approach."],["Begin antimicrobial treatment","No infection findings are present."]],explanation:"Reassess fit, limb status, goals, and the full decongestive plan rather than applying a universal pressure rule.",claims:[T]},
{slug:"exercise-question",complaint:"Can I exercise?",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with stable secondary arm lymphedema controlled with an individualized program and asks whether movement should be avoided. There is no acute complication.",stem:"Which counseling plan is most appropriate?",correct:["Continue tailored exercise plan","Exercise is one component of decongestive care when tailored to the patient."],wrong:[["Avoid affected-arm exercise","Universal activity avoidance is not part of complete decongestive care."],["Replace the program with massage alone","One modality should not replace the individualized program."],["Reuse the current garment without refitting","Compression selection depends on individual assessment."]],explanation:"Support tailored exercise alongside skin care, compression, and other indicated components.",claims:[T]}]);
const spec:FamilySpec={slug:"secondary-lymphedema",label:"Secondary lymphedema",pairing:{indices:[0,1],updates:["Evaluation supports stable secondary arm lymphedema without acute thrombosis, infection, or recurrence concern.","Evaluation supports stable secondary leg lymphedema; dry fissured skin and heaviness are present without acute thrombosis or infection."]},claims:[{id:R,statement:"Chronic limb swelling after lymph-node or lymphatic-vessel treatment may represent secondary lymphedema when history and tissue findings are compatible.",sourceIds:[SOURCES.isl.id,SOURCES.nci.id],category:"evaluation",limitation:"The diagnosis is not made solely from prior treatment history.",population:"Adults with chronic limb swelling after lymphatic treatment."},{id:D,statement:"Acute DVT, infection, recurrent malignancy, and systemic causes must be considered and investigated when the tempo or associated findings indicate them.",sourceIds:[SOURCES.isl.id,SOURCES.nci.id],category:"safety_boundary",limitation:"Testing is driven by the differential rather than ordered routinely for every stable case.",population:"Adults with suspected or established secondary lymphedema."},{id:E,statement:"Early secondary lymphedema may remain soft and pitting before later tissue changes develop.",sourceIds:[SOURCES.isl.id,SOURCES.nci.id],category:"presentation",limitation:"Pitting is compatible but not diagnostic by itself.",population:"Adults with early secondary limb lymphedema."},{id:L,statement:"Long-standing secondary lymphedema can develop firm tissue and skin thickening consistent with fibrotic change.",sourceIds:[SOURCES.isl.id,SOURCES.nci.id],category:"presentation",limitation:"Chronic firmness still requires assessment for other causes when the pattern changes.",population:"Adults with chronic secondary limb lymphedema."},{id:T,statement:"Established lymphedema is managed with individualized decongestive care using fitted compression, exercise, skin care, and manual lymphatic drainage as appropriate.",sourceIds:[SOURCES.isl.id,SOURCES.nci.id],category:"management",limitation:"Evidence and response vary; no universal garment, pressure, modality, or guaranteed response is claimed.",population:"Adults with stable established secondary lymphedema."}],sources:[SOURCES.isl,SOURCES.nci],concepts:[{id:"concept.secondary-lymphedema.clinical-recognition",displayName:"Recognize secondary lymphedema",learningObjective:"Recognize chronic secondary lymphedema while identifying changes that require another differential.",stage:1,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[R,D,E,L],variants:recognition},{id:"concept.secondary-lymphedema.decongestive-therapy-referral",displayName:"Refer for decongestive lymphedema therapy",learningObjective:"Refer stable established secondary lymphedema for individualized decongestive care.",stage:1,educationalTier:0,conceptType:"management",evidenceClaimIds:[T],variants:therapy}]};
const f=buildFamily(spec); export const SECONDARY_LYMPHEDEMA=f; export const SECONDARY_LYMPHEDEMA_AUTHORING_CONCEPTS=f.authoringConcepts,SECONDARY_LYMPHEDEMA_TESTED_CONCEPTS=f.testedConcepts,SECONDARY_LYMPHEDEMA_QUESTIONS=f.questions,SECONDARY_LYMPHEDEMA_CASES=f.cases,SECONDARY_LYMPHEDEMA_CLAIMS=f.claims,SECONDARY_LYMPHEDEMA_SOURCES=f.sources,SECONDARY_LYMPHEDEMA_CASE_REVIEWS=f.caseReviews,SECONDARY_LYMPHEDEMA_TIMING_ENTRIES=f.timingEntries,SECONDARY_LYMPHEDEMA_SERVICE_CONTRACTS=f.serviceContracts;








