import { buildFamily, type FamilySpec, type VariantSpec } from "./family-builder";
const C1="claim.sbo.ct-transition-pattern", C2="claim.sbo.ct-ischemia-limit", C3="claim.sbo.urgent-escalation-features";
const A="concept.small-bowel-obstruction.ct-pattern-recognition", B="concept.small-bowel-obstruction.urgent-surgical-escalation";
const v=(slug:string,complaint:string,presentation:string,stem:string,correct:[string,string,string],d:[[string,string,string],[string,string,string],[string,string,string]],explanation:string,claimIds:string[],currentUpdate?:string):VariantSpec=>({slug,complaint,presentation,stem,correct:{id:correct[0],label:correct[1],rationale:correct[2]},distractors:d.map(x=>({id:x[0],label:x[1],rationale:x[2]})) as VariantSpec["distractors"],explanation,claimIds,...(currentUpdate?{currentUpdate}:{})});
const ct=[
v("adhesive-transition","Outside CT review","{patientName} is a {patientAge}-year-old {patientSex} who returns for stable follow-up after colicky pain, vomiting, distention, and obstipation resolved during hospital care. Outside CT reported dilated proximal small bowel, a discrete transition point, and decompressed distal bowel.","Which diagnosis best explains {patientName}'s completed CT pattern?",["sbo","Mechanical small-bowel obstruction","A transition point separating dilated proximal from decompressed distal small bowel supports mechanical obstruction."],[["ileus","Generalized adynamic small-bowel ileus","Ileus more often lacks a discrete mechanical transition with distal decompression."],["gastroparesis","Gastroparesis","Gastroparesis does not explain the small-bowel transition pattern."],["colitis","Acute colitis","Colitis does not produce this proximal-small-bowel transition pattern."]],"The completed CT pattern supports mechanical SBO; the scan must still be integrated with examination and does not alone exclude evolving ischemia.",[C1,C2]),
v("hernia-transition","Review prior CT","{patientName} is a {patientAge}-year-old {patientSex} who returns for stable follow-up after vomiting and distention resolved. The outside CT described clustered dilated small-bowel loops leading to one transition with collapsed bowel beyond it.","What is the most direct interpretation of this CT report?",["sbo2","Mechanical small-bowel obstruction","The proximal dilation and downstream collapse localize a mechanical obstruction."],[["constipation","Uncomplicated constipation","Constipation does not account for a focal small-bowel transition."],["ileus2","Generalized postoperative small-bowel ileus","A generalized ileus usually does not show one transition with decompressed distal bowel."],["gastritis","Acute gastritis","Gastritis does not explain dilated small bowel with downstream collapse."]],"A focal transition with proximal dilation and distal collapse is the key mechanical SBO pattern; clinical danger features determine urgency.",[C1,C2]),
v("closed-loop-concern","Prior vomiting episode","{patientName} is a {patientAge}-year-old {patientSex} who returns for stable follow-up after a resolved hospital episode of cramping, vomiting, distention, and obstipation. The clinician is reviewing the completed CT description from that episode.","Which completed CT description would most strongly support mechanical small-bowel obstruction?",["mechanical_concern","Proximal dilation, transition, distal decompression","This caliber change across a transition point supports mechanical SBO."],[["benign_ileus","Diffuse bowel dilation without a transition point","Diffuse dilation without a focal transition is more compatible with an adynamic ileus pattern."],["gastric_delay","Isolated gastric dilation with normal small bowel","An isolated gastric finding does not establish small-bowel obstruction."],["colitis_dx","Segmental colonic wall thickening without small-bowel dilation","A colonic wall abnormality without small-bowel dilation does not establish SBO."]],"Mechanical SBO is supported by proximal small-bowel dilation, a transition point, and decompressed distal bowel. That pattern does not by itself determine bowel viability.",[C1,C2]),
v("partial-pattern","Outside CT review","{patientName} is a {patientAge}-year-old {patientSex} reviewing a completed outside scan after intermittent vomiting. The report notes moderately dilated jejunum to a transition point with little distal gas. Symptoms have resolved and the abdomen is soft at follow-up.","Which diagnosis best explains the prior CT pattern?",["partial_sbo","Mechanical small-bowel obstruction","The transition and downstream decompression support mechanical SBO."],[["ischemia_dx","Mesenteric ischemia","The described transition establishes obstruction but does not independently diagnose ischemia."],["ileus_no_transition","Diffuse adynamic small-bowel ileus","A discrete transition and distal decompression favor mechanical obstruction."],["pancreatitis","Acute pancreatitis","The bowel-caliber pattern is not a pancreatic diagnosis."]],"Interpret the prior transition pattern as mechanical SBO while avoiding claims about bowel viability that the report does not establish.",[C1,C2])];
const urgent=[
v("peritoneal-signs","Worsening abdominal pain","{patientName} is a {patientAge}-year-old {patientSex} who presents with vomiting, distention, a completed outside CT showing small-bowel obstruction, and now constant severe pain, guarding, rebound, tachycardia, and worsening tenderness.","What is the safest next disposition?",["transfer","Emergency surgery review","Peritoneal findings with SBO require urgent surgical evaluation."],[["clinic_observe","Continued observation in clinic","Observation risks delaying care for possible strangulation or ischemia."],["oral_trial","Oral hydration trial in clinic","Oral intake is unsafe in worsening obstruction with peritoneal findings."],["routine_followup","Routine outpatient surgery referral","Routine referral is too slow for peritonitis with obstruction."]],"Escalate immediately for emergency surgical evaluation when SBO is accompanied by peritonitis or concern for ischemia.",[C3]),
v("systemic-decline","Vomiting and weakness","{patientName} is a {patientAge}-year-old {patientSex} who presents with a documented mechanical small-bowel obstruction and develops fever, rising heart rate, localized guarding, and continuous rather than colicky pain during reassessment.","Which action should occur now?",["edsurgery","Emergency surgical assessment","Systemic decline and localized peritoneal findings raise concern for compromised bowel."],[["nextday","Schedule next-day clinic review","The evolving danger signs require care sooner than routine follow-up."],["symptomatic","Provide symptom treatment and observe","Observation risks delay when bowel compromise is possible."],["discharge","Discharge with return precautions","Current peritoneal and systemic findings require action now."]],"The change from intermittent symptoms to systemic and peritoneal danger signs warrants immediate external emergency surgical care.",[C3]),
v("stable-no-red-flags","Stable obstruction review","{patientName} is a {patientAge}-year-old {patientSex} reviewing a prior small-bowel-obstruction admission. Today pain has resolved, bowel function has returned, vital signs are normal, and the abdomen is soft without tenderness or distention.","Which feature would change this follow-up into an emergency surgical referral?",["peritonitis","New guarding with rebound","Peritoneal irritation with suspected SBO is an emergency feature."],[["scar","A healed abdominal scar","A scar may suggest adhesion risk but is not itself an emergency finding."],["resolved","Continued passage of stool","Ongoing bowel function does not establish acute strangulation."],["mild_question","Questions about recurrence","Education needs do not alone require emergency transfer."]],"New peritonitis, continuous severe pain, or systemic deterioration would trigger urgent escalation; a stable resolved follow-up does not invent an emergency.",[C3]),
v("ischemia-warning","Pain out of proportion","{patientName} is a {patientAge}-year-old {patientSex} arrives with known small-bowel obstruction, escalating continuous pain, diaphoresis, tachycardia, and marked tenderness. No additional clinic imaging has been obtained.","What should the clinic do before any routine testing?",["urgent","Emergency surgery review","The clinical picture raises concern for strangulation or ischemia and should not wait for clinic testing."],[["oralfluids","Oral hydration and clinic reassessment","Oral fluids and observation are unsafe in a deteriorating obstruction."],["routine","Routine outpatient surgery referral","Routine follow-up is inadequate for possible ischemia."],["symptomcare","Symptom treatment followed by discharge","Discharge after symptomatic treatment risks delaying compromised-bowel care."]],"Clinical concern for bowel compromise is enough to escalate; a clinic test result is not required before transfer.",[C3])];
urgent.forEach((x,i)=>{if(i!==2){x.acuity="urgent";x.prototypeVitalSigns={heartRateBpm:112,systolicBloodPressureMmHg:104,diastolicBloodPressureMmHg:66,temperatureF:i===1?101.5:99.2,oxygenSaturationPercent:97};}});
const spec:FamilySpec={slug:"small-bowel-obstruction",label:"Small-bowel obstruction",claims:[
{id:C1,statement:"A completed CT showing proximal small-bowel dilation, a transition point, and distal decompression supports mechanical SBO.",sourceIds:["source.sbo.acr-2020","source.sbo.wses-2018"],category:"evaluation",limitation:"CT interpretation must be integrated with clinical assessment.",population:"Adults with suspected mechanical SBO and completed CT imaging."},
{id:C2,statement:"A mechanical transition pattern does not by itself establish or exclude bowel ischemia; clinical and additional CT danger features determine concern.",sourceIds:["source.sbo.wses-2018"],category:"safety_boundary",limitation:"No single omitted sign is used to declare bowel viability.",population:"Adults with CT evidence of SBO."},
{id:C3,statement:"Peritonitis or concern for strangulation or ischemia in SBO requires urgent surgical evaluation without a routine outpatient testing delay.",sourceIds:["source.sbo.wses-2018","source.sbo.east-2012"],category:"disposition",limitation:"Stable nonoperative inpatient algorithms are outside this clinic objective.",population:"Adults with SBO and clinical danger features."}],sources:[
{id:"source.sbo.acr-2020",title:"ACR Appropriateness Criteria: Suspected Small-Bowel Obstruction",citation:"Expert Panel on Gastrointestinal Imaging; Chang KJ, Marin D, Kim DH, et al. ACR Appropriateness Criteria Suspected Small-Bowel Obstruction. J Am Coll Radiol. 2020;17(5S):S305-S314. doi:10.1016/j.jacr.2020.01.025.",organization:"American College of Radiology",authors:["Chang KJ","Marin D","Kim DH","et al."],year:2020,doi:"10.1016/j.jacr.2020.01.025",pmid:"32370974",url:"https://pubmed.ncbi.nlm.nih.gov/32370974/",sourceClass:"professional_society_guideline",licenseLabel:"Copyrighted professional-society guidance",reuseStatus:"copyrighted_targeted_verification_only",authority:"Imaging guideline used for targeted factual verification of completed CT interpretation."},
{id:"source.sbo.wses-2018",title:"Bologna guidelines for adhesive small bowel obstruction",citation:"ten Broek RPG, Krielen P, Di Saverio S, et al. Bologna guidelines for diagnosis and management of adhesive small bowel obstruction: 2017 update. World J Emerg Surg. 2018;13:24. doi:10.1186/s13017-018-0185-2.",organization:"World Society of Emergency Surgery",authors:["ten Broek RPG","Krielen P","Di Saverio S","et al."],year:2018,doi:"10.1186/s13017-018-0185-2",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC6006983/",sourceClass:"peer_reviewed_guideline",licenseLabel:"Creative Commons Attribution 4.0",reuseStatus:"cc_by_4_0",authority:"Society guideline for CT danger findings and urgent/nonoperative boundaries."},
{id:"source.sbo.east-2012",title:"Small-Bowel Obstruction, Evaluation and Management",citation:"Maung AA, Johnson DC, Piper GL, et al. Evaluation and management of small-bowel obstruction: an EAST practice management guideline. J Trauma Acute Care Surg. 2012;73(5 Suppl 4):S362-S369.",organization:"Eastern Association for the Surgery of Trauma",authors:["Maung AA","Johnson DC","Piper GL","et al."],year:2012,url:"https://www.east.org/education-resources/practice-management-guidelines/details/smallbowel-obstruction-evaluation-and-management-of",sourceClass:"professional_society_guideline",licenseLabel:"Copyrighted professional-society guidance",reuseStatus:"copyrighted_targeted_verification_only",authority:"Independent society cross-check for emergency surgical escalation."}],concepts:[
{id:A,displayName:"Recognize mechanical SBO on completed CT",learningObjective:"Recognize mechanical SBO from a completed CT transition pattern without claiming imaging alone proves ischemia.",stage:2,educationalTier:1,conceptType:"diagnosis",evidenceClaimIds:[C1,C2],variants:ct as typeof ct & [VariantSpec,VariantSpec,VariantSpec,VariantSpec]},
{id:B,displayName:"Escalate SBO danger features",learningObjective:"Send SBO with peritonitis or concern for ischemia for immediate surgical evaluation.",stage:0,educationalTier:0,conceptType:"disposition",evidenceClaimIds:[C3],variants:urgent as typeof urgent & [VariantSpec,VariantSpec,VariantSpec,VariantSpec]}]};
const f=buildFamily(spec); export const SMALL_BOWEL_OBSTRUCTION=f;
export const SMALL_BOWEL_OBSTRUCTION_AUTHORING_CONCEPTS=f.authoringConcepts, SMALL_BOWEL_OBSTRUCTION_TESTED_CONCEPTS=f.testedConcepts, SMALL_BOWEL_OBSTRUCTION_QUESTIONS=f.questions, SMALL_BOWEL_OBSTRUCTION_CASES=f.cases, SMALL_BOWEL_OBSTRUCTION_CLAIMS=f.claims, SMALL_BOWEL_OBSTRUCTION_SOURCES=f.sources, SMALL_BOWEL_OBSTRUCTION_CASE_REVIEWS=f.caseReviews, SMALL_BOWEL_OBSTRUCTION_TIMING_ENTRIES=f.timingEntries, SMALL_BOWEL_OBSTRUCTION_SERVICE_CONTRACTS=f.serviceContracts;











