import type { SourceSpec } from "./family-builder";
const copyrighted="Copyrighted guidance; targeted factual verification only" as const;
const c=(x:Omit<SourceSpec,"licenseLabel"|"reuseStatus">):SourceSpec=>({...x,licenseLabel:copyrighted,reuseStatus:"copyrighted_targeted_verification_only"});
export const SOURCES={
 hernia:c({id:"source.hernia.ehs-ahs-2020",title:"EHS/AHS umbilical and epigastric hernia guidelines",citation:"Henriksen NA, Montgomery A, Kaufmann R, et al. Guidelines for treatment of umbilical and epigastric hernias from the European Hernia Society and Americas Hernia Society. Br J Surg. 2020;107(3):171-190. doi:10.1002/bjs.11489.",organization:"European and Americas Hernia Societies",authors:["Henriksen NA","Montgomery A","Kaufmann R","et al."],year:2020,doi:"10.1002/bjs.11489",url:"https://europeanherniasociety.eu/guidelines/guidelines-for-treatment-of-umbilical-and-epigastric-hernias-from-the-european-hernia-society-and-americas-hernia-society/",sourceClass:"professional_society_guideline",authority:"Joint society guideline; evidence limitations retained."}),
 varicose1:c({id:"source.varicose.svs-avf-avls-2022",title:"SVS/AVF/AVLS varicose veins guideline Part I",citation:"Gloviczki P, Lawrence PF, Wasan SM, et al. 2022 SVS/AVF/AVLS clinical practice guidelines for management of varicose veins, Part I: Duplex Scanning and Treatment of Superficial Truncal Reflux. J Vasc Surg Venous Lymphat Disord. 2023;11(2):231-261.e6. doi:10.1016/j.jvsv.2022.09.004.",organization:"SVS/AVF/AVLS",authors:["Gloviczki P","Lawrence PF","Wasan SM","et al."],year:2023,doi:"10.1016/j.jvsv.2022.09.004",url:"https://doi.org/10.1016/j.jvsv.2022.09.004",sourceClass:"professional_society_guideline",authority:"Multisociety guideline for reflux duplex and superficial truncal reflux."}),
 varicose2:c({id:"source.varicose.svs-avf-avls-2023",title:"SVS/AVF/AVLS varicose veins guideline Part II",citation:"Gloviczki P, Lawrence PF, Wasan SM, et al. 2023 SVS/AVF/AVLS clinical practice guidelines for management of varicose veins, Part II. J Vasc Surg Venous Lymphat Disord. 2024;12(1):101670. doi:10.1016/j.jvsv.2023.08.011.",organization:"SVS/AVF/AVLS",authors:["Gloviczki P","Lawrence PF","Wasan SM","et al."],year:2024,doi:"10.1016/j.jvsv.2023.08.011",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC11523430/",sourceClass:"professional_society_guideline",authority:"Multisociety guidance for preference-sensitive intervention and conservative care."}),
 dfi:c({id:"source.dfi.iwgdf-idsa-2023",title:"IWGDF/IDSA diabetes-related foot infection guideline",citation:"Senneville E, Albalawi Z, van Asten SA, et al. IWGDF/IDSA Guidelines on the Diagnosis and Treatment of Diabetes-related Foot Infections. Clin Infect Dis. 2023;ciad527. doi:10.1093/cid/ciad527.",organization:"IWGDF and Infectious Diseases Society of America",authors:["Senneville E","Albalawi Z","van Asten SA","et al."],year:2023,doi:"10.1093/cid/ciad527",url:"https://www.idsociety.org/practice-guideline/diabetic-foot-infections/",sourceClass:"professional_society_guideline",authority:"Current intersociety guideline; single-source limitation retained."}),
 burnAba:c({id:"source.burn.aba-referral-2022",title:"ABA Guidelines for Burn Patient Referral",citation:"American Burn Association. Guidelines for Burn Patient Referral: Advice on Transfer and Consultation. 2022.",organization:"American Burn Association",authors:["American Burn Association"],year:2022,url:"https://www.ameriburn.org/burn-care-team/resources/guidelines-for-burn-patient-referral",sourceClass:"professional_society_guideline",authority:"Professional-society authority for burn depth descriptors and consultation/transfer factors."}),
 burnAha:c({id:"source.burn.aha-redcross-2024",title:"2024 Guidelines for First Aid",citation:"American Heart Association and American Red Cross. 2024 Guidelines for First Aid: Thermal Burns. 2024.",organization:"American Heart Association and American Red Cross",authors:["American Heart Association","American Red Cross"],year:2024,url:"https://cpr.heart.org/en/resuscitation-science/2024-first-aid-guidelines",sourceClass:"professional_society_guideline",authority:"Independent first-aid guideline cross-check for burn assessment and referral."}),
 hsAus:c({id:"source.hs.australasian-2025",title:"Australasian hidradenitis suppurativa management guidelines",citation:"Frew J, Smith A, Fernandez Penas P, et al. Australasian hidradenitis suppurativa management guidelines. Australas J Dermatol. 2025;66(2):75-89. doi:10.1111/ajd.14388.",organization:"Australasian Journal of Dermatology",authors:["Frew J","Smith A","Fernandez Penas P","et al."],year:2025,doi:"10.1111/ajd.14388",url:"https://doi.org/10.1111/ajd.14388",sourceClass:"peer_reviewed_guideline",authority:"Current regional guideline; used for targeted factual verification because no reusable license was confirmed."}),
 hsNa:c({id:"source.hs.north-american-2019",title:"North American HS management guidelines Part I",citation:"Alikhan A, Sayed C, Alavi A, et al. North American clinical management guidelines for hidradenitis suppurativa, Part I. J Am Acad Dermatol. 2019;81(1):76-90. doi:10.1016/j.jaad.2019.02.067.",organization:"US and Canadian Hidradenitis Suppurativa Foundations",authors:["Alikhan A","Sayed C","Alavi A","et al."],year:2019,doi:"10.1016/j.jaad.2019.02.067",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9131894/",sourceClass:"professional_society_guideline",authority:"Foundation guideline directly supporting clinical recognition and the limitation of repeated drainage."}),
 parastomal:c({id:"source.parastomal.ehs-2018",title:"EHS parastomal hernia guidelines",citation:"Antoniou SA, Agresta F, Garcia Alamino JM, et al. European Hernia Society guidelines on prevention and treatment of parastomal hernias. Hernia. 2018;22:183-198. doi:10.1007/s10029-017-1697-5.",organization:"European Hernia Society",authors:["Antoniou SA","Agresta F","Garcia Alamino JM","et al."],year:2018,doi:"10.1007/s10029-017-1697-5",url:"https://europeanherniasociety.eu/european-hernia-society-guidelines-on-prevention-and-treatment-of-parastomal-hernias/",sourceClass:"professional_society_guideline",authority:"Society guideline used only as a limited cross-check; exact management statements rely on the open mapping review."}),
 nursing:{id:"source.parastomal.nursing-2025",title:"Nursing interventions for parastomal hernia or bulge",citation:"Larsen C, Borglit TB, Leinum LR, Dreyer P. Nursing Interventions for the Management of a Stoma Complicated by a Parastomal Hernia or Bulge: A Scoping Review. J Clin Nurs. 2025;34(7):2591-2624. doi:10.1111/jocn.17671.",organization:"Journal of Clinical Nursing",authors:["Larsen C","Borglit TB","Leinum LR","Dreyer P"],year:2025,doi:"10.1111/jocn.17671",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC12181155/",sourceClass:"systematic_review",licenseLabel:"Creative Commons Attribution-NonCommercial-NoDerivatives 4.0",reuseStatus:"cc_by_nc_4_0_restricted",authority:"Scoping review; evidence is limited and often expert opinion."} satisfies SourceSpec,
 acpgbi:{id:"source.stoma.acpgbi-2021",title:"ACPGBI emergency colorectal surgery consensus guideline",citation:"Miller AS, Boyce K, Box B, et al. The Association of Coloproctology of Great Britain and Ireland consensus guidelines in emergency colorectal surgery. Colorectal Dis. 2021;23(2):476-547. doi:10.1111/codi.15503.",organization:"Association of Coloproctology of Great Britain and Ireland",authors:["Miller AS","Boyce K","Box B","et al."],year:2021,doi:"10.1111/codi.15503",pmid:"33470518",url:"https://pubmed.ncbi.nlm.nih.gov/33470518/",sourceClass:"peer_reviewed_guideline",licenseLabel:"Creative Commons Attribution-NonCommercial",reuseStatus:"cc_by_nc_4_0_restricted",authority:"Society consensus for urgent stoma-complication boundaries; low evidence grades retained."} satisfies SourceSpec,
 missto:{id:"source.ostomy.missto-wses-2023",title:"MISSTO-WSES mapping review of ostomy complications",citation:"Parini D, Bondurri A, Ferrara F, et al. Surgical management of ostomy complications: a MISSTO-WSES mapping review. World J Emerg Surg. 2023;18:48. doi:10.1186/s13017-023-00516-5.",organization:"MISSTO and World Society of Emergency Surgery",authors:["Parini D","Bondurri A","Ferrara F","et al."],year:2023,doi:"10.1186/s13017-023-00516-5",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC10563348/",sourceClass:"narrative_review",licenseLabel:"Creative Commons Attribution 4.0",reuseStatus:"cc_by_4_0",authority:"Open mapping review supporting recognition and urgent/nonurgent stoma boundaries while acknowledging limited evidence."} satisfies SourceSpec,
 gcsFaq:c({id:"source.gcs.faq-current",title:"Glasgow Coma Scale FAQ",citation:"University of Glasgow. Glasgow Coma Scale FAQ. Undated current site. Accessed September 28, 2026.",organization:"University of Glasgow",authors:["University of Glasgow"],year:null,url:"https://www.glasgowcomascale.org/faq/",sourceClass:"open_educational_resource",authority:"Official interpretive source for complete totals and not-testable reporting."}),
 gcsAid:c({id:"source.gcs.assessment-aid-current",title:"GCS Assessment Aid",citation:"Institute of Neurological Sciences NHS Greater Glasgow and Clyde; Teasdale G. GCS Assessment Aid. Current official aid. Accessed September 28, 2026.",organization:"NHS Greater Glasgow and Clyde and University of Glasgow",authors:["Sir Graham Teasdale","Institute of Neurological Sciences NHS Greater Glasgow and Clyde"],year:null,url:"https://www.glasgowcomascale.org/downloads/GCS-Assessment-Aid.pdf",sourceClass:"open_educational_resource",authority:"Official source for exact eye, verbal, and motor response-to-score mapping."}),
 isl:c({id:"source.lymphedema.isl-2023",title:"ISL 2023 consensus on peripheral lymphedema",citation:"Executive Committee of the International Society of Lymphology. The Diagnosis and Treatment of Peripheral Lymphedema: 2023 Consensus Document. Lymphology. 2023;56(4):133-151. PMID:39207406.",organization:"International Society of Lymphology",authors:["Executive Committee of the International Society of Lymphology"],year:2023,pmid:"39207406",url:"https://isl.arizona.edu/sites/default/files/2024-11/THE-DIAGNOSIS-AND-TREATMENT-OF-PERIPHERAL-LYMPHEDEMA-2023-CONSENSUS-DOCUMENT-OF-THE-INTERNATIONAL-SOCIETY-OF-LYMPHOLOGY.pdf",sourceClass:"professional_society_guideline",authority:"International consensus; uncertainty and patient-specific care retained."}),
 nci:{id:"source.lymphedema.nci-pdq-current",title:"Lymphedema PDQ Health Professional Version",citation:"National Cancer Institute PDQ Supportive and Palliative Care Editorial Board. Lymphedema (PDQ), Health Professional Version. Updated December 18, 2024. Accessed September 28, 2026.",organization:"National Cancer Institute",authors:["NCI PDQ Supportive and Palliative Care Editorial Board"],year:2024,url:"https://www.cancer.gov/about-cancer/treatment/side-effects/lymphedema/lymphedema-hp-pdq",sourceClass:"government_guidance",licenseLabel:"US government factual material; third-party exclusions apply",reuseStatus:"public_domain_conditions_apply",authority:"Government editorial synthesis for diagnosis, differential, and individualized decongestive care."} satisfies SourceSpec,
} as const;


