import { buildFamily,type FamilySpec } from "./family-builder"; import { variants } from "./spec-utils"; import { SOURCES } from "./source-catalog";
const A="claim.stoma-prolapse.assessment",U="claim.stoma-prolapse.urgent-escalation",N="claim.stoma-prolapse.nonurgent-boundary";
const assess=variants([
{slug:"longer-red-stoma",complaint:"Stoma is longer",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a loop colostomy that has elongated several centimeters beyond its usual length. The exposed bowel is pink, moist, productive, and gently reducible.",stem:"Which complication is most likely?",correct:["Stoma prolapse","Full-thickness bowel telescoping outward produces an elongated stoma."],wrong:[["Parastomal hernia","A hernia creates a bulge beside the stoma rather than elongated bowel."],["Stoma retraction","Retraction draws the stoma inward."],["Peristomal dermatitis","Dermatitis affects surrounding skin rather than stoma length."]],explanation:"Recognize prolapse and document reducibility, color, output, pain, and appliance function.",claims:[A,N]},
{slug:"intermittent-telescoping",complaint:"Stoma slides outward",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with an ileostomy that intermittently telescopes outward while standing and returns toward baseline when supine. It remains pink with normal output.",stem:"What is the most likely diagnosis?",correct:["Reducible stoma prolapse","The bowel itself elongates and remains viable and productive."],wrong:[["Parastomal hernia","A peristomal abdominal-wall bulge is not described."],["Stoma stenosis","Stenosis narrows the outlet rather than lengthening it."],["Mucocutaneous separation","Separation occurs at the skin junction without telescoping bowel."]],explanation:"The dynamic elongated bowel is a viable reducible prolapse suitable for nonemergency external assessment.",claims:[A,N]},
{slug:"swollen-dusky",complaint:"Dark swollen stoma",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a newly prolapsed stoma that is edematous, dusky, very painful, and cannot be reduced. Output has stopped.",stem:"Which assessment finding is most concerning?",correct:["Dusky, irreducible, no output","Together these findings suggest ischemic obstruction."],wrong:[["Pink color, reducibility, normal output","This bundle supports a viable nonobstructed prolapse."],["Red color, reducibility, minor bleeding","Contact bleeding with preserved output is less concerning for ischemia."],["Pink color, normal output, pouch leakage","Pouch leakage needs follow-up but does not establish obstruction."]],explanation:"Assess viability and obstruction immediately and arrange emergency surgical evaluation.",claims:[A,U],acuity:"urgent"},
{slug:"appliance-trauma",complaint:"Bleeding elongated stoma",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with an elongated prolapsed stoma that remains red and productive but rubs against the appliance and has small contact bleeding. It is reducible and not severely painful.",stem:"Which features must be documented before disposition?",correct:["Color, reducibility, output, pain, pouch fit","This set separates stable prolapse from ischemia or obstruction."],wrong:[["Length, diameter, bleeding, and operative preference","These omit viability and obstruction findings."],["Bleeding amount, diet, and stoma age","These do not complete the acute viability assessment."],["Pouch brand, wear time, and skin color","Appliance details alone omit reducibility and output."]],explanation:"A structured assessment supports nonurgent specialist care when the prolapse remains viable, reducible, and productive.",claims:[A,N]}]);
const disposition=variants([
{slug:"viable-reducible",complaint:"Longer stoma today",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a pink, moist, productive prolapsed stoma that is gently reducible. Pain is mild and the pouch can be fitted.",stem:"Which disposition is most appropriate?",correct:["Prompt stoma-surgery follow-up","A viable reducible prolapse can follow a nonemergency specialist pathway."],wrong:[["Immediate emergency operation","No ischemia, obstruction, or irreducibility is present."],["Self-monitor after reduction","Recurrence and appliance issues warrant specialist review."],["Parastomal-hernia repair referral","The identified problem is prolapse, not a peristomal fascial bulge."]],explanation:"Arrange external specialist follow-up and safety-net for color change, obstruction, severe pain, or irreducibility.",claims:[N,U]},
{slug:"recurrent-reducible",complaint:"Stoma keeps prolapsing",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with recurrent reducible prolapse, normal color and output, and increasing difficulty maintaining a pouch seal. There is no severe pain.",stem:"What is the best next step?",correct:["Nonurgent stoma-surgery referral","Recurrence and appliance difficulty warrant individualized specialist planning."],wrong:[["Immediate emergency surgical referral","The stoma is viable, reducible, and productive."],["Routine dermatology referral","The structural stoma problem needs colorectal and stoma expertise."],["Urgent obstruction admission","Normal output and reducibility do not support current obstruction."]],explanation:"Use a nonemergency external pathway while preserving emergency warning signs.",claims:[N]},
{slug:"ischemic-prolapse",complaint:"Purple painful stoma",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with a prolapsed stoma that is purple-black, exquisitely painful, swollen, and irreducible, with no output.",stem:"Which disposition is required?",correct:["Emergency surgery review","The findings suggest ischemia and obstruction."],wrong:[["Routine next-week stoma visit","Possible ischemia cannot wait."],["Outpatient appliance refitting","Pouch fit is secondary to threatened bowel viability."],["Home reduction attempts","Attempts outside emergency care risk delaying surgery."]],explanation:"Irreducible prolapse with ischemia or obstruction requires emergency surgical assessment.",claims:[U],acuity:"urgent"},
{slug:"obstructed-prolapse",complaint:"Vomiting with prolapse",presentation:"{patientName} is a {patientAge}-year-old {patientSex} who presents with an irreducible prolapsed stoma, cramping, vomiting, abdominal distention, and sharply reduced output. The bowel remains red but very edematous.",stem:"What is the safest disposition?",correct:["Emergency surgery review","Obstruction makes the irreducible prolapse an emergency even before frank necrosis."],wrong:[["Routine specialist appointment","Obstructive symptoms require immediate evaluation."],["Diet modification at home","Oral management is unsafe with vomiting and low output."],["Appliance adjustment only","Appliance care does not treat obstruction."]],explanation:"Obstruction is an emergency trigger independent of whether the stoma has already become black.",claims:[U],acuity:"urgent"}]);
const spec:FamilySpec={slug:"stoma-prolapse",label:"Stoma prolapse",pairing:{indices:[0,1],updates:["The prolapsed bowel remains pink, productive, and reducible after assessment.","The intermittent prolapse is viable and reducible but has begun to disrupt pouch fit."]},claims:[{id:A,statement:"A prolapsed stoma requires prompt assessment of reducibility, bowel viability, output or obstruction, pain, and appliance function.",sourceIds:[SOURCES.acpgbi.id,SOURCES.missto.id],category:"evaluation",limitation:"Evidence quality for many reduction techniques is low.",population:"Adults with an established stoma and elongated protruding bowel."},{id:N,statement:"A viable reducible stoma prolapse can follow a nonemergency external colorectal and stoma-specialist pathway.",sourceIds:[SOURCES.missto.id],category:"disposition",certainty:"low",limitation:"No specific reduction method or operation is prescribed.",population:"Adults with a viable reducible productive stoma prolapse."},{id:U,statement:"Irreducible stoma prolapse with ischemia or obstruction requires urgent surgical evaluation.",sourceIds:[SOURCES.acpgbi.id,SOURCES.missto.id],category:"disposition",limitation:"Low-grade evidence is retained; reduction attempts must not delay escalation.",population:"Adults with irreducible prolapse and viability or obstruction concerns."}],sources:[SOURCES.acpgbi,SOURCES.missto],concepts:[{id:"concept.stoma-prolapse.viability-obstruction-assessment",displayName:"Assess stoma prolapse",learningObjective:"Recognize stoma prolapse and assess viability, reducibility, output, pain, and appliance function.",stage:1,educationalTier:0,conceptType:"diagnosis",evidenceClaimIds:[A,N,U],variants:assess},{id:"concept.stoma-prolapse.urgent-surgical-escalation",displayName:"Escalate complicated stoma prolapse",learningObjective:"Send irreducible prolapse with ischemia or obstruction for urgent surgical evaluation.",stage:1,educationalTier:0,conceptType:"disposition",evidenceClaimIds:[N,U],variants:disposition}]};
const f=buildFamily(spec); export const STOMA_PROLAPSE=f; export const STOMA_PROLAPSE_AUTHORING_CONCEPTS=f.authoringConcepts,STOMA_PROLAPSE_TESTED_CONCEPTS=f.testedConcepts,STOMA_PROLAPSE_QUESTIONS=f.questions,STOMA_PROLAPSE_CASES=f.cases,STOMA_PROLAPSE_CLAIMS=f.claims,STOMA_PROLAPSE_SOURCES=f.sources,STOMA_PROLAPSE_CASE_REVIEWS=f.caseReviews,STOMA_PROLAPSE_TIMING_ENTRIES=f.timingEntries,STOMA_PROLAPSE_SERVICE_CONTRACTS=f.serviceContracts;






