import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';

const repo=path.resolve(import.meta.dirname,'../../..'),out=path.join(repo,'artifacts/character-movement/gs019-beanie-walk/west-candidate-v1'),probe=process.argv.includes('--probe'),phases=['01','02','03','04','05','06','07','08'];
const sha=value=>createHash('sha256').update(value).digest('hex'),save=(file,canvas)=>{const bytes=canvas.toBuffer('image/png');mkdirSync(path.dirname(path.join(out,file)),{recursive:true});writeFileSync(path.join(out,file),bytes);return{file,sha256:sha(bytes),width:canvas.width,height:canvas.height};};
const sources={first:{file:'tools/character-mapping/gs019-beanie-walk/west-first-half-v1-source.png',prompt:'tools/character-mapping/gs019-beanie-walk/west-first-half-v1-prompt.txt',cuts:[228,228,199,199]},second:{file:'tools/character-mapping/gs019-beanie-walk/west-second-half-v1-source.png',prompt:'tools/character-mapping/gs019-beanie-walk/west-second-half-v1-prompt.txt',cuts:[207,207,185,190]}};
const contract={'01':'NEAR contact foreground; FAR leg back','02':'NEAR straight support foreground; FAR heel-off behind','03':'NEAR straight support foreground; FAR bent passing behind','04':'FAR swing left behind; NEAR support foreground','05':'FAR contact; NEAR leg back foreground','06':'NEAR bent foreground with heel lifting right; FAR planted','07':'NEAR low bend foreground; FAR straight planted','08':'NEAR uncurl left foreground; FAR support behind'};
function cell(image,index){const col=index%2,row=Math.floor(index/2),x=Math.floor(col*image.width/2),y=Math.floor(row*image.height/2),w=Math.floor((col+1)*image.width/2)-x,h=Math.floor((row+1)*image.height/2)-y,c=createCanvas(w,h);c.getContext('2d').drawImage(image,x,y,w,h,0,0,w,h);return{canvas:c,cell:{x,y,width:w,height:h}};}
function largest(canvas){const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data,seen=new Uint8Array(canvas.width*canvas.height);let best=[];for(let start=0;start<seen.length;start++){if(seen[start]||data[start*4+3]<24)continue;const queue=[start],group=[];seen[start]=1;while(queue.length){const at=queue.pop(),x=at%canvas.width,y=Math.floor(at/canvas.width);group.push(at);for(const next of[x?at-1:-1,x<canvas.width-1?at+1:-1,y?at-canvas.width:-1,y<canvas.height-1?at+canvas.width:-1])if(next>=0&&!seen[next]&&data[next*4+3]>=24){seen[next]=1;queue.push(next);}}if(group.length>best.length)best=group;}const output=createCanvas(canvas.width,canvas.height),pixels=output.getContext('2d').createImageData(canvas.width,canvas.height);let left=canvas.width,top=canvas.height,right=-1,bottom=-1;for(const at of best){const x=at%canvas.width,y=Math.floor(at/canvas.width),from=at*4;for(let channel=0;channel<4;channel++)pixels.data[from+channel]=data[from+channel];left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}output.getContext('2d').putImageData(pixels,0,0);return{canvas:output,pixels:best.length,bounds:{left,top,right,bottom,width:right-left+1,height:bottom-top+1}};}
function crop(canvas){const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let left=canvas.width,top=canvas.height,right=-1,bottom=-1;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++)if(data[(y*canvas.width+x)*4+3]>=24){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}const output=createCanvas(right-left+1,bottom-top+1);output.getContext('2d').drawImage(canvas,left,top,output.width,output.height,0,0,output.width,output.height);return{canvas:output,bounds:{left,top,right,bottom,width:output.width,height:output.height}};}
function cleanBody(component,cutY){const context=component.canvas.getContext('2d');context.clearRect(0,0,component.canvas.width,cutY);const cleaned=crop(component.canvas),data=cleaned.canvas.getContext('2d').getImageData(0,0,cleaned.canvas.width,Math.min(12,cleaned.canvas.height)).data,centers=[];for(let y=0;y<Math.min(12,cleaned.canvas.height);y++){let left=cleaned.canvas.width,right=-1,count=0;for(let x=0;x<cleaned.canvas.width;x++)if(data[(y*cleaned.canvas.width+x)*4+3]>=24){left=Math.min(left,x);right=Math.max(right,x);count++;}if(count>=8)centers.push((left+right)/2);}centers.sort((a,b)=>a-b);return{...cleaned,cutY,collarAxis:centers[Math.floor(centers.length/2)],collarRows:centers.length,removedDonorRows:{top:component.bounds.top,bottom:cutY-1}};}
function resize(canvas,scale){const output=createCanvas(Math.round(canvas.width*scale),Math.round(canvas.height*scale)),context=output.getContext('2d');context.imageSmoothingEnabled=false;context.drawImage(canvas,0,0,output.width,output.height);return output;}
function geometry(canvas){const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let left=canvas.width,top=canvas.height,right=-1,bottom=-1,floorAlpha=0,belowFloorAlpha=0;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const alpha=data[(y*canvas.width+x)*4+3];if(alpha<24)continue;left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);if(y===286)floorAlpha++;if(y>286)belowFloorAlpha++;}return{bounds:{left,top,right,bottom,width:right-left+1,height:bottom-top+1},floorAlpha,belowFloorAlpha};}
const standingFile='artifacts/character-movement/brown-beanie-v1/frames/stand/west.png',headFile='tools/character-mapping/layered-pilot/brown-beanie-v1/assets/head-west-original-v1.png',standingBytes=readFileSync(path.join(repo,standingFile)),headBytes=readFileSync(path.join(repo,headFile)),standing=await loadImage(standingBytes),head=await loadImage(headBytes);
const library={};for(const[id,source]of Object.entries(sources)){const bytes=readFileSync(path.join(repo,source.file)),image=await loadImage(path.join(repo,source.file));library[id]=[];for(let index=0;index<4;index++){const extracted=cell(image,index),component=largest(extracted.canvas),body=cleanBody(component,source.cuts[index]);library[id].push({...body,cell:extracted.cell,componentPixels:component.pixels,componentBounds:component.bounds});}source.sha256=sha(bytes);source.promptSha256=sha(readFileSync(path.join(repo,source.prompt)));}
const targetSpan=286-119,scale={};for(const id of['first','second']){const spans=library[id].map(item=>item.canvas.height-1).sort((a,b)=>a-b),median=(spans[1]+spans[2])/2;scale[id]=targetSpan/median;}
const prepared={};for(const[index,phase]of phases.entries()){const id=index<4?'first':'second',source=library[id][index%4],body=resize(source.canvas,scale[id]),collarAxis=source.collarAxis*scale[id],rawX=Math.round(80-collarAxis),x=Math.max(1,Math.min(159-body.width,rawX)),y=286-(body.height-1);prepared[phase]={id,source,body,x,y,rawX,collarAxis};}
const baseline=prepared['01'],frames={},eastFrames={},authored={},measurements={};for(const phase of probe?['01','05']:phases){const item=prepared[phase],authoredFile=`authored/${phase}.png`;authored[phase]=save(authoredFile,item.body);const collar={x:item.x+item.collarAxis,y:item.y},delta={x:Math.round(collar.x-80),y:collar.y-119},headTranslation={e:-4+delta.x,f:-22+delta.y},frame=createCanvas(160,320),context=frame.getContext('2d');context.imageSmoothingEnabled=false;context.drawImage(item.body,item.x,item.y);const nativeHead=createCanvas(160,320),headContext=nativeHead.getContext('2d');headContext.imageSmoothingEnabled=false;headContext.drawImage(head,headTranslation.e,headTranslation.f);const framePixels=context.getImageData(0,0,160,320),headPixels=nativeHead.getContext('2d').getImageData(0,0,160,320).data;for(let pixel=0;pixel<160*320;pixel++)if(headPixels[pixel*4+3])framePixels.data[pixel*4+3]=0;context.putImageData(framePixels,0,0);context.drawImage(nativeHead,0,0);frames[phase]=save(`frames/west-${phase}.png`,frame);const measured=geometry(frame);measurements[phase]={sourceSheet:item.id,sourceCell:(Number(phase)-1)%4+1,sourceCellRect:item.source.cell,componentPixels:item.source.componentPixels,componentBounds:item.source.componentBounds,donorHeadRemoval:{policy:'clear every source-component pixel above the authored collar contraction before any scaling or composition',cutY:item.source.cutY,removedRows:item.source.removedDonorRows,collarRowsMeasured:item.source.collarRows},uniformScale:scale[item.id],bodyPlacement:{x:item.x,y:item.y,width:item.body.width,height:item.body.height},collar:{sourceAxis:item.source.collarAxis,scaledAxis:item.collarAxis,screen:collar,target:{x:80,y:119}},alignment:{requestedX:item.rawX,appliedX:item.x,collarResidualX:collar.x-80,collarDelta:delta},headTranslation,geometry:measured,gaitAudit:contract[phase]};const east=createCanvas(160,320),eastContext=east.getContext('2d');eastContext.translate(160,0);eastContext.scale(-1,1);eastContext.drawImage(frame,0,0);eastFrames[phase]={...save(`frames/east-${phase}.png`,east),exactHorizontalMirrorOf:frames[phase].file};}
const early=createCanvas(480,344),earlyContext=early.getContext('2d');earlyContext.fillStyle='#ded8ce';earlyContext.fillRect(0,0,early.width,early.height);earlyContext.fillStyle='#20242a';earlyContext.font='14px sans-serif';earlyContext.imageSmoothingEnabled=false;for(const[index,[label,image]]of[['Standing West',standing],['Candidate 01',await loadImage(path.join(out,frames['01'].file))],['Candidate 05',await loadImage(path.join(out,frames['05'].file))]].entries()){earlyContext.fillText(label,index*160+4,17);earlyContext.drawImage(image,index*160,24);}const neck=createCanvas(640,248),neckContext=neck.getContext('2d');neckContext.fillStyle='#ded8ce';neckContext.fillRect(0,0,neck.width,neck.height);neckContext.fillStyle='#20242a';neckContext.font='14px sans-serif';neckContext.imageSmoothingEnabled=false;for(const[index,[label,file]]of[['01 neckline 4x',frames['01'].file],['05 neckline 4x',frames['05'].file]].entries()){neckContext.fillText(label,index*320+4,17);const image=await loadImage(path.join(out,file));neckContext.drawImage(image,35,88,80,56,index*320,24,320,224);}
async function allPhaseProof(direction,records){const canvas=createCanvas(1280,344),context=canvas.getContext('2d');context.fillStyle='#ded8ce';context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle='#20242a';context.font='14px sans-serif';context.imageSmoothingEnabled=false;for(const[index,phase]of phases.entries()){context.fillText(`${direction} ${phase}`,index*160+4,17);context.drawImage(await loadImage(path.join(out,records[phase].file)),index*160,24);}return canvas;}
const proofs={early01And05Native:save('proofs/standing-01-05-native.png',early),early01And05Neck4x:save('proofs/01-05-neckline-4x.png',neck),...(probe?{}:{westAll8Native:save('proofs/west-all8-native.png',await allPhaseProof('West',frames)),eastAll8Native:save('proofs/east-all8-native.png',await allPhaseProof('East',eastFrames))})};
const manifest={schemaVersion:'gs019-beanie-walk/west-candidate-v1',status:probe?'probe-needs-parent-review':'prototype-needs-parent-review',characterId:'patient.adult.043',direction:'west',canvas:{width:160,height:320,axisX:80,nominalFloorY:287,visualSoleY:286},gamePresentation:{width:32,height:64,tileSize:24},phaseContract:{ids:phases,cadenceMs:180,anatomy:contract,auditStatus:'source silhouettes require visual near/far review; pixel validation cannot certify anatomy'},pins:{approvedStanding:{file:standingFile,sha256:sha(standingBytes)},originalHead:{file:headFile,sha256:sha(headBytes),directStandingTranslation:{e:-4,f:-22},policy:'head-only exact original source; no clothing mask'},sources},registration:{collarTarget:{x:80,y:119},visualSoleY:286,nominalFloorY:287,policy:'one nearest-neighbor uniform scale per half; each whole body is translated only; exact original head follows integer collar delta'},scaleEvidence:scale,authored,frames,eastFrames,measurements,proofs};const bytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');mkdirSync(out,{recursive:true});writeFileSync(path.join(out,probe?'probe-manifest.json':'manifest.json'),bytes);console.log(JSON.stringify({status:'PASS',mode:probe?'probe':'full',manifestSha256:sha(bytes),scale,measurements:Object.fromEntries(Object.entries(measurements).map(([phase,value])=>[phase,{cutY:value.donorHeadRemoval.cutY,collar:value.collar,headTranslation:value.headTranslation,geometry:value.geometry}])),proofs},null,2));
