import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';

const repo=path.resolve(import.meta.dirname,'../../..'),root=path.join(repo,'artifacts/character-movement/gs019-beanie-walk/west-candidate-v1'),manifestBytes=readFileSync(path.join(root,'manifest.json')),manifest=JSON.parse(manifestBytes),phases=['01','02','03','04','05','06','07','08'],errors=[];
const check=(value,message)=>{if(!value)errors.push(message);},sha=value=>createHash('sha256').update(value).digest('hex'),pixels=canvas=>canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
function cell(image,index){const col=index%2,row=Math.floor(index/2),x=Math.floor(col*image.width/2),y=Math.floor(row*image.height/2),width=Math.floor((col+1)*image.width/2)-x,height=Math.floor((row+1)*image.height/2)-y,canvas=createCanvas(width,height);canvas.getContext('2d').drawImage(image,x,y,width,height,0,0,width,height);return canvas;}
function largest(canvas){const data=pixels(canvas),seen=new Uint8Array(canvas.width*canvas.height);let best=[];for(let start=0;start<seen.length;start++){if(seen[start]||data[start*4+3]<24)continue;const queue=[start],group=[];seen[start]=1;while(queue.length){const at=queue.pop(),x=at%canvas.width,y=Math.floor(at/canvas.width);group.push(at);for(const next of[x?at-1:-1,x<canvas.width-1?at+1:-1,y?at-canvas.width:-1,y<canvas.height-1?at+canvas.width:-1])if(next>=0&&!seen[next]&&data[next*4+3]>=24){seen[next]=1;queue.push(next);}}if(group.length>best.length)best=group;}const output=createCanvas(canvas.width,canvas.height),image=output.getContext('2d').createImageData(canvas.width,canvas.height);for(const at of best)for(let channel=0;channel<4;channel++)image.data[at*4+channel]=data[at*4+channel];output.getContext('2d').putImageData(image,0,0);return output;}
function crop(canvas){const data=pixels(canvas);let left=canvas.width,top=canvas.height,right=-1,bottom=-1;for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++)if(data[(y*canvas.width+x)*4+3]>=24){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}const output=createCanvas(right-left+1,bottom-top+1);output.getContext('2d').drawImage(canvas,left,top,output.width,output.height,0,0,output.width,output.height);return output;}
function rebuildAuthored(image,index,cutY,scale){const component=largest(cell(image,index)),before=pixels(component);let removed=0;for(let y=0;y<cutY;y++)for(let x=0;x<component.width;x++)if(before[(y*component.width+x)*4+3]>=24)removed++;component.getContext('2d').clearRect(0,0,component.width,cutY);const cleaned=crop(component),output=createCanvas(Math.round(cleaned.width*scale),Math.round(cleaned.height*scale)),context=output.getContext('2d');context.imageSmoothingEnabled=false;context.drawImage(cleaned,0,0,output.width,output.height);return{canvas:output,removed};}
function geometry(data,diagonal=true){const width=160,height=320,seen=new Uint8Array(width*height),components=[];let left=width,top=height,right=-1,bottom=-1,floorAlpha=0,belowFloorAlpha=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const alpha=data[(y*width+x)*4+3];if(alpha<24)continue;left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);if(y===286)floorAlpha++;if(y>286)belowFloorAlpha++;}for(let start=0;start<seen.length;start++){if(seen[start]||data[start*4+3]<24)continue;const queue=[start];seen[start]=1;let size=0;while(queue.length){const at=queue.pop(),x=at%width,y=Math.floor(at/width);size++;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if((!dx&&!dy)||(!diagonal&&dx&&dy))continue;const nx=x+dx,ny=y+dy;if(nx<0||nx>=width||ny<0||ny>=height)continue;const next=ny*width+nx;if(!seen[next]&&data[next*4+3]>=24){seen[next]=1;queue.push(next);}}}components.push(size);}components.sort((a,b)=>b-a);return{bounds:{left,top,right,bottom},floorAlpha,belowFloorAlpha,components};}
check(manifest.schemaVersion==='gs019-beanie-walk/west-candidate-v1','schema');check(manifest.characterId==='patient.adult.043'&&manifest.direction==='west','identity/direction');check(JSON.stringify(manifest.phaseContract.ids)===JSON.stringify(phases),'phase order');check(manifest.phaseContract.cadenceMs===180,'cadence');check(manifest.canvas.width===160&&manifest.canvas.height===320&&manifest.canvas.visualSoleY===286&&manifest.canvas.nominalFloorY===287,'canvas/floor');check(manifest.gamePresentation.width===32&&manifest.gamePresentation.height===64,'game size');check(manifest.pins.originalHead.directStandingTranslation.e===-4&&manifest.pins.originalHead.directStandingTranslation.f===-22,'native head baseline');
for(const pin of[manifest.pins.approvedStanding,manifest.pins.originalHead,...Object.values(manifest.pins.sources).flatMap(source=>[source,{file:source.prompt,sha256:source.promptSha256}])])check(sha(readFileSync(path.join(repo,pin.file)))===pin.sha256,`pin ${pin.file}`);
const head=await loadImage(path.join(repo,manifest.pins.originalHead.file)),sourceImages={};for(const[id,source]of Object.entries(manifest.pins.sources))sourceImages[id]=await loadImage(path.join(repo,source.file));
let exactMirrorChannels=0,identityPixels=0,exactIdentityChannels=0,bodyChannels=0,exactBodyChannels=0,removedDonorPixels=0,minFloorAlpha=Infinity,maxBelowFloorAlpha=0,maxComponents8=0;const frameMetrics={};
for(const phase of phases){const measurement=manifest.measurements[phase],westRecord=manifest.frames[phase],eastRecord=manifest.eastFrames[phase],authoredRecord=manifest.authored[phase],source=manifest.pins.sources[measurement.sourceSheet],sourceIndex=measurement.sourceCell-1,reconstructed=rebuildAuthored(sourceImages[measurement.sourceSheet],sourceIndex,measurement.donorHeadRemoval.cutY,measurement.uniformScale);removedDonorPixels+=reconstructed.removed;const authoredImage=await loadImage(path.join(root,authoredRecord.file)),authored=createCanvas(authoredImage.width,authoredImage.height);authored.getContext('2d').drawImage(authoredImage,0,0);check(authored.width===reconstructed.canvas.width&&authored.height===reconstructed.canvas.height,`authored dimensions ${phase}`);check(Buffer.from(pixels(authored)).equals(Buffer.from(pixels(reconstructed.canvas))),`authored exact cleaned source ${phase}`);check(reconstructed.removed>5000,`substantial donor head removed ${phase}`);check(measurement.sourceSheet===(Number(phase)<=4?'first':'second'),`source half ${phase}`);check(measurement.sourceCell===((Number(phase)-1)%4)+1,`source cell ${phase}`);check(measurement.uniformScale===manifest.scaleEvidence[measurement.sourceSheet],`uniform scale ${phase}`);check(Math.abs(measurement.collar.screen.x-80)<=.51&&Math.abs(measurement.collar.screen.y-119)<=3,`collar registration ${phase}`);check(measurement.headTranslation.e===-4+measurement.alignment.collarDelta.x&&measurement.headTranslation.f===-22+measurement.alignment.collarDelta.y,`head follows integer collar ${phase}`);check(measurement.bodyPlacement.y+measurement.bodyPlacement.height-1===286,`visual sole placement ${phase}`);
  const westBytes=readFileSync(path.join(root,westRecord.file)),eastBytes=readFileSync(path.join(root,eastRecord.file)),authoredBytes=readFileSync(path.join(root,authoredRecord.file));check(sha(westBytes)===westRecord.sha256,`West hash ${phase}`);check(sha(eastBytes)===eastRecord.sha256,`East hash ${phase}`);check(sha(authoredBytes)===authoredRecord.sha256,`authored hash ${phase}`);const [westImage,eastImage]=await Promise.all([loadImage(path.join(root,westRecord.file)),loadImage(path.join(root,eastRecord.file))]);check(westImage.width===160&&westImage.height===320&&eastImage.width===160&&eastImage.height===320,`dimensions ${phase}`);const west=createCanvas(160,320),east=createCanvas(160,320),body=createCanvas(160,320),nativeHead=createCanvas(160,320);west.getContext('2d').drawImage(westImage,0,0);east.getContext('2d').drawImage(eastImage,0,0);body.getContext('2d').drawImage(authored,measurement.bodyPlacement.x,measurement.bodyPlacement.y);nativeHead.getContext('2d').drawImage(head,measurement.headTranslation.e,measurement.headTranslation.f);const westData=pixels(west),eastData=pixels(east),bodyData=pixels(body),headData=pixels(nativeHead),measured8=geometry(westData,true),measured4=geometry(westData,false);frameMetrics[phase]={connectivity8:measured8.components,connectivity4:measured4.components,bounds:measured8.bounds,floorAlpha:measured8.floorAlpha,belowFloorAlpha:measured8.belowFloorAlpha,removedDonorPixels:reconstructed.removed};check(measured8.components.length===1,`one connected silhouette ${phase}`);check(measured8.floorAlpha>0&&measured8.belowFloorAlpha===0&&measured8.bounds.bottom===286,`ground ${phase}`);check(measured8.bounds.left>0&&measured8.bounds.right<159&&measured8.bounds.top>0,`no clipping ${phase}`);minFloorAlpha=Math.min(minFloorAlpha,measured8.floorAlpha);maxBelowFloorAlpha=Math.max(maxBelowFloorAlpha,measured8.belowFloorAlpha);maxComponents8=Math.max(maxComponents8,measured8.components.length);
  for(let y=0;y<320;y++)for(let x=0;x<160;x++){const at=(y*160+x)*4,mirror=(y*160+(159-x))*4;for(let channel=0;channel<4;channel++){check(eastData[at+channel]===westData[mirror+channel],`mirror ${phase}@${x},${y},${channel}`);exactMirrorChannels++;}if(headData[at+3]){identityPixels++;for(let channel=0;channel<4;channel++)if(westData[at+channel]===headData[at+channel])exactIdentityChannels++;}else{for(let channel=0;channel<4;channel++){bodyChannels++;if(westData[at+channel]===bodyData[at+channel])exactBodyChannels++;}}if(y<measurement.bodyPlacement.y&&bodyData[at+3])check(false,`body above collar ${phase}@${x},${y}`);}
}
check(exactIdentityChannels===identityPixels*4,'all original head RGBA exact');check(exactBodyChannels===bodyChannels,'body unchanged outside exact head footprint');for(const proof of Object.values(manifest.proofs))check(sha(readFileSync(path.join(root,proof.file)))===proof.sha256,`proof ${proof.file}`);
const result={status:errors.length?'FAIL':'PASS',errors:errors.slice(0,30),anatomicalAudit:{pixelCertified:false,status:'visual-source-and-render-review-required',phases:manifest.phaseContract.anatomy,limits:'Pixel checks certify source pins, donor-head removal, scale/translation-only assembly, exact native head pixels, body preservation, connectivity, mirroring, clipping, and floor contact. They do not certify perceived near/far anatomy.'},metrics:{manifestSha256:sha(manifestBytes),exactMirrorChannels,identityPixels,exactIdentityChannels,removedDonorPixels,bodyChannels,exactBodyChannels,minFloorAlpha,maxBelowFloorAlpha,maxComponents8,frameMetrics}};writeFileSync(path.join(root,'validation.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(errors.length)process.exitCode=1;
