import * as adrenal from "./adrenal-incidentaloma";
import * as paget from "./mammary-paget-disease";
import * as ibc from "./inflammatory-breast-cancer";
import * as aaa from "./abdominal-aortic-aneurysm";
import * as fi from "./fecal-incontinence";
import * as hpylori from "./h-pylori-ulcer";
import * as diverticulitis from "./uncomplicated-diverticulitis";
import * as tgdc from "./thyroglossal-duct-cyst";
import * as prolapse from "./rectal-prolapse";
import * as eoe from "./eosinophilic-esophagitis";

export const BRIEF_EARLY_LEVELS_20260917_AUTHORING_CONCEPTS = [...adrenal.ADRENAL_INCIDENTALOMA_CONCEPTS,...paget.MAMMARY_PAGET_DISEASE_CONCEPTS,...ibc.INFLAMMATORY_BREAST_CANCER_CONCEPTS,...aaa.ABDOMINAL_AORTIC_ANEURYSM_CONCEPTS,...fi.FECAL_INCONTINENCE_CONCEPTS,...hpylori.H_PYLORI_ULCER_CONCEPTS,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_CONCEPTS,...tgdc.THYROGLOSSAL_DUCT_CYST_CONCEPTS,...prolapse.RECTAL_PROLAPSE_CONCEPTS,...eoe.EOSINOPHILIC_ESOPHAGITIS_CONCEPTS];
export const BRIEF_EARLY_LEVELS_20260917_TESTED_CONCEPTS = [...adrenal.ADRENAL_INCIDENTALOMA_TESTED_CONCEPTS,...paget.MAMMARY_PAGET_DISEASE_TESTED_CONCEPTS,...ibc.INFLAMMATORY_BREAST_CANCER_TESTED_CONCEPTS,...aaa.ABDOMINAL_AORTIC_ANEURYSM_TESTED_CONCEPTS,...fi.FECAL_INCONTINENCE_TESTED_CONCEPTS,...hpylori.H_PYLORI_ULCER_TESTED_CONCEPTS,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_TESTED_CONCEPTS,...tgdc.THYROGLOSSAL_DUCT_CYST_TESTED_CONCEPTS,...prolapse.RECTAL_PROLAPSE_TESTED_CONCEPTS,...eoe.EOSINOPHILIC_ESOPHAGITIS_TESTED_CONCEPTS];
export const BRIEF_EARLY_LEVELS_20260917_QUESTIONS = [...adrenal.ADRENAL_INCIDENTALOMA_QUESTIONS,...paget.MAMMARY_PAGET_DISEASE_QUESTIONS,...ibc.INFLAMMATORY_BREAST_CANCER_QUESTIONS,...aaa.ABDOMINAL_AORTIC_ANEURYSM_QUESTIONS,...fi.FECAL_INCONTINENCE_QUESTIONS,...hpylori.H_PYLORI_ULCER_QUESTIONS,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_QUESTIONS,...tgdc.THYROGLOSSAL_DUCT_CYST_QUESTIONS,...prolapse.RECTAL_PROLAPSE_QUESTIONS,...eoe.EOSINOPHILIC_ESOPHAGITIS_QUESTIONS];
export const BRIEF_EARLY_LEVELS_20260917_CASES = [...adrenal.ADRENAL_INCIDENTALOMA_CASES,...paget.MAMMARY_PAGET_DISEASE_CASES,...ibc.INFLAMMATORY_BREAST_CANCER_CASES,...aaa.ABDOMINAL_AORTIC_ANEURYSM_CASES,...fi.FECAL_INCONTINENCE_CASES,...hpylori.H_PYLORI_ULCER_CASES,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_CASES,...tgdc.THYROGLOSSAL_DUCT_CYST_CASES,...prolapse.RECTAL_PROLAPSE_CASES,...eoe.EOSINOPHILIC_ESOPHAGITIS_CASES];
export const BRIEF_EARLY_LEVELS_20260917_CLAIMS = [...adrenal.ADRENAL_INCIDENTALOMA_CLAIMS,...paget.MAMMARY_PAGET_DISEASE_CLAIMS,...ibc.INFLAMMATORY_BREAST_CANCER_CLAIMS,...aaa.ABDOMINAL_AORTIC_ANEURYSM_CLAIMS,...fi.FECAL_INCONTINENCE_CLAIMS,...hpylori.H_PYLORI_ULCER_CLAIMS,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_CLAIMS,...tgdc.THYROGLOSSAL_DUCT_CYST_CLAIMS,...prolapse.RECTAL_PROLAPSE_CLAIMS,...eoe.EOSINOPHILIC_ESOPHAGITIS_CLAIMS];
export const BRIEF_EARLY_LEVELS_20260917_SOURCES = [...adrenal.ADRENAL_INCIDENTALOMA_SOURCES,...paget.MAMMARY_PAGET_DISEASE_SOURCES,...ibc.INFLAMMATORY_BREAST_CANCER_SOURCES,...aaa.ABDOMINAL_AORTIC_ANEURYSM_SOURCES,...fi.FECAL_INCONTINENCE_SOURCES,...hpylori.H_PYLORI_ULCER_SOURCES,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_SOURCES,...tgdc.THYROGLOSSAL_DUCT_CYST_SOURCES,...prolapse.RECTAL_PROLAPSE_SOURCES,...eoe.EOSINOPHILIC_ESOPHAGITIS_SOURCES];
export const BRIEF_EARLY_LEVELS_20260917_CASE_REVIEWS = [...adrenal.ADRENAL_INCIDENTALOMA_CASE_REVIEWS,...paget.MAMMARY_PAGET_DISEASE_CASE_REVIEWS,...ibc.INFLAMMATORY_BREAST_CANCER_CASE_REVIEWS,...aaa.ABDOMINAL_AORTIC_ANEURYSM_CASE_REVIEWS,...fi.FECAL_INCONTINENCE_CASE_REVIEWS,...hpylori.H_PYLORI_ULCER_CASE_REVIEWS,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_CASE_REVIEWS,...tgdc.THYROGLOSSAL_DUCT_CYST_CASE_REVIEWS,...prolapse.RECTAL_PROLAPSE_CASE_REVIEWS,...eoe.EOSINOPHILIC_ESOPHAGITIS_CASE_REVIEWS];
export const BRIEF_EARLY_LEVELS_20260917_SERVICE_CONTRACTS = [...adrenal.ADRENAL_INCIDENTALOMA_SERVICE_CONTRACTS,...paget.MAMMARY_PAGET_DISEASE_SERVICE_CONTRACTS,...ibc.INFLAMMATORY_BREAST_CANCER_SERVICE_CONTRACTS,...aaa.ABDOMINAL_AORTIC_ANEURYSM_SERVICE_CONTRACTS,...fi.FECAL_INCONTINENCE_SERVICE_CONTRACTS,...hpylori.H_PYLORI_ULCER_SERVICE_CONTRACTS,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_SERVICE_CONTRACTS,...tgdc.THYROGLOSSAL_DUCT_CYST_SERVICE_CONTRACTS,...prolapse.RECTAL_PROLAPSE_SERVICE_CONTRACTS,...eoe.EOSINOPHILIC_ESOPHAGITIS_SERVICE_CONTRACTS];
export const BRIEF_EARLY_LEVELS_20260917_TIMING_ENTRIES = [...adrenal.ADRENAL_INCIDENTALOMA_TIMING_ENTRIES,...paget.MAMMARY_PAGET_DISEASE_TIMING_ENTRIES,...ibc.INFLAMMATORY_BREAST_CANCER_TIMING_ENTRIES,...aaa.ABDOMINAL_AORTIC_ANEURYSM_TIMING_ENTRIES,...fi.FECAL_INCONTINENCE_TIMING_ENTRIES,...hpylori.H_PYLORI_ULCER_TIMING_ENTRIES,...diverticulitis.UNCOMPLICATED_DIVERTICULITIS_TIMING_ENTRIES,...tgdc.THYROGLOSSAL_DUCT_CYST_TIMING_ENTRIES,...prolapse.RECTAL_PROLAPSE_TIMING_ENTRIES,...eoe.EOSINOPHILIC_ESOPHAGITIS_TIMING_ENTRIES];

export const BRIEF_EARLY_LEVELS_20260917_BATCH_MANIFEST = {
  contentVersion: "development-batch.2026-09-17.1",
  authoringConceptCount: BRIEF_EARLY_LEVELS_20260917_AUTHORING_CONCEPTS.length,
  testedConceptCount: BRIEF_EARLY_LEVELS_20260917_TESTED_CONCEPTS.length,
  questionVariantCount: BRIEF_EARLY_LEVELS_20260917_QUESTIONS.length,
  caseCount: BRIEF_EARLY_LEVELS_20260917_CASES.length,
  decisionNodeCount: BRIEF_EARLY_LEVELS_20260917_CASES.flatMap((item) => item.decisionNodes).length,
  resultGateCount: BRIEF_EARLY_LEVELS_20260917_CASES.flatMap((item) => item.decisionNodes).filter((node) => node.resultGateAfter !== null).length,
  admissionScope: "active_synthetic_unapproved_prototype",
  publicReleaseAuthorized: false,
} as const;
