import type { ClinicalSource, EvidenceClaim, QuestionVariant } from "../pilot-schema";
import type { SyntheticClinicalCase, TestedConcept } from "../schema";

type Choice = readonly [string, string, boolean];
type Spec = { conceptId: string; id: string; presentationVariantId: string; displayName: string; presentation: string; stem: string; choices: readonly Choice[]; claimIds: readonly string[] };
type SourceInput = readonly [string, string, string, string, string[], number, string | null, ClinicalSource["sourceClass"], string];
type ClaimInput = readonly [string, string, string[], EvidenceClaim["evidenceCategory"]];
const VERSION = "clinical.owner-rows-066-087-109.2026-08-31.1";
const APPROVED = { contentVersion: VERSION, reviewStatus: "clinically_approved", aiAssistedDrafting: true, lastClinicianReview: { reviewer: "Melissa Rowland, MD", reviewedOn: "2026-08-31", contentVersion: VERSION } } as const;
const METADATA = { contentVersion: VERSION, reviewStatus: "needs_clinician_review", aiAssistedDrafting: true, lastClinicianReview: null } as const;
export const ROW_066_087_109_CLINICAL_APPROVALS = [
  { id: "approval.melissa-rowland-md.owner-row-066.2026-08-31", sourceRow: 66, reviewer: "Melissa Rowland, MD", reviewedOn: "2026-08-31", contentVersion: VERSION, approvedConceptIds: ["concept.ipaa.pouchitis-common-post-ipaa-complication"], approvedPresentationVariantIds: ["1a", "1b", "1c", "1d"].map((suffix) => `presentation.ipaa.pouchitis.${suffix}`), approvedQuestionVariantIds: ["1a", "1b", "1c", "1d"].map((suffix) => `question.ipaa.pouchitis.${suffix}.v1`), approvedEvidenceClaimIds: [], approvedReleasePointIds: ["release.l0.clinic_evaluation"], runtimeAnswerShuffle: true, decision: "approved" },
  { id: "approval.melissa-rowland-md.owner-row-087.2026-08-31", sourceRow: 87, reviewer: "Melissa Rowland, MD", reviewedOn: "2026-08-31", contentVersion: VERSION, approvedConceptIds: ["concept.choledochal-cyst.type-iva-combined-duct-dilation"], approvedPresentationVariantIds: ["2a", "2b", "2c", "2d"].map((suffix) => `presentation.choledochal-cyst.type-iva.${suffix}`), approvedQuestionVariantIds: ["2a", "2b", "2c", "2d"].map((suffix) => `question.choledochal-cyst.type-iva.${suffix}.v1`), approvedEvidenceClaimIds: [], approvedReleasePointIds: ["release.l0.clinic_evaluation"], runtimeAnswerShuffle: true, decision: "approved" },
  { id: "approval.melissa-rowland-md.owner-row-109.2026-08-31", sourceRow: 109, reviewer: "Melissa Rowland, MD", reviewedOn: "2026-08-31", contentVersion: VERSION, approvedConceptIds: ["concept.anal-hsil.high-risk-hpv-association"], approvedPresentationVariantIds: ["3a", "3b", "3c", "3d"].map((suffix) => `presentation.anal-hsil.hpv.${suffix}`), approvedQuestionVariantIds: ["3a", "3b", "3c", "3d"].map((suffix) => `question.anal-hsil.hpv.${suffix}.v1`), approvedEvidenceClaimIds: [], approvedReleasePointIds: ["release.l0.clinic_evaluation"], runtimeAnswerShuffle: true, decision: "approved" },
] as const;
const CLAIMS: readonly ClaimInput[] = [
  ["claim.ipaa.pouchitis-frequency", "In the approved UC/IPAA counseling scope, pouchitis is the inflammatory pouch complication used for the frequency comparison.", ["source.barnes.aga-pouchitis.2024", "source.holubar.ascrs-uc.2021"], "epidemiology"],
  ["claim.bile-duct-cyst.type-iva-anatomy", "In the approved imaging-classification scope, Type IVA is the multiple-cystic-dilatation pattern involving both intrahepatic and extrahepatic bile ducts.", ["source.ishibashi.jscbd.2017", "source.ghotbi.bjs-bile-duct-cysts.2023"], "anatomy"],
  ["claim.anal-hsil.hrhpv-association", "In the approved pathology-follow-up scope, anal HSIL is associated with persistent high-risk HPV; HIV is not the etiologic viral answer tested here.", ["source.stier.ians-anal-screening.2024", "source.cdc.hpv-basics.current", "source.nih.nci.hpv-cancer.current"], "definition"],
] as const;
const SOURCE_DATA: readonly SourceInput[] = [
  ["source.barnes.aga-pouchitis.2024", "AGA Clinical Practice Guideline on the Management of Pouchitis and Inflammatory Pouch Disorders", "Barnes EL, Agrawal M, Syal G, et al. Gastroenterology. 2024;166(1):59-85. doi:10.1053/j.gastro.2023.10.015.", "American Gastroenterological Association", ["Barnes EL", "Agrawal M"], 2024, "10.1053/j.gastro.2023.10.015", "professional_society_guideline", "claim.ipaa.pouchitis-frequency"],
  ["source.holubar.ascrs-uc.2021", "ASCRS guideline for surgical management of ulcerative colitis", "Holubar SD, Lightner AL, Poylin V, et al. Dis Colon Rectum. 2021;64(7):783-804. doi:10.1097/DCR.0000000000002037.", "American Society of Colon and Rectal Surgeons", ["Holubar SD", "Lightner AL"], 2021, "10.1097/DCR.0000000000002037", "professional_society_guideline", "claim.ipaa.pouchitis-frequency"],
  ["source.ishibashi.jscbd.2017", "Japanese clinical practice guidelines for congenital biliary dilatation", "Ishibashi H, Shimada M, Kamisawa T, et al. J Hepatobiliary Pancreat Sci. 2017;24(1):1-16. doi:10.1002/jhbp.415.", "Japanese Study Group on Congenital Biliary Dilatation", ["Ishibashi H", "Shimada M"], 2017, "10.1002/jhbp.415", "peer_reviewed_guideline", "claim.bile-duct-cyst.type-iva-anatomy"],
  ["source.ghotbi.bjs-bile-duct-cysts.2023", "Management of extrahepatic bile duct cysts", "Ghotbi J, Yaqub S, Soreide K. Br J Surg. 2023;110(10):1252-1255. doi:10.1093/bjs/znad087.", "British Journal of Surgery", ["Ghotbi J", "Yaqub S"], 2023, "10.1093/bjs/znad087", "narrative_review", "claim.bile-duct-cyst.type-iva-anatomy"],
  ["source.stier.ians-anal-screening.2024", "International Anal Neoplasia Society consensus guidelines for anal cancer screening", "Stier EA, Clarke MA, Deshmukh AA, et al. Int J Cancer. 2024;154(10):1694-1702. doi:10.1002/ijc.34850.", "International Anal Neoplasia Society", ["Stier EA", "Clarke MA"], 2024, "10.1002/ijc.34850", "professional_society_guideline", "claim.anal-hsil.hrhpv-association"],
  ["source.cdc.hpv-basics.current", "About HPV", "U.S. Centers for Disease Control and Prevention. About HPV. Updated July 3, 2024.", "Centers for Disease Control and Prevention", ["Centers for Disease Control and Prevention"], 2024, null, "government_guidance", "claim.anal-hsil.hrhpv-association"],
  ["source.nih.nci.hpv-cancer.current", "HPV and Cancer", "National Cancer Institute. HPV and Cancer. Updated May 9, 2025.", "National Cancer Institute", ["National Cancer Institute"], 2025, null, "government_guidance", "claim.anal-hsil.hrhpv-association"],
];
export const EARLY_GAME_CLINIC_BATCH_SOURCES: ClinicalSource[] = SOURCE_DATA.map<ClinicalSource>(([id,title,completeCitation,organizationOrJournal,authors,publicationYear,doi,sourceClass,claim]) => ({ ...METADATA, id, title, completeCitation, organizationOrJournal, authors: [...authors], publicationYear, doi, pmid: null, officialUrl: doi ? `https://doi.org/${doi}` : String(id).includes("cdc") ? "https://www.cdc.gov/hpv/about/index.html" : "https://www.cancer.gov/about-cancer/causes-prevention/risk/infectious-agents/hpv-and-cancer", accessedOn: "2026-08-31", sourceClass, licenseLabel: "Targeted factual verification only", reuseStatus: "copyrighted_targeted_verification_only", reuseNotes: "Independently written factual synthesis only; do not reproduce source prose.", authorityAssessment: "Authoritative targeted factual verification retained for the approved scope.", usageRole: "evidence", evidenceClaimIds: [claim] }));
export const EARLY_GAME_CLINIC_BATCH_EVIDENCE_CLAIMS: EvidenceClaim[] = CLAIMS.map<EvidenceClaim>(([id, statement, sourceIds, evidenceCategory]) => ({ ...METADATA, id, statement, sourceIds: [...sourceIds], evidenceCategory, certainty: "moderate", limitation: "Independently authored source/claim metadata is not itself clinician approved; the exact question wording is separately approved.", applicablePopulation: "Only patients represented by the exact approved clinic variants.", lastCheckedOn: "2026-08-31" }));
export const ROW_066_CONCEPT = { id: "concept.ipaa.pouchitis-common-post-ipaa-complication", displayName: "Pouchitis after IPAA", learningObjective: "Identify pouchitis as the approved common inflammatory pouch complication after IPAA for ulcerative colitis.", earliestFacilityStage: 0, conceptType: "complication" } satisfies TestedConcept;
export const ROW_087_CONCEPT = { id: "concept.choledochal-cyst.type-iva-combined-duct-dilation", displayName: "Type IVA congenital bile duct cyst anatomy", learningObjective: "Identify Type IVA as the approved combined intrahepatic and extrahepatic cystic-dilatation pattern.", earliestFacilityStage: 0, conceptType: "anatomy" } satisfies TestedConcept;
export const ROW_109_CONCEPT = { id: "concept.anal-hsil.high-risk-hpv-association", displayName: "Anal HSIL and high-risk HPV", learningObjective: "Identify high-risk human papillomavirus as the approved etiologic association of anal HSIL.", earliestFacilityStage: 0, conceptType: "applied_science" } satisfies TestedConcept;
export const EARLY_GAME_CLINIC_BATCH_CONCEPTS = [ROW_066_CONCEPT, ROW_087_CONCEPT, ROW_109_CONCEPT] as const;
const POUCH = "Pouchitis";
const TYPE = "Type IVA includes intrahepatic and extrahepatic involvement.";
const HPV = "High-risk human papillomavirus";
const SPECS: readonly Spec[] = ([
  ["1a", "Patient with ulcerative colitis is considering restorative proctocolectomy with IPAA.", "Which pouch-related inflammatory complication should be described as the most common after this operation?", [["pouchitis","Pouchitis",true],["cuffitis","Cuffitis",false],["crohns_like_pouch","Crohn’s-like disease of the pouch",false]]],
  ["1b", "Patient with ulcerative colitis returns for long-term counseling after IPAA.", "Which inflammatory pouch disorder is encountered most commonly?", [["pouchitis","Pouchitis",true],["cuffitis","Cuffitis",false],["crohns_like_pouch","Crohn’s-like disease of the pouch",false]]],
  ["1c", "A patient with medically refractory ulcerative colitis returns for counseling after restorative proctocolectomy with IPAA.", "Among inflammatory disorders affecting the newly created pouch, which is encountered most commonly?", [["pouchitis","Pouchitis",true],["cuffitis","Cuffitis",false],["crohns_like_pouch","Crohn’s-like disease of the pouch",false]]],
  ["1d", "A patient with ulcerative colitis had IPAA several years ago and asks about recognized long-term inflammatory problems of the reconstruction.", "Which pouch-related inflammatory complication is encountered most commonly?", [["pouchitis","Pouchitis",true],["cuffitis","Cuffitis",false],["crohns_like_pouch","Crohn’s-like disease of the pouch",false]]],
 ] as readonly [string, string, string, readonly Choice[]][]).map<Spec>(([suffix,presentation,stem,choices]) => ({conceptId:ROW_066_CONCEPT.id,id:`case.ipaa.pouchitis.${suffix}`,presentationVariantId:`presentation.ipaa.pouchitis.${suffix}`,displayName:"Clinic Patient: IPAA Counseling",presentation,stem,choices,claimIds:["claim.ipaa.pouchitis-frequency"]}))
  .concat(([
    ["2a", "A middle-aged patient with intermittent abdominal pain and jaundice has MRCP showing multiple cystic dilatations involving both intrahepatic and extrahepatic bile ducts.", "Which Todani subtype fits?", [["type_iva","Type IVA",true],["type_ivb","Type IVB",false],["type_v","Type V",false]]],
    ["2b", "An adult patient has a congenital bile duct cyst (commonly called a choledochal cyst) discovered during outpatient imaging. MRCP shows multiple cystic dilatations involving intrahepatic and extrahepatic bile ducts.", "Which classification is appropriate?", [["type_iva","Type IVA",true],["type_i","Type I",false],["type_ivb","Type IVB",false]]],
    ["2c", "A patient's specialist note identifies a Type IVA congenital bile duct cyst.", "Which anatomic distribution should the clinic team expect on the reviewed imaging?", [["both","Multiple cystic dilatations involving both intrahepatic and extrahepatic bile ducts",true],["extra","Multiple extrahepatic dilatations with normal intrahepatic ducts",false],["intra","Intrahepatic dilation without extrahepatic involvement",false]]],
    ["2d", "A patient is referred after MRCP demonstrates a congenital bile duct cyst, and the clinician contrasts Type IVA with Type IVB.", "Which statement correctly identifies Type IVA?", [["both","It includes multiple cystic dilatations involving both intrahepatic and extrahepatic bile ducts",true],["extra","It is confined to multiple extrahepatic duct dilatations",false],["intra","It is confined to intrahepatic duct dilation",false]]],
  ] as readonly [string, string, string, readonly Choice[]][]).map<Spec>(([suffix,presentation,stem,choices]) => ({conceptId:ROW_087_CONCEPT.id,id:`case.choledochal-cyst.type-iva.${suffix}`,presentationVariantId:`presentation.choledochal-cyst.type-iva.${suffix}`,displayName:"Clinic Patient: Bile Duct Cyst Review",presentation,stem,choices,claimIds:["claim.bile-duct-cyst.type-iva-anatomy"]})))
  .concat(([
    ["3a", "A patient's biopsy shows anal high-grade squamous intraepithelial lesion (anal HSIL; historically high-grade AIN).", "Which viral category is etiologically associated with this lesion?", [["hrhpv","High-risk human papillomavirus",true],["hiv","Human immunodeficiency virus",false],["hcv","Hepatitis C virus",false]]],
    ["3b", "A patient with anal HSIL asks which virus is etiologically linked to this dysplastic lesion.", "Which answer is appropriate?", [["hrhpv","High-risk human papillomavirus",true],["hiv","Human immunodeficiency virus",false],["ebv","Epstein–Barr virus",false]]],
    ["3c", "A solid-organ transplant recipient has off-site pathology confirming anal HSIL.", "Which viral category is directly associated with the dysplastic lesion?", [["hrhpv","High-risk human papillomavirus",true],["bk_polyomavirus","BK polyomavirus",false],["cmv","Cytomegalovirus",false]]],
    ["3d", "Patient with a prior vulvar HSIL is evaluated for a new anal squamous intraepithelial lesion.", "Which persistent infection is the shared oncogenic association?", [["hrhpv","High-risk human papillomavirus",true],["hsv2","Herpes simplex virus type 2",false],["ebv","Epstein–Barr virus",false]]],
  ] as readonly [string, string, string, readonly Choice[]][]).map<Spec>(([suffix,presentation,stem,choices]) => ({conceptId:ROW_109_CONCEPT.id,id:`case.anal-hsil.hpv.${suffix}`,presentationVariantId:`presentation.anal-hsil.hpv.${suffix}`,displayName:"Clinic Patient: Anal Pathology Review",presentation,stem,choices,claimIds:["claim.anal-hsil.hrhpv-association"]})));
function approvedExplanation(spec: Spec): string { const correct = spec.choices.find(([, , isCorrect]) => isCorrect)![1]; return ({ "case.ipaa.pouchitis.1a": "Pouchitis is the most common complication after restorative proctocolectomy with IPAA for UC.", "case.ipaa.pouchitis.1d": "This asks frequency only; it does not diagnose the patient or introduce treatment.", "case.choledochal-cyst.type-iva.2a": TYPE, "case.choledochal-cyst.type-iva.2c": "The second pattern is IVB; intrahepatic-only disease corresponds to Type V/Caroli disease.", "case.anal-hsil.hpv.3a": "Anal HSIL is HPV-associated; this does not mean every HPV infection represents HSIL.", "case.anal-hsil.hpv.3c": "Immunosuppression is patient context; high-risk HPV is the lesion’s viral association." } as Record<string, string>)[spec.id] ?? correct; }
function node(spec: Spec) { const answers=spec.choices.map(([id,label,isCorrect])=>({id,label,isCorrect,serviceRequest:null})); const explanation = approvedExplanation(spec); return { id:`node.${spec.id.replace(/^case\./,"")}`,questionVariantId:`question.${spec.id.replace(/^case\./,"")}.v1`,primaryConceptId:spec.conceptId,stem:spec.stem,answerChoices:answers,shuffleAnswers:true,explanation,sourceLabels:["Exact question approved by Melissa Rowland, MD on 2026-08-31"],resultGateAfter:null,terminalDispositions:answers.filter(x=>!x.isCorrect).map(x=>({answerChoiceId:x.id,kind:"no_terminal_outcome" as const,consequenceNarrative:`The encounter recorded ${x.label} instead of the approved answer.`,clinicalRationale:explanation,sourceLabels:["Exact question approved by Melissa Rowland, MD on 2026-08-31"]}))}; }
export const EARLY_GAME_CLINIC_BATCH_QUESTION_VARIANTS = SPECS.map(s=>({...APPROVED,id:`question.${s.id.replace(/^case\./,"")}.v1`,conceptId:s.conceptId,stem:s.stem,answerChoices:s.choices.map(([id,label,isCorrect])=>({id,label,isCorrect,distractorRationale:isCorrect?null:"This does not match the exact approved answer."})),explanation:approvedExplanation(s),supportingEvidenceClaimIds:[...s.claimIds]})) satisfies QuestionVariant[];
export const EARLY_GAME_CLINIC_BATCH_CASES = SPECS.map(s=>({id:s.id,displayName:s.displayName,patientPresentationVariantId:s.presentationVariantId,releasePointId:"release.l0.clinic_evaluation",patientDisplayName:"Clinic Patient",chiefComplaint:"Reviewing an approved clinic teaching question",presentation:s.presentation,tutorialEligible:false,routineEligible:true,earliestFacilityStage:0,requiredClinicalSetting:"clinic",requiredCapabilityIds:[],rewardTierId:"reward.clinic_basic",sourceLabels:["Exact question approved by Melissa Rowland, MD on 2026-08-31"],decisionNodes:[node(s)],learningSummary:approvedExplanation(s)})) satisfies SyntheticClinicalCase[];
export const EARLY_GAME_CLINIC_BATCH_BLUEPRINTS = SPECS.map(s=>({id:`blueprint.${s.id.replace(/^case\./,"")}`,presentationVariantId:s.presentationVariantId,questionVariantIds:[`question.${s.id.replace(/^case\./,"")}.v1`],releasePointId:"release.l0.clinic_evaluation",earliestFacilityStage:0,requiredClinicalSetting:"clinic",requiredCapabilityIds:[]}));
