import { describe, expect, it } from "vitest";
import { validateSyntheticClinicalRelease } from "../schema";
import { SYNTHETIC_CLINICAL_RELEASE } from "../synthetic-content";
import { ROW_057_CASES, ROW_057_CONCEPTS, ROW_057_EVIDENCE_CLAIMS, ROW_057_QUESTION_VARIANTS, ROW_057_SOURCES } from "./hereditary-spherocytosis-postsplenectomy";
describe("owner row 57 hereditary-spherocytosis post-splenectomy package",()=>{
 it("records two concepts, seven variants, and seven active cases",()=>{expect(ROW_057_CONCEPTS).toHaveLength(2);expect(ROW_057_QUESTION_VARIANTS).toHaveLength(7);expect(ROW_057_CASES).toHaveLength(7);});
 it("uses three shuffled choices with one key and no services except the combined evaluation",()=>{for(const c of ROW_057_CASES){for(const n of c.decisionNodes){expect(n.answerChoices).toHaveLength(3);expect(n.answerChoices.filter(a=>a.isCorrect)).toHaveLength(1);expect(n.shuffleAnswers).toBe(true);}}const combined=ROW_057_CASES.find(c=>c.id.includes("combined"))!;expect(combined.decisionNodes[0]!.resultGateAfter).toMatchObject({resultTypeId:"service.hs.heat-damaged-rbc-scintigraphy",allowedServiceRouteIds:["route.hs.heat-damaged-rbc-scintigraphy.offsite"]});expect(combined.decisionNodes[0]!.terminalDispositions).toEqual([]);expect(combined.decisionNodes[1]!.primaryConceptId).toBe(ROW_057_CONCEPTS[1]!.id);});
 it("preserves equal displayed test services and clinical boundaries",()=>{const scintigraphy=ROW_057_QUESTION_VARIANTS.find(v=>v.id.endsWith("scintigraphy.v1"))!;expect(scintigraphy.answerChoices.map(c=>c.label)).toEqual(["Order Tc-99m heat-damaged RBC scintigraphy","Order Tc-99m sulfur-colloid scintigraphy to identify splenic tissue","Order noncontrast abdominal CT to identify splenic tissue"]);const text=JSON.stringify(ROW_057_EVIDENCE_CLAIMS);expect(text).toContain("supportive only");expect(text).toContain("Incidental tissue alone is not an indication");expect(text).toMatch(/MCV or RDW alone does not establish persistent hemolysis/i);});
 it("links approved claims to sources awaiting metadata review",()=>{expect(ROW_057_SOURCES).toHaveLength(4);expect(ROW_057_SOURCES.every(s=>s.reviewStatus==="needs_clinician_review")).toBe(true);const onkopedia=ROW_057_SOURCES.find(s=>s.id==="source.onkopedia.hereditaere-sphaerozytose.2024")!;expect(onkopedia.officialUrl).toBe("https://www.onkopedia.com/de/onkopedia/guidelines/sphaerozytose-hereditaer-kugelzellenanaemie");const iolascon=ROW_057_SOURCES.find(s=>s.id==="source.iolascon.splenectomy-hereditary-hemolytic-anemias.2017")!;expect(iolascon.authors).toHaveLength(22);expect(iolascon.authors[0]).toBe("Achille Iolascon");expect(iolascon.authors.at(-1)).toBe("Hannah Tamary");expect(iolascon.licenseLabel).toBe("Creative Commons Attribution-NonCommercial 4.0 International");expect(iolascon.reuseStatus).toBe("cc_by_nc_4_0_restricted");expect(ROW_057_EVIDENCE_CLAIMS.every(c=>c.reviewStatus==="clinically_approved")).toBe(true);});
 it("admits each case exactly once",()=>{expect(()=>validateSyntheticClinicalRelease(SYNTHETIC_CLINICAL_RELEASE)).not.toThrow();for(const c of ROW_057_CASES)expect(SYNTHETIC_CLINICAL_RELEASE.cases.filter(x=>x.id===c.id)).toHaveLength(1);});
});
