import type { ClinicalSource, EvidenceClaim, QuestionVariant } from "../pilot-schema";
import type { SyntheticClinicalCase, TestedConcept } from "../schema";

export const ROW_057_CONTENT_VERSION = "clinical.owner-row-057.2026-08-25.1";
const CLINICIAN_APPROVAL = { contentVersion: ROW_057_CONTENT_VERSION, reviewStatus: "clinically_approved", aiAssistedDrafting: true, lastClinicianReview: { reviewer: "Melissa Rowland, MD", reviewedOn: "2026-08-25", contentVersion: ROW_057_CONTENT_VERSION } } as const;
const SOURCE_METADATA_REVIEW = { contentVersion: ROW_057_CONTENT_VERSION, reviewStatus: "needs_clinician_review", aiAssistedDrafting: true, lastClinicianReview: null } as const;
const EVALUATION_CONCEPT_ID = "concept.hereditary-spherocytosis.postsplenectomy-persistent-hemolysis-evaluation";
const MANAGEMENT_CONCEPT_ID = "concept.hereditary-spherocytosis.confirmed-accessory-spleen-management";
const PERSISTENT_HEMOLYSIS_CLAIM = "claim.hereditary-spherocytosis.postsplenectomy-persistent-hemolysis-evaluation";
const HOWELL_JOLLY_CLAIM = "claim.hereditary-spherocytosis.absent-howell-jolly-supportive-clue";
const SCINTIGRAPHY_CLAIM = "claim.hereditary-spherocytosis.heat-damaged-rbc-functioning-tissue-evaluation";
const MANAGEMENT_CLAIM = "claim.hereditary-spherocytosis.confirmed-functioning-tissue-hospital-referral";
const BOUNDARY_CLAIM = "claim.hereditary-spherocytosis.postsplenectomy-boundaries";
const SOURCE_LABELS = ["Onkopedia Hereditary Spherocytosis guideline, 2024", "Iolascon et al., Haematologica, 2017", "Zamora and Schaefer, StatPearls, 2023", "MacDonald and Burrell, JNMT, 2008", "Clinically approved by Melissa Rowland, MD on 2026-08-25"] as const;

export const ROW_057_CLINICAL_APPROVAL = { id: "approval.melissa-rowland-md.owner-row-057.2026-08-25", reviewer: "Melissa Rowland, MD", reviewerRole: "Surgeon", reviewedOn: "2026-08-25", contentVersion: ROW_057_CONTENT_VERSION, sourceProvenance: { workbookFileName: "Gamify Surgery Concepts (4).xlsx", sheetName: "Sheet1", sourceRow: 57, sourceRecordKey: "owner-concept.sheet1.row-057", exactApprovalConversationDate: "2026-08-25" }, approvedConceptIds: [EVALUATION_CONCEPT_ID, MANAGEMENT_CONCEPT_ID], approvedQuestionVariantIds: ["question.hs.postsplenectomy.reassess.v1", "question.hs.postsplenectomy.howell-jolly.v1", "question.hs.postsplenectomy.scintigraphy.v1", "question.hs.postsplenectomy.reverse.v1", "question.hs.accessory-spleen.hospital-referral.v1", "question.hs.accessory-spleen.incidental.v1", "question.hs.accessory-spleen.threshold.v1"], approvedReleasePointIds: ["release.l0.clinic_evaluation"], decision: "approved" } as const;

export const ROW_057_SOURCES = [
  { ...SOURCE_METADATA_REVIEW, id: "source.onkopedia.hereditaere-sphaerozytose.2024", title: "Hereditäre Sphärozytose", completeCitation: "Wörmann B, Eber S, Goede J, Hoferer A, Schrezenmeier H, Sillaber C. Hereditäre Sphärozytose. Onkopedia Guideline. October 2024.", organizationOrJournal: "Onkopedia", authors: ["Bernhard Wörmann", "Stefan Eber", "Jeroen Goede", "Anette Hoferer", "Hubert Schrezenmeier", "Christian Sillaber"], publicationYear: 2024, doi: null, pmid: null, officialUrl: "https://www.onkopedia.com/de/onkopedia/guidelines/sphaerozytose-hereditaer-kugelzellenanaemie", accessedOn: "2026-08-25", sourceClass: "professional_society_guideline", licenseLabel: "Copyrighted professional guidance; targeted factual verification only", reuseStatus: "copyrighted_targeted_verification_only", reuseNotes: "Store independently written atomic facts and citation only; do not reproduce guidance prose, tables, or algorithms.", authorityAssessment: "Current specialist guidance supporting reassessment and accessory-spleen evaluation when hemolysis persists after splenectomy.", usageRole: "evidence", evidenceClaimIds: [PERSISTENT_HEMOLYSIS_CLAIM, MANAGEMENT_CLAIM, BOUNDARY_CLAIM] },
  { ...SOURCE_METADATA_REVIEW, id: "source.iolascon.splenectomy-hereditary-hemolytic-anemias.2017", title: "Recommendations regarding splenectomy in hereditary hemolytic anemias", completeCitation: "Iolascon A, Andolfo I, Barcellini W, Corcione F, Garçon L, De Franceschi L, Pignata C, Graziadei G, Pospisilova D, Rees DC, de Montalembert M, Rivella S, Gambale A, Russo R, Ribeiro L, Vives-Corrons J, Aguilar Martinez P, Kattamis A, Gulbis B, Cappellini MD, Roberts I, Tamary H. Recommendations regarding splenectomy in hereditary hemolytic anemias. Haematologica. 2017;102(8):1304-1313. doi:10.3324/haematol.2016.161166.", organizationOrJournal: "Haematologica", authors: ["Achille Iolascon", "Immacolata Andolfo", "Wilma Barcellini", "Francesco Corcione", "Loïc Garçon", "Lucia De Franceschi", "Claudio Pignata", "Giovanna Graziadei", "Dagmar Pospisilova", "David C. Rees", "Mariane de Montalembert", "Stefano Rivella", "Antonella Gambale", "Roberta Russo", "Leticia Ribeiro", "Jules Vives-Corrons", "Patricia Aguilar Martinez", "Antonis Kattamis", "Beatrice Gulbis", "Maria Domenica Cappellini", "Irene Roberts", "Hannah Tamary"], publicationYear: 2017, doi: "10.3324/haematol.2016.161166", pmid: "28550188", officialUrl: "https://haematologica.org/article/view/8150", accessedOn: "2026-08-25", sourceClass: "peer_reviewed_guideline", licenseLabel: "Creative Commons Attribution-NonCommercial 4.0 International", reuseStatus: "cc_by_nc_4_0_restricted", reuseNotes: "Use independently written factual synthesis with attribution for noncommercial use; do not reproduce source prose, tables, or algorithms.", authorityAssessment: "Peer-reviewed recommendations cross-checking specialist assessment of hereditary hemolytic anemia and splenectomy-related decisions.", usageRole: "cross_check", evidenceClaimIds: [PERSISTENT_HEMOLYSIS_CLAIM, MANAGEMENT_CLAIM, BOUNDARY_CLAIM] },
  { ...SOURCE_METADATA_REVIEW, id: "source.zamora.schaefer.hereditary-spherocytosis.2023", title: "Hereditary Spherocytosis", completeCitation: "Zamora EA, Schaefer CA. Hereditary Spherocytosis. [Updated 2023 Jul 4]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2026 Jan-. Bookshelf ID: NBK539797. PMID: 30969619.", organizationOrJournal: "StatPearls Publishing / NCBI Bookshelf", authors: ["Edgar A. Zamora", "Catherine A. Schaefer"], publicationYear: 2023, doi: null, pmid: "30969619", officialUrl: "https://www.ncbi.nlm.nih.gov/books/NBK539797/", accessedOn: "2026-08-25", sourceClass: "open_educational_resource", licenseLabel: "CC BY-NC-ND 4.0", reuseStatus: "cc_by_nc_4_0_restricted", reuseNotes: "Use only independently written factual synthesis and attribution; do not reproduce source prose or tables.", authorityAssessment: "NCBI Bookshelf cross-check for the limited post-splenectomy Howell-Jolly-body clue.", usageRole: "cross_check", evidenceClaimIds: [HOWELL_JOLLY_CLAIM, BOUNDARY_CLAIM] },
  { ...SOURCE_METADATA_REVIEW, id: "source.macdonald.burrell.nuclear-medicine.2008", title: "Infrequently Performed Studies in Nuclear Medicine: Part 1", completeCitation: "MacDonald A, Burrell S. Infrequently Performed Studies in Nuclear Medicine: Part 1. J Nucl Med Technol. 2008;36(3):132-143. doi:10.2967/jnmt.108.051383.", organizationOrJournal: "Journal of Nuclear Medicine Technology", authors: ["Andrew MacDonald", "Stephen Burrell"], publicationYear: 2008, doi: "10.2967/jnmt.108.051383", pmid: "18703616", officialUrl: "https://tech.snmjournals.org/content/36/3/132", accessedOn: "2026-08-25", sourceClass: "narrative_review", licenseLabel: "Copyrighted journal article; targeted factual verification only", reuseStatus: "copyrighted_targeted_verification_only", reuseNotes: "Use independently written factual synthesis only; do not reproduce source prose, images, or procedures.", authorityAssessment: "Nuclear-medicine reference supporting the approved heat-damaged RBC scintigraphy functional-tissue evaluation.", usageRole: "evidence", evidenceClaimIds: [SCINTIGRAPHY_CLAIM, BOUNDARY_CLAIM] },
] satisfies ClinicalSource[];

export const ROW_057_EVIDENCE_CLAIMS = [
  { ...CLINICIAN_APPROVAL, id: PERSISTENT_HEMOLYSIS_CLAIM, statement: "For the approved presentation of persistent anemia with biochemical hemolysis after documented total splenectomy, reassessment and evaluation for accessory splenic tissue is the selected next step.", sourceIds: ["source.onkopedia.hereditaere-sphaerozytose.2024", "source.iolascon.splenectomy-hereditary-hemolytic-anemias.2017"], evidenceCategory: "evaluation", certainty: "moderate", limitation: "MCV or RDW alone does not establish persistent hemolysis, and this narrow teaching path does not diagnose every cause of anemia after splenectomy.", applicablePopulation: "Patients matching the approved hereditary-spherocytosis post-splenectomy presentations.", lastCheckedOn: "2026-08-25" },
  { ...CLINICIAN_APPROVAL, id: HOWELL_JOLLY_CLAIM, statement: "Absent Howell-Jolly bodies after splenectomy can support suspicion of residual functioning splenic tissue.", sourceIds: ["source.zamora.schaefer.hereditary-spherocytosis.2023"], evidenceCategory: "evaluation", certainty: "moderate", limitation: "Absence is supportive only; it is not independently diagnostic and is not sufficient to select surgery.", applicablePopulation: "Approved post-splenectomy hereditary-spherocytosis presentation with continued hemolysis.", lastCheckedOn: "2026-08-25" },
  { ...CLINICIAN_APPROVAL, id: SCINTIGRAPHY_CLAIM, statement: "Tc-99m heat-damaged RBC scintigraphy is the approved functional-tissue study for the constrained presentation after hereditary spherocytosis remains supported.", sourceIds: ["source.macdonald.burrell.nuclear-medicine.2008"], evidenceCategory: "evaluation", certainty: "moderate", limitation: "The configured facility time is editorial game tuning rather than a clinical turnaround claim; this does not define a universal imaging sequence.", applicablePopulation: "Patients in the approved persistent-hemolysis functional-tissue evaluation presentation.", lastCheckedOn: "2026-08-25" },
  { ...CLINICIAN_APPROVAL, id: MANAGEMENT_CLAIM, statement: "For the approved profile with confirmed functioning accessory splenic tissue causing persistent symptomatic hereditary-spherocytosis hemolysis, referral to hospital surgery for removal is the selected management disposition.", sourceIds: ["source.onkopedia.hereditaere-sphaerozytose.2024", "source.iolascon.splenectomy-hereditary-hemolytic-anemias.2017"], evidenceCategory: "management", certainty: "moderate", limitation: "Incidental tissue alone is not an indication, and this package does not simulate hospital surgery or endorse immediate reoperation before confirmation.", applicablePopulation: "Patients matching the confirmed, symptomatic, persistent-hemolysis profile in the approved management variants.", lastCheckedOn: "2026-08-25" },
  { ...CLINICIAN_APPROVAL, id: BOUNDARY_CLAIM, statement: "The approved pathway does not use steroids, IVIG, or embolization for persistent hereditary-spherocytosis hemolysis after splenectomy.", sourceIds: ["source.onkopedia.hereditaere-sphaerozytose.2024", "source.iolascon.splenectomy-hereditary-hemolytic-anemias.2017", "source.zamora.schaefer.hereditary-spherocytosis.2023", "source.macdonald.burrell.nuclear-medicine.2008"], evidenceCategory: "safety_boundary", certainty: "moderate", limitation: "This is a scope boundary for the exact approved teaching pathway, not a broad claim about all indications for those interventions.", applicablePopulation: "The seven approved row-57 variants only.", lastCheckedOn: "2026-08-25" },
] satisfies EvidenceClaim[];

export const ROW_057_CONCEPTS = [
  { id: EVALUATION_CONCEPT_ID, displayName: "Persistent hemolysis after splenectomy evaluation", learningObjective: "For the approved persistent-hemolysis presentation after total splenectomy, reassess and evaluate for functioning accessory splenic tissue without relying on MCV, RDW, or Howell-Jolly bodies alone.", earliestFacilityStage: 0, conceptType: "workup" },
  { id: MANAGEMENT_CONCEPT_ID, displayName: "Confirmed accessory splenic tissue management", learningObjective: "For confirmed functioning accessory splenic tissue causing persistent symptomatic hemolysis, refer to hospital surgery for removal without treating incidental tissue as an indication.", earliestFacilityStage: 0, conceptType: "management" },
] satisfies TestedConcept[];

type Spec = { caseId:string; presentationId:string; questionId:string; conceptId:string; displayName:string; complaint:string; presentation:string; stem:string; choices:readonly (readonly [string,string,boolean,string|null])[] };
const EVALUATION_CHOICES = [["reassess_accessory","Reassess the diagnosis and evaluate for accessory splenic tissue",true,null],["corticosteroids","Start corticosteroids for persistent anemia without confirmation",false,null],["observation","Observe the persistent anemia without further evaluation",false,null]] as const;
const SCINTIGRAPHY_CHOICES = [["heat_damaged_rbc","Order Tc-99m heat-damaged RBC scintigraphy",true,"service.hs.heat-damaged-rbc-scintigraphy"],["sulfur_colloid","Order Tc-99m sulfur-colloid scintigraphy to identify splenic tissue",false,"service.hs.sulfur-colloid-scintigraphy"],["noncontrast_ct","Order noncontrast abdominal CT to identify splenic tissue",false,"service.hs.noncontrast-abdominal-ct"]] as const;
const SPECS = [
  { caseId:"case.hs.postsplenectomy.reassess", presentationId:"presentation.hs.postsplenectomy.reassess", questionId:"question.hs.postsplenectomy.reassess.v1", conceptId:EVALUATION_CONCEPT_ID, displayName:"Clinic Patient: Persistent Hemolysis After Splenectomy", complaint:"Persistent anemia after total splenectomy", presentation:"A patient with hereditary spherocytosis returns after documented total splenectomy with persistent anemia and biochemical hemolysis.", stem:"What is the best next step in this approved evaluation pathway?", choices:EVALUATION_CHOICES },
  { caseId:"case.hs.postsplenectomy.howell-jolly", presentationId:"presentation.hs.postsplenectomy.howell-jolly", questionId:"question.hs.postsplenectomy.howell-jolly.v1", conceptId:EVALUATION_CONCEPT_ID, displayName:"Clinic Patient: Hemolysis and Blood-Smear Review", complaint:"Ongoing hemolysis after total splenectomy", presentation:"A patient with continued hemolysis after documented total splenectomy returns after a blood-smear review reports absent Howell-Jolly bodies.", stem:"Which finding best explains this limited supportive clue?", choices:[["residual_functioning_tissue","Residual functioning splenic tissue",true,null],["expected_complete_asplenia","Expected complete asplenia after total splenectomy",false,null],["iron_deficiency","Post-splenectomy iron deficiency causing the hemolysis",false,null]] },
  { caseId:"case.hs.postsplenectomy.scintigraphy", presentationId:"presentation.hs.postsplenectomy.scintigraphy", questionId:"question.hs.postsplenectomy.scintigraphy.v1", conceptId:EVALUATION_CONCEPT_ID, displayName:"Clinic Patient: Functional Splenic-Tissue Evaluation", complaint:"Choosing a functional-tissue study", presentation:"A patient returns after hereditary spherocytosis remains supported despite persistent post-splenectomy hemolysis.", stem:"Which study best identifies functioning splenic tissue in this approved pathway?", choices:SCINTIGRAPHY_CHOICES },
  { caseId:"case.hs.postsplenectomy.reverse", presentationId:"presentation.hs.postsplenectomy.reverse", questionId:"question.hs.postsplenectomy.reverse.v1", conceptId:EVALUATION_CONCEPT_ID, displayName:"Clinic Patient: Persistent-Hemolysis Recognition", complaint:"Reviewing anemia after total splenectomy", presentation:"A patient returns after documented total splenectomy to discuss several post-treatment findings.", stem:"Which finding supports the approved persistent-hemolysis evaluation pathway?", choices:[["persistent_hemolysis","Persistent anemia with ongoing biochemical hemolysis",true,null],["stable_asplenia","Stable hemoglobin with expected Howell-Jolly bodies after splenectomy",false,null],["blood_loss","Transient anemia after documented blood loss without ongoing hemolysis",false,null]] },
  { caseId:"case.hs.accessory-spleen.hospital-referral", presentationId:"presentation.hs.accessory-spleen.hospital-referral", questionId:"question.hs.accessory-spleen.hospital-referral.v1", conceptId:MANAGEMENT_CONCEPT_ID, displayName:"Clinic Patient: Confirmed Functioning Tissue", complaint:"Confirmed functioning accessory tissue", presentation:"A patient returns after confirmation of functioning accessory splenic tissue causing persistent symptomatic hereditary-spherocytosis hemolysis.", stem:"Which management disposition fits this approved profile?", choices:[["hospital_removal","Refer to hospital surgery for removal",true,null],["embolization","Refer for embolization of the confirmed accessory tissue",false,null],["corticosteroids","Start corticosteroids for persistent hemolysis",false,null]] },
  { caseId:"case.hs.accessory-spleen.incidental", presentationId:"presentation.hs.accessory-spleen.incidental", questionId:"question.hs.accessory-spleen.incidental.v1", conceptId:MANAGEMENT_CONCEPT_ID, displayName:"Clinic Patient: Incidental Accessory Tissue", complaint:"Incidental splenic tissue finding", presentation:"A patient returns after an incidental accessory-tissue finding with stable hemoglobin and no ongoing hemolysis.", stem:"Which statement best fits this approved management boundary?", choices:[["not_indicated","Removal is not indicated solely because tissue exists",true,null],["immediate_removal","Arrange immediate removal solely because the tissue was found incidentally",false,null],["ivig","Start IVIG solely because the tissue was found incidentally",false,null]] },
  { caseId:"case.hs.accessory-spleen.threshold", presentationId:"presentation.hs.accessory-spleen.threshold", questionId:"question.hs.accessory-spleen.threshold.v1", conceptId:MANAGEMENT_CONCEPT_ID, displayName:"Clinic Patient: Referral Threshold", complaint:"Reviewing confirmed accessory tissue", presentation:"A patient returns to discuss when confirmed accessory splenic tissue changes the hospital-referral decision.", stem:"Which finding meets the approved treatment threshold?", choices:[["confirmed_symptomatic","Confirmed functioning tissue causing persistent hemolysis",true,null],["howell_jolly_alone","Absent Howell-Jolly bodies alone with persistent anemia",false,null],["incidental_resolved","An incidental splenule with resolved anemia and no hemolysis",false,null]] },
] as const satisfies readonly Spec[];
const EXPLANATION = "This approved pathway first confirms functioning accessory splenic tissue after persistent post-splenectomy hemolysis, then uses hospital-surgery referral only when confirmed tissue is causing persistent symptomatic hemolysis. It does not simulate hospital care.";
function variant(spec:Spec):QuestionVariant{return {...CLINICIAN_APPROVAL,id:spec.questionId,conceptId:spec.conceptId,stem:spec.stem,answerChoices:spec.choices.map(([id,label,isCorrect])=>({id,label,isCorrect,distractorRationale:isCorrect?null:"This does not match the approved post-splenectomy pathway."})),explanation:EXPLANATION,supportingEvidenceClaimIds:spec.conceptId===EVALUATION_CONCEPT_ID?[PERSISTENT_HEMOLYSIS_CLAIM,HOWELL_JOLLY_CLAIM,SCINTIGRAPHY_CLAIM,BOUNDARY_CLAIM]:[MANAGEMENT_CLAIM,BOUNDARY_CLAIM]};}
export const ROW_057_QUESTION_VARIANTS=SPECS.map(variant) satisfies QuestionVariant[];
const VARIANTS=new Map(ROW_057_QUESTION_VARIANTS.map(v=>[v.id,v]));
function node(spec:Spec, intermediate=false){const q=VARIANTS.get(spec.questionId)!;const answers=spec.choices.map(([id,label,isCorrect,serviceId])=>({id,label,isCorrect,serviceRequest:serviceId?{serviceId}:null}));return {id:`node.${spec.questionId.replace(/^question\./,"")}`,questionVariantId:q.id,primaryConceptId:spec.conceptId,stem:q.stem,answerChoices:answers,shuffleAnswers:true,explanation:q.explanation,sourceLabels:[...SOURCE_LABELS],resultGateAfter:intermediate?{id:"gate.hs.functioning-splenic-tissue",resultTypeId:"service.hs.heat-damaged-rbc-scintigraphy",pendingLabel:"Functional splenic-tissue study pending",resultNarrative:"The corrected functional study confirms functioning accessory splenic tissue. Persistent symptomatic hemolysis remains present.",readiness:"all" as const,allowedServiceRouteIds:["route.hs.heat-damaged-rbc-scintigraphy.offsite"]}:null,terminalDispositions:intermediate?[]:answers.filter(a=>!a.isCorrect).map(a=>({answerChoiceId:a.id,kind:"no_terminal_outcome" as const,consequenceNarrative:`The encounter recorded ${a.label} instead of the approved pathway.`,clinicalRationale:EXPLANATION,sourceLabels:[...SOURCE_LABELS]}))};}
function standalone(spec:Spec):SyntheticClinicalCase{return {id:spec.caseId,displayName:spec.displayName,patientPresentationVariantId:spec.presentationId,releasePointId:"release.l0.clinic_evaluation",patientDisplayName:"Clinic Patient",chiefComplaint:spec.complaint,presentation:spec.presentation,tutorialEligible:false,routineEligible:true,earliestFacilityStage:0,requiredClinicalSetting:"clinic",requiredCapabilityIds:[],rewardTierId:"reward.referral",sourceLabels:[...SOURCE_LABELS],decisionNodes:[node(spec)],learningSummary:EXPLANATION};}
const combinedA=SPECS[2]!;const combinedB=SPECS[4]!;
export const ROW_057_CASES=[...SPECS.filter((_,i)=>[0,1,3,4,5,6].includes(i)).map(standalone),{id:"case.hs.postsplenectomy.combined-evaluation-to-referral",displayName:"Clinic Patient: Persistent Hemolysis Follow-up",patientPresentationVariantId:"presentation.hs.postsplenectomy.combined",releasePointId:"release.l0.clinic_evaluation",patientDisplayName:"Clinic Patient",chiefComplaint:"Persistent symptomatic hemolysis after total splenectomy",presentation:"A patient with hereditary spherocytosis returns after documented total splenectomy with persistent anemia and biochemical hemolysis. The diagnosis remains supported.",tutorialEligible:false,routineEligible:true,earliestFacilityStage:0,requiredClinicalSetting:"clinic",requiredCapabilityIds:[],rewardTierId:"reward.referral",sourceLabels:[...SOURCE_LABELS],decisionNodes:[node(combinedA,true),node(combinedB)],learningSummary:EXPLANATION}] satisfies SyntheticClinicalCase[];
export const ROW_057_APPROVED_ENCOUNTER_BLUEPRINTS=[...SPECS.filter((_,i)=>[0,1,3,4,5,6].includes(i)).map(s=>({id:`blueprint.${s.questionId.replace(/^question\./,"")}`,presentationVariantId:s.presentationId,questionVariantIds:[s.questionId],releasePointId:"release.l0.clinic_evaluation",requiredClinicalSetting:"clinic",requiredCapabilityIds:[],maximumScoredDecisions:1,intermediateDecisionBehavior:"not_applicable"})),{id:"blueprint.hs.postsplenectomy.combined-evaluation-to-referral",presentationVariantId:"presentation.hs.postsplenectomy.combined",questionVariantIds:[combinedA.questionId,combinedB.questionId],releasePointId:"release.l0.clinic_evaluation",requiredClinicalSetting:"clinic",requiredCapabilityIds:[],maximumScoredDecisions:2,intermediateDecisionBehavior:"corrective_forward"}] as const;
