import type { ClinicalSource, EvidenceClaim, QuestionVariant } from "../pilot-schema";
import type { SyntheticClinicalCase, TestedConcept } from "../schema";

type SourceInput = readonly [string, string, string, string, string[], number, string | null, string | null, string];
type ClaimInput = readonly [string, string, string[], EvidenceClaim["evidenceCategory"]];

export const ROW_062_CONTENT_VERSION = "clinical.owner-row-062.2026-08-31.1";
const VERSION = ROW_062_CONTENT_VERSION;
const APPROVED={contentVersion:VERSION,reviewStatus:"clinically_approved",aiAssistedDrafting:true,lastClinicianReview:{reviewer:"Melissa Rowland, MD",reviewedOn:"2026-08-31",contentVersion:VERSION}} as const;
const METADATA={contentVersion:VERSION,reviewStatus:"needs_clinician_review",aiAssistedDrafting:true,lastClinicianReview:null} as const;
export const ROW_062_CONCEPTS=[
 {id:"concept.men2a.core-manifestation-pattern",displayName:"MEN2A manifestation pattern",learningObjective:"Recognize the approved MEN2A pattern of medullary thyroid carcinoma, pheochromocytoma, and primary hyperparathyroidism.",earliestFacilityStage:0,conceptType:"diagnosis"},
 {id:"concept.men2a.pheochromocytoma-precedes-thyroid-intervention",displayName:"Pheochromocytoma before thyroid intervention",learningObjective:"Recognize that a functioning pheochromocytoma must be excluded or addressed before thyroid intervention in the approved MEN2A scope.",earliestFacilityStage:0,conceptType:"management"},
 {id:"concept.pheochromocytoma.alpha-before-beta-blockade",displayName:"Alpha blockade before beta blockade",learningObjective:"When both are indicated for a functioning pheochromocytoma, establish alpha blockade before adding beta blockade.",earliestFacilityStage:0,conceptType:"management"},
] as const satisfies readonly TestedConcept[];
export const ROW_062_CLINICAL_APPROVAL = {
 id: "approval.melissa-rowland-md.owner-row-062.2026-08-31",
 reviewer: "Melissa Rowland, MD",
 reviewerRole: "Surgeon",
 reviewedOn: "2026-08-31",
 contentVersion: ROW_062_CONTENT_VERSION,
 sourceProvenance: { workbookFileName: "Gamify Surgery Concepts (4).xlsx", sheetName: "Sheet1", sourceRow: 62, sourceRecordKey: "owner-concept.sheet1.row-062", exactApprovalConversationDate: "2026-08-31" },
 approvedConceptIds: ROW_062_CONCEPTS.map((concept) => concept.id),
 approvedPresentationVariantIds: ["1a", "1b", "1c", "1d", "2a", "2b", "2c", "2d", "3a", "3b", "3c", "3d"].map((suffix) => `presentation.men2a.${suffix}`),
 approvedQuestionVariantIds: ["1a", "1b", "1c", "1d", "2a", "2b", "2c", "2d", "3a", "3b", "3c", "3d"].map((suffix) => `question.men2a.${suffix}.v1`),
 approvedEvidenceClaimIds: [],
 approvedReleasePointIds: ["release.l0.clinic_evaluation"],
 runtimeAnswerShuffle: true,
 decision: "approved",
 approvedElements: ["three_stable_concept_ids", "twelve_exact_patient_linked_question_variants", "keyed_answers", "exact_explanations", "level_0_clinic_evaluation_release", "runtime_answer_shuffle"],
} as const;
const SOURCE_DATA = {
 records: [
 ["source.gene-reviews.men2.2023","Multiple Endocrine Neoplasia Type 2","Eng C, Plitt G. Multiple Endocrine Neoplasia Type 2. In: GeneReviews® [Internet]. University of Washington, Seattle; updated August 10, 2023. Accessed 2026-08-31. https://www.ncbi.nlm.nih.gov/books/NBK1257/.","GeneReviews",["Charis Eng","Grace Plitt"],2023,null,"https://www.ncbi.nlm.nih.gov/books/NBK1257/","claim.men2a.manifestation-pattern"],
 ["source.ata.mtc-guideline.2015","Revised American Thyroid Association Guidelines for the Management of Medullary Thyroid Carcinoma","Wells SA Jr, Asa SL, Dralle H, et al. Thyroid. 2015;25(6):567-610. doi:10.1089/thy.2014.0335.","American Thyroid Association",["Wells SA Jr","Asa SL"],2015,"10.1089/thy.2014.0335","https://doi.org/10.1089/thy.2014.0335","claim.men2a.pheochromocytoma-priority"],
 ["source.endocrine-society.ppgl-guideline.2014","Pheochromocytoma and Paraganglioma: An Endocrine Society Clinical Practice Guideline","Lenders JWM, Duh QY, Eisenhofer G, et al. J Clin Endocrinol Metab. 2014;99(6):1915-1942. doi:10.1210/jc.2014-1498.","Endocrine Society",["Lenders JWM","Duh QY"],2014,"10.1210/jc.2014-1498","https://doi.org/10.1210/jc.2014-1498","claim.pheochromocytoma.alpha-before-beta"],
 ["source.jes.ppgl-guideline.2026","Japan Endocrine Society Clinical Practice Guideline for the Diagnosis and Management of Pheochromocytoma and Paraganglioma","Tanabe A, et al. Japan Endocrine Society Clinical Practice Guideline for the Diagnosis and Management of Pheochromocytoma and Paraganglioma. Endocr J. 2026;73(1):115-157. Epub 2025. doi:10.1507/endocrj.EJ25-0165. PMID:41083371. PMCID:PMC12819074.","Japan Endocrine Society",["Tanabe A"],2026,"10.1507/endocrj.EJ25-0165","https://pmc.ncbi.nlm.nih.gov/articles/PMC12819074/","claim.pheochromocytoma.alpha-before-beta"],
 ],
 sourceClasses: {
 "source.gene-reviews.men2.2023": "open_educational_resource",
 "source.ata.mtc-guideline.2015": "professional_society_guideline",
 "source.endocrine-society.ppgl-guideline.2014": "professional_society_guideline",
 "source.jes.ppgl-guideline.2026": "professional_society_guideline",
 },
} as const satisfies {
 records: readonly SourceInput[];
 sourceClasses: Record<string, ClinicalSource["sourceClass"]>;
};
export const ROW_062_SOURCES: ClinicalSource[]=SOURCE_DATA.records.map<ClinicalSource>(([id,title,completeCitation,organizationOrJournal,authors,publicationYear,doi,officialUrl,claim])=>({...METADATA,id,title,completeCitation,organizationOrJournal,authors:[...authors],publicationYear,doi,pmid:id === "source.jes.ppgl-guideline.2026" ? "41083371" : null,officialUrl,accessedOn:"2026-08-31",sourceClass:SOURCE_DATA.sourceClasses[id]!,licenseLabel:"Targeted factual verification only",reuseStatus:"copyrighted_targeted_verification_only",reuseNotes:"Independently written factual synthesis only; do not reproduce source prose.",authorityAssessment:"Authoritative source retained for targeted verification of the approved scope.",usageRole:"evidence",evidenceClaimIds:[claim]}));
const CLAIM_DATA: readonly ClaimInput[]=[
 ["claim.men2a.manifestation-pattern","MEN2A includes medullary thyroid carcinoma, pheochromocytoma, and primary hyperparathyroidism in the approved recognition scope.",["source.gene-reviews.men2.2023"],"definition"],
 ["claim.men2a.pheochromocytoma-priority","A functioning pheochromocytoma must be excluded or addressed before thyroid intervention in the approved MEN2A scope.",["source.ata.mtc-guideline.2015"],"management"],
 ["claim.pheochromocytoma.alpha-before-beta","When both drug classes are used for a functioning pheochromocytoma, alpha blockade is established before beta blockade is added if indicated.",["source.endocrine-society.ppgl-guideline.2014","source.jes.ppgl-guideline.2026"],"management"],
];
export const ROW_062_EVIDENCE_CLAIMS: EvidenceClaim[]=CLAIM_DATA.map<EvidenceClaim>(([id,statement,sourceIds,evidenceCategory])=>({...METADATA,id,statement,sourceIds:[...sourceIds],evidenceCategory,certainty:"high",limitation:"Independently authored source/claim metadata remains needs_clinician_review; exact question wording is separately approved.",applicablePopulation:"Only patients represented by the exact approved MEN2A clinic variants.",lastCheckedOn:"2026-08-31"}));
type S={conceptId:string; suffix:string; presentation:string; stem:string; choices:readonly (readonly [string,string,boolean])[]; claim:string};
const pattern=ROW_062_CONCEPTS[0].id, priority=ROW_062_CONCEPTS[1].id, blockade=ROW_062_CONCEPTS[2].id;
const SPECS:readonly S[]=[
 {conceptId:pattern,suffix:"1a",presentation:"An adult patient with medullary thyroid carcinoma is also found to have a pheochromocytoma and PTH-dependent hypercalcemia.",stem:"Which inherited syndrome best fits this combination?",choices:[["men1","Multiple endocrine neoplasia type 1",false],["men2a","Multiple endocrine neoplasia type 2A",true],["men2b","Multiple endocrine neoplasia type 2B",false]],claim:"claim.men2a.manifestation-pattern"},
 {conceptId:pattern,suffix:"1b",presentation:"A patient with confirmed MEN2A is being counseled after medullary thyroid carcinoma is diagnosed.",stem:"Which pair of additional manifestations belongs to the syndrome’s core pattern?",choices:[["neuromas","Mucosal neuromas and intestinal ganglioneuromatosis",false],["pheo_hpt","Pheochromocytoma and primary hyperparathyroidism",true],["pituitary_pancreas","Pituitary adenoma and pancreatic neuroendocrine tumor",false]],claim:"claim.men2a.manifestation-pattern"},
 {conceptId:pattern,suffix:"1c",presentation:"A patient from a family affected by medullary thyroid carcinoma and pheochromocytoma now has hypercalcemia with an inappropriately elevated PTH level.",stem:"Which MEN phenotype best explains this pattern?",choices:[["men2b","Multiple endocrine neoplasia type 2B",false],["men1","Multiple endocrine neoplasia type 1",false],["men2a","Multiple endocrine neoplasia type 2A",true]],claim:"claim.men2a.manifestation-pattern"},
 {conceptId:pattern,suffix:"1d",presentation:"A patient undergoing evaluation for an MEN2A phenotype has pheochromocytoma and primary hyperparathyroidism.",stem:"Which thyroid malignancy completes the characteristic disease pattern?",choices:[["follicular","Follicular thyroid carcinoma",false],["medullary","Medullary thyroid carcinoma",true],["papillary","Papillary thyroid carcinoma",false]],claim:"claim.men2a.manifestation-pattern"},
 {conceptId:priority,suffix:"2a",presentation:"A patient with MEN2A and medullary thyroid carcinoma is preparing for thyroid surgery. Testing also confirms a functioning pheochromocytoma.",stem:"Which sequence is safest?",choices:[["thyroid_first","Proceed with thyroid surgery before addressing the pheochromocytoma",false],["pheo_first","Address the pheochromocytoma before proceeding with thyroid surgery",true],["no_priority","Perform both operations without assigning either condition priority",false]],claim:"claim.men2a.pheochromocytoma-priority"},
 {conceptId:priority,suffix:"2b",presentation:"An asymptomatic patient with hereditary medullary thyroid carcinoma has completed the neck evaluation and is preparing for thyroid intervention.",stem:"Which occult condition must be excluded before proceeding?",choices:[["pheo","A functioning pheochromocytoma",true],["insulinoma","An insulin-secreting pancreatic tumor",false],["pituitary","A functioning pituitary adenoma",false]],claim:"claim.men2a.pheochromocytoma-priority"},
 {conceptId:priority,suffix:"2c",presentation:"A patient with MEN2A has both medullary thyroid carcinoma and a biochemically confirmed pheochromocytoma. The thyroid operation is already scheduled.",stem:"Which modification is most appropriate?",choices:[["proceed","Proceed with thyroid surgery because the thyroid malignancy was identified first",false],["both","Perform both operations without establishing a sequence",false],["defer","Defer thyroid surgery until the pheochromocytoma is addressed",true]],claim:"claim.men2a.pheochromocytoma-priority"},
 {conceptId:priority,suffix:"2d",presentation:"A patient with MEN2A asks why a confirmed pheochromocytoma changes the order of the planned endocrine operations.",stem:"Which explanation is most accurate?",choices:[["pathology","It can compromise interpretation of the thyroid pathology",false],["crisis","It can precipitate a dangerous perioperative catecholamine crisis",true],["healing","It can impair healing of the cervical incision",false]],claim:"claim.men2a.pheochromocytoma-priority"},
 {conceptId:blockade,suffix:"3a",presentation:"A patient with a functioning pheochromocytoma is being prepared for surgery. Because tachycardia persists, the specialist plans to use both alpha- and beta-adrenergic blockade.",stem:"Which order is appropriate?",choices:[["alpha_beta","Establish alpha blockade before adding beta blockade",true],["beta_alpha","Establish beta blockade before adding alpha blockade",false],["simultaneous","Begin alpha and beta blockade simultaneously",false]],claim:"claim.pheochromocytoma.alpha-before-beta"},
 {conceptId:blockade,suffix:"3b",presentation:"A patient with MEN2A and a functioning pheochromocytoma has a draft medication plan that starts beta blockade before alpha blockade. Both drug classes are expected to be needed.",stem:"Which correction is appropriate?",choices:[["beta_alpha","Establish beta blockade, then add alpha blockade",false],["simultaneous","Establish both forms of blockade at the same time",false],["alpha_beta","Establish alpha blockade, then add beta blockade",true]],claim:"claim.pheochromocytoma.alpha-before-beta"},
 {conceptId:blockade,suffix:"3c",presentation:"A patient with a functioning pheochromocytoma has adequate alpha blockade established, but clinically significant tachycardia persists. The specialist decides that beta blockade is indicated.",stem:"Which next step is consistent with the required sequence?",choices:[["replace","Replace alpha blockade with beta blockade",false],["add","Add beta blockade to the established alpha blockade",true],["delay","Delay beta blockade until after tumor resection",false]],claim:"claim.pheochromocytoma.alpha-before-beta"},
 {conceptId:blockade,suffix:"3d",presentation:"A patient with a functioning pheochromocytoma inadvertently receives beta blockade before alpha blockade.",stem:"Why can this be dangerous?",choices:[["tachy","Unopposed beta-adrenergic stimulation can provoke severe tachycardia",false],["hypertension","Unopposed alpha-adrenergic vasoconstriction can provoke severe hypertension",true],["hypotension","Unopposed dopaminergic vasodilation can provoke severe hypotension",false]],claim:"claim.pheochromocytoma.alpha-before-beta"},
];
function approvedExplanation(spec: S): string { const correct = spec.choices.find(([, , isCorrect]) => isCorrect)![1]; return spec.suffix === "2b" ? `${correct}. Absence of classic symptoms does not remove the perioperative concern.` : correct; }
function node(s:S){const answers=s.choices.map(([id,label,isCorrect])=>({id,label,isCorrect,serviceRequest:null}));const explanation=approvedExplanation(s);return{id:`node.men2a.${s.suffix}`,questionVariantId:`question.men2a.${s.suffix}.v1`,primaryConceptId:s.conceptId,stem:s.stem,answerChoices:answers,shuffleAnswers:true,explanation,sourceLabels:["Exact question approved by Melissa Rowland, MD on 2026-08-31"],resultGateAfter:null,terminalDispositions:answers.filter(x=>!x.isCorrect).map(x=>({answerChoiceId:x.id,kind:"no_terminal_outcome" as const,consequenceNarrative:`The encounter recorded ${x.label} instead of the approved answer.`,clinicalRationale:explanation,sourceLabels:["Exact question approved by Melissa Rowland, MD on 2026-08-31"]}))}}
export const ROW_062_QUESTION_VARIANTS=SPECS.map(s=>({...APPROVED,id:`question.men2a.${s.suffix}.v1`,conceptId:s.conceptId,stem:s.stem,answerChoices:s.choices.map(([id,label,isCorrect])=>({id,label,isCorrect,distractorRationale:isCorrect?null:"This does not match the exact approved answer."})),explanation:approvedExplanation(s),supportingEvidenceClaimIds:[s.claim]})) satisfies QuestionVariant[];
export const ROW_062_CASES=SPECS.map(s=>({id:`case.men2a.${s.suffix}`,displayName:"Clinic Patient: MEN2A Review",patientPresentationVariantId:`presentation.men2a.${s.suffix}`,releasePointId:"release.l0.clinic_evaluation",patientDisplayName:"Clinic Patient",chiefComplaint:"Reviewing an approved endocrine teaching question",presentation:s.presentation,tutorialEligible:false,routineEligible:true,earliestFacilityStage:0,requiredClinicalSetting:"clinic",requiredCapabilityIds:[],rewardTierId:"reward.clinic_basic",sourceLabels:["Exact question approved by Melissa Rowland, MD on 2026-08-31"],decisionNodes:[node(s)],learningSummary:approvedExplanation(s)})) satisfies SyntheticClinicalCase[];
export const ROW_062_APPROVED_ENCOUNTER_BLUEPRINTS=SPECS.map(s=>({id:`blueprint.men2a.${s.suffix}`,presentationVariantId:`presentation.men2a.${s.suffix}`,questionVariantIds:[`question.men2a.${s.suffix}.v1`],releasePointId:"release.l0.clinic_evaluation",earliestFacilityStage:0,requiredClinicalSetting:"clinic",requiredCapabilityIds:[]}));
