import type { ClinicalSource, EvidenceClaim, QuestionVariant } from "../pilot-schema";
import type { SyntheticClinicalCase, TestedConcept } from "../schema";

export const ROW_115_CONTENT_VERSION = "clinical.owner-row-115.2026-08-21.1";
const CLINICIAN_APPROVAL = { contentVersion: ROW_115_CONTENT_VERSION, reviewStatus: "clinically_approved", aiAssistedDrafting: true, lastClinicianReview: { reviewer: "Melissa Rowland, MD", reviewedOn: "2026-08-21", contentVersion: ROW_115_CONTENT_VERSION } } as const;
const SOURCE_METADATA_REVIEW = { contentVersion: ROW_115_CONTENT_VERSION, reviewStatus: "needs_clinician_review", aiAssistedDrafting: true, lastClinicianReview: null } as const;
const CONCEPT_ID = "concept.obstructive-jaundice.vitamin-k-coagulopathy";
const ABSORPTION_CLAIM = "claim.obstructive-jaundice.reduced-vitamin-k-absorption";
const COAGULATION_CLAIM = "claim.vitamin-k-deficiency.coagulopathy-increased-pt-inr";
const SOURCE_LABELS = ["Liu et al., obstructive jaundice review, 2023", "Mathews and Hayward, vitamin K deficiency review, 2025", "Clinically approved by Melissa Rowland, MD on 2026-08-21"] as const;

export const ROW_115_CLINICAL_APPROVAL = { id: "approval.melissa-rowland-md.owner-row-115.2026-08-21", reviewer: "Melissa Rowland, MD", reviewerRole: "Surgeon", reviewedOn: "2026-08-21", contentVersion: ROW_115_CONTENT_VERSION, sourceProvenance: { workbookFileName: "Gamify Surgery Concepts (4).xlsx", sheetName: "Sheet1", sourceRow: 115, sourceRecordKey: "owner-concept.sheet1.row-115", exactApprovalConversationDate: "2026-08-21" }, approvedConceptId: CONCEPT_ID, approvedQuestionVariantIds: ["question.obstructive-jaundice.vitamin-k.bleeding.v1", "question.obstructive-jaundice.vitamin-k.mechanism.v1", "question.obstructive-jaundice.vitamin-k.lab.v1", "question.obstructive-jaundice.vitamin-k.reverse.v1"], approvedReleasePointIds: ["release.l0.clinic_evaluation"], decision: "approved" } as const;

export const ROW_115_SOURCES = [
  { ...SOURCE_METADATA_REVIEW, id: "source.liu.obstructive-jaundice-pathophysiology.2023", title: "Pathophysiological consequences and treatment strategy of obstructive jaundice", completeCitation: "Liu JJ, Sun YM, Xu Y, Mei HW, Guo W, Li ZL. Pathophysiological consequences and treatment strategy of obstructive jaundice. World J Gastrointest Surg. 2023;15(7):1262-1276. doi:10.4240/wjgs.v15.i7.1262.", organizationOrJournal: "World Journal of Gastrointestinal Surgery", authors: ["Jun-Jian Liu", "Yi-Meng Sun", "Yan Xu", "Han-Wei Mei", "Wu Guo", "Zhong-Lian Li"], publicationYear: 2023, doi: "10.4240/wjgs.v15.i7.1262", pmid: "37555128", officialUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10405123/", accessedOn: "2026-08-21", sourceClass: "narrative_review", licenseLabel: "Creative Commons Attribution-NonCommercial 4.0 International", reuseStatus: "cc_by_nc_4_0_restricted", reuseNotes: "Use independently written factual synthesis with attribution; do not copy source prose, tables, figures, or algorithms.", authorityAssessment: "Review supporting the constrained relationship between reduced bile delivery in obstructive jaundice and impaired vitamin K absorption.", usageRole: "evidence", evidenceClaimIds: [ABSORPTION_CLAIM] },
  { ...SOURCE_METADATA_REVIEW, id: "source.mathews.hayward.vitamin-k-deficiency.2025", title: "Vitamin K Deficiency: Diagnosis and Management", completeCitation: "Mathews N, Hayward CPM. Vitamin K Deficiency: Diagnosis and Management. Ann Lab Med. 2025;45(4):358-366. doi:10.3343/alm.2024.0590.", organizationOrJournal: "Annals of Laboratory Medicine", authors: ["N. Mathews", "C. P. M. Hayward"], publicationYear: 2025, doi: "10.3343/alm.2024.0590", pmid: "40269655", officialUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12187499/", accessedOn: "2026-08-21", sourceClass: "narrative_review", licenseLabel: "Creative Commons Attribution-NonCommercial 4.0 International", reuseStatus: "cc_by_nc_4_0_restricted", reuseNotes: "Use independently written factual synthesis with attribution; do not copy source prose, tables, figures, or algorithms.", authorityAssessment: "Current review independently supporting vitamin K deficiency as a coagulopathy with prolonged PT/INR.", usageRole: "cross_check", evidenceClaimIds: [COAGULATION_CLAIM] },
] satisfies ClinicalSource[];

export const ROW_115_EVIDENCE_CLAIMS = [
  { ...CLINICIAN_APPROVAL, id: ABSORPTION_CLAIM, statement: "Reduced bile delivery in obstructive jaundice can impair intestinal vitamin K absorption.", sourceIds: ["source.liu.obstructive-jaundice-pathophysiology.2023"], evidenceCategory: "presentation", certainty: "moderate", limitation: "This does not mean every patient with obstruction develops vitamin K deficiency or bleeding.", applicablePopulation: "Patients in the approved obstructive-jaundice teaching presentations.", lastCheckedOn: "2026-08-21" },
  { ...CLINICIAN_APPROVAL, id: COAGULATION_CLAIM, statement: "Vitamin K deficiency can produce coagulation abnormalities including prolonged PT/INR and bleeding manifestations.", sourceIds: ["source.mathews.hayward.vitamin-k-deficiency.2025"], evidenceCategory: "presentation", certainty: "moderate", limitation: "This narrow concept does not establish a dose, treatment plan, timeline, or every possible cause of abnormal coagulation testing.", applicablePopulation: "Patients in the approved vitamin K-related coagulopathy presentations.", lastCheckedOn: "2026-08-21" },
] satisfies EvidenceClaim[];

export const ROW_115_CONCEPT = { id: CONCEPT_ID, displayName: "Obstructive jaundice, vitamin K, and coagulopathy", learningObjective: "Recognize the approved relationship between obstructive jaundice, reduced vitamin K absorption, and vitamin K-related coagulopathy.", earliestFacilityStage: 0, conceptType: "applied_science" } satisfies TestedConcept;

type Spec = { id:string; presentationId:string; questionId:string; displayName:string; complaint:string; presentation:string; stem:string; choices: readonly (readonly [string,string,boolean])[] };
const SPECS = [
  { id:"case.obstructive-jaundice.vitamin-k.bleeding", presentationId:"presentation.obstructive-jaundice.vitamin-k.bleeding", questionId:"question.obstructive-jaundice.vitamin-k.bleeding.v1", displayName:"Clinic Patient: Jaundice and Bruising", complaint:"Progressive jaundice with new bruising", presentation:"An adult with a confirmed distal biliary obstruction reports progressive jaundice, pruritus, dark urine, pale stools, and new bruising with minor oozing after a blood draw.", stem:"Which vitamin deficiency best explains these bleeding findings?", choices:[["vitamin_k","Vitamin K",true],["vitamin_d","Vitamin D",false],["vitamin_a","Vitamin A",false]] },
  { id:"case.obstructive-jaundice.vitamin-k.mechanism", presentationId:"presentation.obstructive-jaundice.vitamin-k.mechanism", questionId:"question.obstructive-jaundice.vitamin-k.mechanism.v1", displayName:"Clinic Patient: Jaundice and Coagulation Results", complaint:"Discussing jaundice and abnormal coagulation testing", presentation:"A patient with obstructive jaundice returns to discuss abnormal coagulation testing with normal platelets.", stem:"Which mechanism best explains this finding?", choices:[["reduced_vitamin_k_absorption","Reduced vitamin K absorption",true],["reduced_platelet_production","Reduced platelet production",false],["increased_factor_clearance","Increased clotting-factor clearance",false]] },
  { id:"case.obstructive-jaundice.vitamin-k.lab", presentationId:"presentation.obstructive-jaundice.vitamin-k.lab", questionId:"question.obstructive-jaundice.vitamin-k.lab.v1", displayName:"Clinic Patient: Jaundice Before a Procedure", complaint:"Reviewing obstructive jaundice before a procedure", presentation:"A patient with obstructive jaundice returns for evaluation before an invasive procedure.", stem:"Which laboratory finding is most consistent with this presentation?", choices:[["prolonged_pt_inr","Prolonged PT/INR",true],["isolated_thrombocytopenia","Isolated thrombocytopenia",false],["reduced_fibrinogen","Reduced fibrinogen level",false]] },
  { id:"case.obstructive-jaundice.vitamin-k.reverse", presentationId:"presentation.obstructive-jaundice.vitamin-k.reverse", questionId:"question.obstructive-jaundice.vitamin-k.reverse.v1", displayName:"Clinic Patient: Pale Stools and Gum Bleeding", complaint:"Jaundice with new gum bleeding", presentation:"A patient reports jaundice, pale stools, and new gum bleeding.", stem:"Which deficiency directly explains the bleeding?", choices:[["vitamin_k_deficiency","Vitamin K deficiency",true],["vitamin_d_deficiency","Vitamin D deficiency",false],["vitamin_a_deficiency","Vitamin A deficiency",false]] },
] as const satisfies readonly Spec[];
const EXPLANATION = "Obstructive jaundice can reduce bile delivery to the intestine and impair vitamin K absorption. Vitamin K deficiency can prolong PT/INR and cause bleeding.";
function variant(spec: Spec) { return { ...CLINICIAN_APPROVAL, id:spec.questionId, conceptId:CONCEPT_ID, stem:spec.stem, answerChoices:spec.choices.map(([id,label,isCorrect])=>({id,label,isCorrect,distractorRationale:isCorrect?null:"This does not match the approved vitamin K-related coagulopathy concept."})), explanation:EXPLANATION, supportingEvidenceClaimIds:[ABSORPTION_CLAIM,COAGULATION_CLAIM] }; }
export const ROW_115_QUESTION_VARIANTS = SPECS.map(variant) satisfies QuestionVariant[];
export const ROW_115_CASES = SPECS.map((spec) => { const answers=spec.choices.map(([id,label,isCorrect])=>({id,label,isCorrect,serviceRequest:null})); return { id:spec.id, displayName:spec.displayName, patientPresentationVariantId:spec.presentationId, releasePointId:"release.l0.clinic_evaluation", patientDisplayName:"Clinic Patient", chiefComplaint:spec.complaint, presentation:spec.presentation, tutorialEligible:false, routineEligible:true, earliestFacilityStage:0, requiredClinicalSetting:"clinic", requiredCapabilityIds:[], rewardTierId:"reward.clinic_basic", sourceLabels:[...SOURCE_LABELS], decisionNodes:[{id:`node.${spec.questionId.replace(/^question\./,"")}`,questionVariantId:spec.questionId,primaryConceptId:CONCEPT_ID,stem:spec.stem,answerChoices:answers,shuffleAnswers:true,explanation:EXPLANATION,sourceLabels:[...SOURCE_LABELS],resultGateAfter:null,terminalDispositions:answers.filter(a=>!a.isCorrect).map(a=>({answerChoiceId:a.id,kind:"no_terminal_outcome" as const,consequenceNarrative:`The encounter recorded ${a.label} instead of the approved concept.`,clinicalRationale:EXPLANATION,sourceLabels:[...SOURCE_LABELS]}))}],learningSummary:EXPLANATION }; }) satisfies SyntheticClinicalCase[];
export const ROW_115_APPROVED_ENCOUNTER_BLUEPRINTS = SPECS.map(spec=>({id:`blueprint.${spec.questionId.replace(/^question\./,"")}`,presentationVariantId:spec.presentationId,questionVariantIds:[spec.questionId],releasePointId:"release.l0.clinic_evaluation",earliestFacilityStage:0,requiredClinicalSetting:"clinic",requiredCapabilityIds:[]}));
