import { describe, expect, it } from "vitest";
import { SYNTHETIC_CLINICAL_RELEASE } from "../synthetic-content";
import { LEVEL_TWO_ROUTINE_CASE_IDS } from "./level-two-runtime";
import {
  ROW_053_APPROVED_BACKLOG,
  ROW_053_APPROVED_ENCOUNTER_BLUEPRINTS,
  ROW_053_CLINICAL_APPROVAL,
  ROW_053_CONCEPTS,
  ROW_053_EVIDENCE_CLAIMS,
  ROW_053_QUESTION_VARIANTS,
  ROW_053_SOURCES,
} from "./phyllodes-pathology-follow-up";

const RELEASE_POINT_ID = "release.l3.ambulatory_or_qi";
const REQUIRED_CLINICAL_SETTING = "clinic_preoperative_evaluation";

const EXPECTED_VARIANTS = [
  ["question.phyllodes.pathology-follow-up.v1", "presentation.phyllodes.pathology-follow-up.v1", "concept.phyllodes.benign-complete-excision", "claim.phyllodes.benign-complete-excision", "A patient has a core-biopsy diagnosis of benign phyllodes and is planning local treatment.", "Which operative plan should be discussed?", ["Complete excision of the benign phyllodes mass without a prescribed rim or fixed-width margin.", "complete excision with a fixed 5-mm margin", "observation"], "Complete excision of the benign phyllodes mass without a prescribed rim or fixed-width margin.", "benign complete excision is the approved target, not a fixed 5-mm rule."],
  ["question.phyllodes.pathology-follow-up.v2", "presentation.phyllodes.pathology-follow-up.v2", "concept.phyllodes.benign-complete-excision", "claim.phyllodes.benign-complete-excision", "A patient with benign phyllodes asks about local treatment before surgery. There is no separate concern for residual disease.", "Which plan is appropriate?", ["Complete excision of the benign phyllodes mass without a prescribed rim or fixed-width margin.", "complete excision with a fixed 1-cm margin", "observation"], "Complete excision of the benign phyllodes mass without a prescribed rim or fixed-width margin.", "benign management does not require a fixed 1-cm margin."],
  ["question.phyllodes.pathology-follow-up.v3", "presentation.phyllodes.pathology-follow-up.v3", "concept.phyllodes.benign-complete-excision", "claim.phyllodes.benign-complete-excision", "A patient has a benign phyllodes mass confirmed on pathology review and is choosing a definitive local plan.", "Which option best fits?", ["Complete excision of the benign phyllodes mass without a prescribed rim or fixed-width margin.", "complete excision with a fixed 5-mm margin", "complete excision with a fixed 1-cm margin"], "Complete excision of the benign phyllodes mass without a prescribed rim or fixed-width margin.", "this concept separates complete benign excision from fixed-width margin targets."],
  ["question.phyllodes.pathology-follow-up.v4", "presentation.phyllodes.pathology-follow-up.v4", "concept.phyllodes.benign-complete-excision", "claim.phyllodes.benign-complete-excision", "A patient with a benign phyllodes mass attends a preoperative planning visit.", "Which counseling statement is correct?", ["Complete excision of the benign phyllodes mass without a prescribed rim or fixed-width margin.", "observation", "complete excision with a fixed 1-cm margin"], "Complete excision of the benign phyllodes mass without a prescribed rim or fixed-width margin.", "observation is a plausible alternative to discuss but is not the complete-excision plan for this mass."],
  ["question.phyllodes.pathology-follow-up.v5", "presentation.phyllodes.pathology-follow-up.v5", "concept.phyllodes.benign-positive-margin-management", "claim.phyllodes.benign-positive-margin-management", "A patient has a benign phyllodes positive margin on final pathology. The review finds no concern for transected or residual tumor.", "What is the best next discussion?", ["Observation rather than mandatory re-excision.", "automatic re-excision", "routine axillary staging"], "Observation rather than mandatory re-excision.", "a positive benign margin alone does not mandate re-excision."],
  ["question.phyllodes.pathology-follow-up.v6", "presentation.phyllodes.pathology-follow-up.v6", "concept.phyllodes.benign-positive-margin-management", "claim.phyllodes.benign-positive-margin-management", "A patient with benign phyllodes has ink at one margin after complete excision. No residual lesion is suspected on pathology review.", "Which plan fits?", ["Observation rather than mandatory re-excision.", "create a fixed 5-mm margin", "perform sentinel-node staging"], "Observation rather than mandatory re-excision.", "this is a positive-margin management question, not a margin-target question."],
  ["question.phyllodes.pathology-follow-up.v7", "presentation.phyllodes.pathology-follow-up.v7", "concept.phyllodes.benign-positive-margin-management", "claim.phyllodes.benign-positive-margin-management", "Two patients return after benign phyllodes excision with a positive margin. One has no residual concern, while the other has concern that the tumor was transected.", "Which changed finding supports re-excision consideration?", ["Concern that the tumor was transected.", "no residual concern after pathology review", "nonsuspicious axillary nodes"], "Concern that the tumor was transected.", "suspected transection or residual disease is the approved exception."],
  ["question.phyllodes.pathology-follow-up.v8", "presentation.phyllodes.pathology-follow-up.v8", "concept.phyllodes.benign-positive-margin-management", "claim.phyllodes.benign-positive-margin-management", "A patient with benign phyllodes and a positive margin has a later imaging review that suggests remaining local disease.", "Which changed circumstance matters?", ["Consider re-excision for possible residual disease.", "assume every positive benign margin requires chemotherapy", "add routine sentinel-node staging"], "Consider re-excision for possible residual disease.", "the trigger is residual-disease concern, not the positive margin alone."],
  ["question.phyllodes.pathology-follow-up.v9", "presentation.phyllodes.pathology-follow-up.v9", "concept.phyllodes.borderline-margin-target", "claim.phyllodes.borderline-margin-target", "A patient is planning complete excision of a borderline phyllodes tumor.", "What margin target should guide counseling?", ["Aim for 5 mm.", "aim for 10 mm", "use no margin target"], "Aim for 5 mm.", "the approved borderline planning target is 5 mm."],
  ["question.phyllodes.pathology-follow-up.v10", "presentation.phyllodes.pathology-follow-up.v10", "concept.phyllodes.borderline-margin-target", "claim.phyllodes.borderline-margin-target", "A patient is told final pathology is borderline phyllodes before local planning.", "Which target applies?", ["Aim for 5 mm.", "aim for 1 cm", "observe without a margin goal"], "Aim for 5 mm.", "the target belongs to borderline disease."],
  ["question.phyllodes.pathology-follow-up.v11", "presentation.phyllodes.pathology-follow-up.v11", "concept.phyllodes.borderline-margin-target", "claim.phyllodes.borderline-margin-target", "A patient asks whether a 5-mm or 10-mm target applies to the planned borderline excision.", "Which answer is correct?", ["Aim for 5 mm.", "aim for 10 mm", "use no stated target"], "Aim for 5 mm.", "this tests target selection only."],
  ["question.phyllodes.pathology-follow-up.v12", "presentation.phyllodes.pathology-follow-up.v12", "concept.phyllodes.borderline-margin-target", "claim.phyllodes.borderline-margin-target", "A patient's pathology is revised from benign to borderline phyllodes before definitive planning.", "What target should be discussed?", ["Aim for 5 mm.", "aim for 10 mm", "omit a margin target"], "Aim for 5 mm.", "the classification change alters the planning target."],
  ["question.phyllodes.pathology-follow-up.v13", "presentation.phyllodes.pathology-follow-up.v13", "concept.phyllodes.borderline-close-margin-management", "claim.phyllodes.borderline-close-margin-management", "A patient returns after borderline phyllodes excision with a 2-mm margin.", "What management direction is appropriate?", ["Re-excision.", "treat the margin as automatically adequate", "routine axillary staging"], "Re-excision.", "a margin under 3 mm is in the approved re-excision category."],
  ["question.phyllodes.pathology-follow-up.v14", "presentation.phyllodes.pathology-follow-up.v14", "concept.phyllodes.borderline-close-margin-management", "claim.phyllodes.borderline-close-margin-management", "A patient has borderline phyllodes pathology with a 4-mm margin.", "What is the appropriate counseling frame?", ["Individualize the re-excision decision.", "state re-excision is never appropriate", "require axillary dissection"], "Individualize the re-excision decision.", "3 to under 5 mm is individualized."],
  ["question.phyllodes.pathology-follow-up.v15", "presentation.phyllodes.pathology-follow-up.v15", "concept.phyllodes.borderline-close-margin-management", "claim.phyllodes.borderline-close-margin-management", "A patient returns after borderline phyllodes excision with an exactly 3-mm margin.", "What counseling frame is appropriate?", ["Individualize the re-excision decision.", "state that re-excision is required because the margin is under 3 mm", "state that no margin discussion is needed"], "Individualize the re-excision decision.", "an exactly 3-mm margin enters the individualized 3-to-under-5-mm range."],
  ["question.phyllodes.pathology-follow-up.v16", "presentation.phyllodes.pathology-follow-up.v16", "concept.phyllodes.malignant-margin-target", "claim.phyllodes.malignant-margin-target", "A patient is planning local treatment for malignant phyllodes.", "What margin aim should guide counseling?", ["Aim for 10 mm.", "aim for 5 mm", "use no margin target"], "Aim for 10 mm.", "the approved malignant planning target is 10 mm."],
  ["question.phyllodes.pathology-follow-up.v17", "presentation.phyllodes.pathology-follow-up.v17", "concept.phyllodes.malignant-margin-target", "claim.phyllodes.malignant-margin-target", "A patient receives malignant phyllodes pathology after excision planning began.", "Which target now applies?", ["Aim for 10 mm.", "aim for 5 mm", "observe without a stated target"], "Aim for 10 mm.", "malignant and borderline targets differ."],
  ["question.phyllodes.pathology-follow-up.v18", "presentation.phyllodes.pathology-follow-up.v18", "concept.phyllodes.malignant-margin-target", "claim.phyllodes.malignant-margin-target", "A patient asks whether the malignant target is 5 mm or 10 mm.", "Which response is correct?", ["Aim for 10 mm.", "aim for 5 mm", "omit a target"], "Aim for 10 mm.", "this tests the target only."],
  ["question.phyllodes.pathology-follow-up.v19", "presentation.phyllodes.pathology-follow-up.v19", "concept.phyllodes.malignant-margin-target", "claim.phyllodes.malignant-margin-target", "A patient's pathology is revised from borderline to malignant phyllodes before further planning.", "What margin aim should be used?", ["Aim for 10 mm.", "aim for 5 mm", "decide from node examination alone"], "Aim for 10 mm.", "the malignant classification changes the planning target."],
  ["question.phyllodes.pathology-follow-up.v20", "presentation.phyllodes.pathology-follow-up.v20", "concept.phyllodes.malignant-close-margin-management", "claim.phyllodes.malignant-close-margin-management", "A patient returns after malignant phyllodes excision with a 4-mm margin.", "What is the recommended direction?", ["Re-excision.", "surveillance without a risk/benefit discussion", "routine sentinel-node staging"], "Re-excision.", "a margin under 5 mm is in the re-excision category."],
  ["question.phyllodes.pathology-follow-up.v21", "presentation.phyllodes.pathology-follow-up.v21", "concept.phyllodes.malignant-close-margin-management", "claim.phyllodes.malignant-close-margin-management", "A patient has malignant phyllodes pathology with a 7-mm margin.", "What counseling is appropriate?", ["Recommend re-excision while discussing surveillance only after explicit risk/benefit review.", "state surveillance is automatically equivalent", "state no further local discussion is needed"], "Recommend re-excision while discussing surveillance only after explicit risk/benefit review.", "5 to under 10 mm has recommended re-excision, with limited discussed surveillance consideration."],
  ["question.phyllodes.pathology-follow-up.v22", "presentation.phyllodes.pathology-follow-up.v22", "concept.phyllodes.malignant-close-margin-management", "claim.phyllodes.malignant-close-margin-management", "A patient with malignant phyllodes returns after pathology reports a 7-mm margin. The patient asks how the 10-mm target and close-margin intervals should be understood.", "Which explanation is correct?", ["They are consensus management thresholds with evidence limitations, not biological cliffs.", "they are fixed biological cutoffs that determine recurrence for every patient", "they eliminate the need for individualized clinical discussion"], "They are consensus management thresholds with evidence limitations, not biological cliffs.", "the target and intervals guide management but retain evidence and consensus limitations."],
  ["question.phyllodes.pathology-follow-up.v23", "presentation.phyllodes.pathology-follow-up.v23", "concept.phyllodes.hematogenous-spread-pattern", "claim.phyllodes.hematogenous-spread-pattern", "A patient with malignant phyllodes asks about the usual metastatic route during pathology follow-up.", "Which explanation is correct?", ["Predominantly hematogenous spread.", "predominantly nodal spread", "spread only by direct skin extension"], "Predominantly hematogenous spread.", "nodal spread is rare relative to hematogenous spread."],
  ["question.phyllodes.pathology-follow-up.v24", "presentation.phyllodes.pathology-follow-up.v24", "concept.phyllodes.hematogenous-spread-pattern", "claim.phyllodes.hematogenous-spread-pattern", "A patient reviews malignant phyllodes pathology with no suspicious nodes.", "Which spread-pattern statement remains appropriate?", ["Predominantly hematogenous spread.", "routine regional-nodal spread", "a route determined by margin width"], "Predominantly hematogenous spread.", "local margin findings do not define the predominant spread route."],
  ["question.phyllodes.pathology-follow-up.v25", "presentation.phyllodes.pathology-follow-up.v25", "concept.phyllodes.hematogenous-spread-pattern", "claim.phyllodes.hematogenous-spread-pattern", "A patient asks why routine nodal procedures are not assumed in phyllodes counseling.", "Which pattern supports that boundary?", ["Nodal spread is rare relative to hematogenous spread.", "nodal spread is expected in every case", "nodal spread is the only metastatic route"], "Nodal spread is rare relative to hematogenous spread.", "this is a pattern statement, not an individual prognosis."],
  ["question.phyllodes.pathology-follow-up.v26", "presentation.phyllodes.pathology-follow-up.v26", "concept.phyllodes.hematogenous-spread-pattern", "claim.phyllodes.hematogenous-spread-pattern", "A patient with malignant phyllodes has a stable outpatient pathology review after complete local planning.", "Which route should not be presented as the usual route?", ["Predominantly nodal spread.", "predominantly hematogenous spread", "rare nodal involvement"], "Predominantly nodal spread.", "routine nodal spread is not the usual pattern."],
  ["question.phyllodes.pathology-follow-up.v27", "presentation.phyllodes.pathology-follow-up.v27", "concept.phyllodes.no-routine-axillary-staging", "claim.phyllodes.no-routine-axillary-staging", "A patient with borderline phyllodes has no suspicious axillary nodes on examination or imaging.", "What axillary plan is appropriate?", ["No routine sentinel-node or axillary staging.", "routine sentinel-node biopsy", "routine axillary dissection"], "No routine sentinel-node or axillary staging.", "nonsuspicious nodes do not justify routine staging."],
  ["question.phyllodes.pathology-follow-up.v28", "presentation.phyllodes.pathology-follow-up.v28", "concept.phyllodes.no-routine-axillary-staging", "claim.phyllodes.no-routine-axillary-staging", "A patient with benign phyllodes has a stable pathology follow-up and nonsuspicious nodes.", "Which plan fits?", ["No routine sentinel-node or axillary staging.", "sentinel-node biopsy because it is a breast tumor", "axillary dissection because pathology is available"], "No routine sentinel-node or axillary staging.", "this boundary applies across phyllodes subgroups when nodes are nonsuspicious."],
  ["question.phyllodes.pathology-follow-up.v29", "presentation.phyllodes.pathology-follow-up.v29", "concept.phyllodes.no-routine-axillary-staging", "claim.phyllodes.no-routine-axillary-staging", "A patient has malignant phyllodes treated with mastectomy, and the axilla remains nonsuspicious on examination and imaging.", "What axillary plan is appropriate?", ["No routine sentinel-node or axillary staging.", "add sentinel-node biopsy because the patient had mastectomy", "add axillary dissection because disease is malignant"], "No routine sentinel-node or axillary staging.", "mastectomy and malignant pathology do not create a routine staging indication when the axilla is nonsuspicious."],
  ["question.phyllodes.pathology-follow-up.v30", "presentation.phyllodes.pathology-follow-up.v30", "concept.phyllodes.suspicious-node-biopsy-exception", "claim.phyllodes.suspicious-node-biopsy-exception", "A patient with a history of phyllodes tumor has a suspicious axillary node on follow-up imaging.", "What is the first axillary diagnostic step?", ["Image-guided histopathologic needle biopsy.", "immediate axillary dissection", "observation without tissue assessment"], "Image-guided histopathologic needle biopsy.", "suspicious nodes are sampled before any dissection discussion."],
  ["question.phyllodes.pathology-follow-up.v31", "presentation.phyllodes.pathology-follow-up.v31", "concept.phyllodes.suspicious-node-biopsy-exception", "claim.phyllodes.suspicious-node-biopsy-exception", "A patient with malignant phyllodes has a newly suspicious axillary node during pathology follow-up.", "Which action is appropriate first?", ["Image-guided histopathologic needle biopsy.", "routine sentinel-node biopsy instead", "immediate axillary dissection"], "Image-guided histopathologic needle biopsy.", "the exception is driven by a suspicious node, not by malignant pathology alone."],
  ["question.phyllodes.pathology-follow-up.v32", "presentation.phyllodes.pathology-follow-up.v32", "concept.phyllodes.suspicious-node-biopsy-exception", "claim.phyllodes.suspicious-node-biopsy-exception", "A patient with prior borderline phyllodes has a suspicious axillary node and biopsy-proven involvement.", "After MDT review, what may be considered?", ["Axillary dissection after MDT discussion.", "ignore the proven involvement", "perform routine sentinel-node biopsy instead"], "Axillary dissection after MDT discussion.", "dissection is reserved for biopsy-proven involvement after MDT discussion."],
  ["question.phyllodes.pathology-follow-up.v33", "presentation.phyllodes.pathology-follow-up.v33", "concept.phyllodes.suspicious-node-biopsy-exception", "claim.phyllodes.suspicious-node-biopsy-exception", "A patient with a prior benign phyllodes diagnosis has a suspicious axillary node on imaging. Needle biopsy does not show involvement.", "What is the appropriate next implication?", ["Do not proceed to axillary dissection on suspicion alone.", "perform axillary dissection despite the negative biopsy", "treat the node as routine sentinel-node staging"], "Do not proceed to axillary dissection on suspicion alone.", "the dissection exception requires biopsy-proven involvement."],
] as const;

const EXPECTED_CONCEPT_IDS = [
  "concept.phyllodes.benign-complete-excision",
  "concept.phyllodes.benign-positive-margin-management",
  "concept.phyllodes.borderline-margin-target",
  "concept.phyllodes.borderline-close-margin-management",
  "concept.phyllodes.malignant-margin-target",
  "concept.phyllodes.malignant-close-margin-management",
  "concept.phyllodes.hematogenous-spread-pattern",
  "concept.phyllodes.no-routine-axillary-staging",
  "concept.phyllodes.suspicious-node-biopsy-exception",
] as const;

describe("owner row 53 approved deferred phyllodes pathology follow-up", () => {
  it("preserves every exact approved patient-linked question in authored review order", () => {
    expect(ROW_053_QUESTION_VARIANTS).toHaveLength(33);
    for (const [id, presentationVariantId, conceptId, claimId, patientPresentation, stem, labels, correctLabel, explanation] of EXPECTED_VARIANTS) {
      const question = ROW_053_QUESTION_VARIANTS.find((item) => item.id === id);
      expect(question).toMatchObject({ id, presentationVariantId, conceptId, patientPresentation, stem, explanation, releasePointId: RELEASE_POINT_ID, earliestFacilityStage: null, requiredClinicalSetting: REQUIRED_CLINICAL_SETTING, currentGameEligibility: "deferred", shuffleAnswers: true, reviewStatus: "clinically_approved", supportingEvidenceClaimIds: [claimId] });
      expect(question?.answerChoices.map((choice) => choice.label)).toEqual(labels);
      expect(question?.answerChoices.filter((choice) => choice.isCorrect)).toHaveLength(1);
      expect(question?.answerChoices.find((choice) => choice.isCorrect)?.label).toBe(correctLabel);
    }
    const splitVariant = ROW_053_QUESTION_VARIANTS[31]!;
    expect(splitVariant.patientPresentation).toBe("A patient with prior borderline phyllodes has a suspicious axillary node and biopsy-proven involvement.");
    expect(splitVariant.stem).toBe("After MDT review, what may be considered?");
    expect(`${splitVariant.patientPresentation} ${splitVariant.stem}`).toBe("A patient with prior borderline phyllodes has a suspicious axillary node and biopsy-proven involvement. After MDT review, what may be considered?");
  });

  it("keeps all nine FSRS identities deferred with their exact variant distribution", () => {
    expect(ROW_053_CONCEPTS.map((concept) => concept.id)).toEqual(EXPECTED_CONCEPT_IDS);
    expect(ROW_053_CONCEPTS.map((concept) => concept.supportingEvidenceClaimIds)).toEqual(EXPECTED_CONCEPT_IDS.map((conceptId) => [`claim.${conceptId.slice("concept.".length)}`]));
    expect(ROW_053_CONCEPTS.map((concept) => concept.releasePointId)).toEqual(Array(9).fill(RELEASE_POINT_ID));
    expect(ROW_053_CONCEPTS.map((concept) => concept.earliestFacilityStage)).toEqual(Array(9).fill(null));
    expect(ROW_053_CONCEPTS.map((concept) => concept.requiredClinicalSetting)).toEqual(Array(9).fill(REQUIRED_CLINICAL_SETTING));
    expect(ROW_053_CONCEPTS.map((concept) => concept.currentGameEligibility)).toEqual(Array(9).fill("deferred"));
    expect(EXPECTED_CONCEPT_IDS.map((id) => ROW_053_QUESTION_VARIANTS.filter((question) => question.conceptId === id).length)).toEqual([4, 4, 4, 3, 4, 3, 4, 3, 4]);
  });

  it("keeps 33 one-to-one deferred blueprints and the exact deferred backlog", () => {
    expect(ROW_053_APPROVED_ENCOUNTER_BLUEPRINTS).toHaveLength(33);
    expect(ROW_053_APPROVED_ENCOUNTER_BLUEPRINTS.map((blueprint) => blueprint.presentationVariantId)).toEqual(ROW_053_QUESTION_VARIANTS.map((question) => question.presentationVariantId));
    for (const blueprint of ROW_053_APPROVED_ENCOUNTER_BLUEPRINTS) {
      expect(blueprint).toMatchObject({ releasePointId: RELEASE_POINT_ID, earliestFacilityStage: null, requiredClinicalSetting: REQUIRED_CLINICAL_SETTING, currentGameEligibility: "deferred", maximumScoredDecisionsPerEncounter: 1 });
      expect(blueprint.questionVariantIds).toHaveLength(1);
      expect(ROW_053_QUESTION_VARIANTS.some((question) => question.id === blueprint.questionVariantIds[0])).toBe(true);
    }
    expect(ROW_053_APPROVED_BACKLOG).toMatchObject({ conceptIds: EXPECTED_CONCEPT_IDS, releasePointId: RELEASE_POINT_ID, earliestFacilityStage: null, requiredClinicalSetting: REQUIRED_CLINICAL_SETTING, currentGameEligibility: "deferred", approvedForRuntime: false, tutorialEligible: false, maximumScoredDecisionsPerEncounter: 1, questionVariantIds: EXPECTED_VARIANTS.map(([id]) => id), encounterBlueprintIds: ROW_053_APPROVED_ENCOUNTER_BLUEPRINTS.map((blueprint) => blueprint.id) });
  });

  it("preserves the exact named-clinician approval scope", () => {
    expect(ROW_053_CLINICAL_APPROVAL).toMatchObject({ id: "approval.melissa-rowland-md.owner-row-053.2026-08-31", reviewer: "Melissa Rowland, MD", reviewedOn: "2026-08-31", contentVersion: "clinical.owner-row-053.2026-08-31.1", decision: "approved", approvedConceptIds: EXPECTED_CONCEPT_IDS, approvedPresentationVariantIds: EXPECTED_VARIANTS.map(([, id]) => id), approvedQuestionVariantIds: EXPECTED_VARIANTS.map(([id]) => id), approvedEvidenceClaimIds: [] });
  });

  it("maintains complete bidirectional source and claim provenance without conflating review states", () => {
    const sourceIds = new Set(ROW_053_SOURCES.map((source) => source.id));
    const claimIds = new Set(ROW_053_EVIDENCE_CLAIMS.map((claim) => claim.id));
    expect(ROW_053_EVIDENCE_CLAIMS).toHaveLength(9);
    expect(ROW_053_SOURCES).toHaveLength(2);
    expect(ROW_053_SOURCES.map((source) => [source.id, source.evidenceClaimIds])).toEqual([
      ["source.rosenberger.asbrs-sbi-benign-fel.2025", ["claim.phyllodes.benign-complete-excision", "claim.phyllodes.benign-positive-margin-management"]],
      ["source.bishr.uk-abs-phyllodes.2025", ROW_053_EVIDENCE_CLAIMS.map((claim) => claim.id)],
    ]);
    for (const source of ROW_053_SOURCES) {
      expect(source).toMatchObject({ reviewStatus: "needs_clinician_review", contentVersion: "clinical.owner-row-053.2026-08-31.1", lastClinicianReview: null, accessedOn: "2026-08-31" });
      expect(source.completeCitation).not.toHaveLength(0); expect(source.organizationOrJournal).not.toHaveLength(0); expect(source.authors.length).toBeGreaterThan(0); expect(source.publicationYear).toBe(2025); expect(source.officialUrl).toMatch(/^https:\/\//); expect(source.licenseLabel).not.toHaveLength(0); expect(source.reuseStatus).not.toHaveLength(0); expect(source.reuseNotes).not.toHaveLength(0);
      expect(source.evidenceClaimIds.every((claimId) => claimIds.has(claimId))).toBe(true);
    }
    expect(ROW_053_SOURCES[0]).toMatchObject({ id: "source.rosenberger.asbrs-sbi-benign-fel.2025", doi: "10.1001/jamasurg.2025.4392", pmid: "41123921", sourceClass: "professional_society_guideline", licenseLabel: "Copyrighted; targeted verification only", reuseStatus: "copyrighted_targeted_verification_only" });
    expect(ROW_053_SOURCES[1]).toMatchObject({ id: "source.bishr.uk-abs-phyllodes.2025", doi: "10.1093/bjs/znaf152", pmid: "40847758", sourceClass: "professional_society_guideline", licenseLabel: "Creative Commons Attribution-NonCommercial 4.0 International", reuseStatus: "cc_by_nc_4_0_restricted" });
    for (const claim of ROW_053_EVIDENCE_CLAIMS) {
      expect(claim).toMatchObject({ reviewStatus: "needs_clinician_review", contentVersion: "clinical.owner-row-053.2026-08-31.1", lastClinicianReview: null, lastCheckedOn: "2026-08-31" });
      expect(claim.limitation).not.toHaveLength(0); expect(claim.sourceIds.every((sourceId) => sourceIds.has(sourceId))).toBe(true);
      expect(
        ROW_053_SOURCES.some((source) =>
          new Set<string>(source.evidenceClaimIds).has(claim.id),
        ),
      ).toBe(true);
    }
  });

  it("does not admit this deferred package to the active release or routine case pool", () => {
    const packagePrefix = "phyllodes.pathology-follow-up";
    expect(SYNTHETIC_CLINICAL_RELEASE.concepts.some((concept) => EXPECTED_CONCEPT_IDS.includes(concept.id as typeof EXPECTED_CONCEPT_IDS[number]))).toBe(false);
    expect(SYNTHETIC_CLINICAL_RELEASE.cases.some((clinicalCase) => clinicalCase.id.includes(packagePrefix) || clinicalCase.patientPresentationVariantId.includes(packagePrefix) || clinicalCase.decisionNodes.some((node) => node.questionVariantId.includes(packagePrefix) || EXPECTED_CONCEPT_IDS.includes(node.primaryConceptId as typeof EXPECTED_CONCEPT_IDS[number])))).toBe(false);
    expect(LEVEL_TWO_ROUTINE_CASE_IDS.some((caseId) => caseId.includes(packagePrefix))).toBe(false);
  });
});
