import { resolve } from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';

export const GREEN_RIG_V6=Object.freeze({
  id:'patient.adult.046',view:'south',canvas:{width:160,height:320},floorY:287,
  head:{x:36,y:28,scale:1,rigid:true},torso:{topY:110,height:97},
  hips:{left:{x:60,y:197},right:{x:100,y:197}},
  shoulders:{left:{x:46,y:128},right:{x:108,y:128}},
  arms:{sleeveScale:.42,sleevePivot:{x:47,y:35},handScale:.25,handPivot:{x:45,y:4},restHands:{left:{x:42,y:187},right:{x:112,y:187}}},
  seated:{
    lowerTopY:205,
    lowerHeight:82,
    seatY:217,
    replacementFrame:10,
    armScale:.14,
    armRects:{left:[224,212,381,595],right:[931,212,375,595]},
    armPivots:{left:{x:171.075,y:36.906},right:{x:209.109,y:36.737}},
  },
});
const ease=value=>value*value*(3-2*value);
export function sampleWalkPose(frame){const phase=(frame%16)/16*Math.PI*2,sine=Math.sin(phase),cosine=Math.cos(phase),planted=cosine>=0?'left':'right',leftLift=Math.max(0,-cosine)*7,rightLift=Math.max(0,cosine)*7;return{kind:'walk',frame:frame%16,headScale:1,bodyBob:(1-Math.abs(cosine)),legAngles:{left:sine*.018,right:sine*.018},armAngles:{left:sine*.045,right:sine*.045},armOffsetsY:{left:-sine*3,right:sine*3},planted,footTargets:{left:287-leftLift,right:287-rightLift},travelX:0};}
export function sampleSitPose(frame){const index=Math.max(0,Math.min(15,frame)),progress=ease(index/15),replacement=index>=GREEN_RIG_V6.seated.replacementFrame;return{kind:'sit',frame:index,headScale:1,progress,replacement,bodyDrop:progress*16,legAngles:{left:progress*.045,right:-progress*.045},armAngles:{left:-progress*.55,right:progress*.55},planted:replacement?'seated':'both',footTargets:{left:287,right:287},travelX:0};}
function imageData(image){const canvas=createCanvas(image.width,image.height),context=canvas.getContext('2d');context.drawImage(image,0,0);return context.getImageData(0,0,image.width,image.height);}
function alphaBounds(image,rect=[0,0,image.width,image.height],threshold=128){const data=imageData(image).data;let left=rect[0]+rect[2],top=rect[1]+rect[3],right=-1,bottom=-1;for(let y=rect[1];y<rect[1]+rect[3];y+=1)for(let x=rect[0];x<rect[0]+rect[2];x+=1)if(data[(y*image.width+x)*4+3]>=threshold){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y);}if(right<left)throw new Error('empty rig asset');return{x:left,y:top,width:right-left+1,height:bottom-top+1};}
export async function loadGreenRigV6(repo){const asset=relative=>resolve(repo,relative),files={head:'tools/character-mapping/layered-pilot/assets/green-south-source-head-v5.png',torso:'tools/character-mapping/layered-pilot/assets/green-south-torso-arm-free-v4.png',legs:'tools/character-mapping/layered-pilot/assets/green-south-continuous-legs-v5.png',seated:'tools/character-mapping/layered-pilot/assets/green-south-seated-lowerbody-v6.png',seatedArms:'tools/character-mapping/layered-pilot/assets/green-south-seated-arms-v6.png',sleeveLeft:'artifacts/character-movement/layered-pilot/green-south-parts-v3/sleeveLeft.png',sleeveRight:'artifacts/character-movement/layered-pilot/green-south-parts-v3/sleeveRight.png',handLeft:'artifacts/character-movement/layered-pilot/green-south-parts-v3/handLeft.png',handRight:'artifacts/character-movement/layered-pilot/green-south-parts-v3/handRight.png'},images=Object.fromEntries(await Promise.all(Object.entries(files).map(async([id,file])=>[id,await loadImage(asset(file))]))),split=Math.floor(images.legs.width/2),legRects={left:[0,0,split,images.legs.height],right:[split,0,images.legs.width-split,images.legs.height]},legBounds={left:alphaBounds(images.legs,legRects.left),right:alphaBounds(images.legs,legRects.right)},legScale=90/Math.max(legBounds.left.height,legBounds.right.height),torsoBounds=alphaBounds(images.torso),torsoScale=GREEN_RIG_V6.torso.height/torsoBounds.height,seatedBounds=alphaBounds(images.seated),seatedScale=GREEN_RIG_V6.seated.lowerHeight/seatedBounds.height;return{files,images,legRects,legBounds,legScale,torsoBounds,torsoScale,seatedBounds,seatedScale};}
function scanBounds(canvas){const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let left=canvas.width,top=canvas.height,right=-1,bottom=-1;for(let y=0;y<canvas.height;y+=1)for(let x=0;x<canvas.width;x+=1)if(data[(y*canvas.width+x)*4+3]){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y);}return right<left?null:{left,top,right,bottom};}
function supportCenter(canvas,bounds){const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let total=0,count=0;for(let y=Math.max(bounds.top,bounds.bottom-4);y<=bounds.bottom;y+=1)for(let x=bounds.left;x<=bounds.right;x+=1)if(data[(y*canvas.width+x)*4+3]){total+=x;count+=1;}return count?total/count:(bounds.left+bounds.right)/2;}
function drawLegLayer(loaded,side,angle,targetFloor,hipY){const canvas=createCanvas(160,320),context=canvas.getContext('2d'),rect=loaded.legRects[side],bounds=loaded.legBounds[side],localPivot={x:bounds.x-rect[0]+bounds.width/2,y:bounds.y-rect[1]},hip=GREEN_RIG_V6.hips[side];context.save();context.translate(hip.x,hipY);context.rotate(angle);context.scale(loaded.legScale,loaded.legScale);context.drawImage(loaded.images.legs,...rect,-localPivot.x,-localPivot.y,rect[2],rect[3]);context.restore();const initial=scanBounds(canvas),shiftX=hip.x-supportCenter(canvas,initial),shiftY=targetFloor-initial.bottom,output=createCanvas(160,320);output.getContext('2d').drawImage(canvas,shiftX,shiftY);const finalBounds=scanBounds(output);return{canvas:output,bounds:finalBounds,shiftX,shiftY,supportX:hip.x,actualSupportX:supportCenter(output,finalBounds),hip:{x:hip.x+shiftX,y:hipY+shiftY}};}
function rotate(point,center,angle){const cosine=Math.cos(angle),sine=Math.sin(angle),dx=point.x-center.x,dy=point.y-center.y;return{x:center.x+dx*cosine-dy*sine,y:center.y+dx*sine+dy*cosine};}
function drawPivot(context,image,pivot,scale,world,angle){context.save();context.translate(world.x,world.y);context.rotate(angle);context.scale(scale,scale);context.drawImage(image,-pivot.x,-pivot.y);context.restore();}
function drawArm(context,loaded,side,angle,bodyDrop){const key=side==='left'?'Left':'Right',shoulder={x:GREEN_RIG_V6.shoulders[side].x,y:GREEN_RIG_V6.shoulders[side].y+bodyDrop},rest={...GREEN_RIG_V6.arms.restHands[side],y:GREEN_RIG_V6.arms.restHands[side].y+bodyDrop},hand=rotate(rest,shoulder,angle);drawPivot(context,loaded.images[`sleeve${key}`],GREEN_RIG_V6.arms.sleevePivot,GREEN_RIG_V6.arms.sleeveScale,shoulder,angle);drawPivot(context,loaded.images[`hand${key}`],GREEN_RIG_V6.arms.handPivot,GREEN_RIG_V6.arms.handScale,hand,angle);return{shoulder,hand,angle};}
function drawSeatedArms(context,loaded,bodyDrop){const arms={};for(const side of['left','right']){const rect=GREEN_RIG_V6.seated.armRects[side],pivot=GREEN_RIG_V6.seated.armPivots[side],shoulder={x:GREEN_RIG_V6.shoulders[side].x,y:GREEN_RIG_V6.shoulders[side].y+bodyDrop};context.save();context.translate(shoulder.x,shoulder.y);context.scale(GREEN_RIG_V6.seated.armScale,GREEN_RIG_V6.seated.armScale);context.drawImage(loaded.images.seatedArms,...rect,-pivot.x,-pivot.y,rect[2],rect[3]);context.restore();arms[side]={shoulder,scale:GREEN_RIG_V6.seated.armScale,sourceRect:rect};}return arms;}
export function renderGreenPose(loaded,pose){const canvas=createCanvas(160,320),context=canvas.getContext('2d'),contacts=[];if(pose.replacement){const bounds=loaded.seatedBounds,scale=loaded.seatedScale,x=80-(bounds.x+bounds.width/2)*scale,y=GREEN_RIG_V6.seated.lowerTopY-bounds.y*scale,layer=createCanvas(160,320),layerContext=layer.getContext('2d');layerContext.drawImage(loaded.images.seated,x,y,loaded.images.seated.width*scale,loaded.images.seated.height*scale);const initial=scanBounds(layer),shiftY=GREEN_RIG_V6.floorY-initial.bottom;context.drawImage(layer,0,shiftY);contacts.push({part:'seatedLowerBody',floorY:GREEN_RIG_V6.floorY,kind:'replacement',shiftY});}else{for(const side of['left','right']){const leg=drawLegLayer(loaded,side,pose.legAngles[side],pose.footTargets[side],GREEN_RIG_V6.hips[side].y+(pose.bodyBob??0)+('bodyDrop'in pose?pose.bodyDrop:0));context.drawImage(leg.canvas,0,0);contacts.push({part:`${side}Foot`,floorY:leg.bounds.bottom,planted:pose.planted==='both'||pose.planted===side,shiftX:leg.shiftX,shiftY:leg.shiftY,supportX:leg.supportX,actualSupportX:leg.actualSupportX,hip:leg.hip});}}
  const drop='bodyDrop'in pose?pose.bodyDrop:pose.bodyBob,armOffset=pose.armOffsetsY??{left:0,right:0},standingArms=pose.replacement?null:{left:drawArm(context,loaded,'left',pose.armAngles.left,drop+armOffset.left),right:drawArm(context,loaded,'right',pose.armAngles.right,drop+armOffset.right)},torsoX=80-(loaded.torsoBounds.x+loaded.torsoBounds.width/2)*loaded.torsoScale,torsoY=GREEN_RIG_V6.torso.topY-loaded.torsoBounds.y*loaded.torsoScale+drop;context.drawImage(loaded.images.torso,torsoX,torsoY,loaded.images.torso.width*loaded.torsoScale,loaded.images.torso.height*loaded.torsoScale);const arms=pose.replacement?drawSeatedArms(context,loaded,drop):standingArms;context.drawImage(loaded.images.head,GREEN_RIG_V6.head.x,GREEN_RIG_V6.head.y+drop);return{canvas,metadata:{pose,contacts,arms,head:{x:GREEN_RIG_V6.head.x,y:GREEN_RIG_V6.head.y+drop,scale:1},torso:{x:torsoX,y:torsoY,scale:loaded.torsoScale},bounds:scanBounds(canvas)}};}
