(()=>{
  const root=document.getElementById('ultrasound-layout-proof'),canvas=root.querySelector('#ultrasound-art'),ctx=canvas.getContext('2d'),status=root.querySelector('#ultrasound-status'),overlay=root.querySelector('#ultrasound-overlay'),optionalToggle=root.querySelector('#ultrasound-optional'),targets=root.querySelector('#ultrasound-targets');
  const SCALE=2,W=480,H=550,S=120,X=60,Y=130,BOTTOM=Y+3*S,EAST=X+3*S;
  const segments=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'];
  const state={doors:new Set(['S2']),adjacent:new Set(),selected:'S2',optional:true};
  const fixtures={
    table:{id:'table',label:'horizontal ultrasound table',footprint:{left:.6,top:1.1,width:1.8,height:.65},navigationBlocker:{left:1,top:1,width:1,height:1},anchor:{x:1.5,y:1.75},seat:{floorProjection:{x:2.2,y:1.75},facing:'S'},approach:{x:2.2,y:2.2},facing:'S',persistence:'permanent',collision:'solid'},
    stool:{id:'stool',label:'technician stool',footprint:{left:1.95,top:2.55,width:.5,height:.3},anchor:{x:2.2,y:2.75},seat:{floorProjection:{x:2.2,y:2.75},facing:'N'},approach:{x:2.2,y:2.84},facing:'N',persistence:'permanent',collision:'nonblocking'},
    console:{id:'console',label:'ultrasound console',footprint:{left:.55,top:2.0,width:.5,height:.33},anchor:{x:.8,y:2.33},approach:{x:.8,y:2.84},facing:'S',operatorFacing:'N',approachFacing:'N',persistence:'permanent',collision:'nonblocking'},
    wallPrint:{id:'wallPrint',label:'north-center wall print',anchor:{x:1.5,y:-.52},conflicts:['N2'],persistence:'optional',collision:'nonblocking',mount:'north wall'},
    cabinet:{id:'cabinet',label:'northwest supply cabinet',footprint:{left:.15,top:0,width:.48,height:.38},anchor:{x:.39,y:.38},conflicts:['N1','WA'],persistence:'optional',collision:'nonblocking'},
  };  const crops=__CROP_CONFIG__,radius=.16,step=.04,start={x:1.52,y:2.84},navigationBlocker=fixtures.table.navigationBlocker,southPassage={from:{x:.2,y:2.7},to:{x:1.4,y:2.7},layer:'front-of-console',clearanceFromConsole:.37};
  const atlas=new Image();atlas.src='data:image/webp;base64,__ULTRASOUND_ATLAS__';atlas.onload=render;
  const key=p=>`${p.x.toFixed(2)},${p.y.toFixed(2)}`,inflated=r=>({left:r.left-radius,top:r.top-radius,right:r.left+r.width+radius,bottom:r.top+r.height+radius});
  const validPoint=p=>p.x>=radius-1e-6&&p.x<=3-radius+1e-6&&p.y>=radius-1e-6&&p.y<=3-radius+1e-6&&!(()=>{const r=inflated(navigationBlocker);return p.x>=r.left-1e-6&&p.x<=r.right+1e-6&&p.y>=r.top-1e-6&&p.y<=r.bottom+1e-6})();
  const candidates=id=>{const values=[.28,.36,.52,.64,.72];if(id[0]==='N'||id[0]==='S'){const i=Number(id[1])-1,y=id[0]==='N'?radius:3-radius;return values.map(v=>({x:i+v,y})).filter(validPoint)}const i=id.charCodeAt(1)-65,x=id[0]==='W'?radius:3-radius;return values.map(v=>({x,y:i+v})).filter(validPoint)};
  const simplify=path=>path.filter((p,i)=>i===0||i===path.length-1||Math.abs((path[i-1].x-p.x)*(path[i+1].y-p.y)-(path[i-1].y-p.y)*(path[i+1].x-p.x))>.0001);
  function bfs(from,to){const snap=p=>({x:Math.round(p.x/step)*step,y:Math.round(p.y/step)*step}),a=snap(from),b=snap(to);if(!validPoint(a)||!validPoint(b))return[];const queue=[a],prev=new Map([[key(a),null]]),points=new Map([[key(a),a]]),moves=[[step,0],[-step,0],[0,step],[0,-step]];while(queue.length){const p=queue.shift(),pk=key(p);if(pk===key(b)){const path=[];for(let k=pk;k;k=prev.get(k))path.unshift(points.get(k));return simplify(path)}for(const[dx,dy]of moves){const n=snap({x:p.x+dx,y:p.y+dy}),nk=key(n);if(validPoint(n)&&!prev.has(nk)){prev.set(nk,pk);points.set(nk,n);queue.push(n)}}}return[]}
  const routeToDoor=id=>{let best=[];for(const target of candidates(id)){const route=bfs(start,target);if(route.length&&(!best.length||route.length<best.length))best=route}return best};
  let routeCache=null,serviceCache=null;
  const routes=()=>routeCache||(routeCache=Object.fromEntries(segments.map(id=>[id,routeToDoor(id)])));
  const serviceRoutes=()=>serviceCache||(serviceCache={patient:bfs(start,fixtures.table.approach),technician:bfs(start,fixtures.stool.approach),console:bfs(start,fixtures.console.approach)});
  const hiddenOptional=()=>Object.values(fixtures).filter(f=>f.persistence==='optional'&&(!state.optional||f.conflicts.some(id=>state.doors.has(id))||f.conflicts.some(id=>id[0]==='N'&&state.adjacent.has(id)))).map(f=>f.id);
  function surface(left,top,width,height){ctx.save();ctx.beginPath();ctx.rect(left,top,width,height);ctx.clip();ctx.fillStyle='#d8d5ca';ctx.fillRect(left,top,width,height);ctx.strokeStyle='rgba(105,125,103,.24)';ctx.lineWidth=1;const unit=30;for(let x=X+Math.ceil((left-X)/unit)*unit;x<=left+width;x+=unit){ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+height);ctx.stroke()}for(let y=Y+Math.ceil((top-Y)/unit)*unit;y<=top+height;y+=unit){ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left+width,y);ctx.stroke()}for(let py=Math.floor(top);py<top+height;py+=9)for(let px=Math.floor(left);px<left+width;px+=9){const seed=Math.abs((px*13+py*7)%37);ctx.fillStyle=seed%3?'rgba(248,245,235,.10)':'rgba(92,106,96,.06)';ctx.fillRect(px+seed%5,py+(seed*3)%5,1,1)}ctx.restore()}
  function drawShell(){const cream='#efe1bd',green='#58735a',dark='#294632',light='#789173',wood='#744a29',background='#f3ead3',low=29,wall=90,cap=14;ctx.clearRect(0,0,W,H);ctx.fillStyle=background;ctx.fillRect(0,0,W,H);surface(X,Y,3*S,3*S);const tall=i=>{const sx=X+i*S;ctx.fillStyle='#bfd5e8';ctx.fillRect(sx,Y-wall,S,wall);ctx.fillStyle='rgba(146,110,67,.055)';ctx.fillRect(sx+12,Y-wall+30,S-24,2);ctx.fillStyle=green;ctx.fillRect(sx,Y-23,S,23);ctx.fillStyle=light;ctx.fillRect(sx,Y-23,S,4);ctx.fillStyle=dark;ctx.fillRect(sx,Y-7,S,7);ctx.fillRect(sx-1,Y-wall-9,S+2,9);ctx.fillStyle=light;ctx.fillRect(sx-1,Y-wall-9,S+2,3)},backed=i=>{const sx=X+i*S;ctx.fillStyle=green;ctx.fillRect(sx,Y-low,S,low);ctx.fillStyle=light;ctx.fillRect(sx,Y-low,S,4);ctx.fillStyle=dark;ctx.fillRect(sx,Y-7,S,7)};for(let i=0;i<3;i++)state.adjacent.has(`N${i+1}`)?backed(i):tall(i);for(let i=0;i<3;i++)if(state.adjacent.has(`N${i+1}`))ctx.clearRect(X+i*S,0,S,Y-low);const westX=X-cap+2,eastX=EAST-2,side=right=>{const px=right?eastX:westX,neighbor=right?'N3':'N1',top=state.adjacent.has(neighbor)?Y-low:Y-wall-9;ctx.fillStyle=dark;ctx.fillRect(px,top,cap,BOTTOM+29-top);ctx.fillStyle=light;ctx.fillRect(px+(right?0:cap-3),top,3,BOTTOM+29-top)};side(false);side(true);const northDoor=i=>{const backedNorth=state.adjacent.has(`N${i+1}`),left=X+i*S+12,right=X+(i+1)*S-12,top=backedNorth?Y-low:Y-wall+8;ctx.clearRect(left,top,right-left,Y-top);ctx.fillStyle=wood;ctx.fillRect(left-5,top,5,Y-top);ctx.fillRect(right,top,5,Y-top);if(!backedNorth)ctx.fillRect(left-5,top-5,right-left+10,6)},sideDoor=(right,i)=>{const px=right?eastX:westX,top=Y+i*S+12,height=S-24,half=cap/2;ctx.clearRect(px,top,cap,height);if(right){surface(px,top,half,height);ctx.clearRect(px+half,top,half,height)}else{ctx.clearRect(px,top,half,height);surface(px+half,top,half,height)}ctx.fillStyle=wood;ctx.fillRect(px-2,top-3,cap+4,5);ctx.fillRect(px-2,top+height-2,cap+4,5)};for(let i=0;i<3;i++){const left=X+i*S;ctx.fillStyle=cream;ctx.fillRect(left,BOTTOM,S,29);ctx.fillStyle=green;ctx.fillRect(left,BOTTOM+21,S,8);ctx.fillStyle=dark;ctx.fillRect(left,BOTTOM-6,S,8);ctx.fillStyle=light;ctx.fillRect(left,BOTTOM-6,S,3)}for(const id of state.doors){if(id[0]==='N')northDoor(Number(id[1])-1);else if(id[0]==='S'){const i=Number(id[1])-1,left=X+i*S+12,right=X+(i+1)*S-12;ctx.clearRect(left,BOTTOM-6,right-left,35);surface(left,BOTTOM-6,right-left,35);ctx.fillStyle=wood;ctx.fillRect(left-5,BOTTOM-8,5,37);ctx.fillRect(right,BOTTOM-8,5,37)}else sideDoor(id[0]==='E',id.charCodeAt(1)-65)}}
  const drawSprite=(id,anchor,width)=>{const c=crops[id],scale=width/c.w,height=c.h*scale,x=X+anchor.x*S-c.contactX*scale,y=Y+anchor.y*S-c.contactY*scale;ctx.drawImage(atlas,c.x,c.y,c.w,c.h,x,y,width,height);return{x,y,w:width,h:height,contactX:x+c.contactX*scale,contactY:y+c.contactY*scale,sourceContact:{x:c.contactX,y:c.contactY},seatScreen:c.seatX==null?null:{x:x+c.seatX*scale,y:y+c.seatY*scale},seatRise:c.seatY==null?null:(c.contactY-c.seatY)*scale,aspect:c.w/c.h}};
  function drawFurniture(){const hidden=hiddenOptional(),draws={};const specs={wallPrint:.4*S,cabinet:.62*S,table:1.8*S,console:.78*S,stool:.52*S};for(const id of ['wallPrint','cabinet','table','console','stool'])if(!hidden.includes(id))draws[id]=drawSprite(id,fixtures[id].anchor,specs[id]);return{hidden,draws}}
  function drawOverlay(routeMap,draws){if(!overlay.checked)return;ctx.save();ctx.font='10px sans-serif';ctx.fillStyle='rgba(41,70,50,.55)';for(let row=0;row<3;row++)for(let col=0;col<3;col++)ctx.fillText(`${String.fromCharCode(65+row)}${col+1}`,X+col*S+7,Y+row*S+15);for(const f of Object.values(fixtures)){const r=f.footprint;if(!r)continue;ctx.fillStyle=f.collision==='solid'?'rgba(141,90,71,.08)':'rgba(47,112,144,.08)';ctx.strokeStyle=f.collision==='solid'?'#8d5a47':'#2f7090';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.fillRect(X+r.left*S,Y+r.top*S,r.width*S,r.height*S);ctx.strokeRect(X+r.left*S,Y+r.top*S,r.width*S,r.height*S)}ctx.setLineDash([]);ctx.fillStyle='rgba(141,90,71,.14)';ctx.strokeStyle='#8d5a47';ctx.lineWidth=2;ctx.fillRect(X+navigationBlocker.left*S,Y+navigationBlocker.top*S,navigationBlocker.width*S,navigationBlocker.height*S);ctx.strokeRect(X+navigationBlocker.left*S,Y+navigationBlocker.top*S,navigationBlocker.width*S,navigationBlocker.height*S);ctx.fillStyle='#8d5a47';ctx.font='bold 11px sans-serif';ctx.fillText('B2 blocked',X+navigationBlocker.left*S+7,Y+navigationBlocker.top*S+16);const path=routeMap[state.selected];if(path.length){ctx.strokeStyle='#2f7090';ctx.lineWidth=3;ctx.beginPath();path.forEach((p,i)=>(i?ctx.lineTo(X+p.x*S,Y+p.y*S):ctx.moveTo(X+p.x*S,Y+p.y*S)));ctx.stroke()}for(const [id,label,color]of [['table','patient','#8d5a47'],['stool','technician','#2f7090']]){const f=fixtures[id],floor=f.seat.floorProjection,elevated=draws[id].seatScreen;ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(X+floor.x*S,Y+floor.y*S,6,0,Math.PI*2);ctx.stroke();ctx.fillStyle=color;ctx.font='bold 11px sans-serif';ctx.fillText(`${label} floor`,X+floor.x*S+8,Y+floor.y*S+4);ctx.beginPath();ctx.arc(elevated.x,elevated.y,5,0,Math.PI*2);ctx.fill();ctx.fillText(`${label} seat ${f.facing}`,elevated.x+7,elevated.y+3)}const use=fixtures.console.approach;ctx.fillStyle='#355f52';ctx.beginPath();ctx.arc(X+use.x*S,Y+use.y*S,5,0,Math.PI*2);ctx.fill();ctx.fillText('console use N',X+use.x*S-70,Y+use.y*S+4);ctx.restore()}
  const hitSlot=id=>{if(id[0]==='N'||id[0]==='S'){const i=Number(id[1])-1;return{x:X+i*S,y:id[0]==='N'?(state.adjacent.has(id)?Y-29:Y-99):BOTTOM,w:S,h:id[0]==='N'?(state.adjacent.has(id)?29:99):29}}const i=id.charCodeAt(1)-65;return{x:id[0]==='W'?X-14:EAST,y:Y+i*S,w:14,h:S}};
  function render(){ctx.setTransform(SCALE,0,0,SCALE,0,0);ctx.imageSmoothingEnabled=true;drawShell();const fixtureState=drawFurniture(),routeMap=routes(),service=serviceRoutes();drawOverlay(routeMap,fixtureState.draws);for(const button of targets.querySelectorAll('button')){const b=hitSlot(button.dataset.segment);Object.assign(button.style,{left:`${b.x/W*100}%`,top:`${b.y/H*100}%`,width:`${b.w/W*100}%`,height:`${b.h/H*100}%`})}const reachable=Object.values(routeMap).filter(path=>path.length).length;status.innerHTML=`<strong>${state.selected}</strong> · ${state.doors.has(state.selected)?'open doorway':'closed wall'} · ${reachable}/12 approaches reachable from S2<br>B2 is the only blocked tile · patient ${service.patient.length?'reachable':'blocked'} · technician ${service.technician.length?'reachable':'blocked'} · console use ${service.console.length?'reachable':'blocked'} · hidden: ${fixtureState.hidden.join(', ')||'none'}`;root.querySelectorAll('[data-segment]').forEach(button=>{const active=state.doors.has(button.dataset.segment);button.setAttribute('aria-pressed',String(active));button.classList.toggle('btn-primary',active)});canvas.dataset.doors=[...state.doors].join(',');canvas.dataset.adjacency=[...state.adjacent].join(',');canvas.dataset.hidden=fixtureState.hidden.join(',');canvas.dataset.routes=JSON.stringify(routeMap);canvas.dataset.serviceRoutes=JSON.stringify(service);canvas.dataset.fixtures=JSON.stringify(Object.values(fixtures).map(f=>({...f,draw:fixtureState.draws[f.id]||null})));canvas.dataset.navigationBlocker=JSON.stringify(navigationBlocker);canvas.dataset.southPassage=JSON.stringify(southPassage);canvas.dataset.shell=JSON.stringify({logicalCols:3,logicalRows:3,tileSize:S,rearWallHeight:90,lowNorthHeight:29,sideCapWidth:14,southHeight:29,northLowHeader:false,sideDoorSeam:'half-thickness',southFloorToBase:true})}
  const addButton=(id,target,label,hit=false)=>{const button=document.createElement('button');button.type='button';button.className=hit?'ultrasound-hit':'btn';button.dataset.segment=id;button.textContent=hit?'':id;button.setAttribute('aria-label',label);button.addEventListener('click',()=>{state.doors.has(id)?state.doors.delete(id):state.doors.add(id);state.selected=id;render()});target.append(button)};
  for(const[prefix,targetId]of[['N','ultrasound-north'],['S','ultrasound-south'],['W','ultrasound-west'],['E','ultrasound-east']])for(const id of segments.filter(segment=>segment[0]===prefix))addButton(id,root.querySelector('#'+targetId),`Toggle door at ${id}`);for(const id of segments)addButton(id,targets,`Wall door ${id}`,true);for(const id of ['N1','N2','N3']){const label=document.createElement('label');label.className='form-check';label.innerHTML=`<input class="form-check-input" type="checkbox" data-adjacent="${id}"><span class="form-check-label">${id}</span>`;label.querySelector('input').addEventListener('change',event=>{event.target.checked?state.adjacent.add(id):state.adjacent.delete(id);render()});root.querySelector('#ultrasound-adjacency').append(label)}optionalToggle.addEventListener('change',()=>{state.optional=optionalToggle.checked;render()});overlay.addEventListener('change',render);
  window.__ultrasoundLayout={segments,state,fixtures,crops,radius,step,start,navigationBlocker,southPassage,validPoint,candidates,bfs,routeToDoor,routes,serviceRoutes,hiddenOptional,render,ready:()=>atlas.complete&&atlas.naturalWidth>0};render();
})();


