// Native, aspect-preserving asset packing and five-tier private proof exports.
import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import{fileURLToPath}from'node:url';import{createCanvas,loadImage}from'@napi-rs/canvas';import{fixturePlacement}from'./geometry.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.dirname(here),mode=process.argv.includes('--stand-in')?'stand-in':'painted',layout=JSON.parse(fs.readFileSync(path.join(root,'layout.json'))),generation=mode==='painted'?JSON.parse(fs.readFileSync(path.join(root,'assets/generation-manifest.json'))):null,standins=JSON.parse(fs.readFileSync(path.join(root,'stand-in/v2/manifest.json')));
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,Buffer.isBuffer(v)||typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');};
export function bounds(p,t=1){const{width:w,height:h,data:d}=p;let left=w,right=-1,top=h,bottom=-1,count=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>=t){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);count++;}if(!count)throw Error('Empty alpha sprite');return{left,right,top,bottom,width:right-left+1,height:bottom-top+1,pixels:count};}
async function decode(p){const im=await loadImage(p),c=createCanvas(im.width,im.height),g=c.getContext('2d');g.drawImage(im,0,0);return{c,g,p:g.getImageData(0,0,c.width,c.height)};}
const assets={},metadata={schemaVersion:2,status:'candidate_needs_owner_review',approval:null,runtimeIntegrationAuthorized:false,mode,nominalNativePixelsPerTile:480,proofPixelsPerTile:120,assets:{}},contract={schemaVersion:2,mode,aspectPreserved:true,sharedFootprints:true,assets:{}},tiers=[];
for(const tier of layout.tiers){const room=structuredClone(layout.room),presentation=structuredClone(layout.presentation);room.tierLevel=tier.level;room.notes.push(`Room Level ${tier.level}: ${tier.summary}`);room.records=room.records.filter(r=>!r.presentIn||r.presentIn.includes(tier.level));
 for(const p of layout.pieces.filter(p=>!p.presentIn||p.presentIn.includes(tier.level))){const id=`l${tier.level}-${p.id}`,e=generation?.assets.find(a=>a.id===id),standin=standins.assets.find(a=>a.id===p.id),file=mode==='painted'?e?.original:standin.file;if(!file)throw Error('Missing generation entry '+id);const source=path.join(root,file),d=await decode(source),cropBounds=bounds(d.p,8),opaque=bounds(d.p,160),points=mode==='painted'?e.sourcePoints:standin.sourcePoints;
  let removed=0;for(let i=3;i<d.p.data.length;i+=4)if(d.p.data[i]>0&&d.p.data[i]<8){d.p.data[i]=0;removed++;}d.g.putImageData(d.p,0,0);
  const [w,h]=p.canvas,crop=[cropBounds.left,cropBounds.top,cropBounds.width,cropBounds.height],seat=points?.seat,scale=seat?180/(opaque.bottom+1-seat[1]):Math.min((w-12)/crop[2],(h-12)/crop[3]),dw=crop[2]*scale,dh=crop[3]*scale;
  if(dw>w-12+1e-6||dh>h-12+1e-6)throw Error(`Seat-calibrated sprite exceeds shared frame ${id}: ${dw}x${dh} > ${w-12}x${h-12}`);if(mode==='painted'&&scale>1)throw Error('Source would upscale '+id);
  const dx=(w-dw)/2,dy=p.center?(h-dh)/2:h-6-dh,out=createCanvas(w,h),og=out.getContext('2d');og.imageSmoothingEnabled=true;og.imageSmoothingQuality='high';og.drawImage(d.c,...crop,dx,dy,dw,dh);const op=og.getImageData(0,0,w,h),ob=bounds(op,160),ab=bounds(op),mapPoint=([x,y])=>[dx+(x-crop[0])*scale,dy+(y-crop[1])*scale],calibratedPoints={};for(const[k,v]of Object.entries(points??{}))if(k!=='frontRegions')calibratedPoints[k]=mapPoint(v);
  const anchor=p.center?[w/2,h/2]:p.top?[w/2,ab.top]:seat?[calibratedPoints.seat[0],calibratedPoints.seat[1]+180]:[w/2,ob.bottom+1],anchorKind=p.center?'walkable-rug':p.top?'wall':'floor',dest=mode==='painted'?`assets/processed/v2/${id}.png`:`stand-in/v2/prepared/${id}.png`;save(path.join(root,dest),out.toBuffer('image/png'));
  const m={id,file:path.relative(here,path.join(root,dest)).replaceAll('\\','/'),canvas:p.canvas,anchorKind,canvasAnchor:anchor,source:file,sourceSize:[d.c.width,d.c.height],sourceSha256:hash(source),sourceCrop:crop,transform:{scale,dx,dy,dw,dh},alphaCleanup:{threshold:8,pixelsRemoved:removed},outputOpaqueBounds:ob,outputAllAlphaBounds:ab,aspectPreserved:true,sourceUpscaled:mode==='painted'?false:scale>1,outputSha256:hash(path.join(root,dest)),sourcePoints:points,calibratedPoints,prompt:e?.prompt??null,promptSha256:e?.promptSha256??null};
  if(seat){m.measuredSeatRisePixels=(anchor[1]-calibratedPoints.seat[1])/4;m.floorRegistrationErrorPixels=(anchor[1]-(ob.bottom+1))/4;}
  if(calibratedPoints.worktop)m.measuredWorktopRisePixels=(anchor[1]-calibratedPoints.worktop[1])/4;
  metadata.assets[id]=m;assets['design:fo:'+id]={src:m.file,size:p.canvas,prepared:true,preparedId:id};contract.assets[id]={slot:p.id,level:tier.level,canvas:p.canvas,renderSizeTiles:p.size,ground:p.ground??null,seat:p.seat??null,wallTop:p.top??null,center:p.center??null,footprint:p.footprint??null,owners:p.owners};
  const rec=room.records.find(r=>r.id===p.id);rec.assetId='design:fo:'+id;
  if(seat){const mc=createCanvas(d.c.width,d.c.height),mg=mc.getContext('2d');for(const rect of points.frontRegions){mg.save();mg.beginPath();mg.rect(...rect);mg.clip();mg.drawImage(d.c,0,0);mg.restore();}const fc=createCanvas(w,h),fg=fc.getContext('2d');fg.imageSmoothingEnabled=true;fg.imageSmoothingQuality='high';fg.drawImage(mc,...crop,dx,dy,dw,dh);const frontId=id+'-front',frontDest=dest.replace('.png','-front.png');save(path.join(root,frontDest),fc.toBuffer('image/png'));metadata.assets[frontId]={...m,id:frontId,file:path.relative(here,path.join(root,frontDest)).replaceAll('\\','/'),outputSha256:hash(path.join(root,frontDest)),outputOpaqueBounds:bounds(fg.getImageData(0,0,w,h),160),outputAllAlphaBounds:bounds(fg.getImageData(0,0,w,h)),foregroundFor:id,foregroundRegions:points.frontRegions,derivation:'Exact generated pixels selected by source-space foreground rectangles, then the identical uniform transform.'};assets['design:fo:'+frontId]={src:metadata.assets[frontId].file,size:p.canvas,prepared:true,preparedId:frontId};room.records.find(r=>r.overlayFor===p.id).assetId='design:fo:'+frontId;}
 }
 const bases=[];for(const r of room.records.filter(r=>r.worldLocalGround&&!r.overlayFor&&!r.walkable&&r.depthPolicy!=='wall')){const spec=assets[r.assetId],m=metadata.assets[spec.preparedId],d=await decode(path.resolve(here,spec.src)),ob=bounds(d.p,160),w=d.c.width,h=d.c.height;let left=w,right=-1,top=h,bottom=-1;for(let y=Math.max(0,ob.bottom-8);y<=ob.bottom;y++)for(let x=0;x<w;x++)if(d.p.data[(y*w+x)*4+3]>=160){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}const f=fixturePlacement(r,m,120);bases.push({id:r.id+':opaque-base',recordId:r.id,footprint:{left:(f.x+left*f.w/w)/120,top:(f.y+top*f.h/h)/120,width:(right-left+1)*f.w/w/120,height:(bottom-top+1)*f.h/h/120},basis:'Decoded alpha >=160 in final nine-row floor-contact band.'});}
 const navigation={solidFixtures:[],doorThresholdExceptions:[],privateProofRouteModel:presentation};tiers.push({...tier,room,navigation,presentation,bases});
}
const data=JSON.parse(fs.readFileSync(path.join(here,'data.json')));data.founderPresentation=tiers[0].presentation;data.previewBaseClearances=tiers[0].bases;save(path.join(here,'data.json'),data);
save(path.join(here,'design-rooms.js'),'// Private 3x3 office; five full appearances, no runtime integration.\n'+Object.entries({DESIGN_ASSETS:assets,DESIGN_ROOMS:[tiers[0].room],DESIGN_NAVIGATION:{[tiers[0].room.definitionId]:tiers[0].navigation},PREPARED_METADATA:metadata,ASSET_CONTRACT:contract,DESIGN_TIERS:tiers}).map(([k,v])=>'export const '+k+' = '+JSON.stringify(v)+';').join('\n')+'\n');
save(path.join(here,'asset-contract.json'),contract);save(path.join(root,mode==='painted'?'assets/processed/v2/metadata.json':'stand-in/v2/prepared/metadata.json'),metadata);save(path.join(here,'layout-baseline.json'),{room:layout.room,navigation:layout.navigation,presentation:layout.presentation});
const renderer=fs.readFileSync(path.join(here,'lab.js'),'utf8').split('// Proof-only diagnostics, controls and review wording.')[0];save(path.join(here,'lab.js'),renderer+fs.readFileSync(path.join(here,'extension.js'),'utf8'));
save(path.join(here,'proof-manifest.json'),{schemaVersion:2,room:'founders-office',facilityLevel:5,appearanceLevels:[1,2,3,4,5],footprint:[3,3],footprintStatus:'owner_directed',mode,approval:null,runtimeIntegrationAuthorized:false,moraleMechanic:'undecided',doorModel:layout.presentation.doorModel,layoutSha256:hash(path.join(root,'layout.json')),prepaintLayoutSha256:hash(path.join(root,'stand-in/v2/layout-prepaint.json')),generationManifestSha256:generation?hash(path.join(root,'assets/generation-manifest.json')):null,designRoomsSha256:hash(path.join(here,'design-rooms.js')),dataSha256:hash(path.join(here,'data.json')),registrationSha256:hash(path.join(root,'assets/registration-v2.json')),reconciliationSha256:hash(path.join(root,'layout-reconciliation-v2.json')),rendererSha256:hash(path.join(here,'lab.js')),htmlSha256:hash(path.join(here,'index.html')),extensionSha256:hash(path.join(here,'extension.js')),geometrySha256:hash(path.join(here,'geometry.mjs')),newAssets:generation?.assets.map(a=>a.id)??[],notes:['Five complete appearances; 33 generated assets and 10 exact-pixel chair foregrounds.','Same footprints/anchors; founder south, visitor north; desk visitor face.','Morale undecided; browser and owner acceptance are separate.']});
console.log(`BUILD PASS: ${mode}; 5 complete tiers; 33 distinct assets + 10 chair foregrounds; shared 3x3; 12 one-tile doors; same seat anchors.`);
