// Manager Chrome captures: every tier, same controls, no game page or storage.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');const{chromium}=require('@playwright/test'),{listen}=require('./browser-errors.cjs');
const here=__dirname,out=path.join(here,'evidence/v2/browser'),url=process.env.FOUNDER_OFFICE_PROOF_URL||'http://127.0.0.1:4191/tools/room-design/level-5/founders-office/proof/index.html',doors=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'];
(async()=>{fs.mkdirSync(out,{recursive:true});const bytes=fs.readFileSync(path.join(here,'proof-manifest.json')),proofManifestSha256=crypto.createHash('sha256').update(bytes).digest('hex');const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1100}}),events=listen(page),captures=[];assert.equal((await page.goto(url)).status(),200);const ready=()=>page.waitForFunction(()=>document.body.dataset.ready==='1');await ready();assert.equal(await page.evaluate(async()=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await(await fetch('./proof-manifest.json')).arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('')),proofManifestSha256);
const states=[['painted',{}],['empty',{actors:false}],['founder',{visitors:false}],['visitor',{founders:false}],['contacts',{contacts:true,bases:true,grid:true}],['all-doors',{routes:true,doors}],['backed',{backed:['N1','N2','N3']}],['shelf-door',{doors:['N1']}],['accent-door',{doors:['EA']}],['decor-door',{doors:['N2']}]];
for(let level=1;level<=5;level++){await page.setViewportSize({width:1440,height:1100});await page.click('#tier'+level);await ready();for(const[id,override]of states){await page.evaluate(async({level,o})=>{const L=window.__lab;L.setTier(level);Object.assign(L.state,{actors:true,founders:true,visitors:true,routes:false,grid:false,contacts:false,bases:false,doors:new Set(),backed:new Set()},o);if(o.doors)L.state.doors=new Set(o.doors);if(o.backed)L.state.backed=new Set(o.backed);L.refreshControls();await L.draw();}, {level,o:override});await ready();const file=`office-level-${level}-${id}.png`;await page.locator('#canvasB').screenshot({path:path.join(out,file)});captures.push({level,id,file,state:override});}
await page.evaluate(async level=>{const L=window.__lab;L.setTier(level);Object.assign(L.state,{actors:true,founders:true,visitors:true,routes:false,grid:false,contacts:false,bases:false,doors:new Set(),backed:new Set()});L.refreshControls();await L.draw();},level);await ready();const desktop=`office-level-${level}-desktop.png`;await page.screenshot({path:path.join(out,desktop),fullPage:true});captures.push({level,id:'desktop',file:desktop});await page.setViewportSize({width:320,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const mobile=`office-level-${level}-320.png`;await page.screenshot({path:path.join(out,mobile),fullPage:true});captures.push({level,id:'320',file:mobile});}
assert.deepEqual(events.errors,[]);fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify({status:'PASS',url,origin:new URL(url).origin,proofManifestSha256,captures,...events,approval:null},null,2)+'\n');console.log('CAPTURE PASS: all 5 tiers; 50 browser room states plus 5 desktop / 5 mobile pages; real page errors 0.');
}finally{await browser.close();}})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify({status:'FAIL',url,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
