// Engineering validation; no art/clinical approval or runtime integration.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const here=__dirname,root=path.dirname(here),repo=path.resolve(root,'../../../..'),out=path.join(here,'evidence/v2'),json=p=>JSON.parse(fs.readFileSync(p,'utf8')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const{createCanvas,loadImage}=require('@napi-rs/canvas'),G=await import('./geometry.mjs'),D=await import('./design-rooms.js'),{loadNativeEngine}=await import('./native-engine.mjs'),layout=json(path.join(root,'layout.json')),gen=json(path.join(root,'assets/generation-manifest.json')),manifest=json(path.join(here,'proof-manifest.json')),data=json(path.join(here,'data.json'));
assert.equal(manifest.approval,null);assert.equal(manifest.runtimeIntegrationAuthorized,false);assert.equal(manifest.mode,'painted');assert.equal(manifest.moraleMechanic,'undecided');assert.deepEqual(manifest.footprint,[3,3]);assert.deepEqual(manifest.appearanceLevels,[1,2,3,4,5]);assert.equal(manifest.layoutSha256,hash(path.join(root,'layout.json')));assert.equal(manifest.prepaintLayoutSha256,hash(path.join(root,'stand-in/v2/layout-prepaint.json')));const prepaint=json(path.join(root,'stand-in/v2/layout-prepaint.json'));assert.deepEqual(layout.room.supports,prepaint.room.supports);assert.deepEqual(layout.presentation.actors,prepaint.presentation.actors);assert.ok(json(path.join(root,'layout-reconciliation-v2.json')).changes.length>=4);assert.equal(manifest.designRoomsSha256,hash(path.join(here,'design-rooms.js')));assert.equal(manifest.dataSha256,hash(path.join(here,'data.json')));assert.equal(manifest.generationManifestSha256,hash(path.join(root,'assets/generation-manifest.json')));assert.equal(gen.assets.length,33);assert.equal(D.DESIGN_TIERS.length,5);
for(const[k,f]of[['rendererSha256','lab.js'],['htmlSha256','index.html'],['extensionSha256','extension.js'],['geometrySha256','geometry.mjs']])assert.equal(manifest[k],hash(path.join(here,f)));
assert.equal(manifest.reconciliationSha256,hash(path.join(root,'layout-reconciliation-v2.json')));
assert.equal(manifest.registrationSha256,hash(path.join(root,'assets/registration-v2.json')));assert.equal(gen.registrationSha256,manifest.registrationSha256);
for(const a of json(path.join(root,'stand-in/v2/manifest.json')).assets)assert.equal(hash(path.join(root,a.file)),a.sha256,'Frozen prepaint stand-in '+a.id);
const html=fs.readFileSync(path.join(here,'index.html'),'utf8');assert.ok(html.includes('3 × 3 room'));assert.ok(html.includes('Owner review pending'));assert.ok(html.includes('Seated adult visitor facing north'));for(let n=1;n<=5;n++)assert.ok(html.includes('id="tier'+n+'"'));assert.ok(!/Proposed 4|base-room candidate|west-facing|Owner-approved|treatment chair/.test(html));
let sourceHashes=0;const concurrentReferenceChanges=[];for(const r of json(path.join(root,'assets/reference-baseline.json')).references){const actual=hash(path.join(repo,r.path));if(actual!==r.sha256){if(/\/proof\/.*\.(?:mjs|js|cjs)$/.test(r.path))concurrentReferenceChanges.push({path:r.path,intakeSha256:r.sha256,currentSha256:actual});else assert.equal(actual,r.sha256,'Shared source preserved '+r.path);}sourceHashes++;}
async function pixels(p){const im=await loadImage(p),c=createCanvas(im.width,im.height),g=c.getContext('2d');g.drawImage(im,0,0);return{im,c,g,data:g.getImageData(0,0,c.width,c.height).data};}
const assetChecks=[];for(const a of gen.assets){assert.equal(a.tool,'image_gen.imagegen');assert.equal(a.transparentBackground,true);for(const [file,expected]of[[a.original,a.originalSha256],[a.prompt,a.promptSha256],[a.receipt,a.receiptSha256]])assert.equal(hash(path.join(root,file)),expected);for(const r of a.rejectedVersions??[]){assert.equal(hash(path.join(root,r.original)),r.originalSha256);assert.equal(hash(path.join(root,r.prompt)),r.promptSha256);}const m=D.PREPARED_METADATA.assets[a.id],p=path.resolve(here,m.file),d=await pixels(p);assert.deepEqual([d.im.width,d.im.height],m.canvas);assert.equal(hash(p),m.outputSha256);assert.equal(m.sourceSha256,a.originalSha256);assert.equal(m.promptSha256,a.promptSha256);assert.equal(m.aspectPreserved,true);assert.equal(m.sourceUpscaled,false);assert.ok(m.transform.scale<=1);let edge=0,zero=0;for(let y=0;y<d.im.height;y++)for(let x=0;x<d.im.width;x++){const alpha=d.data[(y*d.im.width+x)*4+3];if(!alpha)zero++;if(!x||!y||x===d.im.width-1||y===d.im.height-1)edge=Math.max(edge,alpha);}assert.equal(edge,0,'Clear alpha edge '+a.id);assert.ok(zero>200);const b=m.outputAllAlphaBounds;assert.ok(Math.min(b.left,b.top,d.im.width-1-b.right,d.im.height-1-b.bottom)>=4);if(m.sourcePoints.seat){assert.ok(Math.abs(m.measuredSeatRisePixels-45)<1e-9);assert.ok(Math.abs(m.floorRegistrationErrorPixels)<.6);assert.ok(Math.abs(m.canvasAnchor[0]-m.calibratedPoints.seat[0])<1e-9);}assetChecks.push({id:a.id,canvas:m.canvas,sha256:m.outputSha256,alphaEdge:edge,transparentPixels:zero,anchor:m.canvasAnchor,seatRise:m.measuredSeatRisePixels,worktopRise:m.measuredWorktopRisePixels});}
// Source-space foreground selections use the identical chair transform.
let foregrounds=0;for(const m of Object.values(D.PREPARED_METADATA.assets).filter(m=>m.foregroundFor)){
 const base=D.PREPARED_METADATA.assets[m.foregroundFor],b=await pixels(path.resolve(here,base.file)),f=await pixels(path.resolve(here,m.file));
 assert.equal(hash(path.resolve(here,m.file)),m.outputSha256);assert.deepEqual(m.canvas,base.canvas);assert.deepEqual(m.canvasAnchor,base.canvasAnchor);assert.deepEqual(m.calibratedPoints,base.calibratedPoints);assert.deepEqual(m.transform,base.transform);assert.deepEqual([f.im.width,f.im.height],[b.im.width,b.im.height]);
 assert.equal(m.sourceSha256,base.sourceSha256);assert.deepEqual(m.foregroundRegions,base.sourcePoints.frontRegions);
 // Separate clipped resampling can round alpha/colour at a mask boundary.
 // Rear-view visitors redraw the whole chair and must be byte-identical.
 if(m.foregroundFor.includes('visitorChair'))assert.equal(m.outputSha256,base.outputSha256);
 let opaque=0;for(let y=0;y<f.im.height;y++)for(let x=0;x<f.im.width;x++){const a=f.data[(y*f.im.width+x)*4+3];if(a>=160)opaque++;if(!x||!y||x===f.im.width-1||y===f.im.height-1)assert.equal(a,0,'Clear foreground edge '+m.id);}assert.ok(opaque>100);
 foregrounds++;
}assert.equal(foregrounds,10);
const{engine,warnings}=await loadNativeEngine(),tiers=[];let states=0,routes=0,samples=0,monotonicChecks=0;const expectedDoors=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'];
for(const tier of D.DESIGN_TIERS){engine.setTier(tier.level);const room=tier.room,nav=tier.navigation,north=['N1','N2','N3'];assert.deepEqual(room.footprint,[3,3]);assert.deepEqual(G.roomSegments(room),expectedDoors);assert.deepEqual(tier.presentation,layout.presentation);assert.deepEqual(room.supports,layout.room.supports);assert.deepEqual(nav.doorThresholdExceptions,[]);const baseline=layout.room.records.filter(r=>!r.presentIn||r.presentIn.includes(tier.level));assert.equal(room.records.length,baseline.length);for(const r of room.records){const b=baseline.find(b=>b.id===r.id);for(const k of['renderSizeTiles','destinationTopLeftTiles','worldLocalGround','footprint','doorOwners','backedOwners','depthKey','overlayFor'])assert.deepEqual(r[k],b[k],'Shared '+k+' '+r.id);assert.ok(r.assetId.includes('l'+tier.level+'-'));}for(const slot of['desk','founderChair','visitorChair','shelf','rug','decor'])assert.ok(room.records.some(r=>r.id===slot));
const tierSources=gen.assets.filter(a=>a.level===tier.level);assert.equal(tierSources.length,[6,7,6,7,7][tier.level-1]);const p={room,doors:new Set(),backed:new Set(),ox:80,oy:160};
let tierStates=0,tierRoutes=0;for(let mask=0;mask<8;mask++)for(const doors of[[],...expectedDoors.map(s=>[s]),expectedDoors]){const backed=north.filter((_,i)=>mask&(1<<i)),P={room,doors:new Set(doors),backed:new Set(backed)},result=G.check(room,nav,doors,backed,tier.bases);assert.deepEqual(result.unreachable,[],`L${tier.level} ${doors} unreachable`);assert.deepEqual(result.conflicts,[]);assert.deepEqual(result.doorZone,[]);states++;tierStates++;routes+=result.routes;tierRoutes+=result.routes;const blockers=G.fineBlockers(P,nav,tier.bases);for(const r of G.computeRoutes(P,nav,tier.bases))for(let i=1;i<r.walkingPath.length;i++){const a=r.walkingPath[i-1],b=r.walkingPath[i],n=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/.005));for(let k=0;k<=n;k++){assert.equal(G.clearPoint(P,blockers,a[0]+(b[0]-a[0])*k/n,a[1]+(b[1]-a[1])*k/n),true);samples++;}}}
for(const d of expectedDoors){const P={room,doors:new Set([d]),backed:new Set()},blockers=G.fineBlockers(P,nav,tier.bases);for(const other of expectedDoors){const Q={...P,doors:new Set([d,other])};assert.ok(G.fineBlockers(Q,nav,tier.bases).every(b=>blockers.some(c=>c.id===b.id)));monotonicChecks++;}}
// Measured bases must also be clear of all unowned doorway zones.
for(const base of tier.bases){const r=room.records.find(r=>r.id===base.recordId),owners=G.ownersFor(room,{...r,footprint:base.footprint});assert.ok(owners.every(s=>r.doorOwners.includes(s)),'Measured door clearance '+r.id);}
const a=await engine.collectDrawables(p,true),sorted=[...a.sorted].sort((a,b)=>a.py-b.py),index=(id,kind)=>sorted.findIndex(d=>d.id===id&&d.kind===kind),layers=[];
for(const id of['founderChair','visitorChair']){const chair=sorted.find(d=>d.id===id&&d.kind==='fixture'),front=sorted.find(d=>d.id===id+':front'),actor=sorted.find(d=>d.id===id&&d.kind==='actor');assert.ok(index(id,'fixture')<index(id,'actor'));assert.ok(index(id,'actor')<index(id+':front','fixture'));for(const k of['x','y','w','h'])assert.equal(chair[k],front[k]);const c=createCanvas(640,640),g=c.getContext('2d');await engine.drawImageRec(g,actor);const ap=g.getImageData(0,0,640,640).data;g.clearRect(0,0,640,640);await engine.drawImageRec(g,front);const fp=g.getImageData(0,0,640,640).data;let overlap=0,uncovered=0;for(let i=3;i<ap.length;i+=4)if(ap[i]>=250){if(fp[i]>=250)overlap++;else uncovered++;}assert.ok(overlap>=20,'Camera-side foreground '+id);assert.ok(uncovered>=100,'Real adult remains visible '+id);const m=chair.prepared,seatX=chair.x+m.calibratedPoints.seat[0]*chair.w/m.canvas[0],seatY=chair.y+m.calibratedPoints.seat[1]*chair.h/m.canvas[1];assert.ok(Math.abs(seatX-(p.ox+actor.seat.x*120))<1e-8);assert.ok(Math.abs(seatY-(p.oy+actor.seat.y*120))<1e-8);const fit=tier.presentation.actors.find(a=>a.supportId===id);assert.ok(Math.abs(actor.x+fit.seatContactSource[0]*fit.sourceScale-seatX)<1e-8);assert.ok(Math.abs(actor.y+fit.seatContactSource[1]*fit.sourceScale-seatY)<1e-8);layers.push({id,opaqueForegroundOverlap:overlap,uncoveredAdultPixels:uncovered,order:'chair → real adult → camera-side chair foreground',seatRegistered:true});}
assert.ok(index('founderChair','actor')<index('desk','fixture'));assert.ok(index('rug','fixture')<index('founderChair','fixture'));const b=await engine.collectDrawables({...p,backed:new Set(north)},true);for(const id of['shelf',...(room.records.some(r=>r.id==='accent')?['accent']:[])]){const x=[...a.wall,...a.sorted].find(d=>d.id===id),y=[...b.wall,...b.sorted].find(d=>d.id===id);for(const k of['x','y','w','h'])assert.equal(x[k],y[k]);assert.equal(y.clipTop,undefined);}
for(const fit of tier.presentation.actors){const c=data.characters.find(c=>c.id===fit.characterId),pose=c.poses.sit[fit.direction];assert.equal(hash(path.join(repo,'apps/player/public',pose.url)),pose.sha256);assert.equal(pose.width,160);assert.equal(pose.height,320);}assert.equal(tier.presentation.actors[0].direction,'south');assert.equal(tier.presentation.actors[1].direction,'north');tiers.push({level:tier.level,assets:tierSources.length,states:tierStates,routes:tierRoutes,layers});}
let textFiles=0;for(const file of [...walk(root),path.join(repo,'docs/execplans/level5-room-design-20261008.md')])if(/\.(?:md|json|js|mjs|cjs|html|txt|ps1)$/.test(file)){const b=fs.readFileSync(file);assert.ok(!(b[0]===239&&b[1]===187&&b[2]===191),'No UTF-8 BOM '+file);new TextDecoder('utf-8',{fatal:true}).decode(b);textFiles++;}assert.deepEqual(warnings,[]);const report={status:'PASS',approval:null,runtimeIntegrationAuthorized:false,footprint:[3,3],tiers,states,routes,radiusClearSamples:samples,sampleSpacingTiles:.005,actorRadiusTiles:.18,doorSections:12,backingSections:3,monotonicChecks,arbitraryDoorCombinationProof:'Each single-door path is safe with all other optional objects present; more doors remove obstacles. Backing never adds floor obstacles.',assets:33,foregrounds:10,assetChecks,realIdentities:data.characters.map(c=>c.id),sourceHashes,concurrentReferenceChanges,textFiles,warnings,browserQA:'pending manager',proofManifestSha256:hash(path.join(here,'proof-manifest.json'))};fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'validation-report.json'),JSON.stringify(report,null,2)+'\n');console.log(`VALIDATION PASS: 5 tiers; 33 painted assets + 10 chair foregrounds; 2 real stills; ${states} door/backing states; ${routes} routes; ${samples} radius-clear samples at 0.005T; 12 one-tile doors; shared anchors; contacts/layers/alpha/hashes/UTF-8 checked.`);
function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)]);}
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'validation-report.json'),JSON.stringify({status:'FAIL',error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
