// Manager runs Chrome QA. Real errors fail; performance advisories are recorded.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const{chromium}=require('@playwright/test'),{listen}=require('./browser-errors.cjs');
const here=__dirname,out=path.join(here,'evidence/v2'),url=process.env.FOUNDER_OFFICE_PROOF_URL||'http://127.0.0.1:4191/tools/room-design/level-5/founders-office/proof/index.html',doors=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'],north=['N1','N2','N3'];
(async()=>{fs.mkdirSync(out,{recursive:true});const bytes=fs.readFileSync(path.join(here,'proof-manifest.json')),manifest=JSON.parse(bytes),proofManifestSha256=crypto.createHash('sha256').update(bytes).digest('hex');assert.equal(manifest.approval,null);assert.equal(manifest.mode,'painted');assert.deepEqual(manifest.footprint,[3,3]);assert.deepEqual(manifest.appearanceLevels,[1,2,3,4,5]);
const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1100}}),events=listen(page),checks=[],technical=[];assert.equal((await page.goto(url)).status(),200);const ready=()=>page.waitForFunction(()=>document.body.dataset.ready==='1');await ready();
const servedHash=async file=>page.evaluate(async f=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await(await fetch(f)).arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join(''),file);assert.equal(await servedHash('./proof-manifest.json'),proofManifestSha256);assert.equal(await servedHash('./lab.js'),manifest.rendererSha256);assert.equal(await servedHash('./index.html'),manifest.htmlSha256);
const inspect=()=>page.evaluate(()=>{const L=window.__lab,room=L.rooms.get('founders-office'),P={room,doors:L.state.doors,backed:L.state.backed,ox:0,oy:0};return{origin:location.origin,tier:room.tierLevel,state:{...L.state,doors:[...L.state.doors],backed:[...L.state.backed]},visible:room.records.filter(r=>L.recordVisible(r,P)).map(r=>r.id),actors:L.state.actors?L.actorPlacements(P).map(a=>({id:a.id,characterId:a.characterId,direction:a.direction})):[],check:L.check('founders-office',[...L.state.doors],[...L.state.backed]),overflow:document.documentElement.scrollWidth>innerWidth};});
const expectedActors=[{id:'founderChair',characterId:'founder.01',direction:'south'},{id:'visitorChair',characterId:'patient.adult.007',direction:'north'}];assert.equal(await page.locator('#tierButtons button').count(),5);assert.equal(await page.locator('#doorGrid button').count(),12);assert.equal(await page.locator('#backedChips button').count(),3);assert.deepEqual((await page.locator('#doorGrid button').allTextContents()).sort(),doors.slice().sort());checks.push('5 tier / 12 one-tile door / 3 backing buttons; served code and manifest pinned');
for(let level=1;level<=5;level++){await page.click('#tier'+level);await ready();const initial=await inspect();assert.equal(initial.origin,new URL(url).origin);assert.equal(initial.tier,level);assert.equal(initial.state.tier,level);assert.equal(await page.locator('#tier'+level).getAttribute('aria-pressed'),'true');assert.deepEqual(initial.actors,expectedActors);
const result=await page.evaluate(async()=>{const L=window.__lab,room=L.rooms.get('founders-office'),segments=L.roomSegments(room),north=['N1','N2','N3'],failures=[],assets=[],overlaps=[];let states=0,routes=0;
for(let mask=0;mask<8;mask++)for(const open of[[],...segments.map(s=>[s]),segments]){const c=L.check('founders-office',open,north.filter((_,i)=>mask&(1<<i)));states++;routes+=c.routes;if(c.unreachable.length||c.conflicts.length||c.doorZone.length)failures.push({open,mask,c});}
for(const[id,s]of Object.entries(L.assets).filter(([,s])=>s.preparedId.startsWith('l'+L.state.tier+'-'))){const m=L.metadata.assets[s.preparedId],im=new Image();im.src=s.src;await im.decode();if(im.naturalWidth!==m.canvas[0]||im.naturalHeight!==m.canvas[1])failures.push('Canvas size '+id);const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const p=g.getImageData(0,0,c.width,c.height).data;let edge=0,zero=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const a=p[(y*c.width+x)*4+3];if(!a)zero++;if(!x||!y||x===c.width-1||y===c.height-1)edge=Math.max(edge,a);}if(edge||!zero)failures.push('Alpha '+id);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await(await fetch(s.src)).arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==m.outputSha256)failures.push('Served sprite hash '+id);assets.push(id);}
const P={room,doors:new Set(),backed:new Set(),ox:80,oy:160},a=await L.collectDrawables(P,true),b=await L.collectDrawables({...P,backed:new Set(north)},true),sorted=[...a.sorted].sort((a,b)=>a.py-b.py),index=(id,kind)=>sorted.findIndex(d=>d.id===id&&d.kind===kind);
for(const id of['founderChair','visitorChair']){const actor=sorted.find(d=>d.id===id&&d.kind==='actor'),front=sorted.find(d=>d.id===id+':front'),chair=sorted.find(d=>d.id===id&&d.kind==='fixture');if(!(index(id,'fixture')<index(id,'actor')&&index(id,'actor')<index(id+':front','fixture')))failures.push('Seated foreground order '+id);if(['x','y','w','h'].some(k=>chair[k]!==front[k]))failures.push('Foreground registration '+id);const m=chair.prepared,sx=chair.x+m.calibratedPoints.seat[0]*chair.w/m.canvas[0],sy=chair.y+m.calibratedPoints.seat[1]*chair.h/m.canvas[1],fit=L.data.founderPresentation.actors.find(a=>a.supportId===id);if(Math.abs(sx-(P.ox+actor.seat.x*120))>1e-7||Math.abs(sy-(P.oy+actor.seat.y*120))>1e-7||Math.abs(actor.x+fit.seatContactSource[0]*fit.sourceScale-sx)>1e-7||Math.abs(actor.y+fit.seatContactSource[1]*fit.sourceScale-sy)>1e-7)failures.push('Actual seat contact '+id);const c=document.createElement('canvas');c.width=c.height=640;const g=c.getContext('2d',{willReadFrequently:true});await L.drawImageRec(g,actor);const ap=g.getImageData(0,0,640,640).data;g.clearRect(0,0,640,640);await L.drawImageRec(g,front);const fp=g.getImageData(0,0,640,640).data;let n=0,uncovered=0;for(let i=3;i<ap.length;i+=4)if(ap[i]>=250){if(fp[i]>=250)n++;else uncovered++;}if(n<20||uncovered<100)failures.push('Foreground overlap / adult visibility '+id);overlaps.push({id,pixels:n,uncovered});}
if(!(index('founderChair','actor')<index('desk','fixture')))failures.push('Founder behind desk');for(const id of['shelf',...(room.records.some(r=>r.id==='accent')?['accent']:[])]){const x=[...a.wall,...a.sorted].find(d=>d.id===id),y=[...b.wall,...b.sorted].find(d=>d.id===id);if(!x||!y||['x','y','w','h'].some(k=>x[k]!==y[k])||y.clipTop!==undefined)failures.push('Full-height floor furniture '+id);}
return{level:L.state.tier,states,routes,assets,overlaps,failures};});assert.deepEqual(result.failures,[]);assert.equal(result.states,112);assert.equal(result.routes,576);assert.equal(result.assets.length,[8,9,8,9,9][level-1]);technical.push(result);
for(const s of doors){const button=()=>page.locator('#doorGrid button').filter({hasText:new RegExp('^'+s+'$')});await button().click();await ready();const c=await inspect();assert.deepEqual(c.state.doors,[s]);assert.equal(await button().getAttribute('aria-pressed'),'true');assert.equal(c.check.unreachable.length+c.check.conflicts.length+c.check.doorZone.length,0);const ownership=await page.evaluate(()=>window.__lab.rooms.get('founders-office').records.map(r=>({id:r.id,owners:r.doorOwners})));for(const r of ownership)assert.equal(c.visible.includes(r.id),!r.owners.includes(s));await button().click();await ready();assert.deepEqual((await inspect()).visible,initial.visible);}
checks.push('Level '+level+': all routes, alpha/hashes, seated contacts/foregrounds, full-height backing and every door');}
for(const[id,key,count]of[['allDoors','doors',12],['allDoors','doors',12],['closeDoors','doors',0],['allBacked','backed',3],['allBacked','backed',3],['clearBacked','backed',0]]){await page.click('#'+id);await ready();assert.equal((await inspect()).state[key].length,count);}checks.push('bulk controls idempotent');
for(const s of north){await page.locator('#backedChips button').filter({hasText:new RegExp('^'+s+'$')}).click();await ready();const c=await inspect();assert.ok(c.visible.includes('shelf')&&c.visible.includes('accent'));}assert.ok(!(await inspect()).visible.includes('decor'));await page.click('#clearBacked');await ready();checks.push('independent backing; only wall art hides');
for(const[id,count]of[['tgVisitor',1],['tgFounder',1],['tgActors',0]]){await page.uncheck('#'+id);await ready();assert.equal((await inspect()).actors.length,count);await page.check('#'+id);await ready();assert.deepEqual((await inspect()).actors,expectedActors);}checks.push('individual / all real occupants');
await page.click('#allDoors');await ready();await page.click('#allBacked');await ready();await page.check('#tgContacts');await ready();await page.click('#tier3');await ready();const preserved=await inspect();assert.equal(preserved.state.doors.length,12);assert.equal(preserved.state.backed.length,3);assert.equal(preserved.state.contacts,true);assert.deepEqual(preserved.actors,expectedActors);checks.push('tier selection preserves inspection state and seated occupants');
await page.locator('h1').click();for(let n=1;n<=5;n++){await page.keyboard.press(String(n));await ready();assert.equal((await inspect()).state.tier,n);}await page.keyboard.press('ArrowRight');await ready();assert.equal((await inspect()).state.tier,1);await page.keyboard.press('ArrowLeft');await ready();assert.equal((await inspect()).state.tier,5);await page.keyboard.press('Escape');await ready();assert.equal((await inspect()).state.tier,1);
for(const[key,state]of[['g','grid'],['r','routes'],['a','actors'],['p','visitors'],['v','founders'],['c','contacts'],['f','bases']]){const before=(await inspect()).state[state];await page.keyboard.press(key);await ready();assert.equal((await inspect()).state[state],!before);await page.keyboard.press(key);await ready();assert.equal((await inspect()).state[state],before);}await page.keyboard.press('d');await ready();assert.equal((await inspect()).state.doors.length,12);await page.keyboard.press('b');await ready();assert.equal((await inspect()).state.backed.length,3);await page.keyboard.press('Escape');await ready();
await page.locator('#allDoors').focus();await page.keyboard.press('Space');await ready();assert.equal((await inspect()).state.doors.length,12);await page.locator('#closeDoors').focus();await page.keyboard.press('Enter');await ready();assert.equal((await inspect()).state.doors.length,0);await page.locator('#tier5').focus();await page.keyboard.press('Enter');await ready();assert.equal((await inspect()).state.tier,5);checks.push('1–5 / arrows / diagnostics / reset / Space and Enter');
await page.evaluate(()=>[1,5,2,4,3].forEach(n=>document.getElementById('tier'+n).click()));await ready();assert.equal((await inspect()).state.tier,3);assert.ok((await page.locator('#tierHeading').textContent()).startsWith('Level 3'));checks.push('rapid tier selection settles on final level');
await page.setViewportSize({width:320,height:900});for(let level=1;level<=5;level++){await page.click('#tier'+level);await ready();assert.equal((await inspect()).overflow,false);assert.ok(await page.locator('#canvasB').isVisible());}checks.push('all five tiers at 320px without horizontal overflow');assert.deepEqual(events.errors,[]);
fs.writeFileSync(path.join(out,'browser-validation-report.json'),JSON.stringify({status:'PASS',url,origin:new URL(url).origin,proofManifestSha256,checks,technical,...events,approval:null,runtimeIntegrationAuthorized:false},null,2)+'\n');console.log('BROWSER VALIDATION PASS: '+checks.length+' groups; 5 tiers; 12 doors; 560 states / 2880 routes; real seated adults behind foregrounds; keyboard; 320px; real page errors 0.');
}finally{await browser.close();}})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'browser-validation-report.json'),JSON.stringify({status:'FAIL',url,error:e.stack},null,2)+'\n');console.error(e.stack);process.exitCode=1;});
