import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { ATLAS_SCHEMA_VERSION, CELL_SIZE, DIRECTIONS, LAYER_ORDER, PAGE_DEFINITIONS, REQUIRED_SLOT_IDS, REST_PLACEMENT, SLOT_DEFINITIONS, SLOT_IDS, restPlacementForSlot, slotRect } from './schema-v1.mjs';
import { packAtlasPageV1 } from './pack-atlas-v1.mjs';
import { invertRigidTransform, rigidBoneTransform, signedMarkerSide, solveStraightTwoBone, solveTwoBoneIK, transformPoint } from './rigid-geometry.mjs';
import { standardStarJumpArmTarget } from './standard-character-renderer.mjs';
import { validateCharacterAtlasV1 } from './validate-atlas-v1.mjs';

const sha=b=>createHash('sha256').update(b).digest('hex');
function fixtureLandmarks(type){switch(type){case'torso':return{neck:{screenLeft:{x:90,y:70},screenRight:{x:120,y:70}},joint:{shoulder:{left:{x:160,y:90},right:{x:70,y:90}},hip:{left:{x:145,y:190},right:{x:80,y:190}}}};case'upperArm':return{joint:{shoulder:{x:100,y:70},elbow:{x:115,y:175}},orientation:{outerElbow:{x:150,y:120}}};case'forearmHand':return{joint:{elbow:{x:100,y:70},wrist:{x:112,y:145}},hand:{end:{x:120,y:180}},orientation:{thumbTip:{x:150,y:170},anterior:{x:150,y:120}}};case'thigh':return{joint:{hip:{x:100,y:70},knee:{x:115,y:180}},orientation:{outer:{x:150,y:120}}};case'shin':return{joint:{knee:{x:100,y:70},ankle:{x:115,y:180}},orientation:{outer:{x:150,y:120}}};case'shoe':return{registration:{baselineLeft:{x:70,y:185},baselineRight:{x:180,y:185}},joint:{ankle:{x:100,y:80}},entry:{rear:{x:80,y:100},front:{x:130,y:100}},heel:{rear:{x:70,y:145}},toe:{tip:{x:180,y:145}},sole:{contact:{x:120,y:185}}};case'head':return{neck:{screenLeft:{x:90,y:180},screenRight:{x:120,y:180}},coverage:{crown:{x:110,y:50},chin:{x:110,y:160}}};default:throw new Error(type);}}
function validFixture(){const root=mkdtempSync(join(tmpdir(),'standard-atlas-')),pages={},parts={};for(const[pageId,page]of Object.entries(PAGE_DEFINITIONS)){if(!['upper','lower','identity'].includes(pageId))continue;const canvas=createCanvas(page.width,page.height),c=canvas.getContext('2d');c.fillStyle='#777';for(const id of REQUIRED_SLOT_IDS.filter(x=>SLOT_DEFINITIONS[x].page===pageId)){const slot=SLOT_DEFINITIONS[id],r=slotRect(id);c.fillRect(r.x+40,r.y+40,176,176);const landmarks=fixtureLandmarks(slot.type),op=['upperArm','forearmHand','thigh','shin'].includes(slot.type);let orientation;if(op){const paths=slot.type==='upperArm'?['joint.shoulder','joint.elbow','orientation.outerElbow']:slot.type==='forearmHand'?['joint.elbow','hand.end','orientation.anterior']:slot.type==='thigh'?['joint.hip','joint.knee','orientation.outer']:['joint.knee','joint.ankle','orientation.outer'],get=p=>p.split('.').reduce((v,k)=>v[k],landmarks);orientation={markerSign:Math.sign(signedMarkerSide(get(paths[0]),get(paths[1]),get(paths[2])))};}parts[id]={slotId:id,direction:slot.direction,anatomicalSide:slot.anatomicalSide,contentBounds:{x:40,y:40,width:176,height:176},landmarks,orientation,accessories:[],source:{path:'fixture-source.png',sha256:'fixture-sha',derivation:'test-authored',crop:{x:0,y:0,width:200,height:200}}};}const bytes=canvas.toBuffer('image/png'),file=`${pageId}.png`;writeFileSync(join(root,file),bytes);pages[pageId]={file,sha256:sha(bytes)};}return{root,manifest:{schemaVersion:ATLAS_SCHEMA_VERSION,characterId:'fixture.character',capabilities:{sitting:false,clipboard:false},pages,parts,accessoryPolicy:{watch:{anatomicalSide:'left'}},layerOrder:LAYER_ORDER}};}

test('v1 fixed pages, slots, and rest placements are stable',()=>{assert.deepEqual(DIRECTIONS,['south','east','west','north']);assert.equal(PAGE_DEFINITIONS.upper.width,1024);assert.equal(PAGE_DEFINITIONS.upper.height,1280);assert.equal(PAGE_DEFINITIONS.lower.height,1536);assert.equal(PAGE_DEFINITIONS.identity.height,768);assert.equal(PAGE_DEFINITIONS.actions.height,1024);assert.equal(PAGE_DEFINITIONS.clipboard.width,512);assert.equal(SLOT_IDS.length,74);assert.equal(REQUIRED_SLOT_IDS.length,48);assert.deepEqual(slotRect('upper.east.forearmHand.left'),{x:256,y:768,width:256,height:256});assert.deepEqual(REST_PLACEMENT.upperArm.start,{x:128,y:56});assert.deepEqual(restPlacementForSlot('upper.south.torso',80).targetStart,{x:88,y:48});assert.deepEqual(restPlacementForSlot('upper.south.torso',80).targetEnd,{x:168,y:48});for(const direction of DIRECTIONS)assert.deepEqual(restPlacementForSlot(`lower.${direction}.shoe.left`).axis,{x:1,y:0});});
test('valid required base atlas passes real alpha and landmark checks',async()=>{const f=validFixture(),result=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert.deepEqual(result,{ok:true,errors:[]});});
test('linter rejects missing required part with descriptive slot ID',async()=>{const f=validFixture();delete f.manifest.parts['upper.south.torso'];const r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(r.errors.some(x=>x.includes('Missing required part "upper.south.torso"')));});
test('linter rejects NaN and off-alpha landmarks',async()=>{const f=validFixture(),part=f.manifest.parts['upper.south.upperArm.left'];part.landmarks.joint.shoulder={x:Number.NaN,y:70};let r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(r.errors.some(x=>x.includes('finite {x,y}')));part.landmarks.joint.shoulder={x:5,y:5};r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(r.errors.some(x=>x.includes('not within 6px of visible alpha')));});
test('linter rejects duplicate or wrong-side accessories',async()=>{const f=validFixture(),a={id:'watch',anatomicalSide:'left',landmark:{x:120,y:150}};f.manifest.parts['upper.south.upperArm.left'].accessories=[a];f.manifest.parts['upper.south.forearmHand.left'].accessories=[a];f.manifest.parts['upper.south.upperArm.right'].accessories=[a];const r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(r.errors.some(x=>x.includes('Duplicate accessory "watch"')));assert(r.errors.some(x=>x.includes('wrong anatomical side')));});
test('linter permits one anatomical accessory in alternate pose sets and checks its alpha',async()=>{const f=validFixture(),page=PAGE_DEFINITIONS.actions,canvas=createCanvas(page.width,page.height),c=canvas.getContext('2d'),id='actions.south.seatedArm.left',slot=SLOT_DEFINITIONS[id],rect=slotRect(id);c.fillStyle='#777';c.fillRect(rect.x+40,rect.y+40,176,176);const bytes=canvas.toBuffer('image/png'),file='actions.png';writeFileSync(join(f.root,file),bytes);f.manifest.pages.actions={file,sha256:sha(bytes)};f.manifest.parts['upper.south.forearmHand.left'].accessories=[{id:'watch',anatomicalSide:'left',landmark:{x:120,y:150}}];const landmarks={joint:{shoulder:{x:100,y:70},elbow:{x:110,y:120},wrist:{x:115,y:160}},hand:{contact:{x:120,y:180}},orientation:{thumbTip:{x:150,y:150}}};f.manifest.parts[id]={slotId:id,direction:'south',anatomicalSide:'left',contentBounds:{x:40,y:40,width:176,height:176},landmarks,orientation:{markerSign:-1},accessories:[{id:'watch',anatomicalSide:'left',landmark:{x:120,y:150}}],source:{path:'fixture-source.png',sha256:'fixture-sha',derivation:'test-authored',crop:{x:0,y:0,width:200,height:200}}};let r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(!r.errors.some(x=>x.includes('Duplicate accessory "watch"')));f.manifest.parts[id].accessories[0].landmark={x:5,y:5};r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(r.errors.some(x=>x.includes('not within 6px of visible part alpha')));});
test('linter rejects visible art hidden in an unused fixed slot',async()=>{const f=validFixture(),path=join(f.root,'identity.png'),image=await loadImage(path),canvas=createCanvas(image.width,image.height),c=canvas.getContext('2d');c.drawImage(image,0,0);const rect=slotRect('identity.south.backHair');c.fillStyle='#777';c.fillRect(rect.x+80,rect.y+80,40,40);const bytes=canvas.toBuffer('image/png');writeFileSync(path,bytes);f.manifest.pages.identity.sha256=sha(bytes);const r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(r.errors.some(x=>x.includes('Unused slot "identity.south.backHair" contains visible alpha')));});
test('sitting requires lower bodies and explicit override fallbacks',async()=>{const f=validFixture();f.manifest.capabilities.sitting=true;const r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(r.errors.some(x=>x.includes('actions.south.seatedLower')));assert(r.errors.some(x=>x.includes('Missing seated override "actions.south.seatedTorso"')));});
test('linter rejects collinear orientation marker',async()=>{const f=validFixture(),part=f.manifest.parts['upper.south.upperArm.left'];part.landmarks.orientation.outerElbow={x:110,y:140};const r=await validateCharacterAtlasV1(f.manifest,{root:f.root,throwOnError:false});assert(r.errors.some(x=>x.includes('collinear or too close')));});
test('rigid landmark transform round trips and stays uniform',()=>{const m=rigidBoneTransform({sourceStart:{x:10,y:20},sourceEnd:{x:10,y:60},targetStart:{x:90,y:30},targetEnd:{x:130,y:30}}),inverse=invertRigidTransform(m),point={x:17,y:41},round=transformPoint(inverse,transformPoint(m,point));assert(Math.abs(round.x-point.x)<1e-9);assert(Math.abs(round.y-point.y)<1e-9);assert(Math.abs(Math.hypot(m.a,m.b)-Math.hypot(m.c,m.d))<1e-12);});
test('two-bone IK preserves segment lengths and bend sign',()=>{for(const sign of [-1,1]){const solved=solveTwoBoneIK({shoulder:{x:0,y:0},target:{x:60,y:25},upperLength:45,forearmLength:40,bendSign:sign});assert(Math.abs(Math.hypot(solved.elbow.x,solved.elbow.y)-45)<1e-6);assert(Math.abs(Math.hypot(solved.wrist.x-solved.elbow.x,solved.wrist.y-solved.elbow.y)-40)<1e-6);assert.equal(Math.sign(signedMarkerSide(solved.shoulder,solved.wrist,solved.elbow)),sign);}});
test('shared star-jump directions keep differently sized arm chains straight and mirrored',()=>{for(const lengths of [{upper:42,forearm:29},{upper:30,forearm:24}])for(const stage of ['gather','takeoff','opening','open-star','closing','soft-landing','recover']){const profile={armLengths:lengths},leftShoulder={x:100,y:120},rightShoulder={x:60,y:120},left=standardStarJumpArmTarget({shoulder:leftShoulder,side:'left',stage,profile}),right=standardStarJumpArmTarget({shoulder:rightShoulder,side:'right',stage,profile}),chain=solveStraightTwoBone({shoulder:leftShoulder,target:left.target,upperLength:lengths.upper,forearmLength:lengths.forearm});assert(Math.abs((left.target.x-leftShoulder.x)+(right.target.x-rightShoulder.x))<1e-9);assert(Math.abs(left.target.y-right.target.y)<1e-9);assert(Math.abs(Math.hypot(chain.elbow.x-chain.shoulder.x,chain.elbow.y-chain.shoulder.y)-lengths.upper)<1e-9);assert(Math.abs(Math.hypot(chain.wrist.x-chain.elbow.x,chain.wrist.y-chain.elbow.y)-lengths.forearm)<1e-9);assert(Math.abs(signedMarkerSide(chain.shoulder,chain.wrist,chain.elbow))<1e-9);assert.equal(chain.wrist.y<chain.shoulder.y,['opening','open-star','closing'].includes(stage));}});
test('packer validates authored source alpha and applies canonical uniform transform',async()=>{const root=mkdtempSync(join(tmpdir(),'standard-pack-')),source=createCanvas(200,220),c=source.getContext('2d');c.fillStyle='#888';c.fillRect(40,30,120,180);const sourceFile=join(root,'arm.png'),bytes=source.toBuffer('image/png');writeFileSync(sourceFile,bytes);const landmarks=fixtureLandmarks('upperArm'),packed=await packAtlasPageV1({pageId:'upper',parts:{'upper.south.upperArm.left':{source:{path:sourceFile,sha256:sha(bytes),derivation:'test-authored',crop:{x:30,y:20,width:140,height:200}},landmarks,orientation:{markerSign:Math.sign(signedMarkerSide(landmarks.joint.shoulder,landmarks.joint.elbow,landmarks.orientation.outerElbow))},accessories:[],normalization:{targetLength:90}}},outputFile:join(root,'upper.png')});assert.equal(packed.canvas.width,1024);assert.equal(packed.parts['upper.south.upperArm.left'].normalization.kind,'uniform-rigid');assert.deepEqual(packed.parts['upper.south.upperArm.left'].landmarks.joint.shoulder,REST_PLACEMENT.upperArm.start);assert.equal(readFileSync(join(root,'upper.png')).length,packed.bytes.length);});
test('packer rejects crop-neighbor landmark matches',async()=>{const root=mkdtempSync(join(tmpdir(),'standard-crop-')),source=createCanvas(240,220),c=source.getContext('2d');c.fillStyle='#888';c.fillRect(10,20,80,190);c.fillRect(130,20,80,190);const file=join(root,'parts.png'),bytes=source.toBuffer('image/png');writeFileSync(file,bytes);const landmarks=fixtureLandmarks('upperArm');await assert.rejects(packAtlasPageV1({pageId:'upper',parts:{'upper.south.upperArm.left':{source:{path:file,sha256:sha(bytes),derivation:'test',crop:{x:0,y:0,width:100,height:220}},landmarks,normalization:{targetLength:80}}}}),/outside its explicit crop/);});
test('packer rejects transformed alpha that clipping would discard',async()=>{const root=mkdtempSync(join(tmpdir(),'standard-overflow-')),source=createCanvas(240,240),c=source.getContext('2d');c.fillStyle='#888';c.fillRect(1,1,238,238);const file=join(root,'large.png'),bytes=source.toBuffer('image/png');writeFileSync(file,bytes);const landmarks=fixtureLandmarks('upperArm');await assert.rejects(packAtlasPageV1({pageId:'upper',parts:{'upper.south.upperArm.left':{source:{path:file,sha256:sha(bytes),derivation:'test',crop:{x:0,y:0,width:240,height:240}},landmarks,normalization:{targetLength:150}}}}),/would discard visible source pixels/);});
test('packer rejects a substantial disconnected contaminant in an isolated upper-part crop',async()=>{const root=mkdtempSync(join(tmpdir(),'standard-component-')),source=createCanvas(220,220),c=source.getContext('2d');c.fillStyle='#888';c.fillRect(75,25,80,175);c.fillRect(10,25,35,80);const file=join(root,'contaminated.png'),bytes=source.toBuffer('image/png');writeFileSync(file,bytes);const landmarks=fixtureLandmarks('upperArm');await assert.rejects(packAtlasPageV1({pageId:'upper',parts:{'upper.south.upperArm.left':{source:{path:file,sha256:sha(bytes),derivation:'test',crop:{x:0,y:0,width:220,height:220},requireSingleComponent:true},landmarks,normalization:{targetLength:80}}}}),/second disconnected component/);});
