import { buildFamily, type ConceptSpec, type FamilySpec, type VariantSpec } from "./family-builder";
import { ETHICS_SOURCES } from "./ethics-source-catalog";
type Wrong = [string, string];
type Story = { complaint:string; body:string; task:string; key:string; why:string; wrong:[Wrong,Wrong,Wrong]; spanish?:boolean; sources?:Array<keyof typeof ETHICS_SOURCES> };
type Topic = { id:string; title:string; objective:string; sources:Array<keyof typeof ETHICS_SOURCES>; stories:[Story,Story,Story,Story] };
// Original fictional cases. Keys are first only in this authoring artifact; runtime shuffles.
const topics: Topic[] = [
{ id:"qualified-interpreter", title:"Use qualified interpretation", objective:"Arrange qualified interpretation when language discordance prevents an informed clinical discussion.", sources:["interpreterAhrq","interpreterHhs","consent"], stories:[
{complaint:"Consent discussion",spanish:true,body:"{patientName}, una mujer de {patientAge} años, viene a hablar de una operación electiva de hernia. Dice: «No entiendo el formulario en inglés». Está estable; el cirujano no habla español. Su hijo de diez años ofrece traducir.",task:"How should you begin the elective surgical consent discussion?",key:"Arrange qualified Spanish interpretation",why:"Qualified interpretation supports meaningful consent when patient and clinician cannot communicate adequately. A child's offer does not establish interpreter competence.",wrong:[["Ask the child to translate the consent","The child is not qualified for this complex discussion."],["Read the entire English consent form more slowly","Slower English does not resolve language discordance."],["Accept a signature on the English form","A signature does not establish understanding of an unreadable form."]]},
{complaint:"Biopsy questions",spanish:true,body:"{patientName}, una mujer de {patientAge} años, consulta por una biopsia cutánea electiva. Pregunta: «¿Me quitarán toda la lesión?». El médico solo habla inglés. Una aplicación traduce la pregunta de forma confusa; la paciente sigue sin entender.",task:"What should you arrange before continuing the biopsy consent discussion?",key:"A qualified interpreter for the discussion",why:"When automated translation leaves important uncertainty, qualified interpretation supports an understandable consent discussion.",wrong:[["A signature using the translated application","The confusing translation has not supported understanding."],["A louder explanation using English words","Volume does not repair language discordance."],["A family signature replacing the discussion","Language discordance does not transfer a capable adult's decision to family."]]},
{complaint:"Operation questions",spanish:true,body:"{patientName}, una mujer de {patientAge} años, llega a una consulta electiva por cálculos biliares. El cirujano no habla español. Su pareja contesta todas las preguntas; ella dice: «Quiero hablar yo y hacer mis propias preguntas».",task:"What best supports this patient's participation in the surgical discussion?",key:"Offer a qualified Spanish interpreter",why:"Qualified interpretation supports the patient's own questions and decisions when accurate independent communication is lacking; family participation does not automatically replace it.",wrong:[["Ask the partner to make the decision","No incapacity or authorization to replace the patient is stated."],["Use the partner's answers as consent","The patient wants to participate and ask questions."],["Postpone discussion until English is learned","Qualified interpretation can address the current communication barrier."]]},
{complaint:"Treatment discussion",spanish:true,body:"{patientName}, una mujer de {patientAge} años, está estable y quiere discutir la extirpación de un quiste. No comprende inglés. El cirujano tampoco comprende español; una recepcionista conoce algunas frases, pero no está capacitada para interpretar información clínica.",task:"Which communication support is appropriate before obtaining procedural consent?",key:"Use a qualified medical interpreter",why:"Knowing a few phrases does not establish the ability to interpret complex clinical information accurately and impartially.",wrong:[["Use the receptionist's limited Spanish","This employee is explicitly not qualified for clinical interpretation."],["Use gestures while signing the form","Gestures do not establish understanding of risks and alternatives."],["Use an English handout as consent","The patient cannot understand the English material."]]}
]},
{ id:"informed-consent",title:"Make consent understandable and voluntary",objective:"Correct missing understanding, alternatives or voluntariness before elective procedural consent.",sources:["consent","interpreterAhrq"],stories:[
{sources:["consent"],complaint:"Procedure questions",body:"brings a signed cyst-removal form but says, 'I signed at reception; nobody explained what could go wrong.' The elective procedure has not started, and there is time to discuss options.",task:"What should happen before the elective cyst removal?",key:"Discuss risks, benefits, and alternatives",why:"Consent requires an understandable discussion of the intervention, relevant risks and benefits, and alternatives including foregoing treatment; a signature alone is insufficient.",wrong:[["Proceed using the existing signed form","The signature does not replace the missing discussion."],["Have reception witness a second signature","Another signature does not supply clinical information."],["Ask a relative to endorse the form","A capable patient's informed decision is needed, not a relative's endorsement."]]},
{sources:["consent"],complaint:"Hernia options",body:"asks whether declining elective hernia repair is an option. The booking conversation covered only the preferred operation; the patient is stable and has not decided.",task:"How should you address the unanswered consent question?",key:"Discuss alternatives, including no operation",why:"An informed decision includes relevant alternatives and the implications of foregoing the proposed intervention, tailored to the patient's situation.",wrong:[["Limit discussion to the preferred operation","Preference does not justify withholding relevant alternatives."],["Book surgery before discussing other options","The patient has not made an informed choice."],["Have the insurer select the treatment option","Coverage decisions do not replace the patient's informed choice."]]},
{complaint:"Consent confusion",body:"nods through a lesion-excision explanation, then asks whether the signed form guarantees no scar. The elective procedure has not begun and there is time to clarify.",task:"What best addresses the misunderstanding before proceeding?",key:"Clarify scarring and ask for teach-back",why:"A demonstrated misunderstanding should be addressed before relying on consent. Asking the patient to explain the plan in their own words helps assess understanding.",wrong:[["Rely on the nodding and signed form","The question reveals a material misunderstanding."],["Promise that careful technique prevents scarring","Consent should not use an unsupported guarantee."],["Save clarification for after the excision","The misunderstanding matters before the intervention."]]},
{sources:["consent"],complaint:"Decision pressure",body:"says a companion threatened to stop providing rides unless the patient accepts elective lipoma removal. In private the patient says, 'I do not want this removed.' No urgent medical need exists.",task:"How should you respond to the pressured consent?",key:"Pause and support a voluntary decision",why:"Consent must be voluntary; a refusal expressed under coercive pressure should prompt protection of the patient's choice rather than reliance on a pressured signature.",wrong:[["Proceed after the companion signs the form","A companion cannot override this capable patient's refusal."],["Ask the companion to increase the pressure","More coercion further undermines voluntariness."],["Proceed because transportation is important","Dependency does not make coerced consent valid."]]}
]},
{ id:"capacity-refusal",title:"Respect capable refusal",objective:"Distinguish an unwelcome choice from impaired decision-making capacity.",sources:["consent","capacity"],stories:[
{complaint:"Declining surgery",body:"declines elective hernia repair after explaining its benefits, risks, alternatives and consequences of refusal accurately. The patient gives consistent personal reasons; the surgeon strongly disagrees.",task:"How should you respond to this informed refusal?",key:"Respect refusal and discuss follow-up",why:"Disagreement with a recommendation does not itself establish incapacity. A capable adult's informed refusal should be respected.",wrong:[["Declare incapacity because surgery was refused","Disagreement alone is not a capacity assessment."],["Seek family permission to override refusal","Family cannot replace the capable patient's decision merely because clinicians disagree."],["Schedule the operation despite the refusal","The refusal does not authorize elective surgery."]]},
{complaint:"Consent reassessment",body:"arrives for an elective procedure newly confused, cannot explain its purpose after repeated explanations, and gives rapidly changing answers. A signed consent from an earlier visit is in the chart.",task:"What should happen before this elective procedure?",key:"Pause and assess current capacity",why:"Capacity concerns the present decision and can change. New confusion and inability to understand warrant assessment before an elective intervention.",wrong:[["Proceed solely on the earlier signed form","New impairment requires attention before relying on earlier consent."],["Treat any spoken yes as current consent","Assent without adequate understanding is insufficient."],["Ask reception to choose the treatment","A clerk's choice cannot replace appropriate assessment."]]},
{complaint:"Treatment refusal",body:"has treated depression and declines elective scar revision. The patient explains the options accurately, appreciates their personal effects, reasons coherently and communicates a stable choice.",task:"What does the psychiatric history imply for this refusal?",key:"It does not by itself negate capacity",why:"A diagnosis alone does not establish incapacity; assessment concerns abilities for the specific decision. The described abilities support respecting refusal.",wrong:[["It automatically transfers consent to family","Psychiatric history alone does not confer surrogate authority."],["It makes every treatment refusal invalid","Refusal is not proof of impaired decision-making."],["It removes the need to discuss alternatives","The patient still deserves an informed discussion."]]},
{complaint:"Decision assistance",body:"has mild cognitive impairment and wants a skin lesion removed. With plain-language explanation, the patient describes its purpose, risks and alternatives, applies them personally, and consistently chooses removal.",task:"How should consent authority be approached for this decision?",key:"Assess and support the patient's own decision",why:"Cognitive impairment does not eliminate capacity for every decision. Support understanding and assess actual abilities before seeking a substitute decision-maker.",wrong:[["Automatically replace the patient with a surrogate","A diagnostic label does not outweigh demonstrated decision-making abilities."],["Skip consent because the procedure is small","An elective minor procedure still requires consent."],["Let the receptionist decide for convenience","Convenience does not determine consent authority."]]}
]},
{ id:"surrogate-decisions",title:"Guide surrogates using patient values",objective:"Apply known patient preferences, or best interests when preferences cannot be determined.",sources:["capacity"],stories:[
{complaint:"Care planning",body:"cannot make the current treatment decision. The authorized surrogate recalls specific discussions in which the patient rejected the proposed treatment in these circumstances, although the surrogate personally favors it.",task:"Which consideration should guide the surrogate's decision?",key:"The patient's known treatment preferences",why:"Substituted judgment uses the patient's known preferences and values rather than the surrogate's own treatment preference.",wrong:[["The surrogate's personal treatment preference","The surrogate represents the patient rather than personal wishes."],["The preference of the largest family group","A family vote does not outweigh known patient wishes."],["The option generating the highest clinic fee","Clinic revenue is not a patient-centered decision standard."]]},
{complaint:"Surrogate consultation",body:"lacks capacity for a proposed intervention. Despite reasonable efforts, the authorized surrogate and team cannot identify prior wishes or relevant values; they must consider likely benefits, burdens and suffering.",task:"Which standard should now guide the surrogate's decision?",key:"The patient's best interests",why:"When patient preferences and values cannot be determined, surrogate deliberation should focus on the patient's best interests, including benefits and burdens.",wrong:[["The surrogate's financial interests","The decision should serve the patient, not surrogate finances."],["The clinician's personal life preferences","Personal clinician preferences do not establish patient best interests."],["The family's majority preference alone","A vote alone does not assess benefits and burdens."]]},
{complaint:"Family disagreement",body:"lacks capacity and has clearly documented wishes against the proposed treatment. The authorized surrogate requests it anyway; discussion has not resolved the conflict, and there is no immediate emergency.",task:"What should the team do about this unresolved conflict?",key:"Seek ethics support to protect patient wishes",why:"Unresolved conflict between a surrogate request and known patient wishes warrants appropriate institutional ethics support rather than automatic compliance.",wrong:[["Follow the surrogate request without discussion","Surrogate authority does not erase documented preferences."],["Ignore the documented wishes for convenience","Convenience does not justify abandoning patient values."],["Let a family majority override the directive","A family vote does not supersede the patient's known preferences."]]},
{sources:["capacity"],complaint:"Supported planning",body:"lacks capacity for a complex treatment decision but can express comfort concerns and simple preferences. The authorized surrogate asks whether the patient should leave while the team decides.",task:"How should the patient participate in this discussion?",key:"Include the patient to the extent possible",why:"Even when a surrogate must decide, patients should participate to the extent their abilities permit, with attention to their expressed preferences.",wrong:[["Exclude the patient from every discussion","Lack of capacity for one complex choice does not eliminate all participation."],["Require the patient to decide without support","The scenario establishes a need for surrogate help."],["Replace the surrogate with a clinic clerk","Administrative convenience does not authorize replacing a surrogate."]]}
]},
{id:"perioperative-dnr",title:"Reconsider perioperative resuscitation plans",objective:"Clarify an individualized perioperative resuscitation plan instead of automatically suspending DNR orders.",sources:["dnarAsa","dnarAma"],stories:[
{complaint:"Preoperative planning",body:"has a DNR order and attends a consultation before an elective hospital operation. A checklist says every DNR order disappears upon entering the operating room; the patient asks whether this is required.",task:"How should the perioperative resuscitation plan be established?",key:"Discuss and document the patient's preferences",why:"Perioperative DNR orders require individualized review with the patient or surrogate and responsible clinicians; automatic suspension bypasses self-determination.",wrong:[["Automatically suspend DNR for every operation","A blanket policy replaces the individualized discussion."],["Automatically cancel surgery for every DNR","DNR does not automatically preclude an operation."],["Adopt a standard plan without patient discussion","A standard plan may not reflect this patient's preferences."]]},
{complaint:"Anesthesia preferences",body:"wants an elective hospital operation while retaining some resuscitation limits. The patient asks which interventions are integral to anesthesia and which respond to an unexpected arrest.",task:"What should the team do with these requested limits?",key:"Clarify feasible limits and document the plan",why:"The team should clarify requested interventions in the context of anesthesia, identify essential procedures, and document an agreed individualized plan.",wrong:[["Promise every limit without anesthesia review","Some interventions are integral to the planned anesthesia and need clarification."],["Erase all limits without asking the patient","Unilateral removal bypasses expressed preferences."],["Leave all interpretation until an arrest occurs","Deferring a foreseeable discussion risks inconsistent emergency decisions."]]},
{complaint:"Postoperative planning",body:"agrees to a temporary, specifically documented modification of a DNR order for a hospital operation. The preoperative note does not state when the original limits resume.",task:"What detail should be clarified before the operation?",key:"When the original resuscitation limits resume",why:"Perioperative planning should document when the original directive will be reinstated so temporary modifications do not silently become indefinite.",wrong:[["Whether the original directive should be destroyed","Temporary modification does not require destroying the original directive."],["Whether future admissions automatically suspend DNR","A current discussion does not authorize blanket suspension at future admissions."],["Whether temporary changes automatically last forever","The duration should be agreed and documented, not assumed indefinite."]]},
{complaint:"Treatment concerns",body:"has a DNR order and asks whether the clinic will refuse ordinary symptom treatment. The patient has not declined other care and wants active treatment consistent with personal goals.",task:"What does the DNR order alone limit?",key:"Resuscitation after cardiopulmonary arrest",why:"DNR concerns resuscitative efforts after arrest; it does not by itself prohibit other appropriate treatment consistent with patient goals.",wrong:[["Every treatment for pain or discomfort","Symptom relief is not automatically prohibited by DNR status."],["Every diagnostic discussion or consultation","DNR alone does not remove access to evaluation."],["Every opportunity for elective treatment","Other treatment decisions require their own goals-based discussion."]]}
]},
{id:"error-disclosure",title:"Disclose errors and address safety",objective:"Communicate material errors honestly while arranging appropriate care and avoiding unsupported blame.",sources:["safety"],stories:[
{complaint:"Result follow-up",body:"returns after a verified clinic routing error delayed a biopsy report. Appropriate follow-up is being arranged. A colleague proposes telling the patient only that 'the computer was slow.'",task:"How should the verified error be discussed?",key:"Explain the error and the corrective plan",why:"Patients should receive honest information about errors affecting care, including known implications and steps to address them, rather than a misleading explanation.",wrong:[["Attribute the delay to an unverified computer fault","An invented explanation conceals the known error."],["Wait until the patient discovers the routing error","Disclosure should not depend on independent discovery."],["Remove the routing history before discussing care","Concealing records obstructs transparency and safety improvement."]]},
{complaint:"Medication concern",body:"has just received an unintended medication in clinic and develops symptoms. The team recognizes the error; a staff member wants everyone to finish an incident form before calling for clinical help.",task:"What should take priority in responding to the error?",key:"Provide prompt clinical assessment and care",why:"Immediate patient safety and appropriate treatment take priority; candid disclosure and reporting accompany the response rather than delaying needed care.",wrong:[["Complete all paperwork before assessing symptoms","Reporting must not delay necessary clinical attention."],["Ask the patient to leave before any discussion","Sending a symptomatic patient away evades the safety response."],["Assign individual blame before arranging assistance","Assigning blame does not address the immediate patient need."]]},
{complaint:"Care explanation",body:"asks why a specimen was lost. The clinic has verified the loss but not its cause. A supervisor suggests blaming a courier because 'that is probably what happened.'",task:"What should the initial disclosure communicate?",key:"Known facts, uncertainty, and next steps",why:"Disclosure should distinguish verified facts from uncertainty and explain the care and investigation plan; unverified blame is not a factual explanation.",wrong:[["The courier theory as an established fact","The cause has not been verified."],["A guarantee that no consequence is possible","Uncertain consequences cannot honestly be excluded by a guarantee."],["Only the details favorable to the clinic","Selective concealment prevents an accurate understanding."]]},
{complaint:"Chart correction",body:"learns that an important recommendation was placed in the wrong chart and used during this patient's care discussion. The error was intercepted before treatment. A clinician asks whether absence of injury eliminates any need to explain.",task:"How should this material care-information error be handled?",key:"Explain the error and its correction",why:"An error materially affecting care information can warrant honest disclosure even without demonstrated injury; absence of harm is not a blanket reason for concealment.",wrong:[["Hide the error because no injury occurred","Lack of injury does not make material care information irrelevant."],["Delete all evidence of the original entry","Concealment is not transparent correction."],["Promise compensation before establishing the facts","An unsupported compensation promise does not replace accurate disclosure."]]}
]},
{id:"impaired-colleague",title:"Protect patients when a colleague may be impaired",objective:"Respond to credible impairment concerns with immediate safety measures and appropriate assessment or assistance.",sources:["impairment"],stories:[
{complaint:"Procedure safety",body:"waits for an elective procedure. The assigned clinician is newly stumbling, slurring speech and unable to follow the setup checklist. Qualified coverage is available; the cause of the change is unknown.",task:"What is the safest immediate response to this clinician's behavior?",key:"Arrange safe coverage and urgent assessment",why:"Observable inability to practice safely warrants patient protection and appropriate assessment; the cause should not be assumed from behavior alone.",wrong:[["Allow the procedure while quietly observing","Observation does not adequately address credible immediate safety concerns."],["Assume intoxication and announce it publicly","The cause is unconfirmed and accusation does not arrange safe care."],["Wait for an actual injury before intervening","Protection should precede avoidable injury."]]},
{complaint:"Follow-up safety",body:"reports missed instructions from a clinician. The team has also documented recent confusion that could compromise care. A supervisor proposes keeping these concerns secret to protect the clinician's reputation.",task:"How should the documented safety concern be addressed?",key:"Arrange appropriate assessment and reporting",why:"Credible concerns about impaired practice should prompt appropriate assessment, patient protection and reporting according to the setting, while supporting the colleague.",wrong:[["Suppress the concern to preserve the reputation","Reputation does not justify ignoring safety concerns."],["Wait for definitive proof before arranging coverage","Credible safety concerns warrant protective action while appropriate assessment proceeds."],["Offer private reassurance without safety follow-up","Support alone is insufficient if ongoing practice may compromise patient safety."]]},
{complaint:"Clinician reassurance",body:"asks whether a clinician's visible hand disability makes care unsafe. The clinician uses appropriate accommodations, fulfills the relevant duties safely, and has no observed performance concerns.",task:"What conclusion follows from the stated information?",key:"Disability alone does not establish unsafe practice",why:"Illness or disability is not synonymous with impairment. Decisions should concern actual ability to perform duties safely, including appropriate accommodations.",wrong:[["Any visible disability requires immediate dismissal","A disability label does not establish inability to practice safely."],["Appearance alone proves current clinical impairment","Appearance is not evidence of unsafe professional performance."],["Patient concern eliminates the need for assessment","Concerns should be addressed fairly using relevant performance information."]]},
{complaint:"Coverage concern",body:"awaits an elective procedure when the clinician privately says a current illness prevents safe concentration and requests relief. Qualified coverage is available.",task:"How should the team respond to this request?",key:"Arrange coverage and support appropriate care",why:"A clinician recognizing inability to practice safely should be supported in obtaining coverage and appropriate assistance, with patient protection as the priority.",wrong:[["Insist the clinician proceed to avoid embarrassment","Avoiding embarrassment does not justify unsafe performance."],["Treat the admission as permission to tell everyone","Appropriate assistance does not require indiscriminate disclosure."],["Permanently dismiss the clinician without assessment","Permanent decisions should not be assumed from a current need for support."]]}
]},
{id:"research-consent",title:"Protect voluntary research participation",objective:"Keep research enrollment informed and voluntary, separate from entitlement to ordinary care.",sources:["research","consent"],stories:[
{complaint:"Study invitation",body:"is offered an optional study during a surgical consultation. A recruiter says ordinary clinic care is available only if the patient enrolls, although this study is not required for that care.",task:"What should be clarified about the enrollment decision?",key:"Declining the study will not forfeit ordinary care",why:"Research participation must be voluntary; ordinary care should not be contingent on joining an optional study.",wrong:[["Signing the study form is required for all care","That condition undermines voluntary participation."],["The recruiter may consent on the patient's behalf","A recruiter cannot substitute their choice for a capable adult."],["The clinic consent form automatically enrolls patients","Clinical consent does not establish informed agreement to research."]]},
{complaint:"Research questions",body:"has consented to elective cyst removal. A coordinator proposes an extra research-only tissue sampling procedure under the same signature; its purpose, additional procedure and voluntary nature have not been discussed.",task:"What is needed before the additional research procedure?",key:"An appropriate research consent process",why:"Consent to clinical treatment does not automatically authorize an additional research-only procedure; applicable research consent and oversight requirements must be met.",wrong:[["Only the existing clinical-treatment signature","The additional research procedure was not covered by an informed research discussion."],["A research signature after taking the sample","Retrospective paperwork does not replace required prospective consent."],["Only the coordinator's verbal authorization","A coordinator's approval cannot replace participant consent requirements."]]},
{complaint:"Study expectations",body:"considers a randomized study and says, 'My surgeon will put me in whichever arm is best for me.' The approved protocol uses random allocation, and no arm is guaranteed better.",task:"What misunderstanding should be corrected before enrollment?",key:"Assignment is random and benefit is uncertain",why:"Research consent should explain allocation and uncertainty so participants do not mistake the protocol for individually selected treatment with guaranteed benefit.",wrong:[["The surgeon will personally select the superior arm","That promise contradicts random allocation and uncertain benefit."],["Enrollment guarantees a better personal outcome","Research participation does not guarantee therapeutic benefit."],["Random allocation can be omitted from discussion","Allocation is material information for this enrollment decision."]]},
{complaint:"Leaving a study",body:"wants to withdraw from a voluntary study and continue ordinary clinical follow-up. The coordinator threatens to cancel unrelated clinic appointments unless participation continues.",task:"How should you respond to the threatened loss of care?",key:"Protect voluntary withdrawal and ordinary follow-up",why:"Participants should be able to withdraw without coercive loss of ordinary care; clinical follow-up can be discussed separately from continued participation.",wrong:[["Enforce the threat to retain the participant","Threatening unrelated care undermines voluntariness."],["Treat the original signature as irrevocable consent","Initial consent does not make participation compulsory."],["Ask relatives to force continued participation","Family pressure does not replace voluntary choice."]]}
]},
{id:"qi-versus-research",title:"Seek appropriate QI and research oversight",objective:"Classify projects by purpose and methods rather than labels or publication plans alone.",sources:["qi"],stories:[
{complaint:"Project questions",body:"asks about a local clinic reminder project. Its team plans a journal article and claims that publication automatically makes the activity human-subjects research.",task:"What is the best response to this classification claim?",key:"Publication plans alone do not determine classification",why:"Publication intent alone does not determine whether an activity is research; purpose, design and applicable definitions require appropriate institutional assessment.",wrong:[["Every published project is automatically research","Publication can describe activities that are not research under applicable definitions."],["Every unpublished project is exempt from oversight","An unpublished activity may still meet research criteria."],["The journal editor alone decides institutional oversight","The institution must apply the relevant oversight requirements."]]},
{complaint:"Data project consent",body:"is invited into a project labeled 'QI' that adds an experimental intervention to test a generalizable hypothesis. The organizer says that label means no institutional assessment is needed.",task:"How should the clinic address this assumption?",key:"Seek institutional assessment of the project",why:"Calling a project QI does not exempt an activity that may also be human-subjects research; institutional review should determine applicable requirements.",wrong:[["Accept the QI label as an automatic exemption","A label does not establish substantive classification."],["Let the organizer waive participant protections","An organizer cannot simply waive applicable requirements."],["Wait until publication to ask about oversight","Applicable oversight should be addressed before the relevant activity begins."]]},
{complaint:"Workflow project",body:"asks why the clinic measures implementation of an established reminder practice. The project aims only to improve that local process and collect practical implementation data; no research component has been identified.",task:"What is the appropriate statement about research classification?",key:"Not all local improvement activities are research",why:"Implementing accepted practice and collecting practical improvement data may fall outside the research definition; other institutional obligations still need consideration.",wrong:[["Every local process measurement is research","Measurement alone does not establish a research purpose."],["A QI designation removes every privacy obligation","Nonresearch classification does not erase other protections."],["Only projects with grant funding can be research","Funding source alone does not define research."]]},
{complaint:"Project oversight",body:"is invited to a project combining local improvement with an experimental comparison intended to produce generalizable knowledge. The investigator says a project must be either QI or research, never both.",task:"How should this mixed-purpose project be approached?",key:"Seek review of its research component",why:"An activity may serve both improvement and research purposes; a research component can trigger applicable review and consent requirements despite local benefit.",wrong:[["Use the improvement aim to bypass all review","Local benefit does not erase a research component."],["Use the project nickname to decide exemption","A nickname does not determine substantive classification."],["Use the number of authors to decide consent","Authorship count does not determine participant-protection requirements."]]}
]},
{id:"confidentiality",title:"Protect confidential patient information",objective:"Distinguish authorized care-related disclosure from curiosity or avoidable public exposure.",sources:["confidentiality"],stories:[
{complaint:"Privacy request",body:"asks that an elective procedure remain private. A friend calls for the diagnosis; the patient has not authorized disclosure, and no relevant legal or safety exception applies.",task:"How should reception respond to the friend's request?",key:"Decline disclosure without appropriate authorization",why:"A friend's interest does not authorize disclosure of confidential information when no applicable exception exists.",wrong:[["Disclose because the caller knows the patient's name","Knowing a name does not establish authorization."],["Disclose after the friend promises discretion","A secrecy promise does not create authority to receive information."],["Disclose only the most interesting clinical detail","Selecting one detail does not make disclosure authorized."]]},
{complaint:"Chart privacy",body:"recognizes a neighbor working in the clinic and asks whether that employee can browse the chart. The neighbor has no role in the patient's care or authorized administrative work.",task:"What governs the neighbor's access to this chart?",key:"An authorized work-related need for access",why:"Clinic employment and personal curiosity do not themselves justify accessing a patient's confidential information.",wrong:[["Personal curiosity about an unusual diagnosis","Curiosity is not an authorized purpose."],["Being acquainted with the patient's family","A social relationship does not grant access."],["Having an unused computer account at work","Technical access is not permission."]]},
{complaint:"Public discussion",body:"overhears staff discussing an identifiable clinic case in a crowded elevator. The discussion is not urgent and a private clinical workspace is available.",task:"What should the team do with the discussion?",key:"Move it to an appropriate private setting",why:"Clinical communication should avoid unnecessary exposure of identifiable information to people without an authorized reason to hear it.",wrong:[["Continue because the speakers work in healthcare","Professional status does not protect information from unrelated listeners."],["Speak louder so the entire team can hear","More exposure worsens the avoidable confidentiality problem."],["Omit the name but retain clearly identifying details","Removing a name alone does not prevent identification from other details."]]},
{complaint:"Care coordination",body:"has authorized coordination with a treating specialist who requests information relevant to the consultation. A colleague claims confidentiality prohibits every exchange between clinicians.",task:"How should this authorized care request be handled?",key:"Share relevant information for authorized care",why:"Confidentiality permits appropriate information exchange for authorized care while requiring attention to purpose and unnecessary disclosure; it does not prohibit all coordination.",wrong:[["Send the entire clinic's patient list instead","Other patients' information is unrelated and unauthorized."],["Refuse every exchange despite the authorization","A blanket refusal misstates confidentiality and obstructs care."],["Post the consultation details on a public page","Public posting is not the authorized clinical exchange."]]}
]},
];

function variant(topic:Topic, story:Story, index:number):VariantSpec {
  return {slug:`${topic.id}-${index+1}`,complaint:story.complaint,
    presentation:story.spanish?story.body:`{patientName}, a {patientAge}-year-old {patientSex}, ${story.body}`,
    stem:story.task,correct:{id:`key-${index+1}`,label:story.key,rationale:story.why},
    distractors:story.wrong.map(([label,rationale],i)=>({id:`wrong-${index+1}-${i+1}`,label,rationale})) as VariantSpec["distractors"],
    explanation:`Correct answer: ${story.key}. ${story.why} ${story.wrong.map(([,reason])=>reason).join(" ")}`,
    claimIds:[`claim.gs028se.${topic.id}.${index+1}`],sexLabels:story.spanish?["Female"]:["Female","Male"]};
}
function family(a:Topic,b:Topic):FamilySpec {
 const pair=[a,b];return {slug:`${a.id}-${b.id}`,label:"Ethics and communication",
 sources:[...new Set(pair.flatMap(t=>t.sources))].map(k=>ETHICS_SOURCES[k]),
 claims:pair.flatMap(t=>t.stories.map((s,i)=>({id:`claim.gs028se.${t.id}.${i+1}`,statement:s.why,sourceIds:(s.sources ?? t.sources).map(k=>ETHICS_SOURCES[k].id),category:"safety_boundary" as const,limitation:`Ethical guidance does not replace jurisdiction-specific law or institutional policy.${t.sources.length===1?" Single-source limitation.":""}${t.id==="qi-versus-research"?" Older nonbinding OHRP guidance; current definitions govern.":""}`,population:"People in the stated fictional clinical situation."}))),
 concepts:pair.map(t=>({id:`concept.statistics-ethics.${t.id}`,displayName:t.title,learningObjective:t.objective,stage:0,educationalTier:0,conceptType:"applied_science",evidenceClaimIds:t.stories.map((_,i)=>`claim.gs028se.${t.id}.${i+1}`),variants:t.stories.map((s,i)=>variant(t,s,i))})) as [ConceptSpec,ConceptSpec]};
}
export const ETHICS_FAMILIES=Array.from({length:topics.length/2},(_,i)=>buildFamily(family(topics[i*2]!,topics[i*2+1]!)));

