import type { SourceSpec } from "./family-builder";

/** Targeted factual verification only; source prose and examples are not reused. */
export const ETHICS_SOURCES = {
  interpreterAhrq: {
    id: "source.gs028se.ahrq-lep-2020", title: "Five Key Recommendations To Improve Patient Safety for LEP Patients",
    citation: "Agency for Healthcare Research and Quality. Five Key Recommendations To Improve Patient Safety for LEP Patients. 2012; last reviewed 2020. Accessed 2026-09-29.",
    organization: "Agency for Healthcare Research and Quality", authors: ["Agency for Healthcare Research and Quality"], year: 2012,
    url: "https://www.ahrq.gov/health-literacy/professional-training/lepguide/chapter2.html",
    sourceClass: "government_guidance", licenseLabel: "Targeted factual verification only; record-level reuse permission was not separately verified.", reuseStatus: "copyrighted_targeted_verification_only",
    authority: "Federal patient-safety guidance on qualified interpretation and teach-back.", usageRole: "both",
  },
  interpreterHhs: {
    id: "source.gs028se.hhs-ocr-interpreter-2015", title: "May an LEP person use a family member or friend as interpreter?",
    citation: "U.S. Department of Health and Human Services Office for Civil Rights. May an LEP person use a family member or friend as interpreter? Last reviewed 2015. Accessed 2026-09-29.",
    organization: "HHS Office for Civil Rights", authors: ["HHS Office for Civil Rights"], year: null,
    url: "https://www.hhs.gov/civil-rights/for-individuals/faqs/may-an-lep-person-use-a-family-member-as-an-interpreter/index.html",
    sourceClass: "government_guidance", licenseLabel: "Targeted factual verification only; record-level reuse permission was not separately verified.", reuseStatus: "copyrighted_targeted_verification_only",
    authority: "Federal language-access guidance defining qualified interpretation.", usageRole: "both",
  },
  consent: { id:"source.gs028se.ama-consent-2-1-1", title:"Informed Consent", citation:"American Medical Association. Code of Medical Ethics Opinion 2.1.1: Informed Consent. Accessed 2026-09-29.", organization:"American Medical Association", authors:["American Medical Association"], year:null, url:"https://code-medical-ethics.ama-assn.org/ethics-opinions/informed-consent", sourceClass:"professional_society_guideline", licenseLabel:"Copyrighted; targeted factual verification only", reuseStatus:"copyrighted_targeted_verification_only", authority:"Current professional ethics guidance for clinical consent." },
  capacity: { id:"source.gs028se.ama-capacity-2-1-2", title:"Decisions for Adult Patients Who Lack Capacity", citation:"American Medical Association. Code of Medical Ethics Opinion 2.1.2: Decisions for Adult Patients Who Lack Capacity. Accessed 2026-09-29.", organization:"American Medical Association", authors:["American Medical Association"], year:null, url:"https://code-medical-ethics.ama-assn.org/ethics-opinions/decisions-adult-patients-who-lack-capacity", sourceClass:"professional_society_guideline", licenseLabel:"Copyrighted; targeted factual verification only", reuseStatus:"copyrighted_targeted_verification_only", authority:"Current ethics guidance for capacity and surrogates." },
  dnarAma: { id:"source.gs028se.ama-dnar-5-4", title:"Orders Not to Attempt Resuscitation (DNAR)", citation:"American Medical Association. Code of Medical Ethics Opinion 5.4: Orders Not to Attempt Resuscitation (DNAR). Accessed 2026-09-29.", organization:"American Medical Association", authors:["American Medical Association"], year:null, url:"https://code-medical-ethics.ama-assn.org/ethics-opinions/orders-not-attempt-resuscitation-dnar", sourceClass:"professional_society_guideline", licenseLabel:"Copyrighted; targeted factual verification only", reuseStatus:"copyrighted_targeted_verification_only", authority:"Current ethics guidance: DNAR concerns resuscitation, not all care, and should be confirmed for surgery." },
  dnarAsa: { id:"source.gs028se.asa-dnar-2023", title:"Statement on Ethical Guidelines for the Anesthesia Care of Patients with Do-Not-Resuscitate Orders", citation:"American Society of Anesthesiologists Committee on Ethics. Statement on Ethical Guidelines for the Anesthesia Care of Patients with Do-Not-Resuscitate Orders. Originally approved 2001; reaffirmed 2023. Accessed 2026-09-29.", organization:"American Society of Anesthesiologists", authors:["American Society of Anesthesiologists Committee on Ethics"], year:null, url:"https://www.asahq.org/standards-and-practice-parameters/statement-on-ethical-guidelines-for-the-anesthesia-care-of-patients-with-do-not-resuscitate-orders", sourceClass:"professional_society_guideline", licenseLabel:"Copyrighted; targeted factual verification only", reuseStatus:"copyrighted_targeted_verification_only", authority:"Current anesthesia ethics guidance against automatic suspension; supports documented perioperative review." },
  safety: { id:"source.gs028se.ama-safety-8-6", title:"Promoting Patient Safety", citation:"American Medical Association. Code of Medical Ethics Opinion 8.6: Promoting Patient Safety. Accessed 2026-09-29.", organization:"American Medical Association", authors:["American Medical Association"], year:null, url:"https://code-medical-ethics.ama-assn.org/ethics-opinions/promoting-patient-safety", sourceClass:"professional_society_guideline", licenseLabel:"Copyrighted; targeted factual verification only", reuseStatus:"copyrighted_targeted_verification_only", authority:"Current ethics guidance for error response." },
  impairment: { id:"source.gs028se.ama-impairment-9-3-2", title:"Physician Responsibilities to Colleagues with Illness, Disability or Impairment", citation:"American Medical Association. Code of Medical Ethics Opinion 9.3.2. Accessed 2026-09-29.", organization:"American Medical Association", authors:["American Medical Association"], year:null, url:"https://code-medical-ethics.ama-assn.org/ethics-opinions/physician-responsibilities-colleagues-illness-disability-or-impairment", sourceClass:"professional_society_guideline", licenseLabel:"Copyrighted; targeted factual verification only", reuseStatus:"copyrighted_targeted_verification_only", authority:"Current ethics guidance for safety and colleague assistance." },
  research: { id:"source.gs028se.ama-research-7-1-2", title:"Informed Consent in Research", citation:"American Medical Association. Code of Medical Ethics Opinion 7.1.2: Informed Consent in Research. Accessed 2026-09-29.", organization:"American Medical Association", authors:["American Medical Association"], year:null, url:"https://code-medical-ethics.ama-assn.org/ethics-opinions/informed-consent-research", sourceClass:"professional_society_guideline", licenseLabel:"Copyrighted; targeted factual verification only", reuseStatus:"copyrighted_targeted_verification_only", authority:"Current research-consent ethics guidance." },
  qi: { id:"source.gs028se.ohrp-qi", title:"Quality Improvement Activities FAQs", citation:"U.S. Department of Health and Human Services Office for Human Research Protections. Quality Improvement Activities FAQs. Accessed 2026-09-29.", organization:"HHS Office for Human Research Protections", authors:["HHS Office for Human Research Protections"], year:null, url:"https://www.hhs.gov/ohrp/regulations-and-policy/guidance/faq/quality-improvement-activities/index.html", sourceClass:"government_guidance", licenseLabel:"Targeted factual verification only; record-level reuse permission was not separately verified.", reuseStatus:"copyrighted_targeted_verification_only", authority:"Federal guidance whose older, nonbinding status is explicit." },
  confidentiality: { id:"source.gs028se.ama-confidentiality-3-2-1", title:"Confidentiality", citation:"American Medical Association. Code of Medical Ethics Opinion 3.2.1: Confidentiality. Accessed 2026-09-29.", organization:"American Medical Association", authors:["American Medical Association"], year:null, url:"https://code-medical-ethics.ama-assn.org/ethics-opinions/confidentiality", sourceClass:"professional_society_guideline", licenseLabel:"Copyrighted; targeted factual verification only", reuseStatus:"copyrighted_targeted_verification_only", authority:"Current confidentiality ethics guidance." },
} satisfies Record<string, SourceSpec>;
