(()=>{
  const root=document.getElementById('xray-layout-proof'),canvas=root.querySelector('#xray-art'),ctx=canvas.getContext('2d'),status=root.querySelector('#xray-status'),overlay=root.querySelector('#xray-overlay'),optionalToggle=root.querySelector('#xray-optional'),targets=root.querySelector('#xray-targets');
  const SCALE=2,W=480,H=550,S=120,X=60,Y=130,BOTTOM=Y+3*S,EAST=X+3*S;
  const segments=['N1','N2','N3','S1','S2','S3','WA','WB','WC','EA','EB','EC'];
  const state={doors:new Set(['S2']),adjacent:new Set(),selected:'S2',optional:true};
  const fixtures={
    detector:{id:'detector',label:'upright X-ray detector',footprint:{left:1.225,top:1.5,width:.55,height:.35},navigationBlocker:{left:1,top:1,width:1,height:1},anchor:{x:1.5,y:1.85},use:{x:1.5,y:2.25},facing:'S',useFacing:'N',persistence:'permanent',collision:'solid'},
    tube:{id:'tube',label:'north-facing X-ray tube stand',footprint:{left:.35,top:2.35,width:.6,height:.25},anchor:{x:.65,y:2.6},facing:'N',persistence:'permanent',collision:'nonblocking'},
    console:{id:'console',label:'X-ray console',footprint:{left:2.15,top:1.45,width:.6,height:.3},anchor:{x:2.45,y:1.75},approach:{x:2.45,y:2.35},facing:'S',operatorFacing:'N',persistence:'permanent',collision:'nonblocking'},
    apron:{id:'apron',label:'hanging lead apron',anchor:{x:.5,y:-.633},conflicts:['N1'],persistence:'optional',collision:'nonblocking',mount:'north wall'},
  };  const crops=__CROP_CONFIG__,radius=.16,step=.04,start={x:1.52,y:2.84},navigationBlocker=fixtures.detector.navigationBlocker;
  const atlas=new Image();atlas.src='data:image/webp;base64,__XRAY_ATLAS__';atlas.onload=render;
  const key=p=>`${p.x.toFixed(2)},${p.y.toFixed(2)}`,inflated=r=>({left:r.left-radius,top:r.top-radius,right:r.left+r.width+radius,bottom:r.top+r.height+radius});
  const validPoint=p=>p.x>=radius-1e-6&&p.x<=3-radius+1e-6&&p.y>=radius-1e-6&&p.y<=3-radius+1e-6&&!(()=>{const r=inflated(navigationBlocker);return p.x>=r.left-1e-6&&p.x<=r.right+1e-6&&p.y>=r.top-1e-6&&p.y<=r.bottom+1e-6})();
  const candidates=id=>{const values=[.28,.36,.52,.64,.72];if(id[0]==='N'||id[0]==='S'){const i=Number(id[1])-1,y=id[0]==='N'?radius:3-radius;return values.map(v=>({x:i+v,y})).filter(validPoint)}const i=id.charCodeAt(1)-65,x=id[0]==='W'?radius:3-radius;return values.map(v=>({x,y:i+v})).filter(validPoint)};
  const simplify=path=>path.filter((p,i)=>i===0||i===path.length-1||Math.abs((path[i-1].x-p.x)*(path[i+1].y-p.y)-(path[i-1].y-p.y)*(path[i+1].x-p.x))>.0001);
  function bfs(from,to){const snap=p=>({x:Math.round(p.x/step)*step,y:Math.round(p.y/step)*step}),a=snap(from),b=snap(to);if(!validPoint(a)||!validPoint(b))return[];const queue=[a],prev=new Map([[key(a),null]]),points=new Map([[key(a),a]]),moves=[[step,0],[-step,0],[0,step],[0,-step]];while(queue.length){const p=queue.shift(),pk=key(p);if(pk===key(b)){const path=[];for(let k=pk;k;k=prev.get(k))path.unshift(points.get(k));return simplify(path)}for(const[dx,dy]of moves){const n=snap({x:p.x+dx,y:p.y+dy}),nk=key(n);if(validPoint(n)&&!prev.has(nk)){prev.set(nk,pk);points.set(nk,n);queue.push(n)}}}return[]}
  const routeToDoor=id=>{let best=[];for(const target of candidates(id)){const route=bfs(start,target);if(route.length&&(!best.length||route.length<best.length))best=route}return best};
  let routeCache=null,serviceCache=null;
  const routes=()=>routeCache||(routeCache=Object.fromEntries(segments.map(id=>[id,routeToDoor(id)])));
  const serviceRoutes=()=>serviceCache||(serviceCache={patient:bfs(start,fixtures.detector.use),technician:bfs(start,fixtures.console.approach)});
  const hiddenOptional=()=>Object.values(fixtures).filter(f=>f.persistence==='optional'&&(!state.optional||f.conflicts.some(id=>state.doors.has(id))||f.conflicts.some(id=>id[0]==='N'&&state.adjacent.has(id)))).map(f=>f.id);
  function surface(left,top,width,height){ctx.save();ctx.beginPath();ctx.rect(left,top,width,height);ctx.clip();ctx.fillStyle='#d5d1c9';ctx.fillRect(left,top,width,height);for(let py=top;py<top+height;py+=7)for(let px=left;px<left+width;px+=7){const q=Math.abs((px*17+py*11)%23);ctx.fillStyle=q%4?'rgba(250,248,241,.10)':'rgba(83,94,91,.055)';ctx.fillRect(px+q%4,py+(q*2)%4,1,1)}ctx.restore()}
  function drawShell(){const cream='#efe1bd',green='#58735a',dark='#294632',light='#789173',wood='#744a29',background='#f3ead3',low=29,wall=90,cap=14;ctx.clearRect(0,0,W,H);ctx.fillStyle=background;ctx.fillRect(0,0,W,H);surface(X,Y,3*S,3*S);const tall=i=>{const sx=X+i*S;ctx.fillStyle='#bec8d6';ctx.fillRect(sx,Y-wall,S,wall);ctx.fillStyle='rgba(146,110,67,.055)';ctx.fillRect(sx+12,Y-wall+30,S-24,2);ctx.fillStyle=green;ctx.fillRect(sx,Y-23,S,23);ctx.fillStyle=light;ctx.fillRect(sx,Y-23,S,4);ctx.fillStyle=dark;ctx.fillRect(sx,Y-7,S,7);ctx.fillRect(sx-1,Y-wall-9,S+2,9);ctx.fillStyle=light;ctx.fillRect(sx-1,Y-wall-9,S+2,3)},backed=i=>{const sx=X+i*S;ctx.fillStyle=green;ctx.fillRect(sx,Y-low,S,low);ctx.fillStyle=light;ctx.fillRect(sx,Y-low,S,4);ctx.fillStyle=dark;ctx.fillRect(sx,Y-7,S,7)};for(let i=0;i<3;i++)state.adjacent.has(`N${i+1}`)?backed(i):tall(i);for(let i=0;i<3;i++)if(state.adjacent.has(`N${i+1}`))ctx.clearRect(X+i*S,0,S,Y-low);const westX=X-cap+2,eastX=EAST-2,side=right=>{const px=right?eastX:westX,neighbor=right?'N3':'N1',top=state.adjacent.has(neighbor)?Y-low:Y-wall-9;ctx.fillStyle=dark;ctx.fillRect(px,top,cap,BOTTOM+29-top);ctx.fillStyle=light;ctx.fillRect(px+(right?0:cap-3),top,3,BOTTOM+29-top)};side(false);side(true);const northDoor=i=>{const backedNorth=state.adjacent.has(`N${i+1}`),left=X+i*S+12,right=X+(i+1)*S-12,top=backedNorth?Y-low:Y-wall+8;ctx.clearRect(left,top,right-left,Y-top);ctx.fillStyle=wood;ctx.fillRect(left-5,top,5,Y-top);ctx.fillRect(right,top,5,Y-top);if(!backedNorth)ctx.fillRect(left-5,top-5,right-left+10,6)},sideDoor=(right,i)=>{const px=right?eastX:westX,top=Y+i*S+12,height=S-24,half=cap/2;ctx.clearRect(px,top,cap,height);if(right){surface(px,top,half,height);ctx.clearRect(px+half,top,half,height)}else{ctx.clearRect(px,top,half,height);surface(px+half,top,half,height)}ctx.fillStyle=wood;ctx.fillRect(px-2,top-3,cap+4,5);ctx.fillRect(px-2,top+height-2,cap+4,5)};for(let i=0;i<3;i++){const left=X+i*S;ctx.fillStyle=cream;ctx.fillRect(left,BOTTOM,S,29);ctx.fillStyle=green;ctx.fillRect(left,BOTTOM+21,S,8);ctx.fillStyle=dark;ctx.fillRect(left,BOTTOM-6,S,8);ctx.fillStyle=light;ctx.fillRect(left,BOTTOM-6,S,3)}for(const id of state.doors){if(id[0]==='N')northDoor(Number(id[1])-1);else if(id[0]==='S'){const i=Number(id[1])-1,left=X+i*S+12,right=X+(i+1)*S-12;ctx.clearRect(left,BOTTOM-6,right-left,35);surface(left,BOTTOM-6,right-left,35);ctx.fillStyle=wood;ctx.fillRect(left-5,BOTTOM-8,5,37);ctx.fillRect(right,BOTTOM-8,5,37)}else sideDoor(id[0]==='E',id.charCodeAt(1)-65)}}
  const drawSprite=(id,anchor,width)=>{const c=crops[id],scale=width/c.w,height=c.h*scale,x=X+anchor.x*S-c.contactX*scale,y=Y+anchor.y*S-c.contactY*scale;ctx.drawImage(atlas,c.x,c.y,c.w,c.h,x,y,width,height);return{x,y,w:width,h:height,contactX:x+c.contactX*scale,contactY:y+c.contactY*scale,sourceContact:{x:c.contactX,y:c.contactY},aspect:c.w/c.h}};
  function drawFurniture(){const hidden=hiddenOptional(),draws={};const specs={apron:.38*S,detector:.72*S,tube:1.2*S,console:1.0*S};for(const id of ['apron','detector','tube','console'])if(!hidden.includes(id))draws[id]=drawSprite(id,fixtures[id].anchor,specs[id]);return{hidden,draws}}
  function drawOverlay(routeMap,draws){if(!overlay.checked)return;ctx.save();const route=routeMap[state.selected]||[];if(route.length){ctx.strokeStyle='#2f7090';ctx.lineWidth=3;ctx.beginPath();route.forEach((p,i)=>i?ctx.lineTo(X+p.x*S,Y+p.y*S):ctx.moveTo(X+p.x*S,Y+p.y*S));ctx.stroke();}for(const f of Object.values(fixtures)){if(!f.footprint)continue;const r=f.footprint;ctx.setLineDash([5,4]);ctx.strokeStyle=f.collision==='solid'?'#8d5a47':'#2f7090';ctx.strokeRect(X+r.left*S,Y+r.top*S,r.width*S,r.height*S)}ctx.setLineDash([]);for(const [p,label,color] of [[fixtures.detector.use,'patient N','#8d5a47'],[fixtures.console.approach,'tech N','#355f52']]){ctx.fillStyle=color;ctx.beginPath();ctx.arc(X+p.x*S,Y+p.y*S,5,0,Math.PI*2);ctx.fill();ctx.font='10px sans-serif';ctx.fillText(label,X+p.x*S+7,Y+p.y*S+3)}ctx.restore()}
  const hitSlot=id=>{if(id[0]==='N'||id[0]==='S'){const i=Number(id[1])-1;return{x:X+i*S,y:id[0]==='N'?(state.adjacent.has(id)?Y-29:Y-99):BOTTOM,w:S,h:id[0]==='N'?(state.adjacent.has(id)?29:99):29}}const i=id.charCodeAt(1)-65;return{x:id[0]==='W'?X-14:EAST,y:Y+i*S,w:14,h:S}};
  function render(){ctx.setTransform(SCALE,0,0,SCALE,0,0);ctx.imageSmoothingEnabled=true;drawShell();const fixtureState=drawFurniture(),routeMap=routes(),service=serviceRoutes();drawOverlay(routeMap,fixtureState.draws);for(const button of targets.querySelectorAll('button')){const b=hitSlot(button.dataset.segment);Object.assign(button.style,{left:`${b.x/W*100}%`,top:`${b.y/H*100}%`,width:`${b.w/W*100}%`,height:`${b.h/H*100}%`})}const reachable=Object.values(routeMap).filter(path=>path.length).length;status.innerHTML=`<strong>${state.selected}</strong> · ${state.doors.has(state.selected)?'open doorway':'closed wall'} · ${reachable}/12 approaches reachable from S2<br>B2 is the only blocked tile · standing patient ${service.patient.length?'reachable':'blocked'} · technician ${service.technician.length?'reachable':'blocked'} · hidden: ${fixtureState.hidden.join(', ')||'none'}`;root.querySelectorAll('[data-segment]').forEach(button=>{const active=state.doors.has(button.dataset.segment);button.setAttribute('aria-pressed',String(active));button.classList.toggle('btn-primary',active)});canvas.dataset.selected=state.selected;canvas.dataset.doors=[...state.doors].join(',');canvas.dataset.adjacency=[...state.adjacent].join(',');canvas.dataset.hidden=fixtureState.hidden.join(',');canvas.dataset.routes=JSON.stringify(routeMap);canvas.dataset.serviceRoutes=JSON.stringify(service);canvas.dataset.fixtures=JSON.stringify(Object.values(fixtures).map(f=>({...f,draw:fixtureState.draws[f.id]||null})));canvas.dataset.navigationBlocker=JSON.stringify(navigationBlocker);canvas.dataset.shell=JSON.stringify({logicalCols:3,logicalRows:3,tileSize:S,rearWallHeight:90,lowNorthHeight:29,sideCapWidth:14,southHeight:29,northLowHeader:false,sideDoorSeam:'half-thickness',southFloorToBase:true})}
  const addButton=(id,target,label,hit=false)=>{const button=document.createElement('button');button.type='button';button.className=hit?'xray-hit':'btn';button.dataset.segment=id;button.textContent=hit?'':id;button.setAttribute('aria-label',label);button.addEventListener('click',()=>{state.doors.has(id)?state.doors.delete(id):state.doors.add(id);state.selected=id;render()});target.append(button)};
  for(const[prefix,targetId]of[['N','xray-north'],['S','xray-south'],['W','xray-west'],['E','xray-east']])for(const id of segments.filter(segment=>segment[0]===prefix))addButton(id,root.querySelector('#'+targetId),`Toggle door at ${id}`);for(const id of segments)addButton(id,targets,`Wall door ${id}`,true);for(const id of ['N1','N2','N3']){const label=document.createElement('label');label.className='form-check';label.innerHTML=`<input class="form-check-input" type="checkbox" data-adjacent="${id}"><span class="form-check-label">${id}</span>`;label.querySelector('input').addEventListener('change',event=>{event.target.checked?state.adjacent.add(id):state.adjacent.delete(id);render()});root.querySelector('#xray-adjacency').append(label)}optionalToggle.addEventListener('change',()=>{state.optional=optionalToggle.checked;render()});overlay.addEventListener('change',render);
  window.__xrayLayout={segments,state,fixtures,crops,radius,step,start,navigationBlocker,validPoint,candidates,bfs,routeToDoor,routes,serviceRoutes,hiddenOptional,render,ready:()=>atlas.complete&&atlas.naturalWidth>0};render();
})();


