import * as breast from "./breast-mass";
import * as abscess from "./cutaneous-abscess";
import * as groin from "./groin-hernia-management";
import * as anatomy from "./hernia-anatomy";
import * as ileostomy from "./high-output-ileostomy";
import * as perianal from "./perianal-abscess";
import * as medications from "./perioperative-medications";
import * as prophylaxis from "./postoperative-prophylaxis";
import * as retention from "./postoperative-urinary-retention";
import * as wounds from "./postoperative-wounds";

export const BREAD_BUTTER_20260917_AUTHORING_CONCEPTS = [
  ...breast.BREAD_BUTTER_BREAST_MASS_CONCEPTS,
  ...abscess.CUTANEOUS_ABSCESS_CONCEPTS,
  ...groin.GROIN_HERNIA_MANAGEMENT_CONCEPTS,
  ...anatomy.HERNIA_ANATOMY_CONCEPTS,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_CONCEPTS,
  ...perianal.PERIANAL_ABSCESS_CONCEPTS,
  ...medications.PERIOPERATIVE_MEDICATIONS_CONCEPTS,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_CONCEPTS,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_CONCEPTS,
  ...wounds.POSTOPERATIVE_WOUNDS_CONCEPTS,
];

export const BREAD_BUTTER_20260917_TESTED_CONCEPTS = [
  ...breast.BREAD_BUTTER_BREAST_MASS_TESTED_CONCEPTS,
  ...abscess.CUTANEOUS_ABSCESS_TESTED_CONCEPTS,
  ...groin.GROIN_HERNIA_MANAGEMENT_TESTED_CONCEPTS,
  ...anatomy.HERNIA_ANATOMY_TESTED_CONCEPTS,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_TESTED_CONCEPTS,
  ...perianal.PERIANAL_ABSCESS_TESTED_CONCEPTS,
  ...medications.PERIOPERATIVE_MEDICATIONS_TESTED_CONCEPTS,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_TESTED_CONCEPTS,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_TESTED_CONCEPTS,
  ...wounds.POSTOPERATIVE_WOUNDS_TESTED_CONCEPTS,
];

export const BREAD_BUTTER_20260917_QUESTIONS = [
  ...breast.BREAD_BUTTER_BREAST_MASS_QUESTIONS,
  ...abscess.CUTANEOUS_ABSCESS_QUESTIONS,
  ...groin.GROIN_HERNIA_MANAGEMENT_QUESTIONS,
  ...anatomy.HERNIA_ANATOMY_QUESTIONS,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_QUESTIONS,
  ...perianal.PERIANAL_ABSCESS_QUESTIONS,
  ...medications.PERIOPERATIVE_MEDICATIONS_QUESTIONS,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_QUESTIONS,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_QUESTIONS,
  ...wounds.POSTOPERATIVE_WOUNDS_QUESTIONS,
];

export const BREAD_BUTTER_20260917_CASES = [
  ...breast.BREAD_BUTTER_BREAST_MASS_CASES,
  ...abscess.CUTANEOUS_ABSCESS_CASES,
  ...groin.GROIN_HERNIA_MANAGEMENT_CASES,
  ...anatomy.HERNIA_ANATOMY_CASES,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_CASES,
  ...perianal.PERIANAL_ABSCESS_CASES,
  ...medications.PERIOPERATIVE_MEDICATIONS_CASES,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_CASES,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_CASES,
  ...wounds.POSTOPERATIVE_WOUNDS_CASES,
];

export const BREAD_BUTTER_20260917_CLAIMS = [
  ...breast.BREAD_BUTTER_BREAST_MASS_CLAIMS,
  ...abscess.CUTANEOUS_ABSCESS_CLAIMS,
  ...groin.GROIN_HERNIA_MANAGEMENT_CLAIMS,
  ...anatomy.HERNIA_ANATOMY_CLAIMS,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_CLAIMS,
  ...perianal.PERIANAL_ABSCESS_CLAIMS,
  ...medications.PERIOPERATIVE_MEDICATIONS_CLAIMS,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_CLAIMS,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_CLAIMS,
  ...wounds.POSTOPERATIVE_WOUNDS_CLAIMS,
];

export const BREAD_BUTTER_20260917_SOURCES = [
  ...breast.BREAD_BUTTER_BREAST_MASS_SOURCES,
  ...abscess.CUTANEOUS_ABSCESS_SOURCES,
  ...groin.GROIN_HERNIA_MANAGEMENT_SOURCES,
  ...anatomy.HERNIA_ANATOMY_SOURCES,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_SOURCES,
  ...perianal.PERIANAL_ABSCESS_SOURCES,
  ...medications.PERIOPERATIVE_MEDICATIONS_SOURCES,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_SOURCES,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_SOURCES,
  ...wounds.POSTOPERATIVE_WOUNDS_SOURCES,
];

export const BREAD_BUTTER_20260917_CASE_REVIEWS = [
  ...breast.BREAD_BUTTER_BREAST_MASS_CASE_REVIEWS,
  ...abscess.CUTANEOUS_ABSCESS_CASE_REVIEWS,
  ...groin.GROIN_HERNIA_MANAGEMENT_CASE_REVIEWS,
  ...anatomy.HERNIA_ANATOMY_CASE_REVIEWS,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_CASE_REVIEWS,
  ...perianal.PERIANAL_ABSCESS_CASE_REVIEWS,
  ...medications.PERIOPERATIVE_MEDICATIONS_CASE_REVIEWS,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_CASE_REVIEWS,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_CASE_REVIEWS,
  ...wounds.POSTOPERATIVE_WOUNDS_CASE_REVIEWS,
];

export const BREAD_BUTTER_20260917_SERVICE_CONTRACTS = [
  ...breast.BREAD_BUTTER_BREAST_MASS_SERVICE_CONTRACTS,
  ...abscess.CUTANEOUS_ABSCESS_SERVICE_CONTRACTS,
  ...groin.GROIN_HERNIA_MANAGEMENT_SERVICE_CONTRACTS,
  ...anatomy.HERNIA_ANATOMY_SERVICE_CONTRACTS,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_SERVICE_CONTRACTS,
  ...perianal.PERIANAL_ABSCESS_SERVICE_CONTRACTS,
  ...medications.PERIOPERATIVE_MEDICATIONS_SERVICE_CONTRACTS,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_SERVICE_CONTRACTS,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_SERVICE_CONTRACTS,
  ...wounds.POSTOPERATIVE_WOUNDS_SERVICE_CONTRACTS,
];

export const BREAD_BUTTER_20260917_TIMING_ENTRIES = [
  ...breast.BREAD_BUTTER_BREAST_MASS_TIMING_ENTRIES,
  ...abscess.CUTANEOUS_ABSCESS_TIMING_ENTRIES,
  ...groin.GROIN_HERNIA_MANAGEMENT_TIMING_ENTRIES,
  ...anatomy.HERNIA_ANATOMY_TIMING_ENTRIES,
  ...ileostomy.HIGH_OUTPUT_ILEOSTOMY_TIMING_ENTRIES,
  ...perianal.PERIANAL_ABSCESS_TIMING_ENTRIES,
  ...medications.PERIOPERATIVE_MEDICATIONS_TIMING_ENTRIES,
  ...prophylaxis.POSTOPERATIVE_PROPHYLAXIS_TIMING_ENTRIES,
  ...retention.POSTOPERATIVE_URINARY_RETENTION_TIMING_ENTRIES,
  ...wounds.POSTOPERATIVE_WOUNDS_TIMING_ENTRIES,
];

export const BREAD_BUTTER_20260917_BATCH_MANIFEST = {
  contentVersion: "development-batch.2026-09-17.bread-and-butter.1",
  authoringConceptCount: BREAD_BUTTER_20260917_AUTHORING_CONCEPTS.length,
  testedConceptCount: BREAD_BUTTER_20260917_TESTED_CONCEPTS.length,
  questionVariantCount: BREAD_BUTTER_20260917_QUESTIONS.length,
  caseCount: BREAD_BUTTER_20260917_CASES.length,
  decisionNodeCount: BREAD_BUTTER_20260917_CASES.flatMap(
    (item) => item.decisionNodes,
  ).length,
  resultGateCount: BREAD_BUTTER_20260917_CASES.flatMap(
    (item) => item.decisionNodes,
  ).filter((node) => node.resultGateAfter !== null).length,
  caseReviewCount: BREAD_BUTTER_20260917_CASE_REVIEWS.length,
  sourceCount: BREAD_BUTTER_20260917_SOURCES.length,
  evidenceClaimCount: BREAD_BUTTER_20260917_CLAIMS.length,
  serviceContractCount: BREAD_BUTTER_20260917_SERVICE_CONTRACTS.length,
  timingEntryCount: BREAD_BUTTER_20260917_TIMING_ENTRIES.length,
  admissionScope: "active_synthetic_unapproved_prototype",
  publicReleaseAuthorized: false,
} as const;