(()=>{
  const root=document.getElementById('endoscopy-layout-proof'),canvas=root.querySelector('#endoscopy-art'),ctx=canvas.getContext('2d'),status=root.querySelector('#endoscopy-status'),orientationControl=root.querySelector('#endoscopy-orientation'),overlay=root.querySelector('#endoscopy-overlay'),optionalToggle=root.querySelector('#endoscopy-optional'),procedureToggle=root.querySelector('#endoscopy-procedure'),targets=root.querySelector('#endoscopy-targets');
  const SCALE=2,W=600,S=120,Y=130,radius=.16,step=.04,data=__DATA__,sprites=__SPRITES__,replacementContract=__CONTRACT__,atlases={south:new Image(),east:new Image()};atlases.south.src='data:image/webp;base64,__SOUTH__';atlases.east.src='data:image/webp;base64,__EAST__';
  const worldSegments=['N1','N2','N3','N4','S1','S2','S3','S4','WA','WB','WC','EA','EB','EC'];
  const worldToEast={N1:'WD',N2:'WC',N3:'WB',N4:'WA',S1:'ED',S2:'EC',S3:'EB',S4:'EA',WA:'S1',WB:'S2',WC:'S3',EA:'N1',EB:'N2',EC:'N3'},eastToWorld=Object.fromEntries(Object.entries(worldToEast).map(([world,local])=>[local,world]));
  const state={orientation:'south',doors:new Set(),adjacent:new Set(),selectedWorld:'S2',optional:true,duringProcedure:false};
  const dimensions=()=>state.orientation==='south'?{cols:4,rows:3,x:60}:{cols:3,rows:4,x:120},viewHeight=()=>state.orientation==='south'?550:670;
  const localSegments=()=>{const{cols,rows}=dimensions(),out=[];for(let i=1;i<=cols;i++)out.push(`N${i}`);for(let i=1;i<=cols;i++)out.push(`S${i}`);for(let i=0;i<rows;i++)out.push(`W${String.fromCharCode(65+i)}`);for(let i=0;i<rows;i++)out.push(`E${String.fromCharCode(65+i)}`);return out};
  const toLocal=world=>state.orientation==='south'?world:worldToEast[world],toWorld=local=>state.orientation==='south'?local:eastToWorld[local];
  const rotatePoint=p=>({x:p.y,y:4-p.x}),rotateRect=r=>({left:r.top,top:4-r.left-r.width,width:r.height,height:r.width}),rotateFacing=f=>({N:'W',W:'S',S:'E',E:'N'})[f]||f;
  const base={
    procedureTable:{id:'procedureTable',label:'procedure table',ground:{x:1.5,y:1.95},footprint:{left:.95,top:.35,width:1,height:1.6},navigationBlocker:{left:.95,top:.35,width:1,height:1.6},patientApproach:{x:1.5,y:2.3},headFacing:'N',footFacing:'S',occupiedHeadFacing:'W',collision:'solid',persistence:'permanent'},
    staff:{id:'staffUse',label:'endoscopist standing use point',ground:{x:2.3,y:1.5},facing:'W',collision:'none',persistence:'use-point'},
    tower:{id:'tower',label:'endoscopy equipment tower',ground:{x:2.9,y:.85},footprint:{left:2.6,top:.45,width:.6,height:.4},collision:'nonblocking',persistence:'permanent'},
    cabinet:{id:'cabinet',label:'supply cabinet',ground:{x:.5,y:.3},footprint:{left:.05,top:.05,width:.9,height:.25},conflicts:['N1','WA'],backedConflicts:['N1'],collision:'nonblocking',persistence:'optional'},
    sink:{id:'sink',label:'sink vanity',ground:{x:3.55,y:.3},footprint:{left:3.2,top:.05,width:.7,height:.25},conflicts:['N4','EA'],backedConflicts:['N4'],collision:'nonblocking',persistence:'optional'}
  };
  const fixtures=()=>Object.fromEntries(Object.entries(base).map(([id,value])=>{const f=structuredClone(value);if(state.orientation==='east'){for(const key of ['ground','patientApproach'])if(f[key])f[key]=rotatePoint(f[key]);for(const key of ['footprint','navigationBlocker'])if(f[key])f[key]=rotateRect(f[key]);for(const key of ['facing','headFacing','footFacing','occupiedHeadFacing'])if(f[key])f[key]=rotateFacing(f[key])}return[id,f]}));
  const localDoors=()=>new Set([...state.doors].map(toLocal)),selectedLocal=()=>toLocal(state.selectedWorld),box=()=>{const d=dimensions();return{...d,bottom:Y+d.rows*S,east:d.x+d.cols*S}};
  const hiddenOptional=()=>{const hidden=[];for(const id of ['cabinet','sink']){const f=base[id],door=f.conflicts.some(segment=>state.doors.has(segment)),backed=[...state.adjacent].some(local=>f.backedConflicts.includes(toWorld(local)));if(!state.optional||door||backed)hidden.push(id)}return hidden};
  const floorSurface=(left,top,width,height)=>{const b=box(),tile=24,startCol=Math.floor((left-b.x)/tile),endCol=Math.ceil((left+width-b.x)/tile),startRow=Math.floor((top-Y)/tile),endRow=Math.ceil((top+height-Y)/tile);ctx.save();ctx.beginPath();ctx.rect(left,top,width,height);ctx.clip();ctx.fillStyle='#778087';ctx.fillRect(left,top,width,height);for(let row=startRow;row<endRow;row++)for(let col=startCol;col<endCol;col++){const x=b.x+col*tile,y=Y+row*tile,tone=Math.abs(col*7+row*11)%9;ctx.fillStyle=tone===0?'rgba(196,154,145,.12)':tone===4?'rgba(68,78,82,.11)':'rgba(228,224,211,.05)';ctx.fillRect(x+1,y+1,tile-1,tile-1);const chip=Math.abs(col*17+row*23)%13;ctx.fillStyle=chip%3?'rgba(52,61,65,.20)':'rgba(216,175,158,.18)';ctx.fillRect(x+5+chip%11,y+4+(chip*3)%13,1,1);ctx.fillRect(x+15-(chip%5),y+16-(chip%7),1,1)}ctx.strokeStyle='rgba(45,55,59,.20)';ctx.lineWidth=1;for(let col=startCol;col<=endCol;col++){const x=b.x+col*tile+.5;ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+height);ctx.stroke()}for(let row=startRow;row<=endRow;row++){const y=Y+row*tile+.5;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left+width,y);ctx.stroke()}ctx.restore()};
  const hitSlot=id=>{const b=box(),i=id[0]==='N'||id[0]==='S'?Number(id.slice(1))-1:id.charCodeAt(1)-65;if(id[0]==='N')return{x:b.x+i*S,y:state.adjacent.has(id)?Y-29:Y-99,w:S,h:state.adjacent.has(id)?29:99};if(id[0]==='S')return{x:b.x+i*S,y:b.bottom,w:S,h:29};return{x:id[0]==='W'?b.x-14:b.east,y:Y+i*S,w:14,h:S}};
  function drawShell(){const b=box(),doors=localDoors(),north='#536168',green='#58735a',dark='#294632',light='#789173',wood='#744a29',background='#e7dfc7',cream='#efe1bd',wall=90,low=29,cap=14;ctx.clearRect(0,0,W,viewHeight());ctx.fillStyle=background;ctx.fillRect(0,0,W,viewHeight());floorSurface(b.x,Y,b.cols*S,b.rows*S);
    for(let i=0;i<b.cols;i++){const left=b.x+i*S,id=`N${i+1}`;if(state.adjacent.has(id)){ctx.clearRect(left,0,S,Y-low);ctx.fillStyle=green;ctx.fillRect(left,Y-low,S,low);ctx.fillStyle=light;ctx.fillRect(left,Y-low,S,4);ctx.fillStyle=dark;ctx.fillRect(left,Y-7,S,7)}else{ctx.fillStyle=north;ctx.fillRect(left,Y-wall,S,wall);ctx.fillStyle='rgba(235,226,202,.06)';ctx.fillRect(left+12,Y-wall+30,S-24,2);ctx.fillStyle=green;ctx.fillRect(left,Y-23,S,23);ctx.fillStyle=light;ctx.fillRect(left,Y-23,S,4);ctx.fillStyle=dark;ctx.fillRect(left,Y-7,S,7);ctx.fillRect(left-1,Y-wall-9,S+2,9);ctx.fillStyle=light;ctx.fillRect(left-1,Y-wall-9,S+2,3)}}
    const westX=b.x-cap+2,eastX=b.east-2;for(const[right,px]of[[false,westX],[true,eastX]]){const neighbor=right?`N${b.cols}`:'N1',top=state.adjacent.has(neighbor)?Y-low:Y-wall-9;ctx.fillStyle=dark;ctx.fillRect(px,top,cap,b.bottom+29-top);ctx.fillStyle=light;ctx.fillRect(px+(right?0:cap-3),top,3,b.bottom+29-top)}
    for(let i=0;i<b.cols;i++){const left=b.x+i*S;ctx.fillStyle=cream;ctx.fillRect(left,b.bottom,S,29);ctx.fillStyle=green;ctx.fillRect(left,b.bottom+21,S,8);ctx.fillStyle=dark;ctx.fillRect(left,b.bottom-6,S,8);ctx.fillStyle=light;ctx.fillRect(left,b.bottom-6,S,3)}
    for(const id of doors){if(id[0]==='N'){const i=Number(id.slice(1))-1,left=b.x+i*S+12,right=b.x+(i+1)*S-12,backed=state.adjacent.has(id),top=backed?Y-low:Y-wall+8;ctx.clearRect(left,top,right-left,Y-top);ctx.fillStyle=wood;ctx.fillRect(left-5,top,5,Y-top);ctx.fillRect(right,top,5,Y-top);if(!backed)ctx.fillRect(left-5,top-5,right-left+10,6)}else if(id[0]==='S'){const i=Number(id.slice(1))-1,left=b.x+i*S+12,right=b.x+(i+1)*S-12;ctx.clearRect(left,b.bottom-6,right-left,35);floorSurface(left,b.bottom-6,right-left,35);ctx.fillStyle=wood;ctx.fillRect(left-5,b.bottom-8,5,37);ctx.fillRect(right,b.bottom-8,5,37)}else{const right=id[0]==='E',i=id.charCodeAt(1)-65,px=right?eastX:westX,top=Y+i*S+12,height=S-24,half=cap/2;ctx.clearRect(px,top,cap,height);if(right){floorSurface(px,top,half,height);ctx.clearRect(px+half,top,half,height)}else{ctx.clearRect(px,top,half,height);floorSurface(px+half,top,half,height)}ctx.fillStyle=wood;ctx.fillRect(px-2,top-3,cap+4,5);ctx.fillRect(px-2,top+height-2,cap+4,5)}}
  }
  const drawSprite=(id,fixture)=>{const frame=data[state.orientation].packedFrames[id],source=sprites[state.orientation][id],scale=source.renderedHeight/frame.h,width=frame.w*scale,b=box(),x=b.x+fixture.ground.x*S-source.ground[0]*scale,y=Y+fixture.ground.y*S-source.ground[1]*scale;ctx.drawImage(atlases[state.orientation],frame.x,frame.y,frame.w,frame.h,x,y,width,source.renderedHeight);const result={x,y,w:width,h:source.renderedHeight,sourceGround:{x:source.ground[0],y:source.ground[1]},groundContact:{x:x+source.ground[0]*scale,y:y+source.ground[1]*scale},aspect:frame.w/frame.h,scale};if(source.procedureAttach){result.sourceProcedureAttach={x:source.procedureAttach[0],y:source.procedureAttach[1]};result.procedureAttach={x:x+source.procedureAttach[0]*scale,y:y+source.procedureAttach[1]*scale}}return result};
  function drawFurniture(){const f=fixtures(),hidden=hiddenOptional(),draws={};if(!hidden.includes('cabinet'))draws.cabinet=drawSprite('cabinet',f.cabinet);if(!hidden.includes('sink'))draws.sink=drawSprite('sink',f.sink);draws.tower=drawSprite('tower',f.tower);const tableSprite=state.duringProcedure?'tableOccupied':'tableEmpty';draws[tableSprite]=drawSprite(tableSprite,f.procedureTable);return{fixtures:f,hidden,draws,tableSprite,individualPatientVisible:false}}
  const inflated=r=>({left:r.left-radius,top:r.top-radius,right:r.left+r.width+radius,bottom:r.top+r.height+radius}),validPoint=(p,blocker,d)=>p.x>=radius-1e-6&&p.x<=d.cols-radius+1e-6&&p.y>=radius-1e-6&&p.y<=d.rows-radius+1e-6&&!(()=>{const r=inflated(blocker);return p.x>=r.left-1e-6&&p.x<=r.right+1e-6&&p.y>=r.top-1e-6&&p.y<=r.bottom+1e-6})();
  const doorCandidates=(id,blocker,d)=>{const values=[.28,.36,.5,.64,.72];if(id[0]==='N'||id[0]==='S'){const i=Number(id.slice(1))-1,y=id[0]==='N'?radius:d.rows-radius;return values.map(v=>({x:i+v,y})).filter(p=>validPoint(p,blocker,d))}const i=id.charCodeAt(1)-65,x=id[0]==='W'?radius:d.cols-radius;return values.map(v=>({x,y:i+v})).filter(p=>validPoint(p,blocker,d))};
  const key=p=>`${p.x.toFixed(2)},${p.y.toFixed(2)}`,simplify=path=>path.filter((p,i)=>i===0||i===path.length-1||Math.abs((path[i-1].x-p.x)*(path[i+1].y-p.y)-(path[i-1].y-p.y)*(path[i+1].x-p.x))>.0001);
  function bfs(from,to,blocker,d){const snap=p=>({x:Math.round(p.x/step)*step,y:Math.round(p.y/step)*step}),a=snap(from),z=snap(to);if(!validPoint(a,blocker,d)||!validPoint(z,blocker,d))return[];const queue=[a],prev=new Map([[key(a),null]]),points=new Map([[key(a),a]]),moves=[[step,0],[-step,0],[0,step],[0,-step]];while(queue.length){const p=queue.shift(),pk=key(p);if(pk===key(z)){const path=[];for(let k=pk;k;k=prev.get(k))path.unshift(points.get(k));return simplify(path)}for(const[dx,dy]of moves){const n=snap({x:p.x+dx,y:p.y+dy}),nk=key(n);if(validPoint(n,blocker,d)&&!prev.has(nk)){prev.set(nk,pk);points.set(nk,n);queue.push(n)}}}return[]}
  const routeCache={};function routeModel(f){if(routeCache[state.orientation])return routeCache[state.orientation];const d=dimensions(),blocker=f.procedureTable.navigationBlocker,start=state.orientation==='south'?{x:2.5,y:2.5}:rotatePoint({x:2.5,y:2.5}),routes={};for(const id of localSegments()){let best=[];for(const target of doorCandidates(id,blocker,d)){const route=bfs(start,target,blocker,d);if(route.length&&(!best.length||route.length<best.length))best=route}routes[id]=best}return routeCache[state.orientation]={start,routes,uses:{patient:bfs(start,f.procedureTable.patientApproach,blocker,d),staff:bfs(start,f.staff.ground,blocker,d)}}}
  function drawOverlay(model,f){if(!overlay.checked)return;const b=box(),route=model.routes[selectedLocal()]||[];ctx.save();if(route.length){ctx.strokeStyle='#e2b38d';ctx.lineWidth=3;ctx.beginPath();route.forEach((p,i)=>i?ctx.lineTo(b.x+p.x*S,Y+p.y*S):ctx.moveTo(b.x+p.x*S,Y+p.y*S));ctx.stroke()}for(const fixture of Object.values(f)){if(!fixture.footprint)continue;const q=fixture.footprint;ctx.setLineDash([5,4]);ctx.strokeStyle=fixture.collision==='solid'?'#f1c4a4':'#aad0c2';ctx.strokeRect(b.x+q.left*S,Y+q.top*S,q.width*S,q.height*S)}ctx.setLineDash([]);for(const[p,label,color]of[[f.procedureTable.patientApproach,'patient approach','#f3bd76'],[f.staff.ground,`staff faces ${f.staff.facing}`,'#aed6c2']]){ctx.fillStyle=color;ctx.beginPath();ctx.arc(b.x+p.x*S,Y+p.y*S,5,0,Math.PI*2);ctx.fill();ctx.font='10px sans-serif';ctx.fillText(label,b.x+p.x*S+7,Y+p.y*S+3)}ctx.restore()}
  function render(){const height=viewHeight();if(canvas.height!==height*SCALE)canvas.height=height*SCALE;ctx.setTransform(SCALE,0,0,SCALE,0,0);ctx.imageSmoothingEnabled=true;drawShell();const furniture=drawFurniture(),model=routeModel(furniture.fixtures);drawOverlay(model,furniture.fixtures);for(const button of targets.querySelectorAll('button')){const q=hitSlot(button.dataset.local);Object.assign(button.style,{left:`${q.x/W*100}%`,top:`${q.y/height*100}%`,width:`${q.w/W*100}%`,height:`${q.h/height*100}%`})}const reachable=Object.values(model.routes).filter(path=>path.length).length,local=selectedLocal(),table=furniture.fixtures.procedureTable,staff=furniture.fixtures.staff;status.innerHTML=`<strong>${state.orientation==='south'?'4 × 3 South view':'3 × 4 rotated view'}</strong> · ${local} (${state.selectedWorld} world) ${state.doors.has(state.selectedWorld)?'open':'closed'} · ${reachable}/14 approaches reachable<br>${state.duringProcedure?`Covered patient faces ${table.occupiedHeadFacing}; individual sprite hidden`:'Empty procedure table'} · staff faces ${staff.facing} · hidden: ${furniture.hidden.join(', ')||'none'}`;root.querySelectorAll('[data-world]').forEach(button=>{const active=state.doors.has(button.dataset.world);button.setAttribute('aria-pressed',String(active));button.classList.toggle('btn-primary',active)});canvas.dataset.model=JSON.stringify({orientation:state.orientation,viewHeight:height,dimensions:dimensions(),segments:localSegments(),worldSegments,worldToLocal:Object.fromEntries(worldSegments.map(id=>[id,toLocal(id)])),doors:[...state.doors],localDoors:[...localDoors()],selectedWorld:state.selectedWorld,selectedLocal:local,adjacency:[...state.adjacent],hidden:furniture.hidden,routes:model.routes,useRoutes:model.uses,fixtures:furniture.fixtures,draws:furniture.draws,tableState:state.duringProcedure?'occupiedCovered':'empty',individualPatientVisible:furniture.individualPatientVisible,replacementContract,spriteRevision:sprites.revision,shell:{tileSize:S,rearWallHeight:90,lowNorthHeight:29,sideCapWidth:14,southHeight:29,northDoorTransparent:true,sideDoorSeam:'floor-half-thickness',southDoorFloorBase:true,northColor:'#536168',floorColor:'#778087',floor:'24px dark utility slate with warm speckles',floorPatternSize:24,floorPatternOrigin:{x:box().x,y:Y},logicalGridDrawn:false},radius})}
  function toggleWorld(world){state.doors.has(world)?state.doors.delete(world):state.doors.add(world);state.selectedWorld=world;render()}
  function rebuildControls(){for(const id of ['endoscopy-north','endoscopy-south','endoscopy-west','endoscopy-east','endoscopy-adjacency','endoscopy-targets'])root.querySelector(`#${id}`).replaceChildren();for(const local of localSegments()){const world=toWorld(local),side={N:'north',S:'south',W:'west',E:'east'}[local[0]],button=document.createElement('button');button.type='button';button.className='btn btn-sm btn-outline-secondary';button.textContent=local;button.dataset.local=local;button.dataset.world=world;button.setAttribute('aria-label',`${local} doorway, world ${world}`);button.addEventListener('click',()=>toggleWorld(world));root.querySelector(`#endoscopy-${side}`).append(button);const hit=button.cloneNode(true);hit.className='endo-hit';hit.textContent='';hit.addEventListener('click',()=>toggleWorld(world));targets.append(hit)}const d=dimensions();for(let i=1;i<=d.cols;i++){const id=`N${i}`,label=document.createElement('label');label.className='form-check form-check-inline';label.innerHTML=`<input class="form-check-input" type="checkbox" data-adjacent="${id}"><span class="form-check-label">${id}</span>`;label.querySelector('input').addEventListener('change',event=>{event.target.checked?state.adjacent.add(id):state.adjacent.delete(id);render()});root.querySelector('#endoscopy-adjacency').append(label)}render()}
  orientationControl.addEventListener('change',event=>{state.orientation=event.target.value;state.adjacent.clear();rebuildControls()});overlay.addEventListener('change',render);optionalToggle.addEventListener('change',event=>{state.optional=event.target.checked;render()});procedureToggle.addEventListener('change',event=>{state.duringProcedure=event.target.checked;render()});atlases.south.onload=render;atlases.east.onload=render;rebuildControls();
  window.__endoscopyProof={state,render,rebuildControls,toLocal,toWorld,localSegments,fixtures,routeModel,replacementContract,ready:()=>atlases.south.complete&&atlases.east.complete&&atlases.south.naturalWidth>0&&atlases.east.naturalWidth>0};
})();
