import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { buildStandingGeometry, buildWalkGeometry } from '../../canonical-master/canonical-geometry.mjs';
import { V8_CALIBRATION } from '../green-rig-v8.mjs';
import { DIRECTIONAL_CALIBRATION } from '../directional/directional-rig-v1.mjs';
import { GREEN_ACTION_RIG_V1, greenStarJumpPose } from '../actions/green-action-rig-v1.mjs';
import { LAYER_ORDER } from '../../standard-atlas/schema-v1.mjs';
import { rigidBoneTransform, transformPoint } from '../../standard-atlas/rigid-geometry.mjs';
import { alphaBounds, createStandardCharacterRenderer, drawStandardSlot, standardStarJumpArmTarget, standardWalkArmProjection } from '../../standard-atlas/standard-character-renderer.mjs';
import { drawNormalizedLowerLeg } from '../../standard-atlas/normalized-lower-renderer.mjs';
import { drawRigidProfileLowerLeg } from '../../standard-atlas/rigid-profile-lower-renderer.mjs';
import { loadNormalizedLowerParts } from '../../standard-atlas/normalized-lower-loader.mjs';

export const VIEWS=Object.freeze(['south','east','west','north']);
export const RIG=Object.freeze({
  canvas:{width:160,height:320,axisX:80,floorY:287},
  neckY:{south:121,east:118,west:119,north:107},
  torsoHemY:{south:207,east:205,west:205,north:205},
  lowerTextureScale:{south:.40,east:.48,west:.48,north:.40},
  profileLowerWidthScale:1.70,profileLowerClipWidth:26,
  headNeckOffsetX:{south:0,east:0,west:0,north:0},
  armLengths:{upper:41,forearm:31},armLengthsByView:{south:{upper:42,forearm:31}},
  bendSign:{south:{left:-1,right:1},east:{left:1,right:1},west:{left:-1,right:-1},north:{left:1,right:-1}},
  armMotion:{profileBackwardScale:.42,profileForwardScale:1.45,restWristReach:70,restWristReachByView:{south:70,east:72,west:72,north:70},frontReachRatio:.997,frontSwingYScale:.85,frontProjectionMinScale:.83,southSwingXScale:V8_CALIBRATION.projectionScale.x*.4,southSwingYScale:V8_CALIBRATION.projectionScale.y,northSwingXScale:.85,directionalSwingYScale:.84,outward:{south:{left:14,right:-14},east:{left:-1,right:-1},west:{left:1,right:1},north:{left:-10,right:10}}},
});
export const ACTION=Object.freeze({bodyDrop:16,seatY:236,floorY:287,seatedScale:{south:.30,east:.28,west:.28,north:.30},seatedWrist:{south:{left:{x:96,y:202},right:{x:64,y:202}},east:{left:{x:95,y:202},right:{x:97,y:202}},west:{left:{x:63,y:202},right:{x:65,y:202}},north:{left:{x:62,y:200},right:{x:98,y:200}}},clipboard:{board:{x:56,y:137,width:44,height:34},contacts:{left:{x:100,y:171},right:{x:79,y:171}}}});
const standing=Object.fromEntries(VIEWS.map(view=>[view,buildStandingGeometry(view)])),walking=buildWalkGeometry();
// The legacy canonical South geometry labels screen-left/right, whereas atlas
// slots always label anatomical-left/right (screen-right/left facing South).
function anatomicalGeometry(view,g){return view==='south'?{...g,joints:{left:g.joints.right,right:g.joints.left}}:g;}
function mapped(view,g){const map=p=>view==='south'?{x:80+(p.x-112)*V8_CALIBRATION.projectionScale.x,y:287-(296-p.y)*V8_CALIBRATION.projectionScale.y}:{x:80+(p.x-112)*(view==='north'?32/26:1),y:287-(296-p.y)*((287-DIRECTIONAL_CALIBRATION.target.hipY)/96)};return{hipCenter:map(g.hipCenter),joints:Object.fromEntries(['left','right'].map(side=>[side,Object.fromEntries(['hip','knee','ankle','soleContact','shoulder','wrist'].map(k=>[k,map(g.joints[side][k])]))]))};}
export async function loadRig(repo){const root=resolve(repo,'tools/character-mapping/layered-pilot/brown-beanie-v1'),assets=resolve(root,'assets'),core=JSON.parse(readFileSync(resolve(assets,'core-parts-v1.json'),'utf8')),lower=JSON.parse(readFileSync(resolve(assets,'lower-parts-v1.json'),'utf8')),manifest=JSON.parse(readFileSync(resolve(root,'manifest-v1.json'),'utf8')),parts=manifest.parts,[upperImage,identityImage,lowerImage,actionImage,clipboardImage]=await Promise.all(['upper','identity','lower','actions','clipboard'].map(page=>loadImage(resolve(root,manifest.pages[page].file)))),renderer=createStandardCharacterRenderer({profile:RIG,partRecord:id=>{const p=parts[id];if(!p)throw Error(`missing ${id}`);return p;},hasPart:id=>Boolean(parts[id]),pageImage:id=>id.startsWith('identity.')?identityImage:upperImage});return{core,lower,manifest,parts,images:{upper:upperImage,identity:identityImage,lower:lowerImage,actions:actionImage,clipboard:clipboardImage},renderer,standardLower:loadNormalizedLowerParts(lowerImage,parts)};}
export function standingPose(view){return{view,index:null,phaseId:'stand',geometry:standing[view]};}
export function walkingPose(view,index){const n=((index%8)+8)%8,id=String(n+1).padStart(2,'0');return{view,index:n,phaseId:id,geometry:walking[view][id]};}
function drawBeanieLeg(context,loaded,view,side,joints){const args=[context,{lower:loaded.standardLower},view,side,joints,{textureScale:RIG.lowerTextureScale[view],transverseWidthScale:RIG.profileLowerWidthScale,pantWidth:RIG.profileLowerClipWidth}];return view==='east'||view==='west'?drawRigidProfileLowerLeg(...args):drawNormalizedLowerLeg(...args);}
const PROFILE_WALK_LAYERS=Object.freeze(['backHair','farArm','lower','torso','nearArm','head','frontHair','prop']);
export function renderPose(loaded,pose){const {view}=pose,geometry=anatomicalGeometry(view,pose.geometry),restGeometry=anatomicalGeometry(view,standing[view]),m=mapped(view,geometry),sm=mapped(view,restGeometry),bob=Math.round(m.hipCenter.y-sm.hipCenter.y),near=view==='east'?'right':view==='west'?'left':null,far=near?(near==='left'?'right':'left'):null,torso=loaded.renderer.torsoPose(view,bob),projection=Object.fromEntries(['left','right'].map(side=>[side,standardWalkArmProjection({view,side,geometry,standingGeometry:restGeometry,shoulder:torso.shoulders[side],profile:RIG})])),armTargets=Object.fromEntries(['left','right'].map(side=>[side,projection[side].target])),armOverrides=Object.fromEntries(['left','right'].map(side=>[side,projection[side].projectedLengths?{armLengths:projection[side].projectedLengths}:{}])),profile=view==='east'||view==='west',rendered=loaded.renderer.render({view,bob,armTargets,armOverrides,...(profile?{layerOrder:PROFILE_WALK_LAYERS,deferLowerToLayer:true}:{}),drawLower:context=>{const legs={};for(const side of near?[far,near]:['left','right'])legs[side]=drawBeanieLeg(context,loaded,view,side,m.joints[side]);return legs;}});return{canvas:rendered.canvas,metadata:{view,index:pose.index,phaseId:pose.phaseId,bob,mappedGeometry:m,legs:rendered.metadata.lower,lowerCanvas:rendered.metadata.lowerCanvas,arms:rendered.metadata.arms,armProjection:projection,torso:rendered.metadata.torso,head:rendered.metadata.head,near,far,layerOrder:rendered.metadata.layerOrder,bounds:rendered.metadata.bounds}};}

function mapActionPoint(p){return{x:80+(p.x-GREEN_ACTION_RIG_V1.sourceActionFrame.axisX)*V8_CALIBRATION.projectionScale.x,y:287-(GREEN_ACTION_RIG_V1.sourceActionFrame.floorY-p.y)*V8_CALIBRATION.projectionScale.y};}
function actionLegJoints(j){const soleY=(j.heel.y+j.toe.y)/2;return{hip:mapActionPoint(j.hip),knee:mapActionPoint(j.knee),ankle:mapActionPoint(j.ankle),soleContact:mapActionPoint({x:j.ankle.x,y:soleY})};}
export function starJumpPose(index){return greenStarJumpPose(index);}
export function renderStarJump(loaded,pose){if(pose.phaseId==='08'){const ready=renderPose(loaded,standingPose('south'));return{canvas:ready.canvas,metadata:{...ready.metadata,action:'starJump',stage:pose.stage,exactStandingEndpoint:true}};}const bob=pose.bodyBob,torso=loaded.renderer.torsoPose('south',bob),straight=Object.fromEntries(['left','right'].map(side=>[side,standardStarJumpArmTarget({shoulder:torso.shoulders[side],side,stage:pose.stage,profile:RIG})])),armTargets=Object.fromEntries(['left','right'].map(side=>[side,straight[side].target])),armOverrides=Object.fromEntries(['left','right'].map(side=>[side,{straight:true,armLengths:straight[side].armLengths}])),geometry=anatomicalGeometry('south',pose.geometry),joints=Object.fromEntries(['left','right'].map(side=>[side,actionLegJoints(geometry.joints[side])])),r=loaded.renderer.render({view:'south',bob,armTargets,armOverrides,drawLower:context=>Object.fromEntries(['left','right'].map(side=>[side,drawNormalizedLowerLeg(context,{lower:loaded.standardLower},'south',side,joints[side],{textureScale:RIG.lowerTextureScale.south})]))});return{canvas:r.canvas,metadata:{...r.metadata,action:'starJump',phaseId:pose.phaseId,index:pose.index,stage:pose.stage,bodyBob:bob,exactStandingEndpoint:false}};}
function seatedLowerMatrix(loaded,view,targetWaistX){const id=`actions.${view}.seatedLower`,record=loaded.parts[id],source=record.source.crop,pack=record.normalization,scale=ACTION.seatedScale[view],destY=288-source.height*scale,k=scale/pack.scale,cos=Math.cos(pack.rotationRadians),sin=Math.sin(pack.rotationRadians),waist=record.landmarks.seat.waist,px=waist.x-pack.translation.x,py=waist.y-pack.translation.y,sourceWaistX=(cos*px+sin*py)/pack.scale,desired={x:targetWaistX-sourceWaistX*scale,y:destY-source.y*scale},a=k*cos,b=-k*sin,c=k*sin,d=k*cos,matrix={a,b,c,d,e:desired.x-a*pack.translation.x-c*pack.translation.y,f:desired.y-b*pack.translation.x-d*pack.translation.y};return{id,matrix,waist:transformPoint(matrix,record.landmarks.seat.waist),seatContact:transformPoint(matrix,record.landmarks.seat.contact),soles:{left:transformPoint(matrix,record.landmarks.sole.left),right:transformPoint(matrix,record.landmarks.sole.right)}};}
export function renderSeated(loaded,view){const bob=ACTION.bodyDrop,torso=loaded.renderer.torsoPose(view,bob),targetWaistX=transformPoint(torso.matrix,torso.bodyAxis).x,lower=seatedLowerMatrix(loaded,view,targetWaistX),r=loaded.renderer.render({view,bob,armTargets:ACTION.seatedWrist[view],layerOrder:LAYER_ORDER[`seated${view[0].toUpperCase()}${view.slice(1)}`],drawLower:context=>{drawStandardSlot(context,loaded.images.actions,lower.id,lower.matrix);return lower;}});return{canvas:r.canvas,metadata:{...r.metadata,action:'sit',view,bodyDrop:bob,waistY:lower.waist.y,seatY:ACTION.seatY,floorY:ACTION.floorY}};}
function drawClipboardBoard(context,b){context.fillStyle='#4a3524';context.fillRect(b.x-2,b.y-2,b.width+4,b.height+4);context.fillStyle='#9b6b3d';context.fillRect(b.x,b.y,b.width,b.height);context.fillStyle='#eee4cf';context.fillRect(b.x+4,b.y+4,b.width-8,b.height-8);context.fillStyle='#5a5c5d';context.fillRect(b.x+b.width/2-6,b.y+1,12,5);}
export function renderClipboard(loaded){const base=renderPose(loaded,standingPose('south')),canvas=createCanvas(160,320),context=canvas.getContext('2d'),torso=loaded.renderer.torsoPose('south',0),head=loaded.renderer.headPose('south',0),arms={};for(const side of ['left','right']){const id=`clipboard.${side}.clipboardArm`,record=loaded.parts[id],target=ACTION.clipboard.contacts[side],matrix=rigidBoneTransform({sourceStart:record.landmarks.joint.shoulder,sourceEnd:record.landmarks.hand.contact,targetStart:torso.shoulders[side],targetEnd:target});arms[side]={id,matrix,shoulder:torso.shoulders[side],handContact:transformPoint(matrix,record.landmarks.hand.contact),wrist:transformPoint(matrix,record.landmarks.joint.wrist)};}const layers={lower(){for(const side of ['left','right'])drawNormalizedLowerLeg(context,{lower:loaded.standardLower},'south',side,base.metadata.mappedGeometry.joints[side],{textureScale:RIG.lowerTextureScale.south});},torso(){drawStandardSlot(context,loaded.images.upper,torso.id,torso.matrix);},head(){drawStandardSlot(context,loaded.images.identity,head.id,head.matrix);},prop(){drawClipboardBoard(context,ACTION.clipboard.board);},arms(){for(const side of ['left','right'])drawStandardSlot(context,loaded.images.clipboard,arms[side].id,arms[side].matrix);}};for(const layer of LAYER_ORDER.clipboardSouth)layers[layer]?.();return{canvas,metadata:{action:'clipboard',view:'south',torso,head,arms,board:ACTION.clipboard.board,floorY:287,layerOrder:LAYER_ORDER.clipboardSouth,bounds:alphaBounds(canvas)}};}
