import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { buildStandingGeometry, buildWalkGeometry } from '../../canonical-master/canonical-geometry.mjs';
import { V8_CALIBRATION } from '../green-rig-v8.mjs';
import { DIRECTIONAL_CALIBRATION } from '../directional/directional-rig-v1.mjs';
import { GREEN_ACTION_RIG_V1, greenStarJumpPose } from '../actions/green-action-rig-v1.mjs';

export const OVERSHIRT_VIEWS=Object.freeze(['south','east','west','north']);
export const OVERSHIRT_RIG_V1=Object.freeze({
  canvas:{width:160,height:320,axisX:80,floorY:287},
  torso:{scale:{south:.90,east:.90,west:.90,north:.90},topY:{south:104,east:105,west:103,north:104}},
  legAcrossScale:{south:.40,east:.40,west:.40,north:.40},
  armAcrossScale:{south:.46,east:.46,west:.46,north:.46},
  profileBackwardArmScale:DIRECTIONAL_CALIBRATION.profileBackwardArmScale,
  shoulders:{south:{left:{x:46,y:124},right:{x:114,y:124}},east:{left:{x:65,y:128},right:{x:62,y:128}},west:{left:{x:98,y:126},right:{x:95,y:126}},north:{left:{x:51,y:124},right:{x:110,y:124}}},
  restingHands:{south:{left:{x:43,y:210},right:{x:117,y:210}},east:{left:{x:67,y:211},right:{x:62,y:211}},west:{left:{x:98,y:211},right:{x:93,y:211}},north:{left:{x:49,y:211},right:{x:112,y:211}}},
  // Atlas labels are screen-left/screen-right. South's watch is authored in the
  // left-listed component but belongs on the viewer-right arm, so South swaps
  // donor placement. Profile donors retain their separately checked anatomy.
  armDonor:{south:{left:'right',right:'left'},east:{left:'left',right:'right'},west:{left:'left',right:'right'},north:{left:'left',right:'right'}},
  watchDonor:{south:'left',east:'left',west:'left',north:'left'},
});
export const OVERSHIRT_ACTION_RIG_V1=Object.freeze({durationMs:GREEN_ACTION_RIG_V1.durationMs,sitting:{bodyDrop:16,seatY:236,floorY:287,lowerScale:{south:.43,east:.42,west:.42,north:.43},lowerOffsetX:{south:0,east:7,west:-7,north:0},armAcrossScale:{south:.35,east:.34,west:.34,north:.35},handTargets:{south:{left:{x:64,y:220},right:{x:96,y:220}},east:{left:{x:97,y:220},right:{x:95,y:218}},west:{left:{x:63,y:220},right:{x:65,y:218}},north:{left:{x:62,y:220},right:{x:98,y:220}}}},clipboard:{board:{x:55,y:145,width:44,height:42},armAcrossScale:{left:.29,right:.29},handTargets:{left:{x:70,y:187},right:{x:99,y:175}}}});

const standingGeometry=Object.fromEntries(OVERSHIRT_VIEWS.map(v=>[v,buildStandingGeometry(v)])),walkingGeometry=buildWalkGeometry();
function pixels(image){const c=createCanvas(image.width,image.height),x=c.getContext('2d');x.drawImage(image,0,0);return x.getImageData(0,0,c.width,c.height).data;}
function alphaCentroid(data,width,bounds,start,end){let w=0,sx=0,sy=0;for(let y=Math.floor(bounds.y+bounds.height*start);y<Math.ceil(bounds.y+bounds.height*end);y++)for(let x=bounds.x;x<bounds.x+bounds.width;x++){const a=data[(y*width+x)*4+3];if(a<24)continue;w+=a;sx+=x*a;sy+=y*a;}if(!w)throw new Error(`empty anchor ${JSON.stringify(bounds)}`);return{x:sx/w,y:sy/w};}
function alphaBounds(canvas){const d=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let l=canvas.width,t=canvas.height,r=-1,b=-1;for(let i=0;i<d.length;i+=4)if(d[i+3]>=24){const p=i/4,x=p%canvas.width,y=Math.floor(p/canvas.width);l=Math.min(l,x);t=Math.min(t,y);r=Math.max(r,x);b=Math.max(b,y);}return{left:l,top:t,right:r,bottom:b,width:r-l+1,height:b-t+1};}
function tightBounds(data,width,rect){let l=rect.x,t=rect.y,r=rect.x+rect.width-1,b=rect.y+rect.height-1,found=false;l=rect.x+rect.width;r=rect.x-1;for(let y=rect.y;y<rect.y+rect.height;y++)for(let x=rect.x;x<rect.x+rect.width;x++)if(data[(y*width+x)*4+3]>=24){l=Math.min(l,x);r=Math.max(r,x);found=true;}if(!found)throw new Error(`empty trouser band ${JSON.stringify(rect)}`);return{x:l,y:t,width:r-l+1,height:b-t+1};}
const SHOE_SEAM_Y=Object.freeze({south:203,east:438,west:920,north:678});
function shoeBand(view,bounds){const start=SHOE_SEAM_Y[view]-bounds.y;if(start<=0||start>=bounds.height)throw new Error(`${view} invalid authored shoe seam`);return{x:bounds.x,y:bounds.y+start,width:bounds.width,height:bounds.height-start};}
function trouserBands(view,bounds){const end=SHOE_SEAM_Y[view]-bounds.y,thigh=Math.round(end*.49);return{thigh:{x:bounds.x,y:bounds.y,width:bounds.width,height:thigh},shin:{x:bounds.x,y:bounds.y+thigh,width:bounds.width,height:end-thigh},shoe:shoeBand(view,bounds)};}
function edgeAnchor(data,width,bounds,side){const x0=side==='right'?Math.floor(bounds.x+bounds.width*.55):bounds.x,x1=side==='right'?bounds.x+bounds.width:Math.ceil(bounds.x+bounds.width*.45);return alphaCentroid(data,width,{x:x0,y:bounds.y,width:x1-x0,height:bounds.height},0,.16);}
function farthestAnchor(data,width,bounds,origin){let max=0;for(let y=bounds.y;y<bounds.y+bounds.height;y++)for(let x=bounds.x;x<bounds.x+bounds.width;x++)if(data[(y*width+x)*4+3]>=24)max=Math.max(max,Math.hypot(x-origin.x,y-origin.y));let w=0,sx=0,sy=0;for(let y=bounds.y;y<bounds.y+bounds.height;y++)for(let x=bounds.x;x<bounds.x+bounds.width;x++){const a=data[(y*width+x)*4+3];if(a<24||Math.hypot(x-origin.x,y-origin.y)<max*.86)continue;w+=a;sx+=x*a;sy+=y*a;}return{x:sx/w,y:sy/w};}

export async function loadOvershirtRigV1(repo){const root='tools/character-mapping/layered-pilot/gray-overshirt/assets',provenanceFile=`${root}/overshirt-assets-v1-provenance.json`,provenance=JSON.parse(readFileSync(resolve(repo,provenanceFile),'utf8')),plateFile=`${root}/${provenance.baseAtlas.output.file}`,actionFile=`${root}/${provenance.actionAtlas.source.file}`,[plate,actionPlate]=await Promise.all([loadImage(resolve(repo,plateFile)),loadImage(resolve(repo,actionFile))]),data=pixels(plate),actionData=pixels(actionPlate),identity={},anchors={},actionAnchors={sitting:{},clipboard:{}};for(const view of OVERSHIRT_VIEWS){const rec=provenance.identity[view];identity[view]=await loadImage(resolve(repo,root,rec.head.file));anchors[view]={arms:{},shoes:{},trousers:{}};for(const side of ['left','right']){const arm=provenance.baseAtlas.parts[view].arms[side],leg=provenance.baseAtlas.parts[view].legs[side],shoe=shoeBand(view,leg),bands=trouserBands(view,leg);anchors[view].arms[side]={cap:alphaCentroid(data,plate.width,arm,0,.12),hand:alphaCentroid(data,plate.width,arm,.84,1)};anchors[view].shoes[side]={center:alphaCentroid(data,plate.width,shoe,0,.16),heel:edgeAnchor(data,plate.width,shoe,view==='east'?'left':'right')};anchors[view].trousers[side]={thigh:tightBounds(data,plate.width,bands.thigh),shin:tightBounds(data,plate.width,bands.shin)};}actionAnchors.sitting[view]={};for(const role of ['leftArm','rightArm']){const rect=provenance.actionAtlas.parts.sitting[view][role],shoulder=alphaCentroid(actionData,actionPlate.width,rect,0,.16);actionAnchors.sitting[view][role]={shoulder,hand:farthestAnchor(actionData,actionPlate.width,rect,shoulder)};}}for(const role of ['leftArm','rightArm']){const rect=provenance.actionAtlas.parts.clipboard[role],shoulder=alphaCentroid(actionData,actionPlate.width,rect,0,.16);actionAnchors.clipboard[role]={shoulder,hand:farthestAnchor(actionData,actionPlate.width,rect,shoulder)};}return{plate,actionPlate,provenance,identity,anchors,actionAnchors,files:{provenance:provenanceFile,plate:plateFile,actionPlate:actionFile,original:provenance.original.path}};}

function mapSouth(p){return{x:80+(p.x-112)*V8_CALIBRATION.projectionScale.x,y:287-(296-p.y)*V8_CALIBRATION.projectionScale.y};}
function mapDirectional(view,p){const xs=view==='north'?32/26:1,ys=(287-DIRECTIONAL_CALIBRATION.target.hipY)/96;return{x:80+(p.x-112)*xs,y:287-(296-p.y)*ys};}
function mapped(view,g){const map=p=>view==='south'?mapSouth(p):mapDirectional(view,p);return{hipCenter:map(g.hipCenter),joints:Object.fromEntries(['left','right'].map(s=>[s,Object.fromEntries(['hip','knee','ankle','soleContact','shoulder','wrist'].map(k=>[k,map(g.joints[s][k])]))]))};}
function perpendicular(a,b){const dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1;return{x:-dy/l,y:dx/l};}
function section(c,n,w){return[{x:c.x+n.x*w,y:c.y+n.y*w},{x:c.x-n.x*w,y:c.y-n.y*w}];}
function tri(c,image,s,t){const[s0,s1,s2]=s,[t0,t1,t2]=t,sd=(s1.x-s0.x)*(s2.y-s0.y)-(s2.x-s0.x)*(s1.y-s0.y);if(Math.abs(sd)<1e-6)return;const a=((t1.x-t0.x)*(s2.y-s0.y)-(t2.x-t0.x)*(s1.y-s0.y))/sd,cx=((s1.x-s0.x)*(t2.x-t0.x)-(s2.x-s0.x)*(t1.x-t0.x))/sd,b=((t1.y-t0.y)*(s2.y-s0.y)-(t2.y-t0.y)*(s1.y-s0.y))/sd,d=((s1.x-s0.x)*(t2.y-t0.y)-(s2.x-s0.x)*(t1.y-t0.y))/sd,e=t0.x-a*s0.x-cx*s0.y,f=t0.y-b*s0.x-d*s0.y;c.save();c.beginPath();c.moveTo(t0.x,t0.y);c.lineTo(t1.x,t1.y);c.lineTo(t2.x,t2.y);c.closePath();c.clip();c.setTransform(a,b,cx,d,e,f);c.drawImage(image,0,0);c.restore();}
function quad(c,image,r,q){const s0={x:r.x,y:r.y},s1={x:r.x+r.width,y:r.y},s3={x:r.x,y:r.y+r.height},t0=q[0],t1=q[1],t3=q[3],sd=(s1.x-s0.x)*(s3.y-s0.y)-(s3.x-s0.x)*(s1.y-s0.y),a=((t1.x-t0.x)*(s3.y-s0.y)-(t3.x-t0.x)*(s1.y-s0.y))/sd,cx=((s1.x-s0.x)*(t3.x-t0.x)-(s3.x-s0.x)*(t1.x-t0.x))/sd,b=((t1.y-t0.y)*(s3.y-s0.y)-(t3.y-t0.y)*(s1.y-s0.y))/sd,d=((s1.x-s0.x)*(t3.y-t0.y)-(s3.x-s0.x)*(t1.y-t0.y))/sd,e=t0.x-a*s0.x-cx*s0.y,f=t0.y-b*s0.x-d*s0.y;c.save();c.beginPath();c.moveTo(q[0].x,q[0].y);for(let i=1;i<4;i++)c.lineTo(q[i].x,q[i].y);c.closePath();c.clip();c.setTransform(a,b,cx,d,e,f);c.drawImage(image,0,0);c.restore();}
function rightEdge(canvas,y0,y1){const d=canvas.getContext('2d').getImageData(0,0,160,320).data;let e=-1;for(let y=Math.max(0,y0);y<=Math.min(319,y1);y++)for(let x=0;x<160;x++)if(d[(y*160+x)*4+3]>=24)e=Math.max(e,x);return e;}
function leftEdge(canvas,y0,y1){const d=canvas.getContext('2d').getImageData(0,0,160,320).data;let e=161;for(let y=Math.max(0,y0);y<=Math.min(319,y1);y++)for(let x=0;x<160;x++)if(d[(y*160+x)*4+3]>=24)e=Math.min(e,x);return e===161?-1:e;}
function drawLeg(c,loaded,view,side,j){const all=loaded.provenance.baseAtlas.parts[view].legs,rect=all[side],bands=loaded.anchors[view].trousers[side],profile=view==='east'||view==='west',donor=side,shoe=shoeBand(view,all[donor]),scale=OVERSHIRT_RIG_V1.legAcrossScale[view],visualAnkle=profile?{x:j.ankle.x,y:j.soleContact.y-shoe.height*scale}:j.ankle,overlap=profile?2:0,trouserAnkle={x:visualAnkle.x,y:visualAnkle.y+overlap},tn=perpendicular(j.hip,j.knee),sn=perpendicular(j.knee,trouserAnkle),sum={x:tn.x+sn.x,y:tn.y+sn.y},sl=Math.hypot(sum.x,sum.y)||1,kn={x:sum.x/sl,y:sum.y/sl},an=profile?{x:Math.sign(sn.x)||1,y:0}:sn,half=Math.max(bands.thigh.width,bands.shin.width)*scale/2,hip=section(j.hip,tn,half),ankle=section(trouserAnkle,an,half),ul=Math.hypot(j.knee.x-j.hip.x,j.knee.y-j.hip.y)||1,ll=Math.hypot(trouserAnkle.x-j.knee.x,trouserAnkle.y-j.knee.y)||1,kneeThigh=section({x:j.knee.x+(trouserAnkle.x-j.knee.x)/ll*1.25,y:j.knee.y+(trouserAnkle.y-j.knee.y)/ll*1.25},kn,half),kneeShin=section({x:j.knee.x-(j.knee.x-j.hip.x)/ul*1.25,y:j.knee.y-(j.knee.y-j.hip.y)/ul*1.25},kn,half),tc=createCanvas(160,320),tx=tc.getContext('2d');quad(tx,loaded.plate,bands.thigh,[hip[0],hip[1],kneeThigh[1],kneeThigh[0]]);quad(tx,loaded.plate,bands.shin,[kneeShin[0],kneeShin[1],ankle[1],ankle[0]]);tx.globalCompositeOperation='destination-in';tx.strokeStyle='#fff';tx.lineWidth=half*2;tx.lineCap='round';tx.lineJoin='round';tx.beginPath();tx.moveTo(j.hip.x,j.hip.y);tx.lineTo(j.knee.x,j.knee.y);tx.lineTo(trouserAnkle.x,trouserAnkle.y);tx.stroke();c.drawImage(tc,0,0);let x,y;if(profile){const anchor=loaded.anchors[view].shoes[donor],rearLean=view==='east'?Math.max(0,j.knee.x-j.ankle.x):Math.max(0,j.ankle.x-j.knee.x),base=visualAnkle.x-(anchor.center.x-shoe.x)*scale,w=shoe.width*scale,h=shoe.height*scale,cuffLeft=leftEdge(tc,Math.floor(trouserAnkle.y-10),Math.ceil(trouserAnkle.y)),cuffRight=rightEdge(tc,Math.floor(trouserAnkle.y-10),Math.ceil(trouserAnkle.y)),lower=cuffRight+1-w,upper=cuffLeft-1;x=cuffLeft<0||cuffRight<0?base:Math.max(lower,Math.min(upper,base));y=visualAnkle.y;c.drawImage(loaded.plate,shoe.x,shoe.y,shoe.width,shoe.height,x,y,w,h);return{joints:j,visualAnkle,trouserAnkle,kneeOverlap:2.5,seamOverlap:overlap,authoredShoeSeamY:SHOE_SEAM_Y[view],source:{trouser:bands,shoe},scale,shoeDonor:donor,shoeDestination:{x,y,width:w,height:h},rearLean,cuffLeft,cuffRight,heelEdge:view==='east'?x:x+w};}const w=shoe.width*scale,h=shoe.height*scale;x=j.soleContact.x-w/2;y=j.soleContact.y-h;c.drawImage(loaded.plate,shoe.x,shoe.y,shoe.width,shoe.height,x,y,w,h);return{joints:j,visualAnkle,trouserAnkle,kneeOverlap:2.5,seamOverlap:overlap,authoredShoeSeamY:SHOE_SEAM_Y[view],source:{trouser:bands,shoe},scale,shoeDonor:donor,shoeDestination:{x,y,width:w,height:h},rearLean:0,cuffLeft:null,cuffRight:null,heelEdge:null};}
function armTarget(view,side,g,bob){const stand=standingGeometry[view].joints[side],now=g.joints[side],swing={x:(now.wrist.x-now.shoulder.x)-(stand.wrist.x-stand.shoulder.x),y:(now.wrist.y-now.shoulder.y)-(stand.wrist.y-stand.shoulder.y)};if((view==='east'||view==='west')&&swing.x*(view==='east'?1:-1)<0)swing.x*=OVERSHIRT_RIG_V1.profileBackwardArmScale;const shoulder=OVERSHIRT_RIG_V1.shoulders[view][side],rest=OVERSHIRT_RIG_V1.restingHands[view][side],sx=view==='south'?swing.x*V8_CALIBRATION.projectionScale.x*.4:swing.x*(view==='north'?.85:1),sy=view==='south'?swing.y*V8_CALIBRATION.projectionScale.y:swing.y*.84;return{shoulder:{x:shoulder.x,y:shoulder.y+bob},hand:{x:rest.x+sx,y:rest.y+sy+bob}};}
function drawArm(c,loaded,view,side,target){const donor=OVERSHIRT_RIG_V1.armDonor[view][side],rect=loaded.provenance.baseAtlas.parts[view].arms[donor],source=loaded.anchors[view].arms[donor],sdx=source.hand.x-source.cap.x,sdy=source.hand.y-source.cap.y,sl=Math.hypot(sdx,sdy),tdx=target.hand.x-target.shoulder.x,tdy=target.hand.y-target.shoulder.y,tl=Math.hypot(tdx,tdy),sa={x:sdx/sl,y:sdy/sl},sx={x:-sa.y,y:sa.x},ta={x:tdx/tl,y:tdy/tl},tx={x:-ta.y,y:ta.x},along=tl/sl,across=OVERSHIRT_RIG_V1.armAcrossScale[view],m={a:ta.x*along*sa.x+tx.x*across*sx.x,b:ta.y*along*sa.x+tx.y*across*sx.x,c:ta.x*along*sa.y+tx.x*across*sx.y,d:ta.y*along*sa.y+tx.y*across*sx.y};m.e=target.shoulder.x-m.a*source.cap.x-m.c*source.cap.y;m.f=target.shoulder.y-m.b*source.cap.x-m.d*source.cap.y;c.save();c.setTransform(m.a,m.b,m.c,m.d,m.e,m.f);c.drawImage(loaded.plate,rect.x,rect.y,rect.width,rect.height,rect.x,rect.y,rect.width,rect.height);c.restore();return{donor,sourceRect:rect,sourceAnchors:source,target,matrix:m,alongScale:along,acrossScale:across,hasWatch:donor===OVERSHIRT_RIG_V1.watchDonor[view]};}
function drawTorso(c,loaded,view,bob){const r=loaded.provenance.baseAtlas.parts[view].torso,s=OVERSHIRT_RIG_V1.torso.scale[view],top=OVERSHIRT_RIG_V1.torso.topY[view]+bob,x=80-r.width*s/2;c.drawImage(loaded.plate,r.x,r.y,r.width,r.height,x,top,r.width*s,r.height*s);return{x,y:top,top,bottom:top+r.height*s,scale:s,sourceRect:r};}
function drawHead(c,loaded,view,bob){const rec=loaded.provenance.identity[view],x=80-rec.sourceHipX,y=-24+bob;c.drawImage(loaded.identity[view],x,y);return{x,y,scale:1,bounds:rec.head.bounds};}
export function overshirtPose(view,index=0){if(!OVERSHIRT_VIEWS.includes(view))throw new Error(`unsupported view ${view}`);const n=((index%8)+8)%8;return{view,index:n,phaseId:String(n+1).padStart(2,'0'),geometry:walkingGeometry[view][String(n+1).padStart(2,'0')]};}
export function overshirtStandingPose(view){if(!OVERSHIRT_VIEWS.includes(view))throw new Error(`unsupported view ${view}`);return{view,index:null,phaseId:'stand',geometry:standingGeometry[view]};}
export function renderOvershirtV1(loaded,pose){const{view,geometry}=pose,m=mapped(view,geometry),sm=mapped(view,standingGeometry[view]),bob=Math.round(m.hipCenter.y-sm.hipCenter.y),canvas=createCanvas(160,320),c=canvas.getContext('2d'),near=view==='east'?'right':view==='west'?'left':null,far=near?(near==='left'?'right':'left'):null,legs={},arms={},armCanvas={};for(const side of near?[far,near]:['left','right'])legs[side]=drawLeg(c,loaded,view,side,m.joints[side]);for(const side of ['left','right']){const ac=createCanvas(160,320),target=armTarget(view,side,geometry,bob);arms[side]=drawArm(ac.getContext('2d'),loaded,view,side,target);armCanvas[side]=ac;}let torso;if(near){c.drawImage(armCanvas[far],0,0);torso=drawTorso(c,loaded,view,bob);c.drawImage(armCanvas[near],0,0);}else{c.drawImage(armCanvas.left,0,0);c.drawImage(armCanvas.right,0,0);torso=drawTorso(c,loaded,view,bob);if(view==='south'){c.drawImage(armCanvas.left,0,0);c.drawImage(armCanvas.right,0,0);}else for(const side of ['left','right']){const p=arms[side].target.shoulder;c.save();c.beginPath();c.arc(p.x,p.y,18,0,Math.PI*2);c.clip();c.drawImage(armCanvas[side],0,0);c.restore();}}const head=drawHead(c,loaded,view,bob);return{canvas,metadata:{view,index:pose.index,phaseId:pose.phaseId,bodyBob:bob,mappedGeometry:m,legs,arms,torso,identity:{head},bounds:alphaBounds(canvas),near,far,layerPolicy:near?['legs','farArm','torso','nearArm','head']:view==='south'?['legs','armsBehind','torso','armsFront','head']:['legs','arms','torso','caps','head']}};}

function mapActionPoint(p){return{x:80+(p.x-GREEN_ACTION_RIG_V1.sourceActionFrame.axisX)*V8_CALIBRATION.projectionScale.x,y:287-(GREEN_ACTION_RIG_V1.sourceActionFrame.floorY-p.y)*V8_CALIBRATION.projectionScale.y};}
function actionLegJoints(j){const soleY=(j.heel.y+j.toe.y)/2;return{hip:mapActionPoint(j.hip),knee:mapActionPoint(j.knee),ankle:mapActionPoint(j.ankle),soleContact:mapActionPoint({x:j.ankle.x,y:soleY})};}
export function overshirtStarJumpPose(index){return greenStarJumpPose(index);}
export function renderOvershirtStarJump(loaded,pose){if(pose.phaseId==='08'){const ready=renderOvershirtV1(loaded,overshirtStandingPose('south'));return{canvas:ready.canvas,metadata:{...ready.metadata,action:'starJump',stage:pose.stage,exactStandingEndpoint:true}};}const canvas=createCanvas(160,320),c=canvas.getContext('2d'),legs={};for(const side of ['left','right'])legs[side]=drawLeg(c,loaded,'south',side,actionLegJoints(pose.geometry.joints[side]));const arms={},armCanvases={},offsets={gather:{x:6,y:78},takeoff:{x:18,y:72},opening:{x:35,y:-68},'open-star':{x:35,y:-70},closing:{x:35,y:-68},'soft-landing':{x:18,y:72},recover:{x:6,y:78}};for(const side of ['left','right']){const shoulderBase=OVERSHIRT_RIG_V1.shoulders.south[side],shoulder={x:shoulderBase.x,y:shoulderBase.y+pose.bodyBob},sign=side==='left'?-1:1,offset=offsets[pose.stage],target={shoulder,hand:{x:shoulder.x+offset.x*sign,y:shoulder.y+offset.y}},ac=createCanvas(160,320);arms[side]=drawArm(ac.getContext('2d'),loaded,'south',side,target);armCanvases[side]=ac;c.drawImage(ac,0,0);}const torso=drawTorso(c,loaded,'south',pose.bodyBob);for(const side of ['left','right']){const p=arms[side].target.shoulder;c.save();c.beginPath();c.arc(p.x,p.y,18,0,Math.PI*2);c.clip();c.drawImage(armCanvases[side],0,0);c.restore();}const head=drawHead(c,loaded,'south',pose.bodyBob);return{canvas,metadata:{action:'starJump',phaseId:pose.phaseId,index:pose.index,stage:pose.stage,bodyBob:pose.bodyBob,legs,arms,torso,identity:{head},bounds:alphaBounds(canvas),exactStandingEndpoint:false}};}

function limbMatrix(source,start,end,across){const sdx=source.hand.x-source.shoulder.x,sdy=source.hand.y-source.shoulder.y,sl=Math.hypot(sdx,sdy),tdx=end.x-start.x,tdy=end.y-start.y,tl=Math.hypot(tdx,tdy),sa={x:sdx/sl,y:sdy/sl},sx={x:-sa.y,y:sa.x},ta={x:tdx/tl,y:tdy/tl},tx={x:-ta.y,y:ta.x},along=tl/sl,m={a:ta.x*along*sa.x+tx.x*across*sx.x,b:ta.y*along*sa.x+tx.y*across*sx.x,c:ta.x*along*sa.y+tx.x*across*sx.y,d:ta.y*along*sa.y+tx.y*across*sx.y,alongScale:along,acrossScale:across};m.e=start.x-m.a*source.shoulder.x-m.c*source.shoulder.y;m.f=start.y-m.b*source.shoulder.x-m.d*source.shoulder.y;return m;}
function drawActionArm(c,loaded,rect,source,start,end,across){const m=limbMatrix(source,start,end,across);c.save();c.setTransform(m.a,m.b,m.c,m.d,m.e,m.f);c.drawImage(loaded.actionPlate,rect.x,rect.y,rect.width,rect.height,rect.x,rect.y,rect.width,rect.height);c.restore();return{sourceRect:rect,sourceAnchors:source,shoulder:start,hand:end,matrix:m,alongScale:m.alongScale,acrossScale:m.acrossScale};}
function sittingRole(view,side){if(view==='south')return side==='left'?'rightArm':'leftArm';return side==='left'?'leftArm':'rightArm';}
function drawSeatedLower(c,loaded,view){const rect=loaded.provenance.actionAtlas.parts.sitting[view].lowerBody,s=OVERSHIRT_ACTION_RIG_V1.sitting.lowerScale[view],x=80-rect.width*s/2+OVERSHIRT_ACTION_RIG_V1.sitting.lowerOffsetX[view],y=288-rect.height*s;c.drawImage(loaded.actionPlate,rect.x,rect.y,rect.width,rect.height,x,y,rect.width*s,rect.height*s);return{x,y,scale:s,sourceRect:rect,bottom:y+rect.height*s};}
export function renderOvershirtSeated(loaded,view){if(!OVERSHIRT_VIEWS.includes(view))throw new Error(`unsupported seated view ${view}`);const canvas=createCanvas(160,320),c=canvas.getContext('2d'),lowerBody=drawSeatedLower(c,loaded,view),arms={},armCanvases={};for(const side of ['left','right']){const role=sittingRole(view,side),rect=loaded.provenance.actionAtlas.parts.sitting[view][role],source=loaded.actionAnchors.sitting[view][role],base=OVERSHIRT_RIG_V1.shoulders[view][side],start={x:base.x,y:base.y+16},end=OVERSHIRT_ACTION_RIG_V1.sitting.handTargets[view][side],ac=createCanvas(160,320);arms[side]={...drawActionArm(ac.getContext('2d'),loaded,rect,source,start,end,OVERSHIRT_ACTION_RIG_V1.sitting.armAcrossScale[view]),role,hasWatch:role==='leftArm'};armCanvases[side]=ac;}const near=view==='east'?'right':view==='west'?'left':null,far=near?(near==='left'?'right':'left'):null;let torso;if(near){c.drawImage(armCanvases[far],0,0);torso=drawTorso(c,loaded,view,16);c.drawImage(armCanvases[near],0,0);}else if(view==='north'){c.drawImage(armCanvases.left,0,0);c.drawImage(armCanvases.right,0,0);torso=drawTorso(c,loaded,view,16);}else{torso=drawTorso(c,loaded,view,16);c.drawImage(armCanvases.left,0,0);c.drawImage(armCanvases.right,0,0);}const head=drawHead(c,loaded,view,16);return{canvas,metadata:{action:'sit',view,bodyDrop:16,waistY:lowerBody.y,seatY:236,floorY:287,lowerBody,arms,torso,identity:{head},bounds:alphaBounds(canvas),near,far}};}
function drawClipboard(c,b){c.fillStyle='#4a3524';c.fillRect(b.x-2,b.y-2,b.width+4,b.height+4);c.fillStyle='#9b6b3d';c.fillRect(b.x,b.y,b.width,b.height);c.fillStyle='#eee4cf';c.fillRect(b.x+4,b.y+4,b.width-8,b.height-8);c.fillStyle='#5a5c5d';c.fillRect(b.x+b.width/2-6,b.y+1,12,5);return b;}
export function renderOvershirtClipboard(loaded){const base=renderOvershirtV1(loaded,overshirtStandingPose('south')),canvas=createCanvas(160,320),c=canvas.getContext('2d');for(const side of ['left','right'])drawLeg(c,loaded,'south',side,base.metadata.mappedGeometry.joints[side]);const torso=drawTorso(c,loaded,'south',0),head=drawHead(c,loaded,'south',0),board=drawClipboard(c,OVERSHIRT_ACTION_RIG_V1.clipboard.board),arms={};for(const side of ['left','right']){const role=side==='left'?'rightArm':'leftArm',rect=loaded.provenance.actionAtlas.parts.clipboard[role],source=loaded.actionAnchors.clipboard[role],start=OVERSHIRT_RIG_V1.shoulders.south[side],end=OVERSHIRT_ACTION_RIG_V1.clipboard.handTargets[side];arms[side]={...drawActionArm(c,loaded,rect,source,start,end,OVERSHIRT_ACTION_RIG_V1.clipboard.armAcrossScale[side]),role,hasWatch:role==='leftArm'};}return{canvas,metadata:{action:'clipboard',view:'south',legs:base.metadata.legs,torso,identity:{head},board,arms,bounds:alphaBounds(canvas),floorY:287}};}
