import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { REMAINING10_SOURCES as S } from "./source-catalog-remaining10";

const WORKUP = "claim.gs028e.mixing_initial_workup";
const METHOD = "claim.gs028e.mixing_method";
const CORRECTION = "claim.gs028e.mixing_correction";
const INHIBITION = "claim.gs028e.mixing_noncorrection";
const DELAYED = "claim.gs028e.mixing_time_dependent";
const LIMITS = "claim.gs028e.mixing_limits";
const BASIC = "timing.test.basic_labs";
const SERVICE = "service.basic_labs";
const EXTERNAL = ["route.basic_labs.outsourced"];
const CORRECTED_RESULT = "The external specialist coagulation laboratory reports that the aPTT mixture corrects according to its validated criteria both immediately and after incubation. Specific factor assays remain pending. The patient remains clinically stable.";
const INHIBITED_RESULT = "The external specialist coagulation laboratory reports that the aPTT mixture fails to correct according to its validated criteria both immediately and after incubation. Specific factor and inhibitor assessments remain pending. The patient remains clinically stable.";
const gate = (resultNarrative: string) => ({
  timingProfileId: BASIC, serviceId: SERVICE,
  gate: { serviceId: SERVICE, pendingLabel: "External coagulation analysis pending", resultNarrative, routeIds: EXTERNAL },
});

export const COAGULATION_FAMILY = buildFamily({
  slug: "coagulation", label: "Specialist coagulation workup review",
  sources: [S.tiedeMixing, S.czempikMixing],
  serviceContracts: [{ serviceId: SERVICE, allowedRouteIds: EXTERNAL, delivery: "existing_balance_contract" }],
  pairing: { indices: [0, 1], updates: [CORRECTED_RESULT, INHIBITED_RESULT] },
  claims: [
    { id: WORKUP, statement: "For an unexplained isolated prolonged aPTT after specimen and anticoagulant interference have been assessed, a mixing study can initially help distinguish factor deficiency from an inhibitory substance when immediate FVIII activity testing is unavailable.", sourceIds: [S.tiedeMixing.id, S.czempikMixing.id], category: "evaluation", certainty: "moderate", limitation: "Conditional laboratory workup, not routine preoperative screening or a universal mandatory next test. The cases supply repeated unexplained findings, reviewed interferences and unavailable immediate FVIII:C. Specific factor assays are pursued in parallel by the specialist.", population: "Stable adults already referred for an outside specialist evaluation of an unexplained isolated prolonged aPTT." },
    { id: METHOD, statement: "An aPTT mixing study evaluates the aPTT response after combining patient plasma with normal plasma; immediate and incubated assessments can reveal different inhibitory patterns.", sourceIds: [S.tiedeMixing.id, S.czempikMixing.id], category: "evaluation", certainty: "high", limitation: "Qualitative method only. No mixing ratio, incubation duration, temperature or correction threshold is specified. Neither platelet testing nor a patient-only repeat is that plasma comparison.", population: "Stable adults reviewing the purpose or method of an outside specialist mixing assessment." },
    { id: CORRECTION, statement: "Correction of a prolonged aPTT with normal plasma both immediately and after incubation favors factor deficiency as an initial interpretation.", sourceIds: [S.czempikMixing.id], category: "evaluation", certainty: "moderate", limitation: "The independent society-journal review supports the laboratory principle, not importation of its ICU management algorithm. Correction is laboratory-defined and does not identify a particular factor or establish a final diagnosis.", population: "Adults reviewing a specialist laboratory's qualitative immediate and incubated mixing report." },
    { id: INHIBITION, statement: "Failure of the aPTT mixture to correct immediately and after incubation favors an inhibitory substance as an initial interpretation.", sourceIds: [S.czempikMixing.id], category: "evaluation", certainty: "moderate", limitation: "This finding does not establish a particular inhibitor, acquired hemophilia A or a clinical bleeding phenotype. Drug and preanalytical effects must be considered; the authored report states these have been assessed.", population: "Adults reviewing a valid specialist mixing study with persistent noncorrection." },
    { id: DELAYED, statement: "Initial correction followed by loss of correction after incubation can indicate a time-dependent inhibitor; immediate correction alone does not exclude that possibility.", sourceIds: [S.tiedeMixing.id, S.czempikMixing.id], category: "evaluation", certainty: "moderate", limitation: "No exact incubation period, temperature, ratio or laboratory cutoff is authored. A qualitative pattern suggests a mechanism and requires appropriate factor/inhibitor assessment; it is not a definitive diagnosis.", population: "Adults reviewing immediate versus incubated results from a specialist coagulation laboratory." },
    { id: LIMITS, statement: "Mixing studies are incompletely standardized, cannot by themselves establish or exclude acquired hemophilia A, and should not replace appropriate parallel factor assays.", sourceIds: [S.tiedeMixing.id, S.czempikMixing.id], category: "safety_boundary", certainty: "high", limitation: "No universal correction threshold or isolated-aPTT bleeding-risk estimate is inferred. Interpretation remains tied to the laboratory method and clinical context.", population: "Adults with an outside specialist workup of an unexplained prolonged aPTT." },
  ],
  concepts: [
    {
      id: "concept.coagulation.isolated-aptt-mixing-workup", displayName: "Choose a conditional aPTT mixing assessment",
      learningObjective: "Select a specialist mixing study as an initial deficiency-versus-inhibition assessment for a repeated unexplained isolated prolonged aPTT when immediate FVIII:C is unavailable and interferences have been assessed.",
      stage: 0, educationalTier: 1, conceptType: "workup", evidenceClaimIds: [WORKUP, METHOD, LIMITS],
      variants: variants([
        { slug: "elective-record-workup", complaint: "Abnormal clotting report", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is clinically stable in a clinic review of an outside preoperative workup. Repeated testing shows an unexplained prolonged aPTT with normal PT. The specialist has assessed specimen problems and anticoagulant interference. Immediate FVIII activity testing is unavailable; factor assays are being arranged in parallel at an external coagulation laboratory.", stem: "Which specialist laboratory test can initially distinguish factor deficiency from inhibition in this patient's supplied unexplained isolated-aPTT workup?", correct: ["aPTT mixing study", "Mixing can supply an initial deficiency-versus-inhibition clue in the stated conditional setting."], wrong: [["Platelet-function testing", "This does not provide the normal-plasma mixing comparison requested by the task.", { timingProfileId: BASIC }], ["Fibrinogen activity measurement", "This does not provide the requested patient-plasma mixing comparison.", { timingProfileId: BASIC }], ["Prothrombin-time measurement", "Repeating the already normal PT does not supply the mixing comparison requested here.", { timingProfileId: BASIC }]], explanation: "The correct answer is “aPTT mixing study.” The selected external laboratory evaluates immediate and incubated mixing alongside the specialist's factor workup. Mixing is an initial clue, not a final diagnosis or a substitute for factor assays.", claims: [WORKUP, METHOD, LIMITS], test: gate(CORRECTED_RESULT), ageYears: [46, 67] },
        { slug: "specialist-bruising-review", complaint: "Coagulation workup question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is stable without active bleeding while reviewing an outside hematologist's workup of previous bruising. The aPTT remains isolatedly prolonged on repeat sampling. Specimen and anticoagulant interferences have been assessed, immediate FVIII:C is unavailable, and appropriate factor assays are being arranged in parallel externally.", stem: "Which specialist assessment can initially separate deficiency from an inhibitory effect in this patient's stated isolated-aPTT workup?", correct: ["aPTT mixing study", "The specialist can assess whether normal plasma corrects the abnormal aPTT under its validated mixing protocol."], wrong: [["Platelet-count measurement", "This does not provide the requested comparison after addition of normal plasma.", { timingProfileId: BASIC }], ["Fibrinogen activity measurement", "A single fibrinogen result does not perform the requested mixing comparison.", { timingProfileId: BASIC }], ["Prothrombin-time measurement", "PT measurement is not the requested aPTT deficiency-versus-inhibition mixing assessment.", { timingProfileId: BASIC }]], explanation: "The correct answer is “aPTT mixing study.” Analysis occurs at the external specialist laboratory. A result still requires method-aware interpretation and appropriate parallel factor testing.", claims: [WORKUP, METHOD, LIMITS], test: gate(INHIBITED_RESULT), ageYears: [39, 61] },
        { slug: "referral-test-purpose", complaint: "Referral test question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside specialist plan for a repeated unexplained isolated prolonged aPTT. The patient is well without active bleeding; drug and specimen interference have been assessed. Immediate FVIII:C is unavailable. The specialist has ordered a mixing study and is pursuing specific factor assays in parallel, but no mixing result is available yet.", stem: "Which initial uncertainty does the ordered mixing study address in this patient's stated specialist workup?", correct: ["Factor deficiency versus plasma inhibition", "Mixing can initially help distinguish inadequate factor activity from an inhibitory effect."], wrong: [["Bleeding tendency versus thrombotic tendency", "A mixing study does not itself establish the patient's clinical bleeding or thrombotic phenotype."], ["Platelet deficiency versus platelet dysfunction", "The mixing comparison assesses plasma aPTT behavior rather than platelet number versus function."], ["Inherited disease versus acquired disease", "A mixing response does not by itself establish whether the cause is inherited or acquired."]], explanation: "The correct answer is “Factor deficiency versus plasma inhibition.” This describes why the outside specialist ordered the conditional assessment; it does not interpret a result before one is available or replace the parallel factor assays.", claims: [WORKUP, METHOD, LIMITS], ageYears: [51, 73] },
        { slug: "outside-lab-planning", complaint: "Laboratory plan review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside coagulation team's mixing-study plan for repeat unexplained isolated aPTT prolongation. Drug and specimen interference have been assessed and immediate FVIII:C is unavailable. The patient remains well, and specific factor testing is being pursued in parallel. The patient asks which comparison defines the proposed mixing method.", stem: "Which laboratory comparison defines the mixing assessment in this patient's specialist plan?", correct: ["Patient plasma combined with normal plasma", "The method evaluates aPTT response after adding normal plasma to patient plasma."], wrong: [["Patient plasma measured without normal plasma", "An unmixed patient-only repeat is not the proposed mixing comparison."], ["Normal plasma measured without patient plasma", "A control-only measurement does not test the patient's response to mixing."], ["Patient plasma combined with more patient plasma", "Adding only the patient's own plasma does not provide the normal-plasma comparison."]], explanation: "The correct answer is “Patient plasma combined with normal plasma.” The external coagulation laboratory performs the specialized analysis; immediate and incubated comparisons require its validated protocol.", claims: [WORKUP, METHOD, DELAYED, LIMITS], ageYears: [35, 58] },
      ]),
    },
    {
      id: "concept.coagulation.mixing-study-initial-interpretation", displayName: "Interpret a mixing study as an initial clue",
      learningObjective: "Interpret correction, noncorrection and time-dependent changes as initial laboratory clues while preserving method limitations and the need for factor/inhibitor assessment.",
      stage: 0, educationalTier: 1, conceptType: "applied_science", evidenceClaimIds: [CORRECTION, INHIBITION, DELAYED, LIMITS],
      variants: variants([
        { slug: "both-times-correct", complaint: "Mixing result review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is stable while reviewing a specialist mixing report from an outside laboratory. The patient-plus-normal-plasma aPTT corrects both immediately and after incubation according to that laboratory's criteria. Interferences were assessed, and specific factor assays remain pending.", stem: "Which initial interpretation best fits the specialist's immediate and incubated correction report for this patient?", correct: ["A factor deficiency is favored", "Correction at both assessments favors deficiency as an initial mechanism, without identifying a factor."], wrong: [["An inhibitory substance is favored", "The supplied immediate and incubated correction instead favors deficiency as the initial distinction."], ["Time-dependent inhibition is favored", "The supplied report does not show loss of correction after incubation."], ["A specimen or drug artifact is favored", "The case supplies an assessed-interference specialist report; this correction pattern primarily favors deficiency."]], explanation: "The correct answer is “A factor deficiency is favored.” Use the external laboratory's validated criteria, then interpret the parallel factor studies; mixing alone is not a final diagnosis.", claims: [CORRECTION, INHIBITION, DELAYED, LIMITS], ageYears: [46, 67] },
        { slug: "both-times-prolonged", complaint: "Mixing result review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is stable while reviewing an outside specialist mixing report. The mixture remains prolonged both immediately and after incubation by the laboratory's validated criteria. Specimen and anticoagulant interferences have been assessed; specific factor and inhibitor studies remain pending.", stem: "Which initial interpretation best fits the specialist's persistent mixing noncorrection report for this patient?", correct: ["An inhibitory substance is favored", "Persistent noncorrection favors an inhibitory effect but does not identify its source."], wrong: [["A factor deficiency is favored", "Persistent noncorrection instead favors an inhibitory effect as the initial distinction."], ["Normal coagulation function is favored", "Persistent noncorrection does not favor a normal plasma aPTT response."], ["A specimen or drug artifact is favored", "The case supplies an assessed-interference specialist report; the initial mixing pattern favors inhibition."]], explanation: "The correct answer is “An inhibitory substance is favored.” The external laboratory's result is an initial clue; factor and inhibitor assessment must establish the cause in clinical context.", claims: [INHIBITION, CORRECTION, LIMITS], ageYears: [39, 61] },
        { slug: "correction-lost-with-incubation", complaint: "Two mixing results", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings a completed outside coagulation report. After reviewed specimen and anticoagulant interferences, the aPTT mixture initially corrects but loses correction after incubation under the laboratory's validated protocol. Specific assays are still being interpreted, and the patient is clinically stable.", stem: "Which initial mechanism is suggested by this patient's correction disappearing after incubation?", correct: ["Time-dependent inhibitory activity", "A delayed inhibitory effect can appear after initial correction."], wrong: [["Correction maintained by factor replacement", "The supplied mixture loses correction rather than maintaining a corrected aPTT."], ["Normal baseline coagulation activity", "The time-dependent abnormal response does not describe normal patient-plasma behavior."], ["Unchanging immediate inhibitory activity", "The report describes initial correction followed by a delayed inhibitory effect, rather than unchanged immediate inhibition."]], explanation: "The correct answer is “Time-dependent inhibitory activity.” This pattern requires appropriate factor/inhibitor assessment; it does not establish acquired hemophilia A or a particular inhibitor by itself.", claims: [DELAYED, LIMITS, CORRECTION, INHIBITION], ageYears: [43, 70] },
        { slug: "immediate-only-report", complaint: "Partial mixing report", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is stable in clinic while reviewing a partial outside mixing report for a repeated unexplained prolonged aPTT. The report says the immediate mixture corrects, but the incubated comparison and specific factor studies are not yet available. The outside specialist has assessed drug and specimen interference.", stem: "What can this patient's immediate-only correction report establish about a time-dependent inhibitor while the incubated result is unavailable?", correct: ["Not excluded by immediate correction", "Immediate correction alone cannot exclude an inhibitor whose effect emerges after incubation."], wrong: [["Excluded by immediate correction", "An inhibitor can become apparent after the initially corrected measurement."], ["Confirmed by immediate correction", "Immediate correction alone does not establish a time-dependent inhibitor."], ["Unrelated to the incubated comparison", "Comparison after incubation is relevant to detecting a time-dependent inhibitory effect."]], explanation: "The correct answer is “Not excluded by immediate correction.” Interpret the full specialist assessment and parallel factor assays; mixing alone cannot establish or exclude acquired hemophilia A.", claims: [DELAYED, LIMITS, CORRECTION], ageYears: [32, 56] },
      ]),
    },
  ],
});
