import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { REMAINING10_SOURCES as S } from "./source-catalog-remaining10";

const TYPE_I = "claim.gs028e.type_i";
const HIVES_LIMIT = "claim.gs028e.urticaria_not_always_ige";
const TYPE_IV = "claim.gs028e.type_iv";
const NON_IGE = "claim.gs028e.non_ige_antibody_comparison";
const TCMR = "claim.gs028e.t_cell_graft_comparison";
const PREFORMED = "claim.gs028e.hyperacute_preformed";
const VASCULAR = "claim.gs028e.hyperacute_vascular";

export const IMMUNOLOGY_FAMILY = buildFamily({
  slug: "immunology", label: "Outside immune-reaction record review",
  sources: [S.niaidFoodSummary, S.fdaImmunotoxicity, S.contactDermatitis, S.hyperacuteReview, S.ahrqTransplant],
  claims: [
    { id: TYPE_I, statement: "In a documented IgE-mediated type I reaction, antigen engagement of IgE on sensitized mast cells can trigger mediator release.", sourceIds: [S.niaidFoodSummary.id, S.fdaImmunotoxicity.id], category: "definition", certainty: "high", limitation: "Stable immune mechanism, not a diagnosis from symptoms alone or an allergy-treatment protocol. Both federal sources are older; their mechanism is cross-checked without importing historical management instructions.", population: "Adults discussing an outside-confirmed IgE-mediated reaction." },
    { id: HIVES_LIMIT, statement: "Urticaria alone does not establish an IgE-mediated mechanism because contact urticaria may be IgE-mediated or non-IgE-mediated.", sourceIds: [S.niaidFoodSummary.id], category: "safety_boundary", certainty: "high", limitation: "The authored cases explicitly supply specialist confirmation where an IgE mechanism is tested; they do not classify all hives, all food reactions or all drug reactions as type I.", population: "Adults reviewing a resolved urticarial reaction." },
    { id: TYPE_IV, statement: "Confirmed allergic contact dermatitis is a T-cell-mediated, type IV delayed hypersensitivity reaction rather than an IgE-mediated mast-cell reaction.", sourceIds: [S.contactDermatitis.id, S.fdaImmunotoxicity.id], category: "definition", certainty: "high", limitation: "This applies to allergic contact dermatitis, not every irritant contact rash. Exact onset intervals, patch-testing instructions and treatment are not taught.", population: "Adults with specialist-confirmed allergic contact dermatitis." },
    { id: NON_IGE, statement: "Type II and type III hypersensitivity involve non-IgE antibodies, including IgG or IgM, and complement; these broad antibody mechanisms differ from the IgE mast-cell and T-cell contact pathways.", sourceIds: [S.fdaImmunotoxicity.id], category: "definition", certainty: "high", limitation: "Narrow comparator from the FDA glossary, Hypersensitivity. No specific cytotoxic target, immune-complex disease, frequency or management claim is inferred from this older source.", population: "Adults comparing the established immune mechanism of a resolved reaction." },
    { id: TCMR, statement: "Allograft rejection may involve T-cell-mediated or antibody-mediated pathways, and the pathways can coexist; a documented hyperacute preformed-antibody event should not be substituted with an unproven T-cell-only explanation.", sourceIds: [S.hyperacuteReview.id], category: "safety_boundary", certainty: "moderate", limitation: "Narrow comparator from the transplant review Abstract; does not classify all acute rejection as T-cell-only, infer a treatment or establish a new active diagnosis.", population: "Stable adults reviewing a confirmed historical transplant rejection mechanism." },
    { id: PREFORMED, statement: "Documented hyperacute allograft rejection can be driven by recipient antibodies that were present before transplantation and recognize donor antigens.", sourceIds: [S.hyperacuteReview.id, S.ahrqTransplant.id], category: "definition", certainty: "high", limitation: "Narrow mechanism from a transplant review plus an independent commissioned background cross-check. Early graft dysfunction alone does not prove rejection or this mechanism; no transplant timing threshold or treatment is inferred.", population: "Stable adults reviewing an outside-confirmed historical hyperacute allograft event." },
    { id: VASCULAR, statement: "Preformed donor-specific antibodies can bind allograft endothelium and initiate complement-associated vascular injury and thrombosis in hyperacute rejection.", sourceIds: [S.hyperacuteReview.id], category: "definition", certainty: "moderate", limitation: "One adequately licensed review supplies this narrow vascular mechanism. No claim that all acute rejection is antibody-mediated or that T-cell and antibody mechanisms cannot coexist.", population: "Adults discussing a documented historical donor-specific antibody-mediated graft injury." },
  ],
  concepts: [
    {
      id: "concept.immunology.ige-mast-cell-type-i", displayName: "Explain an IgE-mediated type I reaction",
      learningObjective: "Connect a documented IgE-mediated type I reaction to mast-cell activation rather than infer the mechanism from a rash alone.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [TYPE_I, HIVES_LIMIT, NON_IGE],
      variants: variants([
        { slug: "food-allergy-effector", complaint: "Allergy record question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside allergist's report after a resolved food reaction. The report confirms an IgE-mediated allergy. The patient is well today and asks how an antigen can produce such a rapid reaction in a previously sensitized person.", stem: "Which effector cell is central to this patient's documented IgE-mediated allergic mechanism?", correct: ["Sensitized mast cells", "Mast cells carrying the relevant IgE can be activated by antigen engagement."], wrong: [["Sensitized T lymphocytes", "The supplied type I effector mechanism is mast-cell-bound IgE rather than the type IV T-cell pathway."], ["Circulating B lymphocytes", "These are not the IgE-bearing mast-cell effector identified in the supplied mechanism."], ["Circulating neutrophils", "These are not the IgE-bearing mast-cell effector identified in the supplied mechanism."]], explanation: "The correct answer is “Sensitized mast cells.” The specialist-confirmed mechanism supplies the distinction; hives alone would not prove an IgE-mediated allergy.", claims: [TYPE_I, HIVES_LIMIT, TYPE_IV], ageYears: [26, 47] },
        { slug: "latex-type", complaint: "Glove allergy question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside allergy record that confirms an IgE-mediated reaction to latex proteins. The past episode has resolved. The patient asks whether this is the same immune category as a delayed allergic rash from glove-manufacturing chemicals.", stem: "Which hypersensitivity category describes this patient's confirmed IgE-mediated latex-protein reaction?", correct: ["Type I hypersensitivity", "The supplied IgE-mediated mechanism is type I."], wrong: [["Type II hypersensitivity", "The confirmed mechanism is the IgE pathway specified by type I."], ["Type III hypersensitivity", "The supplied IgE-mediated reaction does not fit this alternative category."], ["Type IV hypersensitivity", "Type IV describes T-cell-mediated allergic contact dermatitis rather than the supplied IgE reaction."]], explanation: "The correct answer is “Type I hypersensitivity.” Latex-protein IgE allergy and confirmed glove-chemical allergic contact dermatitis have different mechanisms; no exposure challenge is performed here.", claims: [TYPE_I, TYPE_IV], ageYears: [34, 58] },
        { slug: "antibody-class", complaint: "Allergy antibody question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, has a resolved, specialist-confirmed type I food-allergic reaction documented in an outside record. The clinic visit is for explanation of the biology, and the patient asks which antibody class is attached to the mast cells involved.", stem: "Which antibody class is central to the mast-cell mechanism in this patient's documented type I reaction?", correct: ["Immunoglobulin E", "IgE bound to sensitized mast cells participates in this mechanism."], wrong: [["Immunoglobulin A", "The supplied type I mast-cell mechanism is specifically IgE-mediated."], ["Immunoglobulin G", "This is not the antibody class specified by the documented type I mast-cell pathway."], ["Immunoglobulin M", "This is not the antibody class specified by the documented type I mast-cell pathway."]], explanation: "The correct answer is “Immunoglobulin E.” This question concerns the mechanism already established by the outside specialist, without assigning that mechanism to every food-associated symptom.", claims: [TYPE_I, HIVES_LIMIT], ageYears: [31, 61] },
        { slug: "mediator-release", complaint: "Reaction mechanism question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews a resolved allergic episode that an outside specialist has established was IgE-mediated. The patient sketches a mast cell and asks what happens when the relevant antigen engages antibody already attached to that cell.", stem: "Which process follows antigen engagement of mast-cell-bound IgE in this patient's established allergic mechanism?", correct: ["Mast-cell mediator release", "Engagement of sensitized mast-cell IgE can activate release of mediators."], wrong: [["Contact-sensitized T-cell response", "That is the distinct type IV allergic contact mechanism."], ["IgG-associated complement response", "That broad non-IgE pathway does not match the supplied mast-cell-bound IgE event."], ["IgM-associated complement response", "That broad non-IgE pathway does not match the supplied mast-cell-bound IgE event."]], explanation: "The correct answer is “Mast-cell mediator release.” The question asks how an established IgE pathway works; it does not direct treatment for an active reaction.", claims: [TYPE_I, TYPE_IV, NON_IGE], ageYears: [39, 65] },
      ]),
    },
    {
      id: "concept.immunology.t-cell-type-iv-contact", displayName: "Explain allergic contact dermatitis",
      learningObjective: "Recognize specialist-confirmed allergic contact dermatitis as T-cell-mediated type IV hypersensitivity and distinguish it from an IgE reaction.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [TYPE_IV, TYPE_I, NON_IGE],
      variants: variants([
        { slug: "adhesive-category", complaint: "Adhesive rash review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside dermatology report diagnosing allergic contact dermatitis from a surgical adhesive. The episode has resolved. The record distinguishes this delayed allergic reaction from an immediate IgE-mediated event and from simple irritant dermatitis.", stem: "Which hypersensitivity category describes this patient's confirmed allergic contact dermatitis?", correct: ["Type IV hypersensitivity", "Allergic contact dermatitis is a T-cell-mediated type IV reaction."], wrong: [["Type I hypersensitivity", "The case specifies allergic contact dermatitis rather than an IgE-mediated event."], ["Type II hypersensitivity", "This category does not match the supplied T-cell contact-allergy mechanism."], ["Type III hypersensitivity", "This category does not match the supplied T-cell contact-allergy mechanism."]], explanation: "The correct answer is “Type IV hypersensitivity.” The specialist's diagnosis supplies an allergic contact mechanism; delay alone would not prove that every rash is allergic.", claims: [TYPE_IV, TYPE_I], ageYears: [37, 67] },
        { slug: "glove-accelerator", complaint: "Glove rash question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside specialist's diagnosis of allergic contact dermatitis to a glove chemical accelerator. The report explicitly excludes a latex-protein IgE allergy. The patient is symptom-free and asks which immune cells account for the contact reaction.", stem: "Which immune effector best explains this patient's established glove-chemical allergic contact dermatitis?", correct: ["Sensitized T lymphocytes", "The supplied allergic contact mechanism is T-cell-mediated."], wrong: [["Sensitized mast cells", "That effector belongs to the distinct IgE pathway rather than this contact mechanism."], ["Circulating B lymphocytes", "The supplied contact-allergy effector is a sensitized T lymphocyte."], ["Circulating neutrophils", "The supplied contact-allergy effector is a sensitized T lymphocyte."]], explanation: "The correct answer is “Sensitized T lymphocytes.” Allergy to a glove chemical and IgE allergy to latex proteins are different established mechanisms.", claims: [TYPE_IV, TYPE_I], ageYears: [28, 54] },
        { slug: "nickel-cellular", complaint: "Jewelry rash review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings outside testing and clinical records confirming allergic contact dermatitis from nickel jewelry. The rash is no longer active. The patient asks whether the established contact allergy is mainly an antibody-on-mast-cell reaction or a cellular immune response.", stem: "Which mechanism best describes this patient's confirmed nickel allergic contact dermatitis?", correct: ["Sensitized T-cell response", "Confirmed allergic contact dermatitis uses a T-cell-mediated pathway."], wrong: [["Allergen-bound IgE mast-cell response", "That describes the distinct type I IgE pathway."], ["IgG-associated complement response", "That broad non-IgE antibody pathway does not match the supplied T-cell contact mechanism."], ["IgM-associated complement response", "That broad non-IgE antibody pathway does not match the supplied T-cell contact mechanism."]], explanation: "The correct answer is “Sensitized T-cell response.” Use the established allergic contact diagnosis rather than classify a rash by location alone.", claims: [TYPE_IV, TYPE_I, NON_IGE], ageYears: [32, 60] },
        { slug: "repeat-contact", complaint: "Contact allergy explanation", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, has a resolved rash from repeated contact with a product that an outside dermatologist has confirmed causes allergic contact dermatitis. The patient knows the skin was previously sensitized and asks which broad immune pathway is reactivated on contact.", stem: "Which immune pathway accounts for this patient's confirmed allergic contact reaction after prior sensitization?", correct: ["T-cell-mediated delayed hypersensitivity", "Sensitized T-cell responses are central to allergic contact dermatitis."], wrong: [["IgE-mediated immediate hypersensitivity", "That is the distinct mast-cell IgE pathway."], ["IgG-associated complement hypersensitivity", "That broad antibody pathway does not match the supplied T-cell contact mechanism."], ["IgM-associated complement hypersensitivity", "That broad antibody pathway does not match the supplied T-cell contact mechanism."]], explanation: "The correct answer is “T-cell-mediated delayed hypersensitivity.” This names type IV biology without assigning an exact reaction interval or prescribing a contact challenge.", claims: [TYPE_IV, TYPE_I, NON_IGE], ageYears: [45, 69] },
      ]),
    },
    {
      id: "concept.immunology.preformed-antibody-hyperacute-rejection", displayName: "Explain documented hyperacute graft rejection",
      learningObjective: "Identify pre-existing recipient donor-reactive antibodies and vascular injury as the mechanism in an outside-confirmed historical hyperacute allograft event.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [PREFORMED, VASCULAR, TCMR],
      variants: variants([
        { slug: "historical-kidney-event", complaint: "Transplant history question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is stable in clinic and asks about a remote outside kidney-transplant event. The transplant team established the historical diagnosis as hyperacute antibody-mediated rejection. Current graft care is managed by that team.", stem: "Which immune effector best explains this patient's established historical hyperacute antibody-mediated rejection?", correct: ["Preformed donor-specific antibodies", "Pre-existing recipient donor-reactive antibodies are the classic effector in the documented hyperacute mechanism."], wrong: [["Newly formed donor-specific antibodies", "New antibody generation after transplantation does not describe the classic preformed-antibody hyperacute mechanism."], ["Activated recipient T lymphocytes", "T-cell graft rejection is a distinct pathway and does not replace the established preformed-antibody explanation."], ["IgE-sensitized recipient mast cells", "The established graft mechanism is donor-reactive antibody vascular injury rather than mast-cell IgE allergy."]], explanation: "The correct answer is “Preformed donor-specific antibodies.” This explains the transplant team's established historical diagnosis; early graft dysfunction alone would not establish that mechanism.", claims: [PREFORMED, VASCULAR, TCMR, TYPE_I], ageYears: [41, 64] },
        { slug: "vascular-biopsy", complaint: "Graft biopsy explanation", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside transplant team's report of a resolved historical hyperacute rejection episode. It describes preformed donor-specific antibody binding, complement-associated graft vascular injury and thrombosis. There is no active transplant emergency today.", stem: "Which target best fits the vascular mechanism documented in this patient's hyperacute rejection report?", correct: ["Donor vascular endothelial cells", "Preformed donor-specific antibodies can bind graft endothelium and initiate vascular injury."], wrong: [["Recipient vascular endothelial cells", "The supplied report locates the injury in the donor graft vasculature."], ["Recipient epidermal keratinocytes", "The report identifies graft endothelium rather than recipient skin cells."], ["Recipient cutaneous mast cells", "The report identifies graft endothelial antibody injury rather than a skin mast-cell target."]], explanation: "The correct answer is “Donor vascular endothelial cells.” The documented antibody-associated vascular process explains this historical event; the clinic is reviewing a record, without performing transplantation or treatment.", claims: [PREFORMED, VASCULAR], ageYears: [48, 70] },
        { slug: "antibody-timing", complaint: "Old transplant report", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, has an outside-confirmed historical hyperacute renal-allograft rejection event. The pretransplant sample already contained the donor-specific antibodies implicated by the transplant team. The patient asks why antibody generation after surgery is not needed to explain that event.", stem: "Which antibody description best explains the supplied mechanism of this patient's historical hyperacute rejection?", correct: ["Donor-reactive antibodies present beforehand", "The record already establishes the relevant antibodies before transplantation."], wrong: [["Donor-reactive antibodies first made afterward", "This contradicts the documented pretransplant presence of the implicated antibodies."], ["Recipient-reactive donor antibodies present beforehand", "The documented antibodies came from the recipient and targeted donor antigens, rather than the reverse direction."], ["Recipient-reactive donor antibodies first made afterward", "Both direction and timing differ from the documented recipient preformed donor-specific antibodies."]], explanation: "The correct answer is “Donor-reactive antibodies present beforehand.” Pre-existing recipient sensitization is the relevant feature; no exact time cutoff or transplant-management rule is required.", claims: [PREFORMED], ageYears: [36, 59] },
        { slug: "injury-pathway", complaint: "Graft injury mechanism", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is well at a clinic record-review visit. A transplant report definitively attributes a prior hyperacute rejection episode to preformed donor-specific antibodies. The patient asks how those antibodies caused the vascular findings described in the report.", stem: "Which injury pathway best explains this patient's documented preformed-antibody hyperacute rejection?", correct: ["Antibody-associated complement vascular injury", "Antibody binding to graft endothelium can produce complement-associated vascular injury and thrombosis."], wrong: [["IgE-associated mast-cell mediator discharge", "The established graft vascular mechanism is distinct from type I IgE mast-cell activation."], ["T-cell-associated cellular graft rejection", "A T-cell pathway can cause graft rejection but does not replace this documented preformed-antibody vascular explanation."], ["New-antibody-associated injury after sensitization", "The supplied event is attributed to antibodies already present, rather than antibodies first generated after graft exposure."]], explanation: "The correct answer is “Antibody-associated complement vascular injury.” The supplied historical diagnosis scopes the teaching point; it does not classify every acute rejection episode or every early graft failure.", claims: [PREFORMED, VASCULAR, TCMR, TYPE_I], ageYears: [52, 73] },
      ]),
    },
  ],
});
