import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { REMAINING10_SOURCES as S } from "./source-catalog-remaining10";

const STAGE = "claim.gs028e.stage_extent";
const GRADE = "claim.gs028e.grade_morphology";
const DISTINCT = "claim.gs028e.grade_not_stage";
const LOSS = "claim.gs028e.suppressor_loss";
const RB1 = "claim.gs028e.rb1_biallelic";
const SCOPE = "claim.gs028e.two_hit_scoped";

export const ONCOLOGY_FAMILY = buildFamily({
  slug: "oncology", label: "Outside cancer-record counseling",
  sources: [S.nciStage, S.nciGrade, S.nlmRb1, S.nciRb1],
  claims: [
    { id: STAGE, statement: "Cancer stage describes the extent of disease, including the primary tumor and its spread, using the system appropriate to that cancer.", sourceIds: [S.nciStage.id], category: "definition", certainty: "high", limitation: "General official definition from one government source; systems differ by cancer. No stage number, treatment or universal prognosis is assigned from incomplete details.", population: "Adults reviewing cancer-specific staging records." },
    { id: GRADE, statement: "Tumor grade describes microscopic features such as differentiation and abnormal appearance, with criteria specific to the tumor type.", sourceIds: [S.nciGrade.id], category: "definition", certainty: "high", limitation: "General official definition from one government source. No universal numeric grading scheme or guaranteed clinical behavior is taught.", population: "Adults reviewing a pathologist's tumor-specific grading report." },
    { id: DISTINCT, statement: "Tumor grade and cancer stage describe different properties; microscopic grade alone does not establish anatomic spread, and an extent-of-disease finding alone does not establish grade.", sourceIds: [S.nciStage.id, S.nciGrade.id], category: "safety_boundary", certainty: "high", limitation: "Two official NCI pages corroborate the distinction but are not independent organizations. The questions do not deny that both properties may matter in a cancer-specific system.", population: "Adults comparing staging and pathology descriptions of cancer." },
    { id: LOSS, statement: "Functional RB1 protein helps restrain cell division; loss of its function removes a tumor-suppressive restraint rather than creating an activated growth-promoting protein.", sourceIds: [S.nlmRb1.id], category: "definition", certainty: "high", limitation: "Stable molecular mechanism from a government gene summary; not a general statement that all cancer-causing mutations act through loss of function.", population: "Adults discussing an outside tumor molecular report explicitly documenting RB1 loss." },
    { id: RB1, statement: "The classic RB1 biallelic-loss model involves inactivation or loss of both functioning RB1 copies in a tumor cell.", sourceIds: [S.nlmRb1.id, S.nciRb1.id], category: "definition", certainty: "high", limitation: "The authored report explicitly establishes loss of both alleles. A supplied adult tumor report is used for molecular discussion; retinoblastoma background sources are not used to create adult retinoblastoma care or inherited-syndrome diagnoses.", population: "Adults with a supplied tumor-cell report documenting biallelic RB1 loss." },
    { id: SCOPE, statement: "A classic RB1 two-hit explanation is scoped to the documented biallelic-loss mechanism and is not a universal claim that every tumor suppressor or every tumor requires two such events.", sourceIds: [S.nciRb1.id], category: "safety_boundary", certainty: "high", limitation: "The current PDQ summary recognizes alternate molecular pathways. No inherited FAP/Lynch objective, germline inference or universal rule is taught.", population: "Adults receiving explanation of an explicitly supplied RB1 biallelic tumor finding." },
  ],
  concepts: [
    {
      id: "concept.oncology.stage-versus-grade", displayName: "Separate cancer stage from tumor grade",
      learningObjective: "Distinguish cancer-specific anatomic extent from microscopic differentiation without treating either as a universal numeric scheme or prognosis.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [STAGE, GRADE, DISTINCT],
      variants: variants([
        { slug: "colon-spread-summary", complaint: "Cancer report question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside colon-cancer evaluation to clinic. One section summarizes primary-tumor extent, regional nodes and whether distant spread is present. A separate pathology section describes how the cells look under the microscope. The patient wants to label the extent-of-disease section correctly.", stem: "Which pairing correctly labels the extent-of-disease section and microscopic section in this patient's colon-cancer report?", correct: ["Extent: stage; microscopy: grade", "Stage describes extent, while grade describes microscopic features."], wrong: [["Extent: grade; microscopy: stage", "This reverses the two supplied descriptor meanings."], ["Extent: stage; microscopy: stage", "The cellular appearance section concerns grade rather than another extent assessment."], ["Extent: grade; microscopy: grade", "The extent section concerns stage rather than microscopic grade."]], explanation: "The correct answer is “Extent: stage; microscopy: grade.” Apply the relevant cancer-specific systems; this question does not assign a numeric stage or grade from a partial report.", claims: [STAGE, GRADE, DISTINCT], ageYears: [52, 70] },
        { slug: "breast-microscopy", complaint: "Pathology grade question", presentation: "{patientName}, a {patientAge}-year-old woman, reviews an outside breast-cancer pathology report. The pathologist describes the tumor's microscopic features and differentiation using the breast-specific grading approach. A separate staging assessment addresses the location and extent of disease.", stem: "Which descriptor represents the microscopic assessment in this patient's breast-cancer pathology report?", correct: ["Histologic tumor grade", "The supplied descriptor concerns microscopic features and differentiation."], wrong: [["Anatomic extent-of-disease stage", "The staging assessment addresses extent rather than the supplied microscopy."], ["Regional extent-of-disease stage", "Regional spread is an extent assessment rather than a histologic grade."], ["Distant extent-of-disease stage", "Distant spread belongs to anatomic staging rather than the supplied cellular assessment."]], explanation: "The correct answer is “Histologic tumor grade.” Grade and stage describe different properties, even when both are relevant to an individual cancer's assessment.", claims: [GRADE, STAGE, DISTINCT], ageYears: [44, 63], sexLabels: ["Female"] },
        { slug: "grade-means-metastatic", complaint: "Grade wording concern", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside sarcoma pathology report describing poor differentiation. The extent-of-disease evaluation is still being completed. The patient has assumed that an abnormal microscopic appearance automatically proves distant metastasis.", stem: "Which interpretation correctly separates grade from stage in this patient's outside sarcoma report?", correct: ["Microscopic grade reported; anatomic extent unresolved", "A microscopic descriptor does not itself establish anatomic spread."], wrong: [["Microscopic grade reported; distant spread established", "Microscopic grade cannot substitute for the cancer-specific extent assessment."], ["Microscopic grade reported; localized extent established", "Microscopic grade alone does not establish localization or exclude spread."], ["Microscopic grade unresolved; anatomic extent established", "The supplied report establishes a microscopic finding, while the extent evaluation remains incomplete."]], explanation: "The correct answer is “Microscopic grade reported; anatomic extent unresolved.” The outside report supplies a microscopic property, without enough information to assign the patient's anatomic extent or prognosis.", claims: [GRADE, STAGE, DISTINCT], ageYears: [36, 58] },
        { slug: "node-versus-cells", complaint: "Two report sections", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside cancer workup. One section describes regional lymph-node involvement, while another describes the primary tumor's differentiation under the microscope. The patient asks which of these belongs to the extent-of-disease assessment rather than the cellular grading assessment.", stem: "Which finding in this patient's report primarily informs anatomic stage rather than microscopic grade?", correct: ["Extent of regional lymph-node involvement", "Regional spread is an extent-of-disease finding."], wrong: [["Degree of resemblance to normal tissue", "Cellular differentiation belongs to microscopic grading."], ["Degree of abnormal cellular appearance", "Microscopic abnormality belongs to the tumor-grade assessment."], ["Differentiation described by the pathologist", "The supplied differentiation finding describes grade rather than extent."]], explanation: "The correct answer is “Extent of regional lymph-node involvement.” The cancer-specific staging system determines how that finding is used; no universal stage number follows from the phrase alone.", claims: [STAGE, GRADE, DISTINCT], ageYears: [49, 72] },
      ]),
    },
    {
      id: "concept.oncology.rb1-biallelic-tumor-suppressor-loss", displayName: "Explain classic biallelic RB1 loss",
      learningObjective: "Explain an explicitly documented loss of both functioning RB1 alleles as a classic tumor-suppressor loss mechanism without generalizing it to every gene or inferring inherited disease.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [LOSS, RB1, SCOPE],
      variants: variants([
        { slug: "one-deleted-one-inactive", complaint: "Tumor gene explanation", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside bladder-tumor molecular report. It explicitly shows deletion of one RB1 allele and an inactivating change in the remaining allele, with neither copy providing normal function. The oncology team has not identified this as an inherited syndrome.", stem: "Which mechanism best explains the supplied loss of both functioning RB1 alleles in this patient's tumor?", correct: ["Loss of tumor-suppressive growth restraint", "The supplied biallelic RB1 loss removes a functional restraint on cell division."], wrong: [["Gain of growth-promoting RB1 protein activity", "The report describes inactivation, not a newly activated RB1 protein."], ["Preservation of normal RB1 growth-restraint activity", "Neither supplied allele provides the normal function."], ["Amplification of normally functioning RB1 alleles", "The report describes loss and inactivation rather than extra functioning copies."]], explanation: "The correct answer is “Loss of tumor-suppressive growth restraint.” This is the classic biallelic RB1 loss pattern documented in the tumor; it does not diagnose a germline syndrome.", claims: [LOSS, RB1, SCOPE], ageYears: [55, 73] },
        { slug: "both-copies-deleted", complaint: "Molecular report review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside adult lung-tumor report documenting loss of both RB1 gene copies in the tumor cells. The patient calls RB1 a 'stuck accelerator,' but the report states that normal RB1 function is absent rather than overactive.", stem: "Which description best matches this patient's explicitly documented RB1 biallelic loss?", correct: ["A tumor-suppressor restraint has been lost", "Normal RB1 helps restrain cell division, and the supplied tumor lacks that function."], wrong: [["A normal RB1 restraint has been duplicated", "Duplication of functioning copies is not what the report shows."], ["A normal RB1 restraint remains fully intact", "The record explicitly establishes loss of both functional copies."], ["An RB1 growth accelerator has become overactive", "The supplied mechanism is loss of restraint rather than RB1 activation."]], explanation: "The correct answer is “A tumor-suppressor restraint has been lost.” The accelerator analogy does not fit the reported loss-of-function mechanism; this question does not generalize the model to all tumor genes.", claims: [LOSS, RB1, SCOPE], ageYears: [48, 69] },
        { slug: "two-hit-description", complaint: "Two-hit term question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, has an outside tumor-cell report that explicitly documents inactivation of both RB1 alleles. The oncologist used the phrase 'classic two-hit loss' for this molecular finding, and the patient asks which part of the report supports that description.", stem: "Which reported finding supports a classic biallelic RB1 loss model in this patient's tumor cells?", correct: ["Both RB1 alleles lack normal function", "The supplied report establishes loss of both functioning copies."], wrong: [["Both RB1 alleles retain normal function", "Preserved function would not establish the supplied biallelic-loss mechanism."], ["Both RB1 alleles show increased normal activity", "Increased activity does not describe the inactivating changes in this report."], ["Both RB1 alleles are normally amplified copies", "Extra normally functioning copies do not establish the documented loss pattern."]], explanation: "The correct answer is “Both RB1 alleles lack normal function.” The two-hit description is scoped to this explicit RB1 finding, without claiming that every tumor suppressor or cancer follows the same rule.", claims: [LOSS, RB1, SCOPE], ageYears: [40, 62] },
        { slug: "functional-consequence", complaint: "RB1 function question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside adult tumor report recording a deletion affecting one RB1 allele and an inactivating change affecting the other. During the clinic explanation, the patient asks what RB1 does when it is functioning normally.", stem: "Which normal biological role of functional RB1 is relevant to explaining this patient's molecular report?", correct: ["Restrain cell division", "Functional RB1 contributes a tumor-suppressive restraint on division."], wrong: [["Accelerate cell division", "The verified normal role is restraint rather than acceleration of division."], ["Amplify cell division", "The verified normal role is restraint rather than amplification of division."], ["Permit unrestricted cell division", "The verified normal role is restraint rather than unrestricted division."]], explanation: "The correct answer is “Restrain cell division.” Functional RB1 helps restrain cell division. This explains its normal biological role without selecting cancer treatment or identifying inherited risk.", claims: [LOSS], ageYears: [51, 75] },
      ]),
    },
  ],
});
