import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { REMAINING10_SOURCES as S } from "./source-catalog-remaining10";

const CLEAN = "claim.gs028e.clean_wound";
const CONTROLLED = "claim.gs028e.clean_contaminated";
const SPILLAGE = "claim.gs028e.contaminated";
const BREACH = "claim.gs028e.contaminated_aseptic_breach";
const DIRTY = "claim.gs028e.dirty_infected";
const CLASS_CLAIMS = [CLEAN, CONTROLLED, SPILLAGE, BREACH, DIRTY];

export const OPERATIVE_INFECTION_FAMILY = buildFamily({
  slug: "operative-infection", label: "Outside operative wound-class review",
  sources: [S.ukhsaWoundClass],
  claims: [
    { id: CLEAN, statement: "An uninfected operative wound without inflammation, relevant tract entry or a break in aseptic technique, and closed primarily, fits the clean class.", sourceIds: [S.ukhsaWoundClass.id], category: "definition", certainty: "high", limitation: "One official surveillance definition source. The case explicitly supplies the operative circumstances; current skin appearance alone does not determine the original class.", population: "Adults reviewing an outside operation's recorded contamination conditions." },
    { id: CONTROLLED, statement: "Controlled entry into an alimentary, respiratory, genital or urinary tract without unusual contamination, infection or a major aseptic breach fits the clean-contaminated class.", sourceIds: [S.ukhsaWoundClass.id], category: "definition", certainty: "high", limitation: "Single official surveillance source. No procedure name alone, infection risk percentage or antibiotic regimen is inferred.", population: "Adults reviewing a documented controlled tract-entry operation." },
    { id: SPILLAGE, statement: "Gross gastrointestinal spillage during an operation without established infection or a pre-existing perforated viscus fits the contaminated class.", sourceIds: [S.ukhsaWoundClass.id], category: "definition", certainty: "high", limitation: "The authored scenario explicitly distinguishes an intraoperative spill from pre-existing perforation or purulent infection; this is not an antibiotic-selection rule.", population: "Adults reviewing an operation with documented gross gastrointestinal spillage." },
    { id: BREACH, statement: "A major break in aseptic technique is a criterion for the contaminated operative wound class.", sourceIds: [S.ukhsaWoundClass.id], category: "definition", certainty: "high", limitation: "Narrow comparator criterion from the same official surveillance source, not a postoperative treatment or infection-probability rule.", population: "Adults reviewing documented operative aseptic conditions." },
    { id: DIRTY, statement: "An operation encountering established purulent infection or a pre-existing perforated viscus fits the dirty/infected class.", sourceIds: [S.ukhsaWoundClass.id], category: "definition", certainty: "high", limitation: "Single official surveillance definition; no copied classification table, traumatic-wound time cutoff, postoperative probability or treatment algorithm is used.", population: "Adults reviewing a prior operation with documented purulence or a perforated viscus." },
  ],
  concepts: [
    {
      id: "concept.infection.operative-wound-classification", displayName: "Classify operative contamination conditions",
      learningObjective: "Distinguish clean, clean-contaminated, contaminated and dirty/infected operative wound classes using the described tract entry, spillage and pre-existing infection.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: CLASS_CLAIMS,
      variants: variants([
        { slug: "clean-soft-tissue", complaint: "Wound class question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is well in clinic while reviewing an outside removal of an uninfected soft-tissue mass. The operative record documents no inflammation, no entry into an alimentary, respiratory, urinary or genital tract, no aseptic breach and primary skin closure.", stem: "Which operative wound class fits the conditions documented for this patient's outside mass removal?", correct: ["Clean", "The supplied uninfected operation has no relevant tract entry or aseptic breach and was closed primarily."], wrong: [["Clean-contaminated", "This class requires controlled relevant tract entry, which the record excludes."], ["Contaminated", "No gross spillage or major aseptic breach is supplied."], ["Dirty/infected", "The record excludes established infection and a perforated viscus."]], explanation: "The correct answer is “Clean.” Classify the conditions at the operation rather than the patient's present scar; the class does not automatically select an antibiotic prescription.", claims: CLASS_CLAIMS, ageYears: [33, 57] },
        { slug: "controlled-bowel-entry", complaint: "Surgical report review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside elective bowel-operation report to clinic. It records deliberate, controlled entry into the bowel, no unusual contamination or gross spillage, no pre-existing infection or perforation and no major aseptic breach. The patient has no current postoperative concern.", stem: "Which wound class fits this patient's controlled bowel entry without unusual contamination or infection?", correct: ["Clean-contaminated wound", "Controlled alimentary-tract entry with the supplied exclusions fits this class."], wrong: [["Clean wound", "The bowel was entered, so the described operation does not meet the clean definition."], ["Contaminated wound", "The supplied record specifically excludes the gross spillage or breach supporting this alternative."], ["Dirty or infected surgical wound", "No pre-existing perforation or established purulent infection is described."]], explanation: "The correct answer is “Clean-contaminated wound.” Controlled tract entry is the relevant distinction; a bowel procedure's name alone would not supply all the classification details.", claims: CLASS_CLAIMS, ageYears: [45, 68] },
        { slug: "unexpected-gross-spill", complaint: "Contamination wording question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside elective bowel-surgery record. During the operation there was gross intestinal-content spillage. The surgeon explicitly documents that no perforated viscus or infection existed before the operation and no purulence was encountered. The patient is stable at today's explanation visit.", stem: "Which operative wound class fits this patient's gross intraoperative bowel spillage without pre-existing perforation or infection?", correct: ["Contaminated", "Gross gastrointestinal spillage supplies the contamination criterion; the record excludes pre-existing dirty/infected conditions."], wrong: [["Clean", "The supplied tract entry and gross spill do not meet the clean criteria."], ["Clean-contaminated", "Gross spillage exceeds the controlled entry without unusual contamination described by this class."], ["Dirty/infected", "The record explicitly excludes the established infection or pre-existing perforation that would support this alternative."]], explanation: "The correct answer is “Contaminated.” The case distinguishes a spill occurring during surgery from a perforated or infected viscus already present; no antibiotic regimen follows from this question alone.", claims: CLASS_CLAIMS, ageYears: [41, 65] },
        { slug: "purulent-perforation", complaint: "Old operation question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is well during a clinic review of a completed outside emergency operation. The old report describes an appendix already perforated before surgery and established purulent material in the operative field. The patient asks which wound-class term refers to those recorded conditions.", stem: "Which operative wound class fits this patient's documented pre-existing perforation and purulent infection?", correct: ["Dirty/infected", "Established purulence and a viscus perforated before surgery fit the dirty/infected class."], wrong: [["Clean", "The established infection and perforation exclude the clean category."], ["Clean-contaminated", "The report describes established infection rather than controlled tract entry without it."], ["Contaminated", "The record goes beyond spillage alone by documenting pre-existing perforation and purulence."]], explanation: "The correct answer is “Dirty/infected.” This class describes the old operative findings, without implying a current infection or a new treatment instruction at today's stable visit.", claims: CLASS_CLAIMS, ageYears: [27, 53] },
      ]),
    },
  ],
});
