import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { FIRST10_SOURCES as S } from "./source-catalog-first10";

const DKA = "claim.gs028e.sglt2.ketoacidosis-without-marked-hyperglycemia";
const TRIGGER = "claim.gs028e.sglt2.ketoacidosis-precipitating-context";
const ESCALATE = "claim.gs028e.sglt2.suspected-ketoacidosis-urgent-care";
const NALOXONE = "claim.gs028e.naloxone.competitive-opioid-antagonism";
const SUPPORT = "claim.gs028e.naloxone.emergency-support-still-required";

export const PHARMACOLOGY_FAMILY = buildFamily({
  slug: "pharmacology", label: "Medication effects and mechanisms",
  sources: [S.empagliflozinFda, S.empagliflozinCurrent, S.ertugliflozinFda, S.mhraDka, S.naloxoneFda, S.naloxoneSafety],
  claims: [
    { id: DKA, statement: "SGLT2-inhibitor exposure can be associated with diabetic ketoacidosis despite glucose that is not markedly elevated; supplied ketone excess and metabolic acidosis support recognition, whereas glucose alone cannot exclude it.", sourceIds: [S.empagliflozinFda.id, S.empagliflozinCurrent.id, S.ertugliflozinFda.id, S.mhraDka.id], category: "evaluation", certainty: "high", limitation: "Medication exposure is a clinically important association, not proof that every acidosis is drug-caused. No glucose, ketone, pH or bicarbonate cutoff is invented.", population: "Adults with diabetes taking an SGLT2 inhibitor and compatible ketone/acidosis findings." },
    { id: TRIGGER, statement: "Surgery, reduced caloric intake, acute illness, and inadequate insulin are recognized precipitating contexts for ketoacidosis during SGLT2-inhibitor therapy.", sourceIds: [S.empagliflozinFda.id, S.ertugliflozinFda.id, S.mhraDka.id], category: "presentation", certainty: "high", limitation: "Context raises concern but does not diagnose ketoacidosis without supporting clinical and laboratory evidence; no risk probability is authored.", population: "Adults taking an SGLT2 inhibitor around illness, fasting or surgery." },
    { id: ESCALATE, statement: "Suspected SGLT2-associated ketoacidosis warrants interruption of the implicated drug and immediate medical assessment; a reassuring glucose value must not delay urgent care when ketones and acidosis are present.", sourceIds: [S.empagliflozinFda.id, S.empagliflozinCurrent.id, S.ertugliflozinFda.id, S.mhraDka.id], category: "disposition", certainty: "high", limitation: "The clinic escalates rather than administering a DKA treatment protocol; no insulin, fluid, electrolyte, restart dose, or monitoring schedule is authored.", population: "Adults with suspected current SGLT2-associated ketoacidosis." },
    { id: NALOXONE, statement: "Naloxone reverses opioid effects by competing at opioid receptor sites as an antagonist rather than stimulating those receptors or chemically destroying the opioid.", sourceIds: [S.naloxoneFda.id, S.naloxoneSafety.id], category: "definition", certainty: "high", limitation: "This is a receptor-mechanism objective; no dose, formulation superiority or response guarantee is supplied. The 2023 label is not asserted to be the latest product label.", population: "Adults discussing documented or planned opioid-overdose reversal." },
    { id: SUPPORT, statement: "Naloxone is a temporary reversal intervention and does not replace emergency medical assistance, airway or respiratory support when needed; opioid-related depression can recur after initial improvement.", sourceIds: [S.naloxoneFda.id, S.naloxoneSafety.id], category: "safety_boundary", certainty: "high", limitation: "Two FDA documents from one authority corroborate the boundary; this clinic does not conduct an opioid challenge or simulate advanced airway care.", population: "Adults with known or suspected opioid toxicity or counseling about naloxone." },
  ],
  concepts: [
    {
      id: "concept.sglt2-inhibitor.euglycemic-ketoacidosis-adverse-effect", displayName: "Recognize SGLT2-associated ketoacidosis",
      learningObjective: "Link SGLT2 exposure to ketoacidosis when compatible ketone/acidosis evidence is supplied despite nonmarked glucose elevation.", stage: 0, educationalTier: 1, conceptType: "complication", evidenceClaimIds: [DKA, TRIGGER, ESCALATE],
      variants: variants([
        { slug: "vomiting-empagliflozin", complaint: "Vomiting and weakness", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, takes empagliflozin for type 2 diabetes and arrives after poor intake with vomiting and deep breathing. Urgent outside results already show ketone excess, low bicarbonate, an anion-gap acidosis, and near-normal glucose.", stem: "Which medication-associated complication best explains this patient's supplied findings?", correct: ["SGLT2-associated ketoacidosis", "Ketone excess and metabolic acidosis remain concerning despite near-normal glucose."], wrong: [["Insulin-associated hypoglycemia", "The provided glucose is not low; this label also omits the supplied ketone/acidosis evidence."], ["Isolated SGLT2-related glucosuria", "This label omits the documented metabolic acidosis and ketone excess."], ["Hyperosmolar hyperglycemic state", "This label does not capture the supplied ketone-associated acidosis being linked to SGLT2 exposure."]], explanation: "The correct answer is “SGLT2-associated ketoacidosis.” Stop the implicated drug and arrange immediate emergency assessment; do not wait for glucose to become very high or create a clinic test delay.", claims: [DKA, TRIGGER, ESCALATE], acuity: "urgent", ageYears: [46, 67] },
        { slug: "postop-record", complaint: "Medication event review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is well after hospital treatment following outside hernia surgery. The event record lists continued empagliflozin, reduced intake, elevated blood ketones, metabolic acidosis, and only modest glucose elevation.", stem: "Which adverse-effect concern should be highlighted in this patient's medication history?", correct: ["SGLT2-associated ketoacidosis", "The drug exposure and ketone/acidosis pattern fit this recognized adverse-effect concern."], wrong: [["SGLT2-associated isolated glucose loss", "That description omits the acid-base and ketone findings that made the event clinically serious."], ["Insulin-associated hypoglycemic episode", "The documented glucose was not low; this label omits the supplied acidosis and ketone excess."], ["Hyperosmolar hyperglycemic episode", "The supplied record identifies a ketone-associated acidosis and SGLT2 exposure rather than this alternative label."]], explanation: "The correct answer is “SGLT2-associated ketoacidosis.” Document the supplied hospital event and coordinate future medication planning; the clinic is reviewing completed care, not treating active acidosis.", claims: [DKA, TRIGGER], ageYears: [51, 71] },
        { slug: "ertugliflozin-illness", complaint: "Nausea with breathlessness", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, takes ertugliflozin and metformin for type 2 diabetes. During an acute illness, outside results show elevated ketones and anion-gap metabolic acidosis, normal lactate, and glucose that is not markedly elevated.", stem: "Which medication-associated complication best fits this patient's laboratory pattern?", correct: ["SGLT2-associated ketoacidosis", "The supplied ketone excess with acidosis fits the SGLT2 warning even without marked glucose elevation."], wrong: [["Metformin-associated lactic acidosis", "The supplied lactate is within the laboratory reference range, while ketones are elevated."], ["Insulin-associated hypoglycemia", "The supplied glucose is not low, while the record explicitly identifies ketone excess and acidosis."], ["Isolated SGLT2-related dehydration", "This label omits the documented ketone excess and metabolic acidosis."]], explanation: "The correct answer is “SGLT2-associated ketoacidosis.” The implicated SGLT2 drug should be interrupted and the patient sent for immediate medical assessment; medication association does not replace evaluation for other contributors.", claims: [DKA, TRIGGER, ESCALATE], acuity: "urgent", ageYears: [43, 65] },
        { slug: "glucose-led-missed", complaint: "Hospital report question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings a resolved outside metabolic event for review. While taking empagliflozin during restricted intake, the patient had elevated blood ketones and documented anion-gap acidosis but near-normal glucose. The patient believes that glucose result ruled out the drug's ketoacidosis warning.", stem: "What does this patient's near-normal glucose mean when the supplied ketone and acidosis findings are present?", correct: ["Does not exclude ketoacidosis", "Glucose alone cannot exclude the compatible ketone/acidosis syndrome."], wrong: [["Excludes SGLT2-associated ketoacidosis", "This treats the glucose value as an exclusion test despite the supplied ketone/acidosis evidence."], ["Establishes a harmless medication effect", "Reassuring glucose does not make the supplied acidosis and ketone excess harmless."], ["Proves the medication caused the episode", "Glucose alone does not establish causation; the drug association still requires clinical evaluation."]], explanation: "The correct answer is “Does not exclude ketoacidosis.” Interpret the supplied ketone and acid-base evidence; a near-normal glucose value neither excludes the complication nor proves its cause.", claims: [DKA, TRIGGER], ageYears: [37, 62] },
      ]),
    },
    {
      id: "concept.naloxone.competitive-opioid-antagonist-mechanism", displayName: "Explain naloxone's receptor action",
      learningObjective: "Explain competitive opioid receptor antagonism in patient-specific naloxone counseling or review of completed emergency care.", stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [NALOXONE, SUPPORT],
      variants: variants([
        { slug: "postop-rescue-record", complaint: "Rescue medicine question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews a completed outside postoperative event: opioid-related slow breathing improved after naloxone while the hospital team provided emergency support. The patient asks how the rescue medicine worked.", stem: "Which receptor action explains naloxone's effect in this patient's recorded event?", correct: ["Competitive opioid receptor blockade", "Naloxone opposes opioid effects by competing at their receptor sites."], wrong: [["Additional opioid receptor stimulation", "Stimulating opioid receptors would not describe naloxone's antagonistic action."], ["Benzodiazepine receptor blockade", "This does not match the opioid receptor mechanism of naloxone."], ["Opioid receptor synthesis inhibition", "Naloxone acts at existing receptor sites rather than blocking production of new receptors."]], explanation: "The correct answer is “Competitive opioid receptor blockade.” Naloxone temporarily opposes opioid effects; emergency respiratory support and observation still matter after an initial response.", claims: [NALOXONE, SUPPORT], ageYears: [40, 63] },
        { slug: "kit-is-not-analgesic", complaint: "Naloxone kit counseling", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is reviewing an outside postoperative medication plan containing an opioid analgesic and a naloxone rescue kit. The patient thinks both medicines activate the same receptors to relieve pain.", stem: "Which receptor action distinguishes the patient's naloxone from the opioid analgesic?", correct: ["Antagonism at opioid receptors", "Naloxone blocks opioid effects rather than providing opioid agonist analgesia."], wrong: [["Agonism at opioid receptors", "That describes opioid-like receptor stimulation, not naloxone's receptor action."], ["Agonism at benzodiazepine receptors", "Naloxone does not reverse opioids through that receptor system."], ["Inhibition of opioid receptor formation", "Its reversal effect comes from competition at receptor sites rather than suppression of receptor formation."]], explanation: "The correct answer is “Antagonism at opioid receptors.” The kit is a rescue intervention, not a second opioid pain medicine, and suspected overdose still requires emergency help.", claims: [NALOXONE, SUPPORT], ageYears: [34, 59] },
        { slug: "opioid-not-destroyed", complaint: "Reversal medicine review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is well after an outside opioid-toxicity episode treated with naloxone. The patient asks whether naloxone permanently destroyed the opioid, making further observation unnecessary.", stem: "Which mechanism correctly explains this patient's naloxone response?", correct: ["Competition at opioid receptor sites", "Naloxone competes with opioids at receptors rather than destroying the opioid."], wrong: [["Chemical destruction of circulating opioid", "The receptor antagonist mechanism does not eliminate the drug chemically."], ["Permanent removal of opioid receptors", "Naloxone does not permanently remove the patient's receptor sites."], ["Stimulation of additional opioid receptors", "Additional receptor stimulation is the opposite of opioid antagonism."]], explanation: "The correct answer is “Competition at opioid receptor sites.” Because reversal can be temporary, an initial improvement does not remove the need for emergency assessment and respiratory support when indicated.", claims: [NALOXONE, SUPPORT], ageYears: [47, 70] },
        { slug: "opioid-specific-target", complaint: "Rescue drug target", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is well at clinic review of an outside medication plan containing an opioid, a benzodiazepine and a naloxone kit. The patient thinks the kit blocks a single receptor shared by both prescribed medicines and asks which receptor action actually explains opioid reversal.", stem: "Which receptor action explains the opioid-specific role of naloxone in this patient's medication plan?", correct: ["Blockade at opioid receptors", "Naloxone competitively opposes opioid effects at opioid receptor sites."], wrong: [["Blockade at benzodiazepine receptors", "That target does not describe naloxone's opioid receptor mechanism."], ["Stimulation at opioid receptors", "Stimulation is the opposite of the opioid antagonism responsible for reversal."], ["Stimulation at benzodiazepine receptors", "That target and action do not describe naloxone's opioid receptor mechanism."]], explanation: "The correct answer is “Blockade at opioid receptors.” Naloxone's competitive target explains its opioid reversal role; the presence of a kit does not replace emergency help or guarantee reversal of every medication effect.", claims: [NALOXONE, SUPPORT], ageYears: [38, 66] },
      ]),
    },
  ],
});
