import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { FIRST10_SOURCES as S } from "./source-catalog-first10";

const EMPA = "claim.gs028e.sglt2.empagliflozin-preoperative-interruption";
const ERTU = "claim.gs028e.sglt2.ertugliflozin-preoperative-interruption";
const RESTART = "claim.gs028e.sglt2.postoperative-restart-conditions";

export const PREOPERATIVE_FAMILY = buildFamily({
  slug: "preoperative-sglt2", label: "Drug-specific perioperative planning",
  sources: [S.empagliflozinFda, S.empagliflozinCurrent, S.ertugliflozinFda],
  claims: [
    { id: EMPA, statement: "U.S. empagliflozin labeling advises withholding the drug for at least three days when possible before surgery or a procedure associated with prolonged fasting.", sourceIds: [S.empagliflozinFda.id, S.empagliflozinCurrent.id], category: "management", certainty: "high", limitation: "Exact interval is drug-specific and based on official U.S. labeling; the second source is a manufacturer-label cross-check, not an independent guideline. Emergency surgery and individualized specialist decisions are outside the scored scenario.", population: "Adults taking empagliflozin before elective surgery with sufficient planning time." },
    { id: ERTU, statement: "U.S. ertugliflozin labeling advises withholding the drug for at least four days when possible before surgery or a procedure associated with prolonged fasting.", sourceIds: [S.ertugliflozinFda.id], category: "management", certainty: "high", limitation: "Single current drug-specific FDA-approved label; the four-day interval is not generalized to every SGLT2 inhibitor. Emergency surgery decisions are outside this objective.", population: "Adults taking ertugliflozin before elective surgery with sufficient planning time." },
    { id: RESTART, statement: "Empagliflozin and ertugliflozin labels condition postoperative resumption on clinical stability and return of oral intake rather than a fixed postoperative clock alone.", sourceIds: [S.empagliflozinFda.id, S.empagliflozinCurrent.id, S.ertugliflozinFda.id], category: "safety_boundary", certainty: "high", limitation: "Resumption remains an individualized treating-team decision; these cases do not authorize restart during active ketoacidosis or prescribe a fixed restart time.", population: "Adults discussing a perioperative empagliflozin or ertugliflozin plan." },
  ],
  concepts: [{
    id: "concept.perioperative-sglt2.drug-specific-interruption", displayName: "Plan drug-specific SGLT2 interruption",
    learningObjective: "Use drug-specific U.S. labeling to plan elective preoperative interruption of empagliflozin versus ertugliflozin without assigning every SGLT2 inhibitor one interval.",
    stage: 0, educationalTier: 0, conceptType: "management", evidenceClaimIds: [EMPA, ERTU, RESTART],
    variants: variants([
      { slug: "empagliflozin-hernia", complaint: "Preop medication planning", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, takes empagliflozin for type 2 diabetes and is preparing well in advance for elective hernia repair at an outside hospital. The clinic is coordinating the U.S. label-based medication plan.", stem: "Which minimum preoperative interruption should be planned for this patient's empagliflozin?", correct: ["At least 3 days before surgery", "The empagliflozin label specifies at least three days when possible."], wrong: [["Starting the morning of surgery", "A morning-only omission does not meet the label's preoperative interval."], ["At least 1 day before surgery", "One day does not meet the empagliflozin label's stated minimum."], ["At least 2 days before surgery", "Two days do not meet empagliflozin's label-based minimum interruption."]], explanation: "The correct answer is “At least 3 days before surgery.” Coordinate the empagliflozin interruption with the treating team when possible; do not assign that interval automatically to ertugliflozin.", claims: [EMPA, ERTU], ageYears: [45, 68] },
      { slug: "ertugliflozin-colon", complaint: "Surgery drug review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, takes ertugliflozin and has ample planning time before an elective outside colon operation with fasting. The patient asks for the U.S. label-based minimum interruption for this specific drug.", stem: "Which minimum preoperative interruption should be planned for this patient's ertugliflozin?", correct: ["At least four days beforehand", "The ertugliflozin label specifies at least four days when possible."], wrong: [["From the operative morning", "That omits the longer preoperative interval specified for ertugliflozin."], ["At least two days beforehand", "Two days do not meet the drug-specific four-day minimum."], ["At least three days beforehand", "The three-day empagliflozin interval must not be substituted for ertugliflozin's label interval."]], explanation: "The correct answer is “At least four days beforehand.” This is ertugliflozin's drug-specific label interval when possible, not a universal rule for every diabetes medicine.", claims: [ERTU, EMPA], ageYears: [52, 73] },
      { slug: "short-empa-plan", complaint: "Medication calendar check", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, takes empagliflozin before an elective outside abdominal operation scheduled far enough ahead for planning. A draft calendar omits only the day-before and surgery-day doses, and the team asks for a correction.", stem: "Which replacement instruction meets this patient's U.S. label-based empagliflozin interruption plan?", correct: ["Withhold at least 3 days before surgery", "The supplied draft is shorter than empagliflozin's stated preoperative minimum."], wrong: [["Withhold on the morning of surgery", "A surgery-morning omission remains shorter than the label-based plan."], ["Withhold at least 1 day before surgery", "This repeats the inadequately short interruption in the draft."], ["Withhold at least 2 days before surgery", "Two days remain shorter than the label-based minimum for this drug."]], explanation: "The correct answer is “Withhold at least 3 days before surgery.” Confirm a drug-specific calendar with the treating team; this scenario does not address an urgent operation that cannot wait.", claims: [EMPA], ageYears: [41, 65] },
      { slug: "drug-switch-calendar", complaint: "Changed medication calendar", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, now takes ertugliflozin after previously taking empagliflozin. Before a planned outside elective operation with ample preparation time, the patient asks why the old drug's minimum interruption calendar needs to change.", stem: "Which pair of U.S. label-based minimum intervals explains the calendar change for this patient's drug switch?", correct: ["Empagliflozin: three days; ertugliflozin: four days", "The drugs have different minimum preoperative interruption intervals when possible."], wrong: [["Empagliflozin: three days; ertugliflozin: three days", "This substitutes empagliflozin's shorter interval for ertugliflozin."], ["Empagliflozin: four days; ertugliflozin: three days", "This reverses the two drug-specific minimum intervals."], ["Empagliflozin: four days; ertugliflozin: four days", "Four days may exceed empagliflozin's minimum, but it is not the drug-specific minimum pair requested."]], explanation: "The correct answer is “Empagliflozin: three days; ertugliflozin: four days.” Plan at least the applicable interval when possible. The treating team also confirms resumption only when clinically stable and oral intake has returned, rather than using a postoperative clock alone.", claims: [EMPA, ERTU, RESTART], ageYears: [49, 70] },
    ]),
  }],
});
