import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { FIRST10_SOURCES as S } from "./source-catalog-first10";

const CT = "claim.gs028e.imaging.ct-ionizing-xrays";
const US = "claim.gs028e.imaging.ultrasound-acoustic-nonionizing";
const MRI = "claim.gs028e.imaging.mri-magnetic-rf-nonionizing";
const DEVICE = "claim.gs028e.mri.device-specific-conditions";
const COCHLEAR = "claim.gs028e.mri.cochlear-specific-instructions";
const WARMTH = "claim.gs028e.contrast.transient-warmth-physiologic";
const HIVES = "claim.gs028e.contrast.urticaria-allergic-like";
const LEAK = "claim.gs028e.contrast.extravasation-local-tissue-event";
const DELAYED = "claim.gs028e.contrast.delayed-cutaneous-event";

export const RADIOLOGY_FAMILY = buildFamily({
  slug: "radiology", label: "Imaging safety counseling",
  sources: [S.fdaXray, S.fdaUltrasound, S.fdaMri, S.fdaMriPatient, S.fdaCochlear, S.acrContrast],
  claims: [
    { id: CT, statement: "CT produces images using ionizing X-rays; omitting injected contrast does not remove the X-ray exposure inherent to CT.", sourceIds: [S.fdaXray.id], category: "definition", certainty: "high", limitation: "A physical modality distinction only; no patient-specific radiation dose, organ-imaging preference, or numeric risk estimate is supplied.", population: "Adults discussing medically indicated CT imaging." },
    { id: US, statement: "Diagnostic ultrasound produces images using sound waves rather than ionizing radiation.", sourceIds: [S.fdaUltrasound.id], category: "definition", certainty: "high", limitation: "Nonionizing does not establish that ultrasound is the correct examination for every clinical question or that unlimited exposure is harmless.", population: "Adults discussing diagnostic ultrasound." },
    { id: MRI, statement: "MRI produces images using magnetic fields and radiofrequency energy without ionizing radiation; this distinction does not eliminate its separate magnetic, device, and heating hazards.", sourceIds: [S.fdaMri.id], category: "safety_boundary", certainty: "high", limitation: "No universal imaging preference or contrast-safety guarantee is inferred from absence of ionizing radiation.", population: "Adults discussing an MRI examination." },
    { id: DEVICE, statement: "MRI screening requires positive identification of an implanted device and verification that the proposed examination satisfies the device's MR safety labeling; a prior uneventful scan alone does not establish clearance for different conditions.", sourceIds: [S.fdaMri.id, S.fdaMriPatient.id], category: "evaluation", certainty: "high", limitation: "The cross-check is another FDA document, not an independent organization. The clinic must not independently clear an unidentified implant or impose a permanent ban on every implant.", population: "Adults with implanted devices referred for MRI." },
    { id: COCHLEAR, statement: "Cochlear-implant MRI restrictions depend on the identified implant and its manufacturer's instructions; instructions for another model cannot be substituted.", sourceIds: [S.fdaCochlear.id], category: "safety_boundary", certainty: "high", limitation: "Single device-specific federal source; no invented field-strength, bandaging, or magnet-removal instruction is authored.", population: "Adults with cochlear implants considering MRI." },
    { id: WARMTH, statement: "Brief isolated flushing or warmth during intravascular iodinated contrast administration is categorized as a physiologic reaction rather than an allergic-like reaction.", sourceIds: [S.acrContrast.id], category: "evaluation", certainty: "high", limitation: "Single society classification source. Applies only to the supplied isolated, transient, fully resolved event; no inference is made about future reaction risk or premedication.", population: "Adults reviewing a documented iodinated contrast event." },
    { id: HIVES, statement: "Urticaria following intravascular iodinated contrast is categorized as an allergic-like reaction, which does not by itself establish an IgE mechanism.", sourceIds: [S.acrContrast.id], category: "evaluation", certainty: "high", limitation: "Single society classification source; no treatment algorithm, exposure challenge, severity inference, or allergy-testing recommendation is supplied.", population: "Adults reviewing documented iodinated contrast-associated hives." },
    { id: LEAK, statement: "Contrast extravasation is escape of intravascular contrast into adjacent tissue and can produce local injection-site pain or swelling rather than isolated generalized warmth.", sourceIds: [S.acrContrast.id], category: "definition", certainty: "high", limitation: "Single society source used to distinguish the supplied documented events; no severity, observation interval, or treatment algorithm is authored.", population: "Adults reviewing a documented intravascular contrast event." },
    { id: DELAYED, statement: "Delayed cutaneous contrast reactions produce a later skin eruption, which is distinct from isolated warmth during injection or urticaria documented during the injection itself.", sourceIds: [S.acrContrast.id], category: "definition", certainty: "high", limitation: "Single society source; no precise timing cutoff or immunologic mechanism is assigned to an individual event.", population: "Adults reviewing the documented timing and features of a contrast event." },
  ],
  concepts: [
    {
      id: "concept.imaging.ionizing-versus-nonionizing-modalities", displayName: "Distinguish ionizing imaging modalities",
      learningObjective: "Explain CT's ionizing X-ray exposure versus the nonionizing mechanisms of ultrasound and MRI during patient-specific imaging counseling.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [CT, US, MRI],
      variants: variants([
        { slug: "prior-ct-ultrasound", complaint: "Imaging exposure question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings reports from a previous abdominal CT and ultrasound. Both studies are complete, and the patient asks which used ionizing radiation.", stem: "Which radiation distinction correctly describes the patient's completed studies?", correct: ["CT used ionizing radiation; ultrasound did not", "CT uses X-rays, while diagnostic ultrasound uses sound waves."], wrong: [["Ultrasound used ionizing radiation; CT did not", "This reverses the mechanisms of the two imaging modalities."], ["Both studies used ionizing radiation", "Sound-based ultrasound does not expose the patient to ionizing X-rays."], ["Neither study used ionizing radiation", "CT remains an ionizing X-ray examination even when performed safely."]], explanation: "The correct answer is “CT used ionizing radiation; ultrasound did not.” This describes imaging physics rather than which study is best for a particular abdominal problem.", claims: [CT, US], ageYears: [36, 61] },
        { slug: "planned-mri-ct", complaint: "MRI counseling", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, is discussing an outside MRI already selected by the treating team. The patient believes the scanner exposes the body to the same X-rays as a prior CT.", stem: "Which explanation correctly distinguishes this patient's planned MRI from the prior CT?", correct: ["MRI uses magnetic fields; CT uses X-rays", "MRI is nonionizing, while CT uses ionizing X-rays."], wrong: [["MRI uses X-rays; CT uses magnetic fields", "These mechanisms have been assigned to the wrong modalities."], ["Both scanners use ionizing X-ray beams", "MRI does not produce its images with ionizing X-rays."], ["Both scanners use returning sound waves", "Acoustic imaging describes ultrasound, not CT or MRI."]], explanation: "The correct answer is “MRI uses magnetic fields; CT uses X-rays.” MRI also uses radiofrequency energy, so routine MRI safety screening still matters even without ionizing radiation.", claims: [CT, US, MRI], ageYears: [44, 67] },
        { slug: "noncontrast-ct", complaint: "CT safety question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews a medically indicated outside CT appointment. The order does not include injected contrast, and the patient asks whether that also removes radiation exposure.", stem: "Which exposure remains inherent to this patient's noncontrast CT?", correct: ["Ionizing X-ray exposure", "CT's X-ray source is independent of whether injected contrast is used."], wrong: [["Magnetic-field exposure", "A CT scanner does not obtain images by MRI's magnetic-field mechanism."], ["Acoustic-wave exposure", "Sound waves are the basis of ultrasound rather than CT."], ["No imaging-energy exposure", "Removing injected contrast does not turn CT into a radiation-free modality."]], explanation: "The correct answer is “Ionizing X-ray exposure.” Contrast and the energy used to make the image are separate issues; this question does not assign a numeric risk to the scheduled examination.", claims: [CT, US, MRI], ageYears: [39, 64] },
        { slug: "ultrasound-sound", complaint: "Ultrasound concern", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, has an ultrasound selected for an outside surgical evaluation. After several previous imaging visits, the patient asks whether this appointment adds another ionizing-radiation exposure.", stem: "Which description correctly explains how this patient's ultrasound creates images?", correct: ["Returning sound waves", "Ultrasound is acoustic imaging without ionizing X-ray exposure."], wrong: [["Emitted ionizing X-rays", "X-ray acquisition describes CT rather than ultrasound."], ["Magnetic radiofrequency signals", "That describes MRI's imaging mechanism rather than ultrasound."], ["Mixed X-rays and sound waves", "Ordinary ultrasound uses sound waves rather than a combination of sound and X-rays."]], explanation: "The correct answer is “Returning sound waves.” This nonionizing mechanism does not make ultrasound interchangeable with every other imaging examination.", claims: [US, CT, MRI], ageYears: [48, 72] },
      ]),
    },
    {
      id: "concept.mri.device-specific-safety-verification", displayName: "Verify an implant's MRI conditions",
      learningObjective: "Identify the exact implanted device and arrange MRI-team verification of device-specific conditions before clearance for the proposed scan.",
      stage: 0, educationalTier: 0, conceptType: "workup", evidenceClaimIds: [DEVICE, COCHLEAR],
      variants: variants([
        { slug: "pacemaker-card", complaint: "Pacemaker MRI question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings a pacemaker card marked MR Conditional before a planned outside MRI. The imaging team has not yet checked the full device system or proposed scanner conditions.", stem: "What is the appropriate device-clearance step before this patient's MRI?", correct: ["Verify device-specific MR conditions", "MR Conditional requires the specific system and scan to meet its conditions."], wrong: [["Proceed using any MRI scanner", "MR Conditional labeling does not authorize unrestricted scanning."], ["Exclude all MRI examinations permanently", "An implant is not automatically a permanent prohibition when a suitable protocol can be verified."], ["Use a prior CT as clearance", "A CT experience does not test the device in an MR environment."]], explanation: "The correct answer is “Verify device-specific MR conditions.” Send the identifying record to the MRI and device teams; the clinic does not independently authorize unrestricted scanning.", claims: [DEVICE], ageYears: [57, 73] },
        { slug: "cochlear-model", complaint: "Implant scan planning", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, has a cochlear implant and brings MRI instructions for a different model found online. The implanted model has not yet been matched to its official instructions.", stem: "Which information should guide clearance of this patient's cochlear implant?", correct: ["The exact implant's MRI instructions", "Device-specific manufacturer conditions must match the actual implanted model."], wrong: [["Any cochlear implant's MRI instructions", "Conditions for another model cannot be safely substituted."], ["The implant's cosmetic appearance", "Appearance does not establish device identity or MR safety conditions."], ["The patient's uneventful CT experience", "CT does not demonstrate compatibility with MRI's magnetic and radiofrequency environment."]], explanation: "The correct answer is “The exact implant's MRI instructions.” The MRI team must verify the actual device; this question does not invent a bandaging or magnet-removal protocol.", claims: [DEVICE, COCHLEAR], ageYears: [31, 56] },
        { slug: "unidentified-implant", complaint: "MRI implant review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, recalls an implanted fixation device but has no identifying records. An outside MRI is requested, and the patient feels that a small implant should need no review.", stem: "What should happen before this patient's implant is cleared for MRI?", correct: ["Verify identity and MR label", "An unidentified device should not be presumed safe for the proposed MR examination."], wrong: [["Clear the implant based on size", "Implant size alone does not establish magnetic, heating, or device risks."], ["Clear the implant based on age", "Time since implantation is not device-specific MR safety labeling."], ["Ban MRI for all implanted metal", "The safe next step is identification and specialist assessment rather than a universal permanent ban."]], explanation: "The correct answer is “Verify identity and MR label.” Defer clearance while the MRI team obtains reliable identification and an appropriate safety assessment.", claims: [DEVICE], ageYears: [42, 69] },
        { slug: "prior-scan-different", complaint: "Repeat MRI question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, has an identified MR Conditional implanted device and previously completed an MRI safely. The new appointment uses a different scanner and examination protocol.", stem: "Which approach appropriately clears this patient's new MRI examination?", correct: ["Check this scan's MR conditions", "A previous uneventful examination does not establish that different conditions are acceptable."], wrong: [["Use the previous scan as clearance", "Past tolerance alone does not verify the current scanner and protocol."], ["Use implantation age as clearance", "Elapsed time does not replace the labeled conditions for the examination."], ["Use absence of symptoms as clearance", "Feeling well does not establish compatibility with the proposed MR environment."]], explanation: "The correct answer is “Check this scan's MR conditions.” Clearance applies to the identified device and the proposed examination, not every future scan automatically.", claims: [DEVICE], ageYears: [46, 71] },
      ]),
    },
    {
      id: "concept.iodinated-contrast.physiologic-versus-allergic-like-reaction", displayName: "Classify a contrast event",
      learningObjective: "Distinguish isolated transient iodinated-contrast warmth from urticaria when reviewing a fully documented outside contrast event.",
      stage: 0, educationalTier: 0, conceptType: "complication", evidenceClaimIds: [WARMTH, HIVES, LEAK, DELAYED],
      variants: variants([
        { slug: "brief-warmth", complaint: "Contrast history review", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews a completed outside contrast CT. Brief warmth occurred during injection, then resolved completely; the record documents no hives, swelling, breathing symptoms, or circulatory instability.", stem: "Which reaction category best describes this patient's isolated transient warmth?", correct: ["A physiologic contrast reaction", "Isolated transient warmth is classified as physiologic."], wrong: [["An allergic-like contrast reaction", "The supplied event lacks the urticaria or other allergic-like features needed for that classification."], ["A contrast extravasation injury", "No injection-site swelling or leakage is described; the event was transient generalized warmth."], ["A delayed cutaneous contrast reaction", "The supplied event was warmth during injection, not a subsequent cutaneous eruption."]], explanation: "The correct answer is “A physiologic contrast reaction.” Do not convert this isolated resolved sensation into a documented allergic-like event; the question does not determine future contrast or premedication plans.", claims: [WARMTH, HIVES, LEAK, DELAYED], ageYears: [35, 62] },
        { slug: "limited-hives", complaint: "Contrast rash history", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside CT record describing itchy raised wheals during iodinated contrast injection. The event resolved under the radiology team's care, and the patient is now well.", stem: "Which reaction category best describes this patient's documented urticaria?", correct: ["An allergic-like contrast reaction", "Hives are an allergic-like feature even when the mechanism is not established."], wrong: [["A physiologic warmth reaction", "Raised itchy wheals are not simply the transient warmth of a physiologic event."], ["A contrast extravasation injury", "A local injection leakage injury does not explain the documented urticarial eruption."], ["A delayed cutaneous contrast reaction", "The documented wheals occurred during injection rather than as a later skin eruption."]], explanation: "The correct answer is “An allergic-like contrast reaction.” This describes the clinical pattern and does not prove that IgE caused the event or specify a future exposure plan.", claims: [WARMTH, HIVES, LEAK, DELAYED], ageYears: [41, 68] },
        { slug: "allergy-list-warmth", complaint: "Allergy record question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, has 'contrast reaction' on an outside referral. The original report documents only fleeting flushing during injection, no rash or swelling, normal breathing and blood pressure, and complete resolution.", stem: "Which classification most accurately describes this patient's recorded event?", correct: ["A physiologic contrast reaction", "The original record describes isolated transient flushing rather than allergic-like features."], wrong: [["An allergic-like contrast reaction", "The nonspecific referral label does not override the documented absence of allergic-like findings."], ["A delayed cutaneous contrast reaction", "No later skin eruption is described in this patient's record."], ["An injection-site contrast injury", "No local leakage, swelling, or tissue injury is documented."]], explanation: "The correct answer is “A physiologic contrast reaction.” Record the actual event rather than inferring its mechanism from a vague referral label.", claims: [WARMTH, HIVES, LEAK, DELAYED], ageYears: [50, 74] },
        { slug: "hives-not-just-warm", complaint: "Contrast event discussion", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, felt warm during an outside contrast CT and then developed several itchy wheals documented by the radiology team. Symptoms resolved, and this visit reviews the event.", stem: "Which classification accounts for this patient's documented wheals as well as warmth?", correct: ["An allergic-like contrast reaction", "The urticaria adds an allergic-like feature beyond isolated warmth."], wrong: [["An isolated physiologic warmth reaction", "That label leaves out the documented hives."], ["A contrast extravasation injury", "No local leakage injury is described, and it does not account for the wheals."], ["A delayed cutaneous contrast reaction", "The documented wheals occurred during the contrast examination rather than as a later skin eruption."]], explanation: "The correct answer is “An allergic-like contrast reaction.” Warmth alone can be physiologic, but the documented urticaria changes this event's classification; it still does not prove an IgE mechanism.", claims: [WARMTH, HIVES, LEAK, DELAYED], ageYears: [38, 65] },
      ]),
    },
  ],
});
