import type { SourceSpec } from "./family-builder";

const FEDERAL = "United States federal government guidance; third-party content, product labeling, logos, and marks retain their own rights. Only independently synthesized facts are used.";
const TARGETED = "Copyrighted professional guidance or approved product labeling; targeted factual verification only, without reproducing protected expression.";

export const FIRST10_SOURCES = {
  fdaXray: {
    id: "source.fda.medical-x-ray-imaging",
    title: "Medical X-ray Imaging",
    citation: "U.S. Food and Drug Administration. Medical X-ray Imaging. FDA medical-imaging safety guidance, undated web page; accessed October 7, 2026. Description and justification sections.",
    organization: "U.S. Food and Drug Administration", authors: ["U.S. Food and Drug Administration"], year: null,
    url: "https://www.fda.gov/radiation-emitting-products/medical-imaging/medical-x-ray-imaging",
    sourceClass: "government_guidance", licenseLabel: FEDERAL, reuseStatus: "public_domain_conditions_apply",
    authority: "Federal radiation-safety guidance directly identifies CT as X-ray imaging using ionizing radiation; no numeric dose or cancer-risk estimate is taught.",
  },
  fdaUltrasound: {
    id: "source.fda.ultrasound-imaging",
    title: "Ultrasound Imaging",
    citation: "U.S. Food and Drug Administration. Ultrasound Imaging. FDA medical-imaging safety guidance, undated web page; accessed October 7, 2026. Description and benefits/risks sections.",
    organization: "U.S. Food and Drug Administration", authors: ["U.S. Food and Drug Administration"], year: null,
    url: "https://www.fda.gov/radiation-emitting-products/medical-imaging/ultrasound-imaging",
    sourceClass: "government_guidance", licenseLabel: FEDERAL, reuseStatus: "public_domain_conditions_apply",
    authority: "Federal device guidance identifies acoustic ultrasound imaging without ionizing radiation; nonionizing does not mean unrestricted or risk-free use.",
  },
  fdaMri: {
    id: "source.fda.mri-benefits-risks",
    title: "MRI: Benefits and Risks",
    citation: "U.S. Food and Drug Administration. MRI (Magnetic Resonance Imaging): Benefits and Risks. Undated FDA web guidance; accessed October 7, 2026. Risks and patients with implants, external and accessory devices sections.",
    organization: "U.S. Food and Drug Administration", authors: ["U.S. Food and Drug Administration"], year: null,
    url: "https://www.fda.gov/radiation-emitting-products/mri-magnetic-resonance-imaging/benefits-and-risks",
    sourceClass: "government_guidance", licenseLabel: FEDERAL, reuseStatus: "public_domain_conditions_apply",
    authority: "Federal MRI-safety guidance distinguishes absence of ionizing radiation from magnetic/RF hazards and requires identification of device status and applicable MR Conditional restrictions.",
  },
  fdaMriPatient: {
    id: "source.fda.mri-patient-device-screening",
    title: "What Patients Should Know Before Having an MRI Exam",
    citation: "U.S. Food and Drug Administration. What Patients Should Know Before Having an MRI Exam. Undated FDA web guidance; accessed October 7, 2026. Implanted-device disclosure and implant-card instructions.",
    organization: "U.S. Food and Drug Administration", authors: ["U.S. Food and Drug Administration"], year: null,
    url: "https://www.fda.gov/radiation-emitting-products/mri-magnetic-resonance-imaging/what-patients-should-know-having-mri-exam",
    sourceClass: "government_guidance", licenseLabel: FEDERAL, reuseStatus: "public_domain_conditions_apply", usageRole: "cross_check",
    authority: "Independent FDA patient-guidance page corroborates disclosure and exact-device identification. It is an additional document from the same authority, not an independent medical organization.",
  },
  fdaCochlear: {
    id: "source.fda.cochlear-implants-mri-safety",
    title: "Cochlear Implants and MRI Safety",
    citation: "U.S. Food and Drug Administration. Cochlear Implants and MRI Safety. FDA medical-device safety web guidance; accessed October 7, 2026. Device identification and manufacturer-specific MRI instructions.",
    organization: "U.S. Food and Drug Administration", authors: ["U.S. Food and Drug Administration"], year: null,
    url: "https://www.fda.gov/medical-devices/cochlear-implants/cochlear-implants-and-mri-safety",
    sourceClass: "government_guidance", licenseLabel: FEDERAL, reuseStatus: "public_domain_conditions_apply", usageRole: "cross_check",
    authority: "Device-specific federal safety guidance confirms that cochlear-implant MRI conditions differ by implant; no manufacturer restriction or magnet-removal protocol is invented.",
  },
  acrContrast: {
    id: "source.acr.contrast-manual.2026.reaction-classification",
    title: "ACR Manual on Contrast Media: reaction classification",
    citation: "American College of Radiology Committee on Drugs and Contrast Media. ACR Manual on Contrast Media. Current web manual with 2026 revision history; accessed October 7, 2026. Extravasation, printed p. 21 (physical PDF p. 24); Allergic-Like and Physiologic Reactions to Intravascular Iodinated Contrast Media, printed pp. 26–31, including delayed cutaneous events on p. 29; acute reaction categories, printed p. 101 (physical PDF p. 104).",
    organization: "American College of Radiology", authors: ["American College of Radiology Committee on Drugs and Contrast Media"], year: 2026,
    url: "https://www.acr.org/Clinical-Resources/Clinical-Tools-and-Reference/Contrast-Manual",
    sourceClass: "professional_society_guideline", licenseLabel: TARGETED, reuseStatus: "copyrighted_targeted_verification_only",
    authority: "Current professional-society consensus manual used only to verify reaction categories. No table, reaction algorithm, exact incidence, prophylaxis rule, or drug treatment is reproduced.",
  },
  empagliflozinFda: {
    id: "source.fda.empagliflozin-label.2025.s063",
    title: "Jardiance (empagliflozin): FDA prescribing information",
    citation: "Boehringer Ingelheim Pharmaceuticals, Inc. Jardiance (empagliflozin tablets): FDA-approved prescribing information, revised October 2025, NDA 204629/S-063, Reference ID 5683490. Sections 2.3 and 5.1; accessed October 7, 2026.",
    organization: "U.S. Food and Drug Administration / Boehringer Ingelheim Pharmaceuticals, Inc.", authors: ["Boehringer Ingelheim Pharmaceuticals, Inc."], year: 2025,
    url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/204629s063lbl.pdf",
    sourceClass: "government_guidance", licenseLabel: TARGETED, reuseStatus: "copyrighted_targeted_verification_only",
    authority: "FDA-approved drug-specific labeling directly supports ketoacidosis recognition and the empagliflozin interruption interval. The dated label is cross-checked against the currently displayed NIH-hosted label; it is not asserted to be the globally latest FDA supplement.",
  },
  empagliflozinCurrent: {
    id: "source.dailymed.empagliflozin-label.2026",
    title: "Jardiance (empagliflozin): current DailyMed label cross-check",
    citation: "Cardinal Health 107, LLC, repackager of Boehringer Ingelheim Pharmaceuticals, Inc. Jardiance (empagliflozin): prescribing information, revised January 2026; DailyMed record updated February 17, 2026, set ID 5777b8a8-ada6-4950-8548-43a1de11f075. Sections 2.3 and 5.1; accessed October 7, 2026.",
    organization: "U.S. National Library of Medicine DailyMed / Boehringer Ingelheim Pharmaceuticals, Inc. / Cardinal Health 107, LLC", authors: ["Boehringer Ingelheim Pharmaceuticals, Inc.", "Cardinal Health 107, LLC"], year: 2026,
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5777b8a8-ada6-4950-8548-43a1de11f075",
    sourceClass: "government_guidance", licenseLabel: TARGETED, reuseStatus: "copyrighted_targeted_verification_only", usageRole: "cross_check",
    authority: "Current NIH-distributed structured product label corroborates unchanged drug-specific interruption and ketoacidosis language. This is repackaged manufacturer labeling, not an independent clinical guideline.",
  },
  ertugliflozinFda: {
    id: "source.fda.ertugliflozin-label.2026.s012",
    title: "Steglatro (ertugliflozin): FDA prescribing information",
    citation: "Merck Sharp & Dohme LLC. Steglatro (ertugliflozin tablets): FDA-approved prescribing information, revised June 2026, NDA 209803/S-012, Reference ID 5809551. Sections 2.3 and 5.1; accessed October 7, 2026.",
    organization: "U.S. Food and Drug Administration / Merck Sharp & Dohme LLC", authors: ["Merck Sharp & Dohme LLC"], year: 2026,
    url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2026/209803s012lbl.pdf",
    sourceClass: "government_guidance", licenseLabel: TARGETED, reuseStatus: "copyrighted_targeted_verification_only",
    authority: "Recent FDA-approved ertugliflozin labeling directly supports the four-day minimum interruption when possible, which must not be collapsed into empagliflozin's three-day label interval.",
  },
  mhraDka: {
    id: "source.mhra.sglt2-ketoacidosis-safety.2016",
    title: "SGLT2 inhibitors: updated advice on the risk of diabetic ketoacidosis",
    citation: "Medicines and Healthcare products Regulatory Agency. SGLT2 inhibitors: updated advice on the risk of diabetic ketoacidosis. Drug Safety Update. April 18, 2016. Government safety guidance, accessed October 7, 2026.",
    organization: "Medicines and Healthcare products Regulatory Agency, United Kingdom", authors: ["Medicines and Healthcare products Regulatory Agency"], year: 2016,
    url: "https://www.gov.uk/drug-safety-update/sglt2-inhibitors-updated-advice-on-the-risk-of-diabetic-ketoacidosis",
    sourceClass: "government_guidance", licenseLabel: "UK Crown copyright, Open Government Licence v3.0, https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/; MHRA credited; no source expression adapted.", reuseStatus: "copyrighted_targeted_verification_only", usageRole: "cross_check",
    authority: "Independent national regulator corroborates near-normal glucose presentations, ketone assessment and drug interruption in suspected ketoacidosis. This older source is not used for the U.S. drug-specific preoperative interval.",
  },
  naloxoneFda: {
    id: "source.fda.naloxone-label.2023.s007.mechanism",
    title: "Narcan (naloxone): FDA mechanism and safety information",
    citation: "Emergent Devices Inc. Narcan (naloxone hydrochloride) nasal spray: FDA-approved prescribing information, revised March 2023, NDA 208411/S-007, Reference ID 5147689. Sections 1, 5.1 and 12.1; accessed October 7, 2026.",
    organization: "U.S. Food and Drug Administration / Emergent Devices Inc.", authors: ["Emergent Devices Inc."], year: 2023,
    url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/208411s007lbl.pdf",
    sourceClass: "government_guidance", licenseLabel: TARGETED, reuseStatus: "copyrighted_targeted_verification_only",
    authority: "FDA-approved label directly states competitive opioid receptor antagonism and need for emergency care. An older prescription-label document is used for the stable mechanism only; no dose, dispensing rule or current packaging claim is authored.",
  },
  naloxoneSafety: {
    id: "source.fda.naloxone-emergency-counseling.2020",
    title: "FDA naloxone counseling and emergency care guidance",
    citation: "U.S. Food and Drug Administration. FDA recommends health care professionals discuss naloxone with all patients when prescribing opioid pain relievers or medicines to treat opioid use disorder. Drug Safety Communication, July 23, 2020. Mechanism and emergency-care sections; accessed October 7, 2026.",
    organization: "U.S. Food and Drug Administration", authors: ["U.S. Food and Drug Administration"], year: 2020,
    url: "https://www.fda.gov/drugs/drug-safety-communications/fda-recommends-health-care-professionals-discuss-naloxone-all-patients-when-prescribing-opioid-pain",
    sourceClass: "government_guidance", licenseLabel: FEDERAL, reuseStatus: "public_domain_conditions_apply", usageRole: "cross_check",
    authority: "Federal safety communication independently corroborates temporary opioid-effect blockade and emergency assistance even after initial improvement; access/dispensing details are outside this batch's claim scope.",
  },
  woundRemodeling: {
    id: "source.frontiers.skin-wound-healing-review.2024",
    title: "Recent advances in molecular mechanisms of skin wound healing and its treatments",
    citation: "Al Mamun A, Shao C, Geng P, Wang S, Xiao J. Recent advances in molecular mechanisms of skin wound healing and its treatments. Frontiers in Immunology. 2024;15:1395479. Published May 21, 2024. doi:10.3389/fimmu.2024.1395479. Remodeling section; accessed October 7, 2026.",
    organization: "Frontiers in Immunology", authors: ["Abdullah Al Mamun", "Chuxiao Shao", "Peiwu Geng", "Shuanghu Wang", "Jian Xiao"], year: 2024,
    url: "https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2024.1395479/full",
    doi: "10.3389/fimmu.2024.1395479", sourceClass: "narrative_review",
    licenseLabel: "Creative Commons Attribution 4.0, https://creativecommons.org/licenses/by/4.0/; credited to Al Mamun, Shao, Geng, Wang and Xiao and Frontiers in Immunology. Only original underlying-fact synthesis is authored; no source expression, figures or tables are reproduced.", reuseStatus: "cc_by_4_0",
    authority: "Peer-reviewed narrative review directly describes early type III collagen being replaced by type I during remodeling. This is a biological mechanism source, not a management guideline; no exact healing timeline, strength percentage or treatment is inferred.",
  },
  sagesShoulder: {
    id: "source.sages.laparoscopic-gallbladder-patient-information.2026",
    title: "Patient information for laparoscopic gallbladder removal",
    citation: "Society of American Gastrointestinal and Endoscopic Surgeons. Patient Information for Laparoscopic Gallbladder Removal (Cholecystectomy). Patient guidance revised May 6, 2026. Recovery and when-to-call sections; accessed October 7, 2026.",
    organization: "Society of American Gastrointestinal and Endoscopic Surgeons", authors: ["Society of American Gastrointestinal and Endoscopic Surgeons"], year: 2026,
    url: "https://www.sages.org/publications/patient-information/patient-information-for-laparoscopic-gallbladder-removal-cholecystectomy-from-sages/",
    sourceClass: "professional_society_guideline", licenseLabel: TARGETED, reuseStatus: "copyrighted_targeted_verification_only",
    authority: "Current society patient guidance supports gas-associated shoulder pain after laparoscopic cholecystectomy and evaluation of warning symptoms. No brochure prose, numeric fever cutoff, expected duration or recovery schedule is reproduced.",
  },
  shoulderMechanism: {
    id: "source.gynecological-surgery.shoulder-pain-trial.2021",
    title: "Effects of delayed suprapubic port removal on post-laparoscopic shoulder pain: a randomized controlled trial",
    citation: "Chalermchockcharoenkit A, Hengrasmee P, Sophontanarak P, Sirimai K, Sutchritpongsa P, Srichaikul P. Effects of delayed suprapubic port removal on post-laparoscopic shoulder pain: a randomized controlled trial. Gynecological Surgery. 2021;18:8. Published May 11, 2021. doi:10.1186/s10397-021-01087-6. Introduction; accessed October 7, 2026.",
    organization: "Gynecological Surgery", authors: ["Amphan Chalermchockcharoenkit", "Pattaya Hengrasmee", "Paiboon Sophontanarak", "Korakot Sirimai", "Pavit Sutchritpongsa", "Pisutt Srichaikul"], year: 2021,
    url: "https://link.springer.com/article/10.1186/s10397-021-01087-6", doi: "10.1186/s10397-021-01087-6",
    sourceClass: "randomized_trial", usageRole: "cross_check",
    licenseLabel: "Creative Commons Attribution 4.0, https://creativecommons.org/licenses/by/4.0/; credited to the six named authors and Gynecological Surgery. Only original underlying-fact synthesis is authored; no trial expression or intervention protocol is adapted.", reuseStatus: "cc_by_4_0",
    authority: "Peer-reviewed trial introduction independently corroborates diaphragmatic/phrenic irritation as a proposed contributor to referred shoulder pain. The study population was adults undergoing gynecologic laparoscopy; it is a mechanism cross-check, not a universal cause or a cholecystectomy treatment recommendation.",
  },
  laparoscopyPhysiology: {
    id: "source.jcm.laparoscopic-anesthesia-review.2020",
    title: "Do Small Incisions Need Only Minimal Anesthesia? Anesthetic Management in Laparoscopic and Robotic Surgery",
    citation: "Hottenrott S, Schlesinger T, Helmer P, Meybohm P, Alkatout I, Kranke P. Do Small Incisions Need Only Minimal Anesthesia?—Anesthetic Management in Laparoscopic and Robotic Surgery. Journal of Clinical Medicine. 2020;9(12):4058. Published December 15, 2020. doi:10.3390/jcm9124058. Sections 3.1 and 3.4, pp. 3–4; accessed October 7, 2026.",
    organization: "Journal of Clinical Medicine", authors: ["Sebastian Hottenrott", "Tobias Schlesinger", "Philipp Helmer", "Patrick Meybohm", "Ibrahim Alkatout", "Peter Kranke"], year: 2020,
    url: "https://mdpi-res.com/d_attachment/jcm/jcm-09-04058/article_deploy/jcm-09-04058.pdf", doi: "10.3390/jcm9124058",
    sourceClass: "narrative_review", reuseStatus: "cc_by_4_0",
    licenseLabel: "Article-specific Creative Commons Attribution 4.0 notice verified on PDF p. 15, https://creativecommons.org/licenses/by/4.0/; credited to the six named authors and Journal of Clinical Medicine. Original underlying-fact synthesis only. The publisher HTML and general terms/open-access pages were unavailable during checking; general site terms were not asserted to have been read.",
    authority: "Peer-reviewed physiology review directly supports absorption/exhalation of insufflated CO2 and context-dependent pressure/position effects on venous return. The older review is cross-checked with a current independent clinical study; no numeric pressure limit, ventilator setting or operating-room treatment protocol is authored.",
  },
  laparoscopicAcidBase: {
    id: "source.jroboticsurg.pneumoperitoneum-acid-base-study.2026",
    title: "Acid–base balance and respiratory mechanics during robotic-assisted surgery: an observational study",
    citation: "Pitimada M, Chiumello D, Monte A, Fratti I, Festa F, Pozzi T, Coppola S. Acid–base balance and respiratory mechanics during robotic-assisted surgery: an observational study. Journal of Robotic Surgery. 2026;20:440. Published April 21, 2026. doi:10.1007/s11701-026-03392-8. Introduction and discussion: acid-base equilibrium and gas exchange; accessed October 7, 2026.",
    organization: "Journal of Robotic Surgery", authors: ["Matteo Pitimada", "Davide Chiumello", "Alessandro Monte", "Isabella Fratti", "Federica Festa", "Tommaso Pozzi", "Silvia Coppola"], year: 2026,
    url: "https://link.springer.com/article/10.1007/s11701-026-03392-8", doi: "10.1007/s11701-026-03392-8",
    sourceClass: "observational_study", reuseStatus: "cc_by_4_0", usageRole: "cross_check",
    licenseLabel: "Creative Commons Attribution 4.0 International, https://creativecommons.org/licenses/by/4.0/; credited to the seven named authors and Journal of Robotic Surgery. Original underlying-fact synthesis only; no source expression, data tables, images or ventilation protocol is reproduced.",
    authority: "Current peer-reviewed observational study corroborates peritoneal CO2 absorption with increased arterial CO2/respiratory acidemia and pressure-associated hemodynamic effects. Colorectal/gynecological surgical population and observational design limit universal mechanistic inference; no renal, numeric outcome or treatment claim is extrapolated.",
  },
} as const satisfies Record<string, SourceSpec>;
