import type { SourceSpec } from "./family-builder";

const FEDERAL = "United States government-authored text; public-domain conditions and attribution apply. Third-party material, images, marks and product labeling are excluded; no source expression reproduced.";
const OGL = "Open Government Licence v3.0, https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/; logo and third-party exclusions apply. Contains public sector information licensed under the Open Government Licence v3.0. The schema has no OGL category, so targeted factual verification is recorded conservatively; OGL is not public domain.";

export const REMAINING10_SOURCES = {
  nhsScars: {
    id: "source.gs028e.nhs_scars", title: "Scars",
    citation: "NHS. Scars. NHS website, reviewed September 18, 2023. Types of scars section; accessed October 7, 2026.",
    organization: "National Health Service, United Kingdom", authors: ["National Health Service"], year: 2023,
    url: "https://www.nhs.uk/conditions/scars/", sourceClass: "government_guidance",
    licenseLabel: `NHS website text under ${OGL} Rights: https://www.nhs.uk/our-policies/terms-and-conditions/, sections 3.3–3.6.`,
    reuseStatus: "copyrighted_targeted_verification_only",
    authority: "Official patient information directly supports the original-wound boundary distinction between hypertrophic scars and keloids and depressed atrophic-scar morphology. No treatment, demographic selection, onset interval or regression guarantee is taught.",
  },
  secondaryHealing: {
    id: "source.gs028e.uhd_secondary_healing", title: "Secondary intention healing wound care",
    citation: "Murguia A, Atienza M. Secondary intention healing wound care. Dermatology Minor Skin Surgery. University Hospitals Dorset NHS Foundation Trust; version three, February 2026. Ref 400/21; review February 2029. Physical PDF p. 2, What is Secondary Intention Healing? Accessed October 7, 2026.",
    organization: "University Hospitals Dorset NHS Foundation Trust", authors: ["A. Murguia", "M. Atienza"], year: 2026,
    url: "https://www.uhd.nhs.uk/uploads/about/docs/our_publications/patient_information_leaflets/dermatology/secondary-intention-healing.pdf",
    sourceClass: "government_guidance", licenseLabel: "Institutional patient-information leaflet; no open license verified. NHS.uk's OGL is not assumed to cover this separate trust. Targeted definition verification only; no expression or wound-care instructions reproduced.",
    reuseStatus: "copyrighted_targeted_verification_only",
    authority: "Current institutional leaflet supports the narrow definition of an appropriately open wound healing without stitched approximation. Single adequate source for this definition; no healing duration, dressing schedule, later-closure recommendation or medication rule is inferred.",
  },
  fdaImmunotoxicity: {
    id: "source.gs028e.fda_immunotoxicity", title: "Immunotoxicity Testing Guidance",
    citation: "U.S. Food and Drug Administration, Center for Devices and Radiological Health, Molecular Biology Branch, Division of Life Sciences, Office of Science and Technology. Immunotoxicity Testing Guidance. Final guidance issued May 6, 1999; HTML content current as of March 27, 2018. Glossary, Hypersensitivity, and immunogenicity discussion following Table 3. Accessed October 7, 2026.",
    organization: "U.S. Food and Drug Administration", authors: ["U.S. Food and Drug Administration, Center for Devices and Radiological Health"], year: 1999,
    url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/immunotoxicity-testing-guidance",
    sourceClass: "government_guidance", licenseLabel: FEDERAL, reuseStatus: "public_domain_conditions_apply", usageRole: "both",
    authority: "Older federal device guidance corroborates stable type I IgE and type IV T-cell mechanisms, including latex-protein versus glove-chemical reactions, and supplies the narrow non-IgE IgG/IgM-complement comparator. It is not a current patient-management or device-testing protocol; no table or algorithm is reused.",
  },
  niaidFoodSummary: {
    id: "source.gs028e.niaid_food_summary", title: "NIAID-sponsored food-allergy guideline summary",
    citation: "National Institute of Allergy and Infectious Diseases. Guidelines for the Diagnosis and Management of Food Allergy in the United States: Summary of the NIAID-Sponsored Expert Panel Report. NIH Publication No. 11-7700. December 2010. Section 4.4, printed p. 14 / physical PDF p. 26; section 6.1, printed p. 21 / physical p. 33. Accessed October 7, 2026.",
    organization: "National Institute of Allergy and Infectious Diseases, National Institutes of Health", authors: ["National Institute of Allergy and Infectious Diseases"], year: 2010,
    url: "https://www.niaid.nih.gov/sites/default/files/faguidelinesexecsummary.pdf",
    sourceClass: "government_guidance", licenseLabel: `${FEDERAL} NIAID publication-text policy: https://www.niaid.nih.gov/global/copyright-and-reuse.`, reuseStatus: "public_domain_conditions_apply",
    authority: "Federal expert-panel summary directly supports allergen interaction with mast-cell-bound IgE and notes that contact urticaria can also be non-IgE-mediated. Stable mechanism only; this older report is not used to author current food-allergy treatment or challenge instructions.",
  },
  contactDermatitis: {
    id: "source.gs028e.acd_tong2026", title: "Immunopathogenesis and immunoregulatory mechanisms in allergic contact dermatitis",
    citation: "Tong Y, Chen H, Kou Q, He B, Tang Y, Ran K, Zhang L, Gan X. Immunopathogenesis and immunoregulatory mechanisms in allergic contact dermatitis. Front Immunol. 2026;17:1835083. Published May 13, 2026. doi:10.3389/fimmu.2026.1835083. Abstract and section 1, Introduction; accessed October 7, 2026.",
    organization: "Frontiers in Immunology", authors: ["Yanjun Tong", "Hong Chen", "Qiong Kou", "Bin He", "Ying Tang", "Kunjie Ran", "Lijun Zhang", "Xin Gan"], year: 2026,
    doi: "10.3389/fimmu.2026.1835083", url: "https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2026.1835083/full",
    sourceClass: "narrative_review", licenseLabel: "Copyright © 2026 Tong, Chen, Kou, He, Tang, Ran, Zhang and Gan. Article-specific Creative Commons Attribution 4.0, https://creativecommons.org/licenses/by/4.0/. Authors and original publication credited; independently written factual synthesis only.", reuseStatus: "cc_by_4_0",
    authority: "Current peer-reviewed mini-review supports the T-cell-mediated mechanism of confirmed allergic contact dermatitis. It does not make all contact rashes allergic, prescribe a patch-test protocol, or supply an exact reaction interval.",
  },
  ahrqTransplant: {
    id: "source.gs028e.ahrq_transplant2012", title: "The impact of pre-transplant red blood cell transfusions in renal allograft rejection",
    citation: "Chen W, Lee S, Colby J, Kluger J, Ashaye A, Tongbram V, Baker E, Mather J, Coleman CI, White CM. The Impact of Pre-Transplant Red Blood Cell Transfusions in Renal Allograft Rejection. University of Connecticut/Hartford Hospital Evidence-based Practice Center for AHRQ; March 7, 2012. Project RENT0610. Executive Summary ES-1 / physical PDF p. 9; conditions of use, printed iii / physical p. 3. Accessed October 7, 2026.",
    organization: "University of Connecticut/Hartford Hospital Evidence-based Practice Center; Agency for Healthcare Research and Quality", authors: ["Wendy Chen", "Soyon Lee", "Jennifer Colby", "Jeffrey Kluger", "Ajibade Ashaye", "Vanita Tongbram", "Erica Baker", "Jeffrey Mather", "Craig I. Coleman", "C. Michael White"], year: 2012,
    url: "https://www.cms.gov/Medicare/Coverage/DeterminationProcess/downloads/id78TA.pdf", sourceClass: "systematic_review",
    licenseLabel: "Commissioned EPC report, not presumed government-authored public domain. Printed iii allows use as a basis for clinical/quality tools without implying AHRQ or HHS endorsement. Targeted original factual cross-check only.", reuseStatus: "copyrighted_targeted_verification_only", usageRole: "cross_check",
    authority: "Older commissioned systematic review corroborates pre-existing anti-donor antibodies in hyperacute renal allograft rejection. Background mechanism only, not current transplant treatment, allocation or crossmatch management.",
  },
  hyperacuteReview: {
    id: "source.gs028e.hyperacute_matsuda2016", title: "Unraveling the Role of Allo-Antibodies and Transplant Injury",
    citation: "Matsuda Y, Sarwal MM. Unraveling the Role of Allo-Antibodies and Transplant Injury. Front Immunol. 2016;7:432. Published October 21, 2016. doi:10.3389/fimmu.2016.00432. PMID:27818660. Abstract; The Role of Preformed DSA, Mechanisms of Onset of ABMR by Preformed DSA; accessed October 7, 2026.",
    organization: "Frontiers in Immunology", authors: ["Yoshiko Matsuda", "Minnie M. Sarwal"], year: 2016,
    doi: "10.3389/fimmu.2016.00432", pmid: "27818660", url: "https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2016.00432/full",
    sourceClass: "narrative_review", licenseLabel: "Copyright © 2016 Matsuda and Sarwal. Article-specific Creative Commons Attribution 4.0, https://creativecommons.org/licenses/by/4.0/. Authors and original publication credited; no source expression reused.", reuseStatus: "cc_by_4_0",
    authority: "Peer-reviewed transplant review supports preformed donor-specific antibodies binding graft endothelium with complement-associated vascular injury. Its Abstract distinguishes T-cell and antibody pathways and recognizes coexistence. Narrow documented hyperacute mechanism only; not every early graft failure or acute rejection is assigned this mechanism.",
  },
  nciStage: {
    id: "source.gs028e.nci_stage", title: "Cancer Staging",
    citation: "National Cancer Institute. Cancer Staging. Reviewed October 14, 2022. Definition, staging systems and TNM discussion; accessed October 7, 2026.",
    organization: "National Cancer Institute", authors: ["National Cancer Institute"], year: 2022,
    url: "https://www.cancer.gov/about-cancer/diagnosis-staging/staging", sourceClass: "government_guidance",
    licenseLabel: `${FEDERAL} Source credited to NCI. Text reuse policy, reviewed March 12, 2025: https://www.cancer.gov/policies/copyright-reuse.`, reuseStatus: "public_domain_conditions_apply",
    authority: "Official patient education supports stage as disease extent and explicitly recognizes cancer-specific staging systems. No universal stage number, prognosis or treatment rule is inferred.",
  },
  nciGrade: {
    id: "source.gs028e.nci_grade", title: "Tumor Grade",
    citation: "National Cancer Institute. Tumor Grade. Updated August 1, 2022. What is tumor grade? and How pathologists grade tumors sections; accessed October 7, 2026.",
    organization: "National Cancer Institute", authors: ["National Cancer Institute"], year: 2022,
    url: "https://www.cancer.gov/about-cancer/diagnosis-staging/diagnosis/tumor-grade", sourceClass: "government_guidance",
    licenseLabel: `${FEDERAL} Source credited to NCI. https://www.cancer.gov/policies/copyright-reuse.`, reuseStatus: "public_domain_conditions_apply",
    authority: "Official patient education distinguishes microscopic appearance/differentiation from anatomic extent. Grading criteria differ among cancers; no numeric grading scheme, equivalence to stage or guaranteed behavior is taught.",
  },
  nlmRb1: {
    id: "source.gs028e.nlm_rb1", title: "RB1 gene",
    citation: "National Library of Medicine. RB1 gene. MedlinePlus Genetics; updated April 1, 2009. Normal Function; Health Conditions Related to Genetic Changes, Retinoblastoma and Other Cancers. Accessed October 7, 2026.",
    organization: "National Library of Medicine, MedlinePlus Genetics", authors: ["National Library of Medicine"], year: 2009,
    url: "https://medlineplus.gov/genetics/gene/rb1/", sourceClass: "open_educational_resource",
    licenseLabel: "MedlinePlus Genetics gene summaries are public domain under https://medlineplus.gov/about/using/usingcontent/ (updated October 26, 2022). Source: MedlinePlus, National Library of Medicine. A.D.A.M. encyclopedia, drug monographs, logos and third-party content excluded.", reuseStatus: "public_domain_conditions_apply",
    authority: "Government-curated gene summary supports RB1 growth restraint and the classic loss of both functioning copies. Used for a supplied adult tumor molecular report, not pediatric disease management, inherited-syndrome diagnosis or a universal rule for every tumor suppressor.",
  },
  nciRb1: {
    id: "source.gs028e.nci_rb1_pdq", title: "Retinoblastoma Treatment (PDQ®): molecular RB1 background",
    citation: "PDQ Pediatric Treatment Editorial Board. Retinoblastoma Treatment (PDQ®): Health Professional Version. Bethesda, MD: National Cancer Institute; updated April 3, 2025. PMID:26389442. Genetics and Genomics, Nonheritable Retinoblastoma; About This PDQ Summary, permissions. Accessed October 7, 2026.",
    organization: "National Cancer Institute PDQ", authors: ["PDQ Pediatric Treatment Editorial Board"], year: 2025, pmid: "26389442",
    url: "https://www.cancer.gov/types/retinoblastoma/hp/retinoblastoma-treatment-pdq", sourceClass: "government_guidance",
    licenseLabel: "Freely usable PDQ text with attribution; modified material cannot be labeled an NCI PDQ summary. NCI trademarks, images and third-party expression excluded. Independent factual cross-check only.", reuseStatus: "public_domain_conditions_apply", usageRole: "cross_check",
    authority: "Current peer-reviewed PDQ summary, explicitly not a formal NCI/NIH guideline, corroborates biallelic RB1 loss and describes exceptions. Only molecular background is used; no pediatric case or cancer-management recommendation is generated.",
  },
  ukhsaWoundClass: {
    id: "source.gs028e.ukhsa_woundclass", title: "Protocol for the Surveillance of Surgical Site Infection: wound class",
    citation: "UK Health Security Agency. Protocol for the Surveillance of Surgical Site Infection. Version 6 (June 2013) r2, published January 2022. Publishing reference GOV-10188. London: UKHSA; 2022. Section 5.2.16, printed and physical PDF p. 50; copyright and license, p. 101. Accessed October 7, 2026.",
    organization: "UK Health Security Agency", authors: ["UK Health Security Agency"], year: 2022,
    url: "https://assets.publishing.service.gov.uk/media/61e989028fa8f505985ef463/Protocol_for_the_Surveillance_of_Surgical_Site_Infection.pdf", sourceClass: "government_guidance",
    licenseLabel: `© Crown copyright 2022. ${OGL}` , reuseStatus: "copyrighted_targeted_verification_only",
    authority: "Current official linked surveillance protocol supports clean, clean-contaminated, contaminated and dirty/infected distinctions. Definitions only; no copied table, source-specific traumatic-wound time cutoff, infection probability or automatic antibiotic prescription.",
  },
  tiedeMixing: {
    id: "source.gs028e.tiede_mixing2020", title: "International recommendations on the diagnosis and treatment of acquired hemophilia A",
    citation: "Tiede A, Collins P, Knoebl P, Teitel J, Kessler C, Shima M, Di Minno G, d’Oiron R, Salaj P, Jiménez-Yuste V, Huth-Kühne A, Giangrande P. International recommendations on the diagnosis and treatment of acquired hemophilia A. Haematologica. 2020;105(7):1791–1801. doi:10.3324/haematol.2019.230771. PMID:32381574. Diagnosis, Mixing tests; accessed October 7, 2026.",
    organization: "Haematologica; Ferrata Storti Foundation", authors: ["Andreas Tiede", "Peter Collins", "Paul Knoebl", "Jerome Teitel", "Craig Kessler", "Midori Shima", "Giovanni Di Minno", "Roseline d’Oiron", "Peter Salaj", "Victor Jiménez-Yuste", "Angela Huth-Kühne", "Paul Giangrande"], year: 2020,
    doi: "10.3324/haematol.2019.230771", pmid: "32381574", url: "https://haematologica.org/article/view/9931", sourceClass: "peer_reviewed_guideline",
    licenseLabel: "Publisher default is CC BY-NC; article-specific license version not verified. Rights: https://haematologica.org/rights-and-permissions and /our-policies. Targeted guideline factual verification only; no expression, algorithm or commercial text mining.", reuseStatus: "copyrighted_targeted_verification_only",
    authority: "International consensus guideline supports the conditional role of mixing tests when immediate FVIII:C is unavailable, parallel factor assays, time-dependent inhibitors and inability of mixing alone to establish or exclude acquired hemophilia A. No universal mandatory next-test rule or bleeding-risk prediction is authored.",
  },
  czempikMixing: {
    id: "source.gs028e.czempik_mixing2020", title: "Isolated prolongation of activated partial thromboplastin time in intensive care unit patients",
    citation: "Czempik PF, Żurawska E, Krzych ŁJ. Isolated prolongation of activated partial thromboplastin time in intensive care unit patients: a practical diagnostic algorithm and management options. Anaesthesiol Intensive Ther. 2020;52(2):165–170. Published June 28, 2020. doi:10.5114/ait.2020.96484. Printed p. 168 / physical PDF p. 4, mixing-study discussion following congenital causes; accessed October 7, 2026.",
    organization: "Anaesthesiology Intensive Therapy; Polish Society of Anaesthesiology and Intensive Therapy", authors: ["Piotr F. Czempik", "Elżbieta Żurawska", "Łukasz J. Krzych"], year: 2020,
    doi: "10.5114/ait.2020.96484", url: "https://www.ait-journal.com/pdf-120403-121971", sourceClass: "narrative_review",
    licenseLabel: "Author institutional record confirms CC BY-NC-SA 4.0, https://creativecommons.org/licenses/by-nc-sa/4.0/, https://ppm.sum.edu.pl/info/article/SUMad15725785874be7b52463ed0a761ea2?lang=en. The schema lacks an SA category; conservative targeted factual verification only. Czempik, Żurawska and Krzych and original publication credited; no source expression adapted or redistributed.", reuseStatus: "copyrighted_targeted_verification_only", usageRole: "both",
    authority: "Independent society-journal review supports initial immediate/incubated correction-versus-inhibition patterns, laboratory-specific criteria and specimen/drug limitations. Its ICU algorithm is not generalized to all preoperative patients, and its local-laboratory statement does not establish this game's onsite capability.",
  },
} satisfies Record<string, SourceSpec>;
