import { buildFamily } from "./family-builder";
import { variants } from "./spec-utils";
import { REMAINING10_SOURCES as S } from "./source-catalog-remaining10";

const SCAR = "claim.gs028e.scar_extent";
const SCAR_SHAPE = "claim.gs028e.scar_shape_comparison";
const SECONDARY = "claim.gs028e.secondary_intention";

export const WOUND_HEALING_REMAINING_FAMILY = buildFamily({
  slug: "wound-healing-remaining", label: "Scar and wound-healing counseling",
  sources: [S.nhsScars, S.secondaryHealing],
  claims: [
    { id: SCAR, statement: "A raised hypertrophic scar stays within the original wound boundary, whereas a keloid extends into skin beyond that boundary.", sourceIds: [S.nhsScars.id], category: "definition", certainty: "high", limitation: "Morphologic distinction from one official patient-information source; neither timing, symptoms nor ancestry alone establishes the classification. No regression or treatment guarantee.", population: "Adults discussing a raised scar after a healed skin wound." },
    { id: SCAR_SHAPE, statement: "An atrophic scar may be depressed below the surrounding skin, in contrast to the raised morphology supplied for hypertrophic scars and keloids.", sourceIds: [S.nhsScars.id], category: "definition", certainty: "high", limitation: "One official patient-information source; used only for the morphological distractor distinction, without cause, treatment or timing claims.", population: "Adults comparing a raised healed scar with a depressed scar pattern." },
    { id: SECONDARY, statement: "Secondary-intention healing describes an appropriately open wound allowed to heal without bringing its edges together with closure; planned later edge approximation is a different strategy.", sourceIds: [S.secondaryHealing.id], category: "definition", certainty: "high", limitation: "One current institutional source for the narrow definition. The question supplies the treating clinician's appropriate open-wound plan; it does not decide which wounds should be left open or prescribe care, duration or strength.", population: "Adults reviewing a clinician-selected open skin-wound healing plan." },
  ],
  concepts: [
    {
      id: "concept.wound.hypertrophic-versus-keloid-extent", displayName: "Distinguish raised scars by their boundary",
      learningObjective: "Use extension beyond versus confinement within the original wound to distinguish a keloid from a hypertrophic scar.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [SCAR, SCAR_SHAPE],
      variants: variants([
        { slug: "incision-overgrowth", complaint: "Growing incision scar", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, visits the clinic about a healed skin incision. A firm raised scar now spreads onto previously uninjured skin beyond both sides of the documented incision. The wound is closed without drainage or surrounding inflammation.", stem: "Which raised-scar pattern best fits extension beyond this patient's original incision?", correct: ["Keloid scar", "The distinguishing feature is growth beyond the original wound boundary."], wrong: [["Hypertrophic scar", "That raised-scar category is confined to the original wound boundary."], ["Atrophic scar", "The described scar is raised and expanding rather than depressed."], ["Flat scar", "The described tissue is raised and extends beyond the incision."]], explanation: "The correct answer is “Keloid scar.” Extension onto skin outside the original injury distinguishes this pattern from a hypertrophic scar; the description does not select a treatment.", claims: [SCAR, SCAR_SHAPE], ageYears: [29, 51] },
        { slug: "lipoma-margin", complaint: "Raised healed scar", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings a photograph of the original incision after an outside lipoma removal. The current scar is thick and raised, but its entire footprint stays inside that incision's edges. There is no open wound, drainage or expanding redness.", stem: "Which scar classification best matches raised tissue confined to this patient's original wound?", correct: ["Hypertrophic scar pattern", "Raised scar confined to the original wound is the hypertrophic pattern."], wrong: [["Pattern of keloid scarring", "A keloid extends beyond the original injury rather than staying within it."], ["Atrophic scar pattern", "The supplied morphology is raised rather than depressed."], ["Flat scar pattern", "The scar is explicitly thick and raised rather than flat."]], explanation: "The correct answer is “Hypertrophic scar pattern.” Compare the scar's footprint with the original wound; raised appearance by itself does not distinguish the two major overgrowth patterns.", claims: [SCAR, SCAR_SHAPE], ageYears: [35, 63] },
        { slug: "piercing-boundary", complaint: "Piercing scar growth", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, shows a healed ear-piercing site in clinic. A specialist has excluded an active infection. The raised scar has grown across intact skin well outside the tiny original puncture, and the patient calls it a 'souvenir with expansion plans.'", stem: "Which scar pattern is supported by growth outside this patient's original piercing wound?", correct: ["Keloid scar", "The growth extends beyond the original puncture boundary."], wrong: [["Hypertrophic scar", "Confinement to the original injury would favor this alternative."], ["Atrophic scar", "The scar is raised rather than sunken."], ["Flat scar", "A raised expanding mass does not match a flat scar pattern."]], explanation: "The correct answer is “Keloid scar.” The old wound boundary is the relevant clue; the nickname, scar location and patient identity do not determine the classification.", claims: [SCAR, SCAR_SHAPE], ageYears: [24, 40] },
        { slug: "burn-outline", complaint: "Scar comparison", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews a fully healed minor burn scar in clinic. Its surface is raised and firm. An outline in the outside wound record shows that the scar remains entirely inside the original burn area, despite the patient worrying that any thick scar must be a keloid.", stem: "Which scar classification best fits this patient's raised scar remaining within the original burn boundary?", correct: ["Hypertrophic scar pattern", "The recorded scar footprint is confined to the original injury."], wrong: [["Pattern of keloid scarring", "The case supplies no extension outside the injury boundary."], ["Atrophic scar pattern", "The described surface is raised rather than depressed."], ["Flat scar pattern", "Flat morphology does not match the supplied raised scar."]], explanation: "The correct answer is “Hypertrophic scar pattern.” Thickening within an old wound and expansion beyond it are different morphologic patterns; no prediction about eventual flattening is required.", claims: [SCAR, SCAR_SHAPE], ageYears: [42, 66] },
      ]),
    },
    {
      id: "concept.wound.secondary-intention-healing", displayName: "Recognize secondary-intention healing",
      learningObjective: "Identify a clinician-selected open wound healing without immediate or planned delayed edge approximation as secondary-intention healing.",
      stage: 0, educationalTier: 0, conceptType: "applied_science", evidenceClaimIds: [SECONDARY],
      variants: variants([
        { slug: "skin-excision-plan", complaint: "Open wound plan", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside dermatology record after a small skin lesion was removed. The treating clinician deliberately left the appropriate defect open to heal without stitches, a graft or planned later closure. The patient is well and has no wound-infection symptoms.", stem: "Which healing strategy describes this patient's wound being left open without later edge closure?", correct: ["Healing by secondary intention", "The plan is open-wound healing without approximation of the edges."], wrong: [["Healing by direct edge approximation", "The record specifically says the edges were not brought together."], ["Healing after delayed edge closure", "No later edge-closure procedure is part of the supplied plan."], ["Healing after skin-graft placement", "The wound plan explicitly excludes a graft."]], explanation: "The correct answer is “Healing by secondary intention.” This names the supplied healing plan; it does not recommend leaving every excision open.", claims: [SECONDARY], ageYears: [46, 71] },
        { slug: "no-stitch-mixup", complaint: "Missing stitch question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, arrives with an outside minor-surgery wound plan and asks whether the surgeon forgot the stitches. The treating clinician intentionally selected secondary-intention healing for the suitable skin defect. The patient is well without active bleeding or infection symptoms.", stem: "Which description explains the intentional absence of stitches in this patient's documented secondary-intention plan?", correct: ["Open healing without edge approximation", "Secondary intention describes healing without bringing the wound edges together for closure."], wrong: [["Immediate healing with sutured edge approximation", "Immediate sutured approximation would describe a different supplied healing method."], ["Open observation followed by delayed edge closure", "Planned later edge approximation is different from secondary-intention healing."], ["Wound coverage by planned skin-graft placement", "A graft-based closure is different from the supplied open-healing plan."]], explanation: "The correct answer is “Open healing without edge approximation.” The term describes an intentional healing method, rather than implying that stitches were forgotten.", claims: [SECONDARY], ageYears: [38, 59] },
        { slug: "scheduled-review", complaint: "Wound follow-up question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, reviews an outside skin-wound plan. The wound is currently open and a follow-up visit is scheduled. The treating clinician says the selected method is secondary intention, and the patient wants to distinguish a review appointment from delayed primary closure.", stem: "Which planned feature distinguishes secondary intention from delayed edge closure in this patient's wound record?", correct: ["Healing proceeds without later edge closure", "The absence of planned later approximation distinguishes open secondary healing from delayed closure."], wrong: [["Wound edges will be sutured at the review visit", "Planned later suturing describes delayed edge closure rather than the supplied method."], ["Wound edges were sutured at the initial procedure", "Immediate approximation is a different method and conflicts with the open wound."], ["A skin graft will close the defect at the review visit", "A planned graft is a closure method rather than open secondary-intention healing."]], explanation: "The correct answer is “Healing proceeds without later edge closure.” A scheduled review by itself does not establish delayed primary closure; the intended absence of later approximation is the decisive distinction.", claims: [SECONDARY], ageYears: [50, 74] },
        { slug: "closure-method-form", complaint: "Healing form question", presentation: "{patientName}, a {patientAge}-year-old {patientSex}, brings an outside skin-surgery report that labels the suitable defect's healing method as secondary intention. The patient is well at the clinic explanation visit and asks for help checking proposed entries in the healing-method section.", stem: "Which proposed chart entry is incompatible with the secondary-intention method already selected for this patient's suitable wound?", correct: ["Healing with planned later edge approximation", "Planned later edge approximation conflicts with the selected secondary-intention method."], wrong: [["Healing without initial edge approximation", "The absence of initial approximation is compatible with the selected open-healing method."], ["Healing without planned later edge approximation", "The absence of planned later approximation is compatible with secondary intention."], ["Healing of the suitable defect while open", "Open healing is compatible with the method already selected in the outside record."]], explanation: "The correct answer is “Healing with planned later edge approximation.” Secondary intention does not include planned later closure of the edges. This checks the consistency of the recorded plan; it does not choose a new treatment for the wound.", claims: [SECONDARY], ageYears: [33, 62] },
      ]),
    },
  ],
});
