const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const assert = require('assert');
const { chromium } = require('@playwright/test');

const here = __dirname, repo = path.resolve(here, '../../../../..');
const sourcePath = path.join(here, 'radiology-reading-proof.html');
const deliveryPath = 'C:/Users/rowla/.codex/visualizations/2026/09/22/01a0ca1d-9c4b-7921-847b-5a7b20244b12/radiology-reading-room-proof.html';
const fragment = fs.readFileSync(sourcePath, 'utf8');
const layout = JSON.parse(fs.readFileSync(path.join(here, '../layout-study/layout.json'), 'utf8'));
const seats = JSON.parse(fs.readFileSync(path.join(here, '../layout-study/seat-sources.json'), 'utf8'));
const assets = JSON.parse(fs.readFileSync(path.join(here, 'asset-contract.json'), 'utf8'));
const prepared = JSON.parse(fs.readFileSync(path.join(here, 'processed-assets/metadata.json'), 'utf8'));
const manifest = JSON.parse(fs.readFileSync(path.join(here, 'proof-manifest.json'), 'utf8'));
const handoff = JSON.parse(fs.readFileSync(path.join(here, 'handoff-contract.json'), 'utf8'));
const chrome = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const sha = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex').toUpperCase();

assert(!/<!doctype|<html|<head|<body/i.test(fragment)); assert(!/fetch\s*\(|XMLHttpRequest|WebSocket/.test(fragment)); assert(Buffer.byteLength(fragment) < 1_000_000);
assert.equal(assets.status, 'provisional-owner-review'); assert.equal(assets.approval, null); assert.equal(assets.runtimeIntegrationAuthorized, false);
assert.equal(handoff.status, 'provisional-owner-review'); assert.equal(handoff.approval, null); assert.equal(handoff.runtimeIntegrationAuthorized, false); assert.equal(handoff.defaultOccupancy, 'empty');
assert.equal(manifest.approval, null); assert.equal(manifest.runtimeIntegrationAuthorized, false); assert.equal(manifest.fragmentBytes, Buffer.byteLength(fragment)); assert.equal(manifest.fragmentSha256, sha(sourcePath)); assert.equal(manifest.deliverySha256, sha(deliveryPath)); assert.equal(sha(sourcePath), sha(deliveryPath));
for (const source of Object.values(assets.sources)) assert.equal(sha(path.resolve(here, source.file)), source.sha256);
assert.equal(prepared.specs.island.worktopRisePixels, 80); for (const id of layout.seats.map(x => `chair-${x.id}`)) assert.equal(prepared.specs[id].seatRisePixels, 45);

const registryPath = path.join(repo, 'apps/player/src/art/characterStillRegistry.generated.json'), registryHash = sha(registryPath), registry = JSON.parse(fs.readFileSync(registryPath, 'utf8')), registryEntries = new Map();
for (const character of registry.characters) for (const family of Object.values(character.poses || {})) for (const pose of Object.values(family || {})) if (pose.url && pose.sha256) registryEntries.set(pose.url.toLowerCase(), pose.sha256.toUpperCase());
for (const [id, seat] of Object.entries(seats.seats)) { const file = path.join(repo, 'apps/player/public', seat.asset); assert.equal(sha(file), seat.sha256.toUpperCase(), `${id} source hash`); assert.equal(registryEntries.get(seat.asset.toLowerCase()), seat.sha256.toUpperCase(), `${id} current registry`); }

const level3 = path.join(repo, 'tools/room-design/level-3'), level3Hashes = {
  'ambulatory-or/proof/ambulatory-or-proof.html': '98759E8F0C2ACF681B469D47F84B6F447B52D1D0FD24DBF5E37AEF9F59C90C56',
  'laboratory/proof/laboratory-proof.html': '1A2D3AE0A8A0623114B52F3D23D56956AC5E21C8E38E496535060766488A4C95',
  'pharmacy/proof/pharmacy-proof.html': 'F2775A9104E494E7F9F51E3424054DAC4CE4A91969266799CA0CD6A03CD00C1C',
  'maintenance-workshop/proof/maintenance-workshop-proof.html': 'A7C8D8BFAC5F5087B795B96EA67D2E3E0DAB7C1BF536701F586945213CFBE439',
  'staff-break-room/proof/staff-break-room-proof.html': 'FD4DE2CA6EAF353AA52D5BAFB2D8C1E9C42C5E3F15498F35DA1433905A71ACFC',
  'surgeons-office/proof/surgeons-office-proof.html': 'AE268AD14EC7F6A9365031C4C7FA45AFFC9F4E1C5AA69CDF077EA9C5E0E375C5',
  'vending/proof/vending-proof.html': '939A3CFA901891DBFED1578B7CA68819844BB821A7E3E01174347DB6B959573B'
};
for (const [file, expected] of Object.entries(level3Hashes)) assert.equal(sha(path.join(level3, file)), expected, `${file} frozen`);

const css = `<style>:root{--background:#f4f4ef;--foreground:#202624;--muted-foreground:#5c6560;--primary:#345c55;--primary-foreground:#fff;--border:#c6cbc8;--input:#c6cbc8;--ring:#557a72;font-family:Arial,sans-serif}body{margin:0;padding:16px;background:var(--background);color:var(--foreground)}button,select,input{font:inherit}.viz-controls{display:flex;flex-wrap:wrap;align-items:center;gap:10px;margin:8px 0}.viz-row{display:flex;flex-wrap:wrap;gap:12px}.viz-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(54px,1fr));gap:6px}.btn{min-height:40px;padding:6px 10px;border:1px solid var(--border);background:transparent;color:var(--foreground);border-radius:6px}.btn[aria-pressed=true]{background:var(--primary);color:var(--primary-foreground)}.form-label{display:grid;gap:4px}.form-select{min-height:40px;padding:5px;border:1px solid var(--input);background:var(--background);color:var(--foreground)}.form-check{display:inline-flex;gap:6px;align-items:center}.text-small{font-size:12px}.text-muted{color:var(--muted-foreground)}</style>`;
const boot = state => `<script>window.__saved=[];window.openai={widgetState:${JSON.stringify(state || null)},setWidgetState:async value=>{window.__saved.push(value);window.openai.widgetState=value}};</script>`;
const get = page => page.locator('#reading-art').evaluate(node => JSON.parse(node.dataset.model));
const set = (page, values) => page.evaluate(values => { const q = window.__radiologyReadingProof; for (const [key, value] of Object.entries(values)) q.state[key] = key === 'doors' || key === 'adjacent' ? new Set(value) : value; document.querySelector('#reading-scale-wrap').hidden = !q.state.scale; q.render(); }, values);

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: chrome });
  const page = await browser.newPage({ viewport: { width: 760, height: 1300 } }), errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.setContent(css + boot() + fragment); await page.waitForFunction(() => document.querySelector('#reading-art')?.dataset.model, null, { timeout: 30000 });
  assert.equal(await page.evaluate(() => window.__saved.length), 0, 'no save on load'); let model = await get(page);
  assert.deepStrictEqual({ cols: model.dimensions.cols, rows: model.dimensions.rows }, { cols: 4, rows: 4 }); assert.equal(model.segments.length, 16); assert.equal(new Set(model.segments).size, 16); assert.deepStrictEqual(model.optionalWallFixtures, []); assert.deepStrictEqual(model.hidden, []);
  assert.equal(Object.keys(model.fixtures).length, layout.solidFurniture.length); for (const fixture of Object.values(model.fixtures)) { assert.equal(fixture.collision, 'solid'); assert.equal(fixture.persistence, 'permanent'); }
  assert.deepStrictEqual(model.scaleContract, { tilePixels: 120, deskWorktopRisePixels: 80, chairSeatRisePixels: 45, actorRenderedWidths: { northwest: 121, northeast: 113, southeast: 116, southwest: 116 } }); assert.equal(model.floorPhase.fixedToRoom, true); assert.deepStrictEqual(model.floorPhase.origin, [0, 0]);
  assert.deepStrictEqual(model.shell, { northTallTop: 52, northLowTop: 91, northLowHeight: 29, sideCapWidth: 22 });
  assert.deepStrictEqual(model.layerOrder, ['shell','screen-glow','chairs','island-base','northwest-actor','northwest-desk-front','northeast-actor','southeast-divider-front','southwest-actor','southwest-desk-front','southeast-actor','southeast-chair-front','ambient-shade']); assert.equal(model.occupancy, 'empty'); assert.equal(Object.keys(model.actors).length, 0);
  for (const seat of layout.seats) { const chair = model.fixtures[seat.fixture].footprint; assert(seat.seatContact.x >= chair.left && seat.seatContact.x <= chair.left + chair.width && seat.seatContact.y >= chair.top && seat.seatContact.y <= chair.top + chair.height); }
  const routeAudit = await page.evaluate(() => { const q = window.__radiologyReadingProof, routes = q.routes(); return { doors: Object.fromEntries(Object.entries(routes.doors).map(([id, route]) => [id, route])), seats: routes.seats }; });
  assert(Object.values(routeAudit.doors).every(route => route.length)); assert(Object.values(routeAudit.seats).every(route => route.length));
  const browserRouteAudit = await page.evaluate(() => { const q = window.__radiologyReadingProof, check = (route, omit) => { if (!route.length) return false; for (let i = 1; i < route.length; i++) { const a = route[i - 1], b = route[i], n = Math.ceil(Math.hypot(b.x - a.x, b.y - a.y) / .005); for (let j = 0; j <= n; j++) if (!q.valid({ x: a.x + (b.x - a.x) * j / n, y: a.y + (b.y - a.y) * j / n }, omit)) return false; } return true; }, routes = q.routes(); return { doors: Object.fromEntries(Object.entries(routes.doors).map(([id, route]) => [id, check(route)])), seats: Object.fromEntries(Object.entries(routes.seats).map(([id, route]) => [id, check(route, `${id}Chair`)])) }; });
  assert(Object.values(browserRouteAudit.doors).every(Boolean)); assert(Object.values(browserRouteAudit.seats).every(Boolean));
  const expectedGroups = { '#reading-door-north': ['N1','N2','N3','N4'], '#reading-door-south': ['S1','S2','S3','S4'], '#reading-door-west': ['WA','WB','WC','WD'], '#reading-door-east': ['EA','EB','EC','ED'] };
  assert.equal(await page.locator('#reading-door-grid button[data-segment]').count(), 16); for (const [selector, ids] of Object.entries(expectedGroups)) assert.deepStrictEqual(await page.locator(`${selector} button`).evaluateAll(buttons => buttons.map(button => button.dataset.segment)), ids, selector);
  await page.locator('#reading-art').evaluate(node => { const q = window.__radiologyReadingProof, ctx = node.getContext('2d'); ctx.getImageData(98, 52, 524, 68); q.render(); window.__initialReadingShellPixels = ctx.getImageData(98, 52, 524, 68).data.slice(); }); const shellPixelsMatchInitial = () => page.locator('#reading-art').evaluate(node => { const current = node.getContext('2d').getImageData(98, 52, 524, 68).data, initial = window.__initialReadingShellPixels; return current.length === initial.length && current.every((value,index) => value === initial[index]); }); const backingInput = page.locator('[data-backing="N1"]'); await backingInput.focus(); await page.keyboard.press('Space'); model = await get(page); assert.deepStrictEqual(model.adjacency, ['N1']); assert.equal(await shellPixelsMatchInitial(), false); await page.keyboard.press('Space'); assert.equal(await shellPixelsMatchInitial(), true, 'keyboard uncheck restores exact north-shell pixels');
  for (const id of model.segments) { await set(page, { doors: [], adjacent: [] }); const button = page.locator(`[data-segment="${id}"]`); await button.focus(); await page.keyboard.press('Enter'); model = await get(page); assert.deepStrictEqual(model.doors, [id]); assert.deepStrictEqual(model.hidden, []); assert.equal(Object.keys(model.fixtures).length, layout.solidFurniture.length); }
  const shellAudit = await page.evaluate(() => { const q = window.__radiologyReadingProof, canvas = document.querySelector('#reading-art'), ctx = canvas.getContext('2d'), ids = ['N1','N2','N3','N4'], centers = [180,300,420,540], rgba = (x,y) => [...ctx.getImageData(x,y,1,1).data], snap = () => ctx.getImageData(98, 52, 524, 68).data.slice(), equal = (a,b) => a.length === b.length && a.every((value,index) => value === b[index]); q.state.occupancy = 'empty'; q.state.doors = new Set(); q.state.adjacent = new Set(); q.render(); snap(); q.render(); const baselinePixels = snap(), baseline = { upper: centers.map(x => rgba(x,70)), lower: centers.map(x => rgba(x,100)), westCap: rgba(110,70), eastCap: rgba(610,70) }, singles = {}; ids.forEach((id,index) => { q.state.adjacent = new Set([id]); q.render(); const changed = { upper: centers.map(x => rgba(x,70)), lower: centers.map(x => rgba(x,100)), westCap: rgba(110,70), eastCap: rgba(610,70) }; q.state.adjacent = new Set(); q.render(); changed.restored = equal(snap(), baselinePixels); singles[id] = changed; }); q.state.adjacent = new Set(ids); q.render(); const allBackedDiffers = !equal(snap(), baselinePixels); q.state.adjacent = new Set(['N2']); q.state.doors = new Set(); q.render(); const closedBacked = { upper: rgba(300,70), lower: rgba(300,100) }; q.state.doors = new Set(['N2']); q.render(); const openBacked = { upper: rgba(300,70), lower: rgba(300,100) }; q.state.adjacent = new Set(); q.render(); const openTall = { upper: rgba(300,70), lower: rgba(300,100) }; q.state.doors = new Set(); q.render(); return { baseline, singles, allBackedDiffers, closedBacked, openBacked, openTall, finalRestored: equal(snap(), baselinePixels) }; });
  for (const [id, sample] of Object.entries(shellAudit.singles)) { const index = Number(id.slice(1)) - 1; assert.notDeepStrictEqual(sample.upper[index], shellAudit.baseline.upper[index], `${id} closed backing collapses its upper wall`); assert.deepStrictEqual(sample.lower[index], shellAudit.baseline.lower[index], `${id} keeps its low wall`); for (let i = 0; i < 4; i++) if (i !== index) { assert.deepStrictEqual(sample.upper[i], shellAudit.baseline.upper[i], `${id} leaves N${i + 1} upper wall`); assert.deepStrictEqual(sample.lower[i], shellAudit.baseline.lower[i], `${id} leaves N${i + 1} low wall`); } assert(sample.restored, `${id} uncheck restores exact canvas bytes`); }
  assert.notDeepStrictEqual(shellAudit.singles.N1.westCap, shellAudit.baseline.westCap); assert.notDeepStrictEqual(shellAudit.singles.N4.eastCap, shellAudit.baseline.eastCap); assert(shellAudit.allBackedDiffers); assert.deepStrictEqual(shellAudit.openBacked.upper, shellAudit.closedBacked.upper); assert.notDeepStrictEqual(shellAudit.openBacked.lower, shellAudit.closedBacked.lower); assert.equal(shellAudit.openBacked.lower[3], 0); assert.equal(shellAudit.openTall.upper[3], 0); assert.equal(shellAudit.openTall.lower[3], 0); assert(shellAudit.finalRestored);
  for (const occupancy of ['empty', ...layout.seats.map(x => x.id), 'all']) { await page.selectOption('#reading-occupancy', occupancy); model = await get(page); assert.equal(model.occupancy, occupancy); assert.equal(Object.keys(model.actors).length, occupancy === 'empty' ? 0 : occupancy === 'all' ? 4 : 1); if (layout.seats.some(x => x.id === occupancy)) assert.equal(model.actors[occupancy].facing, layout.seats.find(x => x.id === occupancy).facing); }
  const savesBeforeGlobals = await page.evaluate(() => window.__saved.length); await page.evaluate(() => window.dispatchEvent(new CustomEvent('openai:set_globals', { detail: { globals: { widgetState: { privateContent: { selected: 'N4', doors: ['N4','BAD'], adjacent: ['N4','BAD'], occupancy: 'northwest', routes: true, scale: true } } } } }))); model = await get(page); assert.deepStrictEqual(model.doors, ['N4']); assert.deepStrictEqual(model.adjacency, ['N4']); assert.equal(model.occupancy, 'northwest'); assert.equal(await page.evaluate(() => window.__saved.length), savesBeforeGlobals, 'no save on globals'); assert(await page.locator('#reading-scale-wrap').isVisible());
  const compareBounds = { island: { left: 200 - prepared.specs.island.anchor[0] * prepared.specs.island.renderScale, top: 380 - prepared.specs.island.anchor[1] * prepared.specs.island.renderScale, right: 200 + (prepared.specs.island.width - prepared.specs.island.anchor[0]) * prepared.specs.island.renderScale, bottom: 380 + (prepared.specs.island.height - prepared.specs.island.anchor[1]) * prepared.specs.island.renderScale } }; assert(compareBounds.island.left >= 0 && compareBounds.island.top >= 0 && compareBounds.island.right <= 960 && compareBounds.island.bottom <= 420);
  const seCoverage = await page.evaluate(async ({ src, scale, ground, blocker }) => { const image = new Image(); image.src = src; await image.decode(); const cv = document.createElement('canvas'); cv.width = image.naturalWidth; cv.height = image.naturalHeight; const cg = cv.getContext('2d', { willReadFrequently: true }); cg.drawImage(image, 0, 0); const data = cg.getImageData(0, 0, cv.width, cv.height).data; let opaque = 0, uncovered = 0; for (let sy = 840; sy <= 850; sy++) for (let sx = 1145; sx <= 1304; sx++) if (data[(sy * cv.width + sx) * 4 + 3] >= 160) { opaque++; const x = ground[0] + (sx - 760) * scale / 120, y = ground[1] + (sy - 1004) * scale / 120; if (!(x >= blocker.left && x <= blocker.left + blocker.width && y >= blocker.top && y <= blocker.top + blocker.height)) uncovered++; } return { opaque, uncovered }; }, { src: `data:image/png;base64,${fs.readFileSync(path.resolve(here, assets.sources.island.file)).toString('base64')}`, scale: prepared.specs.island.renderScale, ground: prepared.specs.island.worldGround, blocker: layout.solidFurniture.find(x => x.id === 'southeastDeskFloorBase').footprint }); assert(seCoverage.opaque > 0); assert.equal(seCoverage.uncovered, 0, JSON.stringify(seCoverage));
  await page.setViewportSize({ width: 320, height: 1400 }); const narrow = await rootMetrics(page); assert(narrow.root <= 320 && narrow.scroll <= narrow.client && narrow.canvas <= 320, JSON.stringify(narrow)); assert.equal(await page.locator('#reading-scale-wrap .viz-row span').count(), 3); const narrowGroups = await page.locator('.reading-door-buttons').evaluateAll(groups => groups.map(group => { const box = group.getBoundingClientRect(), children = [...group.children].map(child => child.getBoundingClientRect()); return { count: children.length, client: group.clientWidth, scroll: group.scrollWidth, contained: children.every(child => child.left >= box.left && child.right <= box.right) }; })); assert.equal(narrowGroups.length, 4); assert(narrowGroups.every(group => group.count === 4 && group.scroll <= group.client && group.contained), JSON.stringify(narrowGroups));
  const toggleMs = await page.evaluate(() => { const t = performance.now(); window.__radiologyReadingProof.toggle('S4'); return performance.now() - t; }); assert(toggleMs < 250); assert.equal(errors.length, 0, errors.join(' | '));
  await browser.close(); console.log(`PASS 16 door routes/singles, 4 independent backings, empty/4 individual/all seats, .005 interpolation, SE lower-base opaque ${seCoverage.opaque}/${seCoverage.opaque} covered, widget/keyboard/320/comparison, registry ${registryHash}; toggle ${toggleMs.toFixed(1)}ms`);
})().catch(error => { console.error(error.stack || error); process.exit(1); });

async function rootMetrics(page) { return page.locator('#radiology-reading-proof').evaluate(root => ({ root: root.getBoundingClientRect().width, scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth, canvas: root.querySelector('.reading-stage').getBoundingClientRect().width })); }
